### ISSUE TITLE
Component library logging warnings

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#1002]
Noticed there are quite a few (66 😬) warnings popping up from the component library. These should be fixed so we notice if we introduce any new ones. Most of them seem quite minor and I don't think it would take too long to fix all of them.

![image](https://user-images.githubusercontent.com/1206987/62602605-c5b8c200-b8fc-11e9-9340-aa5b8398fd6f.png)

**Comment by euanmillar** [comment]
Component lib is being replaced in the next version
