### ISSUE TITLE
Remove @ts-ignore comments

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#1016]
This comment should only be used in very rare cases, when even using `any` isn't enough. Any should also be used sparingly, as it makes our code more difficult to understand and less safe. 

There are currently 375 places where this comment is used. As time goes by, these will eventually make the codebase very difficult to refactor as we've lost the help of the compiler to tell us if we've left something unrefactored by accident. 

The use in test suites might possible be fine, but I'd advice against that as well, as tests are inherently hard to debug, even more so without types.

Let's not add more of these and pay more attention to them in code reviews. Eventually we should be able to get to a point where everyone's so familiar with TypeScript, that no more of these are needed.

**Comment by euanmillar** [comment]
We are all very rarely using this now.
