### ISSUE TITLE
Add response types to QueryProvider

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#1061]
As we now have a centralized way of querying data from the backend, we could also define better types for responses that we're expecting the backend to return. 

So instead of getting

```
<QueryProvider
  event={event}
  action={Action.LOAD_CERTIFICATE_APPLICATION}
  payload={{ id: applicationId }}
>
  <QueryContext.Consumer>
    {({ loading, error, data, dataKey }) => {
```

where `data` is typed as `any`, we could define QueryProvider so that data would have a type based on the supplied `event` and `action` parameters.

**Comment by euanmillar** [comment]
Moved to: https://github.com/opencrvs/opencrvs-core/issues/1515
