### ISSUE TITLE
Update Traefik to v2.0

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#1098]
there are some breaking changes between the 1.7 version we are using so it just might be that traefik.toml and some docker compose files has to be updated

one https://docs.traefik.io/v2.0/migration/v1-to-v2/

**Comment by yeasinhossain-dsi** [comment]
Seems like merging with any version after 4th October, the gateway is restarting. Some thing happened after that date. needs investigation

**Comment by Zangetsu101** [comment]
@yeasinhossain-dsi The issue with the gateway service should be resolved with #4083. The develop has that PR merged in so we are good to go
