### ISSUE TITLE
Delete legacy application count increment script from core

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#1585]
1. Delete these two legacy routes, the corresponding route handlers and other code that's only used by them

https://github.com/opencrvs/opencrvs-core/blob/6924797ee63f1b1a3152953bb203765e0da3ceef/packages/metrics/src/config/routes.ts#L494-L512

**Comment by euanmillar** [comment]
We no longer need this handler and it should be removed:

https://github.com/opencrvs/opencrvs-core/blob/master/packages/metrics/src/features/legacy/handler.ts#L79

**Comment by Zangetsu101** [comment]
Done in #3702
