### ISSUE TITLE
User is not receiving any SMS notification with username and temporary password after creating a new user in the system

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#1595]
Waiting for Fahim’s help on SMS authorization

**Comment by mushrafulhoque-dsi** [comment]
Still waiting for Fahim's response

**Comment by mushrafulhoque-dsi** [comment]
I just created a new user in production for Joymonirhat UP and seems like user has received the new username and temporary password over SMS. So may not be a valid issue at all.

**Comment by euanmillar** [comment]
OK, sounds resolved. Lets close this.
