### ISSUE TITLE
Mobile Bottom Nav

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1659]
https://docs.google.com/presentation/d/1vEQL0hToCojds3fmbt39yd58-CK6iSVhAz9lwkn6Np8/edit#slide=id.g737b227b5c_0_275

**Comment by euanmillar** [comment]
I get access denied when I try to view the google doc. Can it be moved to the OpenCRVS shared drive please?

**Comment by euanmillar** [comment]
Closing as access still denied and I think this is part of a larger design refresh Epic TBC
