### ISSUE TITLE
Feature request: Field agent should see if the application sent was complete or incomplete

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1661]
AS a FA
I WANT to see what applications I sent incomplete or complete
SO THAT I can let applicants know

### Description

- Adds a label fro FA to see what applications they sent complete or incomplete

### Acceptance criteria

- GIVEN I am a FA
WHEN I send an application incomplete
THEN I can tell from the sent for review workqueue
- GIVEN I am a FA
WHEN I send an application complete
THEN I can tell from the sent for review workqueue

**Comment by euanmillar** [comment]
Converting from Epic to Issue: https://github.com/opencrvs/opencrvs-core/issues/2258
