### ISSUE TITLE
As a SysAdmin, I want to see operational data for the whole of a country, So that I can review the country performance

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1711]
### Description

- Adds Bangladesh as option in the administrative area search results
- Disable links to Field agent
- Disable link to Applications

### Acceptance criteria

GIVEN I am searching for an administrative area
WHEN I enter Bangladesh
THEN I can select Bangladesh.

### Design
https://www.figma.com/file/5FYzWuuVGaieaGV5HxqXyt/Performance?node-id=1294%3A0

### Dev-tasks

- [ ]  Task 1

**Comment by euanmillar** [comment]
Currently you get to these pages via an office search, and the national office in Cabinet Division should show registration data from Ward 20, Dhaka South City Corporation only.

So how would you navigate to here?

**Comment by jpye-finch** [comment]
Thought was to add 'Bangladesh' as an option in the Administrative and office search

**Comment by euanmillar** [comment]
Completed
