### ISSUE TITLE
UI - Filter buttons

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1714]
**Describe the bug**
Height 38px > 32px
Border width 1px > 2px

It seems the blue (view select) styled filter is built differently from the other filters. Its should be the same component just styled differently. 
The icon for the blue 'view select' button is 24x24px. Should be 18x18px. 

..ah it probably a style select from the form? I have created dialog that the same as that used for timePeriod and locationSearch:  https://www.figma.com/file/5FYzWuuVGaieaGV5HxqXyt/Performance?node-id=1286%3A5

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/f5eeb887-795a-4df0-a67c-2de3e557c775)

**Comment by euanmillar** [comment]
Hey @jpye-finch can we discuss this one?  I'm not too sure how to address this ticket

**Comment by euanmillar** [comment]
Anik has improved the styling of the current select which you will see when it goes into QA and I hope that when you see it you will find it acceptable alongside the other components. Its a styling of the common select component in use in the form with all the dynamic features we need for re-use and also it has all the mouse events as per HTML select standards.  I don’t think that we should build a custom select like this with the close button.  It would be a lot of work for really minimal value and bound to involve back and forth in QA as it is tested and amended on devices.  Plus we don’t have QA testing on a range of devices at present.
