### ISSUE TITLE
Toolbar not fixed

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1787]
**Describe the bug**
For system admin the tool bar is not sticky

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as System admin
2. Search for an administrative area
3. Scroll
4. The top tool bar disappears

**Expected behaviour**
It is fixed and the content scolls underneath

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/6aa508c4-56a0-48e3-ae57-84ec577d32b6)

**Comment by euanmillar** [comment]
@jpye-finch  this is the same header used elsewhere in the site.  Should it be fixed everywhere?

**Comment by jpye-finch** [comment]
It was oringally fixed across the site. So yep
