### ISSUE TITLE
font size and styling for registration rate widget

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1789]
**Describe the bug**
Not using the correct size and styling for the reg rate widget.
- Size 14 
- Stormy.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a Operational dashboard page
2. View the reg rate widget
3. its size 16 and grey

**Expected behaviour**
- Size 14, - Stormy.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/f15152e1-1652-48dc-acab-19e31753db16)

https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Specifications?node-id=14%3A7208

**Comment by euanmillar** [comment]
@jpye-finch This is a new text style that you have introduced.  If you refer to: https://www.figma.com/file/IbpqQSjnUjwA5smwe2HFwuVA/1.-Styles?node-id=96%3A21 

It becomes hard for us to ensure consistency if we don't update the Design System Figma file.

We also should move away from custom names like Big Body Bold and use standards like:

h5, h6, h7, h8 and then as developers we can use the standard HTML element in place and not make mistakes.  I noticed when performing UI updates on this page last sprint that this design was not aligned to the Design System fonts.  It explains why devs made errors as this font style doesnt exist in:

https://github.com/opencrvs/opencrvs-core/blob/master/packages/components/src/components/fonts.ts

I think that we should refactor the fonts to suit a standardisation of Typography names, but it would require you checking all the text in all the Figma files.  Figma does seem to me to need organising somewhat.

**Comment by euanmillar** [comment]
Please refer to colors:

https://www.figma.com/file/IbpqQSjnUjwA5smwe2HFwuVA/1.-Styles?node-id=96%3A53

Fonts:

https://www.figma.com/file/IbpqQSjnUjwA5smwe2HFwuVA/1.-Styles?node-id=96%3A21
