### ISSUE TITLE
Table heading columns are fixed in Application and Field agent detailed view

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1791]
**Describe the bug**
- I did not envision the table column headings being fixed. just the toolsbar (back button and filters)
- The toolbar on the Application detialed page starts to go off the page when you scroll outside of the table.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Application detialed page
2. Scroll inside the table
3. The column headings are fixed

**Expected behaviour**
the whole section below the toolbar scrolls. just like on any other page. Opes dashboard. Applications etc.
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/48741241-5204-4b9d-a17e-f63efedd6c5f)

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/c43e3bc0-b3fe-46a4-89bf-8f499ca08808)

**Comment by emon-swe-sust** [comment]
I think this bug doesn't exist on current version of the application
![ocrvs-1791](https://user-images.githubusercontent.com/43314141/146132226-639bbd2e-814b-4108-abec-264deaf90311.gif)
.

**Comment by emon-swe-sust** [comment]
I think this bug doesn't exist on current version of the application.
![ocrvs-1791](https://user-images.githubusercontent.com/43314141/146132522-ca79e4df-72d3-498d-821d-45bd7c4494a4.gif)
