### ISSUE TITLE
scroll bar thickness, margin, and show/hide

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1793]
**Describe the bug**
- Scroll bar is very thin -  difficult to drag with mouse
- No space between bottom table row
- The are alwys visible. I like when they appear only on scroll

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Applicaiton detialed view page
2. Scroll. 

**Expected behaviour**
- 8px thick
- 8px margin top and bottom - or left and right
- Show on scroll. 
- Hide when not scrolling

https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Specifications?node-id=14%3A8

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/8e713781-7195-4e1a-badf-6aec4bdb77bf)

**Comment by mushrafulhoque-dsi** [comment]
@euanmillar, it's gonna need a bit more RND to hide the scroll when it's not in use. So it seems like more than 0.5 task to me.
