### ISSUE TITLE
No sorting in Application and Field agent detialed views

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1794]
**Describe the improvement**
Unable to sort other columns

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Application or Field agent detaield view
2. No other columns can be sorted

**Expected behaviour**
You can sort any column
- names etc = (alphabeticlly)
- phone numbers (numerically)
- dates (oldest to newest)
- time durations ( longest to shortest) 

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/46ccc94a-5979-4b7e-8c15-fb6034bd0b97)

**Design**
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=14%3A8

**Comment by euanmillar** [comment]
@jpye-finch this is not a bug.  It is an improvement. If you look at the design not all the columns are sortable.![Screenshot 2020-06-24 at 10.55.26.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/cd299067-9eba-4ef3-9708-a1c8f7bd7608)

**Comment by euanmillar** [comment]
@jpye-finch  Can you check your designs, update as required and change the template to be a feature request?

**Comment by jpye-finch** [comment]
Ya, the design is. that we only bold and show arrow of the column that is sorted. 
True it wasn't in the AC how the other columns should be sorted
