### ISSUE TITLE
Only one ghost row in loading state for large tables

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1798]
**Describe the bug**
- There is only one roew in loading state for tables. 
- How about 16? So the whole page is mostly covered

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Applications or Field agent detailed view
2. Notice on load. one one ghost row shows when loading

**Expected behaviour**
Lets have 16 rows show. 

**Screenshots**
.

**Comment by euanmillar** [comment]
@jpye-finch can you send us a design for this please?
