### ISSUE TITLE
User Audit v1

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#1800]
### **Problem statement**
An audit currently can be done at a record level. However we don't have user centric view of all the actions they have performed. This first version of User Audit creates a User Profile page so auditor can review what they have done on each record. With v2 allowing them to see performance metrics. 

### **Proposed work**
- Create a user centric view of record audit
- The same 'Actions' tracked in record audit but from an user point of view
- So a list of all actions completed by a user on different records 
- Add user performance metrics to Field Agent, Registration Agent and Registrar profiles. 
- No restricting on access to User Audit page. eg. a Registrar can view another user from another jurisdiction. 

Design: https://www.notion.so/opencrvs/Audit-5ea0204d2b6c40858e772028784db864
Screens: https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=1%3A3694

### **Scope**

Summary list:
- Field Agent 
- Registration Agent
- Registrar
- National Registrar
- Local and National System Admin
- Performance Manager

History Action table
- Field Agent 
- Registration Agent
- Registrar
- National Registrar

### **Future work**
- add performance metrics see v2
- add system admin history action table

**Comment by euanmillar** [comment]
@rikukissa please add other technical logs you would like.  I am thinking we should also track device mac address via the PWA

**Comment by rikukissa** [comment]
**All events should record**: Datetime, User ID, IP Address, Device & browser, User location

**Additional items for user audit:**
- User logged in
- User logged out
- New user created (user id of the created user)
- User deactivated (user id of the deactivated user)
- Password changed
- Password / username recovery used
- Anything changed in profile settings
- System configuration changed

**Declarations:**
- Downloaded
- Archived
- Certified
- Registered
- Correction

- Performance management actions (track printed documents... to be defined)


@jpye-finch do the new events change how the table should be formatted? 
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications-v1?node-id=6971%3A128924

**Comment by jpye-finch** [comment]
Have started documenting it here:
https://www.notion.so/opencrvs/User-Audit-9b5377f3d8f54601b778080f4dfa5f6d

**Comment by anny320** [comment]
closed
