### ISSUE TITLE
Review duplicate/s declaration

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1804]
### **Problem statement **
Currently OpenCRVS only flags records that are potential duplicates. Making it hard for a Registrar to compare and assess if the declaration is a duplicate of a record that has already been registered. By providing a simple side by side comparison we can make it easier for the Registrar to make an informed decision.  
           
### **Proposed work**
- Create a potential duplicate review page
- Side by side comparison view of the flagged records
- Tabs to navigate to the different flagged records
- Declaration can be marked as not a duplicate and the Registrar can then go onto review it (Regsiter/send for updates)
- Declaration can be marked as a duplicate and archived

### **Success criteria**

- Registrar find it easy to compare the two records and make a decision
- 0 duplicate records are registered
### **User stories**

- As a Registrar, I want to compare a declaration against a flagged record 
- As a Registrar, I want to mark the record as a duplicate
- As a Registrar, I want to mark the record as not a duplicate
- As a user, I want to view if a record has been reviewed as a potential duplicate (Record/User audit)

### **Scope**
- reviewing a declaration against flagged records
- marking a duplicate
- marking as valid
- record audit history table reflects decision

### **Future work**
- smarter messaging about why it is a potential duplicate

**Comment by SyedaAfrida** [comment]
@jpye-finch @anny320 do we only expect Registrar to mark and view duplicate records from Ready to review menu? Previously RA could also see duplicate icon and warning message of duplicate records. Other thing, are we suppose to see the above mentioned functionalities only from ready to review menu, not from Requires Updates/ sent for approval?
