### ISSUE TITLE
AS a user I WANT to be able to change my phone number SO THAT my new mobile number is associated with my account

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#1809]
### Description

Allow user to update their mobile phone number so that they can continue using the application. 

https://www.figma.com/file/YsucvwEW6lGAOiW9jUp7Cyiw/7.-Settings?node-id=496%3A4979

- [x] Build the UI forms with mobile phone validation using the config setting regexp existing validation functions
- [x] GraphQL resolver in the gateway which can create a 6 - digit code store in Redis for validation.   GraphQL resolver to verify the 6 digit code.  Redis must be a dependency of gateway in package.json and URLs to Redis in Docker Compose files.  Should call notification service to send an SMS and user-mgnt service to change the phone number.

**Comment by SyedaAfrida** [comment]
When Phone number is changed from Team tab it is not updated in Settings page.
https://www.loom.com/share/70aabfaffd234cc5ab7d5fef0d9941a8

**Comment by euanmillar** [comment]
1. is so minor and should be a different bug

**Comment by euanmillar** [comment]
2.  As we do for download icons, when offline, disable the settings link and all the change links on Settings page

**Comment by anny320** [comment]
completed
