### ISSUE TITLE
Registrars should be able to submit an in-progress application too

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#1810]
### **Problem statement**

Applications started and saved mid-way through in an office environment are not visible in any performance data. 
Customers who visit the office and cannot complete the application on first visit with a registrar, do not receive a tracking ID.

### **Proposed work**

TBC

### **Success criteria**

TBC

### **User stories**

- As a customer who cannot complete the application at the office, I want to receive a tracking ID so that I can easily follow up on my next visit.

### **Scope**

TBC

### **Future work**

TBC

**Comment by euanmillar** [comment]
Is the solution to this that a registrar should be able to submit an in-progress application?  By doing so, the application gets a TrackingID as would be the case if a registration agent was doing this in the office.

**Comment by anninawersun** [comment]
Yes for the first user story. 
The second user story is related to the communications epic so we should add in there. We can add this in once we go through tomorrow

**Comment by euanmillar** [comment]
Moved the second story to the communications management epic

**Comment by euanmillar** [comment]
Closing as stale
