### ISSUE TITLE
As a user, I want to receive an SMS to inform me of any changes to my profile details and permissions, so that I am kept up to date

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#1811]
### Description

Users should receive updates when details associated with their profile are changed, along with detail of what has been changed. 

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

(Link to Figma)

### Copy

(Link to Notion)

### Dev-tasks??

- [ ]  Task 1

**Comment by euanmillar** [comment]
Closing as stale
