### ISSUE TITLE
Performance management v2

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#1813]
### **Problem statement**

- Users are unable to see indicators relating to quality of data so there is no way of making informed interventions to improve this. 
- Users are unable to view the individual performance of registrars
- Review the performance management view of records that never made it to registration
- review performance management breakdown of corrections
- A manager, at the national and local level, must know the average (monthly, weekly) number of registrations undertaken per registrar, or the average time that each type of vital event requires to be registered. These quantities may be used as benchmarks for monitoring the actual output of registrars and identifying areas for improvement, and for making adjustments to workloads or other administrative arrangements in order to improve services to the public.
- The ratio of registrars to the size of the population in each locality and the average distance to the local registration centre can also serve as useful indicators in the task of monitoring the capacity of the system to serve the entire population
- performance management breakdown for other actors including Registration Agents and Registrars

### **Proposed work**

- Define quality of data indicators and dashboard content to visualise this
- Individual Registrar performance review (like Reg Agent)

### **Success criteria**

(The criteria that must be met in order to consider this piece of work a success)

### **User stories**

(How the product should work for various user types)

-

### **Scope**

(Current requirements)

### **Future work**

(Future requirements)

**Comment by euanmillar** [comment]
Closing as stale and moved
