### ISSUE TITLE
As a user I want to be able to change the language of system operation when I login for the first time

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#1814]
### Description

User should be able to choose which language they want to operate the application in when they login.

https://www.figma.com/file/Eosd9SIfA3em0dlDMMd1gTPZ/1.-Login%2FOnboarding?node-id=1400%3A3214

- [ ] We should use the select in Performance to populate from available languages that you get in config variables

<img width="241" alt="Screenshot 2021-11-30 at 12 34 19" src="https://user-images.githubusercontent.com/3169954/144048450-b8484824-452e-48fd-bcd3-968fa2fdcaf1.png">

- [ ] Change the language approach can be copied from client app into login app.

**Comment by SyedaAfrida** [comment]
In Zambia there is currently support for one language. So cannot conduct test for this ticket.

**Comment by SyedaAfrida** [comment]
In Farajaland there is currently support for one language. So cannot conduct test for this ticket.

**Comment by SyedaAfrida** [comment]
@anny320 separate tickets are created reporting the bugs for this ticket. #2977 , #2950 & #2976

**Comment by euanmillar** [comment]
Changing language in Login app is not reflected in the client app

**Comment by anny320** [comment]
bug, when the language is changed, upon login the work queues do not get translated to french for farajaland ( eg in progress etc)
see recording belowhttps://images.zenhubusercontent.com/91778759/4d10ee6c-cf3e-48fa-9277-df5e153af3b7/french_translation_not_loading_in_work_queues.mp4

**Comment by euanmillar** [comment]
Something is not complete.  The language selection from Login must get communicated to the Client app so that client loads the right language that is selected in login.  In the URl, next to where we put the JWT, add another param language=en

**Comment by saima-alam** [comment]
@anny320 among the bug related to tickets #2950  #2976 is passed. #2977 is still not fixed.

**Comment by anny320** [comment]
completed
