### ISSUE TITLE
As a registrar I want to see the name of the child/deceased in the ready to review workqueue, so that I can easily distinguish between records

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1816]
### Description

- Replaces tracking ID with child/deceased name in Ready for Review workqueue
- Removes name from expanded view

### Acceptance criteria

GIVEN I am on the ready for review workqueue
THEN I can see the child/deceased name

GIVEN I have expanded a record
THEN I only see the d.o.b or d.o.d and case tracking

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=94%3A12

### Dev-tasks

- [ ]  Task 1

**Comment by euanmillar** [comment]
Can you link to a design please?

**Comment by mushrafulhoque-dsi** [comment]
Made the same changes for two queues:
- 'Ready for Review' workqueue for Registrar
- 'Sent for Approval' workqueue for Registration Clerk
