### ISSUE TITLE
Identity of deceased unknown

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#1826]
### **Problem statement**

There is no way of registering a death of an unidentifiable individual

### **Proposed work**

TBC

### **Success criteria**

(The criteria that must be met in order to consider this piece of work a success)

### **User stories**

(How the product should work for various user types)

-

### **Scope**

(Current requirements)

### **Future work**

(Future requirements)

**Comment by euanmillar** [comment]
Closing this as possible.
