### ISSUE TITLE
Add ICD10 coding

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#1828]
### Description

Research needed on different use cases

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

(Link to Figma)

### Copy

(Link to Notion)

### Dev-tasks??

- [ ]  Task 1

**Comment by euanmillar** [comment]
Closing as it is a duplicate of: https://github.com/opencrvs/opencrvs-core/issues/1837
