### ISSUE TITLE
Delegated authority

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#1829]
### **Problem statement**

Those responsible for registration e.g. Registrar are not always the ones conducting the actual work. 

### **Proposed work**

- A registrar can delegate authority to an agent in their office.
- System admin can delegate authority
- Delegated authority means a Registration agent can register applications and this is tracked and viewable by the Registrar.

### **Success criteria**

(The criteria that must be met in order to consider this piece of work a success)

### **User stories**

- GIVEN I am a registrar
WHEN I am on the team page
THEN I can see all the users in my team

- GIVEN I click on the sub menu icon
WHEN I that user is an agent
THEN I can see the delegate authority action button

- GIVEN I click on the sub menu icon
WHEN I that user is an agent
THEN I can see the delegate authority action button

### **Design**

https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1196%3A5

### **Scope**

(Current requirements)

### **Future work**

(Future requirements)

**Comment by euanmillar** [comment]
Some technical notes:

1. When registering as a reg agent with delegated authority, we must insert a new task type into history of something like "APPROVAL_TO_REGISTER_WITH_DEL_AUTH" before the register step that tracks that "The registration agent approved this application to be registered with delegated authority"

**Comment by eduffus** [comment]
Requires a legal basis to be implementable. Once we have a country that wants this we can build.

**Comment by euanmillar** [comment]
Closing as stale and solved by #6455 and #6454
