### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#1830]
### **Problem statement**

We don't know what users like and don't like on an ongoing basis. 

### **Proposed work**

- Capture user feedback in application

### **Success criteria**

(The criteria that must be met in order to consider this piece of work a success)

### **User stories**

(How the product should work for various user types)

-

### **Scope**

(Current requirements)

### **Future work**

(Future requirements)

**Comment by euanmillar** [comment]
Closing as stale
