### ISSUE TITLE
Notification: product update

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#1832]
### Description

Inform users of what updates have been made to the product

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

(Link to Figma)

### Copy

(Link to Notion)

### Dev-tasks??

- [ ]  Task 1

**Comment by euanmillar** [comment]
Closing in favour of: https://github.com/opencrvs/opencrvs-core/issues/2273
