### ISSUE TITLE
feat: Foetal death registration

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#1833]
### **Problem statement**

(Describe the problem you're trying to solve by doing this work)]

https://www.notion.so/opencrvs/7d321101427640088c305b8bf630aa21?v=cd71becb0d0e4c14a13e67ba38fba1ac&p=2f5b0f88686e4cd08f2f18921d923b7d&pm=s

### **Proposed work**

(High-level overview of what we're building and why we think it will solve the problem).

### **Success criteria**

(The criteria that must be met in order to consider this piece of work a success)

### **User stories**

(How the product should work for various user types)

-

### **Scope**

(Current requirements)

### **Future work**

(Future requirements)

**Comment by jpye-finch** [comment]
Configuration of Event v2
