### ISSUE TITLE
User Notifications

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#1834]
### **Problem statement**

Users do not always know that they have things to do - push notifications can encourage/remind them to take action. 

### **Proposed work**

(High-level overview of what we're building and why we think it will solve the problem).

### **Success criteria**

(The criteria that must be met in order to consider this piece of work a success)

### **User stories**

- AS a user
I WANT to be notified of new items I need to review, achievements and like
SO THAT I stay on top of my job and can see my performance

### **Scope**

(Current requirements)

### **Future work**

(Future requirements)

**Comment by euanmillar** [comment]
Closing in favour of: https://github.com/opencrvs/opencrvs-core/issues/2273
