### ISSUE TITLE
Self-Informant birth registration

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#1835]
### **Problem statement**

Someone might want to apply for a birth certificate themselves (no other applicant). 

### **Proposed work**

(High-level overview of what we're building and why we think it will solve the problem).

### **Success criteria**

(The criteria that must be met in order to consider this piece of work a success)

### **User stories**

(How the product should work for various user types)

-

### **Scope**

(Current requirements)

### **Future work**

(Future requirements)

**Comment by euanmillar** [comment]
Closing as duplicate
