### ISSUE TITLE
As a user, I want to confirm I want to delete an in-progress delcaration, so that I don't delete it by accident. 

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#1836]
### Description
- AddS confirmation modal to flow when user selects to delete in-progress application. 

### Acceptance criteria

GIVEN I started an in-progress declaration
WHEN I click delete (••• menu option)
THEN show confirmation model

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=7024%3A136453

### Dev-tasks

- [ ]  Task 1

**Comment by euanmillar** [comment]
@jpye-finch I assume you mean, when you click on the cross button on the top right corner when creating a draft right?

**Comment by euanmillar** [comment]
When you click here ... ![Screenshot 2022-08-02 at 11.43.46.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/b835fe3a-2bc8-482f-bcc7-1acff0ed3c07)

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/193813743-e2cb2064-7684-43ca-a61f-4bad138f6daa.mp4

**Comment by anny320** [comment]
completed
