### ISSUE TITLE
Assign CoD code to existing registration record

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#1837]
### **Problem statement**

ICD coding is not always done promptly, so the information may not appear in the original notification to OpenCRVS. If the coding is done at a later stage, this should be associated with the record. 

### **Proposed work**

(High-level overview of what we're building and why we think it will solve the problem).

### **Success criteria**

(The criteria that must be met in order to consider this piece of work a success)

### **User stories**

(How the product should work for various user types)

-

### **Scope**

(Current requirements)

### **Future work**

(Future requirements)

**Comment by eduffus** [comment]
There is some pushback from the health sector about introducing ICD10/11 coding directly into the CRVS system. They argue this should be handled within the health system. Requires more inputs...

**Comment by euanmillar** [comment]
Closing as stale.
