### ISSUE TITLE
Dash (-) instead of 00:00:00 

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1847]
**Describe the bug**
Design showied just a dash (-) instead of 00:00:00 for 'time period' columns that the appplication is not in. To increase visability and usability.
 
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Current application in workflow
2. View the time in 'x'
3. 00:00:00 shows for columns 

**Expected behaviour**
The cell is [    -    ] if the time period is 00:00:00.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/c92190d5-4972-4bf7-838a-3c191daa1a55)

![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/d27fc997-abd4-4d7e-9984-11fc371ed0a9)

**Comment by euanmillar** [comment]
Apply to both:

Field Agents and Application Status tables wherever time is 0

**Comment by SyedaAfrida** [comment]
@jpye-finch From second screenshot we can see that "Time in progress" is set to 00:00:00:00. Should that be also dash (-) instead of 00:00:00:00 ?

**Comment by anny320** [comment]
completed
