### ISSUE TITLE
IconButton missalignment in workqueue

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1848]
**Describe the bug**
Button icon is not centered align

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to workqueue

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/6b130dc9-a291-4a1c-af17-59e96e2b4041)

**Comment by emon-swe-sust** [comment]
I think this bug doesn't exist on current application
![Screenshot from 2021-12-21 11-55-08](https://user-images.githubusercontent.com/43314141/146878893-5587d81a-feda-4340-a1af-c96e5b5796e5.png)
.

**Comment by SyedaAfrida** [comment]
not reproducable
