### ISSUE TITLE
Update to columns in Current applications in Workflow page

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1850]
### Description

- Combine Childs name into one cell. (English name, Benglai name)
- Add Applicant name column (Name and relationship)
- update Main Contact to align format. (Number and relationship)

### Acceptance criteria

GIVEN
WHEN
THEN

GIVEN
WHEN
THEN

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=437%3A13412

### Dev-tasks

- [ ]  Task 1

**Comment by anninawersun** [comment]
@euanmillar is this still relevant? Looks Bangladesh specific...

**Comment by euanmillar** [comment]
@anninawersun  I think this still relevant.  All available languages names should be in the same cell.  But I dont know how to test because Zambia only has one language
