### ISSUE TITLE
Performance tab search bar shows no validations

### ISSUE THREAD

**Issue by SabitIbnAliKhan** [opencrvs/opencrvs-core#1871]
**Description of the bug**

In the Performance tab. the Search bar is showing no validation for number / special character / unlisted area name / empty search

**To Reproduce**

1. Go to 'Performance'
2. Click on 'Search bar'
3. Type in a number / special character / unlisted area name / keep empty
4. Click 'Search'
5. No validation is shown

**Expected behavior**
A form of validation has to be shown when attempting to search for invalid data 

**Screenshots**
![performance_location search](https://user-images.githubusercontent.com/44313971/89529108-f54f2280-d80d-11ea-87d7-c3f252e4421a.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 84.0.4147.105

**Comment by noboshashabnom-dsi** [comment]
**Note:** Same for performance and Team tab search option.

**Comment by euanmillar** [comment]
Error message should say:

"No results found"

In red beneath the input field.

**Comment by anny320** [comment]
closed
