### ISSUE TITLE
Rejected birth/death application is visible in "Sent for review" tab of a field agent.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1872]
**Summary**
Register rejected a birth/death application and it is visible in "Sent for review" tab of a field agent.

**Steps To Reproduce:**
1. Log into openCRVS as a field agent.
2. Create a birth & death application.
3. Sent for review both application.
4. Log in as a register in the system.
5. Observe both application in "Ready for review" tab.
6. Download > Review both application.
7. Click > Reject > select a reason & add comment. 
8. Now again, log in as field agent.
9. Observe the rejected applications in "Sent for review" tab and "Require Updates" tab.

**Actual Result:**
The rejected applications are visible in "Sent for review" tab which is not expected as it is already reviewed and is in "Require Updates" tab.

**Expected behavior:**
Rejected birth/death application should not be visible in "Sent for review" tab of a field agent's profile.

**Screenshots**
![BDR_count_tab2](https://user-images.githubusercontent.com/16021495/89529617-d7ce8880-d80e-11ea-9118-b9f388fad32d.png)
![BDR_count_tab1](https://user-images.githubusercontent.com/16021495/89529627-dbfaa600-d80e-11ea-8ebf-ec2753a0fa81.png)

**Desktop:**
 - OS: Windows 10 pro
 - Browser: Chrome 
 - Version 84.0.4147.105 

**Environment:** https://login.opencrvs.qa1.jembi.org/
**Additional context**
In Firefox 79.0 i have observed, only birth application is visible not death application after rejection in "Sent for review" tab.

Screen shot:
![BDR_count_tab3](https://user-images.githubusercontent.com/16021495/89530055-a7d3b500-d80f-11ea-9b66-532f7cdf40b3.png)

**Comment by noboshashabnom-dsi** [comment]
If the application is sent for ready to print by register; field agent can see the same application in ''Send for review" tab. 
![Ready for print_sent for update](https://user-images.githubusercontent.com/16021495/89646755-3282e580-d8de-11ea-8097-6ae222679965.png)

**Comment by euanmillar** [comment]
We need a new design ticket for: "If the application is sent for ready to print by register; field agent can see the same application in ''Send for review" tab."

**Comment by anny320** [comment]
completed
