### ISSUE TITLE
After log into the system an error shows in the console.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1873]
**Steps To Reproduce**
1. Log in to openCRVS as field agent or any other user role.
2. After logged into the system observe the console.

**Actual Result**
Error shows in console though it doesn't create any problem to use the system.
`
index.js:4377 Remote declared application merging not applicable
(anonymous) @ index.js:4377
e.<computed> @ build.umd.js:498
r @ cmd.js:149
Promise.then (async)
y @ cmd.js:162
g @ cmd.js:263
(anonymous) @ cmd.js:187
(anonymous) @ cmd.js:186
g @ cmd.js:269
d @ install.js:127
(anonymous) @ install.js:111
f @ install.js:149
(anonymous) @ redux.js:476
value @ FieldAgentHome.tsx:215
value @ FieldAgentHome.tsx:219
(anonymous) @ react-dom.production.min.js:6201
t.unstable_runWithPriority @ scheduler.production.min.js:266
Na @ react-dom.production.min.js:2740
bu @ react-dom.production.min.js:5985
au @ react-dom.production.min.js:5267
(anonymous) @ react-dom.production.min.js:2775
t.unstable_runWithPriority @ scheduler.production.min.js:266
Na @ react-dom.production.min.js:2740
za @ react-dom.production.min.js:2770
Ua @ react-dom.production.min.js:2760
su @ react-dom.production.min.js:5306
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:65
t.handleChangeWrapper @ Subscription.js:70
_ @ redux.js:220
(anonymous) @ index.umd.js:100
(anonymous) @ middleware.js:36
f @ install.js:146
(anonymous) @ cmd.js:195
(anonymous) @ cmd.js:194
Promise.then (async)
(anonymous) @ cmd.js:193
(anonymous) @ cmd.js:186
g @ cmd.js:269
d @ install.js:127
(anonymous) @ install.js:111
f @ install.js:149
(anonymous) @ cmd.js:195
(anonymous) @ cmd.js:194
Promise.then (async)
(anonymous) @ cmd.js:193
(anonymous) @ cmd.js:186
g @ cmd.js:269
(anonymous) @ cmd.js:187
(anonymous) @ cmd.js:186
g @ cmd.js:269
d @ install.js:127
(anonymous) @ install.js:111
f @ install.js:149
(anonymous) @ cmd.js:195
(anonymous) @ cmd.js:194
Promise.then (async)
(anonymous) @ cmd.js:193
(anonymous) @ cmd.js:186
g @ cmd.js:269
d @ install.js:127
(anonymous) @ install.js:111
f @ install.js:149
(anonymous) @ cmd.js:195
(anonymous) @ cmd.js:194
Promise.then (async)
(anonymous) @ cmd.js:193
(anonymous) @ cmd.js:186
g @ cmd.js:269
d @ install.js:127
(anonymous) @ install.js:111
f @ install.js:149
(anonymous) @ cmd.js:195
(anonymous) @ cmd.js:194
Promise.then (async)
(anonymous) @ cmd.js:193
(anonymous) @ cmd.js:186
g @ cmd.js:269
(anonymous) @ cmd.js:187
(anonymous) @ cmd.js:186
g @ cmd.js:269
d @ install.js:127
(anonymous) @ install.js:111
f @ install.js:149
(anonymous) @ redux.js:476
(anonymous) @ Page.tsx:148
l @ runtime.js:45
(anonymous) @ runtime.js:264
e.<computed> @ runtime.js:98
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Page.tsx:155
(anonymous) @ react-dom.production.min.js:6201
t.unstable_runWithPriority @ scheduler.production.min.js:266
Na @ react-dom.production.min.js:2740
bu @ react-dom.production.min.js:5985
au @ react-dom.production.min.js:5267
eu @ react-dom.production.min.js:5041
Wu @ react-dom.production.min.js:6934
Uu @ react-dom.production.min.js:6943
(anonymous) @ react-dom.production.min.js:7218
lu @ react-dom.production.min.js:5327
Xu @ react-dom.production.min.js:7217
render @ react-dom.production.min.js:7253
1613 @ index.tsx:87
f @ ?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJ2YWxpZGF0ZSIsImNlcnRpZnkiLCJkZW1vIl0sImlhdCI6MTU5NjcxNTk4MywiZXhwIjoxNTk3MzIwNzgzLCJhdWQiOlsib3BlbmNydnM6YXV0aC11c2VyIiwib3BlbmNydnM6dXNlci1tZ250LXVzZXIiLCJvcGVuY3J2czpoZWFydGgtdXNlciIsIm9wZW5jcnZzOmdhdGV3YXktdXNlciIsIm9wZW5jcnZzOm5vdGlmaWNhdGlvbi11c2VyIiwib3BlbmNydnM6d29ya2Zsb3ctdXNlciIsIm9wZW5jcnZzOnNlYXJjaC11c2VyIiwib3BlbmNydnM6bWV0cmljcy11c2VyIiwib3BlbmNydnM6cmVzb3VyY2VzLXVzZXIiXSwiaXNzIjoib3BlbmNydnM6YXV0aC1zZXJ2aWNlIiwic3ViIjoiNWUxNmU2NmUwYTJiMmYxZjA3MGMzN2EzIn0.nQGpRLPwB5CJY62RYsdT0kNF50gUjNE23bue3aLgke8sazhWd-tQo_NXigbiayyoVXWaZoSx-I4jmwnc3_2P7QWyRJa4aQ1JeBF89XUsuPrdtbDQCfI-QjokxHj0vB6RFGRaQWnXnMVzYd30dYh2yJgRKYtsNp9FJk7ee_6UmL5RTqt6_4rtLIH_0Jv_v9sG7iwb_afPoY5O2yQf3sL6WGjL0ejVILXC-i8EV7ZwJZ9qZfXjG0ynv7ZwMB_z0K58zPpcpNUr8SBg0j7RaHNPz_W5VMsIATSbr3_yXo691yZ8Gj8-UKIpDKvKHzi9R8TuJm9t1xlnY0ulKpWQpZ03oA:1
907 @ index.js:30
f @ ?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJ2YWxpZGF0ZSIsImNlcnRpZnkiLCJkZW1vIl0sImlhdCI6MTU5NjcxNTk4MywiZXhwIjoxNTk3MzIwNzgzLCJhdWQiOlsib3BlbmNydnM6YXV0aC11c2VyIiwib3BlbmNydnM6dXNlci1tZ250LXVzZXIiLCJvcGVuY3J2czpoZWFydGgtdXNlciIsIm9wZW5jcnZzOmdhdGV3YXktdXNlciIsIm9wZW5jcnZzOm5vdGlmaWNhdGlvbi11c2VyIiwib3BlbmNydnM6d29ya2Zsb3ctdXNlciIsIm9wZW5jcnZzOnNlYXJjaC11c2VyIiwib3BlbmNydnM6bWV0cmljcy11c2VyIiwib3BlbmNydnM6cmVzb3VyY2VzLXVzZXIiXSwiaXNzIjoib3BlbmNydnM6YXV0aC1zZXJ2aWNlIiwic3ViIjoiNWUxNmU2NmUwYTJiMmYxZjA3MGMzN2EzIn0.nQGpRLPwB5CJY62RYsdT0kNF50gUjNE23bue3aLgke8sazhWd-tQo_NXigbiayyoVXWaZoSx-I4jmwnc3_2P7QWyRJa4aQ1JeBF89XUsuPrdtbDQCfI-QjokxHj0vB6RFGRaQWnXnMVzYd30dYh2yJgRKYtsNp9FJk7ee_6UmL5RTqt6_4rtLIH_0Jv_v9sG7iwb_afPoY5O2yQf3sL6WGjL0ejVILXC-i8EV7ZwJZ9qZfXjG0ynv7ZwMB_z0K58zPpcpNUr8SBg0j7RaHNPz_W5VMsIATSbr3_yXo691yZ8Gj8-UKIpDKvKHzi9R8TuJm9t1xlnY0ulKpWQpZ03oA:1
a @ ?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJ2YWxpZGF0ZSIsImNlcnRpZnkiLCJkZW1vIl0sImlhdCI6MTU5NjcxNTk4MywiZXhwIjoxNTk3MzIwNzgzLCJhdWQiOlsib3BlbmNydnM6YXV0aC11c2VyIiwib3BlbmNydnM6dXNlci1tZ250LXVzZXIiLCJvcGVuY3J2czpoZWFydGgtdXNlciIsIm9wZW5jcnZzOmdhdGV3YXktdXNlciIsIm9wZW5jcnZzOm5vdGlmaWNhdGlvbi11c2VyIiwib3BlbmNydnM6d29ya2Zsb3ctdXNlciIsIm9wZW5jcnZzOnNlYXJjaC11c2VyIiwib3BlbmNydnM6bWV0cmljcy11c2VyIiwib3BlbmNydnM6cmVzb3VyY2VzLXVzZXIiXSwiaXNzIjoib3BlbmNydnM6YXV0aC1zZXJ2aWNlIiwic3ViIjoiNWUxNmU2NmUwYTJiMmYxZjA3MGMzN2EzIn0.nQGpRLPwB5CJY62RYsdT0kNF50gUjNE23bue3aLgke8sazhWd-tQo_NXigbiayyoVXWaZoSx-I4jmwnc3_2P7QWyRJa4aQ1JeBF89XUsuPrdtbDQCfI-QjokxHj0vB6RFGRaQWnXnMVzYd30dYh2yJgRKYtsNp9FJk7ee_6UmL5RTqt6_4rtLIH_0Jv_v9sG7iwb_afPoY5O2yQf3sL6WGjL0ejVILXC-i8EV7ZwJZ9qZfXjG0ynv7ZwMB_z0K58zPpcpNUr8SBg0j7RaHNPz_W5VMsIATSbr3_yXo691yZ8Gj8-UKIpDKvKHzi9R8TuJm9t1xlnY0ulKpWQpZ03oA:1
e @ ?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJ2YWxpZGF0ZSIsImNlcnRpZnkiLCJkZW1vIl0sImlhdCI6MTU5NjcxNTk4MywiZXhwIjoxNTk3MzIwNzgzLCJhdWQiOlsib3BlbmNydnM6YXV0aC11c2VyIiwib3BlbmNydnM6dXNlci1tZ250LXVzZXIiLCJvcGVuY3J2czpoZWFydGgtdXNlciIsIm9wZW5jcnZzOmdhdGV3YXktdXNlciIsIm9wZW5jcnZzOm5vdGlmaWNhdGlvbi11c2VyIiwib3BlbmNydnM6d29ya2Zsb3ctdXNlciIsIm9wZW5jcnZzOnNlYXJjaC11c2VyIiwib3BlbmNydnM6bWV0cmljcy11c2VyIiwib3BlbmNydnM6cmVzb3VyY2VzLXVzZXIiXSwiaXNzIjoib3BlbmNydnM6YXV0aC1zZXJ2aWNlIiwic3ViIjoiNWUxNmU2NmUwYTJiMmYxZjA3MGMzN2EzIn0.nQGpRLPwB5CJY62RYsdT0kNF50gUjNE23bue3aLgke8sazhWd-tQo_NXigbiayyoVXWaZoSx-I4jmwnc3_2P7QWyRJa4aQ1JeBF89XUsuPrdtbDQCfI-QjokxHj0vB6RFGRaQWnXnMVzYd30dYh2yJgRKYtsNp9FJk7ee_6UmL5RTqt6_4rtLIH_0Jv_v9sG7iwb_afPoY5O2yQf3sL6WGjL0ejVILXC-i8EV7ZwJZ9qZfXjG0ynv7ZwMB_z0K58zPpcpNUr8SBg0j7RaHNPz_W5VMsIATSbr3_yXo691yZ8Gj8-UKIpDKvKHzi9R8TuJm9t1xlnY0ulKpWQpZ03oA:1
(anonymous) @ main.3f793581.chunk.js:1
Show 38 more frames

`
**Expected behavior**
The error must be handled to not generate.

**Screenshots**
![Login Error](https://user-images.githubusercontent.com/16021495/89531013-53313980-d811-11ea-9e56-528310b4fe9f.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome Version 84.0.4147.105 & FF version 79.0

**Environment**
https://login.opencrvs.qa1.jembi.org/

**Comment by Zangetsu101** [comment]
https://stackoverflow.com/questions/38733144/why-does-my-es6-promise-rejection-need-to-be-consumed-immediately-to-avoid-a-con

**Comment by Zangetsu101** [comment]
Adding `catch(() => { })` gets rid of the error but then the actual `failActionCreator` doesn't get called. I also tried adding an event listener for `unhandledrejection` to prevent the default behavior but that doesn't work for some reason.

**Comment by Fariha-Amin** [comment]
@anny320  Can be closed
![d](https://user-images.githubusercontent.com/105624748/171835138-617fb8fe-148f-4756-bf1d-fb130b6f9b2b.PNG)

**Comment by anny320** [comment]
completed
