### ISSUE TITLE
Print button flicks when cancel print option.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1874]
**Precondition to reproduce**
1. Create a birth/death application as any user role.
2. Register the application.

**Steps To Reproduce**
1. Log in as a register.
2. Go to "Ready to print" tab.
3. Click download icon.
4. Click "Print" button.
5. Select any option from Certificate collection page.
6. From payment required page click > continue
7. From "Are all the details on the birth certificate correct?" page > Click 'Continue and print' button.
8. From confirmation modal "Print Certificate?" click > print 
9. A new tab open up and print modal open.
10. Click 'Cancel' in the print modal and Close the tab.
11. Observe the  "Ready to print" tab

**Actual Result**
In "Ready to print" tab the print button flicks and “1 application processing” shows below the page.

**Expected behavior**
The print button should not flick and the 'application processing' option should be handled to cancel as user canceled it. 

**Screenshots and video**
![Print_cancel](https://user-images.githubusercontent.com/16021495/89533813-ce94ea00-d815-11ea-96bc-6f4103ad296c.png)
![Print](https://user-images.githubusercontent.com/16021495/89533879-ed937c00-d815-11ea-8f9d-6e8fc6e7eb5d.png)

**Desktop:**
 - OS: Windows 10 pro
 - Browser: Chrome 84.0 & FF 79.0

**Environment**
https://login.opencrvs.qa1.jembi.org/

**Additional context**
No

**Comment by emon-swe-sust** [comment]
I ain't able to reproduce the issue, I guess may be this issue didn't exist on current version.

**Comment by anny320** [comment]
issue now closed.
