### ISSUE TITLE
"Birth and Death registration rate within 45 days of event" not updating 

### ISSUE THREAD

**Issue by SabitIbnAliKhan** [opencrvs/opencrvs-core#1878]
**Describe the bug**
In the Performance tab. the "Birth and Death registration rate within 45 days of event"  is not updating when new births and deaths are being registered. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Observe the "Birth and Death registration rate within 45 days of event" numbers in the Performance tab
2. Create and Register a Birth and a Death application
3.  Go to Performance tab
4.  Observe that the numbers did not update 

**Expected behaviour**
The numbers in the "Birth registration rate within 45 days of event" should update when a new birth or death is registered 

**Screenshots**
![1878_1](https://user-images.githubusercontent.com/44313971/90018431-b8cc6c80-dcce-11ea-8ab9-c63dcc40578f.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 84.0.4147.105

**Comment by mushrafulhoque-dsi** [comment]
Unable to re-produce this. @SabitIbnAliKhan based on our discussion, please re-verify this issue.

**Comment by SabitIbnAliKhan** [comment]
Issue could not be recreated. Birth and Death registration rate within 45 days is updating as expected.
