### ISSUE TITLE
Registration related data based on selected time period 

### ISSUE THREAD

**Issue by SabitIbnAliKhan** [opencrvs/opencrvs-core#1879]
**Description of bug*
Unusual calculation shows when min to max time range is selected from calendar (Jan, 1900 to current) in Performance tab

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Performance' tab
2. Select maximum to minimum time range
3. Observe the registration data
4. Data seems to change incorrectly 

**Expected behaviour**
Correct calculation for the time range should be shown 

**Screenshots**
![Registration calculaton (1)](https://user-images.githubusercontent.com/44313971/89543115-58e34b00-d822-11ea-9773-c61254c124ea.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 84.0.4147.105

**Comment by anninawersun** [comment]
@SabitIbnAliKhan what happens if we put a more recent date? does it work?

**Comment by SabitIbnAliKhan** [comment]
@anninawersun 
Please note in the picture below where the time period is Last 12 Months.
![1897_1](https://user-images.githubusercontent.com/44313971/93783332-637c6700-fc4d-11ea-870e-88ff8791b2c1.JPG)

And in the picture below, I changed the time to January 2017 to September 2020. If anything, the Total Started, Field Agents and Registration Offices number should increase when the time period is increased.  However, we see that it has decreased.
![1897_2](https://user-images.githubusercontent.com/44313971/93783348-66775780-fc4d-11ea-9a71-dbc08076d9bd.JPG)

**Comment by yeasinhossain-dsi** [comment]
This issue seems no longer re-produce able using Zambia resource package. Possibly a lagacy bug which is no longer valid.

So moving the ticket forward

**Comment by SyedaAfrida** [comment]
not reproducable
