### ISSUE TITLE
Login page UI issue after verification code timeout.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1883]
**Steps To Reproduce**
1. Open the login page
2. Provide user name and password
3. In the verification code page provide nothing and wait 10 minutes.
4. Now, provide verification code and hit submit.
5. Validation error shows for timeout.
6. Now click back button of the browser it takes to login page.

**Actual Result**
In login page a red box shows above the user name password.
![Pincode after a while shows wrong 2](https://user-images.githubusercontent.com/16021495/89616103-95a65500-d8a9-11ea-8d68-a338e05c336b.png)

**Expected behavior**
It shouldn't show.

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 84.0, FF 79.0

**Environment:** https://login.opencrvs.qa1.jembi.org/

**Comment by anny320** [comment]
closed
