### ISSUE TITLE
Unexpected text in the Birth and Death registration rate within 45 days of event page's right hand side 

### ISSUE THREAD

**Issue by SabitIbnAliKhan** [opencrvs/opencrvs-core#1884]
**Describe the bug**
It's showing like- Total{lineBreak}registered 7 {lineBreak}

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Performance'
2. Click on 'Birth registration rate within 45 days of event'
3. Observe the right hand side 
4. It is written  Total{lineBreak}registered 7 {lineBreak}

**Expected behaviour:
{lineBreak} should not be showing 

**Screenshots**
![linebreak](https://user-images.githubusercontent.com/44313971/89616862-eb2f3180-d8aa-11ea-8b98-3d57268b1924.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 84.0.4147.105

**Comment by noboshashabnom-dsi** [comment]
Tested and verified.
Looks fine now.
