### ISSUE TITLE
Alignment issues of all columns in Birth and Death registration rate within 45 days of event page

### ISSUE THREAD

**Issue by SabitIbnAliKhan** [opencrvs/opencrvs-core#1887]
**Describe the bug**
The data in the tables are not aligned with the column name 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Performance'
2. Click on 'Birth / Death registration rate within 45 days of event'
3. Observe the table of data 
4. Data is not aligned properly

**Expected behaviour**
The data should be aligned 

**Screenshots**

![30 days table alignment](https://user-images.githubusercontent.com/44313971/89618408-d7d19580-d8ad-11ea-89da-bb9969e6ebb8.png)

![alignment_45days event](https://user-images.githubusercontent.com/44313971/89618424-def8a380-d8ad-11ea-9465-6b7d268f5d97.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 84.0.4147.105

**Comment by noboshashabnom-dsi** [comment]
Tested and verified.
The alignment looks good now.
