### ISSUE TITLE
Sort function doesn't work inside report page.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1889]
**Steps To Reproduce**
1. Log in to system as sysadmin.
2. Go to performance tab by selecting a location.
3. Now select reports from drop down option.
4. Click on the Birth or, Death months sorting icon.

**Actual Result**
Months doesn't get sorted by clicking the icon.

**Expected behavior**
Sort should work by clicking the icon.

**Screenshots**
![report_sort](https://user-images.githubusercontent.com/16021495/89619078-23387380-d8af-11ea-9470-51f8fce026cf.png)

**Desktop):**
- OS: Windows 10
- Browser: Chrome 84.0

**Comment by mushrafulhoque-dsi** [comment]
Remove month sorting from this list

**Comment by SabitIbnAliKhan** [comment]
Sorting is working now
