### ISSUE TITLE
Alignment issue in Performance > Status > View all

### ISSUE THREAD

**Issue by SabitIbnAliKhan** [opencrvs/opencrvs-core#1891]
**Describe the bug**
The data in the table of the View all page of Status section (in Performance tab) is not aligned properly 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Performance'
2. Click on 'Status'
3. Click on 'View All'
4. Data in the table is not aligned properly 

**Expected behaviour**
The data should be aligned 

**Screenshots**
![application workflow_alignment](https://user-images.githubusercontent.com/44313971/89620211-27fe2700-d8b1-11ea-8fa5-9a6f720dc66e.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 84.0.4147.105

**Comment by noboshashabnom-dsi** [comment]
Tested and verified.
No alignment issue has been observed. Looks good now.
