### ISSUE TITLE
There should be a vertical scroll bar in the table of Status > View all page

### ISSUE THREAD

**Issue by SabitIbnAliKhan** [opencrvs/opencrvs-core#1895]
**Describe the bug**
The vertical scroll bar is not visible until the mouse is hovered over the bar in Performance > Status > View all page. Need to show the vertical scroll bar to see all info. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Performance'
2. Click on 'Status'
3. Click on 'View all'
4. Notice that the scroll bar for the table is not visible but becomes visible once the mouse is hovered over the bar

**Expected behaviour**
The scroll bar should be visible at all times 

**Screenshots**

![Vertical scroll bar](https://user-images.githubusercontent.com/44313971/89624005-6f87b180-d8b7-11ea-8108-38bac965bfc7.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 84.0.4147.105

**Comment by mushrafulhoque-dsi** [comment]
Vertical and horizontal scrollbar should be always visible for this list.

**Comment by mushrafulhoque-dsi** [comment]
Vertical scrollbar should be always visible on Report List as well

**Comment by SabitIbnAliKhan** [comment]
Scroll bars are showing now
