### ISSUE TITLE
Couldn't log into the system as new user. 

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1896]
**Describe the bug**
Error shows when tried to log into the system as a new user.

**Steps To Reproduce**
1. Log in as sysadmin.
2. Go to Team > Select location or upazila.
3. Click > New user
4. Provide all data and create a new user.
5. Observe it's in pending status for now.
6. Log out.
7. Now, try to login as new user with new user's user name & password.

**Actual Result**
Error shows in console and the page loads for long. Can't log in.

**Expected behavior**
New user could log into the system

**Screenshots**
![new user login](https://user-images.githubusercontent.com/16021495/89623784-0acc5700-d8b7-11ea-814d-b16ce91d6162.png)

**Desktop (please complete the following information:**
 - OS: Windows 10
- Browser: Chrome 84.0

** Environment**
https://login.opencrvs.qa1.jembi.org/

**Comment by SabitIbnAliKhan** [comment]
Could create and log in with new user
