### ISSUE TITLE
New application title changes in the 4th page from “New birth/death application” to “Birth/Death Application”

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1897]
**Steps To Reproduce**
1. Log in as a field agent.
2. Click + icon to create a new application.
3. Select Birth/death- any.
4. Provide data and go to the 4th page and see the change of the application title.

**Actual Result**
The title changes from “New birth/death application” to “Birth/Death Application” while creating a new application.

**Expected behavior**
The title should be same through out the new application creation process.

**Screenshots**
![Application header change](https://user-images.githubusercontent.com/16021495/89627617-f5f2c200-d8bc-11ea-8af5-593afd586757.png)

**Desktop (please complete the following information:**
 - OS: Windows 10
 - Browser: Chrome 84.0

**Environment**
https://login.opencrvs.qa1.jembi.org/

**Comment by anninawersun** [comment]
Should become: Birth application and Death application (no "New")

**Comment by euanmillar** [comment]
Closing as this is likely a configuration error in the Bangladesh resource package json as opposed to a bug in core
