### ISSUE TITLE
The search label in performance and team page are not consistent. 

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1899]
**Steps To Reproduce**
1. Log in as sysadmin
2. Go to performance tab and observe the label- "Search for an administrative area or office" 
3. No to go Team tab and observe the label-  "Search for an office".

**Expected behavior**
 Both page should show same label

**Screenshots**
![Search label](https://user-images.githubusercontent.com/16021495/89632463-09555b80-d8c4-11ea-83f3-11b0f4a7c610.png)

**Desktop :**
 - OS: Windows 10
 - Browser: Chrome 84.0

**Comment by anninawersun** [comment]
This is not a bug - you can only search by office for team.
