### ISSUE TITLE
Not selecting an option for type of event to be declared and clicking continues takes user to a blank page

### ISSUE THREAD

**Issue by SabitIbnAliKhan** [opencrvs/opencrvs-core#1900]
**Describe the bug**
When making a new application, do not choose an option between birth and death as type of event being declared and click continue. A blank page appears when doing so. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new application 
2. Click on 'Continue. without choosing an option'
3. A blank page appears 

**Expected behaviour**
A validation should be shown saying that no options are chosen 

**Screenshots**
![bug1900](https://user-images.githubusercontent.com/44313971/89635104-4a4f6f00-d8c8-11ea-82ea-382eb251243c.JPG)

![bug1900_2](https://user-images.githubusercontent.com/44313971/89635112-4de2f600-d8c8-11ea-88d7-dca360925469.JPG)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 84.0.4147.105

**Comment by noboshashabnom-dsi** [comment]
Tested and verified.
Now a validation shows- "Please select the type of event" for continue without choosing an option.
