### ISSUE TITLE
Feature request: Success message notifications should automatically disappear.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1901]
**Steps To Reproduce**
1. Log in as sysadmin.
2. Go to Team > Search a location
3. Click > 3 dot icon to edit a user.
4. Update user details and save it.
5. Observe the success message.

**Actual result**
The success message doesn't get disappear until close it.

**Expected behavior**
The message should automatically disappear after few seconds. 

**Screenshots**
![Edit_Agent_Issues](https://user-images.githubusercontent.com/16021495/89636217-14ab8580-d8ca-11ea-9d1b-30d74dcb4933.JPG)

**Desktop:**
 - OS: Windows 10 pro
 - Browser: Chrome 84.0

**Note**
Success message doesn't get disappear for both create & update.

**Comment by SabitIbnAliKhan** [comment]
Also occurs for "Certificate is ready to print"

**Comment by SabitIbnAliKhan** [comment]
Please note that this also occurs for the "As you have connectivity we can synchronize your applications" message 
![connectivity_message](https://user-images.githubusercontent.com/44313971/90125008-1b7f4000-dd83-11ea-9d08-99f7d99126ab.JPG)
