### ISSUE TITLE
Logged in user cannot attach a file while updating an user profile.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1904]
**Steps To Reproduce**
1. Log in as sysadmin.
2. Go to Team > Select a location.
3. Click edit to a user profile who has 'registration clerk' role assigned.
4. Under attachment section add a jpg/png/any file

**Actual Result**
No files get added.

**Expected behavior**
User could able to add files.

**Screenshots**
![User_attachment](https://user-images.githubusercontent.com/16021495/89637841-a9af7e00-d8cc-11ea-9fbd-f61662b94472.png)

**Desktop:**
 - OS: Windows 10 pro
 - Browser Chrome 84.0

**Note**
1. It only appears for registration clerk role. 
2. User can add file in a different page which comes while updating name and other data.

**Comment by euanmillar** [comment]
@jpye-finch this is weird isnt it.  Can you remind us what this button is meant to do please?  I think perhaps it is an in-progress feature of some kind.

**Comment by euanmillar** [comment]
We need to hide attachments for registration agent

We need to make sure that attachments are required in creating a new registrar

We fix the upload network bug

Change the word "Attachments" to "Signature"

**Comment by SyedaAfrida** [comment]
Currently admin user do not have option to change or delete signature from 'edit details' page of a registrar. Check #2509

**Comment by jpye-finch** [comment]
@euanmillar yes this is intended for a system admin to add a Registrar signature

**Comment by anny320** [comment]
completed
