### ISSUE TITLE
No validation shows when remove the location from user edit page.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1905]
**Steps To Reproduce**
1. Log in as sysadmin.
2. Go to Team > Select a location
3. From user list page click edit of an user profile
4. Click 'Change' link of 'Registration Office'
5. Remove the location and click > Continue.
6. It takes to edit user page without showing any validation of required data.
7. Click > continue and observe it has reserved previous location.

**Actual Result**
No validation shows when user removed the location.

**Expected behavior**
A validation should show when there is no data in location field rather reserving the old location. May be user intended to but forgot to update. A validation can give a buzz to update location that has been missed by user.

**Screenshots**
![New user_update_location](https://user-images.githubusercontent.com/16021495/89639260-0dd34180-d8cf-11ea-80ac-9fd404a807a9.png)

**Desktop :**
 - OS: Windows 10 pro
- Browser- Chrome 84.0

**Comment by euanmillar** [comment]
Error message should say:

"No results found"

In red beneath the input field.

Also Submit button should be disabled

**Comment by SyedaAfrida** [comment]
@anny320 this is fixed and can be closed
![#1905](https://user-images.githubusercontent.com/94350336/163959843-034d5caf-6e1f-4b20-ac06-015f02dbe2c8.png)

**Comment by anny320** [comment]
completed
