### ISSUE TITLE
Start time is shown under started by for search results 

### ISSUE THREAD

**Issue by SabitIbnAliKhan** [opencrvs/opencrvs-core#1906]
**Describe the bug**
When searching for an application. the start time is shown under the Started By column for the search results 

**To Reproduce**
Steps to reproduce the behaviour:
1. Search for an application using any criteria
2. Observe the colums 
3. Start time is shown under Started By

**Expected behaviour**
Column header should be 'Started '

**Screenshots**
![search_startedby_error](https://user-images.githubusercontent.com/44313971/89639799-0f513980-d8d0-11ea-85a6-a3130ace91be.JPG)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 84.0.4147.105

**Comment by mushrafulhoque-dsi** [comment]
Change the column header copy to "Started"

**Comment by SabitIbnAliKhan** [comment]
Still showing Started By

**Comment by noboshashabnom-dsi** [comment]
Tested and verified. The column header showing 'Started'.
