### ISSUE TITLE
Searching using phone number only works when adding +880

### ISSUE THREAD

**Issue by SabitIbnAliKhan** [opencrvs/opencrvs-core#1907]
**Describe the bug**
When searching for an application using the phone number, results only appear when +880 is added before the number, even though the number in the application does not contain +880

**To Reproduce**
Steps to reproduce the behaviour:
1. Search for an application using a phone number (+880 not included)
2. No search results 
3. Search for an application using same phone number (+880  included)
4. Results  appear 

**Expected behaviour**
Since the number in the application does not contain +880, search results should appear when +880 is not included.

**Screenshots**
![Search result](https://user-images.githubusercontent.com/44313971/89640327-293f4c00-d8d1-11ea-8724-f0d17bc3bb58.JPG)

![search_result_2](https://user-images.githubusercontent.com/44313971/89640328-2a707900-d8d1-11ea-8996-50e115c90e23.JPG)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 84.0.4147.105

**Comment by noboshashabnom-dsi** [comment]
Duplicate to 1898

**Comment by SabitIbnAliKhan** [comment]
Closing because duplicate issue
