### ISSUE TITLE
NID for CRVS users is superfluous

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1908]
**Steps To Reproduce**
1. Log in as sysadmin.
2. Go to Team > Select a location
3. Click edit option of a user profile who has 'registration clerk' role assigned.
4. Notice the unused NID field

**Comment by euanmillar** [comment]
We should remove the requirement for staff NID in create and edit user

**Comment by euanmillar** [comment]
Lets make NID not a required field.  If it is required then the RegExp for validating an NID must be in the config.  Because it is different in Bangladesh and Zambia

**Comment by anny320** [comment]
completed
