### ISSUE TITLE
Data Limit needs to be added to names 

### ISSUE THREAD

**Issue by SabitIbnAliKhan** [opencrvs/opencrvs-core#1909]
**Describe the bug**
A huge amount of data can be added to the name fields of both Birth and Death applications 

**To Reproduce**
Steps to reproduce the behaviour:
1. Start an application
2. Enter data in name fields 
3. A huge amount of data can be added

**Expected behaviour**
There should be a data limit

**Screenshots**
![data limit in name](https://user-images.githubusercontent.com/44313971/89643502-b9808f80-d8d7-11ea-8c7b-8c886f4e53ec.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 84.0.4147.105

**Comment by noboshashabnom-dsi** [comment]
Need to add data limit in every name field of birth and death application. Father, Mother, Someone else (In Relationship).

**Comment by euanmillar** [comment]
Agree we need to add data limits on each field in some way.

**Comment by SyedaAfrida** [comment]
Huge amount of data can still be added in Death Application in the following name fields-
1.  Mother's Name 
2.  Father's Name 
3.  Someone else

**Comment by SyedaAfrida** [comment]
Data limit also needs to be added in- "Legal Guardian" and "Other caregiver" name fields
![data limit](https://user-images.githubusercontent.com/94350336/147470317-816854c9-b4e8-4eb9-bb33-927514b41b4b.png)
![data limit 2](https://user-images.githubusercontent.com/94350336/147470323-29404a0a-1ddb-4f7d-88be-a149da4ebaae.png)
