### ISSUE TITLE
Duplicate review option doesn't appear for death application.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1914]
**Steps To Reproduce**
1. Log in as a field agent.
2. Create two death application with same name, applicant number, DOB, DOD. 
3. Send both > Submit for review.
4. Log in as Register.
5. Observe the application in Ready for review tab.
6. Click Download > review.

**Actual Result**
1. Duplicate review check doesn't appear for death application.
2. Duplicate flag doesn't show on UI.

**Expected behavior**
For duplicate application dup review should appear.

**Screenshots**
![Death_DUP](https://user-images.githubusercontent.com/16021495/89778504-76b8f480-db2f-11ea-8e44-e3b5476e1a07.png)

**Desktop :**
 - OS: Windows 10
 - Browser: Chrome 84.0

**Comment by mushrafulhoque-dsi** [comment]
Duplication check is supported for death event yet
