### ISSUE TITLE
Application status count in their respective tabs doesn't reflect in offline mode.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1924]
**Prerequisite to reproduce**
Turn off your internet connection in your device after log into the system
 
**Steps To Reproduce**
1. Observe the status count in the respective tabs when the internet connection is active.
2. After turning off the internet connection click on any tab and observe.

**Actual Result**
The counts get disappear.

**Expected behavior**
As the counts is already loaded after log in so it should reflect when there is no internet connection. 
In field agent dashboard count reflect on 'In Progress' & 'Sent for review' tab.

**Screenshots**

![Internet_Count_1](https://user-images.githubusercontent.com/16021495/89987688-4775c500-dca0-11ea-890e-2eb3d282bc35.png)
![Internet_Count_2](https://user-images.githubusercontent.com/16021495/89987699-49d81f00-dca0-11ea-8bfd-f9e018cb3a35.png)
![Internet_Count_3](https://user-images.githubusercontent.com/16021495/89987704-4ba1e280-dca0-11ea-88f7-249b076fdd04.png)
![Internet_Count_4](https://user-images.githubusercontent.com/16021495/89987708-4cd30f80-dca0-11ea-9c24-803b2a170601.png)

**Desktop:**
 - OS: Windows 10 Pro
 - Browser: Chrome 84.0

**Comment by mushrafulhoque-dsi** [comment]
We are intentionally not showing counts in offline mode
