### ISSUE TITLE
Error shows and application details doesn't appear when click "Required Updates" tab's application in offline mode.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1925]
**Steps To Reproduce**
1. Log into the system as field agent.
2. Go to offline mode (Turn off internet connection)
3. Click > Required Updates tab.
4. Click > Any application.
5. Observe the message > "_Whoops! Something went wrong. It's not you, it us. This is our fault. Go To Homepage_" 
6. Click > Go To Homepage.

**Actual Result**
Error shows in console and it redirects to a blank page.

`GET https://resources.opencrvs.qa1.jembi.org/client-config.js net::ERR_INTERNET_DISCONNECTED
validate.ts:52 
Uncaught TypeError: Cannot read property 'COUNTRY' of undefined
    at Module.137 (validate.ts:52)
    at f ((index):1)
    at Module.1614 (person.ts:60)
    at f ((index):1)
    at Object.910 (index.js:30)
    at f ((index):1)
    at a ((index):1)
    at Array.e [as push] ((index):1)
    at main.c9d27941.chunk.js:1`

**Expected behavior**
After clicking the required updates tab's application, it should show the details as like other tab's application.

**Screenshots**
![Internet_1 1](https://user-images.githubusercontent.com/16021495/89988858-f535a380-dca1-11ea-8c8c-0e1bcb9e5eec.png)
![Internet_2](https://user-images.githubusercontent.com/16021495/89988860-f5ce3a00-dca1-11ea-877e-79a787404c83.png)
![Internet_3](https://user-images.githubusercontent.com/16021495/89988870-f8309400-dca1-11ea-9a8f-554dd20b9f82.png)

**Desktop:**
 - OS: Windows 10
-  Browser: Chrome 84.0

**Comment by anninawersun** [comment]
@mushrafulhoque-dsi why is this blocked?
