### ISSUE TITLE
Both "Started On" & "Updated On" information shows after creating an application as field agent.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1929]
**Summary**
Both "Started On" & "Updated On" information shows after creating an application as field agent. But, this behavior is misleading because user just created the application, didn't update it. Start/update status should show based on related action taken.

**Steps To Reproduce**

**Scenario-1**
1. Log in as a field agent 
2. Go to In progress tab.
3. Click create button to create a new application.
4. Create a birth/death application > Save & Exit.
5. Click on the application from the list and observe.
6. "Started on" and "Updated on" info shows.

![Create_Update_field agent](https://user-images.githubusercontent.com/16021495/90019156-d6e69c80-dccf-11ea-8c35-ed88818121fe.png)

**Expected Result**
1. As the user just created the application so it should show only "Started on" information and NOT "Updated on".
2. It would be great if we could show time beside date of the application creation.

**Scenario-2**
6. Now, Update any information of the application > again-Save & Exit.
7. Click on the application from the list under In Progress tab.

**Expected result**
1. Now, it should show the "Updated on" information.
2. Beside date we should show time of update to track the update information.

**Desktop:**
 - OS: Windows 10 pro
 - Browser: Chrome 89.0

**Comment by euanmillar** [comment]
Fix bug and add time hh:mm

**Comment by anny320** [comment]
completed
