### ISSUE TITLE
Update information of a draft application doesn't show which is created by registration clerk and register.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1930]
**Summary**
When register and registration clerk update a draft application, no update information shows when expand the application in list for the action taken. 

**Steps To Reproduce**
1. Log in as register/Registration clerk.
2. Go to In Progress tab.
3. Click create button and create an application > Save & Exit.
4. Now the application is in DRAFT state.
5. Click on the application and observe "Started On" info shows.
6. Click > Update button.
7. Update any information and click > Save & Exit.
8. Again click on the application from the list and observe.

**Actual Result**
No update information shows.

**Expected behavior**
1. "Updated On" information should appear after update action is taken.
2. Beside date, time should also shown of update. User can track creation date-time with update date-time. It would be useful.

**Screenshot**
![Create_Update_Registration clerk](https://user-images.githubusercontent.com/16021495/90022219-17e0b000-dcd4-11ea-8bda-f059f16af3b4.png)

**Desktop:**
 - OS: Windows 10 pro
 - Browser : Chrome 89.0, FF 79.0

**Comment by euanmillar** [comment]
Closing as there is a misunderstanding here about when Task history updates.  It only updates after submission either as Sent for review, or In progress.  Its a back end process.

**Comment by anninawersun** [comment]
@euanmillar I think this reflects the discussion we need to have on audit and what is audited. I would expect this to be in audit. let's discuss
