### ISSUE TITLE
"Name" search is returning multiple incorrect results with the actual result. 

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1931]
**Steps To Reproduce**
1. Log in as a user in the system.
2. In search box select > Name option.
3. Write a name of Child's/ Deceased's and hit > search. 

**Actual Result**
Multiple result shows with the actual result

**Expected behaviour**
Only actual result should show.

**Screenshots**
![Name search_1](https://user-images.githubusercontent.com/16021495/90117896-554b4900-dd79-11ea-91bd-0ba9e6ae5001.png)
![Name search_2](https://user-images.githubusercontent.com/16021495/90117900-55e3df80-dd79-11ea-9fa8-c65f6f2d08b6.png)

**Desktop:**
 - OS: Windows 10 Pro
 - Browser: Chrome 89.0, FF 79.0

**Comment by mushrafulhoque-dsi** [comment]
Currently we searching name in following fields of an application:

-   'childFirstNames',
-   'childFamilyName',
-   'childFirstNamesLocal',
-   'childFamilyNameLocal',
-   'motherFirstNames',
-   'motherFamilyName',
-   'motherFirstNamesLocal',
-   'motherFamilyNameLocal',
-   'fatherFirstNames',
-   'fatherFamilyName',
-   'fatherFirstNamesLocal',
-   'fatherFamilyNameLocal',
-   'informantFirstNames',
-   'informantFamilyName',
-   'informantFirstNamesLocal',
-   'informantFamilyNameLocal',
-   'primaryCaregiverFirstNames',
-   'primaryCaregiverFamilyName',
-   'primaryCaregiverFirstNamesLocal',
-   'primaryCaregiverFamilyNameLocal',
-   'deceasedFirstNames',
-   'deceasedFamilyName',
-   'deceasedFirstNamesLocal',
-   'deceasedFamilyNameLocal',
-   'spouseFirstNames',
-   'spouseFamilyName',
-   'spouseFirstNamesLocal',
-   'spouseFamilyNameLocal'

Not all of them are visible on the list.
