### ISSUE TITLE
Improvement: Need to add year selection option in "Time Period" select box under performance tab and edit user page.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1933]
**Steps To Reproduce**
1. Log into the system as system admin/Register/registration clerk.
2. Go to Performance tab.
3. Click "Time Period" select box

**Expected behavior**
Need to add year selection option in "Time Period" select box. Clicking on the year an option should appear to select year.

**Note**
Same for user edit page audit section.

**Screenshots**
![Year selection](https://user-images.githubusercontent.com/16021495/90141899-89386580-dd9d-11ea-8877-2805226ec791.png)
![User_audit_calender](https://user-images.githubusercontent.com/16021495/90218378-779aa080-de25-11ea-9d4e-e270eb48d8ea.png)

**Desktop:**
 - OS: Windows 10 Pro
 - Browser: Chrome 89.0

**Comment by jpye-finch** [comment]
closing this. I think the arrow selects to change the year is sufficent for now. Would involve alot of redesign to include a year select
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/7ee410dc-4cc0-4358-a0e4-cc0deb06dfcc
)
