### ISSUE TITLE
Inside details report page time period has represented using both 'hyphen' and 'to', it should follow one pattern.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1936]
**Steps To Reproduce**
1. Log into system.
2. Go to Performance > Report
3. Click any month of birth/death which has data in it.
4. Observe the 'Birth registered by time period, from date of occurrence' 3rd and 4th column.

**Actual Result**
3rd column represents data of time using hyphen: 45 days - 1 year
4th column represents data of time using to: 1 year to 5 years

**Expected behaviour**
Both should follow the same pattern. Either 'hyphen' or 'To'

**Screenshots**
![Time eriod representation](https://user-images.githubusercontent.com/16021495/90217377-01953a00-de23-11ea-8a69-0482794eb59a.png)

**Desktop :**
 - OS: Windows 10 pro
 - Browser: Chrome 89.0

**Comment by anninawersun** [comment]
"-" is probably more universal - please use this.

**Comment by anny320** [comment]
completed
