### ISSUE TITLE
User profile 'Device' name is not storing the input data.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1937]
**Steps To Reproduce**
1. Log in as system admin.
2. Go toTeam > Select location.
3. Click > New user
4. Provide all data > Add device name > Create user.
5. From user list page click "Edit" option of the new user created.
6. Observe the device name.

**Actual Result**
Device name is missing

**Expected behaviour**
Device name should return as per input provided.

**Note**
Same for update. If update user and add device name it doesn't save the input data.

**Screenshots**
![User_device_add](https://user-images.githubusercontent.com/16021495/90219173-4327e400-de27-11ea-95d7-abbfa1aba309.png)
![User_device_add_edit page](https://user-images.githubusercontent.com/16021495/90219178-44f1a780-de27-11ea-91d5-d6c518c48a9b.png)

**Desktop:**
 - OS: Windows 10 pro
 - Browser: Chrome 89.0

**Comment by euanmillar** [comment]
What exactly should be the device name and why is it editable?  I think without further specification this feature should be removed.

**Comment by anninawersun** [comment]
@euanmillar this was originally in case users are issued a device by government and they need to be tracked (for inventory). It hasn't been used yet and other features would be required to view device status. But it could be useful in the future. Let's discuss.

**Comment by jpye-finch** [comment]
@anninawersun to be discusssed. Do we show what device the user has been assigned in the team page. Plus system admin can update device etc.

**Comment by euanmillar** [comment]
@anninawersun we have no epic for device management and it isnt tracked in audit or displayed anywhere else.  As this is essentially a broken link in Core, I think we need to removie it and then create an Epic for Device management

**Comment by anninawersun** [comment]
@euanmillar and @jpye-finch i agree - let's get rid of it for now. Not a priority - might become one in a country implementation.

**Comment by euanmillar** [comment]
Actually this is a bug.  We need to fix it, then eventually we can hide it.

**Comment by SyedaAfrida** [comment]
This issue still persist in - login.zambia-uat.newlegacy.digital
**Screen recording**
https://www.loom.com/share/9c90224666d14fb09f61683ab0610ea2

though in local server its working fine. Need to verify if deployment was done properly.

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/163116108-f1a47214-6bb3-428e-8b36-73926e5192c3.mp4

**Comment by anny320** [comment]
completed
