### ISSUE TITLE
In slow internet connection when click 'Logout' from pin code page it shows "undefined undefined" message.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1939]
**Steps To Reproduce**
1. Log in as a user in the system.
2. Wait until the session expire and takes to pin code page.
3. Now, in a slow internet connect > click logout from pin code page.

**Actual Result**
A message shows "undefined undefined" for a while and then takes to login page.

**Expected behaviour**
It should show loading icon for a while in slow connection rather showing irrelevant message. 

**NOTE**
Could reproduce this scenario 3 out of 6 times. 

**Video**
![Undefined](https://user-images.githubusercontent.com/16021495/90225936-04e4f180-de34-11ea-9a5d-b93f52a036af.gif)

**Desktop :**
 - OS: Windows 10 pro
 - Browser : Chrome 89.0, FF 79.0

**Comment by euanmillar** [comment]
On pin page only show name if defined

**Comment by anny320** [comment]
closed
