### ISSUE TITLE
Need to readjust the label of "Confirm" button in new user details page.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1940]
**Steps To Reproduce**
1. As system admin create a new user.
2. With the new user's user name try to log into the system.
3. provide details > add password > go to details page.
4. Observe the 'Confirm' button.

**Expected behaviour**
Need to readjust the label of "Confirm" button in new user details page. It is not appearing nicely.

**Screenshot**
![Confirm button _new user](https://user-images.githubusercontent.com/16021495/90229978-a2432400-de3a-11ea-9511-7fd006e29e11.png)

**Desktop :**
 - OS: Windows 10 pro
 - Browser: Chrome 89.0

**Comment by Zangetsu101** [comment]
![Screenshot from 2021-11-09 15-31-01](https://user-images.githubusercontent.com/29002716/140899300-0d284dfa-2f42-444a-bcab-25a413991d2a.png)
The bug is not present now so this issue can be closed.

**Comment by azantor64** [comment]
According to #1940 issue, 'Confirm' text inside button is adjusted in user details page.So, this bug(#1940) is solved.
