### ISSUE TITLE
Require Updates tab has column header as Sent On but data shown is Rejection date 

### ISSUE THREAD

**Issue by SabitIbnAliKhan** [opencrvs/opencrvs-core#1943]
**Describe the bug**
Require Updates tab has column header as Sent On but data shown is Rejection date 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Applications'
2. Click on 'Require Update'
3.  Notice the column with header Sent on 
4. Data under that colum says Rejected X days ago

**Expected behaviour**
Either the header should be Rejected on or the data in the column should be Sent date

**Screenshots**
![rejected_date](https://user-images.githubusercontent.com/44313971/90252040-a71ace80-de60-11ea-8970-cdf2f3be67d0.JPG)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 84.0.4147.105

**Comment by euanmillar** [comment]
Sent for updates on:

Replace rejected throughout with SENT_FOR_UPDATES / Sent for updates
