### ISSUE TITLE
Application status record list get truncated when it has multiple records. 

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1944]
**Steps To Reproduce**
1. Log in as a user in the system.
2. Create an application.
3. Sent for approval > Reject few times with long comments added > Send for approval again > take multiple action on that application.
4. Now from any status tab > Expand the application to see the status records.

**Actual Result**
The bottom portion gets truncated and no scroll bar to scroll down to see all the records.

![Application records list](https://user-images.githubusercontent.com/16021495/90254258-47262700-de64-11ea-97af-3e0596320182.png)

**Expected behaviour**
A scroll bar would be helpful to scroll down and see all the status records.

**Desktop :**
 - OS: Windows 10 pro
 - Browser: Chrome: 89.0

**Comment by euanmillar** [comment]
Define what the char limit: 500 chars

**Comment by anny320** [comment]
completed
