### ISSUE TITLE
Performance tab info gets overlapped when open status bar in specific display size.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1945]
**Steps To Reproduce**
1. Pick a device which has 15.6'' display.
2. Log into system.
3. Go to Performance tab > Operational > Click status > Observe
4. Now, click > Report > Open Status > Observe

**Actual Result**
Status bar overlap the performance page background for both operational and reports page.

**Expected behavior**
The status bar should be adjusted with small display.

**Screenshots**
![Operational_small screen](https://user-images.githubusercontent.com/16021495/90256527-b18c9680-de67-11ea-9599-39e52629c3c2.png)
![Reports_small screen](https://user-images.githubusercontent.com/16021495/90256528-b2bdc380-de67-11ea-8de6-df6172a0bd2d.png)

**Laptop :**
 - OS: Windows 10
 - Browser Chrome 89.0, FF 79.0

**Note**
Same thing happen for report screen in display 21.5 inch .
![Reports_big screen](https://user-images.githubusercontent.com/16021495/90256673-dc76ea80-de67-11ea-8326-68ffcb26f788.png)

**Comment by euanmillar** [comment]
This is expected behaviour as per the design supplied.
