### ISSUE TITLE
In user details page audit calendar gets cut off in small screen and no scroll bar present.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1946]
**Steps To Reproduce**
1. Pick a device which has 15.6'' display.
2. Log into system.
3. Go to Team > Click on user name link.
4. Click Calendar under audit .

**Actual Result**
The calendar is not showing completely, it's truncated below. No scroll bar is present.

**Expected behaviour**
Need a scroll bar to see information below.

**Screenshot**
![User profile_small screen](https://user-images.githubusercontent.com/16021495/90257318-d7666b00-de68-11ea-93e3-90d4917c92f4.png)

**Laptop : Display 15.6''**
- OS: Windows 10
- Browser: Chrome 89.0, FF 79.0

**Comment by anny320** [comment]
completed
