### ISSUE TITLE
Shows incorrect message on "Required updates" tab of a new field agent user.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1948]
**Describe the bug**
On required updates tab of a new field agent user shows- _**No applications require updates. Great job! You have updated all applications.**_

**Steps To Reproduce**
1. Create a new field agent user as sysadmin. (Field Agent / Hospital)
2. Complete all the procedure to on board the new user.
3. Log in as new field agent user.
4. Click on the tabs and observe- In progress, sent for review & required updates

**Actual Result**
On 'In progress' & 'Sent for review' tab shows "**_No result to display_**" message and on  'Required updates' tab shows "**_No applications require updates. Great job! You have updated all applications._**" Here 'You have updated all applications.' is not not a correct message for a new user.

**Expected behavior**
'Required updates' tab should show "No result to display". Because 'You have updated all applications.' is not not a correct message for a new user.

**Screenshot**
![Newuser_require updates tab](https://user-images.githubusercontent.com/16021495/90377917-85a52700-e09a-11ea-8f53-8aad09d573b6.png)

**Desktop :**
 - OS: Windows 10 pro
 - Browser: Chrome 89.0

**Comment by euanmillar** [comment]
Jon to look at copy for new users on all tabs

**Comment by euanmillar** [comment]
Close due to inactivity and new design
