### ISSUE TITLE
After creating an application as a field agent (which has RC role previously) it redirects to the landing page of a registration clerk. 

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1949]
**Prerequisite**
1. Log in as sysadmin.
2. Change a user role from registration clerk to Field Agent · Hospital.
3. Save.

**Steps To Reproduce**
1. Log in as new field agent.
2. Go to 'In Progress' tab.
3. Click + icon to create an application. Provide data inside the new application >Save & exit. 
4. Observe the landing page and tabs.

**Actual Result**
After creating an application as a field agent it redirects to the landing page of a registration clerk. It shows tabs- In Progress, Ready for review, Sent for updates, Sent for approval & Ready to print. 

**Expected behaviour**
It should redirect to the right landing page view. 

5. Now log out and re-login as new user
6. Observe- it shows the right view of a field agent.

**Video & Screenshots**
![New-field-agent-application](https://user-images.githubusercontent.com/16021495/90383271-b9d01600-e0a1-11ea-84da-6ce2eea06099.gif)
![New field agent_2](https://user-images.githubusercontent.com/16021495/90383302-c6546e80-e0a1-11ea-8196-7394b5ea0812.png)
![New Field agent 1](https://user-images.githubusercontent.com/16021495/90383305-c81e3200-e0a1-11ea-87f9-9a4d08fd103d.png)
![New Field agent 3](https://user-images.githubusercontent.com/16021495/90383312-c9e7f580-e0a1-11ea-916e-baf8eaa9fc0a.png)

**Desktop :**
 - OS: Windows 10 pro
 - Browser : Chrome 89.0

**Comment by euanmillar** [comment]
Closing as this is a real edge case.  The user actually has had their role reduced but the browser still has the download of a registration agent view.  If they trued to perform any of the registration agents actions via form submission it would fail and they would be logged out anyway.
