### ISSUE TITLE
Changing role of agent creating issues

### ISSUE THREAD

**Issue by SabitIbnAliKhan** [opencrvs/opencrvs-core#1951]
**Describe the bug**
Scenario 1 - When a new user is created as Registrar and then his role is changed to Field Agent, creating an application gives the field agent the option to Register the application. When clicking Save and Exit, the view on the Applications page also changes to what a Registrar would see.
Scenario 2 -  When a new user is created as Field Agent and his role is changed to Registration Clerk, clicking Review from Ready for Review tab and clicking Update from Sent for Updates tab  shows a message "We are unable to display this toyou"

**To Reproduce**
Steps to reproduce the behavior for Scenario 1 :
1. Create an user as Registrar
2. Change his role to field agent 
3. Create a new application 
4. User will see the option to directly Register it 
5. Click Save and Exit
6. The view in the Applications page changes to what a Registrar would see

**To Reproduce**
Steps to reproduce the behavior for Scenario 2:
1. Create an user as Field Agent
2. Change his role to Registration Clerk
3. Go to Applications > Ready for Review or Go to Sent for Updates
4. Click review or update on an application
5. A error message will appear 

**Expected behaviour**
Scenario 1 - Field agent should not be able to register an application and view in Applications page should not change 
Scenario 2 - User should be able to Review and Update application 

**Screenshots**

Scenario 1 - 
![roleChange1](https://user-images.githubusercontent.com/44313971/90391519-171e9400-e0af-11ea-86ba-b047ec23f6c1.JPG)

The user is a field agent and the view in Application page is okay

![roleChange2](https://user-images.githubusercontent.com/44313971/90391577-2f8eae80-e0af-11ea-9d6f-286c3971dfc9.JPG)

Field Agent sees the option to Register the application 

![roleChange3](https://user-images.githubusercontent.com/44313971/90391621-40d7bb00-e0af-11ea-818b-16d2edc464f5.JPG)

After clicking save and exit the view changes to what a Registrar sees 

Scenario 2- 

![roleChange4](https://user-images.githubusercontent.com/44313971/90391864-a7f56f80-e0af-11ea-8fbd-80e890d4b742.png)

![roleChange5](https://user-images.githubusercontent.com/44313971/90391883-acba2380-e0af-11ea-88c5-14476b40006a.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 84.0.4147.105

**Comment by noboshashabnom-dsi** [comment]
Same for turning a registration clerk to field agent. It gives option to send application for approval rather for review. 
Explanation: Change a registration clerk role to field agent. Now as field agent create an application and observe the button in review page It shows "Send for approval". Field agent should see the button "Sent for review".

**Comment by euanmillar** [comment]
1. We need to extend the graphql > confg.ts

getApolloConfig method:

compare token role with user-mgnt role, if they dont math throw Auth error

2. handle graphql gateway auth error in the client to show login screen?

**Comment by SabitIbnAliKhan** [comment]
Issue resolved
