### ISSUE TITLE
Health Institution name is not getting saved for both birth and death application.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1953]
**Steps To Reproduce**
1. Log in as a user.
2. Create a birth application. 
3. Select 'Place of delivery'= Health Institution and write the institution name in the text field. 
4. Save & Exit. Observe the review page.

**Actual Result**
Health Institution name is not saved for the application. 

**Expected behaviour**
The field is probably a location search field but it's not showing any suggestion when typing the hospital name. Need to show suggestions or keep it as text field only.

**Note**
Same for Death application "Where did the death occur?"; if select hospital and provide hospital name it's not storing data.

**Screenshots**
![Health institute](https://user-images.githubusercontent.com/16021495/90603560-4b17c780-e21d-11ea-923a-a6cb9b356f02.png)
![Health institute 2](https://user-images.githubusercontent.com/16021495/90603569-4ce18b00-e21d-11ea-82bb-6430e89d0097.png)

**Desktop:**
 - OS: Windows 10 pro
 - Browser : Chrome 89.0

**Comment by euanmillar** [comment]
Jon to take a look at the design?

**Comment by euanmillar** [comment]
1.  Issue 1: User experience - people type and because there isnt a facility to choose, they leave it and expect it to appear - if nothing pops up, it should be a validation error
2. Issue 2: Offline locations - field agents or registrars only can search available institutions within the Upazila as these are the only ones available offline.  We may need some placeholder copy which says `You are offline, type to search institutions in your Upazila' - changes to "You are online, type to search institution"

**Comment by jpye-finch** [comment]
how about this to address Issue 1?
https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/2.-Components?node-id=3500%3A3489

**Comment by jpye-finch** [comment]
Issue 2: Offline locations - field agents or registrars only can search available institutions within the Upazila as these are the only ones available offline. 

We need to consider what we want a Field Agent to do when they are offline (likely) and they want to add a health insitution outside of their Upazilla. So the field isn't left blank making the Registrar life more difficult. 

1. They enter the health institution name (will throw an error. tell them they can continue). Get the Registrar to look at the error, search for the institution with a connection. 
2. When trying to send the application from the Field Agent tablet. We prompt the FA to try and search again (when they have a connection). This could be outside the form when on the workqueue pages. This seems tricky to pull off. 

i mocked it up using 'one page' concept idea here :https://www.figma.com/file/IsPvujBG34IUjctUKt9WlyWs/4.-New-Application?node-id=2320%3A0

using existing design layout: https://www.figma.com/file/IsPvujBG34IUjctUKt9WlyWs/4.-New-Application?node-id=2699%3A23956

**Comment by euanmillar** [comment]
Interesting challenge this and one to review again

**Comment by euanmillar** [comment]
Issue 1 should be solved by: https://github.com/opencrvs/opencrvs-core/issues/2053

We will discuss a solution to Issue 2 in the upcoming Tech arch review

**Comment by euanmillar** [comment]
Just @anninawersun as a wee test

**Comment by euanmillar** [comment]
- [ ] Firstly, we are going to try saving the full list of health facilities offline.  


- [ ] Collaborate with Yeasin's PR - Remove the HEALTH_FACILITY_FILTER config value later

We may need to improve the design of the loading animation on first load, and also in the facility search later
