### ISSUE TITLE
Inconsistent behavior shows for duplicate attachment file name of birth and death application.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1954]
**Steps To Reproduce**

**Birth application**
1. Log in as a user.
2. Create a birth application.
3. Go to attachment page and add all the files. 
Specially, 
- Under 'Proof of place and date of birth' = Other
- Under 'Proof of child age' = Other.
4. Go to review page and try to see the child's other files.

**Actual Result**
1. As the names are duplicate in the drop down, so both name get auto select if click on any of the option of "child's other" 
2. If select the 2nd option of child's other file, it shows the 1st attachment of child's other.

**Screenshot**
![Other option 1](https://user-images.githubusercontent.com/16021495/90607269-d051ab00-e222-11ea-93b0-67d00d1c9372.png)

**Death application**
1. Log in as a user.
2. Create a death application.
3. Go to attachment page and add all the files. 
Specially, 
- Under 'Proof of deceased's ID' = Birth registration certificate
- Under 'Proof of permanent address of deceased' = Birth registration certificate
4. Go to review page and try to see the 'Deceased's birth registration certificate'

**Actual Result**
1. As the names are duplicate in the drop down, so both name get auto select if click on any of the option of 'Deceased's birth registration certificate'. 
2. If select the 2nd certificate option, it shows the 1st attachment of 'Deceased's birth registration certificate'.

**Screenshot**
![death application_birth registration](https://user-images.githubusercontent.com/16021495/90607642-5110a700-e223-11ea-9af2-73b9177d0af2.png)

**Desktop :**
 - OS: Windows 10 ro
 - Browser: Chrome 89.0

**Comment by euanmillar** [comment]
Cannot be replicated in Zambia.  Probably an issue with Bangladesh

**Comment by anny320** [comment]
please retest @azantor64

**Comment by SyedaAfrida** [comment]
@anny320 this is an old design bug. This bug no longer appears, so can be closed

**Comment by anny320** [comment]
closed
