### ISSUE TITLE
Performance tab shows different union name for a new user.

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1961]
**Steps To Reproduce**
1. Log in as system admin.
2. Create a new user in "Sonai Union Parishad"
3. Now setup the new user.
4. Log in as new user in the system.
5. Click Performance tab and then Team tab.

**Actual Result**
Performance tab shows "Baniajan Union Parishad, Atpara" and Team tab shows "Sonai Union Parishad".

**Expected behaviour**
Both performance and team tab should show "Sonai Union Parishad" union as the logged in user in an agent of that location.

**Screen shot & Video**
https://www.loom.com/share/463c74ad48af499e872174149aaf0ea3

![New user_performance tab](https://user-images.githubusercontent.com/16021495/91032393-b39ee400-e623-11ea-9130-8bfe478f5668.png)

**Desktop :**
 - OS: Windows 10 pro
 - Browser: Chrome 89.0

**Comment by anninawersun** [comment]
Thank you!

**Comment by noboshashabnom-dsi** [comment]
The issue is no longer present in the system. Tested and verified. So, closing this now.
