### ISSUE TITLE
New font style required: 12px Semi-Bold - StatusPill

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1963]
### Description
- So basically. im now using both Semi-bold and Regular for all font sizes in the designs: 12, 14, 16, 18, 24, 27, 36, 48, 80px  
- add new font style: 12px SemiBold
- update Status Pill

### Acceptance criteria

Pill:
FontStyle: 12px SemiBold
padding: 4px 8px
border-radius: 2px

### Design
https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/2.-Components?node-id=3051%3A1514

**Comment by euanmillar** [comment]
Closing as no information on where this pill is in use and requires updating

**Comment by euanmillar** [comment]
Its in use in the system admin pages.  See story:
