### ISSUE TITLE
UI - Team table desktop and mobile

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1965]
**Describe the bug**

BodyBold is required for: No. or users![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/67fa92e9-00d9-4e5b-aa7d-34283cef672c)

Desktop:
- Row is 56px height ON DESKTOP
- Row padding-left: 8px, padding-right 8px
- Profile icon: padding right 16px
 https://www.figma.com/file/0S1A3nDaVX2D3mIWViCWZvOp/3.-Patterns?node-id=29%3A1360

Tablet/Mobile:
- Row is 80px height ON MOBILE
- Profile icon missing (if less than 600px)
- Padding-left: 16px, padding-right: 16px
- User type: New font-style required: Regular 14px
 https://www.figma.com/file/0S1A3nDaVX2D3mIWViCWZvOp/3.-Patterns?node-id=29%3A1360

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1%3A2824

**Comment by Fariha-Amin** [comment]
@anny320  this is old ticket from Alpha 3.1 release, can be closed

**Comment by anny320** [comment]
closed
