### ISSUE TITLE
deactivate and reactivate user error messgaing

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1966]
### Description
- Suggest error copy update. Instead of 'Please complete all mandatory fields'
- Bug: Required for registration shows below radio buttons

### Acceptance criteria

A reason is required for deactivating this user
A reason is required for reactivating this user

- no error message should appears below radiobuttons
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/e8b2de1a-0c4c-415d-9aba-d14a9145df48)

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=153%3A17933

**Comment by euanmillar** [comment]
We need to hide the default validation message depending on context.

**Comment by anny320** [comment]
completed
