### ISSUE TITLE
UI - Pill bg colour for Pending status

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1967]
**Describe the bug**
- Pending status colour should be #FCECD9 (Amber Light)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Team page
2. See the colour of the pending status pill

**Design**
https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/2.-Components?node-id=3051%3A1514

Style file: https://www.figma.com/file/IbpqQSjnUjwA5smwe2HFwuVA/1.-Styles?node-id=96%3A53

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/8ffb73a9-05a9-4bd9-ba0a-f244a54d6fb8)

**Comment by SyedaAfrida** [comment]
Pending status color should be #FCECD9 (Amber Light). It is showing #F1B162 (Amber).

**Comment by anny320** [comment]
completed
