### ISSUE TITLE
User Submenu (•••) missing on mobile for System Admin

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1968]
**Describe the bug**
- as a system adin i should be able to edit a user on mobile
- submenu is missing on mobile

**To Reproduce**
Steps to reproduce the behaviour:
1. Login in a system admin
2. Search for an office
2. Create a user
3. Look at the office view on mobile
3. No subMenu header (top right corner). The (...) menu disappears

**Expected behaviour**
It's available and I can edit and deactivate a user on mobile

Design
Mobile: Team management table
https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4430%3A3748

Mobile user audit:
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=100%3A14

**Screenshots**
![Screenshot 2021-11-03 at 11 59 27](https://user-images.githubusercontent.com/3169954/140056220-ee44bcf0-5d05-4ad1-bd11-a8b9fa7ec138.png)
![Screenshot 2021-11-03 at 11 59 15](https://user-images.githubusercontent.com/3169954/140056228-a509ed66-0b7c-4aef-a264-71f8917f5818.png)

**Comment by euanmillar** [comment]
Closing as no image is uploaded or link to Figma so we cant tell what to do.

**Comment by anninawersun** [comment]
@euanmillar i'd like to re-open and assign this to a QA to add a video / image.

**Comment by jpye-finch** [comment]
@euanmillar @emon-swe-sust . Have added a link to the design. Note the sub menu icon is on the user audit page https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=100%3A14

**Comment by jpye-finch** [comment]
also need to fix toast on mobile. Go full width pin to the bottom of the viewport.

**Comment by SyedaAfrida** [comment]
User profile page should also have 3 dot menu as mentioned in design. Currently this is missing in mobile view.
![8](https://user-images.githubusercontent.com/94350336/156732259-b836c59d-4009-45a9-88f0-24d86043d269.png)

**Comment by SyedaAfrida** [comment]
@anny320  this ticket has passed and can be closed

![1](https://user-images.githubusercontent.com/94350336/161916429-4a5df348-c414-4886-b114-e98953f47cad.png)
![fixed](https://user-images.githubusercontent.com/94350336/161916438-387310b1-6294-4529-80ae-c4911ba7aeea.png)

**Comment by anny320** [comment]
Completed
