### ISSUE TITLE
UI - UserAudit padding

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1969]
**Describe the bug**
- page padding on mobile is 16px. So tables look good etc. other sections required additoinal padding
- User details: should have an extra 8px padding: left and right  8px -> 16px
- Padding-top below header: 40px -> 24px
- Spacing between user detials: 14px -> 16px
- Padding bottom before divider: 40px -> 24px
- Padding after divder: 30px -> 24px

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to User Audit on mobile

**Design**
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=100%3A14

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/6df4a51b-73a0-485f-b47f-c48bc0a8d8ae)

**Comment by SyedaAfrida** [comment]
@anny320 This is an old design ticket of User audit. So this can be closed

**Comment by anny320** [comment]
closed
