### ISSUE TITLE
UI - Sub-page heading back button should be blue 

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1970]
**Describe the bug**
- back button should be blue: Stormy -> DeepSea
- DeepSea is the colour used for all things a user can click.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a subpage
2. Review the back button

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/70994d21-2883-4b68-ba48-1139bb799eeb)If applicable, add screenshots to help explain your problem.

**Comment by anny320** [comment]
completed
