### ISSUE TITLE
Duplicate icon application not showing fully on Android

### ISSUE THREAD

**Issue by SabitIbnAliKhan** [opencrvs/opencrvs-core#1981]
**Describe the bug**
The duplicate application icon is only showing partly on Android 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Ready for Review'
2. Observe the duplicate icon 
3. It is only showing partly 

**Expected behaviour**
Icon should be showing fully 

**Screenshots**
![mobile_duplicateIcon](https://user-images.githubusercontent.com/44313971/91943260-1e37da00-ed1e-11ea-9247-47482d8a5ee9.jpeg)

**Smartphone (please complete the following information):**
 - Device: OnePlus5
 - OS: Android 10
 - Browser - Brave
 - Version 1.12.113

**Comment by SabitIbnAliKhan** [comment]
Please not that a similar issue occurs for the Sent for Review flag in the Sent for Review tab when logged in as Field Agent 




![UI_issue_Android](https://user-images.githubusercontent.com/44313971/92219832-e7e49100-eebc-11ea-8620-5920b8dd5afb.jpg)

**Comment by anny320** [comment]
closed
