### ISSUE TITLE
Comments are getting visible for registrars or registration agents while reviewing an application

### ISSUE THREAD

**Issue by mushrafulhoque-dsi** [opencrvs/opencrvs-core#1982]
Mayhadi's comment: 

If vaccinator write something in ‘Comments’ box and sent for registration But Registration Agent and Registrar do not find any comments from their end. Total comment box show blank.

**Comment by noboshashabnom-dsi** [comment]
Tested and verified. 
We can add comment as field agent while sending for review/register. Both registration clerk and register can see the comment and update the comment in review page.
