### ISSUE TITLE
Death registration percentage is incorrect

### ISSUE THREAD

**Issue by SabitIbnAliKhan** [opencrvs/opencrvs-core#1984]
**Describe the bug**
The death registration percentage calculation is wrong. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Performance
2. Observe the male death registered percentage

**Expected behaviour**
Calculation should be correct 

**Screenshots**
![death_percentage_wrong](https://user-images.githubusercontent.com/44313971/92099815-cb811f80-edfc-11ea-9719-69266c57a862.jpeg)

**Smartphone (please complete the following information):**
 - Device: OnePlus5
 - OS: Android 10
 - Browser - Brave
 - Version 1.12.113

**Comment by euanmillar** [comment]
Estimated data must be inserted into the database so that this can be QA-ed

**Comment by euanmillar** [comment]
This should be resolved now that Farajaland has statistical data

**Comment by SyedaAfrida** [comment]
@euanmillar There is still no estimated data in farajaland-qa to conduct this test.
![statisticalData](https://user-images.githubusercontent.com/94350336/156504454-fbcff7b6-ee6e-49ea-b2e0-cf9236acdb52.png)
