### ISSUE TITLE
A futile scrollbar appears in the "Sent Incomplete" confirmation modal. (Chrome 85.0)

### ISSUE THREAD

**Issue by noboshashabnom-dsi** [opencrvs/opencrvs-core#1989]
**Steps To Reproduce**
1. Log in as Field agent.
2. Create a birth/death application > do not complete the form.
3. From review page click > Send Incomplete.
4. Observe the confirmation modal. 

**Actual Result**
Inside the modal a scrollbar appears of no use.

**Expected behavior**
No scrollbar is needed and the text should adjust inside the modal.

**Screenshot**
![Incomplete application sent](https://user-images.githubusercontent.com/16021495/92230008-2f264e00-eecc-11ea-9262-2c5e03bfec3e.png)

**Desktop **
 - OS: Windows 10
 - Browser: Chrome Version 85.0.4183.83

**Comment by jpye-finch** [comment]
we should be increasing the height of the model

**Comment by SyedaAfrida** [comment]
@anny320 Fixed and can be closed
![#1989](https://user-images.githubusercontent.com/94350336/161479770-b658523a-f76b-474e-9dae-b55248e99b00.png)

**Comment by anny320** [comment]
completed
