### ISSUE TITLE
Performance report is not showing any data even though data is available in db for the selected month

### ISSUE THREAD

**Issue by mushrafulhoque-dsi** [opencrvs/opencrvs-core#1990]
![Screen Shot 2020-09-04 at 4.50.42 PM.png](https://images.zenhubusercontent.com/5e96a4d7f13e32a5569b4c55/d56e2063-ac94-440e-b04e-1b3ada72561d)

This error is happening because of missing estimation data for that location

**Comment by SabitIbnAliKhan** [comment]
Performance report showing now
