### ISSUE TITLE
Syncing In Progress applications

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2001]
### **Problem statement**
- In Progress application locally saved to the device are being lost when an update is required (cache needs to be cleared)
- Other reason for syncing that i cant rememebr
- 
-
- We expect Registars/Reg Agents to be online. So we should sync their applications
- We expect Field Agents to be offline. So we should give appropriate messaging to these users to send incomplete applicatons. When an update is planned. Although this would require an internet connection... 

Make a cache delete not required.
> Reasons for cache delete? What changes don't require it??

### **Proposed work**

(High-level overview of what we're building and why we think it will solve the problem).

### **Success criteria**

(The criteria that must be met in order to consider this piece of work a success)

### **User stories**

(How the product should work for various user types)

-

### **Scope**

(Current requirements)

### **Future work**

(Future requirements)

**Comment by euanmillar** [comment]
Closing as cache clear is not a normal action for a user. You experience while testing.  If they do decide to clear cache there is nothing we can do.  Same as deleting cookies.

**Comment by anninawersun** [comment]
@euanmillar - based on my understanding of this ticket - in-progress apps (e.g. drafts) are being deleted when there is an update in the system. Is that correct? If so, we do need to think about how to manage this if a lot of our users will be offline.
