### ISSUE TITLE
Review child's place of birth

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#2007]
As a user, I want to make data entry for child's place of birth as easy as possible, so that I can reduce the time required to complete the form
- Government vs. private health institution: using ref data vs. free form entry and where is this done to ensure high quality data
- Private home: use mother/father's address to minimise data input required

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

(Link to Figma)

### Copy

(Link to Notion)

### Dev-tasks??

- [ ]  Task 1

**Comment by euanmillar** [comment]
mothers fathers address is not completed at this point so it cannot be done.  The other issue is closely linked to: https://github.com/opencrvs/opencrvs-core/issues/1953 so I'm closing for now
