### ISSUE TITLE
As a Registration Agent or Registrar, I want to be able to access other agents draft forms, so that I can make sure they are completed

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#2025]
### Description

Currently, when a Field Agent,  Registration Agent, Registrar starts and saves a draft in their profile, no-one but themselves can complete it. If that user moves on or their device breaks, then the application can not be completed.

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

(Link to Figma)

### Copy

(Link to Notion)

### Dev-tasks??

- [ ]  Task 1

**Comment by euanmillar** [comment]
In this case, the application is lost.  It cannot be synced if it is not saved as an in-progess application
