### ISSUE TITLE
Feature request:  Place of birth - Hospital field should be dropdown only 

### ISSUE THREAD

**Issue by tahmidrahman-dsi** [opencrvs/opencrvs-core#2053]
Hospital field should be dropdown only instead of search and select. Users often just type and continue without selecting the hospital from the search result, specially when no search result found.

To remove confusion, hospital should be dropdown

**Comment by euanmillar** [comment]
Use this design https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/2.-Components?node-id=3500%3A3489

**Comment by euanmillar** [comment]
Error should be "No results found"
