### ISSUE TITLE
Configure birth & death registration number logic for Niue

### ISSUE THREAD

**Issue by mushrafulhoque-dsi** [opencrvs/opencrvs-core#2113]
TODO: Need the Niue registration number generation logic from Jonathon

### Dev Tasks:
- [ ] Update `generateRegistrationNumber` function in `features/generate/service.ts` (opencrvs-niue)

**Comment by jpye-finch** [comment]
@eduffus, @mushrafulhoque-dsi  Suggest we just use OpenCRVS Core default registration number logic. for now
