### ISSUE TITLE
Configure Birth certificate template

### ISSUE THREAD

**Issue by mushrafulhoque-dsi** [opencrvs/opencrvs-core#2115]
### Description
- Uses the default template we have already built. 
- Replaces emblem with the Niue flag.

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1181%3A694

![darren-niue-signature.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/f95e89bc-6806-4a28-9de8-af0fd666777f)

### Dev-tasks
- [x] Update birth certificate layout - 3

**Comment by jpye-finch** [comment]
@Kayumuzzaman 
The design is the same as Zambia. 
I added an example with digital signature. So the name of the Registrar is shown below. 

Sorry I thought we weren't using digital signatures based on the discussions earlier this week.
