### ISSUE TITLE
Phone validation, attachment type mapping is hardcoded in Core

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2126]
### Dev Tasks:
- [x] Extract phone number validation logic from core to resource service  - 2

**Comment by mushrafulhoque-dsi** [comment]
Made phone number validation and masking pattern are now configurable from the resource package.

AttachTypes are still hardcoded in `client` and `gateway` schemas. Need more discussion with Euan about this.

**Comment by euanmillar** [comment]
closed due to inactivity
