### ISSUE TITLE
Form field widths -> maxWidth 344px

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2128]
### Description

Some form fields are extra wide. 

This ticket is to update the form field width so they all have max width of 344px. Same as dropdowns

### Design
https://www.figma.com/file/IsPvujBG34IUjctUKt9WlyWs/4.-New-Application?node-id=1315%3A898

### Dev-tasks

- [ ] Remove form field width as a config option for standard inputs, e.g.  not birth weight
- [ ] Set standard input width in core

**Comment by jpye-finch** [comment]
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/de4cd122-dfd5-41c0-be4d-0138d54501bb)

All text inputs and dropdowns in the application form. 

Except date of birth and weight of child

**Comment by anny320** [comment]
completed
