### ISSUE TITLE
Weight at birth - form width and label

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2129]
### Description

Update the width of form field to -> 4 character width (78px).
Updates label to use Stormy
Adds padding between form field and label 

### Design

https://www.figma.com/file/IsPvujBG34IUjctUKt9WlyWs/4.-New-Application?node-id=1325%3A222

### Dev-tasks

- [ ]  Adjust field size on form config JSON

**Comment by anny320** [comment]
completed
