### ISSUE TITLE
In Death application, "Date Medical Practitioner last saw Deceased" throws incorrect error "Must be a valid birth date"

### ISSUE THREAD

**Issue by tamkinmahmud-dsi** [opencrvs/opencrvs-core#2141]
**Describe the bug**
In death application, "Date Medical Practitioner last saw Deceased" throws incorrect error "Must be a valid birth date" 

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in as Field Agent/Registrar/Registration Agent
2. Create a death application
3. Provide Date Medical Practitioner last saw Deceased: 30/05/2022 (DD/MM/YYYY)
4. Click Tab button
5. See the error

**Actual Results**
Validation shows -
1. In "Date Medical Practitioner last saw Deceased" - "Must be a valid birth date"

**Expected behaviour**
Should show "Must be a valid date"

**Screenshots**
![Selection_008.png](https://images.zenhubusercontent.com/60b47748c75898083f9b17ec/1c7e3334-c431-441c-ad54-b64f0f7ec432)

**Desktop:**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by mushrafulhoque-dsi** [comment]
Same as 2143
