### ISSUE TITLE
In ready for review and sent for updates page, any update of name, contact info or DOB/DOD in the review page does not reflect in the application preview information.

### ISSUE THREAD

**Issue by tamkin-bracu** [opencrvs/opencrvs-core#2163]
**Describe the bug**
In ready for review and sent for updates page, any update of contact info, name  or DOB/DOD in the review page does not reflect in the application preview information.

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as Registration Agent/Registrar
2. Navigate to Ready for review/Sent for Updates page
4. Download the application and Click on Review/Update
5. Update the name of the child/deceased, DOB/DOD and contact info
6. Click Exit
7. Check the application list and click on the application
8. Check contact info, DOD/DOB and Date of event
9. See the error

**Observations**
Name, Date of event, DOD/DOB, Contact info does not show the updated info.

**Expected behaviour**
Name, Date of event, DOD/DOB, Contact info should show the updated info.

**Screenshots**
![Selection_014.png](https://images.zenhubusercontent.com/60b47748c75898083f9b17ec/1b157b7e-5d37-4f79-96a8-28fa4361da78)
![Selection_016.png](https://images.zenhubusercontent.com/60b47748c75898083f9b17ec/80654dab-e521-4012-9f27-fc41794f48bf)
![Selection_013.png](https://images.zenhubusercontent.com/60b47748c75898083f9b17ec/051d9566-112b-420d-a870-6d65280181a3)

https://user-images.githubusercontent.com/49532098/125325312-9ae60c80-e362-11eb-9358-45718d882e3b.mp4

**Comment by euanmillar** [comment]
When we save an update to a draft in Ready For Review, if the change has happened to the birth or death individual's name, contact phone number or date of birth, we must find the item in the IndexedDB and update it.

When the update is submitted / registered, we should check that the Elastic Search details are also updated.  We need to look at the commands to the search microservice to check that the birth or death individual's name, contact phone number or date of birth are updated in Elastic Search in this case

I think that in the Expanded View of any item in work queue in the Ready for Review column,
