### ISSUE TITLE
In application review page, no information found for the Informant's relation to the child/deceased

### ISSUE THREAD

**Issue by tamkin-bracu** [opencrvs/opencrvs-core#2181]
**To Reproduce**
Steps to reproduce the behaviour:
1. Login as Field agent/Registrar/Registration Agent
2. Create a birth/death application
3. Navigate to application review page
4. Check the Application details section

**Observations**
No info found for the informant's relationship to the child/deceased

**Expected behaviour**
Should show the Informant's relationship to the child/deceased

**Screenshots**
**Current View:**
![Selection_029.png](https://images.zenhubusercontent.com/60b47748c75898083f9b17ec/5ce44bc8-bdef-4e2f-b2cd-8c0935dc1120)

**Possible Fix:**
![Selection_030.png](https://images.zenhubusercontent.com/60b47748c75898083f9b17ec/cf149019-0f83-457a-a8f9-2a35f96f92c9)

**Comment by euanmillar** [comment]
The issue appears to be related to Death ass Birth is correct..

Here is birth:

![Screenshot 2021-11-10 at 10 30 00](https://user-images.githubusercontent.com/3169954/141097047-786d3510-490b-42e0-8638-59cdc9cc9052.png)

Death is different and this is strange:

![Screenshot 2021-11-10 at 10 28 55](https://user-images.githubusercontent.com/3169954/141097104-93388aaa-41f4-40f1-b321-6b45c7ac4125.png)
