### ISSUE TITLE
Could not submit the crash report

### ISSUE THREAD

**Issue by tamkin-bracu** [opencrvs/opencrvs-core#2195]
**To Reproduce**
Steps to reproduce the behaviour:
Check the video for better understanding:
https://images.zenhubusercontent.com/91778759/700bee15-48d7-4030-8906-c7e96df13692/opencrvs_registe.mp4

**Comment by Kayumuzzaman** [comment]
Violating Content Security Policy (CSP) is occurring this issue, reconfiguration or reinstall may resolve this issue.
References:
1. https://blog.sentry.io/2018/09/04/how-sentry-captures-csp-violations
2. https://docs.sentry.io/product/security-policy-reporting/

![Issue-2195](https://user-images.githubusercontent.com/46846503/125623089-ba9df16f-e8af-4844-a502-09fab3c1b1d7.png)

**Comment by Kayumuzzaman** [comment]
Violating Content Security Policy (CSP) is occurring this issue, reconfiguration or reinstall may resolve this issue.
References:

1. https://blog.sentry.io/2018/09/04/how-sentry-captures-csp-violations
2. https://docs.sentry.io/product/security-policy-reporting/

![Issue-2195](https://user-images.githubusercontent.com/46846503/125624288-a4beefb4-8bf2-4ded-b65f-5b3bb7b6d1bf.png)

**Comment by youshamahmood96** [comment]
https://forum.sentry.io/t/required-content-security-policy/4484
here it is stated that an update may break some custom plugins, probably similar to our case

**Comment by euanmillar** [comment]
Something is not right.  Getting this error on the staging environment:

```The Content-Security-Policy directive name '*.sentry.io/' contains one or more invalid characters. Only ASCII alphanumeric characters or dashes '-' are allowed in directive names.
```

**Comment by euanmillar** [comment]
Can we try this as described here https://forum.sentry.io/t/required-content-security-policy/4484?

```
connect-src: *.sentry.io
```
