### ISSUE TITLE
In-progress Application | Application get invisible from in-progress tab

### ISSUE THREAD

**Issue by ehsanulhaque-dsi** [opencrvs/opencrvs-core#2213]
Steps to reproduce:
1. Login as a valid user
2. Navigate the the in-progress tab 
3. Try to update any application of the user and navigate to the application review page
4. Click the change link of "What is their contact number?"
5. Update the number and click the **Exit** button 

Observation: Observe that the application is no more visible in the **In-Progress** tab

Expectation: The application should be visible in the in-progress tab since the user did not delete the application or clear the index-db

For more understanding:
https://images.zenhubusercontent.com/91778759/33b234c1-f7fe-4741-80d1-3f3c3454adc6/invisible_issue.mp4

**Comment by euanmillar** [comment]
When a draft is saved we get a draftId, so for example the review link checks if draftId exists.  We should change the Exit button to be a Save & Exit button if the draftId exists, otherwise the button should say Exit and perform as usual
