### ISSUE TITLE
Certificate| Late fees is counted after 15 days which should be after 14 days

### ISSUE THREAD

**Issue by tamkinmahmud-dsi** [opencrvs/opencrvs-core#2224]
**Description**
Late registration fees should be counted after 14 days but it is counted after 15 days.

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as Registrar
2. Complete a birth/death application where DOB/DOD is 14 days ago (Late)
3. Register the application 
4. Go to Ready for print page
5. Click Print and navigate to Payment page
6. See the registration fees

**Observations**
Registration fees is 28$

**Expected behaviour**
Registration fees should be 78$ for the late registration

**Screenshots**
![date2.png](https://images.zenhubusercontent.com/60b47748c75898083f9b17ec/2b04ff58-c785-4fb2-9efc-fd5e9ee69fa7)
![date1.png](https://images.zenhubusercontent.com/60b47748c75898083f9b17ec/f36655d9-bc62-4d7e-8feb-8f29c39ff705)

**Comment by mushrafulhoque-dsi** [comment]
Late payment should be applicable after 14 days. So it doesn't look like a valid issue to me.

**Comment by tamkinmahmud-dsi** [comment]
Not a valid issue
