### ISSUE TITLE
Integration configuration

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2277]
### **Problem statement (post June scope)**

There is no easy way for a non-technical user to set up integration points between OpenCRVS and other systems.

### **Proposed work**

- Show a list of client integrations
- Allow users to create a new clients
- Type of clients
    - Notification
    - ID verification
    - External CRVS system 
    - Webhook

https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8478%3A44119
### **Success criteria**

- Able to add / remove a client
    - Notification
    - ID verification
    - Webhook (birth / death registration)
- Able to enable / disable a client
- Able to see all the necessary information to be able to configure my client
- After configuration is complete and enabled, the client works as designed

System enables System Admin to create, edit and delete connectable external systems and share client_ids and client_secrets

- User login
- List external systems
- Edit / Delete systems

**Comment by SyedaAfrida** [comment]
**Bug:**
System crash occurs when clicked integration
![int conf](https://user-images.githubusercontent.com/94350336/208629062-36444121-1fce-48d2-9ffe-c8c295263ade.png)

**Comment by Zangetsu101** [comment]
@anny320 I think we can close this epic right?

**Comment by anny320** [comment]
closed
