### ISSUE TITLE
Bulk print certificates

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2278]
### Problem statement
To manage workloads certificates are often printed in advance of collection to be signed by the Registrar in one sitting. To be then issued on a collection day. 

Currently each certificate has to be individually printed in advance which is time consuming. So we need a quick way to print all certificates in bulk and then track the issuance. 

### Proposed work
- Adds a button to Ready to print workqueue 'Print all'
- Confirmation model to print all with option to print all receipts also
- A PDF is generated with all certificates
- All records move to Ready to issue workqueue

### User stories
As a Reg Agent or Registrar I want to bulk print all certificates in advance
As a National System Admin, I want to configurable bulk printing on/off

**Comment by euanmillar** [comment]
@jpye-finch I think this should go to In Design column until we talk about it.  I have a bunch of questions.

**Comment by jpye-finch** [comment]
closing as copy of. have copied content to that ticket [Bulk print all certificates in advance#4364](https://github.com/opencrvs/opencrvs-core/issues/4364)
