### ISSUE TITLE
Previously visited sections/groups not updating

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#2292]
**Describe the bug**
When going to a previously visited section, all the errors (if any) should be shown initially.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new birth application
1. Go to Child section
2. Scroll down to bottom
2. Click on 'Continue'
3. Click on 'Back'

**Expected behaviour**
![Expected](https://user-images.githubusercontent.com/29002716/142614591-e2c4867a-ac6f-45cc-9633-2435571a9c6f.gif)

**Current behaviour**
![Current](https://user-images.githubusercontent.com/29002716/142614633-fbb9575b-712a-4578-b63a-81e39908986e.gif)

**Comment by euanmillar** [comment]
@Zangetsu101 I really like this improvement.  Good catch.  Lets just check with the design team what they think too.

@jpye-finch what do you think of this improvement.  I think it kinda makes sense?

**Comment by jpye-finch** [comment]
Yes this is an improvement. Similar to navigating back to the page from the review page
