### ISSUE TITLE
Replace react-styleguidist with react-storybook component library

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2297]
- [x] React styleguidist should be replaced with react-storybook
- [x] Make basic stories.mdx just render component in the story
- [ ] we need to remove all un-used components.  search for component in core and zambia and make sure that it is not used in login and client app.  If so, delete it
- [x] The PDF component in component library, doesnt work, and we dont need it to work, because we are going to deprecate it.  So, you dont need to make a story for this.
- [ ] It would be really nice to see styles and fonts in the storybook somehow.  Dont know if this is possible:  https://www.figma.com/file/IbpqQSjnUjwA5smwe2HFwuVA/1.-Styles?node-id=96%3A53

**Comment by jpye-finch** [comment]
soooo looking forward to this! :D

**Comment by soumita-dsi** [comment]
@euanmillar I have attached the link of the doc file listing all unused components.....

https://docs.google.com/document/d/1COL2dK3QTv20lxxymgor_9wpGonJIQgn29uavCIGWVQ/edit
