### ISSUE TITLE
"District" appears twice in Performance tab

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#2299]
**Describe the bug**
"District" appears twice

**To Reproduce**
1. Login as a Registrar
2. Go to 'Performance'

**Expected behavior**
District should appear only once

**Screenshots**
![district district](https://user-images.githubusercontent.com/29002716/143205128-1f8e8952-ea53-4407-9b78-e364b884ae3e.png)

**Comment by anny320** [comment]
Completed
