### ISSUE TITLE
System crashed when coming back from performance reports details

### ISSUE THREAD

**Issue by emon-swe-sust** [opencrvs/opencrvs-core#2308]
**Describe the bug**
System crashed when coming back from performance reports details

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as Registrar
2. Go to Performance > Select Reports > click any months from Birts or Deaths

**Expected behaviour**
Will back to the previous page smoothly when clicking back icon

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - BrowserChrome 
![bug](https://user-images.githubusercontent.com/43314141/143426354-9acee84d-1a15-48be-9474-8530c5e25d72.gif)

**Comment by anny320** [comment]
completed
