### ISSUE TITLE
The title for the can't login option in Login seems to be wrong

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#2316]
**Describe the bug**
The title for the can't login option in Login seems to be wrong

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Login > Can't login
2. Select either of the options and Continue

**Screenshots**
![image](https://user-images.githubusercontent.com/29002716/144198360-38b2c9a3-5e29-4eff-a8f7-9ab1badd9c46.png)

linked to this ticket [](https://app.zenhub.com/workspaces/opencrvs-core-5afeded64a54b06b54a969b2/issues/opencrvs/opencrvs-core/2913)

**Comment by emon-swe-sust** [comment]
What will be the appropriate title?

**Comment by anny320** [comment]
this issue is not yet resolved ![Screenshot 2022-04-22 at 08.51.50.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/dc1a30ef-cd8b-46bd-883f-145d16eb296e) @SyedaAfrida @Zangetsu101  spelling for associated needs to be fixed.

**Comment by anny320** [comment]
this issue is not yet resolved ![Screenshot 2022-04-22 at 08.51.50.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/dc1a30ef-cd8b-46bd-883f-145d16eb296e) also see ticket number  raised with similar issue

**Comment by Zangetsu101** [comment]
#2344 solves the issue described in this ticket. @anny320 #2913 is a separate bug altogether so I think this ticket should be closed.

**Comment by anny320** [comment]
please could you also fix the typo of the word associated?

**Comment by anny320** [comment]
@Zangetsu101 could the typo for the word associated be fixed? its still reading wrong ![Screenshot 2022-05-20 at 11.20.44.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/81ef3726-526a-43a8-b66f-1c168b4f832b)

**Comment by Zangetsu101** [comment]
@anny320 Yes definitely but as you already have a separate ticket for that maybe you should close this one as this ticket is not related to that 'associated' part

**Comment by anny320** [comment]
ok will close this one, thanks
