### ISSUE TITLE
Field Agent user's type cannot be changed from Edit details in  Sysadmin 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2318]
**Steps To Reproduce**
1. Login as Sysadmin
2. Go to Team > Select a location.
3. Click edit details who has "field agent" role assigned
4. Go to Account details> Type> change
5. Click Type dropdown in Edit User page

**Actual Result**
Showing only selected Field Agent type

Expected behavior
Should show both "CHA" and "Hospital" in dropdown

**Screenshots**
![1.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/44ea71ea-57ed-49b2-85dc-7c85e90a82e1)

![2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/a839871f-619f-4c2f-88ce-9be2d9e7b36b)

**Desktop:**

OS: Windows 10 
Browser: Chrome

**Comment by anny320** [comment]
completed
