### ISSUE TITLE
Add blank footer to all pages

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2328]
### Description

- We don't have a footer so content ends at the bottom of the view point. 
- Suggest we add a blank footer so the pages scrolls further and the final content eg buttons sits further up in the viewport. 
- desktop height: 160px
- mobile height 80px

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=7010%3A148030

### Dev-tasks

- [ ]  Task 1

**Comment by euanmillar** [comment]
Awaiting a Figma file and design

**Comment by jpye-finch** [comment]
design added

**Comment by euanmillar** [comment]
@jpye-finch when you say a blank footer, do you actually just mean a margin underneath wherever Content component is used?  Saying this needs to be added on All pages is just too general to develop and QA.

**Comment by euanmillar** [comment]
@jpye-finch happy to close in place of UI comp library improvements
