### ISSUE TITLE
Cannot send any death application when manner of death is selected as "Manner undetermined"

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2331]
**Steps To Reproduce:**
1. Login as Field agent/ Registration clerk/ Registrar
2. Click "+" sign to create new application
3. Click Death in "What type of event do you want to declare?"
4. Click "Manner undetermined" in "What was the manner of death?"
5. Click Send for review/ Send for approval/ Register (depending on User type)
6. Observe the application in "sent for review"

**Actual Result:**
Showing "waiting to send" for that application

**Expected Result:**
Submission should be completed and should generate a Tracking Id

**Screenshot:**
![Kazam_screenshot_00001.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/0425dad7-4458-4652-b8e2-08ce94661a85)

**Desktop:**
OS: Windows 10, Ubuntu 
Browser: Chrome

**Comment by SyedaAfrida** [comment]
same issue also found in birth application when "Attendant at birth" is selected as "Traditional birth attendant"

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

retest ss:
![dd](https://user-images.githubusercontent.com/105624748/172117254-b4f92cfd-6716-4817-90be-1e51c28f7045.PNG)

**Comment by anny320** [comment]
completed

**Comment by SyedaAfrida** [comment]
Previously This ticket included two similar bug- 
1) in death application when selected manner undetermined 
2) in birth application when selected traditional birth attendant
Currently the second bug is reappearing again.
When "Attendant at birth" is selected as "Traditional birth attendant" the birth application is not submitted properly.

**Comment by SyedaAfrida** [comment]
@anny320 both the bugs of this ticket is now passed and can be closed

**Bug for manner undetermined**
![manner1](https://user-images.githubusercontent.com/94350336/179458642-e84a7e1d-3697-4377-a967-758159affd47.png)

**Bug fort traditional birth attendant**
![trad1](https://user-images.githubusercontent.com/94350336/179458650-68976d33-a801-49aa-9446-423e8844b648.png)

**Comment by anny320** [comment]
completed
