### ISSUE TITLE
System crash when Performance oversight and Performance management selected as role for creating new user

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2336]
**Bug Description:**
System crash when creating new user as role Performance oversight and Performance management in Sysadmin

**Steps to Reproduce:**
1. Login as Sysadmin
2. Click Team
3. Search any office
4. Click new user
5. Select Role> Performance oversight / Performance management

**Actual Result:**
System crash when Performance oversight and Performance management is selected from dropdown

**Expected Result:**
Should be able to select the role and create new user

**Screen recording:**
https://www.loom.com/share/04aa4e8031314391bd0856cb1407ebc2

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by anny320** [comment]
completed
