### ISSUE TITLE
Overlapping Profile menu with status window

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2337]
**Bug Description:**
Cannot view profile menu when status window is open

**Steps to Reproduce:**
1. Login as Registration clerk/ Registrar/ SysAdmin
2. Click Performance
3. Click Status
4. Click Profile icon

**Actual Result:**
Profile menu gets hidden by Status window

**Expected Result:**
User should be able to view profile menu

**Screenshot:**
![after (2).png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/8db7adcf-6499-4352-b6c5-2c08e46a9eeb)

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by anny320** [comment]
completed

**Comment by anny320** [comment]
completed
