### ISSUE TITLE
Amend the Github actions to run the whole OpenCRVS stack on a dedicated VM and run Cypress tests against it

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2339]
Lets set up a self-hosted runner and CI can run Cypress against it.

https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

This approach should be followed for PRs and any code merged into main.

- [x] Set up a VM 
- [x] install Docker
- [x] In either a Github Action, or a Shell script on the VM, checkout the latest Core code and latest Zambia resources package, run the stack, populate the database, finally check that the services are running. wait-on http://localhost:<PORT> for all services
- [x] Github action should run Cypress tests

This could be helpful: https://github.com/cypress-io/github-action#wait-on

**Comment by yeasinhossain-dsi** [comment]
A PR is given which will only run tests for ocrvs-2339 branch. Once All the Cypress tests are fixed we can change the `on` event for all the branches & also change the resource package to main branch (Have a look at `Running the Country specific resource package` step)
