### ISSUE TITLE
Father's Residential address fields needs to to hidden when user do not have father's details

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2341]
**Bug Description:**
Showing "No" in father's residential address when user choose "no" in "Do you have the father's details." It is not required to show residential address in such case. See the screenshot for clarification.

**Steps to Reproduce:**
1. Login as Field Agent/ Registration clerk
2. Declare a birth application
3. Father's details> Do you have the father's details? >Click "No"
4. Click Send for review/ Send for approval (depending on User type)
5. Go to ready to review
6. For that application download> review
7. Observe father's details

**Actual Result:**
Showing "No" in father's residential address.

**Expected Result:**
No need to show residential address since  "no" is chosen in "Do you have the father's details."

**Screenshot:**
![father'sDetails_no.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/d8389a7f-a26a-4a87-8807-aa1874818426)

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by SyedaAfrida** [comment]
Though the previous bug is fixed, I think a similar bug has produced. 
**Step to reproduce:**
1. Login as field agent and declare an birth application
2. Keep mandatory fields in mother's details page empty
3. Keep mandatory fields in father's details page empty
4. Submit incomplete application
5. Login as registration agent
6. Go to in progress> field agent
7. Download and review that application

**Actual result:** lots of "No" in mother details and "Do you have father's details" turned No.

**Screen recording:**
https://user-images.githubusercontent.com/94350336/155986176-6743d387-8231-4c5f-b471-75d667c7aaec.mp4

**Comment by emon-swe-sust** [comment]
> Though the previous bug is fixed, I think a similar bug has produced. **Step to reproduce:**
> 
> 1. Login as field agent and declare an birth application
> 2. Keep mandatory fields in mother's details page empty
> 3. Keep mandatory fields in father's details page empty
> 4. Submit incomplete application
> 5. Login as registration agent
> 6. Go to in progress> field agent
> 7. Download and review that application
> 
> **Actual result:** lots of "No" in mother details and "Do you have father's details" turned No.
> 
> **Screen recording:** https://user-images.githubusercontent.com/94350336/155986176-6743d387-8231-4c5f-b471-75d667c7aaec.mp4

**Comment by emon-swe-sust** [comment]
> Though the previous bug is fixed, I think a similar bug has produced. **Step to reproduce:**
> 
> 1. Login as field agent and declare an birth application
> 2. Keep mandatory fields in mother's details page empty
> 3. Keep mandatory fields in father's details page empty
> 4. Submit incomplete application
> 5. Login as registration agent
> 6. Go to in progress> field agent
> 7. Download and review that application
> 
> **Actual result:** lots of "No" in mother details and "Do you have father's details" turned No.
> 
> **Screen recording:** https://user-images.githubusercontent.com/94350336/155986176-6743d387-8231-4c5f-b471-75d667c7aaec.mp4

I guess this is expected behavior, this is fixed only for father's details. And not for other fields.

**Comment by atiqzaman-dsi** [comment]
@euanmillar should we create a new ticket for the mother section change? I think showing "No" for mother section is not a valid use case.

**Comment by SyedaAfrida** [comment]
I have created a new ticket for the bug mentioned in the comment. #2651
