### ISSUE TITLE
Data for Mother's "Place of heritage" and "Is her usual place of residence the same as her residential address?" showing incorrect when viewed by registrar

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2346]
**Bug Description:**
1) Even though data for  "Place of heritage" is given by field agent, no data is found when reviewed by registrar.
2) "Is her usual place of residence the same as her residential address?" set "yes" by field agent, but shows "No" when reviewed by registrar.

**Steps to Reproduce:**
1. Login as field agent
2.  Complete a birth application
3. Click "Send for Review"
4. Login as Registrar
5. Go to "Send for review"
6. Download that application
7. Click "Review"
8. Observe "Place of heritage" and "Is her usual place of residence the same as her residential address?" 

**Actual Result:**
Showing "Country required for registration" in "Place of heritage" and "Current address" and in "Is her usual place of residence the same as her residential address?" showing NO.

**Expected Result:**
1) "Place of heritage" should have data set by field agent 
2) "Is her usual place of residence the same as her residential address?" should be YES as set by field agent

**Screen Recording:**
https://www.loom.com/share/0f34e9eac6924bae9d1946cfa1a770bd

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by emon-swe-sust** [comment]
I can't generate this bug, I think this is fixed with recent deployment.

**Comment by SyedaAfrida** [comment]
I could re-generate this bug again in farajaland-staging

**Comment by azantor64** [comment]
@anny320  ,this ticket can be closed as it is tested.

**Comment by anny320** [comment]
completed
