### ISSUE TITLE
Able to search an application whose certificate was collected earlier and print that certificate multiple times

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2350]
**Bug Description:**
1) Printed application can be viewed when Searched with name/ tracking id
2) Certificate can be printed multiple times

**Steps to Reproduce:**
1. Login as Registration clerk/ Registrar
2.  Search an already printed application with name/ tracking Id from search field
3. Click download
4. Click Print
5. Click any radio button in "Who is collecting the certificate?"
6. Click "Confirm and Print"
7. Click "Print"
8. Click "Print" and save with file name

**Actual Result:**
1) Able to search an application whose certificate was collected earlier
2) Showing Print button
3) Certificate can be printed multiple times

**Expected Result:**
Should not view application whose certificate was collected earlier and should not have option to print multiple times

**Screenshot:**
![print_multiple_times.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/c6c44ddf-d0e0-49fd-b150-c18d10f3261e)

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by euanmillar** [comment]
Our belief is this is not a bug as such but the user experience will be improved in the future
