### ISSUE TITLE
As A National System Administrator, I can see a Certificate Config Page

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2355]
### Description

As A National System Administrator, I can see a Certificate Config Page when I log in.
We need to create a menu and a blank screen where certificate config takes place

### Acceptance criteria

GIVEN I am a National System Administrator
WHEN I log in
THEN I see a main menu navigation with the items "Configuration" and "Team" and when I click "Configuration", I see a sub navigation containing the item "Certificates".

GIVEN I am a National System Administrator
WHEN I click the "Certificates" link
THEN I see a blank page where Certificate configuration can occur

### Design

https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=11%3A922

### Copy

To be confirmed later

### Dev-tasks

- [x]  Create the main menu, sub menu and blank page for this activity.

**Comment by anny320** [comment]
completed
