### ISSUE TITLE
As A National System Adminnistrator, I can see a list of Event Certificates which I can choose to edit

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2357]
### Description

As A National System Adminnistrator, I can see a list of Event Certificates which I can choose to edit

### Acceptance criteria

GIVEN I am a National System Adminnistrator
WHEN click "Certificates"
THEN I can see a list of vital events and the list contains certificates with a menu of actions "Action Menu"

### Design

https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=11%3A922

### Copy

To be confirmed

### Dev-tasks

- [x]  We should re-use DataSection and DataRow as the base component for the table.  Add an optional sub menu of actions ... re-use ToggleMenu and rename it to ActionMenu
- [x] Create new content keys for the copy in the languages JSON

**Comment by anny320** [comment]
completed
