### ISSUE TITLE
Back end - Certificate config

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2358]
- [x] In the config microservice Yeasin created, we need a new schema for certificates

svgCode
svgFilename
svgDateUpdated
svgDateCreated
user
event
status: ACTIVE / INACTIVE - 1

- [x] Create basic CRUD handlers with REST formatted URLs for the SVG - 2
- [x] Set up Jest in config microservice - 2
- [x] maybe use a library like [this](https://github.com/sindresorhus/is-svg#readme) to check if the code is SVG and return associated errors before saving - 1
- [x] Create GraphQL queries and resolvers for the CRUD handlers restricted to national system administrator JWT scope - 3
- [x] We need a bespoke handler to get the active certificates for all events? - 1
- [x] We need a GraphQL query to get the active certificates for all events - 1
- [x]  Write jest tests for GraphQL resolvers - 1
- [x] Add the config database backup zip in the list of backup zips which appear in backup-restore.sh, clear-all-data.sh, emergency-backup-restore.sh etc - 1
- [x] We must export an SVG from Figma, copy the data points from the certificate JSON in resources package, convert to handlebars, paste into SVG and use Postman to insert a default certificate, then export a backup zip of the config database - 3
- [x] In the ReviewCertificateAction and associated utility files, we need to replace the PDF with SVG retrieved via GraphQL and the config microservice. - 3
- [ ] We need to remove existing JSON and PDF utilities from the resources package for certificates - 1
- [x] When the client loads we need to replace the offline certificate PDF request from resources and instead request from GraphQL config microservice and save accordingly into IndexedDB - 2
- [x] Whenever a certificate CRUD action is performed, call the user-mgnt userAuditHandler to track the action as "Certificate updated". - 2

**Comment by sadmananik** [comment]
We can not remove PDF utilities until as we use pdf utilities for MoneyReceipt implementations.

- [ ]  We may have to use a library to print SVG image
