### ISSUE TITLE
System crash for input in non-mandatory fields for applicant's residential address in Death application

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2362]
**Bug Description:**
In Death application System crash when given input in following fields-
1. State
2. District
3. City / Town
4. Address Line 1
5. Address Line 2
6. Address Line 3
7. Postcode / Zip

**Steps to Reproduce:**
1. Declare a death application
2. In applicant's details> give input in State, District, City / Town, Address Line 1, Address Line 2,  Address Line 3, Postcode / Zip
3. Complete full application and proceed towards review page

**Actual Result:**
System crash and the application is found in "in progress". Cannot update from "in progress" also.

**Expected Result:**
Should be able to input data on the above mentioned fields and application should be able to submit properly

**Screen Recording:**
https://images.zenhubusercontent.com/91778759/7da1f2fb-66b2-40c7-b4d2-d7682faecc2a/loom___free_screen___video_recording_software___20_december_2021.mp4

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by euanmillar** [comment]
Will resolve using the new death flow

**Comment by azantor64** [comment]
https://user-images.githubusercontent.com/70468099/171609244-c97d31a2-f627-40c4-9b77-971dc6cfa052.mp4

Not cashed. tested passed. can be closed. @anny320

**Comment by anny320** [comment]
completed
