### ISSUE TITLE
Mysterious behavior happend when to edit user location

### ISSUE THREAD

**Issue by emon-swe-sust** [opencrvs/opencrvs-core#2371]
Mysterious behaviour occured when to change the location of an user.
Steps to reproduce:
1. login as a sysadmin
2. go to team > select user > click edit details > change registration office

![mystery](https://user-images.githubusercontent.com/43314141/147045215-d2fafa1c-9fc5-42bc-9394-5760d89eaed0.gif)

**Comment by SyedaAfrida** [comment]
According to local system admin business logic, Local system admin should not have option to change registration office location while editing details or creating new user. Created new ticket for that. #2597

**Comment by SyedaAfrida** [comment]
@anny320 since #2597 is fixed this can be closed also

**Comment by anny320** [comment]
completed
