### ISSUE TITLE
As a user I want to navigate to different parts of the application using a side nav

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2376]
### Description

- nav to vital statistics
- nav to reports
- nav to team page

### Acceptance criteria

GIVEN I am on a desktop
WHEN I login as a Field Agent
THEN I can see nav options to In Progress, Sent for Review, Require Updates

GIVEN I am on a desktop
WHEN I login as a Registration Agent
THEN I can see nav options to ...

GIVEN I am on a desktop
WHEN I login as a Registrar
THEN I can see nav options to ...

GIVEN I am on a desktop
WHEN I login as a Local System Administrator
THEN I can see nav options to ...

GIVEN I am on a desktop
WHEN I login as a National System Administrator
THEN I can see nav options to ...

### Design

https://www.figma.com/file/RGC6yAKF1FAVv8ar4VTeGl/OpenCRVS-V3?node-id=3%3A1362

### Future

Future component, search and header look and feel for your reference ...

https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4535%3A27222

### Dev-tasks

- [x]  Make sure that the existing rules are followed for different user types seeing different application section links in the menu. Additionally remove the existing application section links in the header.  In the Component Library, the LeftNavigation must have flexible extra sections with  a separator - 2
- [x] Mobile view should be addressed with the nested items - 2

**Comment by anny320** [comment]
completed
