### ISSUE TITLE
Correct record

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2377]
### **Problem statement**

- mistake happen, omissions are made. So a record needs to be corrected
- maternity and paternity can be disputed, sex and name can change. So a record needs to be corrected

### **Proposed work**

- create correct record workflow
- add 'correct record' button to record audit page and certificate preview page
- depending on the field/s a registrar can make a correction
- depending on the field/s must send the correction for approval
- a National Registrar has a workqueue of correction requests

### **Success criteria**

-

**Comment by SyedaAfrida** [comment]
**Bug:**
 Correct record button should not be in registration agent. Correct record button is available in both registration agent and registrar at present
