### ISSUE TITLE
Component: Content

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2379]
### Description

- update/create Content component
- Sizes:
1. Large (max width 1128px, minimum margin right and left 24px) 
2. Medium (max width 778px, minimum margin right and left 24px) 

- Takes an Icon 40x40px
- Takes a title
- hide/show top secondary button (small)
- hide/show supporting copy
- hide/show bottom primary and secondary buttons (large)

### Design

https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4460%3A6740

### Dev-tasks

- [x]  Task 1

**Comment by anny320** [comment]
completed

**Comment by anny320** [comment]
completed
