### ISSUE TITLE
Settings layout improvement

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2381]
### Description

- simplfied layout of settings page
- uses layout component [ContentMedium](https://app.zenhub.com/workspaces/opencrvs-core-5afeded64a54b06b54a969b2/issues/opencrvs/opencrvs-core/2379)
- uses ListView

### Design
https://www.figma.com/file/RGC6yAKF1FAVv8ar4VTeGl/OpenCRVS-V3?node-id=3%3A204

### Dev-tasks

- [ ]  Refactor Content component in various places to include BodyContainer as per @atiqzaman-dsi  comment here: https://github.com/opencrvs/opencrvs-core/pull/2750#discussion_r832812509

**Comment by euanmillar** [comment]
Blocked until ListView is done

**Comment by jpye-finch** [comment]
@euanmillar ListView has been added. This can now be unblocked to use the Content component.

**Comment by euanmillar** [comment]
@jpye-finch to share standard mobile view for Content component

**Comment by euanmillar** [comment]
REquires help from @jpye-finch

**Comment by azantor64** [comment]
@anny320  **This is tested both on web and mobile view. You can close it**

**Comment by anny320** [comment]
completed
