### ISSUE TITLE
Top nav improvements to UI

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2382]
### Description

Header UI

- changes default background colour to white
- gets rid of shadow!
- [ui update to new application button](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4380%3A3164)

Search
- ui updates to search
- hover state, active state
- [ui update to search filter](https://www.figma.com/file/RGC6yAKF1FAVv8ar4VTeGl/OpenCRVS-V3?node-id=215%3A9828)
- [responsiveness at small screen widths ](https://www.figma.com/file/RGC6yAKF1FAVv8ar4VTeGl/OpenCRVS-V3?node-id=306%3A14522)

Profile
- hover state for profile image
- [update to profile select (settings, and logout)](https://www.figma.com/file/RGC6yAKF1FAVv8ar4VTeGl/OpenCRVS-V3?node-id=306%3A11152)

###Acceptance criteria
GIVEN I hover on the search bar
THEN show the hover state

GIVEN I click on the search bar
THEN show the active state

GIVEN I click on the search icon
THEN search my query

GIVEN I hover on the search filter select
THEN show the hover state

GIVEN I click on the search filter select
THEN show the filter select

GIVEN I select a different search filter
THEN update the search filter

--

GIVEN I hover on the profile image
THEN show the [hover](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4380%3A3207) state

GIVEN I select on the profile image
THEN show the [profile dropdown menu](https://www.figma.com/file/RGC6yAKF1FAVv8ar4VTeGl/OpenCRVS-V3?node-id=306%3A11152)

### Design
https://www.figma.com/file/RGC6yAKF1FAVv8ar4VTeGl/OpenCRVS-V3?node-id=3%3A877

Prototype
https://www.figma.com/proto/RGC6yAKF1FAVv8ar4VTeGl/OpenCRVS-V3?page-id=3%3A877&node-id=3%3A1328&viewport=252%2C48%2C1&scaling=min-zoom&starting-point-node-id=3%3A1328

Press R to reset
Need to hide Figma UI. Click Options to do so. 

### Dev-tasks

- [x]  Update Header UI according to description
- [x] Updated Search UI according to description
- [x] Updated Profile UI according to description

**Comment by euanmillar** [comment]
@jpye-finch should we hold off on this search bar update until the "Advanced Search" feature is designed as I imagine that would affect this design once again?   IE ...what would be the drop-down and select state look-and-feel be like when you expand the TrackingID, BRN menu in search?

Currently looks like this with gradients ... 

![Screenshot 2022-01-05 at 14.27.22.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/a8f52f3d-3d1c-4f2f-ab9b-1ffeff9589cf)

We need to wait for this and how you want it to behave responsively before we can start.  Plus, is it correct that  Annina wants us to stick to the + icon instead of your new create icon?

**Comment by jpye-finch** [comment]
@euanmillar will put some time in the diary to discuss search field/top-nav. Annina mentioned at the end of the call that advanced search can wait. 

So think we can do some simple UI updates. 

![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/efdf800f-fbf7-4095-8c54-82041accb833)

**Comment by SyedaAfrida** [comment]
back button should be disabled when application cannot be backed any further

https://user-images.githubusercontent.com/94350336/155949290-ed9c326d-7422-4172-9760-eac5336dd95c.mp4

**Comment by anny320** [comment]
completed
