### ISSUE TITLE
Invalid data showing in dropdown for supporting documents in review application page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2393]
**Bug Description:**
Invalid data showing in dropdown for supporting documents in review page

**Steps to Reproduce:**
1. Declare a birth/ death application
2. Add file in Attaching supporting documents page> Continue
3. Observe supporting document section in review application page

**Actual Result:**
Invalid data in dropdown

**Expected Result:**
should show file name

**Screenshot:**
![attaching_doc1.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/1c966e18-788c-4d39-9000-55c117578829)

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![supporting doc solved](https://user-images.githubusercontent.com/94350336/165456653-f3dbe7f9-1a4c-470e-83dc-b820fc38ecbc.png)

**Comment by anny320** [comment]
completed
