### ISSUE TITLE
As a Registrar I want to check the ID of the who is requesting a correction

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2400]
### Description

- add ID check page 
- show informant details if available

### Acceptance criteria

GIVEN I have selected a parent or informant
WHEN their data is available
THEN show their ID details (ID, Name, Date of birth, Nationality)
https://www.figma.com/file/B6t82qtZeD1bhzQat210iv/12.-Correct-record?node-id=892%3A13098

GIVEN I have selected another registration agent
THEN skip the ID check page

GIVEN I have selected 'me'
THEN skip the ID check page

GIVEN I have selected any other options, eg legal guardian, someone else
THEN show the check ID page
https://www.figma.com/file/B6t82qtZeD1bhzQat210iv/12.-Correct-record?node-id=932%3A20696

### Design
https://www.figma.com/file/B6t82qtZeD1bhzQat210iv/12.-Correct-record?node-id=892%3A13098

### Copy
(Link to Notion)

### Dev-tasks

- [x] Add "Have you checked their proof of identification?" view, if yes or no continue to next step, and track decision made.  Be careful that the NID for child, may or may not exist.  Build proof of ID page check page with the help of IDVerifier component (like we developed in PrintCertificate flow) -3
- [x] Clicking "No" will open a modal defined in the design (https://www.figma.com/file/B6t82qtZeD1bhzQat210iv/12.-Correct-record?node-id=946%3A24030) - 1

**Comment by sadmananik** [comment]
We have to change the state variable for the corrector definition on this task. 
This task has a dependency on #2399

**Comment by SyedaAfrida** [comment]
**Bug:**
1.  when selected Another registration agent or field agent and Me in Who is requesting a change to this record?, should skip ID check page. Currently showing ID check page for - Another registration agent or field agent and Me
2.  Wrong verbiage in modal " Continue without proof of ID?" 
![bug 02.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/eef22728-78b9-4705-9268-a224496abd9d)
3. Bug in mobile view 
![mobile bug 1.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/333a522b-1d43-44f0-ad9a-303be5401ba4)
4. Modal not showing in mobile view
![mobile bug 2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/758d6cb2-3fad-43af-a93c-feec2e83f523)

**Comment by SyedaAfrida** [comment]
@anny320 all the bugs are fixed. You can review correct record testcases and close this ticket

**Comment by anny320** [comment]
completed
