### ISSUE TITLE
As a registrar I want to make a correction to a record

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2401]
### Description

- after id check show record review page
- registrar can nav to the form and make changes to different fields
- corrections are viewable on the review page. Showing previous entry and correction

### Acceptance criteria

GIVEN I have check the ID of the requester
THEN show the record review page

GIVEN I am on the review page
WHEN no corrections have been made
THEN disable the continue button

GIVEN I have selected a field to change
THEN navigate to that field

GIVEN I have made a change 
WHEN I navigate back to the review page
THEN show the previous state (strikethrough) and correction below
https://www.figma.com/file/B6t82qtZeD1bhzQat210iv/12.-Correct-record?node-id=892%3A13738

GIVEN I navigate to the supporting documents page
THEN I can not delete any existing supporting documents

**Replace father/mother**
GIVEN a father or mother has already been provided 
THEN show a Change all link next to the Father's details heading
https://www.figma.com/file/B6t82qtZeD1bhzQat210iv/12.-Correct-record?node-id=842%3A13594

### Design
https://www.figma.com/file/B6t82qtZeD1bhzQat210iv/12.-Correct-record?node-id=892%3A13350

### Dev-tasks
- [x] Store the application as draft and Reuse ReviewSection component to show application data.  Ensure the close button is not a "Save & Exit" and that the draft is deleted when closed.  We need to show the Continue button which is greyed out, not the Register button. - 3
- [x] After clicking change create another draft and show strikethrough text in case of older values - THIS IS NOT UNIQUE TO CORRECT RECORD.   THIS WIL BE NEW FUNCTIONALITY FOR UPDATING AN EXISTING APPLICATION FROM A READY_FOR_REVIEW STATE - 5
- [x] If replacing mother or father, we must show a modal when clicked with a message TBC, before clearing all the parent details.  - 2

**Comment by Zangetsu101** [comment]
Details of the issues in #2859

**Comment by SyedaAfrida** [comment]
@anny320 have created a ticket #2971 for 2nd bug and all others are fixed. You can review correct record ticket and close this ticket

**Comment by anny320** [comment]
completed
