### ISSUE TITLE
As a Registrar I want to add supporting documents to my correction request

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2402]
### Description

- document upload for supporting documents
- doc type select
- radio buttons to skip doc upload

### Acceptance criteria

GIVEN i have click Continue on the record review page
THEN show the supporting doc upload page

GIVEN I am on the supporting doc upload page
WHEN I have **not** uploaded any documents or clicked a radio button
THEN disable to Continue button

GIVEN I am on the supporting doc upload page
WHEN I have uploaded a documents or clicked a radio button
THEN enable to Continue button

GIVEN I am on the supporting doc upload page
WHEN I click the select field
THEN show the doc type options
(Avadavat, Court document, Other)

GIVEN I click Upload
WHEN I select a document (pdf, png, jpg, doc)
THEN show the uploading state
https://www.figma.com/file/B6t82qtZeD1bhzQat210iv/12.-Correct-record?node-id=936%3A17522

### Design
https://www.figma.com/file/B6t82qtZeD1bhzQat210iv/12.-Correct-record?node-id=892%3A14031

### Copy
(Link to Notion)

### Dev-tasks

- [ ] Add translatable messages (Avadavat, Court document, Other), add form field definitions to use document uploader and radio buttons.   Track radio decision

**Comment by SyedaAfrida** [comment]
**Bug:**
1. In Upload supporting document- Unable to upload any pdf. Should be able to upload (pdf, png, jpg, doc)
![bug 04.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/5d803bb0-e8ee-4b15-a86c-65067d5d50ca)

2. When a file is deleted, unable to select any radio button and able to Continue without selecting any radio button/ uploading any file
![bug4.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/a495e3b0-3fb9-49e4-a1ce-5eb8c94b4970)

**Comment by euanmillar** [comment]
Needs help from @jpye-finch

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is tested. You can review correct record testcases and close this ticket

**Comment by anny320** [comment]
still not able to upload a pdf @SyedaAfrida see recording[Uploading... add pdf not working.mp4]

**Comment by anny320** [comment]
working, note: pdf will be supported in future release
