### ISSUE TITLE
As a Registrar I want to give a reason for the change

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2403]
### Description

- adds reason for change page

### Acceptance criteria

GIVEN I have added a supporting document
WHEN I click Continue
THEN show the reason for change page

GIVEN I am on the reason for change screen
WHEN I have not selected a radio
THEN disable the continue button

GIVEN I am on the reason for change screen
WHEN I have selected a radio
THEN enable the continue button

GIVEN I am on the reason for change screen
WHEN I select other
THEN show Reason for change field
https://www.figma.com/file/B6t82qtZeD1bhzQat210iv/12.-Correct-record?node-id=936%3A17872

### Design
https://www.figma.com/file/B6t82qtZeD1bhzQat210iv/12.-Correct-record?node-id=892%3A13139

### Copy
(Link to Notion)

### Dev-tasks

- [ ]  Build the reason page with the form fields
- [ ] Add disable of the Continue button as a configuration option

**Comment by atiqzaman-dsi** [comment]
@SyedaAfrida can you check again, it should be fixed in recent changes in our components.

**Comment by SyedaAfrida** [comment]
@atiqzaman-dsi now we cannot see the header of this page.
![reason](https://user-images.githubusercontent.com/94350336/166137836-81d163d3-b616-4123-adf8-bee9c60058ea.png)
This is occurring for all the pages of correct record
https://github.com/opencrvs/opencrvs-core/issues/2970

**Comment by SyedaAfrida** [comment]
@anny320 This bug don't exist now, so can be closed
