### ISSUE TITLE
As a Registrar I want a summary of my correction request

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2404]
### Description

- adds summary page

### Acceptance criteria

GIVEN I have given a reason for the correction
WHEN I select continue
THEN show the Correction summary page

GIVEN I have made a correction
THEN show the original and correction

GIVEN I click back to review
THEN nav back to the review page

GIVEN I click back to upload
THEN nav back to the upload page

GIVEN I didn't upload any supporting documents
THEN show the reason given 
https://www.figma.com/file/B6t82qtZeD1bhzQat210iv/12.-Correct-record?node-id=936%3A18827

GIVEN I have not elected a radio for fees
THEN disable the 'Make correction' button

GIVEN fees are required
WHEN I click Yes
THEN show the Total amount field and Upload button
https://www.figma.com/file/B6t82qtZeD1bhzQat210iv/12.-Correct-record?node-id=936%3A18534

GIVEN upload a document for proof of payment
THEN do not show another upload button 
https://www.figma.com/file/B6t82qtZeD1bhzQat210iv/12.-Correct-record?node-id=936%3A19101

### Design
https://www.figma.com/file/B6t82qtZeD1bhzQat210iv/12.-Correct-record?node-id=892%3A14075

### Copy
(Link to Notion)

### Dev-tasks

- [x]  CorrectionReviewForm view that loads data from the old and new draft - 2
- [x] New table component UI  (2 row styles, options for columns or none, option for an action in one of the rows) - 3
- [x] Radio form for payment and document uploader - 2
- [x] We need to build the GraphQl mutation for correct record. It should contain the draft along with input / output values for the changes, along with the documents.  Ensure that the correct record mutation is called as an item in OutboxController - 3
- [x] Start a timer from the point a which the correct record form opened from Search, in the mutation we also send the time spent correcting a record.  If the close button is clicked then the timer is deleted entirely - 1
- [x] In the original registration mutation, include input / output arrays to track any changes made to an application by a registrar. - 2

**Comment by SyedaAfrida** [comment]
**Bug:**
1. In correction summary page, can show maximum 10 correction/ rows. If more corrections are made those are skipped
2. In Correction summary page, in total ($) can enter any alphabets/ special characters and make correction. Should be able to only input numerical values
![bug5.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/740ce98c-d12b-4b99-9472-7fb7bad49fa0)

3. Bug in mobile view-
![mobile bug 4.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/755ae08c-2493-4038-b087-48c29fa3f65a)

**Comment by jpye-finch** [comment]
Mobile design for Content component -> https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=5509%3A17004

**Comment by tahmidrahman-dsi** [comment]
> **Bug:**
> 
> 1. In correction summary page, can show maximum 10 correction/ rows. If more corrections are made those are skipped
> 2. In Correction summary page, in total ($) can enter any alphabets/ special characters and make correction. Should be able to only input numerical values
>    ![bug5.png](https://camo.githubusercontent.com/96580a13c98ce85360f97d20eba954cb323219f6158f9f92f2c843b152e62d1d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3631393230643038366233303739326631303166623961332f37343063653938632d643132622d346239392d393437322d376662376261643439666130)
> 3. Bug in mobile view-
>    ![mobile bug 4.png](https://camo.githubusercontent.com/59096a308ed4d4d40513867af083225f8a1b8d4a2088abac196df3af441f2d18/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3631393230643038366233303739326631303166623961332f37353561653038632d323439332d343033382d623038372d343863323966613366363561)

1. Will be fixed when tableview will have Pagination
2. Fixed by #2854 
3. Will be fixed by #2805

**Comment by SyedaAfrida** [comment]
@anny320 can review the correct record testcases and close this ticket

**Comment by anny320** [comment]
completed
