### ISSUE TITLE
As a user I want to view a record page so that I can see the record history

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2423]
### Description
- removes expanded view of a workqueue record row
- clicking on a row navigates to the Record Audit page

Status Examples:

- [In progress](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1810%3A33851)
- [In review
](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1837%3A48064)
- Requires updates
- [Registered](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1837%3A51029)
- [Certified](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1837%3A52507)
- [Record requires updates](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1879%3A35681)

### Acceptance criteria

GIVEN I am on the workqueue
WHEN I click on a row record
THEN navigate to the Record Audit page for that record

GIVEN I am on the Record Audit page
WHEN I click back in the browser navigation
THEN navigate back to previous screen

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1785%3A30839

### Dev-tasks?

- [x]  Remove the expanded section. Instead when you click on a row, you are taken to the RecordAudit view.  Use the new Content UI component to build the view.

**Comment by anny320** [comment]
completed
