### ISSUE TITLE
As a user I want to see a summary of a record so that can understand more

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2424]
### Description

Can see high-level detail about the record:
- Status
- Event
- Tracking ID
- BRN/DRN (if applicable)
- Date of birth/death
- Place of birth/death
- Applicant (Relationship to child/deceased and contact number)

### Acceptance criteria

GIVEN I am on an In Progress application audit page
WHEN there is no data for name, date of birth/death or place of birth/death
THEN show 'No name provided, No date of birth, no place of birth'

GIVEN I am on an Ready for review application audit page
THEN I can see Status, Event, Tracking ID, Date of birth/death, Place of birth/death, Applicant (Relationship to child/deceased and contact number

GIVEN I am on a Required updates audit page
THEN I can see Status, Event, Tracking ID, Date of birth/death, Place of birth/death, Applicant (Relationship to child/deceased and contact number

GIVEN I am on an Ready to print record audit page
THEN I can see Status, Event, Tracking ID, BRN/DRN Date of birth/death, Place of birth/death, Applicant (Relationship to child/deceased and contact number

GIVEN I am on a certified record audit page
THEN I can see Status, Event, Tracking ID, BRN/DRN Date of birth/death, Place of birth/death, Applicant (Relationship to child/deceased and contact number

GIVEN I am on a record requires updates record audit page
THEN I can see Status, Event, Tracking ID, BRN/DRN Date of birth/death, Place of birth/death, Applicant (Relationship to child/deceased and contact number

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1810%3A33851

### Dev-tasks

- [ ]  In the summary section of RecordAudit, show relevant information for the application selected.

New Change Required:
- [ ] Instead of making new GQL query lets fetch the specific application from indexed DB.

**Comment by SyedaAfrida** [comment]
@jpye-finch what is the difference between  Required updates audit page and  record requires updates record audit page? Which user will see which page?

**Comment by jpye-finch** [comment]
@SyedaAfrida The summary details on Requires updates and Sent for updates is the same

**Comment by SyedaAfrida** [comment]
**Bugs:**

1.In Field agent, there is no tracking ID in audit record page of sent for review. But Tracking ID is available in workqueue.
Should have tracking ID in audit record page of sent for review.
![1](https://user-images.githubusercontent.com/94350336/161708747-1fad0888-bc2c-4e68-b4f0-8a64b25fdbda.png)

2. Should have space between the word "legal guardian" in informant name
![7](https://user-images.githubusercontent.com/94350336/161711968-5e4815a9-fb8a-4237-a409-ac8f5e953520.png)

3. Space between Tracking Id
4. Avoid '_' in son_in_law/ daughter_in_law
![10_11](https://user-images.githubusercontent.com/94350336/161712347-401f8f3a-4d3f-4c88-9809-f50f15e42ebb.png)

**Comment by Fariha-Amin** [comment]
@anny320  passed, can be closed

**Retest SS:**
![dd](https://user-images.githubusercontent.com/105624748/172111109-2e6b7477-adfc-4dfd-a5c5-7f886612d7d7.PNG)
![ddd](https://user-images.githubusercontent.com/105624748/172111113-331f35f1-6007-4ab8-8667-834c06404542.PNG)
![dddd](https://user-images.githubusercontent.com/105624748/172111116-07d7a91e-e5aa-4090-bc89-9c28e12ddf45.PNG)

**Comment by anny320** [comment]
completed
