### ISSUE TITLE
Back end - Amend registration resolver to track changes made to the application by a registrar

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2427]
- [x] In gateway, in the "registration" feature, add input / output arrays to the root-resolver.  If these arrays contain data, then we need to create first an APPLICATION_UPDATED task and Task in Workflow with the new and old values.  When that has been created continue to create a REGISTERED task.  If there is no data in the input and output arrays, we can just make a REGISTERED task.
- [ ] Ensure that the client, when making changes in ready for review, that the input/output values are sent

**Comment by Zangetsu101** [comment]
The second sub-task is similar to the 4th sub-task of #2404. So waiting for that.

**Comment by euanmillar** [comment]
blocked by 2404
