### ISSUE TITLE
Using GlusterFS / Grid FS / Ceph for storing documents at a huge country scale e.g. Nigeria

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#2433]
### Conclusions
- Document data we use for MongoDB should remain on the local disks of the database machines. This is because a distributed file system is less performant and compatibility with MongoDB is unclear. MongoDB's built-in replication and sharding features are more suitable for this use case.
- As we still need a blob storage for attachments, we need to choose between GridFS, Ceph and GlusterFS. GridFS is something MongoDB provides for storing files larger than 16MB (maximum document size in MongoDB). The issue with GridFS is that the files are still stored in MongoDB, eventually slowing it down ([GridFS is provided for convenience, it is not designed to be the ultimate binary blob storage platform](https://stackoverflow.com/questions/67425280/is-it-efficient-to-store-images-inside-mongodb-using-gridfs/67426272#67426272)).  
- Ceph is fundamentally an object storage, not a distributed file system ([Ceph VS GlusterFS?](https://www.reddit.com/r/sysadmin/comments/9onemk/ceph_vs_glusterfs/e7vfij1/?utm_source=share&utm_medium=web2x&context=3)), which for our use case would be file. Our need however is slightly more trivial than that: we just need a distributed file system with replication, thus GlusterFS seems like the better alternative. Ceph's installation (and maintenance) is also more difficult than GlusterFS's.
- GlusterFS is something we need to have running on the servers, so it will work regardless of the container orchestration tool we use. The production infrastructure will **require minimum 2 additional nodes** with <space required for all attachments of all applications> terabytes of storage capacity each. Data is then replicated between these two servers ensuring data availability. 
- GlusterFS should be installed to our infra with ansible using [gluster-ansible-cluster role](https://github.com/gluster/gluster-ansible-cluster). 2 storage nodes act as Gluster servers and the nodes running our application servers act as Gluster clients. 
- Firewalls on storage nodes need to be configured so that:
   - Port 24007 can be accessed by the other storage nodes and the applications servers, not by anyone else.
   - Port 49152 (network volume port) can be accessed by the applications servers, not by anyone else.
 - Gluster access needs to be restricted on storage nodes by using `auth.allow` option. More info [here](https://www.digitalocean.com/community/tutorials/how-to-create-a-redundant-storage-pool-using-glusterfs-on-ubuntu-20-04)

### Infrastructure

Required nodes:
- 2 connected storage nodes with as much storage space as possible
- 2 more nodes on physically different servers that the data gets replicated to **(production)**

### Tasks

- Setup 2 new storage nodes
- Update Ansible playbooks to provision storage nodes 
- Update compose files so that all application containers have a defined path where the storage cluster is mounted to
- Refactor application code so that binary attachments are stored to and read from the mount point
- Verify that sent attachments are stored
- Consider setting up replication **(possibly only when doing a production installation)**

**Comment by rikukissa** [comment]
>For this reason, if you’re going to use GlusterFS in production, it’s recommended that you run it on an isolated network. For example, you could set it up to run in a Virtual Private Cloud (VPC) or with a VPN running between each of the nodes.

https://www.digitalocean.com/community/tutorials/how-to-create-a-redundant-storage-pool-using-glusterfs-on-ubuntu-20-04

**Comment by euanmillar** [comment]
Going with Minio
