### ISSUE TITLE
As a Registration Agents, and Registrars, I want to archive an application, so that it is no longer in my workqueue

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2457]
### Description

- adds archive button to Record Audit page: In Review and Requires Updates
- what about in progress? yours, FAs and Hospital??
- requires download to archive??

### Acceptance criteria

GIVEN the application is status In Review or Requires upates
WHEN I click on the Archive button 
THEN show the confirmation model

GIVEN I click Archive
WHEN I confirm in the model
THEN remove the application from the workqueue

GIVEN I have archived an application
THEN show the action in the record history table

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1879%3A40070

### Dev-tasks
- [x]  On the Record Audit page, you can see an Archive button, on click we need to build the confirmation model, then submit a new mutation: markApplicationAsArchived via OutboxController. - 3
- [x] In the gateway, and workflow, as we have done for CorrectRecord, we need to create a new Task and a new event status: "ARCHIVED".  JWT Scope restriction on the resolver is "validated", or "register".  We will need to update openhim-base-config and replace the backup database zips on farajaland - 3
- [x] In the search service we need save an operationHistory - 2

**Comment by SyedaAfrida** [comment]
**Bug:**
There should be no archive option in sent for approval tab
![13](https://user-images.githubusercontent.com/94350336/161731874-25f45228-cf40-4470-a0cf-45f3e4aea55b.png)

**Comment by Zangetsu101** [comment]
Fixed in #2867

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed. You can review Correct record testcases and close this ticket.

**Comment by anny320** [comment]
completed
