### ISSUE TITLE
As a user I want to download a record , so that I can progress the application

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2459]
### Description

- download button on Record Audit page
- Call to action (Review, Update, Print) disabled until downloaded
- note! no '...downloading' messaging just the icon

### Acceptance criteria

GIVEN I am on the Record Audit page
WHEN I click on the download button
THEN show the spinner

GIVEN I have downloaded the application
THEN enable the Call to action (Review, Update, Print) and show downloaded icon
 

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1837%3A48064

### Dev-tasks

- [ ] In the RecordAudit view, the Actions section and any access to personally identifiable information such as date of birth / national ID number, phone number etc should be initially greyed out. https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1857%3A35811 When you click download, the actions display with links to a modal overlay. - 2
- [x] In the fetchBirthRegistration / fetchDeathRegistration resolver in Gateway, we need to find the previous Tasks status ie DECLARED / REJECTED, duplicate the previous Task status in a new Task but save a new DOWNLOADED "note" on the Task, then send to Workflow to update this task with the downloading user info.  We need to then call a new handler on the the search microservice (and potentially also metrics) to add a DOWNLOADED operation history item.  In this way we can audit the request by the user to get access to personally identifiable information. - 3
- [x] Amend the fethBirthRegistration and fetchDeathRegistration resolvers to request all Tasks from Hearth including input/output correct record / application updated info associated with the Composition and return them so that we can store in IndexedDB - 3

**Comment by euanmillar** [comment]
Blocked waiting for Tahmid's PR on correct record back-end

**Comment by euanmillar** [comment]
Need to have a conversation with @jpye-finch regarding pagination

**Comment by SyedaAfrida** [comment]
**Bug:**

1. .In registrar in progress tab, update button is missing in record audit page

https://user-images.githubusercontent.com/94350336/161711411-d6101fbc-6b21-4b57-9d50-08704beffe67.mp4

2.  From Registration agent, if clicked download from sent for approval tab, then when logged in as Registrar, in audit record page there is no review button.

https://user-images.githubusercontent.com/94350336/161711748-7776aad3-51c1-4115-a6ff-bf57fbcb3102.mp4

3. all the button in mobile view should be below the informant details.
![9](https://user-images.githubusercontent.com/94350336/161712697-52e9e998-4469-4899-824e-e6c3a66eec22.png)

**Comment by euanmillar** [comment]
@SyedaAfrida can you retest and confirm what is still outstanding

**Comment by SyedaAfrida** [comment]
@euanmillar all these bugs no longer exist
@anny320 this ticket is tested and can be closed
1)
![fix1](https://user-images.githubusercontent.com/94350336/169355051-d15f6a6b-edc2-41d8-a15b-17c735d44dcd.png)
2)
![fix2b](https://user-images.githubusercontent.com/94350336/169355140-25e78921-17f0-4033-85a9-46f489273ba8.png)
![fix2a](https://user-images.githubusercontent.com/94350336/169355149-f88c1d20-781b-4d4c-a84a-e0379e537c69.png)
3) this is fine

**Comment by anny320** [comment]
completed
