### ISSUE TITLE
Combine certificate PRs, link certificate config front end to back end

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2465]

**Comment by sadmananik** [comment]
I think there are some design lacks for the config certificate front-end. As

1. The UI looks the same with or without the uploaded SVG certificate template.
2. Should (Preview, Print, Download) options be hidden or disabled if the there is no SVG certificate template uploaded.

Design - https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=11%3A922

**Comment by jpye-finch** [comment]
Hey looking at this now.
Quick comment. We should show the date that the certificate was uploaded. on success. Sorry this was missing from the design. Have updated

**Comment by jpye-finch** [comment]
Hey looking at this now.
Quick comment. We should show the date that the certificate was uploaded. on success. Sorry this was missing from the design. Have updated

**Comment by jpye-finch** [comment]
Hey looking at this now.
Quick comment. We should show the date that the certificate was uploaded. on success. Sorry this was missing from the design. Have updated

**Comment by jpye-finch** [comment]
There will be a default SVG certificate template already uploaded as part of install. So need to hide Preview, Print or Download
