### ISSUE TITLE
Copy update: Applicant to informant and Application to declaration

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2495]
### Description

-  Find a replace all instances of Applicant and replace with Informant
-  Find a replace all instances of Application and replace with Declaration

### Acceptance criteria

GIVEN 
WHEN
THEN 

### Design
(Link to Figma)

### Dev-tasks
- [ ] Copy amend described above - 2
- [ ] General refactor of events and functions to make copy amend described above.  Update the openhim-base-config and backup zips - 3

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Comment by anny320** [comment]
completed
