### ISSUE TITLE
Update informant list for a birth declaration

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2496]
### Description

- Update list of informants to:
1. Mother
2. Father
3. Grandfather
4. Grandmother
5. Brother
6. Sister
7. Legal Guardian
8. Someone else

- Remove Mother & Father option
- Remove Primary contact page if Mother & Father is chosen
- Remove additional someone else list page
- If someone else. Ask Relationship to child
- Remove Self Option

### Acceptance criteria

GIVEN I have started a birth application
WHEN on the informant type question
THEN I can see the complete list of informants

GIVEN I have select someone else
THEN I am prompt to enter the Relationship to child

Given  I can see the complete list of applicants
Then Remove Self as option of lists

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1968%3A38952

Applicant logic https://www.notion.so/opencrvs/Birth-declaration-04bdbc7b98a947cca54c7252423af2b1

### Dev-tasks
- [ ]  Update the informant list with the options, remove the extra someone else list page with Bangladesh options, remove the extra mother & father page, remove Self option

**Comment by anny320** [comment]
Have added extra requirement: remove self option from list of informants refer to applicant logic https://www.notion.so/opencrvs/Birth-declaration-04bdbc7b98a947cca54c7252423af2b1 @euanmillar @jpye-finch

**Comment by euanmillar** [comment]
Closing this in favour of this holistic ticket: https://github.com/opencrvs/opencrvs-core/issues/2499
