### ISSUE TITLE
Update main contact list for birth declaration

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2497]
### Description

 - Update main point of contact list
1. Mother
2. Father
3. Grandfather
4. Grandmother
5. Brother
6. Sister
7. Legal Guardian
8. Someone else

### Acceptance criteria

GIVEN I am on the main point of contact page
WHEN I select an option
THEN show the Phone number text input

GIVEN I am on the main point of contact page
WHEN I select someone else
THEN show the Phone number text input

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1968%3A39031

### Dev-tasks
- [ ]  Update the contact list, remove the logic around the "Applicant" radio button that appears, remove the Relationship to child field for someone else.  We are just asking for phone number on this page

**Comment by euanmillar** [comment]
Blocked by 2496

**Comment by anny320** [comment]
completed
