### ISSUE TITLE
Update default birth declaration form questions and flow

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2499]
### Description

- Updates the [birth declaration form](https://www.figma.com/file/7AYxLlYTpY4RioSTIt0PbG/OpenCRVS-Fajarland-Forms?node-id=0%3A1)

**Key differences**
- checkbox instead of yes/no radio buttons for 'Father's details not available'. OnCheck we hide all questions and ask for a Reason. 
- If Informant is the Father. Hide checkbox 'Father's details not available'

- Remove child protection questions. Checkbox added to Mother page. 'Mothers details not available' If the informant is not the mother or father
- Order of birth (number) moved to Mother's details page. Renamed to 'No. of previous births'
- Sex options (Male, Female, Unknown)

- Checkbox 'Same as mothers usual place of residence' instead of yes/no radio button. Hide checkbox is Mother's details are not available. Disabled if mother's address has not been added.
 
- Add Other document type. If informant is not the mother or father
- Show and hide Document upload for Mother and Father's ID. If checkbox is active for 'Mother/Father details are not available'

### Design
https://www.figma.com/file/7AYxLlYTpY4RioSTIt0PbG/OpenCRVS-Fajarland-Forms?node-id=0%3A1

### Dev-tasks
- [x] Refactor SelectInformant component to integrate into form and align birth and death approach to informants - 5
- [ ] Create checkbox component - 2
- [ ] Remove child protection questions - 1
- [ ] Add new reason for not applying checkbox to mother and father page and update FHIR payload for new values - 3
- [ ] Update document conditionals - 2
- [ ] Rewrite associated unit and automated tests - 5

**Comment by euanmillar** [comment]
@anny320 Can we discuss this, I dont understand what is neeeded

**Comment by jpye-finch** [comment]
@euanmillar have updated this ticket. and highlights main changes

**Comment by SyedaAfrida** [comment]
@anny320 This ticket is tested. the bugs are #3012, #3013, #3016, 3018, #3019 & #3020
You can review the testcase of birth declaration and close this ticket

**Comment by anny320** [comment]
completed
