### ISSUE TITLE
Update: Reorder deceased and applicant questions to be consistent

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2501]
### Description
Reorder deceased and applicant questions to be consistent

Order of questions is :Childs, Mother, Fathers, Deceased and Applicant pages 

### Copy (Link to Notion)
For Birth application use this link as guide
https://www.notion.so/opencrvs/Birth-declaration-04bdbc7b98a947cca54c7252423af2b1

For death application use this link as the guide https://www.notion.so/opencrvs/Death-application-ada99eb56011418b9a8e1cc30c8f519c
...

### Dev-tasks??

- [ ]  Task 1

**Comment by euanmillar** [comment]
@anny320 can we discuss this too.  I dont understand the requirement

**Comment by anny320** [comment]
More clarification: to ensure the order of questions is Childs, Mother, Fathers, Deceased and Applicant pages

**Comment by euanmillar** [comment]
Sorry, I am still not understanding what needs to be changed.  Please can we have a specific explanation for each event explaining what is currently wrong and n explanation of how it needs to be fixed including acceptance criteria.  IE.  In Birth registration, the flow is currently 1,2,3 .. this is wrong, it should be 4,5,6.  GIVEN I am a registrar, field agent or registration agent, WHEN I create a birth application, WHEN I click continue on the X screen, the next section should be Y.

**Comment by anny320** [comment]
### For Birth application use this link as guide
https://www.notion.so/opencrvs/Birth-declaration-04bdbc7b98a947cca54c7252423af2b1

For death application use this link as the guide https://www.notion.so/opencrvs/Death-application-ada99eb56011418b9a8e1cc30c8f519c

**Comment by euanmillar** [comment]
@jpye-finch we need the flow design like we had for Niue

**Comment by jpye-finch** [comment]
closing and updating https://github.com/opencrvs/opencrvs-core/issues/2529
