### ISSUE TITLE
Model header height causing ui issues

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2506]
**Describe the bug**
- model is getting cropped

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'certificate collection flow'
2. Click on 'someone else'
3. Add details
4. Click check box 'I dont have an affidvait'
5. Click continue

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/348d2dc5-fb78-4578-aad3-1966c9a3b9e1)

**Additional context**
Model is getting cropped. Possibly because the tile goes onto two lines.
Removing header height 64px. fixes it seems.

**Comment by Zangetsu101** [comment]
### This is already fixed.
![image](https://user-images.githubusercontent.com/29002716/171135963-4a4ff0c1-fc86-4b67-83b8-1fd708ea59ce.png)

**Comment by Fariha-Amin** [comment]
@anny320  passed, can be closed

![d](https://user-images.githubusercontent.com/105624748/171833758-8dead1cb-a0f4-4ef4-92c0-cf558a4c1d3b.PNG)

**Comment by anny320** [comment]
completed
