### ISSUE TITLE
System admin should have option to change Signature from edit details page 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2509]
**Bug Description:**
System admin should have option to change Signature from edit details page 

**Steps to Reproduce:**
1. Login as Local/ national system admin
2. Click Team
3. Click 3 dot menu for a Registrar
4. Click edit details
5. Observe Signature row

**Actual Result:**
no option to change or delete existing signature file

**Expected Result:**
Either can have a change link beside "User's Signature"  attachment or can have delete option when signature is viewed after clicking "User's Signature"

**Screenshot:**
![6.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/2d6cc8f8-84d3-4f8c-8380-2cd493ef66e6)![7.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/35d55a8b-e544-4dbb-af7c-ddd8d437fc4f)

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by euanmillar** [comment]
Automatically should be fixed with FIleUploader fixes in progess

**Comment by anny320** [comment]
completed
