### ISSUE TITLE
Component library v2

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2514]
### Description

- The application utilises a modular UI component library that has been set up using React Storybook and styled-components, however over the years CSS styling and UI technical debt has accrued in the application.
- During an initial 6-week project (with the potential to extend), we need to polish and style our component library, implement improvements and standardisations, then set us on a new and improved direction.
- Where pages have been constructed in the main application without using preferred elements from the component library, we are looking for refactor assistance to align those pages more tightly to the library.
- Where components in the library are no longer in use, then those components can be deleted. 
- Where the DOM can be optimised, then elements / templates can be re-written. 
- Where components can be made more accessible, then necessary requirements can be added. 
- We must publicise and share our component library, so it needs to be documented and branded.
- By the end of the 6 week term, we must prepare a timeline and resource plan so that we can understand the necessary steps required to bring the DOM and comp lib up to scratch and ensure that OpenCRVS meets WCAG level 2 Accessibility Standards. 

### Figma Design System
https://www.figma.com/file/SsqCzO2eherXXCKyixmli9/OpenCRVS-Design-System-v2-WIP?node-id=0%3A1

### Dev-tasks

**Following Gitflow process, Please create a new feature branch for the project in a pull request with a label "Work In Progress" and "On Hold".   Then branch from that into smaller PRs that merge into the feature branch after code review.  We will not merge the feature branch into "develop" until we schedule the release that this work will go into.  As develop will continuously improve, you should regularly merge / rebase from develop into your feature branch to avoid a lot of conflicts at the end of your project**

Week 1-5

- [ ] Brand React Storybook and setup component library navigation pages to match structure document in [Notion](https://www.notion.so/opencrvs/Component-library-5624f9ac70224e3aafdd3f572a0accfd)
- [ ] Alphabetise the component navigation and resolve naming conventions in code and display
- [ ] Assess and moved Client components into component library 
- [ ] Work through updating a prioritised list of priority components and patterns.  With some patterns that in the client, they need migrated over into the component library but must maintain existing logic
- [ ] Remove obsolete components
- [ ] Publish the Storybook to https://styleguide.farajaland-staging.opencrvs.org/  (?)
- [ ] Consider and implement Addons to support designers and developers

Week 6

- [ ] Prepare a timeline and resource plan so that we can understand the necessary steps required to complete the work and additionally ensure OpenCRVS meets WCAG level 2 Accessibility Standards.

**Comment by euanmillar** [comment]
Roughly 10 weeks of @naftis full time is required to complete the UI Component Library work

**Comment by naftis** [comment]
The component library is now published to https://ui-kit.opencrvs.dev

@jpye-finch can be this be closed now?
