### ISSUE TITLE
Move components in Client into packages/components

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2515]
### Description

- alot of components in Client. 
- they should all be in packages/components

https://www.notion.so/opencrvs/Component-library-5624f9ac70224e3aafdd3f572a0accfd

### Dev-tasks

- [ ]  Task 1

**Comment by naftis** [comment]
I'll close this in favour of https://github.com/opencrvs/opencrvs-core/issues/3744
