### ISSUE TITLE
QA Automation: Automated test to validate Validate Someone else death registration flow

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2523]
### Description
Validate Someone else death registration flow
Death Test case 3
https://docs.google.com/spreadsheets/d/1cVpmTAU_40Rlju8z-rqeN9N_exLJcIIQ3n3kFQNCx-I/edit#gid=0

...

**Comment by euanmillar** [comment]
Closing this as we are changing our automated e2e testing approach
