### ISSUE TITLE
QA Automation: Automated test to validate In progress application tab

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2524]
Validate In progress application tab for FieldAgent view and Registrar user types 

Application test case 1 https://docs.google.com/spreadsheets/d/1cVpmTAU_40Rlju8z-rqeN9N_exLJcIIQ3n3kFQNCx-I/edit#gid=1821929738

**Comment by azantor64** [comment]
**As a Filed Agent:**
- [ ]  Check  in Progress tab
- [ ]  Validate the list after creating form
- [ ]  Test Application form
- [ ]  Check Review Page & Updated Application details page

**Comment by euanmillar** [comment]
Wait for form declaration update tickets to be completed
