### ISSUE TITLE
Update default death declaration form questions and flow

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2529]
### Description
Main differences:
- Combine event details into one page Event details.
- Removes mother, father and spouse details
- refined list of proof of death documents
- refined list of Proof of cause of death
- National ID is not mandatory

### Design
https://www.figma.com/file/NxSCdXCetyZsr26v4aiaxO/Fajarland-Death-Declaration-Forms?node-id=1%3A2

### Copy
Refer to event details logic 
https://www.notion.so/opencrvs/Death-application-ada99eb56011418b9a8e1cc30c8f519c

### Dev-tasks

- [ ]  Combine event details - 2
- [ ] Remove mother, father and spouse details - 2
- [ ] Update document types and FHIR - 2
- [ ] Update proof of cause of death - 2
- [ ] Update unit and automated tests - 3

**Comment by euanmillar** [comment]
@anny320 wait for the feedback

**Comment by SyedaAfrida** [comment]
@Anne this ticket is tested and can be closed. The bugs for this ticket are #3060, #3061,#3064, #3065, #3066

**Comment by anny320** [comment]
completed
