### ISSUE TITLE
File Uploader needs changes.  

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2532]
- [x] File Uploader's state must be available from outside of the component somehow because it is needed in order to block the continue button sometimes - 2
- [x] We need to add the trash icon that should appear next to the filename - 2
- [x] #2869

**Comment by azantor64** [comment]
Bug: After clicking continue button should throw an validation message

steps: 

1. Log in as Sys Admin
2. create e new user 
3. click on Continue button
4. See the error

Screenshot: 
![image](https://user-images.githubusercontent.com/70468099/162694027-d9e808cd-932d-4ef5-89eb-097d18d48e5b.png)

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/162694785-32b8aab0-8164-44e0-be88-fa69773f64c3.png)

**Comment by sadmananik** [comment]
This issue will be fixed with [this](https://github.com/opencrvs/opencrvs-core/issues/2791).

**Comment by anny320** [comment]
completed (error message showing) pending new copy change,
