### ISSUE TITLE
ListView component

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2543]
### Description

- create component ListView. This is currently very similar to ListTable
- A row can have different [variants](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4429%3A3224)
- [Column 1 can be a heading (copy font) or can be a bold link](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4794%3A14459)
    - Bold link should be a new variant of our Link component.
    - Please **don’t** just create a new component for [Bold Link](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4373%3A2875). We should be extending components to take new props. So refactor LinkButton.
    - [LinkButton](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4373%3A2875) needs to be updated to show the underline on hover.
- Column two shows summary data.
- Column three can have an IconButton, LinkButton or Button
- [Mobile view](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4799%3A14663) variants and [mobile view example.](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4794%3A14833)

Pages where the ListTable is used:

- [Team page](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=2197%3A45289) - Currently uses ListTable
- New user summary page - Uses DataRow, just make sure it is wrapped by ListView
- Declaration review page - Uses DataSection and DataRow, just make sure it is wrapped by ListView
- [Reports monthly list](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4860%3A13736) - Uses ListTable
- [Settings](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=2216%3A50989) - Already using ViewData

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

[https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4429%3A3224](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4429%3A3224)

PR 1:

- [x] Merge ViewData, DataSection, DataRow into ListTable, rename it ListView and refactor into the TeamPage, obey the new stylin requirements Jon has asked for. - 2
- [x] In New user summary page, use ListView to wrap DataRow - 2
- [x] In the ReviewSection for any application, we are using DataSection and DataRow.  Instead we should use ListView - 3
- [x] Refactor Settings and Certificate Config page, use ListView

PR 2:

- [x] Refactor UserAudit history and CorrectionSummary to use TableView - 2
- [x] Operational reports should use TableView - 1
- [x] FieldAgent performance table should use TableView - 2

**Comment by atiqzaman-dsi** [comment]
DataSection has been used in the Settings and Certificate Config page.

**Comment by atiqzaman-dsi** [comment]
I confirmed everything is done.

**Comment by azantor64** [comment]
**User names & Roles aren't aligned according to design**
![m_2](https://user-images.githubusercontent.com/70468099/161224870-24fd17bf-3baf-47f5-90b9-f1381c79b4db.png)

Design view

![image](https://user-images.githubusercontent.com/70468099/161225202-966bc998-07cc-441b-bc6f-26bcab2b0554.png)

**Comment by azantor64** [comment]
**User names & Roles aren't aligned according to design**
![m_2](https://user-images.githubusercontent.com/70468099/161224870-24fd17bf-3baf-47f5-90b9-f1381c79b4db.png)

Design view

![image](https://user-images.githubusercontent.com/70468099/161225202-966bc998-07cc-441b-bc6f-26bcab2b0554.png)

**Comment by azantor64** [comment]
_Steps to Reproduce_

1. Log in as Sys Admin
2. Navigate to Team Page
3. Try to click on any user

**Clicking on any user is not user friendly.**
![click](https://user-images.githubusercontent.com/70468099/161225983-7d534e28-8c5d-497c-aa39-9b3e40bb0637.png)

**Comment by azantor64** [comment]
**Active button should be on the right side in accordance with user**


_Steps to Reproduce_

_1. Log in as **Sys Admin**
2. Navigate to **Team** Page
3. Observe 
Device: Mobile,Samsung S8+


![mobile view active](https://user-images.githubusercontent.com/70468099/161227329-acfdc233-8000-496b-b892-a58cd4e476ed.png)


Design view is: 
![image](https://user-images.githubusercontent.com/70468099/161228039-2246e2c3-a109-49b7-bc9c-92d0c6a6ef0c.png)

**Comment by azantor64** [comment]
Though Users are not showing according to user numbers
Steps to reproduce:

1. log in as Sys Admin
2. click on team
3. Count how much user there & what number is written beside the user

![list](https://user-images.githubusercontent.com/70468099/161228977-5a899a07-3409-449b-8fa8-c52e54ad6356.png)

**Comment by azantor64** [comment]
https://github.com/opencrvs/opencrvs-core/issues/2804

**Comment by euanmillar** [comment]
We need to replace everywhere with the new List component

**Comment by anny320** [comment]
a lot of the UI bugs will be fixed by doing 2915 and applying list view simplified.

**Comment by azantor64** [comment]
![Screenshot from 2022-05-30 15-13-32](https://user-images.githubusercontent.com/70468099/170994510-05b5f60c-5d3f-4648-9940-0c03a1942279.png)
![Screenshot from 2022-05-30 15-14-24](https://user-images.githubusercontent.com/70468099/170994521-1820e48d-3827-46ac-bf39-520ac4d4a7a1.png)

![Screenshot from 2022-05-30 15-30-40](https://user-images.githubusercontent.com/70468099/170994541-5ca8f87a-92d3-4832-9d61-0b97e0a16e34.png)

![Screenshot from 2022-05-30 15-32-29](https://user-images.githubusercontent.com/70468099/170994567-fae1a413-3ec4-4ae8-a622-61db6bfcae9e.png)
![Screenshot from 2022-05-30 16-26-37](https://user-images.githubusercontent.com/70468099/170994585-e7f80bf7-70db-4b9e-b058-5952e38b308c.png)
![Screenshot from 2022-05-30 18-22-02](https://user-images.githubusercontent.com/70468099/170994592-245f73b5-2de8-4725-98ea-d7f99e10a597.png)

**Comment by anny320** [comment]
completed
