### ISSUE TITLE
TableView component

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2544]
# TableView

### Description

- create a component called [TableView](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4666%3A14333). It is basically ListTable with styling update header and font size.
- [Variants](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4666%3A14333)
    - [Single column](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4802%3A21643)
        - font 16px
    - Three columns
        - font 16px
    - 3+ columns
        - [Reduce font size to 14px](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4634%3A14791)
    - 5+ then oversized as we have for [Current applications in workflow table](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=2216%3A46696)
- Column headings can be sorted. We require a [Prop to enable of disabling table sorting](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4874%3A13804)
- Mobile - Keep it simple. Same as example [Moveable in this article](https://medium.com/appnroll-publication/5-practical-solutions-to-make-responsive-data-tables-ff031c48b122). What we have already in ListTable.

Pages that use TableView

- Field agents performance
- [Declarations in workflow table](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=2216%3A46696)
- [Reg rates graphs and table](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1860%3A54028)
- Correct Record Summary page (in build)
- Record audit page (in build)
- Record audit action model (in build)
- User audit page 
- User audit action model (models not yet built)

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

[https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4666%3A14333](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4666%3A14333)

**Comment by euanmillar** [comment]
@soumita-dsi looks like bugs exist on mobile

**Comment by SyedaAfrida** [comment]
**Bugs:**
1.  In current declarations workflow page, the header name font size is 16px. Should be 14px
2. In current declarations workflow page, the last column is right aligned. It should be left aligned
![last coln_left Alinged](https://user-images.githubusercontent.com/94350336/163112507-edd5a303-be52-451d-9d6e-6d2171e0eac9.png)
3. In Birth/Death registration rate within 30 days of event, the last row (showing total) is not aligned both in web and mobile view
![Reg rates graphs and table2](https://user-images.githubusercontent.com/94350336/163112643-8ebef191-37c7-43c1-bff6-1e0d58f9815c.png)
![reg_rates](https://user-images.githubusercontent.com/94350336/163112667-ff617b38-bc41-43ce-966c-c8a533bf218f.png)

4. In correction summary page, link texts are not aligned
![Correction summary1](https://user-images.githubusercontent.com/94350336/163112818-6001b6f1-8cb0-4de5-b5dd-634a7585151b.png)

5.  In user audit action and tracking ID are 16px and event & date are 14px
![user audit2](https://user-images.githubusercontent.com/94350336/163113177-a468a6a6-b195-41f4-85d9-34cae907212f.png)

6. No audit to display is not aligned
![User audit3](https://user-images.githubusercontent.com/94350336/163113319-9653ade3-b5fc-40cc-903b-29e65dea5c56.png)

**Comment by emon-swe-sust** [comment]
All bugs except 2 is fixed all ready. Only number bug no. 2 is exists.

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Retest Recording:**

https://user-images.githubusercontent.com/105624748/175026483-c0d0b767-d1cc-4c03-b455-0d9e9de39557.mp4

**Comment by anny320** [comment]
completed
