### ISSUE TITLE
Some ID properties in the "validate.ts" file are hardcoded and they should not be

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2547]
See the values here:

https://github.com/opencrvs/opencrvs-core/blob/6e8510e875f05ae009f07d893ee694eccd814e99/packages/client/src/utils/validate.ts#L544

- [x] const validNationalIDLengths = [10, 17] - This property should be dynamic based on the NID pattern that we get in the config.
- [x] const validBirthRegistrationNumberLength = 17 - This property and switch case should be removed
- [x] const validDeathRegistrationNumberLength = 18 - This property and switch case should be removed
- [x] const validPassportLength = 9 - This property and switch case should be removed
- [x] const validDrivingLicenseLength = 15 - This property and switch case should be removed

**Comment by SyedaAfrida** [comment]
@anny320 this ticked is fixed and can be closed
![tt](https://user-images.githubusercontent.com/94350336/173336601-5502ba17-14b0-4672-903f-df10e786edbf.png)
![brn](https://user-images.githubusercontent.com/94350336/173336606-cce39f9f-de28-4007-956b-97dc6b24af8e.png)
![driving licence](https://user-images.githubusercontent.com/94350336/173336610-81f9c714-a97e-4437-ae7d-d438b42efa29.png)

**Comment by anny320** [comment]
completed
