### ISSUE TITLE
As a National System Admin, I want to see an overview of my ‘general’ configuration

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2553]
### Description

- adds Application configuration page
- view a list of General configuration options
- can nav view tabs to Birth and Death config options

### Acceptance criteria

GIVEN I am a National System Admin
WHEN I click Application in the side menu
THEN nav to the Applications config page. General tab

GIVEN I am on the Application config page
THEN I should see my current configuration for each config options

### Design

[https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=675%3A12159](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=675%3A12159)

### Dev-tasks

- [x]  When clicking on application config, load the default application config page using Content (medium) component and update  certificate config page to use Content (medium) - 1
- [x] Re-use / refactor Tabs component / FormTabs (client) / StickyFormTabs / TopBar (client) and amend styling to be able to tab through empty sections. - 2
- [x] Amend Content component, to contain a tabs option that shifts the horizontal line below the tabs. - 3
- [x] Retrieve the config values from offlineData and render the configurable settings using the ListView, separated into "General", "Birth" & "Death".  The headings of Registration time period and Registration fees are just external headings to ListView - 3

**Comment by SyedaAfrida** [comment]
**Bug:**
In mobile view- header for both Application and certificates showing configuration. Should be Application / Certificate.
![gen1](https://user-images.githubusercontent.com/94350336/164431239-ef622113-22bb-4194-a6c6-21de437bdd7a.png)

**Comment by saima-alam** [comment]
@anny320 The bug mentioned by @SyedaAfrida is fixed. This can be closed. 

![image](https://user-images.githubusercontent.com/105625699/170463536-3efc2feb-11d1-4567-8b84-e2f6d7cb1a02.png)

**Comment by anny320** [comment]
completed
