### ISSUE TITLE
As a System Admin, I want to change the government logo

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2556]
### Description

- adds model to change the government logo
- I can only select pngs, svgs? in the file system menu
- updates the login page logo
- updates the review page logo
- need to set the div height on each of the pages. Then fit the image file to max fill that space. So we can accommodate all types of aspects rations. not just square

### Acceptance criteria

GIVEN I am a System Admin
WHEN I click change on the Government logo
THEN open the government logo change model

GIVEN open the government logo change model
WHEN I click upload
THEN show the system file finder

GIVEN i select a png file
WHEN the image file is greater than 2mb?
THEN show the file to large [error state](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=713%3A13002)

GIVEN I select a file 
WHEN I click select
THEN show the [uploading state](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=581%3A11320) 

GIVEN my file has uploaded
THEN enable to the apply button

GIVEN I click apply
THEN apply my new logo to the system

### Design

[https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=581%3A11288](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=581%3A11288)

### Dev-tasks

- [x]  Create the modal, this time with the File Uploader component - 1
- [x] Call the same mutation as before and follow the same error handling and notification, window.config update steps when submitting. - 2
- [x] Save the logo base64 and filename in the config database, you need to change the database schema and refactor out the use of assets entirely. - 2

**Comment by SyedaAfrida** [comment]
**Bug:**
1. SVG not supported in Government logo
2. logo is not updated when changed from Configuration in Certificate, Onboarding welcome screen,  Onboard confirmation screen
![7](https://user-images.githubusercontent.com/94350336/164432822-a28392c2-2cbe-47f7-a431-ee0155d02ed3.png)

**Comment by Fariha-Amin** [comment]
@anny320  please block this ticket till [https://github.com/opencrvs/opencrvs-core/issues/2912#issue-1209293215](url)   is fixed.
