### ISSUE TITLE
As a System Admin, I want to change the user timeout period

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2557]
### Description

- model to set the user timeout
- max = 99 minutes
- field accepts only two numbers

### Acceptance criteria

GIVEN I am a System admin
WHEN I click change on the user timeout config option
THEN open the User timeout model

GIVEN I try to enter more than two numbers 
THEN nothing happens

GIVEN I try to enter a letter or ./[]\` etc
THEN nothing happens

### Design

[https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=577%3A21843](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=577%3A21843)

### Dev-tasks

- [ ]  Task

**Comment by euanmillar** [comment]
This is about the Pin page, not logging out
