### ISSUE TITLE
As a System Admin, I want to change the system currency

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2558]
### Description

- adds model to update the currency
- updates the label for the currency.
    - in certificate fee collection
    - in correct record fee
    - in performance report views
    - in config models for registration fees
- api/data to use for currency? →
    
    

### Acceptance criteria

GIVEN I am a System admin
WHEN i click change in the Currency config option
THEN open the Currency config model

GIVEN open the currency config mod
WHEN click the select field
THEN show the currency dropdown 

GIVEN I select a currency
WHEN click apply
THEN update the system currency to my selection

—

Places where currency appears:

- Certificate collection
- Certificate Receipt
- Correct record summary page
- Performance reports

### Design

[https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=711%3A12990](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=711%3A12990)

### Dev-tasks

- [x] In the config microservice, add a new field for currency and serve it to the client in window.config and get config query, update config mutation

CURRENCY = {
  isoCode: e.g. JPY Currency code from country-data,
  languagesAndCountry: [`${language-string e.g.: "en"}-${window.config.COUNTRY}`]
} // so we can generate currency [symbols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat)

- [x] Create a modal with select, populated by currency options using the [country-data package](https://www.npmjs.com/package/country-data).  Call the same mutation, update window.config show notifications as before - 3
- [x] Amend all copy for prices in these locations, to de-couple the numeric value from the configurable currency value.  Try using formatjs:

```
<FormattedNumber value={1000} style="currency" currency="USD" />
```

in some cases, you may need to use JS: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

- Certificate collection
- Certificate Receipt
- Correct record summary page
- Performance reports

**Comment by sadmananik** [comment]
@euanmillar Currently Certificate receipt printing is broken. As there is no template configured for the Farajaland and also in the core the code is not like that to store receipt template in redux.

**Comment by anny320** [comment]
Completed
