### ISSUE TITLE
As a System admin, I want to config the phone no. regex

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2559]
### Description

- adds model to add a phone no. regex
- allows you to test different numbers
- we check the regex is valid and wont break the system
- default the mask start to 0
- default the mask end to 3 (phone number mask apply’s to the two factor login step)

### Acceptance criteria

GIVEN I am a System Admin
WHEN I click change on the phone number regex config option
THEN open the phone no regex model

GIVEN I change the regex and add a no.
WHEN I click ‘Test number’
THEN check if the number if valid for the given regex

GIVEN I test the number
WHEN I it is valid
THEN show the valid state

GIVEN I test the number
WHEN I it is invalid
THEN show the invalid state

GIVEN I entered a regex pattern and example number
WHEN I click apply
THEN check the regex is valid and update the system

### Design

[https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=577%3A23532](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=577%3A23532)

### Dev-tasks

- [x]  Create a modal with the form. If the supplied regexp can be casted as RegExp then you can run it against the example phone number supplied. - 2
- [x] Run mutations, window.config update and notifications as before - 2
- [ ] Refactor out "example" and "num" instead the copy will explain this.  "start", and "mask" should be dynamically generated where needed. - 2

**Comment by euanmillar** [comment]
Bug - Fix the alignment issues in the DynamicModal

Figma design:

![Screenshot 2022-03-30 at 15.35.44.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/238eca97-e97a-47ea-a3d7-a26482a885da)

**Comment by euanmillar** [comment]
@emon-swe-sust can you fix this design issue please?

**Comment by emon-swe-sust** [comment]
> Bug - Fix the alignment issues in the DynamicModal
> 
> Figma design:
> 
> ![Screenshot 2022-03-30 at 15.35.44.png](https://camo.githubusercontent.com/89767a6771d030274303dbe1fdd279c78442b32f97fa3996cad192c17fa13198/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565393661326434626566623233396534663262636539352f32333865636139372d653937612d343765612d613364372d613236343832613838356461)
> 
> Our code:
> 
> ![Screenshot 2022-03-30 at 15.35.50.png](https://camo.githubusercontent.com/c4ae693bac5855bd7d27f46d0ed60f5f5c8914d876cf75ab036fe097433dd09e/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565393661326434626566623233396534663262636539352f33623361646637342d653236352d346438612d386163352d383566366635353439333130)

@euanmillar , The gap between title and body seems to be okay one my screen, can you check it again? And I am fixing font style on 'Test number'

**Comment by emon-swe-sust** [comment]
Yeah sure. I've fixed it on this [PR](https://github.com/opencrvs/opencrvs-core/pull/2784)  .

And it is look like: 
![Screenshot from 2022-03-31 13-18-58](https://user-images.githubusercontent.com/43314141/161001423-2865e3d0-de8f-4871-b147-12963b3397cd.png)

**Comment by anny320** [comment]
completed
