### ISSUE TITLE
As a System Admin I want to configure the birth registration  time periods and fees

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2562]
### Description

- adds birth tab to Application config option
- config the registration rate period
    - Legally specified
    - Late registration
    - Delayed registration
- config the reg fees for each. The total fee when it comes to print the certificate

### Acceptance criteria

GIVEN I am a System Admin
WHEN I select the Births tab
THEN I can see the birth registration time period config options

**Legally specified time period**

GIVEN I select Change on the Legally specified 
THEN open the [legally specified config model](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=711%3A12763)

GIVEN I click on the text input 
THEN I can only enter digits. A max of two digits (eg. 99 days)

**Late and Delayed registrations**

GIVEN I select Change on the Delayed registrations
THEN open the [delayed registration period model](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=711%3A12774)

GIVEN I click on the text input 
THEN I can only enter digits. A max of two digits (eg. 99 years)

GIVEN I update the delayed registration period
THEN update the late registration period to reflect the time period. 

eg. if legally specific is 10 days and delayed is 10 years. THEN late registration is ‘Between 10 days and 10 years’

—

GIVEN I am in Performance
WHEN I am on the operational dashboard
THEN I should see the registration rates for me chosen time period. (Labels reflect my chosen time period)

**Fees**

GIVEN I click Change on the Within legally specified time
THEN open the [Within legally specified time config model](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=711%3A12810)

GIVEN I click on the text input 
THEN I can enter a number which auto format to a currency format eg. 99,999.99

 

GIVEN I am wanting to print a certificate
WHEN on the fee collection page
THEN I should show the total fee (depending on the time period in which the declaration was registered)

GIVEN I am wanting to print a certificate
WHEN I open the certificate receipt 
THEN it should show the total fee (depending on the time period in which the declaration was registered)

GIVEN I am in Performance
WHEN I open a report
THEN I should see the total fees collected for that time period. 

### Design

[https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=711%3A12763](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=711%3A12763)

### Dev-tasks

There are 3 prices for birth, 1 price before BIRTH_REGISTRATION_TARGET, 2nd price between BIRTH_REGISTRATION_TARGET and LATE_BIRTH_REGISTRATION_TARGET, 3rd price after LATE_BIRTH_REGISTRATION_TARGET.

There are 2 prices for death, 1 price before DEATH_REGISTRATION_TARGET and another price after DEATH_REGISTRATION_TARGET

Amend the config schema to include a new property:
LATE_BIRTH_REGISTRATION_TARGET.

Refactor these properties:

CERTIFICATE_PRINT_CHARGE_FREE_PERIOD: number // This can be deleted becuase it should be calculated using the LATE_BIRTH_REGISTRATION_TARGET or DEATH_REGISTRATION_TARGET

CERTIFICATE_PRINT_CHARGE_UP_LIMIT: number // This can be deleted becuase it should be calculated using the LATE_BIRTH_REGISTRATION_TARGET or DEATH_REGISTRATION_TARGET

These should be replaced:

CERTIFICATE_PRINT_LOWEST_CHARGE: number
CERTIFICATE_PRINT_HIGHEST_CHARGE: number

with:

BIRTH_FEE
LATE_BIRTH_FEE
DELAYED_BIRTH_FEE
DEATH_FEE
LATE_DEATH_FEE
DELAYED_DEATH_FEE

- [x] Amend the resolvers to return these values and save in window.config - 3
- [x] Change the PrintCertificate utils fee calculations to use these values and calculate the correct fee for the event.  (Compare the date of birth/death with the date of registration).  This [calculateDays](https://github.com/opencrvs/opencrvs-core/blob/76209ba904d3bff7ec01621566c7693129cccbba/packages/client/src/views/PrintCertificate/utils.ts#L102) function is wrong because it is using Date.now().  This is the date that the certificate is being printed, not the date of registration.  It should be the date of registration that is used to calculate the fee.  The date of registration should be available in the certifcate - 2
- [x]  Create the modal for 2 Birth time forms - 2
- [x] Call the same mutation as before and follow the same error handling and notification, window.config update steps when submitting. - 2
- [x]  Create the modal for 1 Death time form - 2
- [x] Call the same mutation as before and follow the same error handling and notification, window.config update steps when submitting. - 2
- [x]  Create the modal for 3 Birth fees.  Use the config.CURRENCY and [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) to generate a currency symbol minus the numbers as a prefix - May need to remove numbers from the prefix as a hack to get the symbol. - 2
- [x] Call the same mutation as before and follow the same error handling and notification, - 2
- [x]  Create the modal for 2 Death fees.   Use the config.CURRENCY and [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) to generate a currency symbol minus the numbers as a prefix - May need to remove numbers from the prefix as a hack to get the symbol.  - 2
- [x] Call the same mutation as before and follow the same error handling and notification,  - 2

**Comment by euanmillar** [comment]
@anny320 we need to discuss the fees again with Ed when he is back as I have a question regarding fees associated following the first time the certificate is printed

**Comment by euanmillar** [comment]
Bug: Fix the design issues on this page.

Figma design:

![Screenshot 2022-03-30 at 15.44.43.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/4cb7e8ed-5bc2-43fc-acca-10fbd141df49)

**Comment by euanmillar** [comment]
@sadmananik can you fix these design issues on birth and death and also the Tabs please?

**Comment by SyedaAfrida** [comment]
**Bug:**
 In Time period, any number of digits can be inputted. So inconsistency can occured in Late Registration.
![b1](https://user-images.githubusercontent.com/94350336/164433743-9bbafe02-5224-4a9e-ac47-625bc9060699.png)

To solve this-  we need to set a validation in delayed registration that the min value has to be always legally specified+2 days
In this case Delayed Registration cannot be less than 40002

**Comment by anny320** [comment]
completed
