### ISSUE TITLE
As a System Admin I want to configure the death registration  time periods and fees

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2563]
### Description

- adds death tab to Application config option
- config the registration rate period
    - Legally specified
    - Delayed registration
- config the reg fees for each. The total fee when it comes to print the certificate

### Acceptance criteria

GIVEN I am a System Admin
WHEN I select the Deaths tab
THEN I can see the death registration time period config options

**Legally specified time period**

GIVEN I select Change on the Legally specified 
THEN open the [legally specified config model](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=711%3A12763)

GIVEN I click on the text input 
THEN I can only enter digits. A max of two digits (eg. 99 days)

GIVEN change the Legally specified time period 
THEN update the delayed time period

eg. if legally specific is 10 days and delayed is ‘After 10 days’

—

GIVEN I am in Performance
WHEN I am on the operational dashboard
THEN I should see the registration rates for my chosen time period. (Labels reflect my chosen time period)

**Fees**

GIVEN I click Change on the Within legally specified time
THEN open the [Within legally specified time config model](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=711%3A12810)

GIVEN I click on the text input 
THEN I can enter a number which auto format to a currency format eg. 99,999.99

GIVEN I am wanting to print a certificate
WHEN on the fee collection page
THEN I should show the total fee (depending on the time period in which the declaration was registered)

GIVEN I am wanting to print a certificate
WHEN I open the certificate receipt 
THEN it should show the total fee (depending on the time period in which the declaration was registered)

GIVEN I am in Performance
WHEN I open a report
THEN I should see the total fees collected for that time period. 

### Design

[https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=711%3A12763](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=711%3A12763)

### Dev-tasks

- [ ]  Task

**Comment by euanmillar** [comment]
Completed in the PR

**Comment by SyedaAfrida** [comment]
**Bug:**
In death tab, Should be "Within legally specified time " instead of "late registration"
![D1](https://user-images.githubusercontent.com/94350336/164434653-f83cb14b-bbb7-4e93-9f06-5d9c3f24197b.png)

**Comment by SyedaAfrida** [comment]
@anny320 this bug has passed and can be closed
![late](https://user-images.githubusercontent.com/94350336/172590946-1a820803-3c84-4b3d-8f23-511599d643a4.png)

**Comment by anny320** [comment]
completed
