### ISSUE TITLE
Part 1: Update Address capture fields: As a agent, I want to add the usual place of residence for a mother, deceased or informant

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2571]
Description
- updates section heading to Usual place of residence and reduces font size to 18px BigBodyBold)
- Defaults address selects (Country, Province, District) to where the user is assigned. This is to speed up address input. Majority of declarations will take place form those living in the same Province and District (Top two administrative areas)
- Places Urban/rural radio buttons side by side. (to save space)

Acceptance criteria
GIVEN I am an agent (Field agent, Reg agent or registrar) WHEN navigate to the Mother’s Details, Deceased or informants THEN show the address defaults to where i am assigned.
GIVEN I am an agent (Field agent, Reg agent or registrar) WHEN I select rural THEN show the village input field
GIVEN I am on the review page THEN the label for the address is ‘Usual place of residence’
Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=2220%3A47829

Dev-tasks

- [ ] For any address default state and district to user's office location state and disctrict - 2
- [x] Update the small radio group to layout horizontally. - 2

**Comment by SyedaAfrida** [comment]
@anny320 this is tested. You can review birth declaration testcases and close this ticket

**Comment by anny320** [comment]
completed
