### ISSUE TITLE
Mother's date of birth showing wrong

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2573]
**Bug Description:**
Mother's date of birth is getting changed and showing same as father's date of birth when reviewed by registration agent/ registrar

**Steps to Reproduce:**
1. Login as field agent
2. Create a birth application keeping mother's date of birth null or valid input, and input father's date of birth
3. Click "Send for review"
4. Login as registration agent/ Registrar
5. Go to ready to review
6. Download > review that application
7. Observe mother's and father's date of birth

**Actual Result:**
Mother's date of birth is getting changed and showing same as father's date of birth

**Expected Result:**
Should show the date of birth that was given by field agent

**Screen recording:**
https://www.loom.com/share/40be3598512346a99a24783161107fc5

**Tested on:**
https://login.farajaland-staging.opencrvs.org/
 ** Test Cases**
https://dsinnovators.testrail.net/index.php?/cases/view/1094
**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by euanmillar** [comment]
Similar to place of heritage bug,

**Comment by azantor64** [comment]
@anny320  ,This ticketed is tested.Could you please review.and close that?

**Comment by anny320** [comment]
completed
