### ISSUE TITLE
Update contact point for death application

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2574]
### Description
List of contacts should be the same as Informant list

Mother
Father
Grandfather
Grandmother
Brother
Sister
Legal Guardian
Someone else

On selection ask for the phone number
If someone else ask for phone number
...

### Acceptance criteria

GIVEN
WHEN the option is selected On  selection ask for the phone number
If someone else ask for phone numberTHEN ask for the phone number

### Design

https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=2244%3A47892

### Copy
https://www.notion.so/opencrvs/Death-application-ada99eb56011418b9a8e1cc30c8f519c

### Dev-tasks??

- [ ]  Task 1

**Comment by euanmillar** [comment]
Closing in favour of https://github.com/opencrvs/opencrvs-core/issues/2499
