### ISSUE TITLE
As a System user after clicking new user NID field is taking as invalid though input is valid

### ISSUE THREAD

**Issue by azaworld** [opencrvs/opencrvs-core#2575]
**Steps to Reproduce**

1. Log in as System admin (https://register.farajaland-staging.opencrvs.org)
2. Click on team 
3. Click on New User
4. Give mandatory input
5. Give **NID** field value(123456789)
6. **Continue**

**Output result**

- _After given 9 numeric input it showing (**The National ID can only be numeric and must be 9 digits long)**_

**Expected Result**

- _That field should not show that message after given numeric & 9 digits_
- _Continue Button should work_

![image](https://user-images.githubusercontent.com/70468099/153580086-412b47fe-fe5c-4d03-b320-646da78d996b.png)

**Comment by SyedaAfrida** [comment]
This issue is also araising in Certificate collection page. But NID is working fine in birth and death application
![bug5](https://user-images.githubusercontent.com/94350336/153593944-1cf4d832-dd46-479c-ac26-46d3a7a60120.png)

**Comment by azantor64** [comment]
@anny320 this bug can be closed
![nidfine](https://user-images.githubusercontent.com/70468099/164965257-cce3ea1e-0b0b-4b3e-9592-68a4cfd37091.png)
![nid1](https://user-images.githubusercontent.com/70468099/164965382-ae17d9b7-bdbb-44b4-8839-25ef203e1aae.png)

**Comment by anny320** [comment]
This bug has reoccured have created tickets #3141
