### ISSUE TITLE
Application that goes to outbox for network issue remains in outbox even after connectivity

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2576]
**Bug Description:**
Application that goes to outbox for network issue remains in outbox even after connectivity. Later no other application can be created or submitted from that user type. All goes to outbox

**Steps to Reproduce:**
1. Login as Registrar
2. Go to ready for review
3. Download> Review any application
4. Click register in offline
6. Go online
5. Observe in outbox

**Actual Result:**
application remains in out box and if any other new application is created/ processed all goes to outbox

**Expected Result:**
application should be submitted whenever there is connectivity. And other application should not go to outbox for one application. 

**Screenshot:**
![BUG1.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/abfa43de-28d9-41b8-9a6b-dbf699f03dce)
![bug2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/46cf7871-3d97-4549-9715-b76d428c72dc)

**Tested on:**
https://login.farajaland-staging.opencrvs.org/

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by yeasinhossain-dsi** [comment]
Seems like it is no longer there

**Comment by SyedaAfrida** [comment]
@anny320 This bug is no longer appearing and can be closed
https://www.loom.com/share/acfdacfc2ae74b7cab80f167ebe6c751

**Comment by anny320** [comment]
completed
