### ISSUE TITLE
In Team page, User list the 3 dot menu should not be available for registration agents and registrars

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2577]
**Bug Description:**
3 dot menu should not be available in registration agent and registrar. Edit details, deactivate and reactivate options do not work for registration agent and registrar.

**Steps to Reproduce:**
1. Login as registration agent / registrar
2. Click Team
3. Click 3 dot menu
4. Click edit details/ deactivate

**Actual output:**
System crash when clicked edit details and show error "Sorry! Something went wrong" when tried to deactivate

 **Expected output:**
should not have 3 dot menu for these user types

**Console error:**
Error: GraphQL error: Expected Iterable, but did not find one for field "Query.getRoles".
    at new t (ApolloError.ts:57:5)
    at QueryManager.ts:576:32
    at QueryManager.ts:1091:13
    at Set.forEach (<anonymous>)
    at QueryManager.ts:1087:24
    at Map.forEach (<anonymous>)
    at e.broadcastQueries (QueryManager.ts:1085:18)
    at QueryManager.ts:1237:16
    at Object.next (Observable.js:322:23)
    at v (Observable.js:135:18)
(anonymous) @ breadcrumbs.ts:103
overrideMethod @ VM3524406 react_devtools_backend.js:4061
Promise.then (async)
k @ cmd.js:76
T @ cmd.js:177
(anonymous) @ cmd.js:101
L @ cmd.js:100
T @ cmd.js:183
d @ install.js:70
(anonymous) @ install.js:54
f @ install.js:96
(anonymous) @ cmd.js:109
(anonymous) @ cmd.js:108
Promise.then (async)
(anonymous) @ cmd.js:107
L @ cmd.js:100
T @ cmd.js:183
d @ install.js:70
(anonymous) @ install.js:54
f @ install.js:96
(anonymous) @ cmd.js:109
(anonymous) @ cmd.js:108
Promise.then (async)
(anonymous) @ cmd.js:107
L @ cmd.js:100
T @ cmd.js:183
d @ install.js:70
(anonymous) @ install.js:54
f @ install.js:96
n.<computed> @ bindActionCreators.js:9
(anonymous) @ CreateNewUser.tsx:86
c @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ main.ccf63313.chunk.js:1
ls @ react-dom.production.min.js:212
Mu @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
qa @ react-dom.production.min.js:122
bu @ react-dom.production.min.js:248
su @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
qa @ react-dom.production.min.js:122
Za @ react-dom.production.min.js:123
Ka @ react-dom.production.min.js:122
nu @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
b.setState @ react.production.min.js:12
(anonymous) @ Router.js:34
r @ history.js:155
(anonymous) @ history.js:173
notifyListeners @ history.js:172
D @ history.js:288
(anonymous) @ history.js:369
confirmTransitionTo @ history.js:145
push @ history.js:350
(anonymous) @ middleware.js:32
f @ install.js:93
(anonymous) @ cmd.js:109
(anonymous) @ cmd.js:108
Promise.then (async)
(anonymous) @ cmd.js:107
L @ cmd.js:100
T @ cmd.js:183
d @ install.js:70
(anonymous) @ install.js:54
f @ install.js:96
n.<computed> @ bindActionCreators.js:9
handler @ UserList.tsx:333
s @ react-dom.production.min.js:14
h @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
y @ react-dom.production.min.js:15
st @ react-dom.production.min.js:52
it @ react-dom.production.min.js:51
ut @ react-dom.production.min.js:52
mt @ react-dom.production.min.js:56
R @ react-dom.production.min.js:287
B @ react-dom.production.min.js:19
$t @ react-dom.production.min.js:70
Qt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
qa @ react-dom.production.min.js:122
C @ react-dom.production.min.js:287
Zt @ react-dom.production.min.js:68
r @ helpers.ts:77

**Screen recording:**
https://www.loom.com/share/a91cbff2b2584f1780061b36be42375f

**Tested on:**
https://login.farajaland-staging.opencrvs.org/

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by euanmillar** [comment]
For any office, the 3 dot menu must be available for NATIONAL_SYSTEM_ADMIN

Only for the LOCAL_SYSTEM_ADMIN 's own office, should 3 dots be available.

**Comment by anny320** [comment]
completed
