### ISSUE TITLE
Verification code is not working to reset password

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#2582]
**Steps to Reproduce**

1. Tap (https://login.farajaland-staging.opencrvs.org)
2. Click on **can't log in**
3. Click on my password
4. give valid phone number (0752658545) & Enter
5. Give verification code (000000)
6. Click on continue

_Output result: Continue button isn't working_

Actual result: Continue button should work

**Comment by euanmillar** [comment]
This works @azantor64 .  Please refer to my comment on this ticket: https://github.com/opencrvs/opencrvs-core/issues/2353

**Comment by azantor64** [comment]
_okay_

**Comment by anny320** [comment]
completed
