### ISSUE TITLE
QA Automated test script: Who is applying for birth registration?

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2592]
### Description
Create automated test script for declaration of birth form for  Who is applying for birth registration?

### Acceptance criteria
Validate In progress application tab for FieldAgent view and Registrar user types

### Design
[ticket.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/6dab1aee-caa2-43e8-9950-d0798a1bc7d1) Who is applying for birth registration

### Copy
Application test case 1 https://docs.google.com/spreadsheets/d/1cVpmTAU_40Rlju8z-rqeN9N_exLJcIIQ3n3kFQNCx-I/edit#gid=1821929738

**Figma**
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=6%3A596

### Dev-tasks??

- [ ]  Task 1

**Comment by azantor64** [comment]
@anny320 , it's working as expected . Can be closed

**Comment by anny320** [comment]
completed
