### ISSUE TITLE
QA Automation test for Who is the main point of contact for this application

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2594]
### Description
Create automated test script for declaration of birth form for  Who is the main point of contact for this application

### Acceptance criteria
Validate In progress application tab for FieldAgent view and Registrar user types

### Design
![ticket2.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/4cec37c7-63c3-48dd-abe9-619fe8e9dc8f)

### Copy
Application test case 1 https://docs.google.com/spreadsheets/d/1cVpmTAU_40Rlju8z-rqeN9N_exLJcIIQ3n3kFQNCx-I/edit#gid=1821929738

**Figma**
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=6%3A596
### Dev-tasks??

- [ ]  Task 1

**Comment by azantor64** [comment]
@anny320 , Functional scripts already implemented. Can be closed

**Comment by anny320** [comment]
closed
