### ISSUE TITLE
When logged in as Local system admin, should not have option to change registration office when creating/ editing a user

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2597]
**Bug Description:**
As Local system admin can create and edit user for their own office, so there should not be change option beside registration office while creating / editing an user.

**Steps to Reproduce:**
1. Log in as Local system admin
2. Click team
3. Click 3 dot menu
4. Click edit details
5. Click Change beside registration office> Enter valid office name
6. Click submit

1. Log in as Local system admin
2. Click team
3. Click new user
4. Fill up all field> Confirm
5. Click Change beside registration office> Enter valid office name
6. Click submit

**Actual output:**
show validation "No office found"

**Expected output:**
should not have option to change registration office 

**Screenshot:**
![bug1.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/a0a76c0f-2552-46f6-bf29-6a08cc7fba4e)
![bug2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/10765917-491f-4e74-9642-b391caeaa1f5)
![bug3.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/5d902aed-1398-4835-9857-1187c15595ed)

Tested on:
https://login.farajaland-staging.opencrvs.org/

Desktop:
OS: Windows 10, Ubuntu
Browser: Chrome

- [x] In front end, only show "Change" button if natlsysadmin scope exists.  In the backend throw an error if anyone but natlsysadmin is trying to change the office

**Comment by euanmillar** [comment]
Only National System Admin should be allowed to change office

**Comment by azantor64** [comment]
https://github.com/opencrvs/opencrvs-core/issues/2597
This is okay now
