### ISSUE TITLE
In mobile view for any user download/ review option not showing.

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2602]
**Bug Description:**
Cannot review and update any application since  download/ review option not showing in any user for mobile view.

**Steps to Reproduce:**
1. In mobile login as field agent/ registration agent/ registrar
2. From any tab click any application

**Actual output:**
not showing any download/ update/ review button

**Expected output:**
should have download/ update/ review button so that user can go to review page and conduct other actions

**Screen recording:**
https://www.loom.com/share/dc6838fb825f4a92866b26d8b38a6343

**Tested on:**
https://login.farajaland-staging.opencrvs.org/

**Device:**
Chrome on Galaxy S8+

**Comment by euanmillar** [comment]
Should be fixed when RecordAudit is merged in.

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![mob2](https://user-images.githubusercontent.com/94350336/165500565-e5bd50b4-1c17-4823-b34a-d76130140ff9.png)
![mob1](https://user-images.githubusercontent.com/94350336/165500571-418188b9-c550-4d22-b84c-4ed4a7d27482.png)

**Comment by anny320** [comment]
completed
