### ISSUE TITLE
Demo data: add in progress / rejected applications for field agents

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#2641]
![image](https://user-images.githubusercontent.com/1206987/155994346-936748d7-ff9c-49c4-a64c-f253965b6e5a.png)

Farajaland field agents are doing magnificent work – no rejections or incomplete declarations! However, this is not only because of the hardworking declaration agents, but mostly because the demo data generator doesn't yet support generating declarations with these statuses.

Let's add a feature to the generator that would allow us to generate incomplete and reject applications. The figures should be ~5% incomplete for each agent and 1-2% rejected per years.

- [x] Pass 2 new properties "probabilityToBeIncomplete" & "probabilityToBeRejected" to  birthDeclarationWorkflow & deathDeclarationWorkflow.

If Math.random() < probabilityToBeIncomplete then leave gender blank when notifying and ensure to populate the incompleteFields value with 'gender'.  

When registering, put the gender in, then register.

If Math.random() < probabilityToBeRejected then do not register the application, instead reject it.

**Comment by euanmillar** [comment]
If metrics database in prod has the wrong data for started by in Influxdata.  Then we need to tech design a migration to correct the metrics in Influxdata.  When we get more info, lets move this back to tech design as a top priority.

**Comment by euanmillar** [comment]
Is this only happening for in progress and rejected ones?  Or is every application in metrics thinking it is started by the wrong person

**Comment by rabiulislamanik** [comment]
> Is this only happening for in progress and rejected ones? Or is every application in metrics thinking it is started by the wrong person

It is only happening for rejected ones. When a registrar rejects, the registrar's id gets was getting set to the ''started_by" column of "declarations_rejected" measurement.

**Comment by euanmillar** [comment]
![Screenshot 2022-09-21 at 17.09.31.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/57e8a511-9bd1-4d55-a905-365282fbffd2)
@rikukissa are you happy with this?  The data is in production.  If so I think this is done.

**Comment by rikukissa** [comment]
Looks good to me 👍

**Comment by anny320** [comment]
completed
