### ISSUE TITLE
Component lib fonts do not reflect the application fonts

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2642]
- [ ] Fix the font rendering in Storybook so that the fonts look the same as the client.  Maybe an issue with font-face

**Comment by SyedaAfrida** [comment]
@anny320 This is fixed and can be closed
![2642-2](https://user-images.githubusercontent.com/94350336/173501256-a041039a-c217-4787-8fd7-5bb4798368fb.png)
![2642-1](https://user-images.githubusercontent.com/94350336/173501263-b994a816-bebe-445a-8a00-2658533a9769.png)

**Comment by anny320** [comment]
closed
