### ISSUE TITLE
Remove previous search and form entries

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2660]
### Description

- We need to stop saving previous search queries so they don't appear
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/48370e43-a673-4633-903a-e25cb121cc2b)

- need to remove previous data entered in form eg. phone numbers etc. So dropdowns like this **don't** show
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/b183b23a-fd39-4f1b-948f-116ba3179416)

### Acceptance criteria

GIVEN
WHEN
THEN

### Dev-tasks

- [ ] In the SearchTool > SearchTextInput, set autocomplete to off - 0.5
- [ ] Remove the unused components > interface > SearchInput component from the library - 0.5

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**retest SS:**
![d](https://user-images.githubusercontent.com/105624748/172133116-f158ec32-740e-4d2a-9ae2-93ac35189a97.PNG)
![dd](https://user-images.githubusercontent.com/105624748/172133123-de790954-9be0-4c23-8326-9afdc3d10151.png)

**Comment by anny320** [comment]
completed
