### ISSUE TITLE
Refactor a new approach to configuring default languages and available fonts

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2663]
At the moment: languages are configured in client config.js files like this:

https://github.com/opencrvs/opencrvs-farajaland/blob/develop/src/farajaland/config/login-config.js

Additionally it must be set here in farjaland:

https://github.com/opencrvs/opencrvs-farajaland/blob/2087e1019422148382d143478eac7d212d094d6c/docker-compose.countryconfig.staging-deploy.yml#L15

https://github.com/opencrvs/opencrvs-farajaland/blob/2087e1019422148382d143478eac7d212d094d6c/docker-compose.countryconfig.staging-deploy.yml#L44

&

https://github.com/opencrvs/opencrvs-farajaland/blob/2087e1019422148382d143478eac7d212d094d6c/docker-compose.countryconfig.staging-deploy.yml#L48

Fonts are hardcoded in core:

https://github.com/opencrvs/opencrvs-core/blob/a76b66c88823de0be57170cd90117bb92d66c901/packages/client/src/components/Page.tsx#L63

Finally in the i18n reducer this property must be changed:

https://github.com/opencrvs/opencrvs-core/blob/a76b66c88823de0be57170cd90117bb92d66c901/packages/client/src/i18n/reducer.ts#L43

Therefore it is currently not only difficult but impossible to configure another language independently.  This has to change.  We need a single place, be that a text file or config file to add a language string and font file which everywhere else can use.  They can either use it via environment variable, API endpoint, or bash script substitution in deployment.

The important thing, is that there should be a single place in Farajaland repo to make the configuration

We are using Noto Sans, and Noto Sans supports every language and character set.  If the langauges supplied require more than one font character et e.g. en, bn.

**Comment by euanmillar** [comment]
LANGUAGES has to go in the config microservice because workflow and metrics needs to requests it via a handler.  

Default language should be hardcoded as English so that name mappings dont break in default.ts.
Mutations and queries need refactored.

Should be a form definition settings variable for multiple language sets in names.

yarn dev and setup.sh need to remove the language string

Font file & font-face in Page.tsx. Users can change a secondary char set file which has a generic filename in public folder / font face

**Comment by SyedaAfrida** [comment]
@anny320 Nothing to test by QA from this ticket

**Comment by anny320** [comment]
closed
