### ISSUE TITLE
Update RecordAudit view for Clerk and Field Agent

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2668]

**Comment by euanmillar** [comment]
@jpye-finch need some kind of design

**Comment by euanmillar** [comment]
I think this will be resolved by: https://github.com/opencrvs/opencrvs-core/issues/3120

**Comment by SyedaAfrida** [comment]
@anny320 Since #3120 is passed, you can close this ticket too

**Comment by anny320** [comment]
closed
