### ISSUE TITLE
/data folder won't get mounted automatically when servers are restarted

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#2688]
I'm not sure if this is a known issue or by design, but I think this is something we should address. Servers can boot randomly, and data not being mounted means that all services will remain down.

if the data folder is encrrypted and the server restarts, the folder cannot mount.  Some [research](https://www.reddit.com/r/selfhosted/comments/ubvr8z/comment/i67fiou/?utm_source=reddit&utm_medium=web2x&context=3)

- [x] Move all the docker compose files out of tmp into a permanent directory - research an appropriate linux directory for these to live eg:  var/opencrvs/. Update anywhere we refer to tmp/compose ...
- [x] Setup staging server so that it can be used to debug the issue.  Take it down. Run Ansible script with encrypted password.  Deploy stack again.  Create some registrations.  

~~Write a Github action script "restart" which will check the hashes of core and farjaland that are running, take stack down, and if the encryted key is provided as a Github secret, mount the directory & unencrypt it, then regardless redeploy the previous hashes.~~

- [x] In the end I had to create a systemd service which calls a shell script to unencrypt the folder on reboot.  I updated Ansible scripts to create the service.  Cron will not work as cron has no access to the dependencies. This approach is working fine on staging.  
- [x] Removed all references to unsupported Node version 14.15...
- [x] Checkout correct core branch in deploy to get the relevant compose and infra files
- [x] Move secrets from crontab into an encrypted file for Mongo and Elasticsearch
- [x] Allow secret provision to be configurable by a hardware security module to override the above if desired

Given our current security design, it doesn’t make our security worse if we (as a temporary solution) store the env variables for backup inside the encrypted partition. If someone gains access to read those files, they already have access to all of our secrets.

Basically, we have (at least) three different attack scenarios:

1. An attacker finds their way inside one of our running docker containers
They find all environment variables given to the container from printenv  or by being able to execute console.log(process.env)  or similar.
They can only find a subset of secrets (hopefully not the subset with superuser passwords)
We protect ourselves from this by making environment variables and access rights as limited as possible

2. An attacker steals the physical hard-drive
As long as environment variables are stored inside the encrypted partition and the decryption key is not on the hard drive, we are pretty much covered.

3. An attacker gains access to one of the host machines
This is pretty much game over. They have access to all containers and their environment variables, all mounted storage devices.
This to me seems like the only viable way to read all data on the encrypted drive  

- [ ] Create a new page in the documentation "7.6 Restarting OpenCRVS on a server" that describes the new github action.  Add instructions for adding the encryption key that was used in step 3.3.2 Install Dependencies to the section 3.3.6 Deploy where we discuss Github secrets.  Amend 3.3.7 to direct people to "7.6 Restarting OpenCRVS on a server" if the user is using encryption.

- [ ] Add requirement to bump Node version in migration docs
- [ ] Add requirement to run Playbook again in migration docs with new paramter names
- [ ] Add option to configure the Playbook in docs

**Comment by euanmillar** [comment]
@rikukissa  If you are running OpenCRVS v1.0.1 and reboot, you can run these commands to remount the encrypted folder.  

1. Check if there is a loop device enabled
```
echo $(losetup -j /cryptfs_file_sparse.img | awk '{print substr($1, 1, length($1)-1)}' | head -1)
```
will output something like "/dev/loop5" or nothing.  If it outputs nothing, try:
```
echo $(losetup --find --show /cryptfs_file_sparse.img)
```
2. Using that parameter now run this command to decrypt the LUKS folder and set a mapping name:
```
echo <!-- your encryption password --> | cryptsetup -d - lluksOpen /dev/loop5 cryptfs || true
```
3. Remount the folder
```
mount /dev/mapper/cryptfs /data || true
```

**Comment by rikukissa** [comment]
Thanks, Euan! We've been using the mount script to do this manually when the environment starts https://github.com/opencrvs/opencrvs-core/blob/a628dfe04b90a5c441f35b9067cbfc67c18bb68a/infrastructure/cryptfs/mount.sh

In our production environment, we do need a way to automate calling this somehow, however. The developers will not have access to SSH into the production servers (these servers are in a virtual private network), and the decryption key is only known by few. It's also a pretty significant risk to allow maintainers to manipulate the primary data storage.  

I think the approach of the rebooting server fetching the decryption key from other nodes in the cluster might be the simplest and would allow the nodes to crash freely without human intervention. I'll ask around for tool recommendations and for a simple way of doing this
