### ISSUE TITLE
Application search not available on Performance and Team pages for Reg Agent, Registrars

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2698]
**Describe the bug**
- missing search bar and application add button on Performance and Team Pages
- was correctly removed for System Admins.

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as Reg Agent or Registrars
2. Nav to Performance page. 
3.  Note there is no search bar or application add button. 

**Expected behaviour**
Same topbar that appears on Application pages should be on Performance and Team pages for Reg Agent, Registrars

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/580962ad-6009-40e5-bc84-13f2c87ac9be)If applicable, add screenshots to help explain your problem.

- [ ] The search tool, should appear in the performance and team header for Registrars and RegAgent.  It should only be hidden for Local & National Sys Admin when in Performance and Team pages

**Comment by azantor64** [comment]
@jpye-finch ,will it be the same feature(search bar & add button)  for performance & team pages in **mobile view**?

**Comment by azantor64** [comment]
**Bug :** missing application add button on Performance and Team Pages
![image](https://user-images.githubusercontent.com/70468099/165248881-834d37f9-8c2c-4651-8c02-c2ab109028b7.png)

![image](https://user-images.githubusercontent.com/70468099/165249000-e4d93cdf-9f95-42d8-99c9-fc4a5a97d68d.png)
![image](https://user-images.githubusercontent.com/70468099/165249050-be4aa518-4b62-4662-b8f6-c00b35786903.png)

**Comment by atiqzaman-dsi** [comment]
@jpye-finch I think you had decided to remove the search on performance page mobile view. If is it same for the team page then it should be a bug.

**Comment by anny320** [comment]
closed
