### ISSUE TITLE
N + 1 query problem in graphql

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#2702]
Currently the queries in the app have the N + 1 query problem. For example, in RecordAudit view the query for the history table as shown below: 
![image](https://user-images.githubusercontent.com/29002716/157627680-ae0e5500-3b45-4113-ae1b-96d3260ba523.png)
If we take a look at the `Location` column, every row has the same location and only one query should be needed for getting the location. But currently there will be N(the number of rows) queries for the same location to the database from GraphQL. The same is also true for the `By` column.

Fortunately, as this is a pretty common problem with GraphQL, there is a generic utility [DataLoader](https://github.com/graphql/dataloader) they provide for batching and caching the queries.

**Comment by rikukissa** [comment]
Will be mostly fixed with this PR https://github.com/opencrvs/opencrvs-core/pull/5879

**Comment by Zangetsu101** [comment]
yeah I think we can close this one
