### ISSUE TITLE
We need to refactor the approach for notes, reason for rejection / comments

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2703]
When we are rejecting an application, the reason for rejection is currently submitted to the gateway and then the Task in the notes array.  This makes it impossible to distinguish.

So instead we need to submit the reason for rejection not as a "note" but instead in the Task "reason" prop.

- [x] Make new mapping functions for rejected reason in the client - 2
- [x] Adapt the Task type-resolvers and fhir-builders for the reason in the gateway - 2
- [x] Adapt the actions detail modal in Record Audit to display rejected reason according to the design - 1

**Comment by atiqzaman-dsi** [comment]
I found a backend issue unfortunately, I am not sure if we know it or am I doing any mistake. FA submitted a declaration with a comment for review, Registrar registered it and changed the comment. It replaced the comment and didn’t set the authorString.
<img width="1263" alt="Screen Shot 2022-06-23 at 2 48 08 PM" src="https://user-images.githubusercontent.com/8521992/177247367-296aa6b4-5d00-4cd3-8116-771e36afeec2.png">

**Comment by SyedaAfrida** [comment]
**Bug:**
1. Correction record showing- Registrar, National Registrar, Registration Agent options in Correction requester page. Should not have these 3 options.
![correction record](https://user-images.githubusercontent.com/94350336/185584013-4463e83b-2b71-4684-b83f-018e48e14dce.png)

2. All the actions of history are showing - Printed on collection and ID check rows
Printed on collection should appear only in certified
ID check should appear in Certified and record corrected
![cor1](https://user-images.githubusercontent.com/94350336/185584432-52ff1b8a-4fac-4c7b-93d2-a5fc4d90b383.png)

3. In corrected record- "Requested by" row is missing and Comment should be replaced "Reason for request". Check the figma design-
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications-v1?node-id=1%3A3541

4. Download action after corrected record action shows- item, original and edit row. should not show this in download.

https://user-images.githubusercontent.com/94350336/185584151-819068c5-aeb8-42e5-ad84-83e490ecb8d5.mp4

**Comment by yeasinhossain-dsi** [comment]
Number 1,2,3(Partially),4 is done. 
But it seems: Following issue needs a ticket as they are not implemented.

- Requester
- Reason for Request (Other)
- Number 6

I have created a new ticket for them to be implemented:
https://github.com/opencrvs/opencrvs-core/issues/3816.

Further discussion on scrum

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is tested and can be closed
![5](https://user-images.githubusercontent.com/94350336/186631089-66bd7212-81d6-4402-bedd-a589b68eeaab.png)
![4](https://user-images.githubusercontent.com/94350336/186631102-b2f7c79a-a120-4a08-9ef9-12a461809cfa.png)
![3](https://user-images.githubusercontent.com/94350336/186631109-1e197292-94f8-4819-9947-f7d3f89de6f1.png)
![2](https://user-images.githubusercontent.com/94350336/186631115-ba7b77d3-d322-4661-b4f4-a565e8752844.png)
![1](https://user-images.githubusercontent.com/94350336/186631119-d6f62e06-4640-4945-9757-d08cd94457de.png)

**Comment by anny320** [comment]
completed
