### ISSUE TITLE
Fix potential query injections in metrics service

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#2705]
In many places where we query from InfluxDB data, we use string interpolation to formulate the query: 

https://github.com/opencrvs/opencrvs-core/blob/bf117febf8de0120a05f39de6fca7494baa1ede3/packages/metrics/src/features/searchMetrics/service.ts#L24

This can be dangerous, as a malicious user could pass in a parameter that manipulates the query structure itself. 

Consider for example `clientId = "'; DROP measurement search_requests; SELECT FROM search_requests WHERE clientId = 1 "`. This would evaluate the full query string to a form of 

```
`SELECT COUNT(clientId) FROM search_requests WHERE clientId = ''; DROP measurement search_requests; SELECT FROM search_requests WHERE clientId = 1 "' AND time >= '${currentDate}'`
```

Not great! We have discovered, that our current InfluxDB client, although quite outdated, supports a thing called "placeholders" that are meant to automatically escape the query variable and solve this problem for us. We are currently using that method in few places like in [here](https://github.com/opencrvs/opencrvs-core/blob/bf117febf8de0120a05f39de6fca7494baa1ede3/packages/metrics/src/features/certifications/service.ts#L35-L41).

Unfortunately the placeholders do not work for integer values in the version we're using. https://github.com/node-influx/node-influx/issues/587

**Dev tasks:**

- [x] Research if there is a more recent version / alternative available for connecting & querying influxdb from Node.js
- [x] Go through the current queries, use placeholders as much as possible

**Comment by Eezi** [comment]
We are now using influx version ^5.0.7 and the bug was fixed on version 5.9.2. Can we update this library to the latest version, which is version 5.9.3.?  And after the update we can start using the placeholders where the potential query injections are.
