### ISSUE TITLE
Update Team page to use Content component

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2707]
### Description
- updates Team page to use Content component
- Field Agent/RegClerk view (no user audit link): https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=3218%3A53589
- Registrar (user audit link) https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=3219%3A53817
- System Admin (user audit link and user edit options) https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4287%3A111369

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=3219%3A58458

### Dev-tasks
- [ ]  ActionPageLight needs refactored so that it can take a different header on desktop and mobile

**Comment by anny320** [comment]
New user button not visible in mobile view for national sys adminhttps://images.zenhubusercontent.com/91778759/36b41537-8298-4f8d-95a5-37c5621348c8/screen_capture__7_.mp4

**Comment by saima-alam** [comment]
@anny320, This can be closed. New user button is showing for National sys admin. 

![image](https://user-images.githubusercontent.com/105625699/175036913-a4541720-5036-4c56-9db6-79a467ba04d4.png)

But found a new bug that New user button is not showing for the Local sys admin. Reported a new bug #3550 for this.

**Comment by anny320** [comment]
completed
