### ISSUE TITLE
Updates UserAudit to use Content component

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2715]
### Description

- updates UserAudit to user Content component. Large.
- mobile design

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=2216%3A45558

### Dev-tasks

- [ ]  Task 1

**Comment by euanmillar** [comment]
Should close in favour of a bigger epic

**Comment by jpye-finch** [comment]
closing. in advance of a detailed User Audit Epic and tickets

**Comment by anny320** [comment]
closed
