### ISSUE TITLE
As a system admin, I can view my published form and drafts declarations

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2722]
### Description

- add form configuration summary page
- adds tab for published
- adds tab for drafts
- onPublish then the [declaration form can no longer be configured ](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1159%3A24531)

### Acceptance criteria

WHEN  the form config has been completed, the changes to the form can be reviewed before saving.
WHEN  draft tab clicked, you can see any saved drafts

### Design
https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1090%3A17132

### Dev-tasks

- [x] Add Declaration Forms as a link, when clicking on declaration forms, load a new page called FormConfiguration in a new folder client/src/views/SysAdmin/Config/Form using Content (medium) component & set up Tabs for Published and Drafts - 2
- [x] Hardcode the Published view using ListView component.  Sub menu items are to be defined in the design - 1
- [x] Drafts will be loaded from this [ticket](https://github.com/opencrvs/opencrvs-core/issues/2739) and populated in a ListView - 2

**Comment by euanmillar** [comment]
Blocked, waiting for @sadmananik

**Comment by SyedaAfrida** [comment]
@anny320 Form config testcases are update and have reported all the bugs separately in new tickets. So this ticket can be closed

**Comment by anny320** [comment]
closed
