### ISSUE TITLE
As a national system admin, I can save and publish a draft of my configuration

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2723]
### Description

- save button in topBar
- onSave show confirmation model with option to add a description of changes
- onConfirmation create a new draft and navigate to Draft tab
- previous drafts can not be viewed

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1589%3A26583

### Show a warning to the user if they have no published drafts for any event.  

- [x] This is because their declaration forms are currently set to Farajaland defaults for each event.  Build a Warning component in the component library which takes text. -1

- [x] In the application config load, we need to check that any form configuration for an event is in either an IN_PREVIEW or PUBLISHED state.  If the event not in these statuses, then no configurations should be made.  Field Agents and Registrars should be using Farajaland default if they were to log in.   Only perform configurations for this event if the status is IN_PREVIEW or PUBLISHED:  https://github.com/opencrvs/opencrvs-core/blob/edef2256c70cb3045753509b46b1b51e01eb1351/packages/client/src/forms/configuration/index.ts#L220 pass the draft config into these reducers here: https://github.com/opencrvs/opencrvs-core/blob/edef2256c70cb3045753509b46b1b51e01eb1351/packages/client/src/forms/register/reviewReducer.ts#L54 and https://github.com/opencrvs/opencrvs-core/blob/edef2256c70cb3045753509b46b1b51e01eb1351/packages/client/src/forms/register/reducer.ts#L59 - 2

- [x] In Drafts Tab, list all events. If there is no draft for the event or draft status is DELETED show a Configure button.  If the status is DRAFT, show the Edit button with menu (Preview / Delete).  If the status is IN_PREVIEW or PUBLISHED, show the Green pill only.  For every draftModifiedAt line, add a comment and a row,  Ensure that the "Edit" button or pills (explained below) display only on the latest row if there is more than 1 row.  - 2

- [x] In Drafts Tab, clicking preview, will open a modal overlay with confirmation text warning the user that all test declarations and registrations will be archived if you proceed.  If you click Preview, then call the modifyDraftStatus mutation with an IN_PREVIEW status change request.  Show toast notification. - 2

- [x] In Drafts Tab, clicking delete, will open a modal overlay with confirmation text warning the user that all test declarations and registrations will be archived if you proceed.  If you click Delete, then call the modifyDraftStatus mutation with a DELETED status change request.   Show toast notification. - 2

- [x] In Preview Tab, show an empty state similar to this if there are no drafts or draft status is DELETED:  https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1589%3A28740 - 0.5

- [x] In Preview tab, list all event form configurations where the draft status === IN_PREVIEW, with an Edit and Publish link.  Clicking edit, will open a modal overlay with confirmation text warning the user that all test declarations and registrations will be archived if you proceed.  If you click Edit, then call the modifyDraftStatus mutation with a DRAFT status change request.  Show toast notification. - 2

- [x] In Preview tab, clicking published, will open a modal overlay with confirmation text warning the user that all test declarations and registrations will be archived if you proceed.  If you click Publish, then call the modifyDraftStatus mutation with a PUBLISH status change request.  Show toast notification. - 2

- [x] In Preview tab or Drafts tab, if an event is Published.  Display the published pill and modifiedAt date - 0.5

- [x] In Published Tab, show the empty state https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1589%3A28740, or display the published row, published pill and statusModifiedAt date for all published events.  Update the warning component to remove the events that are published, or hide it altogether - 2

- [x] In the form configuration header, there is a save button to save changes to the draft configuration.  On click, open a modal to add "Description of changes"comments on the configuration change.  Build the modal with comment form.  https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1099%3A61563. - 2

- [x] Clicking save, will call the mutation that already exists and redirect the user to the Drafts tab of configuration management. Filter questions to compare edits with the draft and perform changes. - 3

**Comment by euanmillar** [comment]
Blocked by: https://github.com/opencrvs/opencrvs-core/issues/2774

**Comment by euanmillar** [comment]
Just waiting final designs from @jpye-finch

**Comment by SyedaAfrida** [comment]
@anny320 Form config testcases are update and have reported all the bugs separately in new tickets. So this ticket can be closed

**Comment by anny320** [comment]
completed

**Comment by anny320** [comment]
completed
