### ISSUE TITLE
As a system admin, I want to see the content keys and certificate handles for a default form element

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2724]
### Description

- onClick of a form element [I can see the content keys and certificate handle](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1094%3A34148)
- A form element has a hover and active state (yellow border)
- User can see the content keys and certificate handle in the rightSideMenu
- onClick of another form element updates the rightSideMenu
- when no form element is active (yellow border) Then update the [rightSideMenu to its default state](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1090%3A17678)

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1094%3A34148

### Dev-tasks

- [x]  Create an FormConfigElementCard container for selection in FormConfigCanvas in the styleguide.  It can contain any component  {children} ie section title, form field, paragraph, group of fields, custom design or a visual representation of an address.  It is clickable, it can either be repositioned or not (movable: boolean) like this one for attendant type: https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1099%3A60458.  It has optional positioning arrows with differentiating click handlers and differenting visibility (e.g. If its at the top, then top arrow disables).  It has an optional trash icon.  It has a grey dashed outline and a yellow focus state.  The background element is clickable with a handler - 3

- [x] In FormConfig Canvas, load all of the fields associated with the section in default.ts and load into the canvas, inside FormConfigElementCards.  Please ignore addresses and place of delivery section for now.  This form rendering method will help:  https://github.com/opencrvs/opencrvs-core/blob/352b154ba9bab0d24e8c282e108e188155cbaaa6/packages/client/src/forms/configuration/index.ts#L220 - 3

- [x] In FormTools, create a sub view called DefaultFieldTools https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1094%3A26264 and mark up the UI for the optional hide toggle and optional required toggle in a ListView,  content key lists and handlebars list - 2

- [x] Develop actions / methods that retrieve the selected field and content keys for the content key list and  fieldName for the handlebar - 2

**Comment by euanmillar** [comment]
Requires help from @jpye-finch

**Comment by euanmillar** [comment]
Euan to decide editable fields

**Comment by SyedaAfrida** [comment]
@anny320 Form config testcases are update and have reported all the bugs separately in new tickets. So this ticket can be closed

**Comment by anny320** [comment]
closed
