### ISSUE TITLE
As a user I want to hide and show fields

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2725]
### Description

- [Adds Toggle to RightSideMenu. ](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1099%3A60456)
- OnToggle of Hide field to On. Then add Hidden Pill and hide field
- Do not show Toggle for default mandatory question eg. child date of birth (TBD)

- On Default RightSideMenu state. [Add Show hidden fields toggle](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1090%3A17678)
- OnToggle of Show hidden fields. Show all hidden fields on all pages. 
- No Hide field toggle for Custom fields

### Design
https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=2153%3A30287

### Dev-tasks

FYI: enabled is a string in IFormFieldBase for hidden fields.  The reason I gave in the Question schema was this:

```
// enabled should be a string "DISABLED" or "" or undefined because existing default fields will be ""
  // wanted to use disabled, but this prop is already in use in IFormField
  enabled?: string
```

I think I meant that existing uncustomisable default fields will not have this property.  Hence if I checked for a boolean True or False, it would always return false when rendering the form

- [x]  We need to create the hidden pill and have that pill replace trash for fields where customisable === true
in the FormElementCard
- [x] In the default canvas view, toggling show hidden fields will display any fields that are hidden
- [x] In the tools for a non-custom question, you can toggle the hide / show and see the pill appear / disappear
- [x] In the tools for a custom field, remove the hide / show toggle entirely - requires #2945 to merge in
- [x] In the draft and backend config microservice, we think we can re-use the enabled boolean for hide/show

**Comment by jpye-finch** [comment]
have update link to design

**Comment by SyedaAfrida** [comment]
@anny320 Form config testcases are update and have reported all the bugs separately in new tickets. So this ticket can be closed

**Comment by anny320** [comment]
closed
