### ISSUE TITLE
As a system admin, I want to change the order of questions

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2727]
### Description

- adds up/down arrows to form element
- OnClick up move the element up one. 
- OnClick Down move the element down on
- PageTitle can not be moved. Hide Up/Down buttons
- Disable up button for first element (after PageTitle) 
- Disable down button for last element

### Acceptance criteria

GIVEN
WHEN
THEN

### Dev-tasks

- [x] In the UI add the up and down arrow buttons.  Every field has these buttons whether it is customisable or not.
- [x] When you click up or down, we need to save a new preceedingFieldId & foregoingFieldId or null.  We need to re-render the canvas to show that the field has moved.  Change redux state appropriately
- [x] Ensure the the new field positions are reflected properly in the register application

**Comment by euanmillar** [comment]
Discuss connectivity

**Comment by euanmillar** [comment]
Works for custom fields only at the moment.  If we have time we will come back and look at moving default fields.

**Comment by SyedaAfrida** [comment]
@anny320 Form config testcases are update and have reported all the bugs separately in new tickets. So this ticket can be closed

**Comment by anny320** [comment]
completed
