### ISSUE TITLE
For a registrar, when clicked on download button from any tab, there is console errors

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2731]
**Bug description:**
When clicked on download button from any tab ( in progress/ ready for review/ ready to print) , there is console errors. This console errors are only showing for Registrars, not fore Registration clerk).

**Steps to reproduce:**
1. Login as registrar
2. Go to  in progress/ ready for review/ ready to print
3. Click download icon for any application
4. Observe the console

**Actual Result:**
![console error on clicking download.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/37350b9d-c101-402c-ace3-8fba79f7a508)

**Expected Result:**
Should not have any console errors

**Console error:**
Exception thrown when running Cmds from action: DECLARATION/DOWNLOAD_DECLARATION_SUCCESS.

Thrown exception: 
Invariant Violation: Invariant Violation: 12 (see https://github.com/apollographql/invariant-packages)

(anonymous) @ breadcrumbs.ts:103
overrideMethod @ react_devtools_backend.js:3973
(anonymous) @ install.js:83
Promise.catch (async)
d @ install.js:76
(anonymous) @ install.js:54
f @ install.js:96
(anonymous) @ cmd.js:109
(anonymous) @ cmd.js:108
Promise.then (async)
(anonymous) @ cmd.js:107
L @ cmd.js:100
T @ cmd.js:183
d @ install.js:70
(anonymous) @ install.js:54
f @ install.js:96
n.<computed> @ bindActionCreators.js:9
a @ DownloadButton.tsx:79
onClick @ DownloadButton.tsx:119
s @ react-dom.production.min.js:14
h @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
y @ react-dom.production.min.js:15
st @ react-dom.production.min.js:52
it @ react-dom.production.min.js:51
ut @ react-dom.production.min.js:52
mt @ react-dom.production.min.js:56
R @ react-dom.production.min.js:287
B @ react-dom.production.min.js:19
$t @ react-dom.production.min.js:70
Qt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
qa @ react-dom.production.min.js:122
C @ react-dom.production.min.js:287
Zt @ react-dom.production.min.js:68
r @ helpers.ts:77
breadcrumbs.ts:103 
Exception thrown when running Cmds from action: DECLARATION/ENQUEUE_DOWNLOAD_DECLARATION.

Thrown exception: 
Invariant Violation: Invariant Violation: 12 (see https://github.com/apollographql/invariant-packages)

(anonymous) @ breadcrumbs.ts:103
overrideMethod @ react_devtools_backend.js:3973
(anonymous) @ install.js:83
Promise.catch (async)
d @ install.js:76
(anonymous) @ install.js:54
f @ install.js:96
n.<computed> @ bindActionCreators.js:9
a @ DownloadButton.tsx:79
onClick @ DownloadButton.tsx:119
s @ react-dom.production.min.js:14
h @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
y @ react-dom.production.min.js:15
st @ react-dom.production.min.js:52
it @ react-dom.production.min.js:51
ut @ react-dom.production.min.js:52
mt @ react-dom.production.min.js:56
R @ react-dom.production.min.js:287
B @ react-dom.production.min.js:19
$t @ react-dom.production.min.js:70
Qt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
qa @ react-dom.production.min.js:122
C @ react-dom.production.min.js:287
Zt @ react-dom.production.min.js:68
r @ helpers.ts:77
invariant.ts:13 Uncaught (in promise) Invariant Violation: Invariant Violation: 12 (see https://github.com/apollographql/invariant-packages)
    at new t (https://register.farajaland-qa.opencrvs.org/static/js/2.fbff6814.chunk.js:2:297678)
    at u (https://register.farajaland-qa.opencrvs.org/static/js/2.fbff6814.chunk.js:2:297908)
    at e.query (https://register.farajaland-qa.opencrvs.org/static/js/2.fbff6814.chunk.js:2:1048499)
    at e.query (https://register.farajaland-qa.opencrvs.org/static/js/2.fbff6814.chunk.js:2:1060831)
    at NE (https://register.farajaland-qa.opencrvs.org/static/js/main.cc442fdd.chunk.js:1:709668)
    at https://register.farajaland-qa.opencrvs.org/static/js/2.fbff6814.chunk.js:2:174511
    at Array.reduce (<anonymous>)
    at J (https://register.farajaland-qa.opencrvs.org/static/js/2.fbff6814.chunk.js:2:174423)
    at https://register.farajaland-qa.opencrvs.org/static/js/2.fbff6814.chunk.js:2:174980
    at https://register.farajaland-qa.opencrvs.org/static/js/2.fbff6814.chunk.js:2:172838
t @ invariant.ts:13
u @ invariant.ts:24
e.query @ QueryManager.ts:751
e.query @ ApolloClient.ts:328
NE @ index.ts:1671
(anonymous) @ merge-child-reducers.js:37
J @ merge-child-reducers.js:24
(anonymous) @ combine-reducers.js:11
(anonymous) @ install.js:36
y @ redux.js:288
(anonymous) @ index.umd.js:101
(anonymous) @ middleware.js:26
f @ install.js:93
(anonymous) @ cmd.js:109
(anonymous) @ cmd.js:108
Promise.then (async)
f @ install.js:96
n.<computed> @ bindActionCreators.js:9
a @ DownloadButton.tsx:79
onClick @ DownloadButton.tsx:119
s @ react-dom.production.min.js:14
h @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
y @ react-dom.production.min.js:15
st @ react-dom.production.min.js:52
it @ react-dom.production.min.js:51
ut @ react-dom.production.min.js:52
mt @ react-dom.production.min.js:56
R @ react-dom.production.min.js:287
B @ react-dom.production.min.js:19
$t @ react-dom.production.min.js:70
Qt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
qa @ react-dom.production.min.js:122
C @ react-dom.production.min.js:287
Zt @ react-dom.production.min.js:68
r @ helpers.ts:77

**Tested on:**
https://register.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by euanmillar** [comment]
@SyedaAfrida can you please empty cache and see if this is still happening?
