### ISSUE TITLE
When logged in as Registrar cannot load "correct record" pages or "review" page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2733]
**Bug description:**
As a Registrar, when clicked on Correct record button from audit record page, then correct record steps are not showing.
As a Registrar, when clicked on any change link in review page, then cannot  navigate to that specific page and change data

**Steps to reproduce:**
1. Login as Registrar
2. Go to Ready to print
3. Download any application
4. Click on that application
5. Click Correct record

1. Login as Registrar
2. Go to in progress/ Ready for review
3. Download and update/ review any application
4. Click any change link

**Actual Result:**
Showing loading sign and not navigating to correct record pages/ expected declaration pages.

**Expected Result:**
should be able to view correct record pages/ expected declaration page

**Screen recording:**
https://images.zenhubusercontent.com/91778759/7311d778-dee4-43a7-8576-b16884f2d1b5/correct_record_bug.mp4

https://images.zenhubusercontent.com/91778759/f13aba3b-8a0e-40af-a166-35c9115fdd95/opencrvs_register___15_march_2022.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by yeasinhossain-dsi** [comment]
Could not reproduce it. After discussing with @SyedaAfrida  seems like this was due to browser cache
