### ISSUE TITLE
Mobile view of review page is broken

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2734]
**Bug description:**
Currently there is a right side blank space in mobile, which should not appear

**Step to reproduce:**
1. login to any user
2. download any application
3. Click review/ update 
4. Observe the review page

**Actual Result:**
![mobile view of review page.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/9506c08b-5b22-49b9-88c6-e3ac16419e32)
![mobile view of review page 2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/9591d0f4-2837-4fbb-940d-8a12a69ab6b4)

**Expected Result:**
Check from the figma link
https://www.figma.com/file/ReHllv1AX7SSq3wQ0ee6S7rj/5.-Review?node-id=112%3A0

**Tested on:**
browserstack

**Comment by anny320** [comment]
images won't show on mobile for June release. Page width to be fixed

**Comment by saima-alam** [comment]
@anny320, This is working as expected. This can be closed.

![image](https://user-images.githubusercontent.com/105625699/170468499-5f49ec9d-29a4-431a-b34f-9fdafdd08e9b.png)

**Comment by anny320** [comment]
completed
