### ISSUE TITLE
Supporting document of Proof of informant ID is not showing in Review page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2736]
**Bug Description:**
When user provide Supporting document in Proof of informant ID, it  is not showing in Review page and after it is registered it goes to outbox.

**Steps to reproduce:**
1. Login as registrar
2. Declare a death application
3. Add supporting documents in Proof of Informant's ID
4. Click Continue ad observe the supporting document section
5. Click Register and observe the application

**Actual result:**
Supporting documents not showing in review page and after it is registered the application goes to outbox

**Expected Result:**
1. Supporting document should appear in review page
2. Application should be registered properly

**Screenshot:**
![attachment error in console.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/80765b93-2a95-40c9-b8cc-4b45db9e5cdb)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by jpye-finch** [comment]
good find @SyedaAfrida !

**Comment by anny320** [comment]
tested and preview loading @SyedaAfrida https://images.zenhubusercontent.com/91778759/2d39d9a4-c9d2-4706-9094-12e0c5b07fda/screen_capture__4_.mp4

**Comment by anny320** [comment]
fixed
