### ISSUE TITLE
Console error in login page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2737]
**Bug description:**
There is one console error from log in page

**Step to reproduce:**
1.  Open https://login.farajaland-qa.opencrvs.org/
2, Observe Console

**Actual Result:**
showing console error-
companion-bubble.js:1416 Uncaught (in promise) b.AssertionError {name: 'AssertionError', actual: null, expected: true, operator: '==', message: 'Invalid pattern', …}

**Expected Result:**
should not show console error

**Screenshot:**
![console error on login page.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/f32c6abc-7806-4461-b00e-97418161f327)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by atiqzaman-dsi** [comment]
Could not reproduce it.

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

retest recording:

https://user-images.githubusercontent.com/105624748/172315689-fff8eaa2-8a99-4ec3-a6e0-1bf5b6ca99fe.mp4

**Comment by anny320** [comment]
completed

**Comment by anny320** [comment]
completed

**Comment by anny320** [comment]
completed
