### ISSUE TITLE
Form config draft setup - BE & FE Redux

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2739]
- [x] We need to amend / extend the question schema to manage a single form config draft per vital event, their associated questions and overall status of the draft ( PUBLISHED, DRAFT, PREVIEW, FINALISED) - 3
- [x] We need a GraphQL query to load drafts for all vital events from the config microservice (gateway & config handlers) - 3
- [x] We need a GraphQL mutation to save/update drafts for all vital events from the config microservice (gateway & config handlers) - 3
- [x] Drafts need to be loaded and saved in a reducer in packages/client/src/forms/configuration and we should save in IndexedDB because connectivity will be an issue for Sys Admins - 3

**Comment by SyedaAfrida** [comment]
@anny320 Form config testcases are update and have reported all the bugs separately in new tickets. So this ticket can be closed

**Comment by anny320** [comment]
closed
