### ISSUE TITLE
As a Nat Sys Admin, I can navigate to a new form configuration

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2740]
### Description

onClick of Configure. Create a new draft and nav to from configuration
menu on left etc....

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1090%3A17392

### Dev-tasks

- [x]  Create a new view FormConfigWizard using NavigationView (estimated below) as a left navigation and the header EventTopBar, and a new right hand FormTools component (estimated below) and a FormConfigCanvas central component (estimated below) - 2
- [x] NavigationView contains a PagesNavigator component.  Item 1 link, refers to [EventInfo](https://github.com/opencrvs/opencrvs-core/tree/develop/packages/client/src/views/EventInfo) and can be hardcoded in the navigation.  We do not bother showing the event selection, and Item 2 and 3 links show SelectInformant etc. For now, please ignore item 2 and 3.  Dont put them in the menu for now.  Dynamic links commence for Birth and Death based on the configurable sections in default.ts(the old register.json) which start at birth applicant and death applicant.  For now, just use the section Enum and map to the section title for the copy - 2
- [x] FormTools basic view is this (https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1094%3A26980).  Mark up the UI for this view using 2 ListView components using an optional smaller font size - 2
- [x] Create a Toggle component in the styleguide - 2
- [x] FormConfigCanvas - use Box component for now - 1
- [x] Using EventTopBar, add in the configurable draft title, create a settings button, save and publish button.  For now, settings, save and publish doesnt do anything. - 2

**Comment by euanmillar** [comment]
Soon to be blocked waiting for @sadmananik

**Comment by SyedaAfrida** [comment]
@anny320 Form config testcases are update and have reported all the bugs separately in new tickets. So this ticket can be closed

**Comment by anny320** [comment]
completed
