### ISSUE TITLE
System Crash while checking status from Performance tab

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2742]
**Bug Description:**
System Crash while checking status from Performance tab

**Steps to reproduce:**
1. Login as Registration clerk/ Registrar/ National or local System admin
2. Click Performance
3. Click Status
4. Click View all

**Actual result:**
System crash while opening Current application in workflow page

**Expected Result:**
Should view Current application in workflow page

**Screen recording:**
https://images.zenhubusercontent.com/91778759/577f78c6-331f-4193-bd3f-875a0ebeb1d4/system_crash_while_checking_status_from_performance_tab.mp4

Tested on:
https://login.farajaland-qa.opencrvs.org/

Browser:
Chrome

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![performance](https://user-images.githubusercontent.com/94350336/164444167-3b79d0c2-30ee-431a-916d-d0aac757ea6d.png)

**Comment by anny320** [comment]
completed

**Comment by anny320** [comment]
completed
