### ISSUE TITLE
Sometime death application goes to waiting for validation status

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2743]
**Bug Description:**
After an application is register by registrar, it goes to waiting for validation status and do not appear in Ready to print tab. This is an inconsistent behaviour. This bug was generated 3 times. 

**Step to reproduce:**
1. Create a death application from any user
2. Add 5 attachments

2. Login to Registrar
3. Go to ready for review
4. Click download> Review on that application
5. Click Register> Register on the modal
6. Observe the application to Ready to Print tab

**Actual Result:**
Application do not appear on ready to print tab. When the application is searched with name, The status is shown, "Waiting for BRIS"/  "waiting validation"

**Expected Result:**
The application should go to Ready for print and status should be "Validated"

**Screenshot:**
![application going to waiting for validation status.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/e70bdb99-7380-4559-a75d-c816445a5ccb)

**Comment by euanmillar** [comment]
Status should be registered.  Check waiting for external validation configuration on the death event

**Comment by Zangetsu101** [comment]
Worked with @SyedaAfrida but wasn't able to reproduce the bug.

**Comment by euanmillar** [comment]
The issue seems to be that the Farajaland repo responds with a 413 error when creating the BRN.  So the workflow service thinks it is still waiting validation

**Comment by euanmillar** [comment]
Blocked - waiting for warning design in the documents page / submission

**Comment by euanmillar** [comment]
20MB max on all collective file uploads.  @jpye-finch waiting for design

**Comment by euanmillar** [comment]
Design required: https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=5749%3A106571

**Comment by azantor64** [comment]
[See that comment](https://github.com/opencrvs/opencrvs-core/issues/3349)

**Comment by anny320** [comment]
completed
