### ISSUE TITLE
In record audit, the initial and loading state of downloading any application is not correct

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2746]
**Bug Description:**
In record audit, the initial and loading state of downloading any application is not correct. Before download, other buttons are not shown. On loading state, name field is becoming ‘No name provided’ and Status and tracking Id is becoming grayed.

**Steps to reproduce:**
1. Login as Registration clerk/ Registrar
2. Go to in progress/ Ready for review/ Sent for updates/ Ready to print
3. Click any **not** downloaded application
4. Click the download icon and observe

**Actual Result:**
Initially before download, User cannot see other buttons like- update/ review/ Archieve/ Print button
On loading state, name field is becoming ‘No name provided’ and Status and tracking Id is becoming grayed. 
After download, There is no green download icon

**Expected Result:**
Initially before download, User should see other buttons like- update/ review/ Archieve/ Print button
On loading state, name , Status and tracking Id should not change
After download, a green download icon should appear

follow the figma design:
https://www.figma.com/proto/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?page-id=0%3A1&node-id=3357%3A59461&viewport=253%2C48%2C0.25&scaling=min-zoom&starting-point-node-id=3357%3A56570&show-proto-sidebar=1

**Screen recording:** 
https://images.zenhubusercontent.com/91778759/124d5300-a7e1-402c-b949-d8c5747d7efb/audit_record_loading_state.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by Fariha-Amin** [comment]
![Capture2](https://user-images.githubusercontent.com/105624748/169831072-c3e3a23d-ada3-4323-b60a-9ca204020e7c.PNG)


@anny320 A green download icon should appear after downloading the application according to the design. Needs to be fixed again.


Figma Design:
https://www.figma.com/proto/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?page-id=0%3A1&node-id=3357%3A59461&viewport=253%2C48%2C0.25&scaling=min-zoom&starting-point-node-id=3357%3A56570&show-proto-sidebar=1

**Comment by Fariha-Amin** [comment]
@anny320  retest passed can be closed

Retest ScreenShot:
![done](https://user-images.githubusercontent.com/105624748/171155300-053f171f-ef04-4171-8a81-8b16e5d27bd7.PNG)

**Comment by anny320** [comment]
completed
