### ISSUE TITLE
Remove strove effect when you input wrong PIN 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2747]
**Bug description:**
Remove strove effect when you input wrong PIN 

**Steps to reproduce:**
1. See login page when session expires
2. Enter wrong pin and observe

**Actual result:**
There is strobe effect when loading the page

**Expected Result:**
Remove the strobe effect

**Screen recording:**
https://images.zenhubusercontent.com/91778759/ae3fb2bc-ab22-49db-8da0-2fc0b2d9d184/strobe_effect.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by anny320** [comment]
no strong effect but now looks a little odd with the red stretching across the screen @Zangetsu101 ![Screenshot 2022-08-12 at 17.28.56.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/a96f71de-edc0-445d-b0c4-0b5a85fd3b7c)

**Comment by Zangetsu101** [comment]
@anny320 Yes definitely. Someone will work on it

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![strobe effect ](https://user-images.githubusercontent.com/94350336/186358209-b0d34983-574c-4824-877a-4623d92b0383.png)

**Comment by anny320** [comment]
completed
