### ISSUE TITLE
In team, username link is only accessible from the left

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2759]
**Bug Description:**
In team, when username link is clicked from the right words, it is not accessible. Only accessible from the left.

**Steps to reproduce:**
1. login as any user other than field agent
2. Click Team
3. Click Username from the right
4. Click Username from the left

**Actual Result:**
 username link is only accessible from the left.

**Expected Result:**
Should be accessible when clicked on User name

**Screen recording:**
https://images.zenhubusercontent.com/91778759/a8c1bbb2-f3d0-4059-ac0b-8ec55f1d04cd/navigation_problem_in_team_.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by jpye-finch** [comment]
will be fixed with the new ListView component
