### ISSUE TITLE
Update Work queues for Field Agent

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2773]
### Description
- Updates GridTable component to 2 new components called WorkQueueDesktop & WorkQueueMobile
- WorkQueueDesktop is a variation on TableView and ListView, WorkQueueMobile is altogether different
- User can sort each row to change the order on WorkQueueDesktop
- [Columns for each table on WorkQueueDesktop are listed here ](https://www.notion.so/opencrvs/Work-queues-4c5690b03e78425e89c4cda193b8cee7?showMoveTo=true)
- There are no columns on WorkQueueMobile
- [Updates empty states on DEsktop](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3950%3A87941)
- [Updates emoty states on Mobile](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3873%3A89918)
- [Mobile design](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3873%3A87471)
### Acceptance criteria

GIVEN
WHEN
THEN

### Design

- [Field Agents specific work queues ](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3821%3A87284)

### Dev-tasks??

- [x] Merge FieldAgentHome into OfficeHome - Remove FieldAgentHome > InProgress,  and move this from FieldAgentHome > SentForReview to OfficeHome > SentForReview - 3
- [x] Update OfficeHome to use Content (large) component wrapper - 2

### Desktop

- [x] Update GridTable to have sortable headers copied from TableView - 3
- [x] Convert GridTable into 2 components WorkQueueDesktop & WorkQueueMobile.  Update the rows in WorkQueueDesktop to suit desktop design - 3

### Mobile

- [x] Update the rows in WorkQueueMobile and dont use Content, move all logic into shared utils.ts that WorkQueueDesktop & WorkQueueMobile use. - 3
- [x] Update the design for no records found WorkQueueDesktop: https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3950%3A87941. and WorkQueueMobile: https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3873%3A89918. @jpye-finch to share copy - 2
- [x] Move onto this ticket and update iconography:  https://github.com/opencrvs/opencrvs-core/issues/2802 
- [ ] Replace "Show more" in the WorkQueueDesktop & WorkQueueMobile with Pagination and update any queries - 3

**Comment by SyedaAfrida** [comment]
@anny320 testcases for these tickets were updated

**Comment by anny320** [comment]
completed
