### ISSUE TITLE
BE - Create and Update Custom Question amends for localisation

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2774]
Update the config microservice "question" schema:

- [x] label and placeholder should not be message descriptors and instead an array like this:

`
[
    {
      "lang": "en",
      "descriptor":  {
            "defaultMessage": 'Shoe size of child',
            "description": 'Custom description for: fieldName',
            "id": 'form.field.label.fieldName'
      },
     {
      "lang": "fr",
      "descriptor":  {
            "defaultMessage": 'Shoe size of child',
            "description": 'Custom description for: fieldName',
            "id": 'form.field.label.fieldName'
      }
]

`

Add similar arrays in the schema for:

description
tooltip
errorMessage

In the gateway, amend the getQuestions resolver and schema to return the message descriptor arrays. - 2
- [x] In the client, in the createCustomField method, we need to select the default language and populate the label, placeholder, description & tooltip appropriately.  https://github.com/opencrvs/opencrvs-core/blob/8ac83fffe5cbbd270686d2d2656336e1b87b71ee/packages/client/src/forms/configuration/customUtils.ts#L77 - 2
- [x] In offline reducer, after the content is loaded:  https://github.com/opencrvs/opencrvs-core/blob/8ac83fffe5cbbd270686d2d2656336e1b87b71ee/packages/client/src/offline/reducer.ts#L344, get all the available content keys for custom questions for both languages from the "formConfig" state and push into the offlineData "languages" object in the right language array to ensure that they custom question translations can render in multiple languages. - 2

**Comment by SyedaAfrida** [comment]
@anny320 Form config testcases are update and have reported all the bugs separately in new tickets. So this ticket can be closed

**Comment by anny320** [comment]
closed
