### ISSUE TITLE
Update work queues for registration agents and registrars

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2775]
### Description

- Updates GridTable component to new component called WorkQueue
- WorkQueue is a variation on TableView and ListView
- User can sort each row to change the order
- [Columns for each table are listed here ](https://www.notion.so/opencrvs/Work-queues-4c5690b03e78425e89c4cda193b8cee7?showMoveTo=true)
- [Updates empty states](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3950%3A87941)
- [Copy for empty states ](https://opencrvs.notion.site/Work-queues-4c5690b03e78425e89c4cda193b8cee7)
- [Field Agents specific work queues ](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3821%3A87284)
- [Mobile design](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3873%3A87471)

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3516%3A78215

https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3871%3A86591
- [x] Rename: InProgress (rename from InProgressTab) to use Content component refactor the buttons into Tabs - 2
- [x] Update columns in WorkQueueDesktop so they are all the same and the "Sent for" label changes to to suit all the different pages - 2

SentForApproval
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3821%3A92330

ReadyToPrint
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3821%3A90689

RequiresUpdates
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3821%3A91623

ReadyForReview
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3516%3A78215

InExternalValidation
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3821%3A92953

- [x] Rename: SentForApproval (rename from approvalTab) to use Content component
Rename: ReadyToPrint (rename from printTab) to use Content component
Rename: RequiresUpdates (rename from rejectTab) to use Content component and anywhere ie for field agent where it says "Sent for updates" it should say "Requires updates"
Rename: ReadyForReview (rename from reviewTab) to use Content component
Rename: InExternalValidation (rename from externalValidationTab) to use Content component - 2

SearchResult
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4117%3A98518
- [ ] Update SearchResult  to use either WorkQueueDesktop or WorkQueueMobile components and for search results do not use the "Sent for" column.  Update the loader. - 2

**Comment by euanmillar** [comment]
Blocked by: View this issue on GitHub

**Comment by SyedaAfrida** [comment]
@anny320 The testcases for workqueue are updated for registration agent and registrar. so this ticket can be closed

**Comment by anny320** [comment]
completed
