### ISSUE TITLE
Update the design for the application loading screen

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2776]
Currently when the application is loading, all you see is a white screen and a blue loader.

- [ ] Lets update the white screen to show this design:

https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3766%3A85923

With the text hardcoded to english

Must show for a minimum of 3 seconds.

**Comment by SyedaAfrida** [comment]
**Bug:**
1. The font style of "Loading your workspace" gets changed at the time of loading
2. After loading no records can be seen unless clicked on any side menu

https://user-images.githubusercontent.com/94350336/165042848-11c9e7d6-f4a0-4cb5-8bfb-19d3f05be72a.mp4

**Comment by anny320** [comment]
this duplicate ticket will be closed in favour of #2906
