### ISSUE TITLE
Field Agent cant get updated record audit after downloading

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2786]
As a field agent, every downloaded application needs a way for it to be removed from cache.  So that the field agent can get up to date audit history.

**Automatic removal after 24 hours:**

- [ ] IUserData.delarations would have to change to something like this: IDowloadedDeclaration[] where IDownloadedDeclaration is:

```
interface IDownloadedDeclaration {
 declaration: IDeclaration
 downloaded: Date
}
```

- [ ] For a Field Agent only, on every page load, if userDetails.declarations has a length, we must loop through IDownloadedDeclaration[] and if todays date is more than 24 hours after  IDownloadedDeclaration.downloaded date, then remove that declaration from downloaded state and ensure that the downloaded button was enabled again.

**Comment by SyedaAfrida** [comment]
@anny320 this issue is not fixed. Any application downloaded by field agent gets removed before 24hrs
![ask](https://user-images.githubusercontent.com/94350336/174792893-4e999767-0373-4413-a663-3a31110d715d.png)

**Comment by euanmillar** [comment]
@atiqzaman-dsi @SyedaAfrida is going to recheck.  It could be that she checked just after 24 hours and the created time displayed is rounded down.  I think that the solution could be to just increase the time to 26 hours to allow for this possibility, so 1560 minutes.

**Comment by euanmillar** [comment]
We decided to increase this limit to 25 hours just to avoid user confusion.  It makes no difference to the desired functionality

**Comment by SyedaAfrida** [comment]
@anny320 This is fixed and can be closed

**Comment by anny320** [comment]
completed
