### ISSUE TITLE
Certificate preview data and handlebar amends

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2787]
- [x] Previewing a configured certificate by a natsysadmin must only use mock offline data so that we dont affect real certificates by any mapping amend place of birth fallback to suit preview, and also so that any changes to location ids dont affect preview.

- [x] Custom field handlebars must have a basic template mapping to return the value.  https://github.com/opencrvs/opencrvs-core/blob/51e4f62cdae82612a93a2d864e72360d4f2730c9/packages/client/src/forms/configuration/customUtils.ts#L88

- [x] Shortlisted default fields need a similar, template mapping https://www.notion.so/opencrvs/Certificate-Configuration-ae1270a42cfd46a58fd6fecb5aece77d

Custom fields do not have a handlebar

**Comment by SyedaAfrida** [comment]
@anny320 this seems like a technical issue. Nothing to be QAed

**Comment by anny320** [comment]
completed
