### ISSUE TITLE
All users does not work offline

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2790]
**Bug description:**
Field agent does not work offline after you refresh it.

**Steps to reproduce:**
1. Log in as an Field Agent
2. Turn off your mobile data to go offline
3. Refresh the page.  

**Actual Result:**
You see a white screen and then the app is unusable

**Expected Result:**
Should work even after refresh

**Screenshot:**
![Screenshot_20220323-152407 - Euan Millar.jpg](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/86a183c4-ce1b-497a-b549-99fa73f05091)

**Tested on:** 
https://login.farajaland-qa.opencrvs.org/
**Device:** mobile

**Comment by anny320** [comment]
@euanmillar to discuss what offline capabilities are covered

**Comment by euanmillar** [comment]
This error occurs because we do not handle the failed request to config microservice gracefully by falling back to use the IndexedDB config

**Comment by Fariha-Amin** [comment]
@anny320  Passed and can be closed

**Comment by anny320** [comment]
completed
