### ISSUE TITLE
Cannot create a field agent, registrar & system admins in different locations

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2791]
**Bug description:**
Cannot create a field agent, registrar, System admin (local/ national) user type in different locations 

**Steps to reproduce:**
1. Login as national system admin
2. Go to team
3. For any location (which has registrar) Click new user
4. Observe Role drop down

1. Login as national system admin
2. Go to team
3. Click any new location
4. Try to create system admin/ registrar

**Actual Result:**
1. Do not show Field agent option
2. When try to create registrar, shows error 'Sorry, Something went wrong'
5. When try to login with username & password of local/ national system admin, the system keeps on loading

**Expected Result:**
1. Should have field agent option in Role and CHA/ Hospital in Type
2. should be able to create registrar
3. should be able to create local/national system admin

**Screenshot:**
![Screenshot 2022-03-23 at 14.32.23 - Riku Rouvila.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/b8183195-e17e-431c-9cab-853e1b800ca7)

![reg err](https://user-images.githubusercontent.com/94350336/162704126-4c485018-2494-41d4-a7f1-473ee96f580c.png)

**Tested on:**
https://register.farajaland-qa.opencrvs.org/

**Device:**
desktop

**Comment by saima-alam** [comment]
Newly created Local system admin and National system admin can not log in if there is no register created in the same location.
Reference video of the issue: https://www.screencast.com/t/L9y0pWK1du

**Comment by SyedaAfrida** [comment]
@anny320 This bug is fixed and can be closed. 
1. Able to create and edit field agent in new location
![fa in new location](https://user-images.githubusercontent.com/94350336/170930076-72d8c44a-c2e2-4de8-a18b-baf9a0f41e86.png)
2. Able to create and edit registrar in new location
![reg in new location](https://user-images.githubusercontent.com/94350336/170930191-e9765b7a-e048-40d0-a6d5-5cc4ec15d2f7.png)
3. Able to login with a local/ national system admin created in a new location
![sys ad](https://user-images.githubusercontent.com/94350336/170930413-681f11d5-a52c-4222-8a00-59af838e87c7.png)

**Comment by anny320** [comment]
completed
