### ISSUE TITLE
Remove Performance Operational Roles

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2793]
**Bug Description:**
Role types: Performance Oversight is not active roles in the system and need to be removed

**Steps to reproduce:**
1. Login as local/ national system admin
2. Go to team
3. Click new user
4. Observe Role drop down

**Actual result:**
Shows Performance Oversight 

**Expected Result:**
should not show Performance Oversight

**Screenshot:**
![per mang_ oversight.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/dcfba7dd-a34f-403b-83c5-464af9d69505)

**Tested on:**
https://register.farajaland-qa.opencrvs.org/

**Device:**
Desktop

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![remove oversight](https://user-images.githubusercontent.com/94350336/164461758-59442106-d8c2-4610-8b54-28e3440ae20b.png)

**Comment by anny320** [comment]
completed
