### ISSUE TITLE
As a user when logged in for the first time, lose the new and confirmed password I have entered if I navigate back from the security questions page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2794]
**Bug Description:**
As a user who is logging in for the first time, I lose the new and confirmed password I have entered if I navigate back from the security questions page

**Steps to reproduce:**
1. Login for first time
2. Enter new password and confirm it
3. Navigate to next page (security questions)
4. Select back 

**Actual Result:**
1. new password and confirmed password is gone, 
2. do not show Error message when clicked Continue even if do not match password requirements

**Expected Result:**
1. Should keep the password
2. Should show error message when do not match password requirements and clicked continue

**Screenshot:**
![Bug 1 - Annina Wersun.JPG](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/4c859067-e3cb-4fec-8592-b2299a917bd3)

![Screenshot 2022-04-01 151317.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/af3cc6e4-de72-4a4c-a0a2-dbe2c6c69146)

**Tested on:**
https://register.farajaland-qa.opencrvs.org/

**Comment by jpye-finch** [comment]
think its fine to loose password on navigation back.

Continue should be disabled until an accepted password is entered.
