### ISSUE TITLE
As a Local or National System Admin I want to view my assigned office by default

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#2796]
### Description
- defaults the Team page for a Local or National System Admin to their assigned office
- so removes the page which just has the Search on it
- a Local or National System Admin can then search for an office 

### Acceptance Criteria

GIVEN I am a Local or National System Admin
WHEN i click on Team
THEN show my assigned office team 

GIVEN I am on my Team page
WHEN I click the office search
THEN show the office search model

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4287%3A111369

**Comment by jpye-finch** [comment]
@azantor64 @euanmillar this page won't be needed when we make updates to the Performance and Team page. As the locations select is on the page 
<img width="746" alt="image" src="https://user-images.githubusercontent.com/46478402/161268175-57679078-d9bc-4ede-9e6b-461bb0a75a27.png">

**Comment by euanmillar** [comment]
@jpye-finch we still have this Team search flow.  What should we do?

**Comment by jpye-finch** [comment]
we should default their assigned office

**Comment by SyedaAfrida** [comment]
**Bug:** 
System crash occurs after clicking create new user icon from team page or try to edit user from team page
![sys crash](https://user-images.githubusercontent.com/94350336/193219860-31c2948c-7c5e-4f83-954a-8de6a588c2f9.png)

**Comment by SyedaAfrida** [comment]
@anny320 This ticket is fixed and can be closed
![fixed](https://user-images.githubusercontent.com/94350336/194508539-c3cd482e-685c-468d-86e5-5b9e44925a8c.png)

**Comment by anny320** [comment]
completed
