### ISSUE TITLE
After clicking any office it should show user lists but it takes time and shows no user lists

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#2797]
steps: 
1. log in as Sys admin
2. make your network slow a little bit
3. Search Ibombo office

https://www.loom.com/share/25882c44fb4c4b67816039b3567872b3

**Comment by jpye-finch** [comment]
Need to add loading state
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3219%3A54936
