### ISSUE TITLE
Icon changes

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2802]
### Description

- [Status icons (left WorkqueueRow icon](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=3044%3A0) 
- [Workqueue action icons ](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=3051%3A373)
- Show error toast when error on downloading declaration
- Updates error state for a downloaded declaration

### Acceptance criteria

GIVEN I download a declaration
WHEN there is an error
THEN show a toast message with error
THEN turn the download button red

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3516%3A78215

Prototype: https://www.figma.com/proto/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?page-id=6%3A595&node-id=4149%3A87221&viewport=290%2C48%2C0.25&scaling=min-zoom&starting-point-node-id=4149%3A87221

### Copy
'Failed to download declaration. Please try again'

### Dev-tasks
- [x] Update icons: 

- [Status icons (left WorkqueueRow icon](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=3044%3A0) 
- [Workqueue action icons ](https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=3051%3A373)

- [x]  Update location and logic for iconography in the flow for download in the work queues

**Comment by jpye-finch** [comment]
@emon-swe-sust. let me know if you have any questions on this. Can jump on a call to discuss

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**retest ss:**
![dd](https://user-images.githubusercontent.com/105624748/172119251-8cab6043-5919-4e49-a9b0-8f89fe22aba9.png)

**Comment by anny320** [comment]
completed
