### ISSUE TITLE
In System admin team view user's pending,deactivate,active options 3 dot's aren't aligned in straight line order

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#2804]
After deactivating an user or pending option three dot goes out of the box.For that 3 dot can't aligned in a straight line comparing with action's 3 dot.

**To Reproduce**

1.  Log in as 'Local/System admin'
2.  Click on 'Team'
3.  Search Ibombo district
4.  click any user's 3 dot 
5.  Deactivate an user 
6. Click on Resend SMS invite
7.  See the error

**Expected behaviour**
3 dots (of Pending,Deactivated,action) all should be aligned within a column straight line

**Screenshots**
![line.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/6e5d064c-e2dd-4ce4-ba74-629994be32ce)

Right Side view: 
![Selection_023.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/eef5d05f-58ef-4623-965d-19f3234f5a65)

**Desktop:**
 - OS: Ubuntu
 - Browser: Chrome

**Comment by jpye-finch** [comment]
this will be fixed when ListView Simplified is applied
