### ISSUE TITLE
System Crash when health institution set null and tried to navigate to record audit page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2812]
**Bug description:**
From an in progress application, set health institution null and click  save & exit. System crash when tried to view record audit page.

**Steps to reproduce:**
1. Login as registration agent
2. Create a draft application where "Place of delivery" is set as Private home/ Other
3.  Click save & exit
4.  Click update button of that application
5.  Click Change in place of delivery
6. Change location to health institution & **do not** select any thing from health institution drop down
7. Click save & exit
8. Click on the application to open record audit page

**Actual Result:**
System crash instead of navigating to record audit page

**Expected result:**
should be able to navigate to record audit page

**Console:**
breadcrumbs.ts:103 TypeError: Cannot read properties of undefined (reading 'split')
    at rg (utils.ts:216:55)
    at Fg (utils.ts:355:19)
    at DE (RecordAudit.tsx:637:11)
    at RecordAudit.tsx:677:23
    at Qa (react-dom.production.min.js:153:146)
    at Ss (react-dom.production.min.js:261:496)
    at vu (react-dom.production.min.js:246:265)
    at mu (react-dom.production.min.js:246:194)
    at su (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
(anonymous) @ breadcrumbs.ts:103
overrideMethod @ react_devtools_backend.js:4026
is @ react-dom.production.min.js:209
a.componentDidCatch.r.callback @ react-dom.production.min.js:227
ma @ react-dom.production.min.js:131
cs @ react-dom.production.min.js:212
_u @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
wu @ react-dom.production.min.js:248
su @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Xi @ react-dom.production.min.js:122
N @ react-dom.production.min.js:287
Zt @ react-dom.production.min.js:68
n @ helpers.ts:77

**Screen recording:**
https://images.zenhubusercontent.com/91778759/a5d8b9b7-53b4-440e-afb6-0509c708d12f/system_crash_when_try_to_update_an_incomplete_application.mp4

**Tested on:**
https://register.farajaland-qa.opencrvs.org/

**Comment by soumita-dsi** [comment]
This bug should be fixed in ticket #2792

**Comment by SyedaAfrida** [comment]
@anny320 this bug has passed and can be closed

**Comment by anny320** [comment]
closed
