### ISSUE TITLE
Research if we need to have a migration plan from React class components to function components

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#2815]

**Comment by Zangetsu101** [comment]
react-apollo will need to be upgraded in case we migrate to function components #3009

**Comment by euanmillar** [comment]
@Zangetsu101 can we upgrade react-apollo after Vite migration?

**Comment by Zangetsu101** [comment]
Yeah we should add this to our pipeline after vite

**Comment by euanmillar** [comment]
Closing this as the dependency upgrade of react-apollo will be included in a new ticket
