### ISSUE TITLE
As a user I want to search for a location, so that I can see performance data [3]

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2820]
### Description
- Move location search into Performance page
- Defaults locations: National Reg = Farajaland Reg Agent/Reg = Their Office (as we do today)
- Search is same experience as: ![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/0026a348-4d09-49e3-adad-c81464aab435)

### Acceptance criteria

GIVEN I am on the Performance page
WHEN I click on the Location filter
THEN Show the location search

GIVEN I search for a new location
WHEN I select the new location
THEN load and display the data for my chosen location

### Design
..

### Dev-tasks

- [ ]  Replacing the logic of location search on PerformanceHome with a LocationPicker

**Comment by anny320** [comment]
completed
