### ISSUE TITLE
As a user I want to view performance data for different events

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2821]
### Description

- adds event filter to Performance Dashboard

### Acceptance criteria

GIVEN I am on the Performance Dashboard
WHEN I click on the event filter
THEN show a select with available event

GIVEN I select a different event
THEN load and display performance data for my chosen filters

### Design
(Link to Figma)

### Dev-tasks

- [ ]  Update all relevant queries, by event selection

**Comment by anny320** [comment]
completed
