### ISSUE TITLE
As a user I want to view Stats for my selected location

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2822]
### Description

- Adds Stats to Performance Dashboard
- Show number of Offices
- Shows No of Registrars. 
- Shows number of Registrars to population of my chosen administrative area.
- Does not show on Office Performance Dashboard

### Acceptance criteria

GIVEN I am on the Performance Dashboard
THEN show the Stats

GIVEN I change location
THEN update the stats to reflect my chosen administrative area

GIVEN I on an Office Performance Dashboard
THEN don't show the Stats

### Design
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/379620ee-75e8-4d64-8339-7e09eb47fbad)

### Dev-tasks

- [x]  We need a gateway resolver and client query to get all offices in a location from metrics where location type is a CRVS_OFFICE and partOf is Location/id-of-location.  
- [x] In metrics create a handler for this which contacts hearth and returns associated office numbers, total population, number of Registrar type practitioners in the location. If location is a CRVS_OFFICE, no need to return population, just number of registrars in the single office
- [x] In client call the query with the selected locatiion and display results

**Comment by SyedaAfrida** [comment]
@anny320 review the testcase of performance and this ticket can be closed.

**Comment by anny320** [comment]
completed
