### ISSUE TITLE
As a user I want to see Completeness Rates [2] - Front End

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2823]
### Description

- Add ListView of Completeness rates
- Within legally stipulated period. Label updates to reflect what was set in App Config
- Within 1 year and 5 years (1 year and 5 years is hardcoded)- note this has nothing to with the certificate fees dates
- Desegregation by sex
- When I click 'View' navigate to graph detail page (line graph and table)
- onHover of % we show a tool tip with the nominator and denominator eg. '98,000 out of an  estimated 100,000 births'

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4262%3A100815

#### Initial component setup

- [x]  Content component needs to be modified to accept buttons where the tabs go.  Specifically the location button and the time select button that we see in Registration Rates.  Use the over time select for the birth / death event select

![Screenshot 2022-04-13 at 11.23.47.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/4bde0e36-87b9-4563-8c09-f99907f7de80)

Update the font style and colors of the buttons 

- [x] Delete the existing PerformanceHome as Location search is now handled by the location search button.  Rename OperationalReport to PerformanceHome and put the operational>RegistrationRatesReport and  operational>DeclaratonsStartedReport inside a the Content component

- [x] Make 2 columns in the new PerformanceHome and position a Box component at the top with another underneath to contain the status content

- [ ] Delete DeclarationStatusWindow component.  Move the Query and the DeclarationStatusWiseCount component inside the bottom box

- [x] Rename RegistrationRatesReport to CompletenessRates and layout the Birth data into a single row of a ListView

- [x] Build the logic for the event select in PerformanceHome, passes event as a prop to CompletenessRates.  When death is selected hide the birth row and show the death row.

- [x] From the updated query https://github.com/opencrvs/opencrvs-core/issues/2884 retrieve and split events appropriately in 2 additional rows in ListView for birth1YearMetrics, death1YearMetrics, birth5YearMetrics, death5YearMetrics

**Comment by SyedaAfrida** [comment]
@anny320 review the testcase of performance and this ticket can be closed.

**Comment by anny320** [comment]
completed
