### ISSUE TITLE
As a user I want to see Registration rates [4]

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2824]
### Description

- Adds ListView of registration rates
- Total, Late, Delayed  (time period based on App config)
- Adds Home / Health split. 

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/3c45777d-d6e2-4f4b-a359-4d694dbcdcca)
(Link to Figma)

### Dev-tasks

- [x]  Populate the data from the fetchRegistrationMetrics query into a List View component

**Comment by SyedaAfrida** [comment]
@anny320 review the testcase of performance and this ticket can be closed.
