### ISSUE TITLE
As a user I want to see the sources of declarations [6]

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2826]
### Description

- Reorganises current performance data into ListView
- Split Registration Office into Registration Agent and Registrars
- Adds National Registrar
- If no Health System Integration that don't show ListItem 
- On Field Agent 'View' navigate to Field Agent Table 

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/d068e256-79b6-42d0-9a55-d8de258c1852)

### Dev-tasks

- [ ] Using ListViewSimplified, layout the table.  Build on top of Tahmid's branch
- [x] Blocked - BE.

**Comment by euanmillar** [comment]
Source of declaration needs a change to the pointGenerator for birth/death registration

**Comment by SyedaAfrida** [comment]
@anny320 review the testcase of performance and this ticket can be closed.

**Comment by anny320** [comment]
completed
