### ISSUE TITLE
As a user I want to see performance data on the Corrections

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2827]
### Description

- Add ListView of Corrections
- Total, and total by reason

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/a019e400-1dd1-4c97-a508-c75ad00dd376)

### Dev-tasks

- [ ] Using ListViewSimplified, layout the table. Build on top of Tahmid's branch
- [ ]  In metrics, store reason for correction parameter, return it in a new handler or edit an existing handler

**Comment by anny320** [comment]
completed
