### ISSUE TITLE
As a user I want to see the amount of Fees collected

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2828]
### Description

- As ListView of the Fees collected
- Total, Certificate fees, Correction fees

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/c57f5d83-9cb7-4446-8875-58a1f7787468)

### Dev-tasks

- [x] Using ListViewSimplified, layout the table.  Build on top of Tahmid's branch
- [ ] Blocked - BE awaiting the correction fee in the certificate fees response from existing query that is used in the legacy reports section

**Comment by SyedaAfrida** [comment]
@anny320 review the testcase of performance and this ticket can be closed.

**Comment by anny320** [comment]
completed
