### ISSUE TITLE
Performance: Average time spent in workqueue/status

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2829]
### Description

- Adds 'Avg. time in respective workqueue

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/24a0cf65-df86-42da-b4d7-715bc7e7744b)

### Dev-tasks

- [ ]  Task 1

**Comment by euanmillar** [comment]
@jpye-finch @anny320 we estimated that calculating average time for all applications in the workqueues at a National level will be extremely difficult and take perhaps as much time as the entire Performance feature.  We need to refactor the whole back end to support this kind of metrics into scheduled tasks

**Comment by euanmillar** [comment]
We could work on this, but it is quite a bit of work. I think we should hold off until we prioritise alongside other v1.0.2 and v2 features

**Comment by euanmillar** [comment]
Closing as we are deprecating this view
