### ISSUE TITLE
Update Status panel for selected event

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2830]
### Description

- Status panel must only show data from the event selected
- links to Status table only on Office Performance Level page
- **no** links on National, Province and district performance pages

### Design
![Screenshot 2022-04-21 at 10.56.37.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/9d1a1d99-c0da-409e-95ef-99ab11ffe286)

### Dev-tasks

- [ ]  Update queries and search handlers to reflect showing search results only from the event selected

**Comment by euanmillar** [comment]
Closing as a duplicate

**Comment by euanmillar** [comment]
Changed description to use this ticket for the event stats

**Comment by SyedaAfrida** [comment]
@anny320 review the testcase of performance and this ticket can be closed.

**Comment by anny320** [comment]
completed
