### ISSUE TITLE
As a user I want to see the Performance page Load [1]

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2831]
### Description
- as spinner to Content component and Performance Card
- on fail to load data. Show error and refresh link. 

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4268%3A104823

### Dev-tasks

- [ ]  While queries are loading show the blue loader for completeness rates and status component

**Comment by SyedaAfrida** [comment]
@anny320 review the testcase of performance and this ticket can be closed.

**Comment by anny320** [comment]
completed
