### ISSUE TITLE
No history on Record Audit for inprogress declarations

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2833]
**Describe the bug**

- No case history for in progress declarations

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new declaration
2. Save it
3. Go to Record Audit
4. Note: History is greyed

**Expected behaviour**
You can see case history. eg. Start on. Updated. etc...
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=1810%3A33851

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/18a97fbd-e4c4-4315-ba57-d8e22342e6f7)

**Additional context**
Audit table: https://www.notion.so/opencrvs/Audit-5ea0204d2b6c40858e772028784db864

**Comment by euanmillar** [comment]
When working on a draft, then ensure that there is a row inserted using the date and information you have in IndexedDB

**Comment by azantor64** [comment]
Can see history. This can be closed. @anny320 
![image](https://user-images.githubusercontent.com/70468099/170662175-9cdfc3e7-c093-4ace-90d3-d2c0d9af0495.png)

**Comment by anny320** [comment]
completed
