### ISSUE TITLE
Unable to download or navigate to Record audit page of a record which is corrected and update status for corrected record

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2834]
**Bug description:**
Unable to download or navigate to Record audit page of a record which is corrected

**Steps to reproduce:**
1. login as registrar
2. go to ready to print
3. make correction of any record
4. Search for that record with name/ tracking id
5. Click on the work queue/ click download

**Actual result:**
1. Do not view audit record page. navigate back to first page (ready for review)
2. When a record is in ready to print and I correct a record, it no longer appears in ready to print work queue

**Expected result:**
1. Should be able to view record audit page
3. When a record is in ready to print and I correct a record, Then the status should still be Registered. So should remain in Ready to Print. 
4. If the record status is Certified ( a certificate has been printed), hen If I correct the record. It’s status should remain Certified
5. In both cases  a history line item should  show "Record corrected "
6. The corrected data should reflect in record audit page
7. [OnClick of Record corrected.](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=1%3A3541) The model should show the Reason, ID Check (yes/no), documents, the change (original and edit) and any comments. 

**Notion link:**
https://www.notion.so/opencrvs/Record-Audit-5ea0204d2b6c40858e772028784db864

**Screen recording:**

https://images.zenhubusercontent.com/91778759/2e41a9fe-9cd2-4fbf-993b-0bf111ac877f/loom___free_screen___video_recording_software___7_april_2022.mp4

**Console error:**
(when tried to download)
invariant.ts:13 Uncaught Invariant Violation: Invariant Violation: 12 (see https://github.com/apollographql/invariant-packages)
    at new t (https://register.farajaland-qa.opencrvs.org/static/js/2.acffcc56.chunk.js:2:173598)
    at u (https://register.farajaland-qa.opencrvs.org/static/js/2.acffcc56.chunk.js:2:173828)
    at e.query (https://register.farajaland-qa.opencrvs.org/static/js/2.acffcc56.chunk.js:2:857389)
    at e.query (https://register.farajaland-qa.opencrvs.org/static/js/2.acffcc56.chunk.js:2:869721)
    at nd (https://register.farajaland-qa.opencrvs.org/static/js/main.bccad89a.chunk.js:1:655656)
    at https://register.farajaland-qa.opencrvs.org/static/js/2.acffcc56.chunk.js:2:123869
    at Array.reduce (<anonymous>)
    at Y (https://register.farajaland-qa.opencrvs.org/static/js/2.acffcc56.chunk.js:2:123781)
    at https://register.farajaland-qa.opencrvs.org/static/js/2.acffcc56.chunk.js:2:124338
    at https://register.farajaland-qa.opencrvs.org/static/js/2.acffcc56.chunk.js:2:122196
t @ invariant.ts:13
u @ invariant.ts:24
e.query @ QueryManager.ts:751
e.query @ ApolloClient.ts:328
nd @ index.ts:1499
(anonymous) @ merge-child-reducers.js:37
Y @ merge-child-reducers.js:24
(anonymous) @ combine-reducers.js:11
(anonymous) @ install.js:36
v @ redux.js:288
(anonymous) @ index.umd.js:101
(anonymous) @ middleware.js:26
h @ install.js:93
r.<computed> @ bindActionCreators.js:9
a @ DownloadButton.tsx:79
onClick @ DownloadButton.tsx:119
s @ react-dom.production.min.js:14
d @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
v @ react-dom.production.min.js:15
st @ react-dom.production.min.js:52
at @ react-dom.production.min.js:51
ut @ react-dom.production.min.js:52
pt @ react-dom.production.min.js:56
D @ react-dom.production.min.js:287
z @ react-dom.production.min.js:19
$t @ react-dom.production.min.js:70
Jt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
N @ react-dom.production.min.js:287
Zt @ react-dom.production.min.js:68
n @ helpers.ts:77
Show 3 more frames

**Tested on:**
https://register.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by jpye-finch** [comment]
@SyedaAfrida looks good!
Just added a comment on what to expect in the model for 'Record corrected'

**Comment by Zangetsu101** [comment]
The part about navigating to the home page instead of `RecordAudit` is the only thing that can be considered a bug in here. The other parts are because the requirements were changed after the feature `Correction` was merged in so those should be moved into a separate ticket @jpye-finch @SyedaAfrida

**Comment by SyedaAfrida** [comment]
From expected result only number 1 is fixed. Need to fix 2-6. Since all the mentioned issues are for correction record, not making another separate ticket

**Comment by SyedaAfrida** [comment]
@anny320 number 6 of expected result is failing. Created new ticket for that- https://github.com/opencrvs/opencrvs-core/issues/3295

**Comment by anny320** [comment]
completed
