### ISSUE TITLE
Showing 'Bengali name' column in Current declarations in workflow page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2835]
**Bug description:**
Showing 'Bengali name' column in Current declarations in workflow page after having multiple language support

**Step to reproduce:**
1. login as any user except Field agent
2. Click Performance 
3. Click Status
4. Click View all

**Actual Result:**
Showing bengali name column in table

**Expected result:**
Should not show bengali name

**Screenshot:**
![bengali name column.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/a2564d4d-bacd-4197-b814-6d3325107777)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by jpye-finch** [comment]
has been raised to be fixed as part of Performance Update tickets

**Comment by SyedaAfrida** [comment]
@jpye-finch Is this also reported? Bengali name appearing in when try to login with new user.
![bengali name login](https://user-images.githubusercontent.com/94350336/162146735-5ea34608-8860-4547-9a9d-5c498e1ef9e6.png)

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/171602456-ef169645-fb98-4a0e-bab6-c7ce57ba90eb.png)
Passed . can be closed. @anny320

**Comment by anny320** [comment]
completed
