### ISSUE TITLE
As a Registrar I want to see the Status of records

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2836]
### Description

- moves current Status of records table into the Content component
- so it's not full screen
- removes Time in BRIS
- Renames English name to Name
- Removes Bengali column
- [updates table column copy ](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4287%3A109512)
- removes 2nd language name

- only links available on an Office Performance Dashboard page

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/1a1932c4-2104-4d78-90bf-b39c88483d7b)

https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3319%3A57256

### Dev-tasks

- [ ] Move the view into a Content component, and control the appearance of the Time in BRIS column by the value of EXTERNAL_VALIDATION_WORKQUEUE.  Change the copy of Time in BRIS to "Time in external validation"

**Comment by euanmillar** [comment]
Unfortunately the time select will not work on this page because of an existing back end bug. Time period is not recognised at all on this page at the moment

**Comment by SyedaAfrida** [comment]
@anny320 review the testcase of performance and this ticket can be closed.

**Comment by anny320** [comment]
completed
