### ISSUE TITLE
Validation message for invalid phone number is broken

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2837]
**Bug description:**
Validation message for invalid phone number is broken

**Step to reproduce:**
1. Login as any user except local/ national system admin
2. Declare a birth/ death application
3. Input invalid phone number in main point of contact page

**Actual result:**
Broken Error message showing- Must be a valid {num} digit number that starts with {start}

**Expected result:**
"Must be a valid 11 digit number that starts with "079"

**Screenshot:**
![validation message.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/2f763278-2862-4ff0-a6b7-73a7822fa6d1)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by anny320** [comment]
issue resolved, ticket will be closed
