### ISSUE TITLE
As a user I want to see the performance of FieldAgents

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2838]
### Description

- moves current field agents performance table into page
- accessible from View in 'Source of declarations'

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3320%3A78071

### Dev-tasks

- [x]  Move the view into a Content component

**Comment by euanmillar** [comment]
@jpye-finch there is no description on what the 3 dot menu is meant to be used for in the top right of this image

**Comment by jpye-finch** [comment]
removed image and link to design that doesn't have three dots

**Comment by anny320** [comment]
completed
