### ISSUE TITLE
Default views of performance management for different users [2]

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2839]
### Description

- set the default view for different users
- set the available administrative areas a user can view Performance Data for. 
- restrict areas by not showing results for restrictive admin areas. 

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
https://www.notion.so/opencrvs/Default-views-of-performance-management-for-different-users-ec2735c981ef4b4995a00e2e1d3ccc71

### Dev-tasks

- [x]  Ensure that the default PerformanceHome location is the personal office for the Registrar, Registration Agent & Local System Administrator

**Comment by euanmillar** [comment]
@anny320 @jpye-finch The Office level default for Registrar shows no completeness rates, are you sure their default should be Office?

**Comment by euanmillar** [comment]
Blocked until this completed: https://github.com/opencrvs/opencrvs-core/issues/2844
and the new user types:

**Comment by Fariha-Amin** [comment]
@anny320  solved, can be closed

![d](https://user-images.githubusercontent.com/105624748/171806310-efcd3efe-b247-4b4a-a416-50b64f56064f.PNG)

**Comment by anny320** [comment]
completed
