### ISSUE TITLE
In Progress record form Field Agent Icon is wrong

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2840]
**Describe the bug**
- grey instead of Purple

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to  InProgress Fa workqueue
2. Click on a record
4. Note the icon colour 

![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/be4b58e3-15e8-496d-ab6c-30e0554600cd)

**Expected behaviour**
it should be the purple document colour

**Comment by anny320** [comment]
issue resolved with latest form fix
