### ISSUE TITLE
Bold words and Normal words becomes overwritten (Certificate Collection page)

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#2842]
****bug**
" Continue without signed affidavit? " becomes overwritten with other words** 

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in as Registrar
2. Click on 'Ready to Print'
3. Download an application
4. Click on Print
5. choose an option
6. Tab on Continue
7. fill up the fields
8. Click on continue
9. Don't upload
10. Mark on " They don't have a signed affidavit
11. click continue 
12. See the bug

**Expected behaviour**
All the words shouldn't be overwritten

**Screenshots**

![overwritten](https://user-images.githubusercontent.com/70468099/162171598-68998d8a-3dfa-4570-bb18-9cab62057926.png)

**Desktop :**
 - OS: linux
 - Browser:  chrome

**Possible fixes**
https://www.loom.com/share/3740a1792c21483888ef5aa58196c80b

**Comment by Zangetsu101** [comment]
### This seems to have already been fixed
![image](https://user-images.githubusercontent.com/29002716/174767037-b35f061d-bd99-4f23-88c7-3e2d9ee709e9.png)

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/174783926-8ba16619-f2fc-4db1-9161-2386bd30c448.png)
This is passed

**Comment by anny320** [comment]
completed
