### ISSUE TITLE
Create Offices at National Level and Province Levels

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2845]
### Description

- Create Farajaland HQ at National Level: 1 National Registrar, 1 National System Admin, 1 Performance Manager
- Create Province 1,2,3 etc Office: 1 Local System Admin, 1 Registrar, 1 Performance Manager

- So we can test Local System Admin permissions. IF they can only edit/add users in their jurisdiction 

### Acceptance criteria

GIVEN
WHEN
THEN

### Dev-tasks

- [ ]  Task 1

**Comment by euanmillar** [comment]
@jpye-finch we need to discuss this and if it is needed

**Comment by euanmillar** [comment]
@jpye-finch  Closing this as there is nothing blocking this from current functionality.  There is nothing to build
