### ISSUE TITLE
Create a performance manager user type & view

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2846]
### Description

- Only have access to Performance tab. Defaulted to location to Farajaland. 
- Delete Performance Oversight user type

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/d0de1771-1658-498d-b8d3-c7a6d7fe8a9a)

### Dev-tasks

- [ ]  Create a new user Performance Manager.  They need a new scope.  Restrict their scope to only see performance, no search bar, no work queues, no teams.  
- [ ] The status window "View all" and the Field Agent status links must be disabled for this user as they link to personal information

**Comment by Fariha-Amin** [comment]
Issue raised while testing this is : [https://github.com/opencrvs/opencrvs-core/issues/3312#issue-1257726171](url)

**Comment by anny320** [comment]
completed
