### ISSUE TITLE
Create National Registrar user

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2847]
### Description

- We don't have a National Registrar!!
- Create new user type. National Registrar
- Performance tab - defaulted to Farajaland
- Team defaulted to their assigned office

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
https://www.notion.so/opencrvs/Users-224e2095e2324bc096684d4d89122d78
https://www.notion.so/opencrvs/Default-views-of-performance-management-for-different-users-ec2735c981ef4b4995a00e2e1d3ccc71

### Dev-tasks

- [x] Create a new user type who is a NATIONAL_REGISTRAR.  Their default performance view is the Farajaland view.  Their scope is the same as registrar.
- [x] If logged in as LOCAL_SYSTEM_ADMIN, ensure they cannot create a NATIONAL_REGISTRAR or a NATIONAL_SYS_ADMIN in the create user flow.  Only a NATIONAL_SYS_ADMIN can create these user types

**Comment by saima-alam** [comment]
@anny320. The test is complete for National Registrar. Testcases are also updated. This can be closed.

**Comment by anny320** [comment]
completed
