### ISSUE TITLE
Page language remains same after changing the page language

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#2853]
**Describe the bug**
After changing language, page becomes change after refresh 

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as FA
2. Click on Change" to modify language
3. Select another language
4. See no update

**Expected behaviour**
Page should be modified after changing language

**Screenshots**
![image.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/8ca28a93-5e02-4a89-a5e5-f6db174578a0)

https://images.zenhubusercontent.com/91778759/4dcc25c5-e3ed-4252-8d9f-70261593b425/opencrvs_register___8_april_2022.mp4
![yeee](https://user-images.githubusercontent.com/70468099/162700033-36e379fd-8558-4f4b-8ed8-da7b485406dd.png)

**Comment by jpye-finch** [comment]
@azantor64 can we highlight where there isn't french translations also. ie. tabs in the side nav

**Comment by azantor64** [comment]
@jpye-finch 
![yeap](https://user-images.githubusercontent.com/70468099/162699681-9a6032c6-e164-4f45-b447-a58a529695be.png)
