### ISSUE TITLE
Update Status and history action in audit record

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2861]
**Bug description:**
some of the status , history action and icons showing as expected.

**Notion link:**
https://www.notion.so/opencrvs/Record-Audit-5ea0204d2b6c40858e772028784db864

**Steps to reproduce:**
1. Login as Registrar/ Registration agent
2. Navigate to all the tabs

**Expected Output:**
1. The first action in History for all the records should be Started. This action should also appear in records whose status is Incomplete
2.  Remove Waiting for validation action from History (only show Waiting for validations when OpenCRVS is configured  validate registrations with another system)
3. Status for in progress> Field agent should be Incomplete (Field Agent)
4. Status for in progress> Hospital should be Incomplete (Health System)
5. Copy change in history action from Updated declaration to Updated
6. In ready for review the status should be In review instead of Declared
7. Copy change in history action from Declaration registered to Registered
8.  'Reinstated to Declaration started' not showing at first time after reinstate
9. In Sent for update the status should be Requires updates instead of Rejected
10. Copy change in history action from Rejected to Requires updates
11.  Copy change in history action, if the user is a Field Agent, then Started Declaration needs to change to Sent notification for review
12. Add Certified line in history
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=0%3A1

**Steps to reproduce:**
1. Login as Field agent
2. Navigate to all the tabs

**Expected Output:**
1. In sent for review the status should be 'In review' instead of Submitted when a complete application is submitted with orange document icon
2. In sent for review the status should be 'Incomplete (Field Agent)' instead of Submitted when an incomplete application is submitted with a purple document icon

**Comment by jpye-finch** [comment]
@SyedaAfrida 

jUst not clear on no.8 have you got a screenshot of what currently shows?

**Comment by SyedaAfrida** [comment]
> @SyedaAfrida
> 
> jUst not clear on no.8 have you got a screenshot of what currently shows?

Observe Reinstate in the history
![reins](https://user-images.githubusercontent.com/94350336/162712879-410822bb-1942-4718-9809-9c8204ebf150.png)

**Comment by euanmillar** [comment]
NOTE: Certified exists, just if you have already downloaded this application you dont get an updated record audit.  This will fix itself when we finish the conflicts work.

**Comment by SyedaAfrida** [comment]
@anny320 Number 1 in Expected result has failed. so created new ticket #3323
Number 8 & 12 will be tested after conflict is deployed to QA.
All others has passed

**Comment by anny320** [comment]
2861 to be retested once conflicts pushed to QA  for 8&12

**Comment by anny320** [comment]
reopened for retesting

**Comment by SyedaAfrida** [comment]
@anny320 12 number in expected result is passed now
![Uploading certified passed.png…]()

**Comment by anny320** [comment]
completed
