### ISSUE TITLE
when a record is save & exit, the history should show updated action

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2862]
**Bug description:**
- No record history for your own drafts. 
- When a record is save & exit, the history should show updated action in the audit record page

**Steps to reproduce:**
1. Login as FA/ Registration agent/ Registrar
2. Click in progress
3. Click update
4. change any information'
5. Click Save & exit

**Actual result:**
In record audit history, there is no action saying the record is updated

**Expected Result:**
Should see line item for 'Started'
Should show 'Updated' action

**Screen recording:**
https://images.zenhubusercontent.com/91778759/c176068d-d1ed-433e-9e30-036052c1f1c7/when_a_record_is_save___exit_the_history_should_show_updated_action.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by jpye-finch** [comment]
@SyedaAfrida just made minor udpates

**Comment by euanmillar** [comment]
We agreed that saving history on your own draft is not saved in the backedn so we are just going to show a single row for drafts.
