### ISSUE TITLE
Form configuration: Settings

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2870]
### Description

- Adds settings option to Form configuration. To select the no. of address to be captured for the Deceased, Parents and Informant, and whether the HIDE_EVENT_REGISTER_INFORMATION property is true or false
- If Birth: Parents and Informant
- If Death: Deceased and informant
- Default is one address

### Acceptance criteria

GIVEN I am on the Settings page for form configuration
WHEN I click change
[THEN show the Addresses? model](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1947%3A26674)

GIVEN I change it to two addresses
WHEN I click apply
THEN update the form to show two addresses for the Informant and Parents. Usual place of residence and 2nd address

### Design
https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1090%3A17421

## Uses Application Config backend

- [x]  In the config microservice config schema add a new property ADDRESSES can be equal to a number 1 or 2.  Update any handlers, queries, mutations. - 2

## FE

- [x] Clicking the cog in the Form config header, opens a new page FormConfigurationSettings using a Content component and ListView.  Mark up the 2 options with a "Change link".  Load the currently selected option from window.config - 2

- [x] Clicking change on the "Introduction page" row opens a modal with the toggle form: https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1947%3A26712. Clicking Apply calls the application config update mutation to change the value of HIDE_EVENT_REGISTER_INFORMATION.  Show toast notification on success. - 2

- [x] Clicking change on the "Number of addresses" row opens a modal with the radio group form: https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1947%3A26674. Clicking Apply calls the application config update mutation to change the value of ADDRESSES.  Show toast notification on success. -2

**Comment by anny320** [comment]
closed
