### ISSUE TITLE
As a registrar/rgistration agent, archive incomplete notifications from Field Agent and Health System

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2871]
### Description

- add Archive button to incomplete Field Agent and Health System notifications

### Acceptance criteria

GIVEN I am on the In Progress Field agent workqueue or Health system workqueue
WHEN I click on a record
THEN I can Archive the record

GIVEN I archive the record
THEN remove it from the  In Progress Field agent workqueue or Health system workqueue

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4432%3A96108
https://www.notion.so/opencrvs/Record-Audit-5ea0204d2b6c40858e772028784db864

### Dev-tasks
- [ ]  Probably most changes will need to be made in workflow like adding IN_PROGRESS status to the list of archivable statuses etc - 2
- [ ] Update the workqueues and RecordAudit to enable Archiving in progress declarations. Might need to use data:generator to test the hostpital notifications - 2

**Comment by euanmillar** [comment]
Blocked until https://github.com/opencrvs/opencrvs-core/issues/3120 is completed

**Comment by euanmillar** [comment]
No longer blocked, but you can archive if at first you reject so there is a workaround

**Comment by SyedaAfrida** [comment]
**Bug:**
From field agent create any incomplete death application with has no data other than phone number and submit it. Later when Registration agent/ Registrar  archive that application and search , **System crash** when trying to redirect to record audit page


https://user-images.githubusercontent.com/94350336/182588824-32c757a0-4fe3-4a4a-9dcd-ace45ad36ff9.mp4

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is now fixed and can be closed

https://user-images.githubusercontent.com/94350336/184864095-29d96a9d-125f-4a21-94b8-44f2dcb0c082.mp4

**Comment by anny320** [comment]
completed
