### ISSUE TITLE
Update forms depending on application config number of addresses: ADDRESSES

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2872]
Make Primary and Secondary address options configurable

**Comment by euanmillar** [comment]
Blocked until Form Config and Form Config Settings is all merged and ready.  Develop branch would need to be merged into the FormConfig branch

**Comment by SyedaAfrida** [comment]
@anny320 testcases are updated so this ticket can be closed
![birth 2 addresses](https://user-images.githubusercontent.com/94350336/172599089-efbac911-4606-42ee-b556-b42d89e51f53.png)

**Comment by anny320** [comment]
completed
