### ISSUE TITLE
Back end - As a national system admin, I can save and publish a draft of my configuration

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2877]
## Back end

- [x] Drafts need 4 enum statuses: DRAFT, IN_PREVIEW, PUBLISHED, DELETED and an statusModifiedAt timestamp property to save the timestamp.  We also need an array of draft versions including version number, comments strings, and draftModifiedAt timestamps to display in the Drafts tab of the UI. Amend the schema, and any handlers / resolvers to cater for this new property - 1

- [x] In workflow, in the modifyTaskBundle service, check the status of drafts in the config microservice here: https://github.com/opencrvs/opencrvs-core/blob/c3c221d4b693d1ee2f5e078825e255919f130843/packages/workflow/src/features/task/fhir/fhir-bundle-modifier.ts#L32

If the status of any event draft is not published, then add an extension to the Task:

```

          {
            url: 'http://opencrvs.org/specs/extension/configuration',
            valueReference: { reference: 'IN_CONFIGURATION' }
          }
```
- [x] Build a modifyDraftStatus handler in config microservice.  It should receive the event and status to be changed.  The logic should change the draft status.  A DRAFT can be made IN_PREVIEW or DELETED.  An IN_PREVIEW can be made DRAFT, PUBLISHED or DELETED.  DRAFT cannot be made PUBLISHED.  PUBLISHED cannot be made IN_PREVIEW, DELETED or DRAFT.  It should return the new status and statusModifiedAt property or throw an error. - 2
- [x] Build a modifyDraftStatus mutation in gateway restricted to "natlsysadmin" scope.  It should call the modifyDraftStatus in config service.  In modifyDraftStatus in the config microservice, check all Tasks on Hearth.  If any of the tasks DO NOT have the IN_CONFIGURATION extension throw an error.  As long as all tasks have the IN_CONFIGURATION extension, then  use mongoose to drop the collections of Composition, Person, Patient, RelatedPerson, Observation, Extension.  

- [x] In search service, create a handler to delete everything.  
- [x] In the metrics service create a handler to delete everything.
- [x] After dropping the collections, config should call the search and metrics delete handlers.

**Comment by SyedaAfrida** [comment]
@anny320 Since testcases of form config is updated and tested this ticket can be closed

**Comment by anny320** [comment]
completed
