### ISSUE TITLE
Performance BE for Completeness Rates [2] 

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2884]
### Completeness Rates
- [x] In client rename metricsQuery  PERFORMANCE_METRICS to REGISTRATION_RATES_METRICS
- [x] In client rename metricsQuery OPERATIONAL_REPORTS_METRICS to PERFORMANCE_METRICS and OPERATIONAL_REPORTS_METRICS_FOR_OFFICE to PERFORMANCE_METRICS_FOR_OFFICE.  In client and gateway, getEventEstimationMetrics resolver must return birthTargetDayMetrics, deathTargetDayMetrics, birth1YearMetrics, death1YearMetrics,  birth5YearMetrics, death5YearMetrics

- [x] In metrics microservice, the fetchLocationWiseEventEstimations handler logic must be repeated so that the handler returns not just data where EXPECTED_BIRTH_REGISTRATION_IN_DAYS is equal to BIRTH?.REGISTRATION_TARGET or DEATH?.REGISTRATION_TARGET, but also 365 days and 1825 days respectively.

**Comment by SyedaAfrida** [comment]
@anny320 testcase of performance are updated so this ticket can be closed

**Comment by anny320** [comment]
completed
