### ISSUE TITLE
Performance BE for Registration Rates [4] & Fees Collected

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2886]
### Registration Rates

- [x] In the client, in metricsQuery, from the renamed REGISTRATION_RATES_METRICS, move the fetchRegistrationMetrics query into the new PERFORMANCE_METRICS & PERFORMANCE_METRICS_FOR_OFFICE set of queries.  We are going to combine genderBasisMetrics and estimatedTargetDayMetrics in some way and instead fetchRegistrationMetrics must include malePercentage / femalePercentage, blocks for birth and death. In birth we need regWithinTargetd, regBetweenTargetDAndLate, regLate.  In death, we need regWithinTargetd and regLate

- [ ] In the metrics service, metricsHandler must be refactored to return similar metrics for 3 time periods for birth and 2 for death.  E.g. regWithinTargetd from the query is equal to registrationTargetInDays.  But we need 2 more properties for regBetweenTargetDAndLate and regLate, using the config variables BIRTH.LATE_REGISTRATION_TARGET and greater than BIRTH.LATE_REGISTRATION_TARGET.  Similarly for death regLate uses greater than DEATH.LATE_REGISTRATION_TARGET.  Deprecate genderBasisMetrics in favour of male/female percentages

- [x] In metrics > features > registration > pointGenerator > generateBirthRegPoint check if the place of birth is a HEALTH_FACILITY or HOME_BIRTH and save.  Amend fetchRegistrationMetrics query and resolver and the metrics service metricsHandler to return the heakth facility and home birth statistics.

**Comment by SyedaAfrida** [comment]
@anny320 review the testcase of performance and this ticket can be closed.
