### ISSUE TITLE
Alignment of Side menu is not vertically straight in Mobile view

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#2892]
**Description**
In mobile view, Side menu (Performance,Team,Configuration,settings,Logout) aren't aligned in accordance with the 1st line.

**To Reproduce**

1. Go to https://register.farajaland-qa.opencrvs.org/
2. Login as National Sys Admin
3. Observe Alignment of Performance,team settings and logout

**Actual Result**
Side menus aren't aligned as design
**Expected behaviour**
Alignment of (performance,team,setting, logout) should be vertically straight

**Screenshots**
![image.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/e365195d-3db0-4c1f-b4e3-f3141eb03cdb)

**Smartphone :**
 - Device: Samsung S+
 - OS: Android
 - Browser: Chrome

**Comment by anny320** [comment]
issue resolved with latest form fix
