### ISSUE TITLE
Print receipt is not working

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2895]
**Bug description:**
When you try to print a certificate, Print receipt button is not working

**Steps to reproduce:**
1. Login as Registration agent/ Registrar
2. Go to ready to print
3. Click Download> Print on any application 
4. Click any option except "Print in advance for signatures and collection" >  Continue
5. Click "yes" > Continue
6. Click Print receipt

**Actual result:**
Print receipt button is not working

**Expected result:**
Should have option to print receipt

**Screenshot:**
![print_receipt.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/be063620-8fc9-4487-84c5-5a6d617dae1f)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by jpye-finch** [comment]
@euanmillar we removed the print receipt, right? When we added currency to application config? Was tricky to config the pdf to show the different currency symbol?

**Comment by euanmillar** [comment]
We must remove the print receipt button entirely

**Comment by eduffus** [comment]
If we cannot implement printing of receipts fully then agree with @euanmillar --> We must remove the print receipt button entirely, including any code associated with printing receipts. Think about the places where printing receipts is possible in the application, related to certificate printing, making a correction,...

**Comment by anny320** [comment]
completed
