### ISSUE TITLE
Add intl messages for al field types

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2896]
- [x] Create intl messages and translations for all different types of field

**Comment by yeasinhossain-dsi** [comment]
Submitted in following PR:
https://github.com/opencrvs/opencrvs-core/pull/2945

**Comment by Zangetsu101** [comment]
We need intl messages for these field types: https://github.com/opencrvs/opencrvs-core/blob/fb0985a913ca955f57f3aac87204f83e178f0cb5/packages/client/src/forms/index.ts#L37-L62

**Comment by SyedaAfrida** [comment]
@anny320 Form config testcases are update and have reported all the bugs separately in new tickets. So this ticket can be closed

**Comment by anny320** [comment]
closed
