### ISSUE TITLE
For some previewGroups do not render config fields, instead render ConfigPlaceholder

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2897]
- [ ] We need a new ConfigPlaceholder component that takes the previewGroup label as text

![Screenshot 2022-04-19 at 11.04.42.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/9da3e037-6c55-41f8-9924-d28c86f136a6)

- [ ]  In the FormConfigCanvas, if the field is inside an uneditable previewGroup: (primaryAddress, secondaryAddress, placeOfDeath or placeOfBirth), do not render the field.  Only one ConfigPlaceholder component should render for the previewGroup.

**Comment by SyedaAfrida** [comment]
@anny320 this is fixed and can be closed
![place of del 3](https://user-images.githubusercontent.com/94350336/173541203-94505880-988f-4f5c-89ee-6405061a2996.png)
![place of del2](https://user-images.githubusercontent.com/94350336/173541212-1dd1ddfb-681c-406e-84be-e68a5953685c.png)
![Place of del](https://user-images.githubusercontent.com/94350336/173541216-5bae6665-d308-48e0-971c-a7a75715d87c.png)

**Comment by anny320** [comment]
completed
