### ISSUE TITLE
As a registration agent or a registrar I want to assign myself and download a record

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2899]
### Description

- add confirmation model to record download
- on confirm. The record is assigned to the user
- no one else can them download the record

### Acceptance criteria

GIVEN I am on a workqueue
WHEN I click download
THEN show the confirmation model

GIVEN the model is open
WHEN I click confirm
THEN download

GIVEN the record has successfully downloaded
THEN assign the record to the user

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4301%3A99992

### Dev-tasks
- [ ]  If you are a registration agent or a registrar, the behaviour of the download button must change.  Instead it must open a modal overlay.  

If the assignment object exists and the user is a registration agent.  They cannot download. Instead they see this modal:

![Screenshot 2022-05-09 at 12.14.22.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/9b546402-71bb-4bbf-8a39-bef8148bebf7)

If there is no assignment object and  the user is a registration agent or registrar, then they see this modal:

![Screenshot 2022-05-09 at 12.18.02.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/486ca57f-6f65-4478-93e9-975c8bd5ced6)

When you click assign, then call the fetchBirthregistration fetchDeathRegistration handler

**Comment by euanmillar** [comment]
@jpye-finch if a registration-agent user tries to download a record that is assigned to someone else what do they see if they click a profile image?  Only a registrar can un-assign the row

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/174007442-2db91704-e978-49a3-a2c9-1b4658b48949.png)

**Comment by SyedaAfrida** [comment]
@anny320 testcase of this ticket is updated and tested. So this can be closed
