### ISSUE TITLE
As a user I want to see who is assigned to a record

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2900]
### Description

- Adds profile image to Workqueue row to indicator who the record is assigned to
- Model on click of profile. Shows who and where it is assigned

### Acceptance criteria

GIVEN I am on the workqueue
WHEN a record is assigned to someone else
THEN I [can see their profile image](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4301%3A100870)

GIVEN I click on the profile image
THEN show the [description model of who it is assigned to](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4253%3A100568)

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4301%3A100870

### Dev-tasks

- [ ]  When the workqueue loads, if the assignment object exists and the user is a registration agent or registar, replace the download icon with a new button containing an image tag.   The src will be to the Avatar API using the initials of the user's firstName and lastName.   The src should also call the avatar endpoint on gateway and replace this placeholder, if a user has created an avatar.

**Comment by SyedaAfrida** [comment]
@anny320 testcase of this ticket is updated and tested. So this can be closed

**Comment by anny320** [comment]
completed
