### ISSUE TITLE
As a registrar, I want to unassign a user from a record

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2901]
### Description

- Adds unassign option for registrar. 

### Acceptance criteria

GIVEN a record is assigned to another user
WHEN a Registrar click on the profile image
THEN [show the unassign model ](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4211%3A95460)

GIVEN the Registrar unassigns a record
THEN show the loading state

GIVEN the record is successfully unassigned 
THEN show the download button

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4211%3A95460

### Dev-tasks

- [ ]  If the user is a registrar, and the assignment object exists, when they click the download button they see this modal:

![Screenshot 2022-05-09 at 12.22.42.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/bb669f01-3397-44f5-8bb4-d3081040bd77)

- [ ] Clicking unassign, should wait for the markXAsUnassigned mutation to complete, then call the fetchXRregistration handler

**Comment by SyedaAfrida** [comment]
@anny320 testcase of this ticket is updated and tested. So this can be closed

**Comment by anny320** [comment]
completed
