### ISSUE TITLE
As a user, I want to unssaign myself from a record

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2902]
### Description

- User can unassign themselfs from a record
- clicking the downloaded icon show the unassign model
- any changes are lost
- record reverts to previous downloaded state.

### Acceptance criteria

GIVEN I have downloaded a record
WHEN I click the green downloaded icon
THEN show [the self unassign model](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4316%3A101577)

GIVEN I click unassign
THEN show the loading state

GIVEN I have successfully unassigned a record from myself
THEN show the download button

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4316%3A101577

### Dev-tasks

- [ ]  If the assignment object exists, and the userId is equal to the user who is clicking it, then you see this modal:

![Screenshot 2022-05-09 at 12.24.49.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/f3884167-0f31-425a-aa99-d22c0599cf21)

Clicking Unassign, calls he markXAsUnassigned mutation and removes the item from IndexedDB

**Comment by SyedaAfrida** [comment]
@anny320 testcase of this ticket is updated and tested. So this can be closed

**Comment by anny320** [comment]
completed
