### ISSUE TITLE
As a user I want to see the completeness rate graph and table

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2903]
### Description

- On View of Completeness Rates from Performance Dashboard. Nav to graph detail views. (As we do today)

If View:
1. Legally specified (Within 30days). Default filter on graph/table page to Within 30 days
2. Within 1 year. Default filter on graph/table page to Within 1 year
3. Within 5 years. Default filter on graph/table page to Within 5 years

- Embeds graph and table in Content component
- keeps current filtering logic

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3319%3A55104

### Dev-tasks
- [x]  Move data for each month request into a single request so that this page loads quicker
- [x] Rename the RegistrationRates component to CompletenessRates and load into a Content component
- [x] Build the select to change BRTH.REGISTRATION_TARGET / DEATH>REGISTRATION_TARGET to 1 year / 5 years and ensure that changing this reloads the metrics and renames the table column headings

**Comment by anny320** [comment]
completed
