### ISSUE TITLE
As a user I want to see the status of declarations

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2904]
### Description

- embed current table in Content component
- keeps current filtering logic
- [updates table columns ](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4287%3A109512)
- removes bengali name, time in external validation 
- on click on tracking ID. Navigate to record audit page

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3319%3A57256

### Dev-tasks
- [ ]  Task 1

**Comment by euanmillar** [comment]
@jpye-finch is this not a duplicate of this?  https://github.com/opencrvs/opencrvs-core/issues/2836

**Comment by jpye-finch** [comment]
oh it is!
