### ISSUE TITLE
As a Registrar I want to see Field Agent performance 

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2905]
### Description

- embed current table in Content component
- keeps current filtering logic
- [update table columns and copy](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3348%3A58240)

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3320%3A78071

### Dev-tasks
- [ ]  Task 1

**Comment by euanmillar** [comment]
@jpye-finch is this not done already and can be closed?

**Comment by jpye-finch** [comment]
closing

**Comment by anny320** [comment]
closed
