### ISSUE TITLE
Local system admin, National system admin and Performance Manager should not have search and Plus icon in top navigation

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2910]
**Bug description:**
Local system admin, National system admin and Performance Manager should not have search and Plus icon in top navigation

**Step to reproduce:**
1. Login as Local system admin/ National system admin / Performance Manager
2.  Click Profile
3. Click Settings

**Actual Result:**
showing search and Plus icon in top navigation

**Excepted Result:**
 should not have search and Plus icon in top navigation

**Screenshot:**
![search.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/f3db08b5-9acb-4a51-9e48-ec9ae9e425a0)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by atiqzaman-dsi** [comment]
This is quite easy fix. Changing the following logic in Header.tsx will fix the issue:
```
if (
      activeMenuItem !== ACTIVE_MENU_ITEM.DECLARATIONS &&
      (NATL_ADMIN_ROLES.includes(this.props.userDetails?.role as string) ||
        SYS_ADMIN_ROLES.includes(this.props.userDetails?.role as string))
    )
```
`activeMenuItem !== ACTIVE_MENU_ITEM.DECLARATIONS` logic fails since on both contains 0 on the settings page.

Also PERFORMANCE_MANAGEMENT is need to be checked but there is no constant declared for this role in the constants.ts.

**Comment by Fariha-Amin** [comment]
@anny320  This issue is solved and can be closed now

Retest  Recording:

https://user-images.githubusercontent.com/105624748/170420059-a1ee7587-ef96-4df5-84ee-316c18152e81.mp4

**Comment by anny320** [comment]
Completed
