### ISSUE TITLE
Goverment logo is fixed square. Doesn't apply in all locations

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2912]
**Describe the bug**
- aspect ration for the government logo is square. 
- so anythings uploaded other than square gets squashed
- government logo doesn't apply in all locations

- Farajaland logo: https://www.figma.com/file/IbpqQSjnUjwA5smwe2HFwuVA/styles?node-id=1238%3A750

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to declaration review page
2.Notice the logo is squashed 

**Expected behaviour**
- The logo should take the height of the div that it is placed in. 
https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=6008%3A18215
- if the div is 80px high. the logo should be 80px high. and maintain the aspect ratio of the logo
- so i can upload a logo with any aspect ratio

Logo must apply in these location (replace OpenCRVS logo)
- Login
- Review page (does already)
- Onboarding welcome screen
- Onboarding confirmation screen

Note:
- Pin Entry needs to be updated to use the users profile image

**Comment by Fariha-Amin** [comment]
@anny320  Government logo is not being updated on Onboarding confirmation screen and username/password reset confirmation screen. Also when image is changed, start button in the onboarding confirmation screen comes down, padding needs to be added below.


https://user-images.githubusercontent.com/105624748/173332008-2212d856-7c4f-480a-a784-de01cc10c0f2.mp4

![Screenshot from 2022-06-13 16-00-20](https://user-images.githubusercontent.com/105624748/173332060-1e9cf83a-0d8f-4eb6-b373-dc3771b943df.png)

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Retested with trianglular and rectangular shape image.**
**-Logo successfully updated in these locations:** ( for different shapes logo is not squashed)
-Login
-Review page (does already)
-Onboarding welcome screen
-Onboarding confirmation screen
- password reset confirmation screen
**Retest Recording:**

https://user-images.githubusercontent.com/105624748/174544464-4488b837-0be5-436f-ae33-eadac8292d25.mp4
