### ISSUE TITLE
Fix copy on Username reminder request page  from "assoricated" to associated

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2913]
**Describe the bug**

Fix copy on forgot username page from "**assoricated**" to **associated** in the question What is your phone number?
This is the number assoricated with your account

Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**
![Screenshot 2022-04-20 at 10.51.53.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/10f7ddce-4329-4966-8d97-215647fbf819)

**Additional context**

**Possible fixes**

replace "assoricated" to associated

**Comment by jpye-finch** [comment]
Update made

**Comment by Fariha-Amin** [comment]
@anny320 spelling is still wrong, needs to be corrected
![d](https://user-images.githubusercontent.com/105624748/171597770-5fdea473-89c7-4110-9eeb-eba63b716147.PNG)

**Comment by euanmillar** [comment]
This line should be removed now

**Comment by Fariha-Amin** [comment]
@anny320  The line is removed now, so this ticket can be closed.

**Comment by anny320** [comment]
completed
