### ISSUE TITLE
Application name not updating on Onboarding screen

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2914]
**Describe the bug**
- need to replace OpenCRVS with configured application name 

**To Reproduce**
Steps to reproduce the behaviour:
1. Change name of application
2. Create new user
3. Login as new user
4. Note Onboarding welcome screen. Name is still OpenCRVS. 

**Expected behaviour**
- name on Onboarding welcome screen should reflect the config application name

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/e1ce4fff-94ef-4d14-961b-f0e47df10a28)

**Comment by jpye-finch** [comment]
could remove the application name from this page and have amore generic title... 
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4747%3A100577

**Comment by jpye-finch** [comment]
could remove the application name from this page and have amore generic title... 
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4747%3A100577

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/171831648-3b35b2be-4223-479f-a956-fb431fcce996.png)

![image](https://user-images.githubusercontent.com/70468099/171831549-4c9a584e-cb2a-4a8d-b354-60d2fc34321f.png)
Passed. Can be closed. @anny320

**Comment by anny320** [comment]
completed
