### ISSUE TITLE
Not using ListViewSimplified in all locations

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2915]
**Describe the bug**
- not using ListViewSimplified in all locations

**Locations**
1. [x] Settings page
2. [x] Declaration review page
3. [x] Team page
4. [ ] Application config
5. [ ] Certificate config
6. [ ] Form declaration config
7. [ ] Form declaration Settings
8. [ ] Onboarding summary page
9. [ ] New user summary page

After all pages updated. Delete ListView. Then rename ListViewSimplified to ListView

**Comment by anny320** [comment]
completed
