### ISSUE TITLE
Update Onboarding flow to use Content component

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2918]
### Description

- updates Onboarding flow to use Content component
- updates loading state for 'Creating account' 

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4737%3A109593

### Dev-tasks

- [x]  Use Content component for the  onboarding flow pages
- [x] Add the loading state at the end

**Comment by anny320** [comment]
completed
