### ISSUE TITLE
Login, two factor pin creation and pin entry V2 (UI update)

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2920]
### Description

- this ticket supports issue #2667 (adding a custom background to Login pages)
- UI improvement to update login, two factor pin creation and pin entry
- add a white backdrop < Box > to form/page elements 
- use new < Frame > component
- use < Box >,< Stack > and new < Button > components
- uses < Toast > component to display error messages
- gets rid of 'gummy' icons on Pin creation

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7065%3A133711

### Dev-tasks

The Login app is quite a legacy application, we can use this opportunity to refactor Login to use react hooks.
There is also a lot of hardcoded styling in the Login app.  Now that we have a better component library, we can refactor the pages to clean it up.

- [x]  Refactor the StepOneForm to use react-hooks, the Box component and the Loading button.  Remove code for the ```mode={THEME_MODE.DARK}``` in InputField as this is no longer required.  Remove any custom styles. 

- [x]  Refactor the StepTwoForm to use react-hooks, the Box component and the Loading button.  Remove code for the ```mode={THEME_MODE.DARK}``` in InputField as this is no longer required.  Remove any custom styles.

- [x] Rename DarkPage / DarkPageContainer to `LoginBackground`.  From the StepOneForm extract the `usePersistentCountryLogo` hook to use in the new `LoginBackground` component and remove it from there. This component is common for both the StepOneForm and StepTwoForm.

- [x] Similar to `usePersistantCountryLogo` create another hook `usePersistantCountryBackground` which reads the `COUNTRY_BACKGROUND` from the reducer. Amend the IApplicationConfig interface in `authApi.ts` file to include the COUNTRY_BACKGROUND. (COUTNRY_BACKGROUND would be implemented in #2667 but in the meantime we can manually set the value in mongo to continue working in this ticket)
```ts
type ICountryBackground = {
  backgroundColor: string // hex value
  backgroundImage: string //base64 string
  imageFit: 'FILL' | 'TILE'
}
interface IApplicationConfig {
  //previous configs
  COUNTRY_BACKGROUND: ICountryBackground
}
```

- [x] Depending on the value of the COUNTRY_BACKGROUND render the `LoginBackground` with the backgroundColor or the background image

**Comment by jpye-finch** [comment]
related to https://app.zenhub.com/workspaces/opencrvs-core-5afeded64a54b06b54a969b2/issues/opencrvs/opencrvs-core/2667

**Comment by euanmillar** [comment]
We can do this, but I think we need to prioritise alongside other large pieces of work such as User Audit and the product roadmap for v2 as it is a big ask

**Comment by euanmillar** [comment]
@jpye-finch language select should be on the Login pages, not the PIN pages

**Comment by euanmillar** [comment]
@jpye-finch I think it makes sense to make the application config UI #2667 in tandem with this ticket.  Madagascar recently asked for this

**Comment by euanmillar** [comment]
Can we use this opportunity to refactor Login. use hooks, deprecate redux, use react-hook-form?  Up to the tech designer.

**Comment by SyedaAfrida** [comment]
**Bug:**
should support png and jpg file for background image. currently only support png. And the error message must be changed. Error message should be- "png, svg supported image only"
![err](https://user-images.githubusercontent.com/94350336/216037924-7c5a3173-35da-474d-b181-3503cfa77b99.png)

2. Keyboard not showing to enter pin

https://user-images.githubusercontent.com/94350336/216042181-e7e7b09b-bead-4b23-afe0-332465d43cfd.mp4

**Comment by SyedaAfrida** [comment]
**Bug:**
1. Apply button not working when upload an jpg file less than 2mb 

https://user-images.githubusercontent.com/94350336/222092873-f2cc0e27-42fe-4695-b0d2-8508948796bd.mp4

2. in mobile view cannot enter pin from keyboard

https://user-images.githubusercontent.com/94350336/222093036-163e1784-0613-49bb-9aa2-da983e788f07.mp4

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/227927409-7ad71b3f-d8a7-446e-8da3-81f39d377f6a.mp4


https://user-images.githubusercontent.com/94350336/227928015-a7bbb4ec-e40b-4303-b0a4-ddbbd52c56ac.mp4

**Comment by anny320** [comment]
completed
