### ISSUE TITLE
Updates change phone number to use models

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2921]
### Description

- uses models instead of full page to change number
- cleaner and more consistent approach

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4798%3A105611

### Dev-tasks

- [ ] Refactor change phone number flow to use modals instead of redirecting to a new page.
- [ ] Also convert to FC while at it

**Comment by SyedaAfrida** [comment]
@anny320 This ticket has passed and can be closed
![phone number1](https://user-images.githubusercontent.com/94350336/181195275-c206879b-68a5-4f14-aacb-5dd0502e5f31.png)

![Phone number 2](https://user-images.githubusercontent.com/94350336/181195268-b8cd79bb-2da4-4286-afad-eccb3564fe64.png)

**Comment by anny320** [comment]
completed
