### ISSUE TITLE
When multiple records submitted from field agent offline, some records stays on sending status

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2936]
**Bug description:**
In offline from field agent, when two or more records are submitted and then go online, the first records keeps on loading in Sent for review page. Though they can be found in in Progress/ Ready for review tab of Registration agent/ Registrar.
Sometimes this application also gets doubled in Sent for review tab with different status.

**Steps to reproduce:**
1. Login as Field agent
2. Go offline
3. Send 1 complete/ incomplete application offline
4. Send another complete/ incomplete application offline
5. Go online and observe the application in Sent for review tab

**Actual result:**
1st application keeps on loading
2nd application is submitted properly
if logged in to registration gent/ registrar can find both applications in Progress/ Ready for review tab as expected

**Expected result:**
both the application should be submitted properly from Sent for review tab

**Screen recording:**
https://images.zenhubusercontent.com/91778759/1c9d7193-59de-4472-b20e-5ee8e2336ca8/1_com_1_incom__com_donot_get_sent.mp4

Sometimes when logged out and logged in again to field agent, those  not submitted application appears in double
![double app.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/6ff84f9b-525e-42b2-97fd-0789a6ab477a)

**Tested on:**
 https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by euanmillar** [comment]
Possibly submission problem in Outbox.  Possibly workqueues for field agent not getting cleared before query populates new values when back online.

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![off one](https://user-images.githubusercontent.com/94350336/170654948-9e78f134-1400-4c19-b9bc-563841a1205c.png)
![off two](https://user-images.githubusercontent.com/94350336/170654994-f002dcc9-0799-43e6-a14d-b999109c3823.png)

**Comment by anny320** [comment]
completed
