### ISSUE TITLE
Certificate Config not showing properly in mobile view

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2939]
**Bug Description:**
Certificate Config not showing properly in mobile view

**Steps to reproduce:**
1. Login to national system admin
2. Click Configuration
3. Click Certificates

**Actual Result:**
1. Verbiages are crossing out of the screen
2. Preview page not center of the Screen
3. Upload modal not showing properly

**Expected Result:**
Should show the verbiages and buttons properly

**Screenshot:**
![1.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/080eeb7f-efa3-4128-af99-55df9db5f8b0)
![3.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/8d0beb52-6c20-4ecc-9d52-c294dfa21e04)
![4.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/02536246-d7a1-4312-99be-4db947f26877)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by azantor64** [comment]
- Verbiages are not crossing out of the screen

![image](https://user-images.githubusercontent.com/70468099/173324115-90e49173-5e4a-41cd-8b77-21890c415e2c.png)

- Preview page is centered on the screen

![image](https://user-images.githubusercontent.com/70468099/173324341-c163ae49-11f6-4018-bffe-89fb2b87af3c.png)

**Comment by azantor64** [comment]
Passed. Can be closed. @anny320

**Comment by anny320** [comment]
closed
