### ISSUE TITLE
Certificates Config page changes in loading state

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2940]
**Bug description:**
Certificates Config page changes in loading state. In Loading state, there is no updated date and 3 dot menu. 

**Steps to reproduce:**
1. Login as National system admin
2. Click Configuration
3. Click Certificates
4. Refresh the page and observe for few minutes

**Actual result:**
 In Loading state, do not show updated date and 3 dot menu. 

**Expected result:**
should be always showing updated date and 3 dot menu. 

**Screen recording:**
https://images.zenhubusercontent.com/91778759/4197393d-d10f-4b18-94e7-065b89989f3b/opencrvs_register___24_april_2022.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by SyedaAfrida** [comment]
This bug is fixed and can be closed
![loading state of certificate config](https://user-images.githubusercontent.com/94350336/171355397-83cfaee0-9523-4493-bb15-2ae9ff3e46cc.png)

**Comment by anny320** [comment]
completed
