### ISSUE TITLE
Records going to outbox and not getting registered

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2941]
**Bug description:**
When a record is Clicked to be registered when the previous record is still in the process of being registered, the first record goes to outbox and is not registered properly

**Steps to reproduce:**
1. Login as Registrar
2. In slow network, Click review> Click Register any record
3. Before the first application is registered properly,  Click review> Click Register another record
4. Observe the outbox

**Actual result:**
The first record stays in outbox (registering state) and second one is registered

**Expected result:**
Both should be registered

**Screen recording:**
https://images.zenhubusercontent.com/91778759/d3962c96-c6cd-4b19-a94d-73824a60ede0/when_two_records_are_registered_in_slow_network.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
Should be resolved with a fix to

**Comment by anny320** [comment]
completed
