### ISSUE TITLE
User Audit

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2942]
### Description

- Update User Audit to use Content component
- same layout and approach to RecordAudit

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=2216%3A45558

### Dev-tasks

- [ ]  Task 1

**Comment by euanmillar** [comment]
Needs combined with v2, v3, v4 Epics and a full description
