### ISSUE TITLE
Certificate Config bugs

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2944]
**Describe the bug**
Birth bugs
- It looks like the template handlbars for childs name is set incorrectly to informant FirstName and informantFamilyName.  update handles to show child's first name and family name. childFirstName and childFamilyName and check that the correct name renders on the certificate

![Screenshot 2022-05-25 at 16.28.34.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/309f615a-fb56-419f-ba1d-42a72495769e)

In Application config preview for certificate...

- update preview example name to Jane Smith
- update birth location preview example to Ibombo, Central, Farajaland

Death bugs:
- update deceased preview name to Michael Jones
a

**Comment by euanmillar** [comment]
Just waiting on completion of the ticket

**Comment by SyedaAfrida** [comment]
@anny320 This bug is fixed and can be closed
![prev](https://user-images.githubusercontent.com/94350336/171637762-d23a4a00-1b7a-4411-8726-130a28867a79.png)
![prev2](https://user-images.githubusercontent.com/94350336/171637782-91761742-618b-4723-b280-e0ae01204c3c.png)

**Comment by anny320** [comment]
completed
