### ISSUE TITLE
System crash for ready to review when download record offline

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2947]
**Bug description:**
when clicked download any record offline in ready to review, switch to any other tab, then come online and try to go to ready for review- System crash

**Steps to reproduce:**
1. Login as registration agent/ registrar
2. Go offline
3. Go to ready for review
4. Click download in any record
5. Go toa any other tab
6. Go online
7. Click ready for review

**Actual result:**
System crash for ready to review 

**Expected Result:**
Should not crash for ready for review. System does not crash for any other tab

**Screen recording:**
https://images.zenhubusercontent.com/91778759/28fe4393-87c1-412a-93d6-fcb397ff840c/ready_for_review_crash.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by SyedaAfrida** [comment]
@anny320 this ticket has passed and can be closedhttps://images.zenhubusercontent.com/91778759/59e17ac0-6cd9-40d8-8811-5396d853d4ac/no_system_crash_for_download.mp4

**Comment by anny320** [comment]
completed
