### ISSUE TITLE
System crash for correct record after language change 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2950]
**Bug description:**
system crash for correct record after language change 

**Steps to reproduce:**
1. Login as Registrar
2. Go to settings
3. Click change in language
4. Select Français
5. Click apply (in Français)
6. Go to ready to print
7. Download any record
8. Click Correct record
9. Select any option> Continue

**Actual result:**
System crash for correct record id checking page

**Expected result:**
should not crash system

**Screen recording:**
https://images.zenhubusercontent.com/91778759/ce36dcd3-f75d-47d7-8dd1-bd2cde09fdc0/system_crash_for_correct_record_after_language_change___1_.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by soumita-dsi** [comment]
@SyedaAfrida this should be fixed in #2976 ticket

**Comment by saima-alam** [comment]
@anny320, This is working as expected. This can be closed.
https://www.screencast.com/t/6YO4WMZR

**Comment by anny320** [comment]
Completed
