### ISSUE TITLE
Record created in one location cannot be continued/ registered in another location

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2952]
**Bug description:**
Record created in one location cannot be continued/ registered in another location. Suppose field agent of Ilanga District created any complete/ incomplete declaration. Now Registration agent/ Registrar of Ibombo District Office cannot find that record in workqueue/ search for that record using tracking id/ name

**Steps to reproduce:**
1.  Login as field agent of 1 location
2. Create a complete/ incomplete declaration
3. Note the tracking ID
4. Login to Registration agent/ Registrar of a different location
5. Search for that record

**Actual result:** 
shows no record found

**Expected result:**
should be able to find the record an d register/ print them

**Screen recording:**
https://images.zenhubusercontent.com/91778759/e377cef2-f133-4a5a-b273-475fc04809a1/opencrvs_register___27_april_2022.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

- [x] For registrars remove location id requirement from search
- [x] For loading workqueues, the results should show existing results from your location only, plus any result where regLastUser was the searching user

**Comment by sadmananik** [comment]
@euanmillar Second task is already done. Because when register can search declarations for other locations then review and REGISTERED it. At that moment it called modifyTask and modify the **regLastLocation**  on the hearth. So the work queue will load that declaration on ready to print tab as the location is the same as Register's location.

**Comment by Fariha-Amin** [comment]
@anny320  retest passed and can be closed

Retest Recording:

https://user-images.githubusercontent.com/105624748/170457572-cb52e97d-f76c-4480-902d-56974080d4b3.mp4

**Comment by anny320** [comment]
completed
