### ISSUE TITLE
For new location, field agent's audit not showing

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2955]
**Bug description:**
For new location ( other than Ilanga District Office/ Ibombo District Office) , field agent's audit not showing in user details page

**Steps to reproduce:**
1.  Create a new user of a Field Agent type in a new location
2. Login as the new user, change password, set security questions
3. Log out
4. Log in create a new birth or death application in an in - progress
5. Create a record
6. Login as registrar of that location
7. Click Team
8. Click on the field agent user

**Actual result:**
shows "No audits to display"

**Expected result:**
should be able to see audit

**Screen recording:**
https://images.zenhubusercontent.com/91778759/816450f5-d748-4caa-ac1e-ab78ce2f03f0/for_new_location_user_audit_not_showing_for_field_agent_users.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
I think this will be resolved by: https://github.com/opencrvs/opencrvs-core/issues/3120

**Comment by euanmillar** [comment]
Deprioritising as instead we are going to disable user audit links

**Comment by SyedaAfrida** [comment]
@anny320 this ticket cannot be tested since links to user audit is now disabled

**Comment by anny320** [comment]
closed
