### ISSUE TITLE
Show Modal in formConfigWizard for mobile view

### ISSUE THREAD

**Issue by yeasinhossain-dsi** [opencrvs/opencrvs-core#2958]
https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1117%3A43691

**Comment by SyedaAfrida** [comment]
@anny320 this ticket has passed and can be closed
![mobile view dec2](https://user-images.githubusercontent.com/94350336/173327596-044a8fbd-b1d8-4992-a82a-7423d7b74866.png)
![mobile view of dec](https://user-images.githubusercontent.com/94350336/173327602-d4a89e79-7c66-4565-a11d-826bd34d83b8.png)

**Comment by anny320** [comment]
completed
