### ISSUE TITLE
Sent for approval workqueue appearing in Registrars view

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2962]
**Describe the bug**
Login as registrar Derrick Bulaya/Kennedy
Sent for approval work queue is appearing in their view, it should be removed 
**Expected behaviour**
see work queue table   Registrar is not checked to view this work queue
https://www.notion.so/opencrvs/Work-queues-4c5690b03e78425e89c4cda193b8cee7
)**Screenshots**
![PXL_20220428_090741554.jpg](https://images.zenhubusercontent.com/61d3cc06859638b515717606/7eddea0a-d7df-4d22-840e-c4011b8746c6)

![Screenshot 2022-04-28 at 16.29.25.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/f1b760bb-817f-424b-9ec5-e0daeed8c1d5)
![Screenshot 2022-04-28 at 16.30.17.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/402b7ed0-8632-4348-ab94-76013b878773)

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by emon-swe-sust** [comment]
This is already fixed.

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/170267334-8a5f1195-4cd1-418c-bafb-8e1a2586caca.png)
![image](https://user-images.githubusercontent.com/70468099/170267391-14c86650-5a72-4891-9d1c-253a6a0fe60d.png)
This is passed. can be closed. @anny320

**Comment by anny320** [comment]
Completed
