### ISSUE TITLE
Record audit page of Field agent's requires Update not correct

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2968]
**Bug description:**
Record audit page of Field agent's requires Update not correct. There is no download option, so cannot view history also. The icon color should be red

**Steps to reproduce:**
1. Login as field agent
2. Create a complete/ incomplete birth/ death declaration
3. Login as Registration agent/ registrar
4. Go to in progress (field agent) / ready for review
5. Click download> review on that record
6. Click reject
7. Select any reason> give comment> Confirm
8. Login as field agent
9. Go to requires update and observe that record

**Actual result:** 
1. there is n download button
2. cannot view history
3. Icon color is gray
4. status is submitted

**Expected result:**
1. should have download icon
2. On download should be able to view history
3. Status icon should be red
4. Status should be requires update

**Screenshot:**
![sent for update.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/c0542fc2-4c9f-439b-a912-a4b73bba610a)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
Links and buttons must be disabled after download.  There is no assign / unassign ie for conflicts needed for field agent

**Comment by euanmillar** [comment]
This will be resolved by https://github.com/opencrvs/opencrvs-core/issues/3120

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/171626090-354832d9-0305-4ac0-8ea1-f9153effef38.png)

tested.passed. @anny320

**Comment by anny320** [comment]
completed

**Comment by anny320** [comment]
completed
