### ISSUE TITLE
In mobile view, back to review button and headings of correct record pages are missing

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2970]
**Bug description:**
In mobile view, back to review button of summary details page and headings of all correct record pages are missing

**Steps to reproduce:**
1. Login as registrar (in mobile)
2. Go to Ready to print
3. Click any record
4. Click Download> Click correct record

**Actual result:**
There is no , back to review button of summary details page and headings of all correct record pages are missing

**Expected result:**
should show header and back to review button

**Screenshot:**
in web
![web.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/02904b33-e185-421a-8842-9f452a3b95a6)

in mobile
![mob.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/e8848fd5-6f7f-4e3d-99fe-cc4de15bbcff)

**tested on:**
browser stack

**Comment by anny320** [comment]
@jpye-finch  please review

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/171598747-6a3a4b0a-734c-47a3-bf17-450a68189737.png)
Passed. can be closed @anny320

**Comment by anny320** [comment]
completed
