### ISSUE TITLE
Should not have strikethrough No in review page of correct record

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2971]
**Bug description:**
Should not have strikethrough No in review page of correct record

**Steps to reproduce:**

1. Login as registrar (in mobile)
2. Go to Ready to print
3. Click any record
4. Click Download> Click correct record
5. Go to review page
6. change father's details from no to yes

**Actual result:**
show strikethrough No in review page of correct record

**Expected result:**
should show - instead

**Screenshot:**
![tameem.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/4ca17ff1-f9f2-4325-b442-0efa475b9cdf)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/172155159-a6ee352c-2b5d-45db-ac03-1965a73eae7d.png)
![image](https://user-images.githubusercontent.com/70468099/172155218-81bfb459-3fc5-493f-b6ff-9a42cf2a78c4.png)
passed.waiting for review. @anny320

**Comment by anny320** [comment]
completed
