### ISSUE TITLE
In mobile view when delete any supporting document in review page, record goes to outbox

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2972]
**Bug description:**
System crash in mobile view when delete any supporting document in review page. In web view there is no option to delete supporting documents from review page. so need to confirm if there should be delete option in mobile view

**Steps to reproduce:**
1. Login as registrar/ registration agent
2. Go to any tab
3. Click on any application> Click review
4. Click on supporting doc
5. Click on the delete button
6. Click register/ Send for approval

**Actual result:**
Record goes to outbox and do not register and show console error

**Expected result:**
should be registered properly

**Console error:**
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting '_fhirID')
    at main.07faeac6.chunk.js:sourcemap:1:673067
    at Array.forEach (<anonymous>)
    at EE (main.07faeac6.chunk.js:sourcemap:1:672293)
    at Object.birth (main.07faeac6.chunk.js:sourcemap:1:2431639)
    at Mx (main.07faeac6.chunk.js:sourcemap:1:2433733)
    at main.07faeac6.chunk.js:sourcemap:1:2439530
    at l (2.c3f2e682.chunk.js:sourcemap:2:4477396)
    at Generator._invoke (2.c3f2e682.chunk.js:sourcemap:2:4477184)
    at Generator.next (2.c3f2e682.chunk.js:sourcemap:2:4477825)
    at n (2.c3f2e682.chunk.js:sourcemap:2:124489)

**Screen recording:**
https://images.zenhubusercontent.com/91778759/621190e7-e460-4d7d-a345-3991e07cdc15/library___loom___google_chrome___30_april_2022.mp4

**Comment by anny320** [comment]
to include network response

**Comment by rikukissa** [comment]
This issue cannot be reproduced after new deployments to QA. It was possibly caused by outdated declarations stored locally in the browser.
