### ISSUE TITLE
Console error when loading the system

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2973]
**Bug description:**
Console error when loading the system

**Screenshot:**
![console error.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/9ba0553d-92ae-483d-86c5-75e48395626c)

![console error 2](https://user-images.githubusercontent.com/94350336/166098020-d77d61ff-40f8-4e16-9246-c3bcadc9d021.png)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
Is this priority correct?

**Comment by eduffus** [comment]
Unclear whether this is blocking further login. If blocks login it should be high. In to-do to investigate further.

**Comment by sadmananik** [comment]
@SyedaAfrida Couldn't produce it in my local.

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/174774374-fe18670b-5068-481c-a813-43f867c65d47.png)

**Comment by anny320** [comment]
completed
