### ISSUE TITLE
Bugs for language change 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2977]
**Bug description:**
Bug that found after language is changed to french-

1. Create pin pages language do not change
![antor.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/79256e2f-a75c-4d07-b94e-f48f0e096612)

2. In review page, in many places language dont change. stays in english
![confusiong4.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/e0e504f8-45c8-48cf-991a-77ff9c5484c9)

3. In review page, verbiage not correct where record can be approved /rejected/ submitted by FA
![2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/00d408fe-e37d-4c49-b859-4a7d174109d8)

![16.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/0d36b365-2253-4a7c-a92c-eacd146cb050)

4.  In declaration page
![14.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/0fb95263-777f-40d7-83d3-0cb76f2227c6)

![15.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/a6aa149a-77d2-47eb-996e-071db626ea75)

![11.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/eb699cad-a67c-45c9-86d3-1e163d90050e)

5. headers of modal
![18.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/71388bb1-f0a4-41f8-9ba5-8b4720a2e58e)

6. In work queue, sometimes shows no names provided when there is name given
![19.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/a69a9a78-89a9-45c2-ac46-430bf3b4437d)

7. In work queue, column names are in mixed language. Names and actions are missing
![3.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/bbda70f4-459c-48d9-8370-dd60c07168eb)

8. In audit record some fields not in French
![7.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/fe535590-fd3e-4af6-ae96-63752a1049b1)

![bug sure.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/630ed975-c21d-4d74-9cfd-6b2ef98c359a)

9. In user audit
![confusion11.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/20dc39b2-696e-4656-8524-72d8fec3a149)

10. pagination
![12.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/60678e8b-0519-4b53-9695-f7bb7a992e92)

11. Search
![confusion9.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/78f31ac8-3399-4595-9667-a05ab0cfdc0b)

12. Calender
![AprilNotchanged.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/a5820774-28e7-4931-a248-8f961140034f)

13. In team, status and new user button in english
![Screenshot 2022-05-01 012007.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/6b2b1820-fecc-4735-8e27-606ef7ff3651)

14. Notification should be in English.
![notification](https://user-images.githubusercontent.com/70468099/166137614-2f4cc0b1-fb4b-44c1-90f1-065fdcfdbe14.png)

15. Months,dates,hours should be in french language
![bug3](https://user-images.githubusercontent.com/70468099/166136486-c4162af5-593d-4c10-819b-33c7341e4f1f.png)

16. Should be in francais
![1](https://user-images.githubusercontent.com/70468099/166138489-45cbd4ab-7f14-484d-92ea-68b73a7e04a6.png)
![2](https://user-images.githubusercontent.com/70468099/166138494-383cd673-5714-4284-86c7-5d3aca645b74.png)
![5](https://user-images.githubusercontent.com/70468099/166139095-67cf666b-5642-4c4e-967e-49b8edd82c4a.png)
![3](https://user-images.githubusercontent.com/70468099/166139104-dffdf77c-3d95-45d8-ac47-0b34e66a58bb.png)

**Comment by azantor64** [comment]
Another two bugs related to [Bugs for language change](https://github.com/opencrvs/opencrvs-core/issues/2977)

1.  [System crash for correct record after language change](https://github.com/opencrvs/opencrvs-core/issues/2950)
2. [System crashes and unable to print certificate,when language in set to french](https://github.com/opencrvs/opencrvs-core/issues/2976)

**Comment by saima-alam** [comment]
Bug exist in following pages

1.  Review page

**Comment by Fariha-Amin** [comment]
@anny320   Some issues are remaining:

**1. Translation of Registrar is wrong**
**actual result:**
![c](https://user-images.githubusercontent.com/105624748/174762593-fd4bffb4-aa29-4c80-9223-74c3cc395379.PNG)
**Expected Result:**
![b](https://user-images.githubusercontent.com/105624748/174762762-5b1b59b9-fce5-4ca8-af9e-129a182bb39b.PNG)

**2. Translation of local system admin is wrong**
**Actual Result:**
![sysadmin](https://user-images.githubusercontent.com/105624748/174763294-66e99b92-88aa-4655-8eb8-1c2dd780bcbc.PNG)
**Expected Result:**
![ad](https://user-images.githubusercontent.com/105624748/174763443-b5e8d045-f793-4848-8b52-b8e35b84199e.PNG)

**3. while declaring death event , "Deceased usual place of residence" is not translated to French**
**Actual Result:**
![a](https://user-images.githubusercontent.com/105624748/174763732-db05a222-03a3-4c86-ad04-658ef0a2b419.PNG)
**expected Result:**
![ad](https://user-images.githubusercontent.com/105624748/174763908-29d0ebac-429e-431b-bce1-fc61ba7f05e7.PNG)

**Comment by anny320** [comment]
completed
