### ISSUE TITLE
Keyboard navigation improvements  enable using tabs for side panel navigation

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2987]
**Describe the bug**
Improve accessibility. Keyboard navigation (using the tab key to navigate the page)
**To Reproduce**
https://images.zenhubusercontent.com/91778759/3fda2b6b-fdc6-4571-8402-048cafaca968/keyboard_navigation.mp4

**Expected behaviour**
Currently the tab navigation only works on Top Nav, should also work on side Nav
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by jpye-finch** [comment]
this has been address in the SideNav updates
