### ISSUE TITLE
Missing prompt to capture phone number for the Other family member option in Birth form

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2990]
**Describe the bug**
We need to capture the  pone number for Other family member section in birth form

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Birth form, follow prompts
2. Click on Who is the main point of contact for this declaration? *
3. Select Other family member 
4. See error - there is no option to capture the phone number

**Expected behaviour**
a text box should load to capture the phone number of the other family member
**Screenshots**
https://images.zenhubusercontent.com/91778759/23aaedd7-a06b-40fa-9b0f-3cca59bec205/other_family_member_missing_phone_number.mp4
**Desktop (please complete the following information):**
 
chrome browser

**Comment by Fariha-Amin** [comment]
@anny320  Retest passed and this issue can be closed now.
 

**retest screenrecording:**
https://user-images.githubusercontent.com/105624748/170245220-a8768be0-79ff-46f6-8204-39ce66cf519d.mp4

**Comment by anny320** [comment]
completed
