### ISSUE TITLE
Data is not visible when a record is clicked/downloaded

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#2991]
**Describe the bug**
Data greying out and not visible when a record is being downloaded. It should keep the same icon and data shown before clicking download

**To Reproduce**
Steps to reproduce the behaviour:
1.nav to record audit page
click download
notice the icon changes to purple and name changes to No name provided
supporting data changes to a default
It should keep the same icon and data shown before clicking download
**Expected behaviour**
clicking download should not change any content all ready shown

**Screenshots**
before
![image (4).png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/34413b5d-3d62-44c0-9a02-888f261653c9)

after
![image (3).png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/d517d5ae-2406-42a2-949d-0f21edb33b4d)

https://images.zenhubusercontent.com/91778759/55b7c08a-fa53-4520-a304-d520bd58574a/screen_capture__22_.mp4
**Desktop

**Comment by SyedaAfrida** [comment]
@anny320 seems like this ticket is the duplicate of #2746

**Comment by anny320** [comment]
will close this ticket and leave 2746
