### ISSUE TITLE
Tabs on mobile view are stacking

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#2996]
**Bug description:**
Tabs on mobile view are stacking.  It should overflow and allow horizontal scrolling.

**Actual result:**
Tabs on mobile view are stacking.
![image (3).png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/f92a35b8-2db7-4183-87fc-7597ce3d300a)

**Expected result:**
should overflow and allow horizontal scrolling. should have Stacking for filters only

**Check the design-**
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=5576%3A108102

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by SyedaAfrida** [comment]
@anny320 This bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/171800104-c77362ba-6001-4028-afde-79fc2b5c177d.mp4

**Comment by anny320** [comment]
completed
