### ISSUE TITLE
Search showing old loading state

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3000]
**Bug description:**
Search showing old loading state.

**Actual result:**
https://images.zenhubusercontent.com/91778759/824fac54-9b14-49a5-a5b6-9d5716e5cded/loading___.mp4

**Expected result:**
should be same as workqueue

![image (5)](https://user-images.githubusercontent.com/94350336/167122432-a635765e-9892-45ea-a79b-22f2f31a379d.png)
![image (6)](https://user-images.githubusercontent.com/94350336/167122500-a57729d0-9f27-48ba-a78d-9f2f952f0114.png)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by saima-alam** [comment]
@anny320, This is working as expected. This can be closed.

https://user-images.githubusercontent.com/105625699/172168154-b28e1960-ef3f-4068-83a0-371fea844010.mp4
