### ISSUE TITLE
System Crashes after clicking Archive button

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3008]
**bug**
As field agent after submitting an application, when as Registrar goes to archive that application then System shows: **Opps! this page could not be found**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://register.farajaland-qa.opencrvs.org/'
2. Create an application as **FA**
3. Click " **Send for review** " & Submit Application
4. Log out as FA
5. _log in as_ **Registrar** & **Registration clerk**
6. Go to Ready for review page
7. Click on Review 
8. Click on Archive 
9. See " Opps! this page could not be found"

**Expected behaviour**
Application should be archived

**Screenshots**
![image.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/cfb4796c-9d89-4a80-8a9e-6b60f1b56a05)

**Desktop**
 - OS:Ubuntu 
 - Browser : Chrome
https://images.zenhubusercontent.com/91778759/e23a2a18-f6ba-46d6-80e7-e5bf4c853535/opencrvs_register___9_may_2022.mp4

**Comment by anny320** [comment]
completed
