### ISSUE TITLE
In Correct Record feature System Crashes after click Cross(X) button

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3010]
**Describe the bug**
As Registration clerk after downloading an application in correct record section , Clicking on (X) button , it shows **Opps! this page could not be found**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://register.farajaland-qa.opencrvs.org/'
2. Log in as Registration clerk
3. Click on **ready to print**
4. Download an application 
5. click on correct record
6. Click on X (cross) button
7. See error

**Expected behaviour**
It should be redirected to correct record page

**Screenshots**
![image](https://user-images.githubusercontent.com/70468099/167402959-f33c114b-f2dd-46ef-8f0d-dc02bdf6486b.png)
https://www.loom.com/share/4b558149e8554c1cad0e5f3c4532b707

**Comment by emon-swe-sust** [comment]
resolved with this PR: https://github.com/opencrvs/opencrvs-core/pull/3055

**Comment by azantor64** [comment]
@anny320 , this is retested and passed. can be closed
https://user-images.githubusercontent.com/70468099/170018288-2d4ff802-1028-4ac7-8683-63fa633adc52.mp4

**Comment by anny320** [comment]
completed
