### ISSUE TITLE
When place of delivery is other than farajaland, it do not appear in record audit page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3016]
**Bug description:**
When place of delivery is other than farajaland, it do not appear in record audit page

**Steps to reproduce:**
1. Declare a birth event
2. In Child's details page> location- Residential address/ Other
3. Select any country other than farajaland
4. Fill up all the mandatory fields
5. Submit 

**Actual result:**
place of delivery do not appear in record audit page but appears in review page

**Expected result:**
should appear in record audit

**Screenshot:**
![place of delivery 2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/d99ec4a8-76a3-496d-b85f-c03aae0c65ee)
![place of delivery1.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/3d017f11-722e-45f5-a3aa-188965a2c254)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by saima-alam** [comment]
This is working as expected.

![image](https://user-images.githubusercontent.com/105625699/169539532-fb08f1b1-41a9-4bd0-ab9d-6c0a4266f2b7.png)

**Comment by anny320** [comment]
completed
