### ISSUE TITLE
Duplicate Application page can not be found after click on duplicate application

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3017]
**Describe the bug**
As Registrar after clicking a duplicate application page can't be found

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://register.farajaland-qa.opencrvs.org/'
2. Make 2 same application as FA and submit it 
3. Login as Registrar 
4. Search the name of that application 
5. Click on the duplicate application 
6. See Error 

**Expected behaviour**
Duplicate application page should be shown
**Actual Result** 
it shows: **Oops!
This page could not be found**

**Screenshots**
![image](https://user-images.githubusercontent.com/70468099/167574963-da63864d-a40b-4847-a4ac-52249565eb4a.png)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser: crome
https://www.loom.com/share/268c86c68a32417db07ab83c33eb218c

**Comment by euanmillar** [comment]
Blocked awaiting new design approach to satisfy thius brief to close off any issues with duplicates:  https://opencrvs.notion.site/De-duplication-improvements-1a7a816c1b644f35b82a1b5a658f0ef9

**Comment by euanmillar** [comment]
@jpye-finch Yay!

**Comment by emon-swe-sust** [comment]
I guess, this is fixed for current version
![duplicate](https://user-images.githubusercontent.com/43314141/168590767-166397d7-308b-4be4-8314-1c2c5d89a164.gif)

**Comment by euanmillar** [comment]
Will be fixed by: https://github.com/opencrvs/opencrvs-core/issues/3112

**Comment by anny320** [comment]
completed
