### ISSUE TITLE
Informant's age can be smaller than child's age

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3018]
**Bug description:**
Informant's age can be smaller than child's age. Currently in a birth declaration, informant must be older than child or else there is an error showing invalid date of birth

**Steps to reproduce:**
1. Declare a birth event
2. Enter child's DOB example 01/01/2000
3. Enter informant's DOB  smaller than child's example 02/02/2012
4. Go to review page

**Actual result:**
show error "Must be a valid date"

**Expected result:**
should not show error

**Screenshot**
![info.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/171c42f2-666f-4493-9161-a6e421456dfe)
![info2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/c955005d-6f26-4353-aa02-479f78d57253)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by Fariha-Amin** [comment]
@anny320   The bug is fixed now and can be closed

Retest recording link:

https://www.loom.com/share/57b0eef173cb403d851fecda1939a2cf
