### ISSUE TITLE
In supporting document, birth certificate of informant shows twice and skip Proof of legal guardianship doc 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3019]
**Bug description:**
In supporting document, birth certificate of informant shows twice and skips Proof of legal guardianship doc in review page

**Steps to reproduce:**
1. Login to field agent/ registration agent/ registrar
2. In "Who is applying for birth registration?" select any except mother/ father
3. Go to supporting document page
4. Upload files in all the options of Informant's ID
5.  Upload files in all the options of Others
6. Continue 
7. In review page observe informant supporting document dropdown

**Actual result:**
birth certificate shows twice in dropdown of informant

**Expected result:** 
birth certificate and Proof of legal guardianship options should show separately with correct document

**Screenshot:**
https://images.zenhubusercontent.com/91778759/c050ec4d-d8d9-452c-8eed-97855752dc7a/informant_supporting_doc_bug.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by SyedaAfrida** [comment]
@anny320 please set priority for this ticket

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/170680671-a86d24e1-998e-4cc2-8d29-e0655da8ffab.png)
![image](https://user-images.githubusercontent.com/70468099/170680748-1b8840a8-327a-402c-a510-fe16c0d4883a.png)
Passed. can be closed. @anny320

**Comment by anny320** [comment]
completed
