### ISSUE TITLE
Loading state for record audit

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3021]
**Describe the bug**
- loading state for record audit flashes back to 'in-progress view (purple icon and no name provided

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to record audit for a record that has not been downloaded
2. Click on download
3. Notice the page change: Icon (purple), child/deceased name changes to No name provided, status greys out

**Expected behaviour**
- it should keep the same data as before the download.

**Screenshots**
https://images.zenhubusercontent.com/91778759/aa6cbefb-a965-4265-8115-5dbdb3a8cd9b/record_loading_state.mp4

**Comment by emon-swe-sust** [comment]
Solved with this PR https://github.com/opencrvs/opencrvs-core/issues/3106

**Comment by Fariha-Amin** [comment]
@anny320   this problem is fixed and can be closed .

retest passed screen recording:


https://user-images.githubusercontent.com/105624748/170047661-772b3c97-6a22-4404-b05d-bd4b7a992e2d.mp4

**Comment by anny320** [comment]
completed
