### ISSUE TITLE
Download button doesn't change to noWifi icon when no connectivity

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3022]
**Describe the bug**
- using old no connectivity indicator
- Download button should change to noWifi if no connectivity
- Tooltip 'No connectivity'

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to workqueue
2. Go offline
3. Not no connectivity indicator centered at bottom 

**Expected behaviour**
- any download buttons in the workqueue should change to noWifi
- https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4149%3A91379
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/409238c3-9b20-447c-ab16-87c84419b245)

Note: Go Online button is part of prototype. ignore it

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/b60261d2-2ebb-400d-b033-06327ef2558b)

**Comment by euanmillar** [comment]
@emon-swe-sust has done it

**Comment by azantor64** [comment]
![online](https://user-images.githubusercontent.com/70468099/171834658-0655162a-4807-4331-9305-5306aa49f6cd.png)

@jpye-finch ,said **Not no connectivity indicator centered at bottom.**
![image](https://user-images.githubusercontent.com/70468099/171835026-b924fbce-01a0-4564-9372-d3f2aff213b5.png)

**Comment by anny320** [comment]
completed
