### ISSUE TITLE
Certificate Config: Add data tag to images

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3023]
**Describe the bug**
- difficult to work out correct order for images so that the signature properly displays

- suggest to use a data tag for images. So that the signature is appropriately tagged and doesn't matter where it appears in the code.

**Comment by euanmillar** [comment]
Remove logo from certificate altogether.  The only image will be for signature.  But please add a tag and use the tag to replace the signature

**Comment by saima-alam** [comment]
@anny320 Signature is showing correctly. This can be closed.
![image](https://user-images.githubusercontent.com/105625699/173070537-bb103ee7-eb01-403e-ba00-e5dfa3386355.png)

**Comment by anny320** [comment]
completed
