### ISSUE TITLE
Certificate config: Doc upload - use same component as gov logo upload

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3025]
### Description
- use upload flow/pattern used elsewhere (eg. gov logo upload).  my mistake.... 

### Acceptance criteria
GIVEN I am on Certificate Config
WHEN I click Upload
THEN show the upload confirmation model

GIVEN I click upload in the confirmation model
THEN show the system file select

GIVEN I select a file
THEN show the loading state

GIVEN the file has successfully loaded
THEN show the[ loaded state](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=3%3A594)

GIVEN there was an issue with the svg file
THEN show the[error state](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=11%3A3499)

GIVEN I uploaded a valid svg
WHEN I click Apply
THEN apply the certificate template and show the confirmation model

### Design
https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=2289%3A33690

### Dev-tasks

- [x]  Add an optional prop `previewTransformer` to `SimpleDocumentUploader` which will be used in the `selectForPreview` function to transform the previewFile. `previewTransformer` takes as an input the previewFile, applies some transformation on it and then returns it  - 1

- [x] In SysAdmin > Config > Certificates, we would replace the current file select component with 
SimpleDocumentUploader. When previewing the certificate, we need to feed some dummy data to the handlebars defined in the certificate svg. We will use the `previewTransformer` created in the previous task to do so. - 2

The previewTransformer function would be somewhat like the following:
```ts
  <SimpleDocumentUploader 
      allowedDocType={['image/png', 'image/svg+xml', 'application/pdf']}
      previewTransformer={(previewFile) => someTransformer(previewFile)}
  />
```

**Comment by euanmillar** [comment]
@jpye-finch updating this flow should be prioritised alongside updating login flow and user audit and other roadmapped features for v2

**Comment by euanmillar** [comment]
The request is essentially .... SVG upload component, could it be the same as gov logo upload component for example

**Comment by SyedaAfrida** [comment]
**Bug:**
After a certificate template is uploaded in death, the same file name appears in when clicked upload from birth and vice versa. Note, this issue no longer appears in the page is refreshed.

https://user-images.githubusercontent.com/94350336/193759009-32569e09-82a5-4c31-bb41-80f852a67bd3.mp4

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/195804919-27569868-29f3-4a4e-a11c-8115b0a5f8d0.mp4

**Comment by anny320** [comment]
completed
