### ISSUE TITLE
 The whole workqueue row should not be a link

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3029]
**Bug description:**
The whole workqueue row is currently a link. The name of child/deceased should be a LinkButton same as on team page. To navigate to record audit

**Steps to reproduce:**
1. Login to any user other than local/ national system admin
2. Go to any side menu other than performance/ team
3.Click on the workqueue row

**Actual result:**
The whole workqueue row is currently a link

**Expected result:**
Only the name of child/deceased should be a LinkButton same as on team page

**Screen recording:**
https://images.zenhubusercontent.com/91778759/40efdbf1-693d-4c16-ac0b-b8bd99657ea6/no_workqueue_link.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by Fariha-Amin** [comment]
@anny320  The bug is fixed now and can be closed

**Comment by anny320** [comment]
completed
