### ISSUE TITLE
Address field not fully loading when father is the only informant

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3031]
**Describe the bug**
A partial address field is loading when father is the informant when completing a birth registration as registration agent, only showing the title usual place of residence 
**To Reproduce**
Steps to reproduce the behaviour:
1. login as a registration agent , Go to birth form
2. select father as informant, complete phone number
3. complete child's details
4. select no  to question are mothers details available
5. complete fathers details, at the address step, you will only see the title usual place of residence
also missing in the review page is father address field

**Expected behaviour**
An address field should load to capture the fathers address.
Address details should also show in review page, currently missing

see design guide
https://www.figma.com/file/7AYxLlYTpY4RioSTIt0PbG/Fajarland-Birth-Declaration-Forms?node-id=1586%3A285

**Screenshots**
![Screenshot 2022-05-11 at 12.31.15.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/74bc0f7b-9624-43ed-9359-1ddbe51de931)
![Screenshot 2022-05-11 at 12.50.56.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/11e08ee2-b87e-4c1e-8211-c068da119cd1)
**Desktop (please complete the following information):**
 - chrome desktop

**Smartphone (please complete the following information):**

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by Fariha-Amin** [comment]
@anny320   Retest passed, can be closed

**Retest Screenshot:**

![father1](https://user-images.githubusercontent.com/105624748/170971781-1a1d3ee8-43a7-48b2-b371-ef1f32350cdf.PNG)
![father2](https://user-images.githubusercontent.com/105624748/170971791-bda36b16-cdd0-49ec-aa7d-6f1dc488f5e3.PNG)

**Comment by anny320** [comment]
completed
