### ISSUE TITLE
Form config,Performance,Certificate  appears on Field Agent home

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3039]
**Describe the bug**
When log in as FA , Form config,Registration home,performance ,certificate page appears after search these related URL

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://register.farajaland-qa.opencrvs.org/
2. Log in as Field Agent (username:kalusha.bwalya,pass: test)
3. Hit those URL: 
https://register.farajaland-qa.opencrvs.org/performance
https://register.farajaland-qa.opencrvs.org/config/application
https://register.farajaland-qa.opencrvs.org/config/certificate
4. See Error

**Expected behaviour**
Form config,Performance,Certificate pages shouldn't be appear on FA home
**Actual Result**
National Sys Admin Form config pages are appeared in FA home
**Screenshots**
![certificate.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/6998de99-79cd-4c2c-8516-aba0aebde77c)![config.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/c6886ac0-a31f-42be-91e3-e905743735d1)![perofrmance.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/e294fdf7-b2d8-43bb-aa43-07e75ff8e477)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome & Edge
**Video**

https://user-images.githubusercontent.com/70468099/167863319-d4c1c3d2-c47e-4491-b814-3eee1e6d7c41.mp4

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/170195653-5b61fbe9-79e4-4f01-a5c7-065f1edf8a64.png)
![image](https://user-images.githubusercontent.com/70468099/170195842-c2522163-66b0-4282-9e82-530db3a3ca72.png)
![image](https://user-images.githubusercontent.com/70468099/170195912-3c822946-5a16-4548-9b99-57e0f8350e33.png)

@anny320 ,Passed. can be closed! waiting for your review.

**Comment by anny320** [comment]
completed
