### ISSUE TITLE
Update image upload copy to remove pdf type

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3043]
**Describe the bug**
Currently we request a user to upload even pdf type of document when its not supported, to update the copy to remove pdf type
**To Reproduce**
Steps to reproduce the behaviour:
1. login as any user (i used registration agent)
2. Go to birth form / death form 
3. follow prompts to complete form.
In supporting documents page, attempt to upload an svg or pdf, to prompt the error message "File format not supported, please attach png, jpeg or pdf
Update to remove pdf option

**Expected behaviour**
Remove pdf option in copy

**Screenshots**
![Screenshot 2022-05-12 at 11.29.06.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/5fc0d220-fd46-46a6-9151-5b5434bf3d49)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - chrome desktop

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by jpye-finch** [comment]
have updated copy. This can be closed

**Comment by euanmillar** [comment]
Will be completed with JPFs copy amends

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/171627322-4e1d6ab7-93e5-40e2-8f1f-fa77d6e2a489.png)
**passed can be closed.**  @anny320
