### ISSUE TITLE
Cannot delete any in progress declaration

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3049]
**Bug description:**
Cannot delete any in progress declaration

**Steps to reproduce:**
1. Login To field agent/ Registration agent/ Registrar
2. Go to In progress record
3. Click Update in any record
4. Click 3 dot at the heading
5. Click Delete declaration
6. Observe in progress tab

**Actual result:**
Declaration do not get deleted

**Expected Result:**
Should get deleted and do not appear in in progress

**Screen recording:**
https://images.zenhubusercontent.com/91778759/7180a9f6-921f-4e69-aa92-9ce42639c79b/death_declaration.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by anny320** [comment]
issue was resolved![Screenshot 2022-06-03 at 14.56.10.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/e7dc371b-46c9-4fc5-949b-bb0b344f5aec) closing ticket
