### ISSUE TITLE
logo and signature is not appearing in Certificate

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3051]
**Bug Description:**
logo and signature is not appearing in Certificate

**Steps to reproduce:**
1. Login to registration agent/ registrar
2. Go to ready to print
3. Click Download> Print in any record
4. Click any Option and continue to Certificate preview page

**Actual result:**
Blank black image appears in logo and signature fields

**Expected Result:**
Should be able to view logo and signature

**Screen recording:**
![cer.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/04bb95c2-52d8-40ed-b1e3-3b6bec3d0fc6)

 **Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by SyedaAfrida** [comment]
@anny320 This bug is not fixed in QA.
![cer](https://user-images.githubusercontent.com/94350336/171105077-c7ee0eda-1e83-4416-b8a6-e92946f4f90e.png)

**Comment by SyedaAfrida** [comment]
This bug has passed and can be closed
![certificate passed](https://user-images.githubusercontent.com/94350336/171579448-af2da3e2-491c-429d-ad20-0092afe7810d.png)
![certificate passed 2](https://user-images.githubusercontent.com/94350336/171579476-be7deba2-2e99-4a77-9433-3d9aff50397e.png)

**Comment by anny320** [comment]
completed
