### ISSUE TITLE
Icon for validated status not correct

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3052]
**Bug description:**
Icon for validated status not correct

**Steps to reproduce:**
1. Login as registrar
2. Go to ready for review
3. Download any record which is approved by registration agent

**Actual result:**
Icon is grey
![image (12).png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/e77aa808-059a-4729-876f-c592a7ed148f)

**Expected Result:**
Should be yellow with a tick mark
![image (13).png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/8dfa3de6-7154-471f-a104-865b8735dfde)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by anny320** [comment]
issue resolved ![Screenshot 2022-05-26 at 15.10.55.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/25ab1c54-6ab0-4384-ad7d-6216e47ad106)
