### ISSUE TITLE
Text in any radio button should be top-aligned if text overflows onto two lines

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3053]
**Bug description:**
Text in any radio button should be top-aligned if text overflows onto two lines

**Steps to reproduce:**
Observe small and large radio buttons in any place of application

**Actual result:**
Text in any radio button is centered-aligned if text overflows onto two lines
![image (14).png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/0e5f1850-f2a1-4736-b1c3-f01ea4b2ef4d)

![image (15).png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/a52878f5-76e5-4faa-bf13-7960c9811b5e)

**Expected result:**
Text in any radio button should be top-aligned if text overflows onto two lines

![image (16).png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/b97fea6f-5479-43f5-af2d-69fb5d0e871b)

**Tested on :**
https://login.farajaland-qa.opencrvs.org/

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Retest SS:**
![ddd](https://user-images.githubusercontent.com/105624748/174247822-c0649d97-82e9-40e7-bf0b-99088d44508a.PNG)
![dd](https://user-images.githubusercontent.com/105624748/174247832-d16c7f08-f616-4216-a2cc-4548dc6c107b.PNG)
![d](https://user-images.githubusercontent.com/105624748/174247838-01b40adc-4bcf-4507-b455-830efa8c07b4.PNG)
