### ISSUE TITLE
In Review page validation message of  First & last name are not same

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3054]
**Describe the bug**
After fill up an application First name and last name of Child ,mother and father adds extra 's' , so they are different

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://register.farajaland-qa.opencrvs.org/
2. Make an application without giving child ,mother and father's First and last name
3. Go to review page

**Expected behaviour**
First name(s) in english required for registration
Last name in english required for registration
![image](https://user-images.githubusercontent.com/70468099/169235946-6bd9cc33-f108-422d-b524-43862b94e0fc.png)

**Actual result**
![Selection_010.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/8aba1ade-1d37-4c2e-b2b7-688374a4d5bf)
![Selection_009.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/c962e460-c557-4350-8a9c-d1f8e100cb61)

*

**Comment by euanmillar** [comment]
@anny320 can you combine these requirements with

**Comment by jpye-finch** [comment]
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/a0747edc-7e13-48dd-8350-dd282423a761)

**Comment by anny320** [comment]
lets use  #3058, will close this ticket
