### ISSUE TITLE
Should have space between numbers in pagination

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3057]
**Bug description:**
Should have space between numbers in pagination

**Actual result:**
![pagination.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/7da67dc9-13d0-4f11-8a75-60df5d19178f)

**Expected result:**
Should have space between numbers in pagination

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/173046985-c405ec0d-0397-4210-b660-22e46e9484ee.png)
