### ISSUE TITLE
Update Copy: name instances on form review page replace english name with Name and residential address

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3058]
**Describe the bug**
Replace the following copy with the proposed below:
**Steps to reproduce:**
1. Declare birth event
2. Observe child details page
3. Observe mother's details page
4. Observe father's details page

**copy: First name(s), Last name**
![image (7).png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/7aef5ea4-3936-45b1-924a-bba52d1f724c)
**copy:  First name(s), Last name**
![image (8).png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/9ad6ac29-b7fd-4883-a21f-635fed1f7c84)
**copy: Name**
![image (9).png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/3fbe1c51-abb8-4f03-8f32-ade2f215bc34)

**copy: Name**
![image (10).png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/3a4c552d-89d8-4c02-b552-6bfe3d65d22e)

**copy: Name**
![image (11).png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/6b9d0fb6-9fa1-4e15-a27d-8246ed6fb7c0)

**copy: Usual place of residence**

![image (12).png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/c5206cfe-0343-44df-8a95-cc8fa2068f03)
**To Reproduce**

**Expected behaviour**
Replace the copy with the suggestion provided.

**Comment by Fariha-Amin** [comment]
@anny320  not fixed for any case

**Comment by Fariha-Amin** [comment]
@jpye-finch

**Comment by jpye-finch** [comment]
yes this is still an issue:

Form:
First name(s)
Last name

Review page:
Full name

**Comment by Fariha-Amin** [comment]
@jpye-finch 
**1. Expected: First Name(s)**
![mothers- first name(s)](https://user-images.githubusercontent.com/105624748/171828636-18bd0c5b-95eb-4943-9c65-135e27ffdb04.PNG)

**2.Expected: Father's Fullname**
![ddd](https://user-images.githubusercontent.com/105624748/171828709-2ee250f9-f189-4fc8-9994-929abdd87f16.PNG)
**3. Expected: Informant's Fullname**
![informant-father](https://user-images.githubusercontent.com/105624748/171828791-68007841-1b2c-4d0e-b755-b38998fad6db.PNG)

**Comment by Fariha-Amin** [comment]
@anny320  passed, can be closed

**Retest SS:**
![dd](https://user-images.githubusercontent.com/105624748/172579563-0d99654c-e001-411d-b672-f59fd6d5bbcf.PNG)
![d](https://user-images.githubusercontent.com/105624748/172579575-5c851fef-40c4-4434-b202-bbc9ddcdab1b.PNG)
