### ISSUE TITLE
Copy change in Death form

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3064]
**Bug description:**
Copy change in Death form

**Steps to reproduce:**
1. Declare a death event
2. Go to death details page
3. Go to Attaching supporting document page

**Actual result vs Expected result:**
1. In death details page, "Where did the death occur?" should be "Place of death"
2. In  Attaching supporting document page, "Proof of informants ID""  & " Proof of deceased ID" should be "Proof of deceased's Identity" & "Proof of informant's Identity"

 **Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by jpye-finch** [comment]
Updates made. bugs fixed

**Comment by azantor64** [comment]
![2022_plans](https://user-images.githubusercontent.com/70468099/171576976-8f023ff0-b7d2-47b1-aed5-dee893b0de37.png)

**This is passed** but 
see next comment

**Comment by anny320** [comment]
@jpye-finch please review

**Comment by jpye-finch** [comment]
closing
