### ISSUE TITLE
Console error when search for an invalid health institution

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3065]
**Bug description:**
Console error in health institution when search for an invalid health institution.

**Steps to reproduce:**
1. Declare a Birth event/ Death event
2. Go to child details/ Death details page
3. In place of delivery/ Place of death Select Health Institution
4. In location select any thing which is not valid

**Actual result:**
![when health institution not found error.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/3ad4fa9d-43d7-44e8-8fe9-a6cee70527a2)

**Expected result:**
should not show error in console

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by saima-alam** [comment]
@anny320 This is working as expected. This can be closed. 

![image](https://user-images.githubusercontent.com/105625699/169971420-b0d3cf99-20c6-4d6a-b59e-2087d0e8d34f.png)

**Comment by anny320** [comment]
completed

**Comment by azantor64** [comment]
Actual result = Expected result: can be closed. @anny320 \
https://www.loom.com/share/c84e728097fc4f3ebc31bae57c82c591

**Comment by anny320** [comment]
completed

**Comment by anny320** [comment]
completed
