### ISSUE TITLE
In workqueue, Icon and name are not center alligned in the row and  vertical allignment issue

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3070]
**Bug description:**
In workqueue, Icon and name are not center alligned in the row. There is also  vertical allignment issue.  The column names should also be bold.

**Steps to reproduce:**
1. Login as any user
2. Go to any tab
3. See the workqueue

**Actual result:**
1. In workqueue, Icon and name are not center alligned in the row. 
![image (17).png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/99eaffd5-5603-4124-bb08-3222800191f7)
2. Vertical allignment not correct
![image (18).png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/0fba87f0-d83c-4313-9b50-506601bb9358)
3.  The column names are not bold.
![image (20).png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/9475f3d4-31ab-4a79-b194-b52b63ec49b4)

**Expected result:**
1. In workqueue, Icon and name should be center alligned in the row. 
2. Vertical allignment needs to be fixed
3.  column headings should use the font style bold14

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by anny320** [comment]
issue currently resolved![Screenshot 2022-06-06 at 16.46.29.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/c5c2a524-3525-4ef2-b8c6-040b939a0ade)
