### ISSUE TITLE
Copy for No records Requires Update is incorrect

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3071]
**Bug Description:**
Copy for No records Requires Update is incorrect. Showing "No declaration Sent for Updates"

**Steps to reproduce:**
1. Login as Field agent
2. Go to Requires Update when there is no data

**Actual result:**
Showing "No records Sent for Updates"

**Expected result:**
Should be "No records Requires Update "

**Screenshot:**
![image (19).png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/89185908-18fb-4e35-ab22-e2ffa4524f1f)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by emon-swe-sust** [comment]
Solved in current version.
![Screenshot from 2022-05-17 12-16-37](https://user-images.githubusercontent.com/43314141/168741921-6aa0a9eb-068c-4894-aa15-01c68841cf5d.png)

**Comment by Fariha-Amin** [comment]
@anny320   retest passed and can be closed

Retest ScreenShot:

![Capture5](https://user-images.githubusercontent.com/105624748/170423150-41fd9667-4d4f-419e-ade5-7c796f1249cb.PNG)

**Comment by anny320** [comment]
completed

**Comment by anny320** [comment]
completed

**Comment by SyedaAfrida** [comment]
@anny320 This bug is reappearing again

**Comment by euanmillar** [comment]
@jpye-finch over to you.  I think this is fine ...

**Comment by euanmillar** [comment]
Can we check the empty state here please?  Something has gone wrong.

**Comment by SyedaAfrida** [comment]
@anny320 passed again
![no record require updates](https://user-images.githubusercontent.com/94350336/172803771-2608c76c-9336-4655-b0e0-9f2b8118a2c1.png)

**Comment by anny320** [comment]
completed
