### ISSUE TITLE
Password reset page back button doesn't work

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3078]
*Bug:*
Password reset page back button is disable if an user want to back to the page 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://login.farajaland-qa.opencrvs.org/
2. Click on Can't login
3. click on my password
4. Give field agen phone number and continue
5.Enter verification code 
6. Enter security questions answer
7. click on Password reset back button

**Expected behaviour**
Reset back button should work

**Actual Result**
I![reset button.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/3b5e7833-7cfd-4afa-9d5b-9e5a6750df0f)
https://images.zenhubusercontent.com/91778759/0e3fe47f-461e-4886-b6dc-2c365c6614c0/library___loom___16_may_2022.mp4

**Comment by azantor64** [comment]
https://user-images.githubusercontent.com/70468099/170266679-ee2d5cc5-169e-4279-b157-0e334a817e08.mp4

it's working. passed. can be closed. @anny320

**Comment by azantor64** [comment]
https://user-images.githubusercontent.com/70468099/170450405-1af6dc96-379e-447d-83dc-e3d74784304a.mp4

Tested on Config environment. passed. can be closed. @anny320

**Comment by anny320** [comment]
completed
