### ISSUE TITLE
Column name not correct in Ready for review of registrar

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3081]
**Bug description:**
Column name not correct in Ready for review of registrar

**Steps to reproduce:**
1. login as registrar
2. Go to ready for review
3. Check the column

**Actual result:**
Showing name column twice

**Expected Result:**
should be "Event"

**Screenshot:**
![bug in header.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/925cb441-40ad-4ccb-8828-641d23a8d0e4)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by Fariha-Amin** [comment]
@anny320   Not only for registrar....This problem is also showing for registration clerk.

**Comment by azantor64** [comment]
![Selection_009](https://user-images.githubusercontent.com/70468099/172148007-15600495-253c-4bc7-8f71-7aded40fe080.png)

![oho](https://user-images.githubusercontent.com/70468099/172148200-3f705c0a-7cea-4e6a-ab16-cbee84c6c64a.png)
passed. can be closed. @anny320

**Comment by anny320** [comment]
completed
