### ISSUE TITLE
System crashes after click on duplicate application review  button

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3085]
**Describe the bug**
As a registrar after click on duplicate application review button,shows that this page couldn't be found.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://register.farajaland-qa.opencrvs.org/
2. log in as FA and create same two application 
3.Navigate to Ready for review 
4. Download the duplicate application 
5. Click on Review

**Expected behaviour**
Declaration page should be available

**Actual Result**
![image.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/24639f2e-27b6-4aa3-98ad-229ad007f5d5)

https://user-images.githubusercontent.com/70468099/168751728-79dd25fa-59c3-4105-a74c-5c6935612780.mp4

**Comment by anny320** [comment]
blocked pending design of how to manage the conflicts to be shared by @jpye-finch

**Comment by euanmillar** [comment]
Will be fixed by: https://github.com/opencrvs/opencrvs-core/issues/3112

**Comment by anny320** [comment]
completed
