### ISSUE TITLE
Time period for audit can't be set in the user profile page

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3086]
**Description:**
In user profile page, time period for audit can't be set. The calender can't be seen in full zoomed view, needs to be zoomed out to be able to see the calender.

**Steps:**
1. Login as a system/national system admin
2. goto team
3. select any user and goto profile page
4. click on the calender icon in the audit option

**Actual Result:**

Calender is opened but can't be seen. Only visible if zoomed out to 50%. 

**Expected Result:**
Should be able to see the calender and select time period for audit.

**Screen recording:**
https://www.loom.com/share/d3b10a43cecd41e7a3a4fcb27001af59?sharedAppSource=personal_library

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**
Username: e.mayuka
password: Welcome321

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by euanmillar** [comment]
We need to discuss with Ed on Monday about User Audit

**Comment by euanmillar** [comment]
Will be fixed by disabling user audit links in this release: https://github.com/opencrvs/opencrvs-core/issues/3271
