### ISSUE TITLE
cannot input phone number from Can't login page and team page when try to create new user

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3087]
**Bug description:**
1. In  can't login when clicked forgot password / username, it is not taking any input in phone
number
2. In team page, when try to create a new user, all phone numbers showing invalid

**Steps to reproduce:**
1. Go to login page
2. Click cannot login
3. Click "My username"
4. Enter Phone number and observe
5. Login as National system admin
6. Go to team
7. Click New user
8. Try to fill up the phone number 
9. Continue

**Actual result:**
1. for Can't login page, It is not taking any input
![bug3.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/12408aa6-ed71-41a0-8778-c79b2741d155)

2. For team page, it is showing error
![bug1.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/dd757298-7944-4e0a-bf6f-1a37cc889de1)

**Expected result:**
1) for Can't login page, It should be taking input
2) for new user, should be able to create new user with new phone numbers

**Tested on:**
https://login.farajaland-config.opencrvs.org/

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed![Screenshot_20220526-145301_Messages.jpg](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/af890dcd-368a-4125-89f0-50c48f484981)
![team.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/84d69cac-4488-4a82-94ba-96501231207c)

**Comment by anny320** [comment]
completed
