### ISSUE TITLE
Same phone number can't be used by different users

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3089]
**Description:**

Same phone number can't be used by different users. But when system admins tries to change a users phone number or create a new user with a number, that matches with an existing phone number of another user, it doesn't give any error message.

**Steps for edit phone number with non-unique number::**
1.Login as system admin
2.goto team
3.click three dot option of any user
4.click edit details option and goto change phone number link
5.Change the phone number with a number that is used by another user

**Steps for creating new user with non-unique phone number:**
1.Login as system admin
2.goto team
3.Click new user option to create a new user
4.give phone number a non-unique number used by another existing user

**Actual Result:**

No error message is shown. Takes input non-unique number.

**Expected Result:**

Should show a error message like "This number is used by another user".

**Screen Recording:**
For Edit:    https://www.loom.com/share/b706d9567d4a4258bffd8aa0765683ff
For New:   https://www.loom.com/share/5c41b9db22044b1cac1f9e93609d2697

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**
Username: e.mayuka
password: Welcome321

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by anny320** [comment]
to be retested in config @SyedaAfrida @Fariha-Amin before we close ticket? ideally should be working ok, its not possible to use one number for multiple accounts

**Comment by Fariha-Amin** [comment]
@anny320  This feature is working now and can be closed. I have retested it by creating users with same phone number and also edit a users phone number to an existing one. Also tested for two users of different locations. For all scenarios feature is working well. 


**Retest Screenshots:**

![new one](https://user-images.githubusercontent.com/105624748/170667510-52307ff4-9862-4af6-be59-67c64ecde787.PNG)
![new two](https://user-images.githubusercontent.com/105624748/170667516-1ec491ff-e5e7-4dc6-917b-a247ffd93ade.PNG)
![new_two_edir](https://user-images.githubusercontent.com/105624748/170667518-57eb87fb-7e3b-4ae9-bdbe-e45f4d84fbc7.PNG)
![new loc one](https://user-images.githubusercontent.com/105624748/170667530-ce7f48fb-d47e-4bab-a1bf-a6ce1da9891d.PNG)
![new loc edit](https://user-images.githubusercontent.com/105624748/170667540-c135a9d7-b48e-4106-ac8d-391fc359e283.PNG)

**Comment by anny320** [comment]
completed
