### ISSUE TITLE
"How to configure a certificate?" link is disabled in the Certificates templates page

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3092]
**Description:**
On the Certificates templates page, the 'How to configure a certificate?' link is disabled. This link is showing in grey color and is not clickable. 

**Steps:**

1. Log in as a national system admin
2. Click on config > Certificates "How to configure a certificate?" link
3. Observe the "How to configure a certificate?" link

**Actual Result:**

- "How to configure a certificate?" link is disabled  

**Expected Result:**

- "How to configure a certificate?" link should be enabled and clickable to users

**Screenshot:**
![image](https://user-images.githubusercontent.com/105625699/168810498-3ddc7f99-4493-42a4-a122-9d0478715609.png)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**

- Username: jonathan.campbell (National System Admin)
- password: test

**Desktop:**

- OS: Windows 10
- Browser: Chrome

**Note:** The requirement is not clear that where user will be navigated after clicking on the "How to configure a certificate?" link

**Comment by anny320** [comment]
This is a duplicate to #3001 will close this ticket
