### ISSUE TITLE
While uploading invalid registrar signature image error message should be only png supported 

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3095]
**Description:**
While uploading invalid extensions image for registrar signature , error message is image/png supported only

**Steps:**
1.Login as system admin
2.goto team
3.click create new user option and select registrar in role
4.fill all required fields and click continue
5.try to upload signature with .jpg/.jpeg extension
6. Click upload
7. See error message

**Actual Result:**

Notification is shown "Image/PNG supported only". 

**Expected Result:**
png supported image only

**Screen Recording:**
https://www.loom.com/share/8e6a30d865864350bd7e9430857a690c

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username and password used:**

Username: e.mayuka
Password: Welcome321

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by Fariha-Amin** [comment]
@euanmillar  Error message is visible  when user clicks continue button without uploading any file . But Error message is not shown while invalid file type is uploaded.  will be little difficult for the user to understand why file is not being uploaded,  without any error message in time of uploading.

**steps to reproduce:**
1.Login as system admin
2.goto team
3.click create new user option and select registrar in role
4.fill all required fields and click continue
5.try to upload signature with .jpg/.jpeg/.pdf extension
6. Click upload

**Screen Recording:**

https://user-images.githubusercontent.com/105624748/171624477-c7cd2ada-e2d4-4257-a602-682ffd854850.mp4

**Comment by euanmillar** [comment]
Solution should be to show the error message regardless

**Comment by yeasinhossain-dsi** [comment]
It is already done & in the develop branch

**Comment by euanmillar** [comment]
@yeasinhossain-dsi are you sure?  The issue is about if uploading a JPG then showing the message too.  I'm not sure it is in develop already.  Can you show me the line of code please?

**Comment by Fariha-Amin** [comment]
@anny320  passed, can be closed

Retest Recording:

https://user-images.githubusercontent.com/105624748/172538941-ceb104d7-28e0-404c-bd7a-fe839ee4efb0.mp4

**Comment by anny320** [comment]
completed

**Comment by anny320** [comment]
completed
