### ISSUE TITLE
In performance, stats data not correct when filtered for provinces

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3097]
**Bug description:**
In performance, stats data not correct when filtered for provinces. In Sulaka province, there is one district also named Sulaka. In Sulaka district, Sulaka province, there is one office and 1 registrar. But when filtered to Sulaka Province, there is no office & registrar. Since Sulaka district is a part of Sulaka province, it should show same stats value

**Steps to reproduce:**
1. Login as National system admin
2. Go to Performance 
3. from location filter, select any district that has office and registrar, like Sulaka district, Sulaka province
4. Observe Stats value
5. from location filter, select Province from that district
6. Observe Stats value

**Actual result:**
In performance, stats data not correct when filtered for provinces. District values are not showing for province

**Expected result:**
province stats should add up all district stats value within that province. According to the recording  Sulaka province, should show 1 registration office, 1 registrar

**Screen recording:**
https://images.zenhubusercontent.com/91778759/17498213-4c82-462f-a5c0-589877c57f25/province_stats_not_correct.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by SyedaAfrida** [comment]
@anny320 This bug is fixed and can be closed
![3097 fix 2](https://user-images.githubusercontent.com/94350336/173296877-efcc52f8-bcc2-489c-b860-260bfaa82a27.png)
![3097 fix1](https://user-images.githubusercontent.com/94350336/173296887-1dd62749-7ae7-4629-84c5-e60cf10f661f.png)

**Comment by anny320** [comment]
completed
