### ISSUE TITLE
In team, allignment of signature attachment is not correct in review page of creating new user

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3098]
**Bug description:**
In team, allignment of signature attachment is not correct in review page of creating new user

**Steps to reproduce:**
1. Login as local/ national system admin
2. Go to team
3. Click New user
4. Fillup all information and set role as registrar > Continue
5. Attach signature> Continue
6. Go to review page and observe

**Actual result:**
In team, allignment of signature attachment is not correct in review page of creating new user

**Expected result:**
should be just below the attachment title

**Screenshot:**
![sign bug.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/9ff69fa0-f4d8-4774-967c-5a8e146f66df)

**Tested on :**
https://login.farajaland-qa.opencrvs.org/

**Comment by Fariha-Amin** [comment]
@anny320  passed , can be closed

**Retest SS:**
![Capture](https://user-images.githubusercontent.com/105624748/172310613-de889925-de9c-44ba-ac63-078578dc1845.PNG)

**Comment by anny320** [comment]
completed
