### ISSUE TITLE
In performance, Stats and Completeness rates option should be hidden for all offices

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3100]
**Bug description:**
In performance, Stats option should be hidden for all offices

**Steps to reproduce:**
1. Login as any user other than field agent
2. Go to performance
3. Click Location filter
4. Select any office
5. Observe Stats and Completeness rates

**Actual Result:**
Showing Stats and Completeness rates  in Performance when filtered for office

**Expected Result:**
should not show Stats and Completeness rates in Performance when filtered for office

**Screenshot:**
![office stats.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/ffae62ad-d4b6-46e0-86c5-2652e6cb3584)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by anny320** [comment]
completed
