### ISSUE TITLE
Wrong certificate is showing when user update a new certification template

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3108]
**Bug Description:**
If National System Admin uploads a new birth certificate template, the birth certificate template shows when the registration agent wants to print a death certificate. If the user reloads the screen then, the death certificate template appears but then the death certificate template shows while printing the birth certificate. f user reloads again the birth certificate shows but then the death certificate again shows the birth certificate template.

**Steps:**
1. Log in as a National system admin
2. Click on Config > Certificates
3. Click the 3 dot menu beside Birth Certificate
4. Upload a new birth certificate template
5. Log out from the application
6. Login with a Registration agent
7. Click on the 'Ready for print' option
8. Download a death certificate > Click on Print

**Actual Result:**

- Birth certificate template is showing instead of the death certificate. After refreshing the screen 
death certificate is showing. Then after that If the user tries to print a death certificate, it shows the birth certificate template. After refreshing birth certificate appears but then the printing death certificate shows the wrong (birth certificate) template. 

**Expected Result:**

- The correct template should be shown for the birth and death certificates. When printing a birth certificate, it shows what was uploaded in the certificate template for the birth certificate and When printing a death certificate, it should show what was uploaded in the certificate template for the death certificate.

**Screen recording:**
https://www.screencast.com/t/jnBWh6xRffQ

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**
Username: jonathan.campbell 
password: test

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by anny320** [comment]
Completed

**Comment by saima-alam** [comment]
@anny320 This is working as expected. This can be closed. 
Reference video: https://www.screencast.com/t/zjMk4SMq
