### ISSUE TITLE
 Pagination should be added for user audit page

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3111]
**Bug Description:**
On the user audit page, pagination is not showing according to requirements.

**Steps:**
1. Log in as a National system admin
2. Click on Team
3. Select an address
4. Click on a user name
5. Observe the audit data

**Actual Result:**

- Pagination is not showing according to the requirement of table view in Figma

**Expected Result:**

- Pagination should be according to the pagination of the table view that is given in Figma.

**Figma Link:** https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=5796%3A18097 

**Screen recording:**
https://www.screencast.com/t/Uymnur0tYcwX

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**
Username: jonathan.campbell
password: test

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by anny320** [comment]
linked to 3271

**Comment by jpye-finch** [comment]
close. will be fixed as part of User Audit designs and epic ticket
