### ISSUE TITLE
In performance, the count for certificate issue total should not increase, if same certificate is printed multiple times

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3113]
**Bug description:**
In performance, the count for certificate issue total should not increase, if same certificate is printed multiple times. Currently it is increased , for printing multiple times. 

**Steps to reproduce:**
1. Login as registration agent/ registrar
2. Go to ready to print
3. Choose any record> Click Print
4. Select any option > Continue
5.  Click Confirm & Print
6.  Go to performance and observe Certificate issues value
7. Click search
8. Search for the same record with name/ tracking id
9. Print that the certificate again
10. Go to performance and observe Certificate issues value

**Actual result:**
Total & Certification rate values is changed when same certificated is printed multiple times. For this reason the percentage gets more than 100%

**Expected result:**
Total & Certification rate values should not change, when same certificated is printed multiple times. This would not let percentage to be more than 100%

**Screenshot:**
![cer rate.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/6806de01-f1da-47e9-9cbc-549f1aebc9ea)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
Not correct. @eduffus said this was not an issue.

**Comment by Fariha-Amin** [comment]
@anny320  passed, can be closed. 
**Retest Video:**

https://user-images.githubusercontent.com/105624748/172165300-08d6073b-5352-476d-88df-aea40f024675.mp4

**Comment by anny320** [comment]
completed
