### ISSUE TITLE
The empty state (grey box) for summary data is not available in audit record page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3117]
**Bug description:**
the empty state (grey box) for summary data is not available in audit record page

**Steps to reproduce:**
1. Login as any user other than local/ national system admin
2. Go to any tab
3. Click any record which is not downloaded

**Actual result:**
PII before download is empty. nothing showing.

**Expected result:**
PII before download should be  empty state (grey box)

 **Screenshot:**
![image (21).png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/b87e67ff-2acc-494b-9818-1e5b4ceb61ec)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by anny320** [comment]
issue resolved
