### ISSUE TITLE
Replace Notification with FloatingNotification everywhere

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#312]
Notification is a very old component.  All instances must be replaced with FloatingNotification
![Screenshot 2022-02-14 at 10 23 19](https://user-images.githubusercontent.com/3169954/153846889-ce5c56c0-3eaf-4ab5-b0e4-4003807e5701.png)

If you change profile image, then you see the correct Notification style

Also please look at refactor of the styles and the callback naming convention is a bit strange

**Comment by euanmillar** [comment]
This component should be deleted.  We should only use ToastNotification and it should be moved into component lib.

**Comment by euanmillar** [comment]
We have an old component library.  react-styleguidist is losing popularity against react-storybook.  It could become difficult to maintain and it isnt very useful at present.  Also many of the styles in it are outdated, replaced by new fonts and colors.  A big tidy up would be useful and perhaps a migration to react-sstorybook.

**Comment by azantor64** [comment]
@anny320 , this ticket is waiting for review.

**Comment by anny320** [comment]
completed
