### ISSUE TITLE
Refactor Field Agent WorkQueue to behave similarly to Registrars

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3120]
Field Agent Sent for review should ideally be deprecated in favour of reusing Registration Agent/Clerk's Sent for approval.  The only difference Euan can see is the color of the icon and the copy.  If we do this, we dont have the duplication problem, and you can download and see history etc.

- [x] In OfficeHome, refactor out syncWorkQueueFieldAgent so that FieldAgent's Sent for review and Requires Updates uses ListSyncController and redux data - 3
- [x] Refactor RequiresUpdateFieldAgent to get data from OfficeHome rather than a query - 2
- [x] ListSyncController needs to support FieldAgents Requires Updates & Sent for Review query - 2
- [x] Refactor Registration Agent's Sent for approval to cater for the yellow icon and copy for Field Agent's Sent for review case. - 1

This enables the download button and record audit for Field Agent on both Sent for Review and Requires Updates pages.

- [x] However all the links in record audit to view changes and click through to RecordAudit are disabled.  All the action buttons to Review are disabled. - 2

**Comment by SyedaAfrida** [comment]
@anny320 completed testing this ticket and raised 3 bug- #3377, #3378,  #3379

**Comment by anny320** [comment]
closed
