### ISSUE TITLE
Default Profile Image should be shown while offline

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3121]
Description:
Default Profile Image should be shown while offline. But not shown for any user except for field agent.

Steps:
1.Login as any user whos profile image is not set (except field agent).
2. observe profile image, initials of first and last name should be shown while online & when profile image is not set
3. Go offline
4.  observe profile image while offline

Actual Result:

Initials of first and last name is shown, same as online & when profile image is not set

Expected Result:

Default Profile Image should be shown while offline

Screen Recording:
https://www.loom.com/share/2e016f3614fc4fecbe9e56445d1702b2

Tested on:
https://login.farajaland-qa.opencrvs.org/

Username and password used:

Username: felix.katongo
Password: test

Desktop:
OS: Windows 10
Browser: Chrome

**Comment by Fariha-Amin** [comment]
@anny320  This problem is no longer appearing and can be closed.

**Comment by Fariha-Amin** [comment]
@euanmillar  no head icon is appearing offline, I retested again , initials of name is being shown while offline. I tried this for all users.

Retest Recording:

https://user-images.githubusercontent.com/105624748/170643706-f7382d39-101b-4ad2-bc98-2a4df4d27477.mp4

**Comment by euanmillar** [comment]
Let me explain in a different way.  We use a webservice when you are online to generate the initialed profile image. If you have ever been online and received that image, then it is saved in your browser cache and it becomes the default as long as you do not clear your cache.  If there is a page of users you have not seen yet, then those profile images with initials will not be generated.  If you were offline when you viewed that page for the first time, then you would see the head svg icon.  In a sense, what you are experiencing is good.  You have the initialed image even when offline.  I think that this can be closed as passing.

**Comment by anny320** [comment]
ticket will be closed as no further action will be taken.
