### ISSUE TITLE
National registrar option not showing in list in Sources of applications

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3123]
**Bug description:**
National registrar option not showing in list in Sources of applications

**Steps to reproduce:**
1. Go to any user other than field agent
2. Go to performance
3.  Observe  list in Sources of applications

**Actual result:**
do not  show National Registrar option

**Expected Result:**
should show National Registrar option

**Screenshot:**
![nat reg.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/edce4fa0-fc36-4d7c-af83-558ea1a69e9e)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by Fariha-Amin** [comment]
@anny320  Solved, can be closed

**Retest SS:**
![Capture](https://user-images.githubusercontent.com/105624748/172320488-76f78d9c-a20b-4407-9a7e-e267c1b6acc6.PNG)

**Comment by anny320** [comment]
completed
