### ISSUE TITLE
As a user I want to search for a record offline 

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3125]
### Description
- adds Alert to search results if offline

### Acceptance criteria

GIVEN I am offline 
WHEN I search for a record
THEN show the Alert message. "You are offline. The search results are only local.... "

GIVEN I am offline 
WHEN I search for a record
THEN return any results from my work-queues

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7537%3A14932

### Dev tasks

- [ ] Task 1

**Original bug below**

Description:
Search from within the workqueue is not successful while offline. Only successful while online.

Steps:
1.Login as registration clerk
2. Goto offline
2. Search application with tracking id/name/reg number/phone number while offline

Actual Result:

Search from within the workqueue is not successful while offline.

Expected Result:

Search from within the workqueue should be successful while both online and offline

Screen Recording:
https://www.loom.com/share/3efa5f99760c4c02aab050f3fcbe433c

Tested on:
https://login.farajaland-qa.opencrvs.org/

Username and password used:

Username: felix.katongo
Password: test

Desktop:
OS: Windows 10
Browser: Chrome

**Comment by euanmillar** [comment]
In the future, we will allow searching of any cached application in IndexedDB but we would still need some kind of offline state if no records are found offline

**Comment by euanmillar** [comment]
@jpye-finch  How would the user know that they have only been searching offline downloaded applications, rather than searching the national database?  Should there not be some kind of indication of this?  I think it needs a little bit of advanced search design.

**Comment by jpye-finch** [comment]
@anny320 have update ticket to use the issue template. 

We need to define the copy. I welcome direction on this @euanmillar @eduffus

**Comment by euanmillar** [comment]
@jpye-finch @anny320 @eduffus how about .... "You are currently offline and therefore you cannot search nationally. These results are records from your local browser's cache."

**Comment by euanmillar** [comment]
You can only search page 1 of any workqueue

**Comment by euanmillar** [comment]
Closing as this is adding no value
