### ISSUE TITLE
Form radio buttons should be Checkbox's

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3126]
**Describe the bug**
- radio buttons still used instead of checkbox.

Update Yes/No Radio button on Mother's and Father's details pages, to:

[ ] Mother's details are unavailble
[ ] Father's details are unavailble

**Expected behaviour**
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=2220%3A48002

Form flow:
https://www.figma.com/file/7AYxLlYTpY4RioSTIt0PbG/Fajarland-Birth-Declaration-Forms?node-id=0%3A1

**Comment by euanmillar** [comment]
@jpye-finch  Should the ticket not also mention "Same as X usual place of residence" for QA purposes?  Cause of Death checkbox issue has already been raised in bug: #3926.  Linking it to that one so we can find easy.

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![mob birth](https://user-images.githubusercontent.com/94350336/202143649-87723579-f323-4032-a091-a31e79e3a0c6.png)

https://user-images.githubusercontent.com/94350336/202143806-80332dca-310d-4bb7-a7ef-b6c7be6f3af8.mp4

**Comment by anny320** [comment]
completed
