### ISSUE TITLE
Offline state for performance and teams

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3130]
### Description

- adds offline state for Performance and Team

### Acceptance criteria

GIVEN I am on the Performance page
WHEN I am offline 
THEN [show the offline line state](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=6040%3A111008)

### Dev-tasks

- [x]  On the performance pages if you are offline, show the No connection text and icon
- [x] On the Team pages we need to disable links if offline, and show a graceful error such as this icon and no connection however you see fit.  No need to align to any design

**Comment by SyedaAfrida** [comment]
@anny320 This ticket has passed and can be closed
![Performance error](https://user-images.githubusercontent.com/94350336/171614886-4cf95659-bf98-41b9-9052-1a798b73e5a4.png)
![team offline](https://user-images.githubusercontent.com/94350336/171614911-b2dfd68d-7964-4399-82cb-31a3b970b7b3.png)

**Comment by SyedaAfrida** [comment]
When user goes from offline to online in performance, System crashes

https://user-images.githubusercontent.com/94350336/171616182-e93e667c-cf3f-4f49-8111-65e5b3e4f421.mp4

**Comment by SyedaAfrida** [comment]
This bug is not fixed yet @sadmananik @anny320

**Comment by SyedaAfrida** [comment]
@sadmananik @anny320 the offline state of performance page is not properly showing, thus also creating issue when go online. At the beginning there is separate block in offline. But when switch tab and return to performance there is one single block.

**At first:**
![sadman1](https://user-images.githubusercontent.com/94350336/172348859-6bdaf51d-3f5e-44d6-a06f-dcb82e10f65f.png)

**Later after changing tab:**
![sadman2](https://user-images.githubusercontent.com/94350336/172348853-ebc94eb6-454b-427e-b6a8-9adfcf92a3e2.png)

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![per](https://user-images.githubusercontent.com/94350336/173010183-0fb00188-83a8-4bf9-9e9a-935d6315edc2.png)

**Comment by anny320** [comment]
completed
