### ISSUE TITLE
In performance, if Health system (integration) is 0, then should not show this in the list of Source of application 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3131]
**Bug description:**
In performance, if Health system (integration) is 0, then should not show this in the list of Source of application 

**Steps to reproduce:**
1. Login to any user other than field agent
2. Go to performance
3.  Observe Health system (integration) 

**Actual result:**
showing Health system (integration) option even if if Health system (integration) is 0

**Expected result:**
if Health system (integration) is 0, then should not show this in the list of Source of application 

**Screenshot:**
![nat reg.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/85300f40-afa1-4db0-ba6a-df90b4ffaf4d)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by jpye-finch** [comment]
@anny320 this is fine. I don't consider it a bug.
