### ISSUE TITLE
In performance, no data is showing when location is an office

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3132]
**Bug description:**
In performance, no data is showing when location is an office. And for office Completeness bloc should be hidden

**Steps to reproduce:** 
1. Login as any user other than field agent
2. Go to Performance
3. Select location as office and observe

**Actual result:**
1) all values are 0%
2) Completeness block is showing

 **Expected result:**
1) should show actual values. If there is only 1 office in a district then all the values should be same as district
2) should hide completeness block

**Screenshot:**
![office.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/267b3057-0435-4b05-b9cf-8da9315c0575)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by jpye-finch** [comment]
@anny320 This is a very high priority bug!

**Comment by anny320** [comment]
completed
