### ISSUE TITLE
Default message should be provided when there is no date of event given in record audit page

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3134]
**Description:**
Default message should be provided when there is no "date of event" given in record audit page 

**Steps:**
1.Login as any registration agent/registrar
2. observe record audit page from in progress/ready for review/requirs update 
3. observe "date of event"

**Actual Result:**
column is blank when there is no data  provided for date of event

**Expected Result:**

A default message like "No date provided" should be provided in red colour
**ScreenShot:**
![no](https://user-images.githubusercontent.com/70468099/169539481-368b5d5d-1062-4cc7-a96c-e80ab3c08dc0.png)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username and password used:**

Username: felix.katongo
Password: test

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by jpye-finch** [comment]
Fine empty in my opinion. If not:

'No date of birth'
'No date of death'

**Comment by euanmillar** [comment]
@jpye-finch I was wrong.  If you click the item you can see that we have a date created for this in Record Audit.  I think we need to show that date here

**Comment by euanmillar** [comment]
@jpye-finch says "fine if empty".  We will take that and this ticket can be closed.

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Comment by anny320** [comment]
closed
