### ISSUE TITLE
Registration agent or Field agent can't be created in an empty office

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3139]
**Describe the bug**
There is no option to create/select a RA or Field agent as National Sys admin in an empty office
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://login.farajaland-qa.opencrvs.org/
2. Log in as National Sys Admin
3. Navigate to team and select new office
4. Try to create Field agent or RA as new user
**Actual Result**
![image.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/49dc0359-da57-4bce-afcd-11ee36be612b)

**Expected behaviour**
There should be Field agent and Registration agent to select to create that user

**Comment by soumita-dsi** [comment]
@azantor64 this has been already fixed. Could not reproduce it.

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/172827151-6c2dbf6c-86fc-4ef1-aacd-9d3f9e349187.png)
Fixed. @anny320 
Can be closed

**Comment by anny320** [comment]
completed
