### ISSUE TITLE
Change button on death form to read Save and Exit instead of save

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3140]
**Describe the bug**
Change button on death form to read Save and Exit instead of save
**To Reproduce**
Steps to reproduce the behaviour:
1. login as field agent (go offline)
2. start a death application form, follow the steps to select informant and add contact
3. attempt to exit, you only see save instead of Save and Exit

**Expected behaviour**
Change button from save to save and exit
**Screenshots**
![Screenshot 2022-05-20 at 13.40.11.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/1313422d-f7ea-425a-86f0-2842946b227d)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 
 - Browser chrome status offline

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by Fariha-Amin** [comment]
@anny320  solved, can be closed

**retest SS:**
![d](https://user-images.githubusercontent.com/105624748/171611873-fea395ac-43da-4906-ac6c-ec27cb749848.PNG)

**Comment by anny320** [comment]
completed
