### ISSUE TITLE
NID Error message not clearing in death form in offline status when 9 digits are entered

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3141]
**Describe the bug**
Login as field agent, go offline
start a death declaration
follow the  prompts until the deceased details page, when entering the validator, the error message is  not clearing when 9 digits are entered.

Also clear error in review page since its affecting submitting of a complete death declaration

**Expected behaviour**
error message should clear once 9 digits are entered
**Screenshots**
![Screenshot 2022-05-20 at 19.36.45.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/69ed8048-a385-4460-87a3-df7fce8abec0)

![Screenshot 2022-05-20 at 19.58.33.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/691357f5-09bb-4773-82f0-2370d2db9498)
**Desktop (please complete the following information):**

 - Browser chrome (offline status)
 -
**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by SyedaAfrida** [comment]
@anny320 this is not a bug. Previously NID pattern was changed from application config. You can retest it now and close this ticket

**Comment by anny320** [comment]
Closef
