### ISSUE TITLE
Form Config UI: Canvas scroll behaviour

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3155]
**Describe the bug**
- content scrolls within canvas
- the canvas should scroll off screen

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to form config
2. scroll in the centre canvas
3. Not the content scrolls within

**Expected behaviour**

The canvas scrolls of the page
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/c87ece36-2753-4f26-a560-179761d38ab7)

**Screenshots**
Current behaviour
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/5ae153e3-6942-4847-8f78-c55ad321300d)

**Comment by anny320** [comment]
completed
