### ISSUE TITLE
Form Config: missing tooltips

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3156]
**Describe the bug**
- missing tooltip for Content Keys.
'Use these keys to update copy for this field'

- missing tooltip for Cert handlebars 
'Use this handlebar in your certificate SVG to show this data field'

- missing toooltip for Required for registration 
'Select if this field is mandatory to complete registration'

**Expected behaviour**
- ![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/e98ca915-d3b9-494c-a78b-92d7fece17db)

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/99f662bb-6cd4-4923-af83-673b0866787a)

**Comment by Fariha-Amin** [comment]
@anny320  not fixed for "required feild"

**retest ss:**

https://user-images.githubusercontent.com/105624748/173049522-0766bd4d-97da-4d87-b343-dcf623b7b33b.mp4

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

Retest Recording:

https://user-images.githubusercontent.com/105624748/174031301-677791cd-0d44-436a-84a4-abeaced9ccaa.mp4

**Comment by anny320** [comment]
completed
