### ISSUE TITLE
Form Config: Missing settings and save button on Settings

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3157]
**Describe the bug**
- toolbar changes in Settings
- setting button and save button disappear

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to form config
2. Click on settings cog
3. Note the toolbar changes

**Expected behaviour**
The toolbar remains the same

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/325019da-bbd1-4d6a-b1c2-bb40d6369909)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by anny320** [comment]
recommend closing this ticket

**Comment by Zangetsu101** [comment]
I don't get why we should have the settings icon in the toolbar when we are already in the settings page?

**Comment by euanmillar** [comment]
Yes lets close it for now @jpye-finch

**Comment by anny320** [comment]
closed
