### ISSUE TITLE
Form Config UI: CircleButton not used

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3158]
**Describe the bug**
- CircleButton not used
- icon colour wrong

**Expected behaviour**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/dc8d25dd-89fa-4590-9571-a1fd7bb15410)

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/1ca61a75-90e1-4d7b-9d55-134e9a99869a)

**Comment by anny320** [comment]
@jpye-finch please provide more context for this ticket

**Comment by anny320** [comment]
completed

**Comment by anny320** [comment]
completed
