### ISSUE TITLE
Form config: Missing content key for No of previous births

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3159]
**Describe the bug**
- No of previous births

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/0a308d72-3ce8-48d6-821e-91d51c430b78)

![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/5a6b118f-873b-4351-9d28-f79c7e17676b)

**Comment by anny320** [comment]
completed
