### ISSUE TITLE
Form Config: Only showing content keys for options in selects. not the label

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3161]
**Describe the bug**
Missing label content key on Selects

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on a select

**Expected behaviour**
- Can see label content key and options

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/358352b9-3592-4058-b4f3-4af0ec5e6c4c)

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/172118792-7c803ea3-6e72-42ca-b070-f17db428cb71.png)

**Comment by azantor64** [comment]
![radiobutton](https://user-images.githubusercontent.com/70468099/172119456-a5e35e7d-24f2-427e-a4a8-1c96b7bc9db5.png)

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/172120907-8e9ed414-9152-4d55-8d68-d75481b6140b.png)

![image](https://user-images.githubusercontent.com/70468099/172120980-a0bda20a-528a-40bd-8cc9-667e20d3da90.png)

passed. can be closed. @anny320

**Comment by anny320** [comment]
completed
