### ISSUE TITLE
Form Config: Missing content key on radios

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3162]
**Describe the bug**
- Form radios will change to checkboxes...
- however for now the radio button label content does not show.
- just the Yes and No

List:
Do you have the father's details?
Do you have the mother's details?
Same as mother's usual place of residence? 

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on a radio button

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/0ca40bee-87a2-429b-8a3e-5b82d8a0e16d)

**Comment by azantor64** [comment]
![radiobutton](https://user-images.githubusercontent.com/70468099/172119632-105ed6c8-6147-45c4-8652-2d367f1465b5.png)

**Comment by anny320** [comment]
To be improved in the future releases
