### ISSUE TITLE
Form Config UI: Dropdown menu styling

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3163]
**Describe the bug**
- menu styling

**Expected behaviour**
Design:
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/d852176b-75ee-4b8a-9edf-78a966cf4097)
https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4385%3A3617

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/bcea3991-cbe1-4f50-abb2-ed11dfbbd713)

**Comment by emon-swe-sust** [comment]
@jpye-finch already fixed this

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/174997276-71ba0730-14dd-486b-a1f0-ed133841c96d.png)

**Comment by anny320** [comment]
completed
