### ISSUE TITLE
Form Config: no * added on custom fields on toggle of 'Required for registration'

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3164]
**Describe the bug**
- no * added on custom fields on toggle of 'Required for registration'

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a custom field
2. Toggle on 'Required for registration'

**Expected behaviour**
- a red * is added to form field
- field becomes mandatory for registration

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/b2389612-8cff-4ee1-b32b-b20b1199931a)

**Comment by euanmillar** [comment]
@jpye-finch I think this is low priority, because if you click Save on that form then the asterisk updates.
