### ISSUE TITLE
Form config: Delete does not revert back to default configuration

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3166]
**Describe the bug**
- Delete does not revert back to default configuration

**To Reproduce**
Steps to reproduce the behaviour:
1. Create some draft versions
3. Click delete
4. Confirm delete
5. Toast confirms delete..

6. The 'Configure' button then changes on the version you deleted
7. when you click Configure then form shows that version with previous edits you made
8. so nothing is deleted

**Expected behaviour**
- reverts back to default configuration
- so v0
- add you loose all previous versions
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/61449600-4078-4ce8-b909-9d8a6b9ecef3)

**Screenshots**
https://images.zenhubusercontent.com/91778759/e2edd92e-0f14-4835-9abd-ab5354e36bad/form_config_delete.mp4

**Comment by Zangetsu101** [comment]
@euanmillar is this a legitimate bug as we kinda had a discussion about this?

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/171832333-2ae78a13-3de1-48ea-b40a-e67fe11dd331.mp4

**Comment by anny320** [comment]
completed
