### ISSUE TITLE
Form config: Custom phone number * is also

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3167]
**To Reproduce**
Steps to reproduce the behaviour:
1. Add a phone number
2. Note the * is shown
3. Toggle Required for registration doesn't do anything

**Expected behaviour**
* reflects the toggle state of Required for registration

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/75ffa6f5-10ef-4672-992c-9ca0c082506c)

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![custom phone number fixed](https://user-images.githubusercontent.com/94350336/172356697-9aa20133-a0ab-4a2f-a314-a8f4154f95b3.png)

**Comment by anny320** [comment]
completed
