### ISSUE TITLE
Correct record option should not be available for registration agent in certificate preview page

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3169]
Description:
Correct record option should not be available for registration agent in certificate preview page

Steps:
1.Login as registration clerk 
2.goto ready to print and click print for any application
3.select any option in certificate collector page
4.click id verified/no id verified then click continue
5. In review certificate page click correct record

Actual Result:

Reg. Agent can click correct record button and can correct record

Expected Result:
correct record option should not be available for registration agent in certificate preview page

Screen Recording:
https://www.loom.com/share/33098cabaae749649ae56edb379e4496

Tested on:
https://login.farajaland-qa.opencrvs.org/

Username and password used:

Username: felix.katongo
Password: test

Desktop:
OS: Windows 10
Browser: Chrome

**Comment by Fariha-Amin** [comment]
@anny320  solved, can be closed

**Retest SS:**
![d](https://user-images.githubusercontent.com/105624748/171412295-109ff403-3a5d-40eb-b234-9f5451b4f200.PNG)

**Comment by anny320** [comment]
completed
