### ISSUE TITLE
user can upload affidavit and at the same time click checkbox for no affidavit in a single record

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3170]
Description:
While uploading invalid extensions image for registrar signature , error message is image/png supported only

Steps:
1.Login as registration clerk
2.goto ready to print
3.Select "someone else" as certificate collector
4.fill all required fields and click continue
5. In upload signed affidavit page, upload affidavit and also mark the checkbox saying "No signed affidavit available"
6. click continue

Actual Result:
user can upload affidavit and at the same time click checkbox for no affidavit in a single record and print application without any error

Expected Result:
user should not  upload affidavit and at the same time click checkbox for no affidavit in a single record. If user uploads affidavit checkbox should be disabled.

Screen Recording:
https://www.loom.com/share/1580c9f08eb340dda9f6f2604df57526

Tested on:
https://login.farajaland-qa.opencrvs.org/

Username and password used:

Username: felix.katongo
Password: test

Desktop:
OS: Windows 10
Browser: Chrome

**Comment by Fariha-Amin** [comment]
@anny320  passed, can be closed

**Retest Recording:**
https://user-images.githubusercontent.com/105624748/171590482-021dd188-fd76-4d49-9022-f697a344259a.mp4

**Comment by Fariha-Amin** [comment]
@anny320 passed, can be closed

Retest Recording:

https://user-images.githubusercontent.com/105624748/171591154-5430a369-9622-4da9-a206-27286c1dbdae.mp4

**Comment by anny320** [comment]
completed

**Comment by Fariha-Amin** [comment]
@anny320   issue reappearing again


https://user-images.githubusercontent.com/105624748/175016919-269a6ce7-dcce-4a8d-a10e-f50727034ef4.mp4

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Retest Recording:**

https://user-images.githubusercontent.com/105624748/175225822-a1c69899-6c7e-482c-8448-1f688f1e4349.mp4

**Comment by anny320** [comment]
completed

**Comment by anny320** [comment]
completed
