### ISSUE TITLE
Request correction page can't be found after correction any information for death application

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3171]
**Describe the bug**
As registrar when an user correct any application record and search the application show see the request correction page,then system crashes

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in as Registrar
2. Make a death application
3. Navigate to print tab 
4. Download that application and go correct record
5. Change any data and submit it
6. Now search it
7. Click on Request correction page
8. See error

**Expected behaviour**
Should show that page

![image.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/174cf058-24ad-4df2-8e49-132789e73c85)
**Actual Result**

https://user-images.githubusercontent.com/70468099/169988063-1de49bad-1391-409b-86a7-41e1e7bc512a.mp4

**Comment by atiqzaman-dsi** [comment]
Looks like the bug is fixed somehow.

**Comment by Fariha-Amin** [comment]
@anny320  passed, can be closed

**Retest Recording:**

https://user-images.githubusercontent.com/105624748/172842941-27c53ae5-cd16-4cb7-bc45-05cb775fcd65.mp4

**Comment by anny320** [comment]
completed

**Comment by anny320** [comment]
completed
