### ISSUE TITLE
Reason of application rejection is not visible from history

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3173]
Description:
Reason of application rejection is not visible from history when the reason of rejection is "duplicate declaration".

Steps:
1.Login as registration clerk
2.goto requires update
3.click an application that was rejected for "duplicate declaration" reason
4. download and goto history
5. click "rejected"

Actual Result:

Only Comment is visible, reason of rejection is not visible.

Expected Result:
Reason of rejection and the comment should be shown separately.

Screen Recording:
![Capture](https://user-images.githubusercontent.com/105624748/169804834-780f597f-f9ce-416a-82e5-565d0362ebd0.PNG)

Tested on:
https://login.farajaland-qa.opencrvs.org/

Username and password used:

Username: felix.katongo
Password: test

Desktop:
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by Fariha-Amin** [comment]
@anny320  retest passed, can be closed

retest recording:

https://user-images.githubusercontent.com/105624748/171596505-dbf1d62e-75be-4531-bf08-ce029f65d781.mp4

**Comment by anny320** [comment]
completed
