### ISSUE TITLE
Form Config: add default configuration version In Preview

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3174]
**Describe the bug**
- add line item that the 'default configuration' is In Preview

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to In Preview
2. Note that there is no line item showing the current version In Preview

Also:
1. Edit the current In Preview version eg v4. 
2. Note that the version disappears from In Preview and does not update to v0: 'Default configuration'
3. We should show that it has changed back to the default configuration

**Expected behaviour**
- when no new draft has been set to preview. [We show the default configuration is set to InPreview](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=2475%3A28545)

**Screenshots**
https://images.zenhubusercontent.com/91778759/2b61757a-5558-4718-89ee-d50ce12bb24d/edit_preview.mp4

**Comment by SyedaAfrida** [comment]
@anny320 This bug is fixed and can be closed
![fixed](https://user-images.githubusercontent.com/94350336/171830703-9eee48cc-9251-4cb8-866c-94ec50112676.png)

**Comment by anny320** [comment]
completed
