### ISSUE TITLE
Form Config: Hiding fields state not saved

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3175]
**Describe the bug**
- Hidden field state not saved it seems on Save of a version

**To Reproduce**
Steps to reproduce the behaviour:
1. Hide a field
3. Save a version
4. Edit the version
5. Note that the hidden field pill is no longer there.
6. The field is not set to be hidden 

**Expected behaviour**
- hidden field saved and set

**Screenshots**
https://images.zenhubusercontent.com/91778759/ce3cf3ab-91db-466d-82b1-a63ed6247477/hidden_fields.mp4

**Comment by Fariha-Amin** [comment]
@anny320 passed, can be closed

**Retest Recording:**

https://user-images.githubusercontent.com/105624748/172590007-99a18543-55cd-4536-8491-aa3807942140.mp4

**Comment by anny320** [comment]
completed
