### ISSUE TITLE
Application is visible in outbox even if it is  is sent for approval successfully

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3176]
Description:
Application is visible in outbox even if it is  is sent for approval successfully

Steps:
1.Login as registration clerk
2.click ready for review
3. click any application, goto review and select "send for approval" in offline
4. record goes to outbox. Now goto online again
5. reload and observe the sent for approval page

Actual Result:

the record is successfully enlisted in the sent for approval page, but still it is visible in outbox, even if it is  is sent for approval successfully.

Expected Result:
Application shouldn't be visible in the outbox in online and when it is sent for approval successfully.

Screen Recording:
https://www.loom.com/share/ad5781d8bdce46d7b7e96db30a25638f

Tested on:
https://login.farajaland-qa.opencrvs.org/

Username and password used:

Username:  felix.katongo
Password: test

Desktop:
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by Fariha-Amin** [comment]
Might be similar to the bug 2941

**Comment by Fariha-Amin** [comment]
@anny320  retest passed and can be closed

**Retest Recording:**

https://user-images.githubusercontent.com/105624748/170701172-a9f31d1a-1208-436e-bec9-b07cb39460ad.mp4

**Comment by anny320** [comment]
completed
