### ISSUE TITLE
Certificate review page is broken

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3180]
**Bug description:**
Certificate review page is broken

**Steps to reproduce:**
1. Go to registration agent/ registrar
2. Go to ready to print
3. Click download> Print
4. Select Print in advance> Continue
5. Observe Certificate review page

**Actual result:**
Print and correct record button showing before the certificate

**Expected result:**
Print and correct record button should be below the certificate

**Screenshot:**
![review certificate broken.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/4f76c4fa-f8d7-40a9-9e24-c973701a7acb)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by jpye-finch** [comment]
As part of my PR. I put the certificate preview below the Content component. As elemets on the page jumped when the certificate loaded.

Suggest we raise an improvement ticket as I was unable to recreate the design: https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=1952%3A39187

**Comment by euanmillar** [comment]
Therefore is the priority correct and the bug description correct here? @jpye-finch  If you made these changes and additionally I dont remember applying any design change to Certificate page being a backlog item in this version.  I suggest this is closed.
