### ISSUE TITLE
In Performance, Registration by status block should be available for only office, not province / district

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3185]
**Bug Description:**
In Performance, Registration by status block should be available for only office, not province / district. Currently showing for province and districts also

**Steps to reproduce:**
1. Login to any user except Field agent
2. Click Performance
3. Filter location by any province/ district

**Actual result:**
Currently showing  Registration by status block for province and districts also

**Expected result:**
Should be only available for office

**Screenshot:**
![ss1.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/c9d5a4eb-6ae1-42c9-9ccb-54b134f096ed)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
@jpye-finch says the links should disabled but we can still show the panel

**Comment by jpye-finch** [comment]
@SyedaAfrida  this is not a bug!

The 'Registrations by status' panel. Should be available on **all** performance views!

Links to the Registration by status **table**. Only active at an office level. No links at a district, province or at Farajaland.
