### ISSUE TITLE
In Performance, Registration by status verbiage is wrong and total and view all is not displayed

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3186]
**Bug description:**
In Performance, Registration by status verbiage is wrong and total is not displayed

**Steps to reproduce:**
1. Login to any User except Field agent
2. Click Performance
3. Observe Registration by status

**Actual result:**
1.Verbiage is wrong
2.Total count not showing
3. View all link not showing

**Expected Result:**
1. Verbiage- " Current status of [Births/ deaths] being processed for your selected administrative area"
2. Total count should be present
3. View all link should be present

**design:**
https://camo.githubusercontent.com/36edfc4707766277ddf0b27ad8b6601a65c051bdcebc77537377dbd4baeb9deb/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565393661326434626566623233396534663262636539352f39643161316439392d633064612d343039652d393565662d393961623131666665323836

**Screenshot:**
![ss2](https://user-images.githubusercontent.com/94350336/169988293-c7189ff7-bfdb-4f5c-8734-78776b2e224f.png)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
Total count and view all links are not necessary in this release. @jpye-finch  comment is already addressed in this: Closing in favour of this new ticket that has up to date rules: https://github.com/opencrvs/opencrvs-core/issues/3371

**Comment by anny320** [comment]
ok, this is noted, adding on-hold status and once ready it can be picked up

**Comment by SyedaAfrida** [comment]
@jpye-finch to check

**Comment by euanmillar** [comment]
Closing as this view will be deprecated in favour of Metabase
