### ISSUE TITLE
Informant should have a minimum age restriction to declare a birth/death event

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3187]
Description:
Informant should have a minimum age restriction to declare a birth/death event. But  now, informant's age can be anything accept future and todays date. So, informant can be less than 1 year old also, this shouldn't be a logical input.

Steps:
1.Login as any user except system admins
2. click plus sign to create an application
3. fill necessary information and continue
4. When reached at informants details page,
observe the input field for DOB

Actual Result:
Informant doesn't have any minimum age restriction to declare a birth/death event

Expected Result:
Informant should have a minimum age restriction ( at least 18 years)  to declare a birth/death event.

ScreenShot:
![Capture4](https://user-images.githubusercontent.com/105624748/169984076-de4e1747-976e-40d6-9946-c687daa84002.PNG)

Tested on:
https://login.farajaland-qa.opencrvs.org/

Username and password used:

Username: felix.katongo
Password: test

Desktop:
OS: Windows 10
Browser: Chrome

**Comment by Fariha-Amin** [comment]
> Description: Informant should have a minimum age restriction to declare a birth/death event. But now, informant's age can be anything accept future and todays date. So, informant can be less than 1 year old also, this shouldn't be a logical input.
> 
> Steps: 1.Login as any user except system admins 2. click plus sign to create an application 3. fill necessary information and continue 4. When reached at informants details page, observe the input field for DOB
> 
> Actual Result: Informant doesn't have any minimum age restriction to declare a birth/death event
> 
> Expected Result: Informant should have a minimum age restriction ( at least 18 years) to declare a birth/death event.
> 
> ScreenShot: ![Capture4](https://user-images.githubusercontent.com/105624748/169984076-de4e1747-976e-40d6-9946-c687daa84002.PNG)
> 
> Tested on: https://login.farajaland-qa.opencrvs.org/
> 
> Username and password used:
> 
> Username: felix.katongo Password: test
> 
> Desktop: OS: Windows 10 Browser: Chrome

**Comment by euanmillar** [comment]
Related to: https://github.com/opencrvs/opencrvs-core/issues/2156

**Comment by jpye-finch** [comment]
this can be set as part of form config depending on country requirements. so can be closed.
