### ISSUE TITLE
"Reason for mother/Father" field shouldn't take numeric input

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3188]
**Description:**
"Reason for mother/Father" field shouldn't take numeric input. 

**Steps:**
1.Login as any user except system admins
2. click plus sign to create an application
3. fill necessary information and continue
4. When reached at mother's/father's details page
5. click "No" for "Do you have Mother's/Father's details ?" option.
6. Observe the input field for "Reason for mother/Father".

**Actual Result:**
"Reason for mother/Father" field is taking numeric input. (even if only numbers are given as input)

**Expected Result:**
"Reason for mother/Father" field shouldn't take numeric input. (specially if the whole input is numeric)

**Screen Recording:**
https://www.loom.com/share/4092b22461f84d5da7dde10eaecfd695

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username and password used:**

Username: felix.katongo
Password: test

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by euanmillar** [comment]
We are going to allow numbers and alphabet in this field as your explanation may involve the use of numbers. e.g.  They died in 1990
