### ISSUE TITLE
In correct record, verbiage of radio buttons are wrong in fees required

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3190]
**Bug description:**
In correct record, verbiage of radio buttons are wrong in fees required

**Steps to reproduce:**
1. Login as registrar
2. Click ready to print
3. Click Download in any record
4.  Click on the name
5. Click Correct record
6. Continue to the correct record summary page

**Actual result:**
In fees required , "ID verified" and "NO ID match" is showing in radio button

**Expected result:**
should be Yes/ No

**Screenshot:**
![wrong in fee.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/dac59cb6-38e2-484c-88df-392b33f50e1d)

**Tested on:** 
https://login.farajaland-qa.opencrvs.org/

**Comment by Fariha-Amin** [comment]
@anny320  passed, can  be closed 

**retest SS:**
![Capture](https://user-images.githubusercontent.com/105624748/172307548-13e8560f-822b-429e-ae1f-d1dcae197d1c.PNG)

**Comment by anny320** [comment]
completed
