### ISSUE TITLE
Verbiage of birth declaration is showing in death declaration in review page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3191]
**Bug description:**
Verbiage of birth declaration is showing in death declaration in review

**Steps to reproduce:**
1. Login as Field agent/ registration agent/ registrar
2. Declare a death application
3. Fillup and continue till review page

**Actual result:**
In Declaration incomplete/ complete section, verbiage of birth is showing

**Expected result:**
In Declaration incomplete/ complete section, verbiage of death should show

**Screenshot:**
![verbiage of birth in death declaration.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/4dc2ef72-930e-4280-85e4-071baba83eeb)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by azantor64** [comment]
![verbiage](https://user-images.githubusercontent.com/70468099/171606501-e77a872a-d30e-4dba-83ae-3f0ca85269bd.png)

Thisi is tested. passed @anny320

**Comment by anny320** [comment]
completed
