### ISSUE TITLE
Pagination is showing for Less than 10 record in In Progress 

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3196]
**Bug Description:**

Pagination is showing in 'In Progress' section when there are less than 10 records

**Steps to Reproduce:**

1. Log in as a Registration clerk 
2. Add more than 10 records in My Draft.
3. Navigate to the Field agent
4. Add 2 or 3 records in field agent(not more than 10)

**Actual Result:**

- Pagination is appearing in the 'In Progress > Field Agent' tab 

**Expected Result:**

- If records are less than 10, pagination should not show

**Screenshot:**

![image](https://user-images.githubusercontent.com/105625699/170028861-9a4e594d-0d1e-4c7e-95db-8eb177aad857.png)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**

- Username: felix.katongo 
- password: test

**Comment by emon-swe-sust** [comment]
Can't find this bug for current application

**Comment by saima-alam** [comment]
@anny320, This is working as expected. This can be closed

![image](https://user-images.githubusercontent.com/105625699/172152834-357b639f-4770-49d7-a91e-f67d0ccd7342.png)

**Comment by anny320** [comment]
completed
