### ISSUE TITLE
Download is failing for one specific application

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3197]
**Description:**
Download is failing for one specific application

**Steps:**
1.Login as registration clerk/registrar
2.goto ready to print and click just a particular application "Antr test".
3. Click download for "Antr test"

**Actual Result:**
Download is failing for one specific application "Antr test". Also Name and status is grayed before downloading.
![can't download](https://user-images.githubusercontent.com/105624748/170030943-3b71bc5d-d5a8-4c80-b6d8-46a93e6ff510.PNG)
![no_name](https://user-images.githubusercontent.com/105624748/170030970-fd9463ff-55fa-44fb-bb58-89c74ae56013.PNG)
![network](https://user-images.githubusercontent.com/105624748/170031138-48d3b8af-779e-408c-ad1c-1c8660a4b77c.PNG)

**Expected Result:**
Download should be successful and before download Name and status should be visible not grayed. 

**Response of the network request:**
[problem_response.txt](https://github.com/opencrvs/opencrvs-core/files/8762464/problem_response.txt)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username and password used:**

Username: felix.katongo
Password: test

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by Fariha-Amin** [comment]
@anny320   retest passed, can be closed.

**Comment by anny320** [comment]
completed

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Comment by anny320** [comment]
closed
