### ISSUE TITLE
System crashes after downloading any record from "requires update" page,  which do not have any "date of death"

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3198]
**Description:**
System crashes after downloading any record from "requires update" page, which do not have any "date of death"

**Steps:**
1.Login as registration clerk/registrar
2. goto in progress (field agent) and reject a application that has no death filled up
2.goto requires update page and select that application 
3. download that application 
4. press back button after downloading

**Actual Result:**
System crashes after downloading the record which do not have any "date of death"

**Expected Result:**
System should not crash for downloading incomplete records

**Screen Recording:**
https://www.loom.com/share/e544d9e212a84d80933a8ea159db7d1f

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username and password used:**

Username: felix.katongo
Password: test

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by anny320** [comment]
completed
