### ISSUE TITLE
Sorting is not correct in History page

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3199]
**Bug Description:**

The history of any birth/death application is not sorted correctly in the history screen

**Steps:**

1. Log in as a Registration clerk
2. Navigate to requires Update
3. Click on an Application
4. Download the application
5. Add more than 10 records in the history of the application
6. navigate to the 2nd page of the history

**Actual Result:**

- History is sorted incorrectly. Record which should show on 1st page is showing on the 2nd page

**Expected Result:**

- History should show the most recent record in the first. 

**Screenshot:**

![test](https://user-images.githubusercontent.com/105625699/170187565-9e22d6d6-8e06-4c3a-bcca-0fc078847e9b.png)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**

- Username: felix.katongo 
- password: test

**Desktop:**

- OS: Windows 10
- Browser: Chrome

**Comment by saima-alam** [comment]
@anny320 This is not fixed yet. 

![image](https://user-images.githubusercontent.com/105625699/171804653-b3d2c020-0fd3-4206-be83-0f537ca552dd.png)
![image](https://user-images.githubusercontent.com/105625699/171804691-52115e5c-59ca-4e6f-bb6b-1e76290da3c2.png)

**Comment by saima-alam** [comment]
@anny320, This is working as expected. This can be closed.

![image](https://user-images.githubusercontent.com/105625699/172359907-7ebdf9f1-0d61-4d70-8cdc-904877b047af.png)

**Comment by anny320** [comment]
completed
