### ISSUE TITLE
Floating notification appears in the log page

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3203]
**Describe the bug**
After session time out when logout page / pin input page appears then 
**Floating notification** remains on the pin input page/log out page

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://register.farajaland-qa.opencrvs.org/
2. Navigate to Ready to print
3. Download any application which shows any notification
![image](https://user-images.githubusercontent.com/70468099/170201986-db34f362-8de3-4bce-8762-1b6380b71e70.png)

4. After seeing notification wait untill the logout page appears
5. See error

**Actual Result**
![image.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/f76962b2-9436-409a-98a3-69209dd5bba7)
**Expected result**
Floating notification should not appear in log page

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser :Chrome,edge

**Comment by atiqzaman-dsi** [comment]
@anny320 @jpye-finch what could be the solution? Should we use a timeout to hide the toast after few seconds, for instance 5 seconds?

**Comment by atiqzaman-dsi** [comment]
I think we need time to fix this issue. Related unit tests fails due to auto hide.

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/174019399-8a82133b-8fbd-48dc-b69b-4dc2f5b95659.png)
