### ISSUE TITLE
In performance Completeness rate page, not showing 0 in the ‘‘Within 30 days/ Within 1 year/ Within 5 year’ column when there is no registration for a time period

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3204]
**Bug description:**
In performance Completeness rate page, not showing 0 in the ‘‘Within 30 days/ Within 1 year/ Within 5 year’ column when there is no registration for a time period

**Steps to reproduce:**
1. Login as any user except Field agent
2. Click Performance
3. Click any View beside Completeness block
4. Observe the table

**Actual result:**
 when there is no registration for a time period, not showing 0 in the ‘Within 30 days/ Within 1 year/ Within 5 year’ column 

**Expected result:**
Should show 0  in the ‘Within 30 days/ Within 1 year/ Within 5 year’ column 

**Screenshot:**
![not showing 0.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/f9a7dd4b-0b43-418b-867d-7f75a71ea4e5)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Retest SS:**
![a](https://user-images.githubusercontent.com/105624748/174598714-e94fb69f-56f7-4d73-ade4-31e73359c334.PNG)
