### ISSUE TITLE
Event registration location is not visible in certificate

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3210]
**Description:**
Event registration location is not visible in final certificate.

**Steps:**
1.Login as registration clerk/registrar
2.goto ready to print page
3.download any birth/death application
4.click print and complete all steps to generate certificate 
5.observe the final certificate

**Actual Result:**

Event registration location is not visible in certificate. ( For both birth and death ).

![no_location_print](https://user-images.githubusercontent.com/105624748/170239366-3423e651-f75b-4a00-9ca9-eea1790ea8a7.PNG)

**Expected Result:**
Event registration location should be  visible in certificate.

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username and password used:**

Username: emmanuel.mayuka
Password: test

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by euanmillar** [comment]
Must be health centre, district, state, country

**Comment by euanmillar** [comment]
Still has an issue with death

**Comment by Fariha-Amin** [comment]
@anny320  passed, can be closed.

ScreenShot:
![d](https://user-images.githubusercontent.com/105624748/171574759-cc1e318e-d97e-4585-bba0-5fe256e8b210.PNG)

**Comment by anny320** [comment]
completed
