### ISSUE TITLE
If user search a birth/death application and open it, Date of death,Place of death and Informant do not show 

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3211]
**Bug Description:**

If a user searches a birth/death application and then opens it, the Following information shows blank:

- Date of death
- Place of death
- Informant

**Steps:**

1. Log in as a field agent/Registration Clerk/Register
2. Click on any application which has the Date of death, Place of death, and Informant from any tab
3. Download the application(if logged in with Registration clerk/Register)
4. Observe that the Date of death, Place of death, and Informant are showing
5. Copy the tracking id or name or phone number
6. Search the application with the tracking id or name or phone number
7. Click on the application

**Actual Result:**

- Date of death, Place of death, and Informant do not show any data

**Expected Result:**

- Date of death, Place of death, and Informant should show if the user opens the application after searching

**Screen record:**
https://www.screencast.com/t/3T0jmT70bl

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**

- Username: felix.katongo 
- password: test

**Desktop:**

- OS: Windows 10
- Browser: Chrome

**Comment by saima-alam** [comment]
@anny320 This is working as expected. This can be closed.
Reference video: https://www.screencast.com/t/FKLup5tZtuOC

**Comment by anny320** [comment]
completed
