### ISSUE TITLE
 Workqueue should be sorted by the last column by default

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3212]
**Bug description:**
 Workqueue should be sorted by the last column by default. Currently the records are sorted by name. A to Z.

**Steps to reproduce:**
1. Login as any user
2. Select a workqueue with some records
3. Click on the Name header

**Actual result:**
 the records are sorted by name. A to Z

**Expected result:**
 Workqueue should be sorted by the last column by default

**Screenshot:**
![image (22).png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/5253f69a-cfaf-4874-b875-762e54535533)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by saima-alam** [comment]
@anny320, This is working as expected. This can be closed.

![image](https://user-images.githubusercontent.com/105625699/172167472-3dce5eb9-1209-4a03-b1f1-aa3cb6c65575.png)

**Comment by anny320** [comment]
completed
