### ISSUE TITLE
Default view for performance is wrong for local system admin, registration agent and registrar

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3224]
**Description:**
Default view for performance is wrong for local system admin, registration agent and registrar

**Steps:**
1.Login as system admin /registration agent/ registrar 
2. goto performance page
3. observe the search bar for location

**Actual Result:**
"Ibombo District,Central Province"  is showing as default view.

**Expected Result:**
"Ibombo District Office" should be shown as default view.

**ScreenShot:**
![local_admin](https://user-images.githubusercontent.com/105624748/170470760-05c6d480-9d8e-40c4-9d8b-cd598f79e4d1.PNG)

**Default View requirements:**
![image](https://user-images.githubusercontent.com/105624748/170470922-981c9901-5193-4971-b8a6-512d064d1b6c.png)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username and password used:**

Username: emmanuel.mayuka , felix.katongo,  kennedy.mweene
Password: test

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by anny320** [comment]
completed
