### ISSUE TITLE
Spelling mistake in a button of Check proof ID portion

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3226]
**Describe the bug**
Spelling mistake in a button of Check proof ID portion

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://login.farajaland-qa.opencrvs.org/
2. Log in as Registrar
3. Navigate to Ready to Print
4. Download an application
5. Go to Correct record 
6. Select any option
7. See Green button
**Actual Result**
![spelling mistake.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/bb0c5632-3f8f-4954-9766-27844c9d74f9)
**Expected behaviour**
Button will be **ID verified**

**Comment by soumita-dsi** [comment]
Fixed with ticket #3190

**Comment by soumita-dsi** [comment]
![image](https://user-images.githubusercontent.com/57105414/172382399-69509c29-0f96-4722-8863-e454b336c704.png)
This is already done

**Comment by anny320** [comment]
completed
