### ISSUE TITLE
For field agent, in sent for review, DRN is showing for a complete death application

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3229]
**Description:**
For field agent, in sent for review, DRN is showing for a complete death application

**Steps:**
1.Login as field agent
2. declare a death event
3. send a complete death application
4. goto sent for review page
5. observe record audit page

**Actual Result:**
DRN is showing.

**Expected Result:**
DRN shouldn't show to field agent in record audit page.

**ScreenShot:**

![comp_death.PNG](https://images.zenhubusercontent.com/6281e46d6f51be7532fe12bd/e2c531ab-e315-407b-9a7e-bb9d3b3bd1ac)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by Fariha-Amin** [comment]
@anny320  passed, can be closed

**retest ss:**
![d](https://user-images.githubusercontent.com/105624748/171415049-92b9c0f7-14a6-465c-ad3b-ca01159bdc15.PNG)

**Comment by anny320** [comment]
completed
