### ISSUE TITLE
In Performance, when location is changed, 'Registration by status' data is incorrect

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3230]
**Bug Description:**

In the performance section, when the user changes a location from the location filter, Registration by status doesn't show correct data. It is showing the same data for all locations.

Steps:

1. log in as Register
2. Go to Performance
3. From the location filter, select any location
4. Observe Registration by status

**Actual Result:**

The data in Registration by status is showing the wrong data. The numbers beside the  In Progress, Ready for review, Sent for updates, Sent for approval, and Ready to print links are not matching with the number of application that shows after clicking on the link 

**Expected Result:**
the numbers beside the  In Progress, Ready for review, Sent for updates, Sent for approval, and Ready to print links should show the correct numbers

**Screenshot:**

![image](https://user-images.githubusercontent.com/105625699/170501700-90c922db-4153-4d55-b36c-241c1221260c.png)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**
Username: kennedy.mweene
password: test

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by SyedaAfrida** [comment]
@anny320 this can be closed

**Comment by anny320** [comment]
closed
