### ISSUE TITLE
System crashes after clicking on a user name of a newly created user except field agent from team page

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3235]
**Bug Description:**

When the National system admin creates any of these following users and clicks on the user name from the team page, the system crashes. This is not happening for Field agents. 

1. National system admin
2. Local system admin 
3. Register
4. Registration agent
5. Performance Manager 
6. National Register

**Steps:**

1. Log in as a National system admin
2. Click on Team
3. Select an Office
4. Click on New user
5. Create a National system admin/Local system admin/Register/ Registration agent/Performance Manager/National Register
6. Click on the newly created user name from the team page

**Actual Result:**

- System crashes. This page could not be found appears.

**Expected Result:**

- Clicking on a user name of a newly created user from the team page should navigate to the user audit page.

**Screen record:**
https://www.screencast.com/t/otXattAxw7q6

**Screenshot:**
![image](https://user-images.githubusercontent.com/105625699/170648834-b1e75502-82a3-4745-8236-0719096db350.png)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**
- Username: jonathan.campbell
- password: test

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by euanmillar** [comment]
User audit links will be deleted

**Comment by anny320** [comment]
closed
