### ISSUE TITLE
Copy change needed in Form config , In preview and Published tab

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3239]
**Bug description:**
Type error of accounts in In Preview tab
Type error of Published in Published page

**Steps to reproduce:**
1. Login as National system admin
2. Click Config
3. Click Declaration forms
4. Click In preview
5. Click Published

**Screenshot:**
![2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/b79d32cb-73d8-4337-8982-fae4874f48d4)
![3.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/19ed87da-dd96-4eff-98f3-d2eebd0c4c66)

**Tested on:**
https://login.farajaland-config.opencrvs.org/

**Comment by eduffus** [comment]
Tested on config env
