### ISSUE TITLE
BRN/DRN is showing in record audit page, even for non-registered applications, before downloading them

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3244]
**Description:**
BRN/DRN is showing in record audit page, even for non-registered applications, before downloading them. After downloading, BRN/DRN field disappears.

**Steps:**
1.Login as any user except system admins.
2.click ready for review/In progress/requires update
3. click any application, goto record audit page
4. observe the fields in record audit page

**Actual Result:**
BRN/DRN is listed in audit record page for unregistered applications ,only before downloading. After downloading it disappears.

**Expected Result:**
BRN/DRN is shouldn't be  listed in audit record page for unregistered applications. BRN/DRN should only appear for the applications in ready to print page, as it has all registered applications.

**Screen Recording:**

https://user-images.githubusercontent.com/105624748/170698154-2d269d2a-34cb-4937-809a-3829fd01e59c.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by Fariha-Amin** [comment]
@anny320  solved can be closed

**Retest SS:**
![d](https://user-images.githubusercontent.com/105624748/171413674-a91e0631-c8d4-407b-a12d-24c13a68736d.PNG)

**Comment by anny320** [comment]
completed
