### ISSUE TITLE
In the history of audit record, Update declaration is not showing correctly

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3252]
**Bug Description:**

When reviewing an application If a register updates the application, It shows some wrong information in the Update declaration In the history of the audit record.
If the register updates the first and last name of the child, mother, father, and informant it shows the updated child's first name and last name in the place of : 
1. mother's first name and last name
2. father's first name and last name
3. informant's first name and last name

Also if the register updates the National ID of both and mother and father, it shows the updated mother's National ID into the father's National ID

**Steps:**

1. A complete application that has informant,mother and father details should be available in the ready of review of the register
2. Log in as a Register
3. Navigate to ready for review 
4. Download the application and click review
5. Change the first name and last name of the child, informant, father and mother
6. Change the NID of the informant, father and mother
7. Register the Application
8. Click on ready to print
9. Find the application and download it
10. Click on Update declaration from history

**Actual Result:**

1. The child's first and last name is showing in the place of the informant, mother and father's first name and last name. 
2. Mother's NID is showing is the place of the father's NID

**Expected Result:**
1.  Informant, mother and father's first name and last name should show correctly
2. Father's NID should show the correct NID 

**Screenshots:**
Informant:
![1](https://user-images.githubusercontent.com/105625699/170962645-3cf40ced-806f-4bcd-bbe3-50c6ff68b1f2.png)
![informant 2](https://user-images.githubusercontent.com/105625699/170962886-df04f2db-649e-417e-815e-e414baa44e95.png)
Mother:
![mother name](https://user-images.githubusercontent.com/105625699/170962909-95a76b44-2bbb-4e13-83aa-041841767c96.png)
Father:
![father name](https://user-images.githubusercontent.com/105625699/170963184-c4eec5ec-3b32-4cb2-9523-945ab6bc277c.png)
![father nid](https://user-images.githubusercontent.com/105625699/170963203-a92d8df8-69e8-42bd-b411-566714fad158.png)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**
Username: kennedy.mweene
password: test

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by saima-alam** [comment]
@anny320, This can be closed. This is working as expected. Informant, mother, and father's name is showing correctly.
Father's NID is also showing correctly.
![image](https://user-images.githubusercontent.com/105625699/171803481-022c911e-fa58-4481-8c25-ea83fb2bd8c7.png)
![image](https://user-images.githubusercontent.com/105625699/171803510-e729f8a6-0b25-4b02-810f-091b42170299.png)

**Comment by anny320** [comment]
completed
