### ISSUE TITLE
In form config, Question mark tooltip is not working

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3253]
**Bug description:**
In form config, Question mark tooltip is not working

**Steps to reproduce:**
1. Login as National System admin
2. Click Config> Click Declaration form
3. Click Configure in draft page
4. Click any mandatory element (like DOB)
5. Click Question mark in the right side menu

**Actual Result:**
Question mark tooltip is not working

**Expected Result:**
should show messages

**Figma:**
https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1286%3A23770

**Screenshot:**
![question.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/a753c65e-88d9-4ba4-8473-cec82657e289)

**Tested on:**
https://login.farajaland-config.opencrvs.org/

**Comment by azantor64** [comment]
this ticket is a copy of [3156](https://github.com/opencrvs/opencrvs-core/issues/3156)

**Comment by anny320** [comment]
duplicate closed
