### ISSUE TITLE
In form Config, When trying to add a custom field, the UI of disabled save button is not correct

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3254]
**Bug description:**
In form Config, When trying to add a custom field, the UI of disabled save button is not correct

**Steps to reproduce:**
1. Login as National System admin
2. Click Config> Click Declaration form
3. Click Configure in draft page
4. Click out side the form canvas
5. Click any add Link
6. Observe the disabled Save button

**Actual result:**
save text not found in the button

**Expected result:**
save should be mentioned in the button

**Screenshot:**
![save disabled.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/a6cae96f-120a-4a27-b2a7-4f3227c83746)

**Tested on:**
https://login.farajaland-config.opencrvs.org/

**Comment by Fariha-Amin** [comment]
@anny320  passed, can be closed

**Retest SS:**
![d](https://user-images.githubusercontent.com/105624748/171818978-707acbae-490f-4a5f-be11-f8eb782049ce.PNG)

**Comment by anny320** [comment]
completed
