### ISSUE TITLE
In form config, Max length cannot be edited properly

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3256]
**Bug description:**
In form config, Max length cannot be edited properly

**Steps to reproduce:**
1. Login as National System admin
2. Click Config> Click Declaration form
3. Click Configure in draft page
4. Click outside form canvas
5. Click any add
6. In max length delete 1 digit at a time

**Actual result:**
Unable to delete the full value properly

**Expected result:**
 should be able to delete the full value properly

**Screen recording:**
https://images.zenhubusercontent.com/91778759/32be0974-9585-463c-8b6f-9062543f570c/max_length_cannot_be_edited_from_250.mp4

**Tested on:**
https://login.farajaland-config.opencrvs.org/

**Comment by Fariha-Amin** [comment]
@anny320  fixed, can be closed

**Retest Recording:**

https://user-images.githubusercontent.com/105624748/172789297-954be4a5-3286-4249-824c-ca1a156a9ab9.mp4

**Comment by anny320** [comment]
completed
