### ISSUE TITLE
Correct Record is not showing Informant details, if 'Who is applying for birth registration?' is changed when reviewing a birth application

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3259]
**Bug Description:**

If a birth application that is applied by the father/mother is sent for review and the register changes the 'Who is applying for birth registration?' from father/mother to any other option and registers the application, the updated informant details don't get updated in the correct record.

**Steps:**

1. A complete birth application that has been applied by the father or mother is available in the  ready for review of the register
2. Log in as a Register
3. Navigate to ready for review
4. Download the application and click review
5. Change the 'Who is applying for birth registration?' from father/mother to any other option except mother/father
6. Register the Application
7. Click on ready to print
8. Click on the application
9. Click on Correct record
10. Observe the Declaration details

**Actual Result:**

'Who is applying for birth registration?' is showing previous data. Don't show the updated data. Also, no Informant details are available.

**Expected Result:**

'Who is applying for birth registration?' should show the update to the Informant. Also, Informant details should show.

**Screen record:**

https://user-images.githubusercontent.com/105625699/170972928-1ce89883-0502-4c86-8994-d5dc745231bc.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**
Username: kennedy.mweene
password: test

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by saima-alam** [comment]
Now the correct record is showing informant details but there is another issue. Relationship to child doesn't show in correct record
**Steps:**
1. An birth application is available in Ready for review where the informant type is father /mother 
2. Log in as Registrar
3. Go to Ready for review and find the birth application
4. Change the informant to Someone else and register the application
5. Go to Ready for print and click on the correct record of the application
**Actual Result:**

- Informant type is showing 'Required for registration' in place of Relationship to child

- After clicking on Change link beside the informant type  the Relationship to child field doesn't show any data

**Expected Result:**

- Informant type should show 'Relationship to child' if Someone else is selected as informant

- Clicking on the Change link beside the informant type  the Relationship to child field should show 

![image](https://user-images.githubusercontent.com/105625699/172331967-bbc1b3fc-dd56-4368-af7c-32b1cc29e206.png)
![image](https://user-images.githubusercontent.com/105625699/172332033-65a89079-ad90-4949-81f5-edd169df7670.png)

**Comment by saima-alam** [comment]
@anny320, This is working as expected. This can be closed.

https://user-images.githubusercontent.com/105625699/172389412-cca45f94-ba92-461f-8d45-296bd3e46a10.mp4

**Comment by anny320** [comment]
Completed
