### ISSUE TITLE
UI issue in performance 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3260]
**Bug description:**
UI issue in performance when try to view table

**Steps to reproduce:**
1. Login as a registrar
2. Click performance
3. Click any link from Registration by status
4. Observe in large screen

**Actual result:**
![performance UI.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/4c25b1b7-e4c0-4865-b01e-0bad6d076718)

**Expected result:**
The table should be shown in full page

**Tested on:**
https://login.farajaland-config.opencrvs.org/

**Comment by tahmidrahman-dsi** [comment]
Seems to be resolved. Requesting @SyedaAfrida to retest

**Comment by saima-alam** [comment]
This is resolved. This can be closed. 

![image](https://user-images.githubusercontent.com/105625699/172822469-789b58af-37f3-4ddc-8856-34822614e937.png)

**Comment by anny320** [comment]
@saima, seeing some new issues on this ticket  text overlapping) ![Screenshot 2022-06-09 at 13.29.34.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/285d6a42-b109-4c15-94d0-310c02ddbd3e) will close this one and create new tickets on the new issue
