### ISSUE TITLE
In form config, Cannot save draft when Max length of custom field is 200

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3261]
**Bug description:**
In form config, Max length cannot take input 200

**Steps to reproduce:**
1. Login as National System admin
2. Click Config> Click Declaration form
3. Click Configure in draft page
4. Click outside form canvas
5. Click any add
6. In max length enter 200
7. Click save
8. Click save draft
9. Enter description
10. Click save

**Actual result:**
Fail to save draft
**Expected result:**
should be able to save draft 
**Screen recording:**
![max length cannot be 200.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/cfc165fa-38bb-4691-abea-98cf4e08d080)

**Network:**
"Variable \"$questions\" got invalid value \"200\" at \"questions[6].maxLength\"; Int cannot represent non-integer value: \"200\""

**Tested on:**
https://login.farajaland-config.opencrvs.org/

**Comment by azantor64** [comment]
1.Able to save draft

https://user-images.githubusercontent.com/70468099/172790915-11563a39-88ae-4e41-8b0a-be89c37bb742.mp4

**Comment by anny320** [comment]
completed
