### ISSUE TITLE
Record audit must support a birth notification by a Health System

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#3263]
Bug description:
Currently, if a birth declaration is created by a Health System downloading and opening up a declaration causes system to crash. This is because Record audit history isn't capable of handling a declaration created by Health System

Steps to reproduce:
Generate a birth notification using demo data generator
Login as a local registrar
Click Ready for review
Download and open the birth declaration

Actual result:
System crash

Expected Result:
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=6295%3A112593

**How to create a Health Notification using the demo data generator tool:**

1. In your local environment, go to `opencrvs-farajaland` directory. Run the demo data generator by running `yarn data-generator`. This command should now start generating new birth declarations to your database. 
2. You will notice, however, that most of the generated declarations are not made by Health Integration, but by a regular field agent instead. You can change the ratio of field agent / health integration created declarations by opening up `src/data-generator/index.ts`. Here you should see the following code block

```
// Create 30 users for each location:
// 15 field agents, ten hospitals, four registration agents and one registrar
export const FIELD_AGENTS = 15
export const HOSPITAL_FIELD_AGENTS = 10
export const REGISTRATION_AGENTS = 4
export const LOCAL_REGISTRARS = 1
```

If you decrease the number of field agents and increase hospital field agents, the next time you run the generator you should see more notifications and less regular declarations

```
// Create 30 users for each location:
// 15 field agents, ten hospitals, four registration agents and one registrar
export const FIELD_AGENTS = 1
export const HOSPITAL_FIELD_AGENTS = 15
export const REGISTRATION_AGENTS = 4
export const LOCAL_REGISTRARS = 1
```

**Comment by emon-swe-sust** [comment]
How can I create application from health system from UI rather than just demo data generator.

**Comment by rikukissa** [comment]
You can't really. Birth notifications are meant to be sent by the health system directly to the country config package, which in turn writes the data directly to Hearth. From what I've seen, the notifications work and get stored properly to the database but the UI doesn't know how to handle them in some cases.

**Comment by euanmillar** [comment]
@rikukissa when you are able to, can you provide step-by-step instructions to a dev on how to run the data generator just for health notifications?

**Comment by SyedaAfrida** [comment]
@anny320 Since there is no data in health system, can't test this ticket

**Comment by euanmillar** [comment]
![Screenshot 2022-09-21 at 17.05.43.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/3862cdf1-760f-4351-a8eb-9e3e5631e5dd)

Now the data generator has been amended, I can see this data in record audit so this can be closed

**Comment by jpye-finch** [comment]
Nice! 

The Location should probably be blank for Health System..?

**Comment by anny320** [comment]
A new ticket to remove a location from the health system notification will be created.  The current ticket will now be marked as completed
