### ISSUE TITLE
Search by Location should be disabled from registration by status pages

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3264]
**Description:**
Search by Location should be disabled from registration by status pages .

**Steps:**
1.Login as any user except field agent
2. goto performance page
3. goto In progress/ready for review/send for updates/sent for approval/ready to print from registration by status section
4. observe search by location filter

**Actual Result:**
Search by Location is not disabled from registration by status pages. Also the default view is incorrect for search  by location. "Ibombo District, Central Province" is set as default view.
![de1](https://user-images.githubusercontent.com/105624748/170991108-b6ec3941-a961-4609-8d4e-dcedd978cd7a.PNG)

**Expected Result:**
 "Ibombo district office" should be set as default view and the search by location field should be disabled.
![gray](https://user-images.githubusercontent.com/105624748/170991016-1cd8ca62-afb5-4ca3-8b7f-3ce1b96152cf.PNG)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username and password used:**

Username: emmanuel.mayuka , felix.katongo, kennedy.mweene
Password: test

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by euanmillar** [comment]
Closing in favour of this new ticket that has up to date rules: https://github.com/opencrvs/opencrvs-core/issues/3371
