### ISSUE TITLE
"Corrections" field is not being updated in performance page when no correction fees is provided

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3267]
**Description:**
"Corrections" field is not being updated in performance page

**Steps:**

1. login as registrar and goto ready for print page
2. click on any application, download it
3. click correct record
4. correct any information and confirm correction without any payment
5.Login as any user except field agent
6. goto performance page
7. observe the "corrections" field

**Actual Result:**
"Corrections" field is not being updated in performance page when no correction fees is provided . fields are showing "0".

**Expected Result:**
"Corrections" field should be  updated in performance page whenever correction is made **( without payment)**  in any application after registration .

**ScreenRecording:**

https://user-images.githubusercontent.com/105624748/171103963-3d496fdb-8b4a-4824-8526-b0b4ff7408c6.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by soumita-dsi** [comment]
@azantor64 This has been already fixed. Could not reproduce it.

**Comment by Fariha-Amin** [comment]
@anny320  passed, can be closed

**retest video:**

https://user-images.githubusercontent.com/105624748/173060133-d3504d6e-9268-4748-a899-557a1ba2d036.mp4

**Comment by anny320** [comment]
completed
