### ISSUE TITLE
In application config(Death) K and Number is not aligned horizontally

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3269]
**Describe the bug**
In application config(Death) K and Number is not aligned horizontally

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in as National Sys admin
2. Navigate to Config>Death
3. Click on late registration change button

**Expected behaviour**
K and Number should be aligned horizontally

**Actual Result**
If applicable, add screenshots to help explain your problem.![image.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/132ecd51-75ed-400f-b263-8b84b4d99bd8)

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**retest ss:**
![d](https://user-images.githubusercontent.com/105624748/172782187-a26d43e1-0913-43a7-a9ed-c7d4989f1e27.PNG)

**Comment by anny320** [comment]
issue not completely fixed, alignment is still slightly off ![Screenshot 2022-06-14 at 09.37.49.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/852786b8-6da1-4acf-86eb-12142baa300d)

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/174561191-4d1cf0aa-95ad-42f0-b961-ec32593e2a59.png)
![image](https://user-images.githubusercontent.com/70468099/174561231-4e6efeeb-6cc8-422d-9541-e23edf021adc.png)
![image](https://user-images.githubusercontent.com/70468099/174561269-b883a7ef-1a39-4319-90c5-277604b3e562.png)

Finally: 
![align](https://user-images.githubusercontent.com/70468099/174561594-4b01fece-7c1b-44c0-aef0-0ee706fda55c.png)

Passed. @anny320 , @eduffus
