### ISSUE TITLE
Disable all User Audit links and display username in Sys Admin > User > Edit Details

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3271]
UserAudit page is not completed so we must disable all links to it.

Additionally, we must insert a new row in the edit user form somewhere to display the generated username, but this should not be an editable field.

- [x] disable links to user audit from all record audit rows for all users:

![Screenshot 2022-05-30 at 23.29.04.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/97cbf1aa-7ccb-45fb-9ff8-bb85c15b361a)

- [x] disable links to user audit from Team page

![Screenshot 2022-05-30 at 23.30.07.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/b501e36d-d60a-41c5-aab5-b332cd6fbab8)

- [x] As a local or national system admin, when you click on Edit Details for a user ...

![Screenshot 2022-05-30 at 23.33.13.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/35e407e1-e4db-4689-a40e-0e0eca17e517)

On the Edit Details page, insert an extra row that shows the user's username.  There should NOT be a "Change" link for this row.  It is simply displaying so that the sys admin can communicate the generated user name to the user in case they forget it.

![Screenshot 2022-05-30 at 23.33.29.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/2806b21b-4144-4054-9a1a-32c01d0a41bd)

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/171629501-fc1a3e20-1b04-403c-ac18-8d43789a2195.png)

**Comment by Fariha-Amin** [comment]
@anny320  passed, can be closed

Retest SS:
![d](https://user-images.githubusercontent.com/105624748/171803559-24341d90-b86a-406b-8d61-04f4631c6820.PNG)
![dd](https://user-images.githubusercontent.com/105624748/171803564-5f006fca-ae67-4bf7-88e8-6e0b7a2300e3.PNG)

**Comment by anny320** [comment]
completed
