### ISSUE TITLE
In Performance, deactivated field agents are not showing when viewing records started by field agents

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3274]
**Bug Description:**

In the performance, When register selects an office and clicks on the view link beside Field Agents under the Sources of applications section, deactivated field agents don't show. If Deactivate is selected in the filter, it shows 'No user found'

**Steps:**

1. An deactivated field agent is created in the location of the register
2. log in as the Register
3. Go to Performance
4. From the location filter, select an office
5. Navigate to 'Sources of applications'
6. Click on View beside Field agents
7. Select Deactive in the filter

**Actual Result:**

- Deactivate field agent is not showing

**Expected Result:**

- Deactivated field agents should show if Deactive is selected in the filter

**Screenshot:**

![image](https://user-images.githubusercontent.com/105625699/171113586-42eedd4d-f723-4322-8179-a5aa25776fa2.png)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**
Username: kennedy.mweene
password: test

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by anny320** [comment]
completed
