### ISSUE TITLE
In Performance, Field agents  name column is not sortable when viewing records started by field agents 

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3275]
**Bug Description:**

In the performance, When register selects an office and clicks on the view link beside Field Agents under the Sources of applications section, the Field agents name column is not sortable.

**Steps:**

1. An deactivated field agent is created in the location of the register
2. log in as the Register
3. Go to Performance
4. From the location filter, select an office
5. Navigate to 'Sources of applications'
6. Click on View beside Field agents
7. Try to sort the Field agents column

**Actual Result:**

- Field agents column is not sortable

**Expected Result:**

- Field agents column should be sortable

**Screen record:**

https://user-images.githubusercontent.com/105625699/171115785-64e87d90-500c-4b7f-aac4-f89d58634415.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**
Username: kennedy.mweene
password: test

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by saima-alam** [comment]
@anny320, This is working as expected. The field agent's name column is sortable now. This can be closed.

https://user-images.githubusercontent.com/105625699/173297602-cbd733a4-cdc0-49d3-8351-ef6962dbe198.mp4

**Comment by anny320** [comment]
completed
