### ISSUE TITLE
In form config, Custom phone number input, placeholder do not work

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3278]
**Bug description:**
In form config, Custom phone number input, placeholder do not work and error message should be deleted

**Steps to reproduce:**
1. Login as National System admin
2. Click Config> Click Declaration form
3. Click Configure in draft page
4. Click outside form canvas
5. Click add in Phone number input
6. Enter label name in english
7. Enter label name in french
8. Enter place holder name in english
9. Enter place holder name in french
10. Click Save

**Actual result:**
do not show placeholder text in form canvas

**Expected result:**
Should be able to view place holder text in form element

**Screenshot:**
![phone number placeholder not working.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/ad8d8c6d-0da9-4b65-a85f-b46d09f5186b)

**Tested on:**
https://login.farajaland-config.opencrvs.org/

Tasks
- [ ] Ensure place holder is editable and renders. 
- [ ] Hide the error message input as it doesnt work and will not allow the user to customise the error in this release.

**Comment by SyedaAfrida** [comment]
@anny320 This bug is fixed and can be closed
![place holder1](https://user-images.githubusercontent.com/94350336/172148232-6778e48d-2239-4906-a3a1-6f43f41177fc.png)

**Comment by anny320** [comment]
completed
