### ISSUE TITLE
Can not create a new national registrar in any location

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3281]
**Bug Description:**

National System Admin Can not create a new national registrar in any location

**Steps:**

1. Log in as a National system admin
2. Click on Teams
3. Select any location
4. Click on New user
5. Create a National registrar

**Actual Result:**

- The user is unable to create a National registrar. It shows the error "Sorry! Something went wrong"

**Expected Result:**

- National Registrar should be created successfully

**Screenshot:**

![image](https://user-images.githubusercontent.com/105625699/171173481-45c6a549-f130-4a88-b71a-1a5e7f9a6e7b.png)

**Screen record:**

https://user-images.githubusercontent.com/105625699/171173677-7324a0a1-ecba-4308-b1a0-0599e27f2079.mp4

Tested on:
https://login.farajaland-qa.opencrvs.org/

Username & Password Used:

- Username: joseph.musonda 
- password: test

**Comment by euanmillar** [comment]
We definitely should be allowed to create multiple National Registrars in any location

**Comment by saima-alam** [comment]
@anny320 This is working expeacted. National System Admin can create multiple National registrars. This can be closed.
Reference video : 
https://user-images.githubusercontent.com/105625699/171592286-d1cbcc07-097d-4162-831e-e4c5f18f42e2.mp4

**Comment by anny320** [comment]
completed
