### ISSUE TITLE
In form config, the right side menu do not change when custom element is changed from one to another

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3282]
**Bug description:**
In form config, the right side menu do not change when custom element is changed from one to another

**Steps to reproduce:**
1. Login as National System admin
2. Click Config> Click Declaration form
3. Click Configure in draft page
4. Click any custom field
5. Observe the right side menu
6. Click another custom filed
7. Observe the right side menu

**Actual result:**
The heading change according to custom field but the other fields do not change like- label, placeholder, error message etc

**Expected result:**
Both heading and other fields like- label, placeholder, error message etc should change 

**Screenrecording:**
https://images.zenhubusercontent.com/91778759/b52fd1d5-5644-4fbd-a7b0-57d62628a87a/rightside_menu_not_updating_when_customizable_elements_are_changed.mp4

**Tested on:**
https://login.farajaland-config.opencrvs.org/

**Comment by anny320** [comment]
closed
