### ISSUE TITLE
Additional comment box not appear in death declaration page

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3284]
**Describe the bug**
In Death application review page Additional comment box not appear in death declaration page in online and offline

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in as field agent
2. Make a death application
3.  Go to Death Declaration page
4. See No additional comment box

**Expected behaviour**
user can add an additional comment with the application

**Actual Result**
No comment box to add comment
![image.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/8446502b-f040-4505-b9ec-b8eaa07f25df)

**Desktop (please complete the following information):**
 - OS:Linux
 
 Tested on: [qa-server](https://login.farajaland-qa.opencrvs.org/)

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/172160142-1f65a993-ba3b-4b61-9ace-23f42c60d19e.png)

**Comment by anny320** [comment]
completed
