### ISSUE TITLE
System crashes if National registrar clicks on an application from any tab 

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3285]
**Bug Description:**

When the national registrar clicks on an application from any tab, the system crashes

Steps

1. Log in as National Registrar
2. Click on any tab
3. Click on any application

**Actual Result:**

- System crashes

**Expected Result:**

- Should be navigated to the audit record page 

**Screenshot:**

![image](https://user-images.githubusercontent.com/105625699/171156958-626a9123-3a69-44f7-8614-222e2d208558.png)

**Video:**

https://user-images.githubusercontent.com/105625699/171157046-81a6bfff-1b02-479c-8258-2e19b9751e60.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**

- Username: joseph.musonda 
- password: test

**Comment by saima-alam** [comment]
@anny320, I'm getting this issue again only in Ready for review. This bug needs to be reopened. 

![image](https://user-images.githubusercontent.com/105625699/172144062-84298a30-bc71-479f-b454-4f28f5c04164.png)

**Comment by anny320** [comment]
completed
