### ISSUE TITLE
In form config, Phone number custom field is automatically becoming mandatory field

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3286]
**Bug description:**
In form config, Phone number custom field is automatically becoming mandatory field

**Steps to reproduce:**
1. Login as National System admin
2. Click Config> Click Declaration form
3. Click Configure in draft page
4. Click add of phone number
5.  set label both in english and french
6. Click Save and observe

**Actual result:**
Phone number custom field is automatically becoming mandatory field

**Expected result:**
Should not be mandatory since required for registration is OFF

**Screenshot:**
![phone number custom field automatically becoming mandatory field.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/b00fad7d-3b51-44d2-91d3-d370c039512d)

**Tested on:**
https://login.farajaland-config.opencrvs.org/

**Comment by anny320** [comment]
closed
