### ISSUE TITLE
Text gets overlapped in table view when viewing records started by field agents in performance

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3289]
**Bug Description:**

In the performance, When register selects an office and clicks on the view link beside Field Agents under the Sources of applications section, the Field agents type and office name is overlapping

**Steps:**

1. An deactivated field agent which type is health care worker is available in the location
2. log in as the Register
3. Go to Performance
4. From the location filter, select an office
5. Navigate to 'Sources of applications'
6. Click on View beside Field agents
7. Observe the type and office 

**Actual Result:**

- Field agents type and office name is overlapping

**Expected Result:**

- Field agents type and office name should not be overlapping

**Screenshot:**
![image](https://user-images.githubusercontent.com/105625699/171182497-04f8dbbc-ceaa-4d0f-bea2-b8903a532d37.png)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**
Username: kennedy.mweene
password: test

**Comment by soumita-dsi** [comment]
Could not replicate it

**Comment by saima-alam** [comment]
@anny320, This bug is fixed. This can be closed.

![image](https://user-images.githubusercontent.com/105625699/174978516-a6ec5f3c-9dca-40d8-a295-2a788f500f9b.png)
