### ISSUE TITLE
Record do not get submitted for a newly configured application for custom number field

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3290]
**Bug description:**
Record do not get submitted for a newly configured application, when user input value in custom number field

**Steps to reproduce:**
1. Login as National System admin
2. Click Config> Click Declaration form
3. Click Configure in birth v0
4. Click outside form canvas
5. Click add in number input
6. Add label in both english and French (example Doctor's serial number)> Click Save
7. Click Save and add description and save
8. Click 3dot menu> Click Preview> Click Preview
9. Logout
10. Login as FA/ RA/ Registrar
11. Declare a birth event
12. Enter number input in that number custom field (example Doctor's serial number)
13. Complete the full application and submit

**Actual result:**
Application goes to outbox and not submitted properly for number custom field

**Expected Result:** 
Should be able to submit the application

**Screenshot:**
![number custom field bug.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/70abefbe-6e27-4b47-ae9b-fc1710444849)

**Tested on:**
https://login.farajaland-config.opencrvs.org/

**Comment by SyedaAfrida** [comment]
@anny320 This bug is fixed
![Screenshot 2022-06-06 153447](https://user-images.githubusercontent.com/94350336/172144095-cf2e6897-e77d-4ff9-8679-29ba4943cf80.png)

**Comment by anny320** [comment]
completed
