### ISSUE TITLE
State and District registrars should be removed from team user list

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3291]
**Description:**
State and District registrars should be removed from team user list 

**steps:**
1. login as national system admin
2. goto team page
3. search ilanga district
4. observe Ilanga district team list

**Actual result:**
State and District registrars are showing in  team user list
![what](https://user-images.githubusercontent.com/105624748/171186583-714eae65-5b5c-4fb9-a8a8-d975be7263d1.PNG)

**Expected result:**
State and District registrars shouldn't be in team user list

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by Fariha-Amin** [comment]
@anny320  keeping it  blocked till performance tests are finished

**Comment by anny320** [comment]
@euanmillar flagging this ticket for your view to delete these user types, thanks

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**retest SS:**
![d](https://user-images.githubusercontent.com/105624748/172779443-7aab169b-ad29-4de6-9b8e-de8726dd9a6a.PNG)

**Comment by anny320** [comment]
completed

**Comment by Fariha-Amin** [comment]
@anny320  these registrars were deleted from the list previously but now they are again reappearing in the team list of Ilanga and Ibombo district 
![district](https://user-images.githubusercontent.com/105624748/174753056-a3dab722-bc15-48d1-99fc-70783ab007a1.PNG)
![state](https://user-images.githubusercontent.com/105624748/174753071-694a02ce-24c2-4a29-9069-9c16eda510b9.PNG)

**Comment by euanmillar** [comment]
I manually deleted them from the database previously .  On a restore these return. Essentially this is not a bug but a configuration issue of test users.  So there is no codefix required.  However, as this seems to keep causing confusion, I am deleting them forever from a backup so that they never return
