### ISSUE TITLE
Place of death not appearing on certificate

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3292]
Steps to reproduce:

Create a Death registration where place of death is set to "Same as deceased usual place of residence"

Notice the certificate place of death is empty:

![Screenshot 2022-05-31 at 17.03.40.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/0e5df8aa-5adc-40e0-9f5d-c0e76c7ba05c)

**Comment by anny320** [comment]
completed
