### ISSUE TITLE
System crash when clicked "Record corrected" from history line

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3295]
**Bug description:**
System crash when clicked "requested correction" from history line

**Steps to reproduce:**
1. Login as registrar
2. Go to ready to print
3. Click any record
4. Click Download> Click Correct record
5. Make any change
6. Click make correction
7. Click that application again from ready to print tab
8. Click Record corrected from History

**Actual result:**
System crash

**Expected result:**
 should show audit

**Screenshot:**
![record corrected.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/ed521f2a-ffe0-4372-9f0a-ff112054ba72)

**After clicking link in console:** 
Objects are not valid as a React child (found: object with keys {user, comment, createdAt, __typename}). If you meant to render a collection of children, use an array instead.

**Tested on :**
https://login.farajaland-qa.opencrvs.org/

**Comment by jpye-finch** [comment]
@SyedaAfrida Is this linked to any ticket that. It should not be 'Requested correction'

it should be 'Record corrected'

**Comment by SyedaAfrida** [comment]
@jpye-finch Updated

**Comment by azantor64** [comment]
https://user-images.githubusercontent.com/70468099/172357309-0c29626c-ae63-4548-8e93-9ae5fe0d3d05.mp4

**Comment by anny320** [comment]
completed
