### ISSUE TITLE
Remove internal calls to verifyToken

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#3296]
Currently as part of registerBirthDeclaration and markBirthAsRegistered mutations, we call POST /verifyToken 43 times. Let's change it so that the token only gets verified once at the gateway level.

https://kibana.farajaland-qa.opencrvs.org/app/apm/services/opencrvs_gateway/transactions/view?rangeFrom=now-15h&rangeTo=now&transactionName=registerBirthDeclaration%20markBirthAsRegistered&transactionType=graphql&comparisonEnabled=true&comparisonType=day&transactionId=0fd259a83f06ee29&traceId=51f101f012415f813769f7840cefed86

**Comment by euanmillar** [comment]
Remove calls to verifyToken from every microservice except config, gateway, countryconfig and webhooks.  Essentially there is no need for the createServer -> validate: validateFunc in the jwt setup for microservices which are not externally facing.  Verify when using the application that verifyToken is only called once for each operation.

**Comment by Zangetsu101** [comment]
Closed by #3689
