### ISSUE TITLE
In form config required for registration field is getting changed in birth declaration of child details page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3300]
**Bug description:**
In form config required for registration field is getting changed in birth declaration of child details page between Type of birth and Weight at birth

**Steps to reproduce:**
1. Login as National system admin
2. Click Configuration> Declaration form
3. Click configure/ edit in birth
4. In child details page, make  Type of birth mandatory
5. Do not change anything for weight at birth
6. Click Save> add description> click save
7. Logout from national system admin
8. Login as registrar
9. declare a birth declaration
10. Go to child details page and observe Type of birth and weight at birth

**Actual result:**
1. Type of birth is not mandatory
2. Weight at birth is showing mandatory

**Expected result:**
1. Type of birth  should be mandatory
2. Weight at birth should not be mandatory

**Screenshot:**
![weight at birth not mandatory.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/33aa901e-9184-4c9b-a9fe-719687192c95)
![weight at birth not mandatory2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/723392e7-3d47-4f71-a5ce-0beee04da44b)

**Tested on:**
https://login.farajaland-config.opencrvs.org/

**Comment by anny320** [comment]
closed
