### ISSUE TITLE
Form config: After configurating death form, death application are not submitted properly if tried to submit a death application

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3308]
**Bug description:**
After configurating death form, death application are not submitted properly if tried to submit a death application

**Steps to reproduce:**
1. Login as National system admin
2. Click Configuration> Declaration form
3. Click configure in death version
4. Click save
5. Add description> Save
6. Click 3 dot menu> preview
7. Logout
8. Login as FA/RA/ registrar
9. declare a death event
10. Submit

**Actual result:**
the death application is not found in any workqueue

**Expected  result:**
the death application should be found

**Screen recording:**

https://user-images.githubusercontent.com/94350336/171410085-22fe81fb-6303-45cc-9858-492d36c2afaf.mp4

**tested on:**
https://login.farajaland-config.opencrvs.org/

**Comment by SyedaAfrida** [comment]
@anny320 this bug is  fixed and can be closed
![config death](https://user-images.githubusercontent.com/94350336/172595045-53f1aece-c22e-4c81-9758-d7735103b3f3.png)

**Comment by anny320** [comment]
completed
