### ISSUE TITLE
"View" option should not show beside field agent in performance page for Performance Manager, when any office is selected

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3312]
**Description:**
"View" option should not show beside field agent, in Sources of applications field in performance page, for Performance Manager, when any office is selected.

**Steps:**
1.Login as Performance Manager
2. in performance page, select any office from location filter
3. scroll down to "Sources of applications" field
4. observe field agents from Sources of applications list

**Actual Result:**
"View"  option is visible beside field agent when office is selected. When "view" is clicked, field agent page is loaded and throw  an error message .

**Expected Result:**
"View" option should not show beside field agent in performance page for Performance Manager, when any office is selected

**ScreenRecording:**

https://user-images.githubusercontent.com/105624748/171564552-383ca72c-236b-43a6-a0b8-9cf26eddc6ea.mp4

![d](https://user-images.githubusercontent.com/105624748/171564916-e2cad6f1-c3a2-47b0-a234-d560d32c4498.PNG)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by euanmillar** [comment]
Closing in favour of this new ticket that has up to date rules: https://github.com/opencrvs/opencrvs-core/issues/3371
