### ISSUE TITLE
The first action in History for all the records should be Started

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3323]
**Bug description:**
The first action in History for all the records should be Started

**Steps to reproduce:**
1. Login as Registrar/ Registration agent
2. Navigate to all the tabs

**Actual result:**
Started history row is missed from all records except "my drafts"

**Expected result:**
In all records for all tabs the first row in history should be "Started"

**Screenshot:**
![jon.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/a9547585-ffd1-428b-8855-87f8fa437d05)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
We addressed this request for any drafts that are not submitted to the server.  They are then submitted to the server with the correct status which would be sent for review, or sent incomplete.  So I believe this requirement should be re-designed or closed.

**Comment by anny320** [comment]
closed

**Comment by jpye-finch** [comment]
can we reopen this? Regardless of the status. We should have a line item. 'Started'. 
So you know when the record was started.
