### ISSUE TITLE
Review page modal errors if there is no description

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3332]
As a quick fix I set the areYouSure copy to be an empty space:

https://github.com/opencrvs/opencrvs-core/pull/3329/files#r888015261

**Comment by euanmillar** [comment]
Refactor the description approach as we do not need any description in this modal

**Comment by Zangetsu101** [comment]
Done in #3835 and https://github.com/opencrvs/opencrvs-farajaland/pull/336
