### ISSUE TITLE
Page crash for National Sys Admin when click settings

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3336]
**Describe the bug**
Page crash for National Sys Admin when click settings

**To Reproduce**
Steps to reproduce the behaviour:
1.  Log in as National Sys admin
2. Click on profile 
3. Click on settings

**Expected behaviour**
Should show settings page
 **Actual Result**
https://images.zenhubusercontent.com/91778759/12c9d89a-84f7-47c8-93eb-4fda36f3cb20/screen_capture__35_.mp4

**Comment by emon-swe-sust** [comment]
I guess this will be fix by this PR https://github.com/opencrvs/opencrvs-core/pull/3337/files

**Comment by azantor64** [comment]
https://user-images.githubusercontent.com/70468099/172156392-5adc34f4-4121-42ae-93ea-39e597968e71.mp4

Passed. Can be closed. @anny320

**Comment by anny320** [comment]
completed
