### ISSUE TITLE
National Registrar can be created without Signature

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3340]
**Bug Description:**
When created National registrar the signature upload option doesn't appear and it can be created without a signature

**Steps:**

1. Log in as a National system admin
2. Click on Team
3. Select an address
4. Click on add new user
5. Create a National registrar
6. Click on Continue

**Actual Result:**

- National registrar is created

**Expected Result:**

- A Page for uploading the signature for the user should appear.  National registrar should not be created without a signature. 

Screen recording:

https://user-images.githubusercontent.com/105625699/171826220-6a299fc6-e51e-4f5a-8aa2-95e1be3b9846.mp4

Tested on:
https://login.farajaland-qa.opencrvs.org/

Username & Password Used:
Username: jonathan.campbell
password: test

**Comment by euanmillar** [comment]
Tahmid to work on adding a signature file to a Nat Reg in the user-mgnt service

**Comment by saima-alam** [comment]
@anny320 , This issue is resolved. For creating National registrar signature need to be uploaded. This can be closed.

Reference Video: https://user-images.githubusercontent.com/105625699/172793061-95dd685b-9c4e-4b03-8b21-d63d05af0481.mp4

**Comment by anny320** [comment]
completed
