### ISSUE TITLE
Type field is showing in the preview page of edit details for National registrar, registrar, registration agent , local and national system admin

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3341]
**Bug Description:**
The type field is showing in the preview page of edit details for the National registrar, registrar, registration agent, local and national system admin. But Type is not available for those users. 

**Steps:**

1. Log in as a National system admin
2. Click on Team
3. Select an address
4. Click edit details of National registrar, registrar, registration agent, local and national system admin
5. Observe the Type of field

**Actual Result:**

- The type is available. 

**Expected Result:**

- As type is not available for those users, the Type field should not show in the preview of edit details.

Screen recording:

https://user-images.githubusercontent.com/105625699/171836462-172279f7-171b-4dac-97b9-d8e2b27d2051.mp4

Tested on:
https://login.farajaland-config.opencrvs.org/

Username & Password Used:
Username: jonathan.campbell
password: test

**Comment by anny320** [comment]
completed
