### ISSUE TITLE
Death application can't be submitted  for attachment files

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3349]
**Describe the bug**
Death application can't be submitted  for attachment files 

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in as Registration agent 
2. Make a death application 
3. upload same type of files in attach support docs page
4. Submit the application 
5. See error 

**Error**
{"errors":[{"message":"Variable \"$details\" got invalid value \"DECEASED_DEATH_CAUSE_PROOF\" at \"details.registration.attachments[3].subject\"; Value \"DECEASED_DEATH_CAUSE_PROOF\" does not exist in \"AttachmentSubject\" enum. Did you mean the enum value \"DECEASED_DEATH_PROOF\", \"DECEASED_BIRTH_PROOF\", or \"DECEASED_ID_PROOF\"?","extensions":{"code":"BAD_USER_INPUT"}}]}

![image](https://user-images.githubusercontent.com/70468099/171851047-91fad714-a72a-44ec-b63a-a160fa5ff110.png)

**Expected behaviour**
It should be sent
**Actula result**

https://user-images.githubusercontent.com/70468099/171851088-7d0774e5-fce0-457f-91ff-12b2dcd4eaee.mp4

**Comment by azantor64** [comment]
https://user-images.githubusercontent.com/70468099/172336321-66d975cf-e93e-4866-bb66-141bcc3d3c57.mp4

Passed. @anny320

**Comment by anny320** [comment]
completed
