### ISSUE TITLE
Signature not blank if printing in advance

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3350]
**Describe the bug**
When printing a certificate in advance Signature is not blank if printing 

**To Reproduce**
Steps to reproduce the behaviour:

1. Log in as Registrar
2. Navigate to Ready to print
3. Download a record in Ready to Print
4. Click Print
5. Click Print in advance
6. View certificate preview
7. See the bug. The digital signature is present

**Expected behaviour**
it should be blank/ empty. So the Registrar can do a wet signature

**Screenshots**
![image](https://user-images.githubusercontent.com/70468099/171852045-f4839835-104a-4e67-8836-b3e1affbf9cb.png)
**Actual Result**
![image](https://user-images.githubusercontent.com/70468099/171852066-d3b1fdf9-5b94-4c19-821d-f623800ab06a.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Edge, Chrome

**Comment by Fariha-Amin** [comment]
@anny320  not fixed, need to be fixed again

**Retest Recording:**

https://user-images.githubusercontent.com/105624748/172306186-34adba6b-3668-40ba-8280-2fa9e0ed86c3.mp4

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Retest Recording:**

https://user-images.githubusercontent.com/105624748/172555633-15ffe9f6-92c1-4b53-b96b-5fe8f115568f.mp4

**Comment by anny320** [comment]
completed
