### ISSUE TITLE
Hard coded copy used on Create pin page

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3353]
**Describe the bug**
- copy on create pin is hardcoded.
- ticket is to add content keys
- SecureAccountView.tsx

**Copy**
title: Secure your account
description: Your personal identification number will be required to access your account
button: Create PIN

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/9df805ae-551e-4e0e-a17a-77af0fdb0145)
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/8934813d-db19-4254-b2a7-4c0e64a229f2)

**Comment by euanmillar** [comment]
@sadmananik I think you have addressed this already.  If that is true can you move to Code Review?

**Comment by sadmananik** [comment]
@jpye-finch @euanmillar Yes. These are fixed on [ocrvs-2977]( https://github.com/opencrvs/opencrvs-core/pull/3367
) and [ocrvs-2977](https://github.com/opencrvs/opencrvs-farajaland/pull/289)
![Screenshot from 2022-06-08 13-27-22](https://user-images.githubusercontent.com/36187489/172557639-5e85c235-7ae0-41c0-8c3d-8cafdb1d6a68.png)
![Screenshot from 2022-06-08 13-27-33](https://user-images.githubusercontent.com/36187489/172557652-08759ffd-3a44-48b0-b190-520f9bf90570.png)

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/174313555-29142eef-5aad-4e72-83f1-59355b0b3e11.png)
![image](https://user-images.githubusercontent.com/70468099/174313657-38ceb13a-ab09-4e82-9467-33f06dad8d73.png)
Passed. @eduffus
