### ISSUE TITLE
Register modal for registrar on declaration review page incorrect

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3363]
**Describe the bug**
Register module for registrar on declaration review page incorrect

**To Reproduce**
Steps to reproduce the behaviour:

1. Login as a registrar
2. Make a complete death declaration
3. click the register button - see the content showing on the button modal

https://www.notion.so/opencrvs/Copy-review-4bf01a73fe2946cf8384cb9f1dba1901

**Expected behaviour**
Register the event?

Cancel/ Confirm

**Screenshots**
![Screenshot 2022-06-03 at 06.14.41.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/dd59b9cc-6f79-457e-a123-b934a99800e6)
**Desktop (please complete the following information):**
 -desktop-  chrome

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by saima-alam** [comment]
@anny320 @emon-swe-sust, it is showing "Register the birth ?" but it should show
"Register the event?
Cancel/ Confirm"
See the proposed copy changs here : https://www.notion.so/opencrvs/Copy-review-4bf01a73fe2946cf8384cb9f1dba1901

![image](https://user-images.githubusercontent.com/105625699/172555060-22e40e95-ec27-485a-ac31-8a7fab3169a4.png)
