### ISSUE TITLE
When creating a user the username is blank. If we have already generated it, then we should show it.

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3374]
**Describe the bug**
When creating a user the username is blank. If we have already generated it, then we should show it.
**To Reproduce**
Steps to reproduce the behaviour:
1. .Login as a Sys Admin/ or National Sys Admin
2. go to team tab, create a new user
3. complete the details, view the review user details page - the row for username is not showing a username

**Expected behaviour**
If we have already generated it, then we should show it.

**Screenshots**
[](https://www.loom.com/share/114b449175564b239cbc311248622cdc
)**Desktop (please complete the following information):**
chrome

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/172814689-4e63859a-8af3-410c-90e9-61234a3108e5.png)

passed. @anny320

**Comment by anny320** [comment]
completed, create new user  preview, blank row was removed [Screenshot 2022-06-14 at 09.15.07.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/97dc5249-2b50-4dfb-983d-eeef010caba7)
