### ISSUE TITLE
National Registrar made a correction but history says "Requested Correction". Should be "Corrected record".

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3375]
**Describe the bug**
National Registrar made a correction but history says "Requested Correction". Should be "Corrected record".
**To Reproduce**
Steps to reproduce the behaviour:

1. Login as a National registrar
2. Open any record in the work queues ready to print/ ready to review
3. Make a correction on the record and submit
4. Search for the record and review the record history - it reads "requested correction "

**Expected behaviour**
Records corrected by the national registrar should reflect " Corrected  record" in the history
**Screenshots**
![Screenshot 2022-06-06 at 17.00.51.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/e71c17fd-42a7-466c-83fb-75b1d64bd212)
**Desktop (please complete the following information):**
 -chrome

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

Retest SS:
![d](https://user-images.githubusercontent.com/105624748/172547626-cd73a87f-d367-450c-8e8b-7fb0a79f2ac5.PNG)
![dd](https://user-images.githubusercontent.com/105624748/172547634-fd460064-c671-4da3-88a1-1224f46911e3.PNG)

**Comment by anny320** [comment]
completed
