### ISSUE TITLE
In field agent, column name is wrong in Sent for review tab

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3377]
**Bug description:**
In field agent, column name is wrong in Sent for review tab. Should be Sent for review in place of Sent for approval

**Steps to reproduce:**
1. Login as field agent
2. Click Sent for review
3. Observe the column names

**Actual result:**
Showing  Sent for approval

**Expected result:**
Should be Sent for review

**Screenshot:**
![emon.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/a01c1a88-1d27-4b57-9824-76303528608e)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by saima-alam** [comment]
@anny320, This is working expeacted. This can be closed.

![image](https://user-images.githubusercontent.com/105625699/172559504-f9216e35-aa90-4e4c-b626-9e10de742c57.png)

**Comment by anny320** [comment]
completed
