### ISSUE TITLE
In Field agent when searched for a certified record, the download icon is showing different in workqueue and audit record page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3378]
**Bug description:**
In Field agent when searched for a certified record, the download icon is showing different in workqueue and audit record page

**Steps to reproduce:**
1. Login as Field agent
2. Search for a certified record with their tracking id/ name
3. In workqueue obserse the download icon
4. Click on the name
5. In audit record page, observe the download icon

**Actual result:**
In initial state:
1. In workqueue showing downloaded green icon
2. In audit record showing download icon

**Expected result:**
In both case should be download icon

**Screenshot:**
![cer_downloaded.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/5376e91f-0558-45b2-b6cb-0ad38279cb92)
![cer_downloaded2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/d65f7f05-3cec-48ed-ab58-31f6d2880f1d)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by emon-swe-sust** [comment]
Will fixed by this pr https://github.com/opencrvs/opencrvs-core/pull/3387

**Comment by saima-alam** [comment]
@anny320 This is working as expected. This can be closed.

https://user-images.githubusercontent.com/105625699/172600087-878b6797-00d8-4118-9fce-ed6d14b9a3e5.mp4

**Comment by anny320** [comment]
completed
