### ISSUE TITLE
For field agent, in record audit page, the location links should be disabled

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3379]
**Bug description:**
For field agent, in record audit page, the location links should be disabled

**Steps to reproduce:**
1. Login as Field agent
2. Go to any tab
3. Click in the name of any record
4. Click on the location link

**Actual result:**
Location links render to team page with an error

**Expected result:**
Location links should be disabled

**Screen recording:**
https://images.zenhubusercontent.com/91778759/f793a03b-7192-412f-b708-46de6bc3ff8e/location_link_disabled_in_fa.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by emon-swe-sust** [comment]
Will fix by this PR https://github.com/opencrvs/opencrvs-core/pull/3387

**Comment by saima-alam** [comment]
@anny320 This is working as expected. The location link is disabled now. This can be closed.

![image](https://user-images.githubusercontent.com/105625699/172596666-b10158f5-ca2f-4d49-a67d-540d65f884ae.png)
