### ISSUE TITLE
 Copy change Requested correction to record corrected

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3384]
**Describe the bug**
 Copy change **Requested correction** to **Record corrected**

**Steps to reproduce:**
1. Login as registrar
2. Go to ready to print
3. Click any record
4. Click Download> Click Correct record
5. Make any change
6. Click make correction
7. Click that application again from ready to print tab
8. see Requested correction

**Expected behaviour**
Requested correction  will be **Record corrected**
**Actual Result![requested correction.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/146ad941-c2f8-4d2d-80a3-f59d08712d92)**

**Comment by anny320** [comment]
duplicate for #3375
