### ISSUE TITLE
Disable Location filter for all users except National Registrar

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3385]
**Describe the bug**
- users cans search for other office on the Registration by status table.
- only a National Reg should be able to. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as a Reg Agent or Registrar
2. Click on a status in the Registration by status table. (on your office Performance view)
4. See error. Location filter is active. They can nav to another location

**Expected behaviour**
- the Location filter is disabled. 
- same as the Field Agent table

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/4465a44e-a066-4861-bfb9-faeca54ccc73)

**Comment by Fariha-Amin** [comment]
@anny320  location filters disabled for RA and registrar . Can be closed.

**Retest Recording:**

https://user-images.githubusercontent.com/105624748/172792932-ae9cca1a-79b0-43dd-b205-accb11127fe8.mp4

**Comment by anny320** [comment]
completed
