### ISSUE TITLE
Correct Record is not showing Relationship to child if 'Informant type' is changed to someone else when reviewing an application

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3389]
**Bug Description:**

If Informant type is someone else for any birth/death application, 'Relationship to child' doesn't show when user do correct record. 

**Steps:**
1. An birth/death application is available in Ready for review where the informant type is father /mother 
2. Log in as Registrar
3. Go to Ready for review and find the birth application
4. Change the informant to Someone else and register the application
5. Go to Ready for print and click on the correct record of the application

**Actual Result:**

- Informant type is showing 'Required for registration' in place of Relationship to child

- After clicking on Change link beside the informant type  the Relationship to child field doesn't show any data

**Expected Result:**

- Informant type should show 'Relationship to child' if Someone else is selected as informant

- Clicking on the Change link beside the informant type  the Relationship to child field should show 
Screenshot:

![image](https://user-images.githubusercontent.com/105625699/172331967-bbc1b3fc-dd56-4368-af7c-32b1cc29e206.png)
![image](https://user-images.githubusercontent.com/105625699/172332033-65a89079-ad90-4949-81f5-edd169df7670.png)

**Comment by saima-alam** [comment]
@anny320, This is working as expected. Relationship to the child is appearing now when correcting record.  This can be closed.

![image](https://user-images.githubusercontent.com/105625699/173040338-4e5cc740-b1bf-4142-a81a-ca3ce4e41b50.png)

**Comment by anny320** [comment]
completed
