### ISSUE TITLE
UI issue in Fees Collected in Performance

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3391]
**Bug Description:**

If currency is changed to Bangladeshdeshi Taka from the configuration, it shows incorrectly in the Fees Collected of performance. 

**Steps:**

1. Log in as a National system admin
2. Click on Config > Application
3. Click on the General tab
4. Click 'Change'beside Currency
5. Change the currency to Bangladesh Taka
6. Click on Performance
7. Observe the Fees collected section

**Actual Result:**

- Currency is showing incorrectly. it shows 000 and taka symbol before the amount

Expected Result:

- taka symbol should show after currency. There should be no 0 before the amount. 

**Screenshot:**

![image](https://user-images.githubusercontent.com/105625699/172392286-fa678f03-0448-4a84-9b20-d1602af0d4a1.png)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![performance](https://user-images.githubusercontent.com/94350336/184869028-af4c34fc-c3ec-4e99-80d7-ba4fbfcb90b7.png)

**Comment by anny320** [comment]
completed
