### ISSUE TITLE
Form config: screen resolution issues, unable to scroll right in form configuration 

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3399]
**Describe the bug**
Form config: screen resolution issues, unable to scroll right -( mostly an issue with some windows devices)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to form config environment
2. Login as the national sys admin
3. Scroll down to configuration settings  and select a form
4. Unless the user reduces screen resolution to 90% not able to scroll or see scroll bar

**Expected behaviour**
Users should be able to scroll 
**Screenshots**
![image (17).png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/da277eaa-42a2-4cd7-a579-d022aa5b131c)
![image (18).png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/a25d8bb8-a2b3-4420-96b2-04c2f005ed76)

**Desktop (please complete the following information):**
 - chrome

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/175033695-725e2f24-cd4f-4629-8f3a-0de722eddd88.png)
Can be scrolled . @anny320 . waiting for your review
