### ISSUE TITLE
If Place of delivery is changed to Heath Institution from Residential address 'Central' doesn't show in province after clicking on change from review page

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3400]
**Bug Description:**

If in a birth application, the place of delivery is selected as Health Institution and the registrar changes the place of delivery to the Residential address. Then province dropdown doesn't show Central.

**Steps:**

1. A birth application that has 'Health institution' selected as the Place of delivery is available in Ready for review
2. Log in as a Registrar
3. Go to ready for review
4. Download the birth application
5. Click on Review
6. Click on change beside the place of delivery
7. Change the place of delivery to 'Residential address'
8. Select Farajaland as a Country

**Actual Result:**

- Province dropdown doesn't show central as an option. If the user keeps the province dropdown blank and clicks back to review, central shows as the province

**Expected Result:**

- Central should show in province Dropdown when country is Farajaland

**Screenrecord:**

https://user-images.githubusercontent.com/105625699/172591950-4fa31e35-fe9a-4b31-a120-10324efd0330.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**
Username: kennedy.mweene
password: test

**Comment by saima-alam** [comment]
@anny320, This can be closed. The issue is not there. 

https://user-images.githubusercontent.com/105625699/174972499-7a003b29-a281-48f7-b942-c93aa83f5236.mp4

**Comment by anny320** [comment]
completed
