### ISSUE TITLE
In birth declaration, Addresses donot appear in review page when no data is filled up from mother's details page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3402]
**Bug description:**
In birth declaration, addresses do not appear in review page when no data is filled up from mother's details page

**Steps to reproduce:**
1. Login as field agent
2. Declare a birth
3. Go to mother's detail page
4. keep all fields empty> Continue
5. Go to father's detail page
6. keep all fields empty> Continue
7. Go to review page
8. Observe mother's details - Usual place of residence

**Actual result:**
In review page showing- "Province required for registration"
When Click Change and go to Mother's detail page- Province = Central & District = Ibombo by default

**Expected result:**
In review page should show Province = Central & District = Ibombo

**Note: This bug will not generate if in mother's details page atleast one field is filled up**

**Screen recording:**

https://user-images.githubusercontent.com/94350336/172603111-1d24ee67-3918-475e-b4d7-99126fdcb366.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by atiqzaman-dsi** [comment]
I think all address related tickets are related.

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Retest Recording:**

https://user-images.githubusercontent.com/105624748/174241494-37f52702-1e5b-4eca-8bbe-f9ac537644d7.mp4
