### ISSUE TITLE
Stats box on Performance Management (currently correctly visible for all views other than Office view) is showing incorrect data:

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3403]
**Describe the bug**
Stats box on Performance Management (currently correctly visible for all views other than Office view) is showing incorrect data:

1. Registration Offices should show total Reg Offices in this Administrative Area (e.g. 16 for Farajaland, 4 for Province)
2. Registrars should show total No. of Registrars in this Administrative Area
3. Registrars to citizens should be a ratio (Registrars in this Administrative Area / Population in this Administrative Area) e.g. 1:10,000 

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as a registrar 
2. Click on Performance
3. Select Farajaland View
4. See stats table - showing incorrect data

**Expected behaviour**

1. Registration Offices should show total Reg Offices in this Administrative Area (e.g. 16 for Farajaland, 4 for Province)
2. Registrars should show total No. of Registrars in this Administrative Area
3. Registrars to citizens should be a ratio (Registrars in this Administrative Area / Population in this Administrative Area) e.g. 1:10,000 

**Screenshots**
![Screenshot 2022-06-08 at 13.03.44.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/5795bf92-5cbf-4829-9e59-c7e35eb62d3b)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by euanmillar** [comment]
The number of offices for Farajaland shows 3000+ in QA environment.  This appears to be a database issue in that environment only.  It is showing the correct number 16 in production.  @eduffus and @euanmillar and @rikukissa discussed and we decided this is not an issue that requires a bugfix.  So we can close this

**Comment by anny320** [comment]
closed
