### ISSUE TITLE
Repeated section on intro to birth declaration form - copy change required. 

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3410]
**Describe the bug**
Repeated section on intro to birth declaration form - copy change required. Should be content key register.eventInfo.birth.listItem2 only
**To Reproduce**
Steps to reproduce the behaviour:
1. Login as registrar
2. Click on + to create a new birth declaration
3. Review the copy on the intro page, repeated sections
_Make sure you collect the certificate. A birth certificate is critical for this child, especially to make their life easy later on. It will help to access health services, school examinations and government benefits.
Make sure you go and collect the certificate. A birth certificate is critical for this child, especially to make their life easy later on. It will help to access health services, school examinations and government benefits._

**Expected behaviour**
copy change required. Should be content key register.eventInfo.birth.listItem2 only

**Screenshots**
![Repeated copy (1).jpg](https://images.zenhubusercontent.com/61d3cc06859638b515717606/df9ff665-08ab-4232-bf74-0f20878a4c84)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 -chrome

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Retest SS:**
![d](https://user-images.githubusercontent.com/105624748/172797782-84123e82-e190-44ef-a33a-63568deee173.PNG)

**Comment by anny320** [comment]
completed
