### ISSUE TITLE
English First Name and Last Name on the Create New User form - should be "First Name" and "Last Name"

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3411]
**Describe the bug**
English First Name and Last Name on the Create New User form - should be "First Name" and "Last Name"

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as a national sys admin
2.go to team page, select an office and click  new user button
3. Scroll down to the name section English first name, English last name *
**Expected behaviour**
should be "First Name" and "Last Name"
**Screenshots**
![English first name.jpg](https://images.zenhubusercontent.com/61d3cc06859638b515717606/4cd4ee93-400b-440c-abee-df20a69ce9ac)

**Desktop (please complete the following information):**
 -chrome

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by saima-alam** [comment]
@anny320 , This is working as expected. This can be closed.
![image](https://user-images.githubusercontent.com/105625699/172798895-12bd6a3a-5b5a-4afc-ad9e-a5ba2fea5102.png)

**Comment by anny320** [comment]
completed
