### ISSUE TITLE
Confirm button doesn't get disabled when National registrar's signature is removed from preview page

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3416]
**Bug Description:**

User can remove the signature by clicking the delete icon from the Preview page and can click confirm. The confirm button doesn't get disabled. Then the national registrar can be created without the signature.

**Steps:**

1. Log in as a National system admin
2. Click on Team
3. Select an address
4. Click on add new user
5. Create a National Registrar
6. Click on Continue
7. Enter a signature and click continue
8. Click on the delete icon and remove the signature from the preview screen
9. Observe the Continue button

**Actual Result:**

- Continue button doesn't get disabled. User can click on Continue and National registrar is created without signature.

**Expected Result:**

- Continue button should get disabled when National registrar's signature is removed from preview page. 

**Screen record:**

https://user-images.githubusercontent.com/105625699/172791848-631bb684-3f3a-4125-9d76-be0b14846e3c.mp4

Tested on:
https://login.farajaland-qa.opencrvs.org/

**Comment by saima-alam** [comment]
@anny320 This is working as expected. This can be closed

https://user-images.githubusercontent.com/105625699/174036743-8a5e6564-e59c-4746-94b1-c09a539fd51b.mp4

**Comment by anny320** [comment]
completed
