### ISSUE TITLE
When creating a new user I cannot "quit" the process. I am forced to use the back arrow.

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3418]
**Describe the bug**
When creating a new user I cannot "quit" the process. I am forced to use the back arrow.

**To Reproduce**
Steps to reproduce the behaviour:
1. login as national sys admin
2. select the team tab
3. click new user button
4. enter the details required
5. click continue, in the preview if you want to terminate the process at this point, there is no cancel option, one has to use back arrow
**Expected behaviour**
Add a X on the  top right hand corner
(this also applies to the print certificate flow)
**Screenshots**
https://www.loom.com/share/93664aa29f5547b4b007ff58d7612dd5

**Desktop (please complete the following information):**
chrome

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by anny320** [comment]
@jpye-finch will we need design for this?

**Comment by Fariha-Amin** [comment]
@anny320  After quitting user creation process, if back button is pressed, previous data is deleted 

Steps to produce:

**Scenario1:**
1. login as any system admin
2.  goto team
3.  click create user in any area
4.  choose registrar as user type
5.  fill the form and goto signature upload page
6.  click cross button, you'll be nevigated to team page
7.  click back button, you'll be back to signature upload page
8.  again upload signature and proceed

**Actual result:**
User is asked to select Area and fill the user information form again
**expected:**
user should be navigated to review page directly

**Recording:**

https://user-images.githubusercontent.com/105624748/173296899-2f44195d-8966-4eab-8744-447c94b5b7c5.mp4


**scenario-2:**
1. login as any system admin
2.  goto team
3.  click create user in any area
4.  choose registrar as user type
5.  fill the form and continue
6. press cross button from review page
7.  press back button, **an empty review page without any data is shown**
8.  press cross button,  **it's not clickable anymore**
9. go back to signature page and click cross button

Actual result:
all data from team tab is missing. 

**Recording:**

https://user-images.githubusercontent.com/105624748/173297114-970820f4-5012-4b41-894a-d13c5eefd74e.mp4

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

Retested for the 2 issues from the last comment and also for printing flow

**Retest Recording:**

https://user-images.githubusercontent.com/105624748/174572264-e950c556-cc5f-456b-8245-84b2ead7cd68.mp4
