### ISSUE TITLE
Copy Change:  "Secondary Address" is expected in place of "Current address" in application review page, when number of residence is changed from 1 to 2 from form- config->settings

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3420]
**Description:**
Copy Change:  "Secondary Address" is expected in place of "Current address" in application review page, when number of residence is changed from 1 to 2 from form- config->settings

**Steps:**

1. login as national system admin
2. goto configuration
3. click declaration form and click "configure" of  a birth/death draft
4. from chlids details, goto settings 
5. change number of address from 1 to 2
6 login as fielld agent/Registration agent/registrar
7. declare a birth/death event which will have 2 address fields for child/deceased, informant, mother and father now
8. In application review page, observe the fields for secondary address

**Actual Result:**
"Actual address" is showing as the title of secondary address.

**Expected Result:**
"Secondary Address" is expected in place of "Current address" 

**Screen Recording:**
https://images.zenhubusercontent.com/91778759/c9e9161e-6314-4b49-baa9-7a12b8b6d9c2/bandicam_2022_06_09_15_39_37_451.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Retest SS:**

https://user-images.githubusercontent.com/105624748/174023301-dbd1e453-be4e-45ff-b01f-02b504acd705.mp4

**Comment by anny320** [comment]
completed
