### ISSUE TITLE
Collection form (death cert) for client side validation refers to mandatory fields for registration. Should just say "This is a mandatory field"

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3422]
**Describe the bug**
Collection form (death cert) for client side validation refers to mandatory fields for registration. This is not the registration process. Should just say "This is a mandatory field"
**To Reproduce**
Steps to reproduce the behaviour:
1. Login as registrar
2. Click on ready to print tab, select a death declaration, follow the prompts
3. Collectors details  - fill in details incomplete
4. See error message when mandatory fields are missing

**Expected behaviour**
Error message Should just say "This is a mandatory field"

**Screenshots**
![Collection form refers to mandatory fields for registration.jpg](https://images.zenhubusercontent.com/61d3cc06859638b515717606/b17635a1-46af-4561-8124-b90f1c8d8b7a)
**Desktop (please complete the following information):**
 - chrome

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/173336353-b0dcab80-9ba8-45ab-b0fd-1590a9cad2e1.png)
Passed. Can be closed. @anny320

**Comment by anny320** [comment]
completed
