### ISSUE TITLE
Modal showing wrong info in addition to the change made - only DoB was changed.

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3424]
**Describe the bug**

**To Reproduce**
1. FA created complete declaration.
2. Registrar updates DoB only and Registers.
3. Record Audit shows update but incorrect modal - should be just DoB change.
**Expected behaviour**
Record Audit shows update but incorrect modal - should be just DoB change.

**Screenshots**
![Update modal incorrect (1).jpg](https://images.zenhubusercontent.com/61d3cc06859638b515717606/0426730d-fca5-4a52-bef5-5b4b5a30eaaa)

https://www.loom.com/share/7ec1518881924f35a58c96bf2848a80d see video at 3:40. 

**Desktop (please complete the following information):**
 chrome

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by Zangetsu101** [comment]
@euanmillar I've been able to reproduce the issue so I'll be working on this today. This was happening when health institution was selected as place of birth

**Comment by Fariha-Amin** [comment]
@anny320  this can be closed, though still have issue of modal but hopefully will be solved with ticket   3114.

Retest Recording:

https://user-images.githubusercontent.com/105624748/173306995-384ab9a4-9910-441b-9834-2f5bcb9332ff.mp4

**Comment by anny320** [comment]
completed
