### ISSUE TITLE
Registration Agent title  appearing on certificate

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3425]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as a registration agent
2. Click on ready to print tab, select a record, download
3. Click print certificate, follow prompts
4. View the certificate
4. See error on the title below the signature

**Expected behaviour**
Only Registrar Title should appear in the certificates

**Screenshots**
![Screenshot 2022-06-09 at 13.54.26.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/9962b6ce-d582-49b6-9317-a589c62e7952)

https://www.loom.com/share/7ec1518881924f35a58c96bf2848a80d

**Desktop (please complete the following information):**
 -chrome

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/173084478-8f0c9698-5fdb-4fee-bb0f-2b6f578db903.png)

**Comment by anny320** [comment]
completed
