### ISSUE TITLE
On a slow connection, a registrar cannot be created in Ibombo by the National Sys Admin

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3426]
**Describe the bug**
Registrar cannot be created in Ibombo by the National Sys Admin
**To Reproduce**
Steps to reproduce the behaviour:
1. Set your network speed to slow 3G
3. Login as national sys admin
4. Click on team- new user 
5. create a registrar user for Ibombo using the supplied 1.5MB signature file
6. See error

**Expected behaviour**
Should be able to create additional registrars in an office
**Screenshots**
![Registrar cannot be created.jpg](https://images.zenhubusercontent.com/61d3cc06859638b515717606/da281345-a2e9-421c-bbb2-e04bcfde80b7)

https://www.loom.com/share/a3d86e0f970d4561ba286503184a6e15

**Desktop (please complete the following information):**
 - chrome

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by euanmillar** [comment]
@tahmidrahman-dsi sorry I worked on this already.   The solution is to increase the timeout from 30 seconds to 10 minutes, otherwise attachments dont upload on slow connections

**Comment by euanmillar** [comment]
Increasing timeout did not work.  Currently it is not possible to change signature on a slow 3G connection with a PNG of 1MB

**Comment by euanmillar** [comment]
![Ed_sig_opencrvs.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/103c9e07-ee32-4ec2-9c17-5202b4e71054)

**Comment by euanmillar** [comment]
Slow connectivity is blocking submission of images in birth and death reg and user creation

**Comment by euanmillar** [comment]
Solution is here: https://opencrvsworkspace.slack.com/archives/C02LU432JGK/p1655369946437219

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Retested With 1.9 MB file:**

https://user-images.githubusercontent.com/105624748/174536393-c6f9fa00-eb68-41c9-bf5e-c33e12406024.mp4
