### ISSUE TITLE
"Confirm your details" page when creating user. Incorrect inclusion of "create password...". Should be removed.

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3430]
**Describe the bug**
"Confirm your details" page when creating user. Incorrect inclusion of "create password...". Should be removed.

**To Reproduce**
Steps to reproduce the behaviour:
1. login as a national sys admin
2. clock on the team tab,  select a location - new user button
3. create a new user, follow prompts 
**Expected behaviour**
Incorrect inclusion of "create password...". Should be removed.

**Screenshots**
![Create user - confirm your details.jpg](https://images.zenhubusercontent.com/61d3cc06859638b515717606/6e3927f7-22db-422e-83f9-a0b62d64b71a)
**Desktop (please complete the following information):**
 - OS: [e.. iOS]

**Smartphone (please complete the following information):**

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by eduffus** [comment]
I have just reproduced this again: Steps to reproduce:
Nat Sys Admin creates a Registrar
Registrar logs in for the first time
Registrar creates a password
Registrar sets security questions and clicks continue

Image and loom video below:

<img width="773" alt="image" src="https://user-images.githubusercontent.com/57897493/174257855-9584f0aa-d747-4db4-92a0-8d6374d836ea.png">

https://www.loom.com/share/c575192fcefe461c894903bf176b9cbf

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/174550587-5cb79dd3-fd28-40e1-a9dc-44c4a7dca4f8.png)

**Comment by azantor64** [comment]
https://user-images.githubusercontent.com/70468099/174557422-8075a776-7680-4608-993c-0e4d928dcb89.mp4
No incorrect inclusion found. Passed. @eduffus @anny320 this is waiting for your review
