### ISSUE TITLE
Certified record shows no entry for certification on the record audit

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3431]
**Describe the bug**
Certified record shows no entry for certification on the record audit

**To Reproduce**
Steps to reproduce the behaviour:
1. login as registrar
2. Click on a record in ready to print queue
3. follow the prompts and print the record
4. Search for the record again, observe record audit trail, there is no entry for Certified

**Expected behaviour**

**Screenshots**
![Certified but no record audit of certification.jpg](https://images.zenhubusercontent.com/61d3cc06859638b515717606/2489d4ec-e835-48d6-af41-6d968b92675d)
https://www.loom.com/share/7ec1518881924f35a58c96bf2848a80d (minute 6:11)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/174575184-dd0d1aaf-4077-45c7-aa54-b4d432b861ba.png)

**Comment by azantor64** [comment]
Not passed. Certified record shows no entry for certification on the record audit
https://user-images.githubusercontent.com/70468099/174575417-250b07a8-3688-47d4-9167-f5c22e4ced3d.mp4

**Comment by anny320** [comment]
completed
