### ISSUE TITLE
Province not auto-selected when completing the address details on the form (informant and mother)

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3432]
**Describe the bug**
Province not auto-selected when completing the address details on the form (informant and mother): Birth declaration - informant is Grandfather

**Expected behaviour**

**Screenshots**
https://www.loom.com/share/7ec1518881924f35a58c96bf2848a80d (see video at 8.00)
**Desktop (please complete the following information):**
 
chrome

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by euanmillar** [comment]
Struggling to reproduce this

**Comment by euanmillar** [comment]
Hopefully this fix will also resolve this:

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Retest Recording:**
https://user-images.githubusercontent.com/105624748/174240594-b160e207-ce59-4121-a1e4-9bceebc3442e.mp4
