### ISSUE TITLE
Certificate label does not reflect the user role who registered the record

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3437]
**Bug Description:**

In the certificate label, the user role who registered the record doesn't appear. The user role of who is printing the certificate appears. It should be the 
Registrar/National Registrar who registered the record.

**Steps:**

1. Log in as a Registration agent
2. Click on Team
3. Select an address
4. Click on Ready to Print
5. Download an application
6. Click on Print
7. Go to Preview

**Actual Result:**

- The user role at the bottom of the name is showing the user role of who is printing the certificate.

**Expected Result:**

- The user role should be who registered the record

**Screenshot:**

![image](https://user-images.githubusercontent.com/105625699/173022884-ffbdf164-f191-4700-8a5d-7d5393799638.png)

**Video:**

https://user-images.githubusercontent.com/105625699/173032366-c4c84dc0-9101-4633-b645-8fa2f396376a.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**
Username: felix.katongo
password: test

**Comment by anny320** [comment]
duplicate ticket @saima-alam  #3425 so will close this ticket
