### ISSUE TITLE
Blank page showing when clicked on any record after changing page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3441]
**Bug description:**
Blank page showing when clicked on any record after changing page

**Steps to reproduce:**
1. Login as an user
2. Click on any application tab
3. Change page
4. Click on any record

**Actual result:**
the record disappears and show blank page

**Expected result:**
User should see record audit page

**Screen recording:**
https://images.zenhubusercontent.com/91778759/e1eaa0f8-c534-45c8-ba85-d55e600a139b/pagination_bug.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by eduffus** [comment]
Still not working as it should. Page does not go blank but flashes.
Blocked until 3500 fixed, then requires retest.
Moving back to QA queue.
@azantor64 to retest when unblocked.

**Comment by azantor64** [comment]
Yeah. Sure

**Comment by azantor64** [comment]
As [3500](https://github.com/opencrvs/opencrvs-core/issues/3500)is passed so it can be closed

**Comment by anny320** [comment]
closed
