### ISSUE TITLE
Disable "print in advance" for all offices apart from the registering office.

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3445]
**Describe the bug**
Record registered in office A. Informant goes to office B. Registrar in B prints the certificate.

Bug: they have the option to Print in advance. (This causes signature and title mismatch on certificate)

**Description of what you expected to happen.**
Expected: they can only print with digital signatures.

**Screenshots**

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by saima-alam** [comment]
@anny320, This is working as expected. This can be closed.

https://user-images.githubusercontent.com/105625699/175007613-5078b1ad-f737-47f7-9940-d7ff6c2b6cf0.mp4
