### ISSUE TITLE
Data generator: created user roles should be made logically possible

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#3449]
Currently, the demo data generator creates user that cannot be created through the UI. Fix the script so that the users created match the ones possible in the app. 

- [x] the only user role which has a type is a field agent.  The [script](https://github.com/opencrvs/opencrvs-farajaland/blob/521283aa4f8441d953867dbe99e7bd96483a4d7c/src/data-generator/users.ts#L215) should pick a random type from this array for field agents.  Other users type can be null / empty:

```
['HEALTHCARE_WORKER', 'POLICE_OFFICER', 'SOCIAL_WORKER', 'LOCAL_LEADER']
```

Add validation to the user creation API to ensure illegal combinations cannot be created.

- [x] In user-mgnt service createUser / updateUser, if the user role is field agent and the type submitted doenst match item in array throw an error.  "Type not supported for this user".  For any other user role, if type is submitted, throw the same error.

**Comment by euanmillar** [comment]
@Zangetsu101 dont put this into the QA column.  Once all data generator issues are merged, just leave them in Ready To Deploy.  I need to prepare an environment for QA to be able to test these.  I will do it later

**Comment by euanmillar** [comment]
@rikukissa this appears to be resolved on production. ![Screenshot 2022-09-21 at 17.13.49.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/c0131616-156e-40d1-8512-6291d76151c1)

**Comment by anny320** [comment]
completed
