### ISSUE TITLE
Data generator: make sure phone numbers of generated users are valid compared to dial code / phone number regexp in the app

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#3450]
- [ ] In data generator, [here](https://github.com/opencrvs/opencrvs-farajaland/blob/521283aa4f8441d953867dbe99e7bd96483a4d7c/src/data-generator/users.ts#L62) You want to pass to faker, the correct msisdn country code followed by the number of hashes associated with the correct number length like this:

```
faker.phone.number('+48 ## ### ## ##')
```

Call the config API to get the regexp.  

Import country code from the client-config and pass to the country-data library to get the country code.

Try this lib: https://github.com/wimpyprogrammer/regex-to-strings to generate the mobile numbers in place of faker, or use this lib to find out how many hashes to send to faker.

**Comment by euanmillar** [comment]
Checked on production and working as expected

**Comment by euanmillar** [comment]
![Screenshot 2022-09-21 at 17.11.17.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/29fe733b-ac4e-46fa-a05b-dc0fd47bb6f9) In case you would like to see an example

**Comment by anny320** [comment]
completed
