### ISSUE TITLE
System crash when clicked back button after closing an incomplete application

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3452]
**Bug description:**
System crash when clicked back button after closing an incomplete application

**Steps to reproduce:**
1. Login as any user
2. Declare a birth / death declaration
3. Continue till main point of contact
4. Close the application
5. Click back

**Actual result:**
System crash when clicked back

**Expected result:**
user should stay in homepage

**Console:**
breadcrumbs.ts:103 Error: Draft "8446f9fe-f044-4f13-8180-aa2440fe4ce3" missing!
    at Function.mapToProps (DeclarationForm.tsx:47:11)
    at n (wrapMapToProps.js:41:46)
    at n.mapToProps (wrapMapToProps.js:50:19)
    at n (wrapMapToProps.js:41:46)
    at selectorFactory.js:23:18
    at connectAdvanced.js:327:16
    at Object.useMemo (react-dom.production.min.js:165:493)
    at t.useMemo (react.production.min.js:25:113)
    at v (connectAdvanced.js:312:30)
    at Qa (react-dom.production.min.js:153:146)
(anonymous) @ breadcrumbs.ts:103
overrideMethod @ react_devtools_backend.js:4026
is @ react-dom.production.min.js:209
a.componentDidCatch.r.callback @ react-dom.production.min.js:227
ma @ react-dom.production.min.js:131
cs @ react-dom.production.min.js:212
_u @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
wu @ react-dom.production.min.js:248
su @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Xi @ react-dom.production.min.js:122
ru @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
w.setState @ react.production.min.js:12
(anonymous) @ Router.js:34
n @ history.js:155
(anonymous) @ history.js:173
notifyListeners @ history.js:172
C @ history.js:288
(anonymous) @ history.js:311
confirmTransitionTo @ history.js:145
I @ history.js:309
P @ history.js:294
n @ helpers.ts:77

**Screen recording:**
https://images.zenhubusercontent.com/91778759/7ca10b11-93dd-436b-b16e-002aa6c993fe/system_crash_for_back_button_when_no_draft_is_found.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by Fariha-Amin** [comment]
@anny320  passed, can be closed

**Retest Recording:**

https://user-images.githubusercontent.com/105624748/174239159-9b686d72-e052-4fd9-a055-b4a946d6f3a9.mp4
