### ISSUE TITLE
Country-logo takes time to be loaded  in login page

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3454]
**Describe the bug**
Country-logo takes time to be loaded  in login page

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [Login page](https://login.farajaland-qa.opencrvs.org/)
2. See error
![image.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/69fd41d6-8c2e-4a44-847e-0d086257eb98)
3. Reload 
4. See error again

**Expected behaviour**
Should be loaded in time

**Actual result**
![image.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/8f3d9e6b-8069-4276-b9d5-e8507880f371)

- [ ] Create an independent endpoint to serve the country logo from the config. Similar to conflicts - 2
- [ ] use that endpoint to load the logo in login - 1/2
- [ ] Create a new backup in farajaland with the smaller logo - 1/2

**Comment by rikukissa** [comment]
This is caused by login config taking a long time to download. Only after that we can load the country logo. The solution I'd suggest now is: 
- load login config before rendering anything. It increases the time the site is blank, but it minimises loading issues like this
- make the image resolution smaller. 240 x 240 is enough as we render it as 120 x 120.

In the future we can speed the whole process up by moving the file into a static file storage from where the browser is able to cache the file and render immediately.

**Comment by atiqzaman-dsi** [comment]
@jpye-finch could you please update the image?

**Comment by euanmillar** [comment]
This image should be replaced in the database and should be cached so that it doesnt load everytime.  Can we convert the base64 image data into an http:// URL so that the image gets cached

**Comment by rikukissa** [comment]
> This image should be replaced in the database and should be cached so that it doesnt load everytime. Can we convert the base64 image data into an http:// URL so that the image gets cached? We did something similar for the profile image

It's a good idea to turn it into an HTTP URL if it's not already, as it makes it easier for us to replace it with an actual url when we get the static file storage. It doesn't help caching however as the client still needs to load the full base64 as part of the configuration JSON 😕

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![logo in web](https://user-images.githubusercontent.com/94350336/182351093-cef61492-b101-46ac-802c-de4aa62bec37.png)
![logo in mob](https://user-images.githubusercontent.com/94350336/182351109-0260774f-630b-4647-aa4d-60da72c0b80c.png)

**Comment by anny320** [comment]
completed
