### ISSUE TITLE
Copy change: typo in mobile view modal

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3456]
**Bug description:**
Copy change: typo in mobile view modal

**Steps to reproduce:**
1. Login as national system admin in mobile
2. Click Configuration> Declaration forms
3. Click Edit/ Configure

**Actual result vs Expected result:**
Spelling mistake of available
![mobile view of dec.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/e0010d20-82f1-40b8-aba3-0d6f14878ef5)

**Tested on:**
 browser stack

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Retest SS:**
![d](https://user-images.githubusercontent.com/105624748/174032072-1ae8df68-2eb7-4635-bce0-f8b933436d9a.PNG)

**Comment by anny320** [comment]
completed
