### ISSUE TITLE
Duplicate record  message and icon should not be shown for any application that has been registered

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3460]
**Description:**
Duplicate record message and icon should not be shown for any application that has been registered.

**Steps:**
1. Login as registrar
2. goto ready to ready to review tab
3. review two duplicate applications
4. register two duplicate applications
5. goto ready to print page
6. download and goto record audit page of duplicate application

**Actual Result:**
Duplicate message and icon is shown in the record audit page. But duplicate icon not shown in the work queue.

**Expected result:**
Duplicate record message and icon should not be shown in workqueue and record audit page,  for any application that has been registered.

**Screen Recording:**
https://images.zenhubusercontent.com/91778759/e41ed433-2a69-4c10-8b88-fb3a8a206bef/bandicam_2022_06_13_17_32_06_357.mp4Tested on:
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by euanmillar** [comment]
Only show the duplicate icon and duplicate warnings on workqueue and review page if the status of the declaration is ready for review by a registrar

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Retest Recording:**

https://user-images.githubusercontent.com/105624748/174993775-8cd01798-c213-40c2-9eda-8292c0eac4cd.mp4

**Comment by Fariha-Amin** [comment]
After duplicate certificates are registered, duplicate icon is not shown in ready to print tab as expected. But after they are printed, if searched, duplicate icon is showing beside both of the applications in work queue ( In record audit page it's ok ).

https://user-images.githubusercontent.com/105624748/175240764-052184c3-1a97-47e8-9ae1-929d92f121be.mp4

**Comment by euanmillar** [comment]
Looks like a bug to me :)

**Comment by eduffus** [comment]
Agree. This has not been fully fixed. Move to to-do column.

**Comment by euanmillar** [comment]
@emon-swe-sust would you mind taking another look at this please?  Looks like one more place to check

**Comment by Fariha-Amin** [comment]
@anny320  can be closed 

Recording:

https://user-images.githubusercontent.com/105624748/175288102-0b19d5e4-42e5-4904-aabc-8c9137af5a9a.mp4

**Comment by anny320** [comment]
completed
