### ISSUE TITLE
Pagination should be added for Registration by status of Performance

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3462]
**Bug Description:**
On the  Registration by status of Performance, pagination is not showing according to requirements.

**Steps:**
1. Log in as a National system admin
2. Click on Performance
3. Click on any link of Registration by status where records are available in large number
4. Observe the pagination

**Actual Result:**

- Pagination is not showing according to the requirement of a table view in Figma

**Expected Result:**

- Pagination should be according to the pagination of the table view that is given in Figma.

**Figma Link:** https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=5796%3A18097 

**Screenshot:**
![image](https://user-images.githubusercontent.com/105625699/173352404-3e0bfb21-1648-4e65-bfd6-898c50525c87.png)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**
Username: jonathan.campbell
password: test

**Comment by saima-alam** [comment]
@anny320, Pagination is showing in Registration by status page. This can be closed.

![image](https://user-images.githubusercontent.com/105625699/174024510-85e0a500-96fd-4b04-a0bb-9ed2e90116f1.png)

**Comment by anny320** [comment]
completed
