### ISSUE TITLE
Birth doesn't remain selected in Registration by status of Performance

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3464]
**Bug Description:**

On the  Registration by status of Performance, Birth/Death doesn't remain selected although the records that show in the table are based on the selection of birth/death on the previous page. For example, if 'Births' is selected on the performance page, the record of birth shows in the registration by status page, but the 'Births' is not selected dropdown on the Registration by status  page 

**Steps:**
1. Log in as a National system admin
2. Click on Performance
3. Select an office in the Location Dropdown
4. Select Births on the dropdown
5. Click on any link of Registration by status 
6. Observe the 2nd Dropdown 

**Actual Result:**

- Nothing is selected on the dropdown although the Birth records are showing

**Expected Result:**

- Births/Deaths should be selected on the dropdown, based one which record is shown on the table 

**Screen record:**

https://user-images.githubusercontent.com/105625699/173362182-ce9f30c1-17c1-4e14-af09-4034f545f938.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**
Username: jonathan.campbell
password: test

**Comment by euanmillar** [comment]
The child pages' data when Selects or Location or Time Period changes will conflict with the parent pages' data selections when clicking back.  So it is the dev team's view that the UX on these child pages needs redesigned.

**Comment by euanmillar** [comment]
As we do on the completeness page view we should pass the search parameters forward and default event select.  Then ensure that search paramters are in the URL so that back and forward buttons work.

**Comment by saima-alam** [comment]
@anny320 This is working as expected. This can be closed

https://user-images.githubusercontent.com/105625699/174975132-24e16c42-0e61-4770-9bb1-6b50aea1479d.mp4

**Comment by anny320** [comment]
completed
