### ISSUE TITLE
Reinstate is not showing in History Action

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3470]
**Describe the bug**
Reinstate is not showing in History Action rather showing sent for approval

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in as Registrar
2. Go to ready for review
3. Download >Archive an application
4. Search that application
5. Reinstate that application
6. See in history
**Actual Result**
https://images.zenhubusercontent.com/91778759/544192a5-e2a1-41fa-a420-a464197a77da/opencrvs_register___13_june_2022.mp4

**Expected behaviour**
Reinstate action should be in History 
**Screenshots**
![image.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/2616fdf5-e57f-49f3-9409-0bdb4d7837d1)

**Desktop (please complete the following information):**
 - OS:Linux

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/174783319-811b7957-05d4-4d89-88c5-979cd2998900.png)
Passed. @anny320

**Comment by sadmananik** [comment]
@anny320 @euanmillar This should be fixed by https://github.com/opencrvs/opencrvs-core/issues/2689

**Comment by azantor64** [comment]
@euanmillar , reinstate is not showing in history action. Shouldn't it be fixed?

**Comment by euanmillar** [comment]
@Zangetsu101 can you please explain and demo the solution to @azantor64 as your fix is on QA

**Comment by azantor64** [comment]
@anny320 ,

-  **1st time arichive > Download > reinstate**  Reinstate not showing in history.

https://user-images.githubusercontent.com/70468099/174793987-5667a506-c22c-4368-98a5-2b7df52249fc.mp4

**Comment by anny320** [comment]
completed
