### ISSUE TITLE
Photo spins when adding comments

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3471]
**Describe the bug**
When creating an application with attachments, then when typing a comment on the Review Page, the photo spins

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as a registrar
2. Draft a birth or death application
3. Add an attachment
4. Go to the review form
5. Start typing a comment
6. Notice that the image spins

**Expected behaviour**
The image should not spin unless the rotate button is clicked on the image

**Screenshots**

Fast forward video to:  1:36
https://www.loom.com/share/7ec1518881924f35a58c96bf2848a80d

**Possible fixes**

Perhaps some kind of debounced effect

**Comment by eduffus** [comment]
Tested in config env
