### ISSUE TITLE
UI issue in mobile view : Can't login pages

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3474]
**Bug description:**
UI issue in mobile view : Can't login pages

**Steps to reproduce:**
1. Click Can't login
2. Observe all the pages in mobile view

**Actual result:**
There is no top or side spaces

**Screen shot:**
![ask.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/b4cadd39-5676-4738-a2c5-f6f606f064e3)
![ask2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/38c11b5d-7009-42b5-a8b7-ff39f3e55367)

**Tested on:**
Browser stack

**Comment by jpye-finch** [comment]
not using Content component. wasn't prioritised

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Retest SS:**
![b](https://user-images.githubusercontent.com/105624748/174586144-f5ab2e22-e212-4b51-a95b-3022f869f4dc.PNG)
![a](https://user-images.githubusercontent.com/105624748/174586156-fa3870bd-a8de-4f5c-b3b2-f3d1ef9e8726.PNG)
