### ISSUE TITLE
UI issue in mobile view : Team page

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3481]
**Bug description:**
UI issue in mobile view: Team pages

**Steps to reproduce:**
1. Login with a user who can view the team page
2. click on Team

**Actual result:**
Both sides of the page is is cut off. 

**Screenshot:**
![image](https://user-images.githubusercontent.com/105625699/173581999-ab55a543-7caf-45e4-b1d8-4f38580be4e0.png)

**Tested on:**
Browser stack

**Comment by jpye-finch** [comment]
we are not using the Content component. There is a PR I can see to add this

**Comment by azantor64** [comment]
![bs_realdroid_Mobile_Samsung Galaxy S8 Plus-7 0-1440x2960](https://user-images.githubusercontent.com/70468099/174543988-20485589-dfa5-4d14-9099-f30752125ec0.jpg)
Both side are not cut off. @jpye-finch  @anny320  waiting for review
