### ISSUE TITLE
Any draft cannnot be deleted properly from in progress tab

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3483]
**Bug description:**
Cannot delete any in progress declaration

**Steps to reproduce:**
1. Login To field agent/ Registration agent/ Registrar
2. Go to In progress record
3. Click Update in any record
4. Click 3 dot at the heading
5. Click Delete declaration
6. Observe in progress tab
7. Declare another birth/ death declaration
8. Click save and exit from any page
9. Observe the in progress tab

**Actual result:**
Previous deleted declaration appears again

**Expected Result:**
Should get deleted and do not appear in in progress

**Screen recording:**
https://images.zenhubusercontent.com/91778759/8a8ae304-9718-44ba-a2ac-09dd797bcf6b/delete_application.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Retest Recording:**

https://user-images.githubusercontent.com/105624748/174599540-e0d03e10-c845-45c9-b30e-94aa460f9308.mp4
