### ISSUE TITLE
UI issue in mobile view :Position of language dropdown in the login page should be fixed in different mobile resolutions

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3484]
**Description:**
Position of language dropdown in the login page should be fixed in different mobile resolutions

**Steps:**
1. Goto login page in mobile view
2.  change mobile screen resolution
3. observe the language dropdown in each  different mobile resolution

**Actual Result:**
Position of language dropdown changes in different resolution and overlaps with government logo

**Expected Result:**
Position of language dropdown in the login page should be fixed in different mobile resolutions

**Screenshots in different mobile views:**
![bandicam 2022-06-14 23-38-28-688.jpg](https://images.zenhubusercontent.com/6281e46d6f51be7532fe12bd/83f557c3-9c85-4e52-9159-f7cb79bb19e1)
![bandicam 2022-06-14 23-40-21-406.jpg](https://images.zenhubusercontent.com/6281e46d6f51be7532fe12bd/05c7e3fb-15c2-4e7a-8b35-528f84850c67)
![bandicam 2022-06-14 23-39-29-193.jpg](https://images.zenhubusercontent.com/6281e46d6f51be7532fe12bd/f9b7fdc8-0b55-4da1-8152-bfaa9149f626)
![bandicam 2022-06-14 23-39-47-259.jpg](https://images.zenhubusercontent.com/6281e46d6f51be7532fe12bd/1af3dda8-6f9a-440b-8cf6-261aa0974174)
![fariha](https://user-images.githubusercontent.com/105624748/173773848-2a720a19-3332-4283-92a2-f4e587afdb5f.png)

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by jpye-finch** [comment]
not a bug. Is there a phone size less than 360px!?

**Comment by Fariha-Amin** [comment]
> not a bug. Is there a phone size less than 360px!?

@jpye-finch  not all are less than 360, kindly check the dimensions of these two...it slightly overlaps with the logo with dimension change , is it a issue ?
![fariha](https://user-images.githubusercontent.com/105624748/173774749-7f4380c1-93a6-4349-a4b1-7003b0441b59.png)
![drop](https://user-images.githubusercontent.com/105624748/173774999-0b0194f4-33ae-45d2-9535-10128d2cfec7.jpg)

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Retest Recording:**

https://user-images.githubusercontent.com/105624748/175009162-57c3190f-0609-4d63-914f-0fee2ab78602.mp4

**Comment by anny320** [comment]
completed
