### ISSUE TITLE
Language doesn't change in log in page if user change language from settings

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3487]
**Bug Description:**

If the user changes the language from settings and logout, the language doesn't change on the login page.

**Steps:**

1. Log in to the application
2. Go to Settings
3. Change the language
4. Log out
5. Observe the language in login screen

**Actual Result:**

- Language doesn't change on the login screen

**Expected Result:**

- Language should change on the login screen if the user changes the language from the settings

**Screen record:**

https://user-images.githubusercontent.com/105625699/173820792-5572cf1d-cdb8-487f-bfbf-5e63635e5c2b.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

- [ ] Find a way on how this can be achieved

**Comment by euanmillar** [comment]
@eduffus @anny320 is this really priority medium?  I dont think we should worry too much about this right now.  Other things are probably more important

**Comment by euanmillar** [comment]
Could we send language choice in a URL param on logout when we redirect to login page

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/183389626-247bfa23-9826-4e94-b224-dac5e1630143.mp4

**Comment by anny320** [comment]
completed

**Comment by anny320** [comment]
completed
