### ISSUE TITLE
"No Results found" message is not visible in mobile view, when searched with invalid data

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3488]
**Description:**
"No Results found" message is not visible in mobile view, when searched with invalid data.

**Steps:**
1. Login as field agent/registration agent/registrar
2. click top search bar 
3. search an application with **invalid** tracking id/name/BRN/DRN/mobile number
4. search with **valid** tracking id/name/BRN/DRN/mobile number but with a space in the front

**Actual result:**
"No result found " message is not shown, blank page appears
**Expected result:**
"Record Results found" message should be visible in mobile view, when searched with invalid data.
**Recording:**

https://user-images.githubusercontent.com/105624748/173827474-bbaa72d8-7792-4f83-9307-907e234609ea.mp4

**Comment by Fariha-Amin** [comment]
@anny320  can be closed

**Retest Recording:**

https://user-images.githubusercontent.com/105624748/174783469-963ec300-fb28-4f95-8d2c-008e7fedda81.mp4

**Comment by anny320** [comment]
completed
