### ISSUE TITLE
Cant publish default form config

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3490]
**Describe the bug**
You cannot publish the default form config

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as a national system administrator
2. Go to Configuration > Declaration Forms
3. Click in Preview tab
4. Click Publish on birth or death  default configuration
5. You get an error when clicking publish on the modal

**Expected behaviour**
You should be allowed to publish the default configuration

**Screenshots**
![Screenshot 2022-06-15 at 21.39.16.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/daea70bf-cc2f-4262-8abd-3ca8c96020c4)

Error in Network Tab:
```
{"errors":[{"message":"Something went wrong on config service. Couldn't update form draft status","locations":[{"line":19,"column":3}],"path":["modifyDraftStatus"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: Something went wrong on config service. Couldn't update form draft status","    at Object.<anonymous> (/Users/euanmillar/Clients/Plan/Development/opencrvs-core/packages/gateway/src/features/formDraft/root-resolvers.ts:81:11)","    at Generator.next (<anonymous>)","    at fulfilled (/Users/euanmillar/Clients/Plan/Development/opencrvs-core/packages/gateway/src/features/formDraft/root-resolvers.ts:5:58)","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:95:5)"]}}}],"data":{"modifyDraftStatus":null}}

```

**Comment by azantor64** [comment]
@euanmillar , not possible to to test in that environment.

**Comment by euanmillar** [comment]
I have tested this many times on all environments in order to setup prod and qa.  I will close this and you can consider it resolved.
