### ISSUE TITLE
Total number of registrations is less than it should be

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#3492]
![image.png](https://images.zenhubusercontent.com/61dc3c9c2cdd207c355831e1/debdeb88-1f06-4cec-b8cb-486fc13fcf3f)

Total number of registrations shows a number less than the number of registrations in the metrics database. This causes the certification rate to sometimes exceed 100%. 

Seems to be caused by this line of code:
https://github.com/opencrvs/opencrvs-core/blob/ea59119bf6eca317daac0bf15ae654f7ad5963a2/packages/metrics/src/features/metrics/metricsGenerator.ts#L731

If counts are taken directly from the same measurement using `COUNT(*) as totals`, we see that the number differs depending on which field we use to take the total from

```
total_ageInDays total_compositionId
--------------- -------------------
306             316
```

**Comment by azantor64** [comment]
https://user-images.githubusercontent.com/70468099/174988732-c6038ce2-c47f-4809-ad3c-35c98de6ba45.mp4
Passed.
@rikukissa 
@anny320  this is waiting for your review.

**Comment by anny320** [comment]
completed
