### ISSUE TITLE
Assign / Un-assign should not be available for FA at all

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3502]
**Describe the bug**
Incomplete declaration: work queue vs detailed record view of conflicts
**To Reproduce**
Steps to reproduce the behaviour:
1. FA sends an incomplete declaration for review
2. RA downloads the record
3. Registrar views the record
4. When an FA send an incomplete declaration for review, then the conflicts functionality only works when the full record details are shown and not the work queue list.

**Expected behaviour**
Conflicts iconography and functionality needs to be the same whether you are viewing a record in the work queue list or have expanded out the record details.

**Screenshots**
https://www.loom.com/share/4ccd7c87e0d04a62b051bbd97fc94eda
**Desktop (please complete the following information):**
 -chrome

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by yeasinhossain-dsi** [comment]
Should fixed in https://github.com/opencrvs/opencrvs-core/pull/3506

**Comment by eduffus** [comment]
Tested and now working.
