### ISSUE TITLE
Conflicts not working when viewing a record from another office

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3507]
**Describe the bug**
Conflicts: not working when viewing a record from another office, one is still able to download and assign and already assigned record

**To Reproduce**
Steps to reproduce the behaviour:
1. RA in Office A sends declaration for approval
2. Registrar in Office A downloads the record
3. Registrar in Office B searches for the record

**Expected behaviour**
A registrar from another office should see that a record is already assigned

**Screenshots**
https://www.loom.com/share/0a53639d92d94e168ee28ffc2b192396

**Desktop (please complete the following information):**
 - chrome

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by eduffus** [comment]
Partly fixed. Correct functionality in the work queue view but not in the detailed record view.
See video below:
https://www.loom.com/share/3b16f57f4aba455a818602f1cc42f8a3

**Comment by SyedaAfrida** [comment]
@anny320 this bug is partially fixed. Registrar of office B can unassign registrar of office A from Record audit page. But the name initial keeps on appearing until the page is refreshed

https://user-images.githubusercontent.com/94350336/174962905-bd86359b-d85c-407e-9437-786fbec84d7f.mp4

**Comment by saima-alam** [comment]
@anny320 the issue mentioned by Syeda is fixed. This can be closed.

https://user-images.githubusercontent.com/105625699/175289202-9888d43d-6800-4512-b9b1-3f4eaa779fe2.mp4

**Comment by anny320** [comment]
completed
