### ISSUE TITLE
Conflict issue: Registration agent should not have option to assign themselves to any Sent for approval records

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3509]
**Bug description:**
Registration agent should not have option to assign themselves to any Sent for approval records

**Steps to reproduce:**
1. Login as Registration agent
2. Click sent for approval tab
3. Click Download in any record

**Actual result:**
There is a modal to assign Registration agent to that record

**Expect result:**
Registration agent should not have option to assign themselves from sent for approval tab. There should be no modal

**Screenshot:**
![sent for app.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/c079023c-6865-451d-be6d-48bd4f89c3e6)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by eduffus** [comment]
Retested and passed.
