### ISSUE TITLE
Conflicts: Record stays assigned to Registrar after printing.

### ISSUE THREAD

**Issue by eduffus** [opencrvs/opencrvs-core#3516]

**Comment by eduffus** [comment]
**Expected behaviour:** 
Registrar prints a death certificate
The status of the record changes to "certified"
The record audit includes an entry "certified"
The record is not assigned
An RA can assign the record to themselves for re-printing
**Actual behaviour**
Registrar prints a death certificate
The status of the record changes to "certified"
The record audit does not include an entry "certified"
The record appears assigned to the Registrar
An RA can assign the record to themselves for re-printing 
**Steps to reproduce:**
RA creates a complete death declaration
Registrar assigns record to themselves (in RTR) and registers
Registrar assigns record to themselves (in RTP) and prints
Registrar searches for record --> observe record
RA searches for record --> observe record

See video: https://www.loom.com/share/eb0f8541cb9b4ec78c7c1b1d02b54ec8

**Comment by SyedaAfrida** [comment]
@anny320 the bug mentioned in the last comment is not fixed

**Comment by anny320** [comment]
completed
