### ISSUE TITLE
Conflict bug: Application created by registration agent cannot be assigned and registered by registrar

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3518]
**Bug description:**
Application created by registration agent cannot be assigned and registered by registrar

**Steps to reproduce:**
1. Login as registration agent
2. Declare a birth/ death event
3. Click sent for approval
4. Logout from registration agent
5. Login as registrar
6. Download> assign that application
7. Click review
8. Click register

**Actual result:**
shows error message that the application is unassigned

**Expected result:**
Registrar should be able to register

**Screen recording:**
https://images.zenhubusercontent.com/91778759/65f54333-f081-4138-b06c-0fec3354eb83/application_created_by_ra_is_not_assigned_completely.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by anny320** [comment]
completed
