### ISSUE TITLE
Form config can't Published or Deleted when there are any declarations in Sent for approval/Ready for review

### ISSUE THREAD

**Issue by sadmananik** [opencrvs/opencrvs-core#3521]
**Describe the bug**

**To Reproduce**
1. Log in as RA
2. Create any birth/death declaration and sent it for approval
3. Log in as NSA
4. Try to Published or deleted any in preview birth/death form config 
5. See the error "Something went wrong. Please try again."

**Expected behaviour**
It should publish or delete the birth/death form config and also delete all the "Sent for approval/Ready for review" declarations

**Screenshots**
![bug.gif](https://images.zenhubusercontent.com/61890a0cad80f673106cbfb4/91e7b0a1-f912-4a16-b79e-2014b15ffb35) 

**Desktop (please complete the following information):**
 - Browser -  chrome

**Possible fixes**
Sent for approval declarations do not have "IN_CONFIGURATION" Extension on hearth "Task". But it should have this extension that will solve the bug.

**Comment by saima-alam** [comment]
@anny320 This bug is fixed. This can be closed.

https://user-images.githubusercontent.com/105625699/175243298-5f72b3c6-7019-4392-b5b8-f53a89daa3af.mp4

**Comment by anny320** [comment]
completed
