### ISSUE TITLE
Government Logo upload related issues

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3524]
**Description:**
Government Logo upload related 3 issues:

**Issue 1:**
SVG image type should be accepted as government logo

**Steps:**
1. login as national system admin
2. goto configuration>>application
3. click to change Government Logo
4. select a .SVG file

**Actual Result:**
SVG file is not uploabale, error message is shown
**Expected Result:**
SVG file should be accepted
**Recording_issue_1:**
https://images.zenhubusercontent.com/91778759/b97bf35a-9dbb-422a-9fb0-6631cd12ed09/svg_logo.mp4

**Issue 2:**
Previous error message is not being replaced with new error message

**Steps:**
1. login as national system admin
2. goto configuration>>application
3. click to change Government Logo
4. select a .png file larger than 2 MB ( see error message)
5. select a .jpg  file but less than 2 MB

**Actual Result:**
 Previous and new error message both are shown
**Expected Result:**
only jpg image not supported error message should be shown. As it is less than 2 MB, previous error message should be replaced
**Recording_issue_2:**
https://images.zenhubusercontent.com/91778759/75144843-06ce-4bba-aaf0-648dad9a50b6/error_logo.mp4

**Issue_3:**
error message should be shown when file with unsupported size is uploaded, not after clicking apply button
**Steps:**
1. login as national system admin
2. goto configuration>>application
3. click to change Government Logo
4. select a .png file larger than 2 MB (error message is expected to be visible now)
5. Click apply button

**Actual Result:**
Error message is visible after clicking apply button

**Expected result:**
Error message should be shown as soon as file with unsupported size is uploaded
**Recording_issue_3:**
https://images.zenhubusercontent.com/91778759/7fd9284c-c0cc-40df-b0ba-87f6288984ad/bandicam_2022_06_20_16_11_57_872.mp4

**Comment by euanmillar** [comment]
Not sure this is so important. PNG is enough no?

**Comment by jpye-finch** [comment]
yes .png is enough

**Comment by euanmillar** [comment]
Please close as PNG is enough

**Comment by anny320** [comment]
closed

**Comment by anny320** [comment]
closed, correct error message appearing when a different file type e.g jpeg uploaded
![Screenshot 2022-08-12 at 15.03.38.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/cbd44a1c-a3bd-4c7b-b75f-22cfb1fa2d5b)
