### ISSUE TITLE
National Registrar can not unassign local registrar and registration agent from a record

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3528]
**Bug Description:**

If a record is assigned to a local registrar or registration agent, the national register can not unassign them from the record. The national registrar should be able to unassign the local registrar and registration agent from a record.  

**Steps:**
1. Application is available which is assigned to the Local registrar/ Registration agent
2. log in as a National registrar
3. Find the application that is assigned to the Local registrar/Registration agent
4. Click the profile icon

**Actual Result:**

- Can not unassign the record. "[Username] at [specified] Office has sole editable access to this record" appears

**Expected Result:**

- Following modal for the 'unassign record' should appear and the National registrar should have the ability to unassign records. 

![image](https://user-images.githubusercontent.com/105625699/174604277-2d4730ed-7c61-4ee9-9412-c4f1713c25bc.png)

**Screen record:**

https://user-images.githubusercontent.com/105625699/174604663-e90c4b13-ee0c-41c9-b529-1c40d8af140d.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**
Username: joseph.musonda
password: test

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/174968725-1cdba758-19fd-4306-9dd2-5fc3c13153d9.mp4

**Comment by anny320** [comment]
completed
