### ISSUE TITLE
Form config UI issue : In mobile view, not published message of form config is showing in side nav of all user

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3530]
**Bug description:**
In mobile view, not published message of form config is showing in side nav of all users

**Steps to reproduce:**
1. Login as national system admin
2. Click Configuration > Declaration forms
3. Do not Publish birth/ death form
4. In mobile view, Login as FA/ RA/ Nation or local Registrar/ performance manager/ local System admin
5. View the side nav

**Actual result:**
not published message of form config is showing for all users

**Expected result:**
not published message of form config should only show for national system admin, not any other users

**Screenshot:**
![err](https://user-images.githubusercontent.com/94350336/174733201-31818343-2478-4d9e-89d6-50b1e0c70485.png)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
Lets hide this warning on mobile

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/175012835-dfba6f48-f770-4535-a6b4-126a592294a7.png)

**Comment by azantor64** [comment]
![image](https://user-images.githubusercontent.com/70468099/175020186-58590c9c-35d9-487b-990f-96aa594b692b.png)
![image](https://user-images.githubusercontent.com/70468099/175020546-75c77456-efd3-4a20-8863-05aea353d40e.png)

**Comment by anny320** [comment]
completed
