### ISSUE TITLE
Conflict bug in slow net connection: takes long time to load icon and always show default icon for all users in place of Users initials

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3536]
**Bug description:**
Conflict bug in slow net connection: takes long time to load icon in workqueue/ record audit page and always show default icon for all users in place of Users initials

**Steps to reproduce:**
1. In slow net login to RA/ local or national registrar
2. Observe the records which are assigned to other users

**Actual result:**
1. It takes long time to load profile icon if no profile image is set to that user
2. After it loads, show default icon for all users

**Expected result:**
1. In slow net, even if no profile image is set to that user, profile icon should load fast
2. Should show user name initials

**Screen recording:**
https://images.zenhubusercontent.com/91778759/e774e418-8ad0-4ec1-9558-bba90c85f6ef/in_slow_net__takes_long_time_to_view_icon_and_show_default_icon_for_all_users__1_.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
I think we can't get around to this at the moment

**Comment by euanmillar** [comment]
We could replace Gravatar or whatever we are using and instead create a circle with some initials when creating / editing an issue.  We need to create another improvement ticket.
