### ISSUE TITLE
When language is set to French and any application is printed, Role field in certificate should not be French

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3540]
**Description:**
When language is set to French and any application is printed, Role field in certificate should not be French.

**Steps:**
1. login as registrar/national registrar
2. goto ready to print
3. download any application, and print it
4. observe the Role field under registrar's name

**Actual Result:**
Role "Registrar" is translated to french. "Bureau d'enregistrement)"  is showing

**Expected Result:**
Everything in the certificate should be in English. When language is set to French and any application is printed, Role in certificate field should not be French.

**ScreenRecording:**
https://images.zenhubusercontent.com/91778759/5eb398dc-1044-4d84-afc4-ad4d0b0090f2/french.mp4

Desktop:
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by Fariha-Amin** [comment]
@anny320  passed, can be closed

**Retest SS:**

https://user-images.githubusercontent.com/105624748/175225020-ed8091db-127f-44e2-9f78-cba8cf88fb0b.mp4

**Comment by anny320** [comment]
completed
