### ISSUE TITLE
Spinner size is large in accordance with design

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3542]
**Describe the bug**
Reduce spinner size to 24x24px On Performanc

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in as any user who has performance page
2. Navigate to performance 
3. Observe Spinner

**Expected behaviour**
Reduce spinner size to 24x24px. On Performance
**Actual Result**
![image.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/1dc41dd5-449d-429c-8518-6dd28a0c88d0)

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![loading](https://user-images.githubusercontent.com/94350336/182544178-3859a228-c5f7-4969-8b81-2d2a4dafe01f.png)
![ploading in mbile](https://user-images.githubusercontent.com/94350336/182544196-102d5aeb-1f07-4b9b-a5f6-873d32ce6914.png)

**Comment by anny320** [comment]
Completed
