### ISSUE TITLE
Retrieved, Assigned, Unassigned record history actions

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3544]
### Description

- now that we have conflicts we should update the Record History line items to reflect the action of downloading and assigning a record. So that the action copy isn't always 'Downloaded'

### Acceptance criteria

GIVEN a field agent downloads a record
THEN the action is Retrieved

GIVEN a Reg agent downloads and assigns a record in Sent for approval
THEN the action is Assigned 

GIVEN a Reg agent or Registrar downloads and assigns themselves to a record
THEN the action is Assigned

GIVEN a Reg agent or Registrar unassign themselves from a record
THEN the action is Unassigned

GIVEN a Registrar unassigns someone from a record
THEN the action is Unassigned

### Design
https://www.figma.com/file/8SKJA7QJJkwzzdLTxVbC8c/OpenCRVS-Specs-v2?node-id=1%3A3

### Dev-tasks

- [ ]  Task 1

**Comment by euanmillar** [comment]
For now, we should not change the backend and potentially just hide the downloaded rows?  However ... I think that conflicts is such a new feature that having downloaded as a separate history item revealing a client that has downloaded and accessed PI as separate to the act of assigning and unassign-ing is useful for the product

**Comment by euanmillar** [comment]
@Zangetsu101 I think we need to remove the "Downloaded" rows in the history table for Reg Agent and Registrar with the exception of FA.  We need to keep the Downloaded as a separate task in the backend but it is weird from a user perspective to see all these rows in the table.  Maybe you can discuss each case with @jpye-finch when you are looking at this.

**Comment by jpye-finch** [comment]
I will update the Record Audit table to reflect the requirements notion.so/Record-Audit-5ea0204d2b6c40858e772028784db864

**Comment by euanmillar** [comment]
@eduffus @anny320  could you refer back to this Slack conversation we had today regarding search: https://opencrvsworkspace.slack.com/archives/C02LU432JGK/p1663249315829859 and reflect on the proposal in this ticket and Notion doc?  Perhaps you wish to add the search use case and refer to @jpye-finch 's proposed changes.  From a tech point of view:  In the backend DOWNLOADED and ASSIGNED are the given names for different statuses as they needed to be for different users.  Essentially a searching system has been applied the same status to save development time. There was no point creating an explicitly new status for essentially the same action: download of composition data including potentially attachments.  I think in that ticket we need to have some explicit copy and UI requirements case by case for every user ... e.g.  "As a Field Agent when I download the application, the DOWNLOADED status should be represented by the copy "Retrieved"" - Note they do not assign.  "As a Registrar and Registration agent, the DOWNLOADED and ASSIGNED statuses should be combined into a single row with the copy "Assigned"".  As an External System API, could the DOWNLOADED status should be represented by the copy "Retrieved" too?

**Comment by eduffus** [comment]
I think "retrieved" is about the best word to use for all these cases where the user or system pulls data from the system (as in the case of FA or the API request). Another option would be accessed, but that doesn't give the same meaning of being downloaded, which is actually the case.
So I think: 
GIVEN a field agent downloads a record
THEN the action is Retrieved

GIVEN an external system searches for and downloads a record
THEN the action is Retrieved

**Comment by SyedaAfrida** [comment]
**Bug:**
1. In field agent, the retrieved action modal of requires updates show reason of rejection

https://user-images.githubusercontent.com/94350336/203497944-1caf83e5-a341-419f-aecf-51db6c581a54.mp4

2. Sometimes assign unassign modal do not appear and directly gets assigned/ unassigned. This happens for all the workqueues

https://user-images.githubusercontent.com/94350336/203498237-a3f23d65-39ff-487d-9831-fcfbeb401b22.mp4

**Comment by SyedaAfrida** [comment]
@anny320 the bugs for this ticket are now fixed and can be closed

https://user-images.githubusercontent.com/94350336/206669132-c8748d45-e2f8-41f7-bb87-02b25a84515e.mp4


https://user-images.githubusercontent.com/94350336/206669186-253052a5-1e70-4835-a577-b62ab75e6304.mp4

**Comment by anny320** [comment]
completed
