### ISSUE TITLE
Conflict bug: when searched an assigned application, profile icon not showing only in record audit page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3545]
**Bug description:**
Conflict bug: when searched an application assigned user not showing only in record audit page, but working fine in workqueue

**Steps to reproduce:**
1. Login as Registration agent/ registrar/ national registrar
2. search any assigned application with tracking id / name
3. observe the workqueue
4. click the application
5. Observe the record audit page

**Actual result:**
Profile icon not showing in record audit page, but showing in workqueue

**Expected result:**
Profile icon should show record audit page and workqueue

**Screenrecording:**
https://images.zenhubusercontent.com/91778759/71138414-b4a3-480a-8144-3fdbc6925715/downloads___21_june_2022.mp4

 **Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by SyedaAfrida** [comment]
@anny320 the fix for this ticket will be similar to #3507

**Comment by emon-swe-sust** [comment]
![bug_conflicts](https://user-images.githubusercontent.com/43314141/175233302-aa16d5d3-c768-4ef0-bedd-d6ccdef4cf00.gif)

This bug is already fixed

**Comment by saima-alam** [comment]
@anny320, This bug is fixed. This can be closed

https://user-images.githubusercontent.com/105625699/175267314-59f77a7f-28ce-490d-b22d-e09e146b55b8.mp4

**Comment by anny320** [comment]
completed
