### ISSUE TITLE
Conflict bug: Registration agent showing assigned if Registration agent rejects any application

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3549]
**Bug description:**
Conflict bug: Registration agent showing assigned if Registration agent rejects any application, when logged in as registrar in Requires update tab

**Steps to reproduce:**
1. Login as registration agent
2. Go to ready for review
3. Download> assign that record to RA
4. Click review
5. Click reject> add comment > click reject
6. Click and Observe Requires update tab
7. Logout from RA
8. Login as Registrar
9. Click and Observe Requires update tab

**Actual result:**
1. In RA's requires update, that record is not assigned
2. In registrar's requires update, that record is assigned to RA

**Expected result:**
In both requires update that application should be unassigned

**Screen recording:**
https://user-images.githubusercontent.com/94350336/174584913-e78ec8b1-bc7e-401f-853f-eec6fb2f57c7.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by saima-alam** [comment]
@anny320 This bug is fixed. This can be closed.

https://user-images.githubusercontent.com/105625699/175235538-c9e85a1b-573d-44fe-8e82-422e0535723e.mp4

**Comment by anny320** [comment]
completed
