### ISSUE TITLE
Add new user and Location search button are not visible in mobile view for local system admin

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3550]
**Bug Description:**

In mobile view add new user button and location search icon are not showing. Add new user button and location search button should for the local sys admin   

**Steps:**

1. Log in as a Local system admin from mobile
2. Click on Team
3. Observe on the top left side 

**Actual Result:**

- There should be Add new user and Location search button

**Expected Result:**

- Add new user and the Location search button is not showing in the mobile view.

**Figma design**: https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=3219%3A60833

**Screenrecord:**

https://user-images.githubusercontent.com/105625699/175244629-7c3509d4-3f69-43b9-b34c-8c4deaa05944.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username & Password Used:**
- Username: emmanuel.mayuka
- password: test

**Comment by euanmillar** [comment]
Add new user button should be available on a mobile, but not location search.  @jpye-finch do we not also need a mock up of where this should go, but please understand that the Office name could stretch the width of the view, so how would the text flow around the create user button on a mobile

**Comment by jpye-finch** [comment]
this is the current build 
<img width="386" alt="image" src="https://user-images.githubusercontent.com/46478402/176453297-abca0a86-f111-4cbb-b939-029af728c0e6.png">

so you can search and add a new user on mobile

**Comment by jpye-finch** [comment]
need a new ticket to use the Content component on the location search page. 

so we can close this

**Comment by SyedaAfrida** [comment]
@anny320 this bug is not fixed yet

**Comment by SyedaAfrida** [comment]
@anny320 this bug is now fixed with the ticket- #2917 . so this can be closed
![mob](https://user-images.githubusercontent.com/94350336/186353127-e4e78496-4ef0-45a6-99a7-d2c6bcfec560.png)

**Comment by jpye-finch** [comment]
Sorry missed my initial mention to this ticket. What is the reason why location search is not available? Local system admin should be able to search for other offices. Same as National System Admin

**Comment by SyedaAfrida** [comment]
@jpye-finch so should local system admin will also have access to edit, deactivate, create users of other offices?

**Comment by euanmillar** [comment]
Local System Admin is currently tech designed to be in control of a single office of the lowest administrative level

**Comment by anny320** [comment]
closing issue, new ticket created for a state-level system admin role [3914 ]( https://github.com/opencrvs/opencrvs-core/issues/3914 )
