### ISSUE TITLE
Conflict bug: When registrar/ RA assign themselves to any record created by FA, FA cannot download that record from Sent for review

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3551]
**Bug description:**
When registrar/ RA assign themselves to any record created by FA, FA cannot download that record from Sent for review. They can only download if Registrar/ RA unassign themselves again.

**Steps to reproduce:**
1. Login as RA/ Registrar
2. Download> assign to any record created by FA
3. Logout
4. Login to FA
5. Download that application and observe
6. Logout
7. Login to RA/ Registrar
8. Unassign from that record
9. Logout
10. Login to FA
11. Download that application and observe

**Actual result:**
1. When registrar/ RA assign themselves to any record created by FA, FA cannot download that record from Sent for review
2. When registrar/ RA unassign themselves to any record created by FA, FA can download that record from Sent for review

**Expected result:**
When registrar/ RA assign themselves to any record created by FA, FA should be able to download that record from Sent for review

**Screen recording:**
https://images.zenhubusercontent.com/91778759/e7037052-761a-445d-8a0d-a2bbf3544f28/opencrvs___22_june_2022.mp4

**Note:**
Same bug is appearing in requires update of Field agent

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by saima-alam** [comment]
@anny320, This bug is fixed. This can be closed.

https://user-images.githubusercontent.com/105625699/175293176-7f039035-cbbe-44f4-8cc3-fbc0001d927f.mp4

**Comment by anny320** [comment]
completed
