### ISSUE TITLE
FA "Sent for review" column in "Sent for review" tab doesn't show original time of submission.

### ISSUE THREAD

**Issue by emon-swe-sust** [opencrvs/opencrvs-core#3552]
https://www.loom.com/share/7af44f8ad97c4532bcb7ea98f6e24bda

FA "Sent for review" column in "Sent for review" tab doesn't show original time of submission. Rather it shows the time of latest submission status changing time. We don't have the original creation time of declaration for now.

**Comment by euanmillar** [comment]
Breaking change. Populate in Elastic for legacy data

**Comment by euanmillar** [comment]
The started at time is not in ElasticSearch according to Emon which the cause of this issue. We need to research it.

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/193537049-48226cd7-78f0-4b57-b774-5f976d4e9437.mp4

**Comment by SyedaAfrida** [comment]
**Bug:**
If a registration agent directly sends an application to registrar, the sent for review column is showing blank .

https://user-images.githubusercontent.com/94350336/193555492-a8c79301-a877-4afd-9f7b-b0a6aa530150.mp4

**Comment by rabiulislamanik** [comment]
> **Bug:**
> 
> 1. If a registration agent directly sends an application to registrar, the sent for review column is showing blank .
> 
>  3552.bug.mp4 
> 2. When Field agent sends an incomplete application, The "Sent for review" column is showing blank in Sent for review tab of Field agent
> 
>  sent.for.review.column.is.blank.when.sent.an.incomplete.application.mp4

**Comment by rabiulislamanik** [comment]
> **Bug:**
> 
> 1. If a registration agent directly sends an application to registrar, the sent for review column is showing blank .
> 
>  3552.bug.mp4 
> 2. When Field agent sends an incomplete application, The "Sent for review" column is showing blank in Sent for review tab of Field agent
> 
>  sent.for.review.column.is.blank.when.sent.an.incomplete.application.mp4

@Zangetsu101 this pr fixes this https://github.com/opencrvs/opencrvs-core/pull/4042 issue that @SyedaAfrida mentioned

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/195600422-a20d238c-034e-4822-98e3-0857ec85a5a0.mp4

**Comment by anny320** [comment]
completed
