### ISSUE TITLE
Hotfix: Server firewall not blocking Elasticsearch

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#3556]
It is currently possible to access Elasticsearch directly with a port number by using a URL like 
https://register.farajaland.opencrvs.org:9200/ if 9200 is exposed from the docker network. 

We should only really be exposing 443 (HTTPS) port from the servers as someone might accidentally expose one of these ports.

Traefik seems to expose all ports that are mapped by the Docker Swarm and this overrides ufw settings.

**Comment by euanmillar** [comment]
We need 9200 exposed in order for the Elasticsearch backup to work.  As it password protected anyway, this is probably not such a big problem.  @rikukissa I think we can close this.

**Comment by rikukissa** [comment]
Isn't the backup script in the docker network thought?

```
# Register backup folder as an Elasticsearch repository for backing up the search data
#-------------------------------------------------------------------------------------
docker run --rm --network=$NETWORK appropriate/curl curl -XPUT -H "Content-Type: application/json;charset=UTF-8" "http://$(elasticsearch_host)/_snapshot/ocrvs" -d '{ "type": "fs", "settings": { "location": "/data/backups/elasticsearch", "compress": true }}'

# Backup Elasticsearch as a set of snapshot files into an elasticsearch sub folder
#---------------------------------------------------------------------------------
docker run --rm --network=$NETWORK appropriate/curl curl -X PUT "http://$(elasticsearch_host)/_snapshot/ocrvs/snapshot_$BACKUP_DATE?wait_for_completion=true&pretty"
```

So it should be able to connect elasticsearch without us exposing the ports to the host machine. If we want to go with secure by default approach, then we should restrict the access as much as possible. 

```
curl http://register.farajaland.opencrvs.org:9200/
```

Seems to still also be responding from the public internet. Password protection is a good start, but the credentials can be accidentally leaked or the password bruteforced
