### ISSUE TITLE
Ask for date of birth of Informant for death declaration

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3561]
### Description

- adds date of birth for an informant in death declaration

### Acceptance criteria

GIVEN I am completing a death declaration
WHEN on the Informant details
THEN show date of birth question

### Design
https://www.figma.com/file/NxSCdXCetyZsr26v4aiaxO/Fajarland-Death-Declaration-Forms?node-id=1%3A2

### Dev-tasks

- [ ]  Edit form
- [ ] Edit cypress tests - in workflow virtual box we need to select the cypress version - npx cypress run instead of npm install -g cypress 
- [ ] data-generator may need a change

**Comment by euanmillar** [comment]
Database change is a breaking change.  If this is marked as required for registration, for all existing OpenCRVS Registrations in v1.01. that do not have a date of birth for informant, what do we do?  When those records are corrected, this value will be marked as "required", but the user will not know the answer.  How should a system admin who has implemented v1.0.1 migrate this new value?

**Comment by euanmillar** [comment]
@eduffus @jpye-finch @anny320 this remains blocked in Tech Design at present as we are not sure how a migration between versions would cope with this requirement, especially if a previously submitted form is corrected and informant d.o.b. is now a required field. We need to meet to discuss the risk

**Comment by euanmillar** [comment]
The decision is that we should get this in for Nigeria as the risk is low that any real registrations exist using v1.0.1 at this time particularly given the imminent release of v1.1.0

**Comment by euanmillar** [comment]
@jpye-finch just waiting on the decision on which field is configurable in death:

https://www.notion.so/opencrvs/Default-form-config-fields-0d27f0edac2f42fa956c0ece91e45984

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/191953679-a4ee1ac9-0e45-4d21-a5f5-5608c0633047.mp4

**Comment by anny320** [comment]
completed
