### ISSUE TITLE
Duplicate icon is not showing  in any death application

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3562]
**Description:**
Duplicate icon and message  is not showing both in work queue  and audit page  for duplicate death applications

**Steps:**

1. login as field agent/registration agent
2. create 2 deadth applications with exactly same data and send them for approval
3. login as registrar
4. goto ready for review
5. observe the two duplicate applications

**Actual result:**
Duplicate icon is not showing in work queue and no duplicate application message shown in audit / review page.

**Expected result:**
Duplicate icon should be shown in work queue and duplicate application message should be shown in audit / review page.

**Screen Recording:**
https://images.zenhubusercontent.com/91778759/1ac2f285-30a1-4f4f-b11e-ba8b8e7b33eb/bandicam_2022_06_23_17_45_22_388.mp4

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by euanmillar** [comment]
We have not designed duplication for death

**Comment by euanmillar** [comment]
@eduffus @jpye-finch can you define how we should identify death duplicates please?

**Comment by jpye-finch** [comment]
@SyedaAfrida can you confirm that this can be closed. thanks!

**Comment by SyedaAfrida** [comment]
This ticket is fixed and can be closed
