### ISSUE TITLE
Certificate config: Wrong notification is showing when trying to upload an svg file after trying any other invalid file

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3564]
**Bug description:**
Certificate config: Wrong notification is showing when trying to upload an svg file after trying any other invalid file

**Steps to reproduce:**
1. Login as national system admin
2. Click Configuration> Certificates
3. from birth/ death click 3 dot menu
4. Click Upload
5. Upload any invalid file (not svg)
6. Close the notification
7. Click 3 dot menu>Upload
8. Upload an svg file and observe

**Actual result:**
Wrong notification is showing in red. But actually the svg file is uploaded properly

**Expected result:**
![c1.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/8e9b5672-e807-40a1-ba7e-85abf8945e7d)
![c2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/01765c60-2738-45ed-8338-2ab311fcf7eb)

**Screen recording:**
https://www.loom.com/share/6db0df5709704faebe980478723fc954

**Tested on:**
https://login.farajaland-config.opencrvs.org/

- [ ] The error state probably needs to be cleared when the error notification is closed

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

![notif1](https://user-images.githubusercontent.com/94350336/180149565-f2789796-5afa-4f8b-b2fe-73c2b7ab9cec.png)

![notif2](https://user-images.githubusercontent.com/94350336/180149561-e92d5c48-0d6b-4fff-9aef-c1de0ecf9563.png)

![notif3](https://user-images.githubusercontent.com/94350336/180149552-6eedd038-25e6-4951-8d38-374dd42f1597.png)

**Comment by anny320** [comment]
completed
