### ISSUE TITLE
After uploading any invalid file in "Upload supporting documents" page, continue button should be disabled for only supporting document page

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3565]
**Description:**
After uploading invalid file in "Upload supporting documents" page, continue button of all previous pages is disabled

**Steps:**

1. Login as Field agent/ registration agent/ registrar
2. declare a birth / death event
3. in the "uploading supporting documents" page, upload any upload any wrong file type (.pdf/.svg)/ any file larger than 5 MB
4. observe continue button ( should be disabled for this page)
5. click back button
6. observe continue button (should be enabled)

**Actual Result:**
continue button of all previous pages is disabled
**Expected result:**
continue button should be disabled for only supporting document page

Screen Recording:

https://user-images.githubusercontent.com/105624748/175525326-5ec2df83-31a2-4362-8d46-b6413b650f4a.mp4

**Desktop:**
windows 10

**Tested on:**
https://register.farajaland-qa.opencrvs.org/

- [ ] Make sure that the disabled state is removed even if there is an error

**Comment by euanmillar** [comment]
@Zangetsu101  In my point of view the continue button should not be disabled at all.  The image should just be not included in any payload that is submitted.

**Comment by Zangetsu101** [comment]
I agree. The continue button should be disabled only when the file is being uploaded. It should not be affected by the image being valid or not.

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/182348302-9d8cdef2-e06e-4835-893c-2e5df3e711d4.mp4

**Comment by anny320** [comment]
completed
