### ISSUE TITLE
JPG signature shouldn't be supported from review page

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3567]
**Description:**
can support jpg signature from only review page

**Steps:**
1. login as National System Admin
2. click create user button
3. select user type as Registrar/ National Registrar
4. upload .png signature and goto review page (if JPG signature uploaded error message is given here)
5. delete the signature to change it
6. upload a JPG signature

**Actual Result:**
can support jpg signature from  review page
**Expected Result:**
Should only support PNG image from both signature upload and review page. If bad quality JPG is uploaded from review page and gets accepted, it can effect the certificate

Recording:
https://images.zenhubusercontent.com/91778759/b2747484-b1d3-419c-9cda-df64eb31ee57/bandicam_2022_06_24_16_07_28_592.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10
Browser: Chrome

- [ ] Make sure that unsupported images throw an from the review page as well

**Comment by SyedaAfrida** [comment]
@anny320 this bug has passed and can be closed
![sign bug](https://user-images.githubusercontent.com/94350336/179685765-b37c3f3e-51e0-4bfd-91e1-f185443fb6c2.png)

![sig bug mob](https://user-images.githubusercontent.com/94350336/179685792-cd58b488-139e-4ecd-8879-cd1f219dd7a9.png)

**Comment by anny320** [comment]
completed
