### ISSUE TITLE
No error message shown when invalid file type is uploaded as signed affidavit

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3570]
**Description:**
No error message shown when invalid file type is uploaded as signed affidavit

**Steps:**
1. Login as Registrar
2. goto ready to print tab
3. click print on any application
4. select someone else as certificate collector
5. In signed affidavit page, upload any invalid file type ( except PNG/JPG )

**Actual Result:**
No error message is given, No indication is given to user about what was wrong

**Expected Result:**
Error message soulld be given like " PNG/JPG file only"

**Recording:**
https://images.zenhubusercontent.com/91778759/54d6289a-942c-4bdf-836f-82c4ee24b912/bandicam_2022_06_24_19_18_15_780.mp4

**Desktop:**
OS: Windows 10
Browser: Chrome

- [ ] Make sure the correct error message is shown

**Comment by SyedaAfrida** [comment]
This bug is not fixed in QA yet
https://www.loom.com/share/c3ae49c5185046fe8912f3f669272c9d

**Comment by Zangetsu101** [comment]
@SyedaAfrida It seems to working. Could you please check again?
![not-bug](https://user-images.githubusercontent.com/29002716/178663865-2f2d672f-3e17-4d98-a86a-60ac00d63022.gif)

**Comment by SyedaAfrida** [comment]
@Zangetsu101 this is a bug. Error message is appearing for birth applications but not appearing for death applications
https://www.loom.com/share/99b78213cdea4f4e8bd36f5ab355f735

**Comment by SyedaAfrida** [comment]
@anny320 this bug is now passed and can be closed
![birth error](https://user-images.githubusercontent.com/94350336/179459690-8b786e57-c456-4073-b2e6-8603791c2205.png)

**Comment by anny320** [comment]
completed
