### ISSUE TITLE
Automatically record audit page reloads after clicking any application 

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3572]
**Describe the bug**
 Record audit page reloads automatically

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://login.farajaland-qa.opencrvs.org/
2. Log in as Registrar/RA
3. Navigate to ready to print or review
4. Go to 2nd page/3rd page
5. Click on any application

**Expected behaviour**
Should open record audit page
**Actual Behaviour**

https://user-images.githubusercontent.com/70468099/175870224-5fe6909d-7918-43c1-815e-889b487f1586.mp4

- [ ] When loading data for workqueues, make sure that the data for the currently selected page for a particular workqueue is downloaded instead of always downloading the data for the first page.

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/180969736-f15acf10-cac0-43a8-9694-75a503ba0294.mp4

**Comment by anny320** [comment]
completed
