### ISSUE TITLE
Config bug: When default config is made mandatory, in birth declaration form that field is appearing twice and hide functionality in config not working

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3573]
**Bug description:**
Config bug: When default config is made mandatory, in birth declaration form that field is appearing twice and hide functionality in config not working

**Steps to reproduce:**
1. login as National System Admin
2. Go to Configuration> Declaration form
3. Click Configure in birth
4. Click weight at birth
5. Make Required for registration on
6. Click Type of birth
7. Make Hide toggle button on'
8. Click Save> add description> Click save
9. Logout
10. Login to FA/ RA/ Registrar
11. Declare a birth application
12. Go to child details page
13. Observe Weigh at birth and Type of birth

**Actual result:**
Weight at birth is appearing twice
Type of birth is showing

**Expected result:**
Weight at birth is mandatory and show once
Type of birth should be hidden

**Screen shot:**
**_Config page_**
![weight at birth not mandatory 2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/e9399865-3d22-45d3-b8a7-07281db0490e)

**_declaration page_**
![weight at birth twice.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/02bb40ed-65fb-49a9-ac3f-f61421845604)

**Tested on:**
https://login.farajaland-config.opencrvs.org/

**Comment by Fariha-Amin** [comment]
@anny320  passed.

Retest **SS:**
![passed config](https://user-images.githubusercontent.com/105624748/176127446-bd219ccf-6279-4147-8315-f089f5229060.png)

**Comment by anny320** [comment]
completed
