### ISSUE TITLE
Config bug: When any Custom field is made mandatory from Config page, in declaration that mandatory field appear even if the details is hidden

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3575]
**Bug description:**
Config bug: When any Custom field is made mandatory from Config page, in declaration that mandatory field appear even if the details is hidden

**Steps to reproduce:**
1. login as National System Admin
2. Go to Configuration> Declaration form
3. Click Configure in birth/ death
4.  Add any custom field> save
5.  Click on that custom field> Make the required for registration toggle on
6. Click save> add description> save
7. Logout
8. Login to field agent
9. Declare a birth/ death event
10. Go to that details page
11. Click 'No' in Do you have the details? question and observe

**Actual result:**
the custom mandatory field appears even if there is no details of that person

**Expected result:**
the custom mandatory field should not appear if there is no details of that person

**Screenshot:**
![custom mandatory field do not hide when no details is given.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/435e0a27-2675-4576-afc0-da755aad652d)

**Tested on:**
https://login.farajaland-config.opencrvs.org/

**Comment by euanmillar** [comment]
@Zangetsu101 in customUtils, [createCustomField](https://github.com/opencrvs/opencrvs-core/blob/e6c8af0629bbf5d830029b069e0c8d9710c268ff/packages/client/src/forms/configuration/customUtils.ts#L28) we need to know which section the custom field is being added to.  Then we need to add the correct conditionals array.  For mother use the conditionals [here](https://github.com/opencrvs/opencrvs-core/blob/e6c8af0629bbf5d830029b069e0c8d9710c268ff/packages/client/src/forms/configuration/administrative/addresses.ts#L123).  For father add the conditionals [here](https://github.com/opencrvs/opencrvs-core/blob/e6c8af0629bbf5d830029b069e0c8d9710c268ff/packages/client/src/forms/configuration/administrative/addresses.ts#L148).
