### ISSUE TITLE
Config bug: From in preview  form cannot be edited when another form is published

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3578]
**Bug description:**
Config bug: From in preview  form cannot be edited when another form is published

**Steps to reproduce:**
1.  Login to national system admin
2. Configure  birth form> save
3. Take the form to In preview
4. publish birth form
5. logout
6. login as Fa
7. Declare a birth event> submit
8. logout
9. Login as National system admin
10. Click configure in death application
11. Save> add description> save
12.  Take the death form to In preview
13. Go to in preview> Click 3 dot> Edit

**Actual result:**
Shows error when trying to edit

**Expected result:**
should be able to edit

**Screen recording:**
![ocrvs-bug](https://user-images.githubusercontent.com/94350336/175885985-a91151fc-f380-4e92-9255-4552a0437744.gif)

**Comment by Fariha-Amin** [comment]
@anny320  can be closed, passed.

**Comment by anny320** [comment]
completed
