### ISSUE TITLE
Conflict bug:Profile icon is not showing in record audit page if local registrar/national registrar unassign any user and assign themselves in any record 

### ISSUE THREAD

**Issue by saima-alam** [opencrvs/opencrvs-core#3580]
**Bug description:**
Conflict bug: assigned user not showing only in record audit page, when local registrar/national registrar unassign any user and assign themselves in any record. If the unassigned user log in , they see the local registrar/national registrar's profile icon in  workqueue but after clicking on the application the profile icon doesn't show

**Steps to reproduce:**
1. Application is assigned and downloaded by Registration agent/Local Register/National Registrar is available
2. log in as registrar/ national registrar
3. Unassign a record that is assigned to any other user except themself (for example unassigned a registration agent.)
4. Assign the record to themself
5. Log out
6. Log in as the user who was unassigned from the application (for example registration agent who was unassigned in step 3) 
7. Click on the Review/Update/Reject of the application
8.  Observe that the error message- "You were unassigned from [tracking id] shows and the profile icon of the assigned user is showing in workqueue
9. Click on the application

**Actual result:**
Profile icon not showing in record audit page, but showing in workqueue

**Expected result:**
Profile icon should show record audit page and workqueue

**Screenrecording:**
https://www.screencast.com/t/HrUgFxM6d

 **Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by SyedaAfrida** [comment]
@anny320 this bug has passed and can be closed

https://user-images.githubusercontent.com/94350336/179924482-6da41cb0-242f-4d38-9ba5-40c993898770.mp4

**Comment by anny320** [comment]
completed
