### ISSUE TITLE
Registrar and National Registrar can still print a certificate & correct a record even after they are unassigned from that record, in ready to print tab

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3581]
**Description:**
Registrar and National Registrar can still print a certificate even after they are unassigned from that record, in ready to print tab

**Steps:**
1. login as  National registrar
2. goto ready to print tab
3. click download an assign 
4. logout and login as Registrar
5. goto to ready to print tab
6. unassig National registrar from that record
7. download and assign himself to the record
8. logout and login as National registrar
9. goto ready to print tab
10. observe that record, click print button or correct record button

**Note: This steps can be also reproduced by Registrar**

**Actual Result:**
1. User is able to print or correct that record even when he  is unassigned from that record.  
2. Even if the application is printed, the record still stays in ready to print tab 
3. Shows unassigned error message and also printed successfully message together

**Expected Result:**
1. User should see Unassigned error message before they print and should not be able to print
2. User should see Unassigned error message before they correct a record and should not be able to correct a record
3. In workqueue it should show the actual assigned user 

**ScreenRecording:**
https://images.zenhubusercontent.com/91778759/f934d0a3-dca3-4f18-8363-8bfa0a2e74bf/bandicam_2022_06_27_14_34_57_298.mp4

- [x] In gateway, correction > root-resolvers.  We must add the checkUserAssignment function check before performing requestBirthRegistrationCorrection & requestDeathRegistrationCorrection - 2
- [x] In gateway, registration > root-resolvers.  We must allow cert to be tracked regardless of assignment so we must remove the checkUserAssignment function in markBirthAsCertified & markDeathAsCertified resolver - 1

**Comment by euanmillar** [comment]
im already assigned
another user sees I am assign
if he clicks and unassigns me I cannot print

But the correct record button is not disabled like the print button.  Please disable the correct record button

**Comment by euanmillar** [comment]
The solution to this ticket, should be the same as that used for registration and addressed in this ticket: https://github.com/opencrvs/opencrvs-core/issues/2951

The Registrar and National Registrar, should be able to continue the correct record process, but at the point of submitting the correction, they should then receive the error from the backend and get the notification as described in #2951

The Registrar and National Registrar, should be able to continue the print process, but at the point of printing, they should receive the error from the backend and get the notification as described in #2951

**Comment by euanmillar** [comment]
We also need to find a solution to the fact that these users can print offline, without tracking it in this case.  Potentially it may not be possible to print offline and still have certified copies

**Comment by euanmillar** [comment]
- [ ] In gateway, correction > root-resolvers.  We must add the checkUserAssignment function check before performing requestBirthRegistrationCorrection & requestDeathRegistrationCorrection

**Comment by euanmillar** [comment]
@jpye-finch we did a check, and it IS possible to certify offline.  No worries

**Comment by jpye-finch** [comment]
@euanmillar ...so if they assign/download. Are we assuming it has been certified and issued. It might not be..?

**Comment by euanmillar** [comment]
@jpye-finch we are not assuming that they have printed it just because they have downloaded it.  The user downloads, it is unassigned from them by someone else, but they still have it downloaded.  They can still print offline.  If they print offline, when they regain connectivity, then we will track that they printed it, even though it had been previously unassigned from them.  There is nothing else we can do I think.

**Comment by eduffus** [comment]
I agree with Euan's comment, however I would like to understand what the graceful fallback solution is in this instance. Does the record move to status "certified" if printed offline when the record was assigned to someone else? If the person assigned has already printed it it will already be at status certified. If they have not printed or even corrected, then we may have a problem.

**Comment by euanmillar** [comment]
So the status moves to certified and stays on certified no matter how many times it is printed so if I understand your question correctly, there is no issue.

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is now fixed and can be closed

for print-
https://user-images.githubusercontent.com/94350336/190619040-f21101eb-04c7-45cf-bd31-caf44b131f95.mp4

for correct record-

https://user-images.githubusercontent.com/94350336/190619119-59b2d1f2-08a1-4dbc-90cf-65e5e90dd1fa.mp4

**Comment by anny320** [comment]
completed
