### ISSUE TITLE
Death deduplication

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3583]
### **Problem statement**

(Describe the problem you're trying to solve by doing this work)

### **Proposed work**

(High-level overview of what we're building and why we think it will solve the problem).

### **Success criteria**

(The criteria that must be met in order to consider this piece of work a success)

### **User stories**

(How the product should work for various user types)

-

### **Scope**

(Current requirements)

### **Future work**

(Future requirements)

**Comment by anny320** [comment]
will include the tickets  to flag death duplicates in the advanced deduplication epic
