### ISSUE TITLE
As a System Admin, I want to see a list of clients I have integrations with

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3592]
### Description

- adds integrations config page
- list of clients added

### Acceptance criteria

GIVEN I am a system admin
WHEN I click on Integrations in the side nav
THEN navigate to the Integration page

GIVEN I on the Integrations page
THEN I want to see a list of previous clients I have added

GIVEN I on the Integrations page
THEN I want to see the status (enabled/disabled) of previous clients I have added

Design

https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8478%3A44119

### Dev-tasks

- [x] Add "Integrations" to side navigation under "Configuration" when you are logged in as a system admin - 1
- [x] Create a directory under /packages/client/src/views/SysAdmin/Config called "Integrations" and add a new view "Integrations.tsx". Use [`<Content>`](https://ui-kit.farajaland-qa.opencrvs.org/?path=/docs/layout-content--default) and add a [`<ListViewSimplified>`](https://ui-kit.farajaland-qa.opencrvs.org/?path=/docs/data-list-view--default). - 1
- [x] List the name and status of the integrations from configuration. The configuration is loaded in `loadConfig`.

```
interface IIntegration {
  name: string
  status: string // statuses
  systemId: string // This is not here now. It is added in a different ticket
}

export const statuses = {
  PENDING: 'pending',
  ACTIVE: 'active',
  DISABLED: 'disabled',
  DEACTIVATED: 'deactivated'
}

window.config.INTEGRATIONS: IIntegration[]
```

**Comment by SyedaAfrida** [comment]
will be tested after the system crash mention in #2277 is fixed

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![fixed](https://user-images.githubusercontent.com/94350336/209296348-a38b63ab-0dd9-4b4a-b07f-6979da2e8256.png)

**Comment by anny320** [comment]
Completed
