### ISSUE TITLE
As a System Admin, I want to see the keys for a client I have added

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3593]
# As a System Admin, I want to see the keys for a client I have added

### Description

- adds ‘Reveal keys’ to sub menu

### Acceptance criteria

GIVEN I am on the Integration page
WHEN I click the sub menu (three dots)
THEN show the submenu

GIVEN I am on the Integration Config page and a Client has already been created
WHEN I click the sub menu (three dots)
THEN show the submenu with:

* Reveal Keys
* Enable/Disable (depending on current status)
* Delete

GIVEN I can see the submenu
WHEN I select “Reveal Key”
THEN [show keys for that client](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8478%3A44119)

### Design

[https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8478%3A44119](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8478%3A44119)

### ocrvs-3593-reveal-keys
- [x] Update [`getSystemHandler`](https://github.com/opencrvs/opencrvs-core/blob/20752517229bcf9c413232975df61325a4bb2744/packages/user-mgnt/src/features/system/handler.ts#L291-L292) to allow searching with either `systemId` or `clientId` - 1
- [x] Create a GraphQL gateway endpoint `fetchIntegration` to `packages/gateway/src/features/integrations` which would call `user-mgnt` `getSystemHandler`. The endpoint would return systems `name`, `clientId`, `shaSecret` - 1
- [x] Add a 3-dot menu to `<ListViewSimplified>` in Integrations-view, which has a "Reveal keys" -item in it. It opens a `<Modal>`, and with the previously made gateway endpoint, it lists Client ID, Client Secret and Sha secret (see design). Client secret isn't visible, but has a "Refresh" `<Link>` . _"Copy"-button doesn't need to be implemented._ - 2

### ocrvs-3593-refresh-secret
- [x] Create a `refreshSystemClientSecret` endpoint to `user-mgnt` which would take `clientId` as an payload input and updates the system with a new `clientSecret` which is `uuid()` - 1
- [x] Create a GraphQL gateway mutation to `packages/gateway/src/features/integrations` which would call `user-mgnt` `refreshSystemClientSecret`. The endpoint would return systems `name`, `clientId`, `clientSecret`, `shaSecret` - 1
- [x] Clicking the `<Link>` "Refresh", would call the previously made GraphQL gateway endpoint, and show a Spinner while it's creating a new client secret. After that, the new Client secret is visible similar to Client ID & Sha secret - 1

Example GraphQL queries:
```
query fetchIntegration($clientId: UUID!) {
  fetchIntegration(clientId: $clientId) {
    integration {
      name
      clientId
      shaSecret
    }
  }
}

mutation refreshIntegrationClientSecret($clientId: UUID!) {
  refreshIntegrationClientSecret(clientId: $clientId) {
    integration {
      name
      clientId
      clientSecret
      shaSecret
    }
  }
}
```

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/209294438-1a50ccb3-a6d7-4a22-a0d8-f5d99f9f46e5.mp4

**Comment by anny320** [comment]
Completed
