### ISSUE TITLE
As a System admin, I want to create a new client integration

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3594]
# As a System admin, I want to create a new client integration

### Description

- adds new client button
- Types of client:
    - notification,
    - id verification
    - external crvs system (to be discussed)
    - webhook

### Acceptance criteria

GIVEN I am a system admin
WHEN I click New client on the Integration page
THEN open the new client model

GIVEN I am creating a new client
WHEN I add a name already used
THEN show the error ‘Client name already being used.’

GIVEN I am creating a new client
WHEN I select Health Notification
THEN show the explainer copy for Health Notification

GIVEN I am creating a new client
WHEN I select National ID
THEN show the explainer copy for National ID

GIVEN I have created a National ID client
WHEN I select the Type select
THEN the option for National ID should not exist as there is only one of this type allowed

GIVEN I am creating a new client
WHEN I select Record Search
THEN show the explainer copy for Record Search

GIVEN I am creating a new client
WHEN I select Webhook
THEN show the explainer copy for Webhook

GIVEN I have added a name and select a type
WHEN I click create
THEN [show the loading state]

GIVEN the client has been created
THEN show the keys

GIVEN there was an error creating the client
THEN show the error. ‘There was a problem creating the client [Name]. Please try again.’

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8478%3A44119

### Dev-tasks

- [x] In the user-mgnt microservice we need a route and handler to get ALL systems. - 1
#4141
- [x] Amend the system schema in user-mgnt, change name to be a plain string and the createdBy to be the id of the user that has created the system, and amend the registerSystemClient / getSystemClient handler to save these values instead. Add the type which can be either HEALTH, NATIONAL_ID or RECORD_SEARCH. registerSystemClient handler should be updated to use systemScopeMappings populate the scope based on the payload input of type. - 3
#4146
- [x] Remove the IIntegrations[] from the config model in the config microservice and remove it from the update config Joi validation and any associated update queries from the client. Instead, the getApplicationConfig method, needs to call the user-mgnt microservice, parse the system clients and return the IIntegrations[] in the response - 2
#4142
- [x] Add a "[Create client]" button to the Configuration->Integrations <Content>. Pressing the button will open up a <Modal> according to the design. Selecting different types should show a short description of the system type. After pressing "Create", the modal will display placeholder values as "Client ID", "Client Secret" and "Sha secret". - 1.5
#4170
- [ ] For the downloaded event in the workflow, if the request in scope includes RECORD_SEARCH we would add an identifier to a task as we do for birth notifications, to mark if the action was performed by a system. - 1
https://github.com/opencrvs/opencrvs-core/issues/4184
- [ ] Amend the History in registrations/type-resolvers.ts and instead of "user" lets call it "performedBy". It would return union of a User or a System (https://www.apollographql.com/docs/apollo-server/schema/unions-interfaces/), depending on the identifier we added in the previous task.  We need a schema and type-resolvers for a system. - 2
- [ ] Amend record audit history to handle the case in the client when the `performedBy` could be a User or a System - 1
- [x] #4189

**Comment by naftis** [comment]
@jpye-finch the actual system name is going to be something like if Pyry Rouvila created it, "PR-Sweeeet". We wanna show the system name under the "New client" -> "Name" as a preview. Could you mock something up for the designs?

**Comment by naftis** [comment]
@jpye-finch when you create a integration. We should show an alert that the "Client secret" will visible one-time only. 
![image](https://user-images.githubusercontent.com/1322608/197183965-b75e01e9-12aa-4a90-9cee-1d0e810422f7.png)

**Comment by euanmillar** [comment]
@naftis @Zangetsu101 I realised, that when adding or removing an integration of type MOSIP, the backend process should add/remove the "webhooks" route in the OpenHIM Birth Registration and Death Registration channel too.
```
{
          "type": "http",
          "status": "enabled",
          "forwardAuthHeader": true,
          "name": "Webhooks -> Death Registration",
          "secured": false,
          "host": "webhooks",
          "port": 2525,
          "path": "",
          "pathTransform": "",
          "primary": false,
          "username": "",
          "password": ""
        }
```

**Comment by euanmillar** [comment]
@naftis @Zangetsu101 @jpye-finch  Apologies I know I said we would not do a Webhook type, but I think we should after some thought.  @Zangetsu101  @naftis  We should create a new scope "webhook".  Then in the webhooks microservice in the transformBirthBundle and transformDeathBundle have a different case for "webhook" which just sends only the child / deceased data for now.  Additionally, we should have some validation so that only 1 National ID client can be created.  Users can make as many Record Search, Health Notification and Webhook clients as they like, but if there was more than 1 nationalId client, we sould have technical problems.  Can you create tasks for this and split this ticket up so that Robin or a SeamHealth developer can help?

**Comment by SyedaAfrida** [comment]
**Bug:**
when client name is already used, should through error -  ‘Client name already being used.’& NID dropdown should not show as there is only one of this type allowed

https://user-images.githubusercontent.com/94350336/209291079-e5414f45-6e8c-4149-bef6-cb01cdf34090.mp4

**Comment by Zangetsu101** [comment]
@SyedaAfrida We are showing a warning instead of just straight up hiding the NID option in the type dropdown and the create button is also disabled in this case. And duplicate names are fine for integrations

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/209527890-5063eebd-c0eb-4fc6-8d7b-0dab7c666bd4.mp4

**Comment by anny320** [comment]
Completed
