### ISSUE TITLE
As a System Admin I want to enable and disable a client integration

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3595]
# As a System Admin I want to enable and disable a client integration

### Description

- add disable and enable to sub menu

### Acceptance criteria

GIVEN I am on the Integration page
WHEN click the sub menu (three dots)
THEN show the submenu

- Reveal Keys
- Enable/Disable (depending on current status)
- Delete

GIVEN the client is enabled
WHEN I click disable
THEN disable the client (an existing connected client can no longer connect)

GIVEN the client is disabled
WHEN I click enable
THEN enable the client (an disconnected client can now connect)

### Design

[https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8478%3A44119](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8478%3A44119)

### Dev-tasks

- [x]  user-mgnt already has routes for `deactivateSystemClient` and `reactivateSystemClient`. They find the System in database by `_id`. Lets change those to find the system by `client_id` with `System.findOne({ client_id: .. })` - 1
- [x] Create a GraphQL gateway endpoints to packages/gateway/src/features/integrations which would call user-mgnt `deactivateSystemClient` and `reactivateSystemClient`. - 1
- [x] Add Enable / Disable (depending on current status) to 3 dot menu in Integrations. Clicking the button will open a Confirm-modal. Clicking confirm will call the GraphQL endpoint made in the previous task. - 2

**Comment by SyedaAfrida** [comment]
will be tested after the system crash mention in #2277 is fixed

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/209294748-7ceaeede-c480-4416-95c4-ea63c872456f.mp4

**Comment by anny320** [comment]
Completed
