### ISSUE TITLE
Vital statistics export

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3598]
### **Problem statement**

There is currently no simple way to easily export all non PII data from the OpenCRVS.
There is need create a process to enable extraction of quality Vital statistics data for a fixed period or on demand for statistics and planning purposes for births and deaths.
Future scope will include other vital events like marriages, divorces, foetal deaths etc

**Definitions**

Vital statistics constitute the collection of statistics on vital events pertaining to the population, including relevant characteristics of the events themselves and also of the persons concerned.

Why:
They are critical for a wide range of government operations, e.g. population register, national identification system, and other administrative registers, and for commercial enterprises (e.g. life insurance and marketing of products).

- At the subnational level, accurate population data are essential for planning the needs of the community, and for addressing and monitoring regional inequalities.
- Vital statistics collected from a civil registration system that cover all events (for the whole country and not just a sample), can provide a reliable basis for small-area information needed to design and implement policies on public health, maternal and child care, family planning, social security, education, housing and economic development.

Vital statistics involves:

1. Quantities and rates of births: Important characteristics of births, such as births by sex, location and maternal age.
**Birth Statistics**: It includes an absolute number of births, crude birth rates, and sex ratio at birth. It also comprises fertility rates in terms of adolescent birth rate, age-specific fertility rate, and total fertility rates as well as low birth weight and preterm live births.
2. Quantities and rates of deaths, and Deaths by essential characteristics such as age, sex, location and cause of death.
**Death Statistics:** It covers an absolute number of deaths, crude death rates, age-, sex-, and cause-specific death rates. Moreover, death statistics include life table and life expectancy, infant mortality, under-five mortality and maternal mortality ratio.

The usefulness of vital statistics depends on their quality.
**Common data quality concerns include:**

- if registration covers all the national territory and population groups (coverage)
- the extent to which all births and deaths that take place during the year are recorded (completeness)
- the presence of partially collected or missing elements or characteristics (ie sex, age, residence etc.)
- the percentage of deaths that do not have a useable cause of death (COD)
- the use of standard definitions and classifications
- timeliness and accessibility of the data.

### **Proposed work**

There is a need to design and develop a standard VS export that includes all system data (no PII) that can be used for VS purposes.
This functionality allows a user to export system data in order to import into digital VS system for cleansing and processing

1. Anonymise vital event records before exporting
2. Create .CSV formatted data exports
3. Selection of data by event type ( birth/ death) or event date (year)
4. User presented with a warning about the amount of data to de exported and potential download time
5. Micro-data export into a standard file format e.g. CSV
6. Current records only (not historical data that was corrected)
7. No info on the transaction or processing required, just the record data

### **Success criteria**

(The criteria that must be met in order to consider this piece of work a success)

1. National coverage of the data and completeness of vital events
2. Plausibility of the data - if compared against other metrics like previous years/ global standards its accurate
3. Date formats are consistent
4. There are no duplicates in the data
5. As many fields are completed as possible

### **User stories**

1. As a National Registrar / National Sys Admin I would like access the vital statistics dashboard on the performance page through a link on the side navigation
2. As a National Registrar / National Sys Admin I would like to generate vital statistics data for a selected period for births and deaths events
3. As a National Registrar / National Sys Admin I would like to be alerted of the file size of the export before downloading
4. As a National Registrar / National Sys Admin I would like to see export links of VS for previous years in order to be able to download the .csv files

### **Scope**

(Current requirements)

### **Future work**

(Future requirements)

Other notes:

Major data quality concerns to be aware of for vital statistics data to ensure quality of the data is Plausibility checks and data cleaning .

***Plausibility checks*** involve evaluating the data to determine if they are likely to be true (plausible) or if they are likely to be untrue (implausible). The final judgement about the plausibility of data can often only be arrived by using some comparator: that is, comparing recent data to previous years’, or data from another source. The data are more plausible if they are similar to those from other years or sources. For example, if the current year’s vital statistics data show there were 120,000 deaths, and there were 118,000 deaths in the previous year, and the United Nations estimated 122,000 deaths, then these results are similar enough to show the recent data are plausible.
***Data cleaning*** involves a series of checks and actions that need to be applied to the raw data before it can be further analysed. The checks may include making sure:
1.  There is only one record per line and one line per record
2. There is only one field per column that each file has the variables or fields in the same order so they can be combined later
3. There are no duplicates in the data
4. Date formats are consistent
5. As many fields are completed as possible.

**Comment by SyedaAfrida** [comment]
This epic do not require QA testing
