### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3599]
previously search for a record v2
### **Problem statement**
- In countries with a large number of records, searching for a user with their name might return a large number of records that are difficult to distinguish between, so users may want to search within a set of more defined parameters. Customers may have also lost their BRN or DRN number.
- The system currently only allows a user to search by tracking ID, BRN/DRN number, phone number or name (any associated with the record)

### **Proposed work**

There is a need to: 

- extend the search functionality for more specific searches i.e. advanced search to be able to uniquely identify a record
- Search for similar matches on names (fuzzy search)
- add validation logic to ensure that the search parameter is correctly formatted (e.g. Tracking ID has the correct number of chars)
- Include 3rd party users' access (OpenCRVS API explorer)
- Search record by a date range (Date of birth, date of Death)
- Search based on National ID
- Search via parameters

### **Requirements**

Common scenarios that need to be supported:

- The registrar is investigating what has happened to a registration for which there is a query
- Family member arrives to pick up the death certificate —> search —> print certificate
- Parent is requesting a certified copy —> search —> print certificate

1. Search parameters:

Basic search - the rest are advanced search

1. Basic search should show by default, advanced search is an option, if required.
2. Once the search is executed:
    - If no results, state “No results meet your search criteria”
    - Show the total number of search results found
3. Display all results as follows:
    - Show header information for each record (min for PII but enough to identify record)
        - Type
        - Name
        - Date of event
        - Status
    - Default order the search results by date of event (most recent first)
    - Limit records per page (10)
    - Expand the record to show more detailed information
        - Tracking ID
        - Registration no.
        - Informant contact no.
        - Status update history
4. Ability to download and take action (if permissions allow) e.g. create a certified copy. If no action is possible, then indicate.
5. Search is available to Field Agent, Registration Agents, Registrars, National Registrars, Local System Admin, National System Admin

### **Success criteria**

1. A user can retrieve a unique record based on a single search parameter (tracking ID, registration no)
2. A user can retrieve records based on a combination of search parameters (see table above)
3. A user can retrieve records that are similar to the entered search parameter (for fields where fuzzy search is enabled - see table above)
4. User sees the total number of results from the search   
5. Where multiple records satisfy the search parameters, the user can navigate through the entire list of records
6. The user can take actions on a record if they have the role/permission to do so
7. The user cannot take action on a record if they do not have the role/permission to do so

### **Scope**

Birth and death registration records

**Comment by anny320** [comment]
completed
