### ISSUE TITLE
MOSIP Integration

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3603]
MOSIP and OpenCRVS need to integrate birth and death webhooks.

The UIN & VIN (Visual national ID) must be returned to OpenCRVS after MOSIP has subscribed to a Birth registration webhook.

The UIN & VIN returned must be saved into OpenCRVS Patient model as identifiers.

The RegExp for NID must be changed to conform to the MOSIP VIN pattern in Farajaland.

On death, the VIN must be entered into the OpenCRVS form as the deceased NID and deceased's NID must be mandatory.

The deceased details can then be sent to MOSIP.

**Comment by euanmillar** [comment]
After consultation with MOSIP, the VID and UIN will NOT be returned to OpenCRVS.  Instead MOSIP will share a token.  During death registration we will send whatever VID is submitted along with the token for MOSIP verification.  In this way we create a person-centric longitudinal event connection
