### ISSUE TITLE
Replace Create React App with Vite in Login, Client and Component libraries.

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3606]
### Storybook 6.5 is already released but they hadn't updated their changelog. So we can go on with using vite in components package.

- [x] Replace react-scripts (CRA) and craco with [Vite](https://vitejs.dev/) in login app
- [x] Replace react-scripts (CRA) and craco with [Vite](https://vitejs.dev/) in client app
- [x] Replace react-scripts (CRA) with [Vite](https://vitejs.dev/) in components
- [ ] Find a way to show React component names in React DevTools instead of styled.* #2988 
   This might be of help: https://github.com/vitejs/vite/discussions/4098#discussioncomment-1389047

**Comment by Zangetsu101** [comment]
Done in #3703
