### ISSUE TITLE
Refactor SubmissionController to be a better middleware /  use redux / redux-loop

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3607]
Submission Controller requires re-factored to use redux/redux-loop or developed into redux middleware.
Currently there are some independent async / await handlers that are hard to debug and could cause side effects.

- [x] Refactor _MODIFY_DECLARATION_ to handle immutability properly
- [x] Currently when writing a single declaration finishes, changes to other declarations are overwritten to the time when the write started. Refactor the _WRITE_DECLARATION_ to make sure that the other declarations aren't altered when writing finishes
- [x] Refactor the submission controller to adopt an event driven approach instead of the imperative one that's currently being used

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

**Comment by anny320** [comment]
closed
