### ISSUE TITLE
Replace " download" with retrieve when accessing a record?

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3608]
### Description
The systems says that records are being “downloaded” to work on them. I would suggest to rather say “retrieve” or something like that as download could imply that the record is saved on the local machine and would be available outside of OpenCRVS – which I assume is not the case.
...

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

(Link to Figma)

### Copy

(Link to Notion)

### Dev-tasks??

- [ ]  Task 1

**Comment by jpye-finch** [comment]
@anny320 we have this ticket https://app.zenhub.com/workspaces/opencrvs-core-5afeded64a54b06b54a969b2/issues/opencrvs/opencrvs-core/3544

**Comment by anny320** [comment]
Hi, the name needs to change from downloaded to either retrieve or something else so we can always link the two

**Comment by jpye-finch** [comment]
closing duplicate of #3544
