### ISSUE TITLE
Refactor SettingsPage

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#3616]
- [x] Refactor from class to FC
- [x] Create seperate components for each row inside `ListViewSimplified`. The structure should be something like this:
```ts
<ListViewSimplified>
  <Name />
  <PhoneNumber />
  <Role />
  ...
</ListViewSimplified>
```
- [x] Decouple the logic accordingly in each component rather than keeping all the logic in the `SettingsPage`

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is tested and can be closed
![settings](https://user-images.githubusercontent.com/94350336/181195774-f2666b7c-09e5-4b16-abcd-9bc929f41b63.png)

**Comment by anny320** [comment]
completed
