### ISSUE TITLE
In mobile view, should not have option to delete supporting documents from review page as it is not supported in web view 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3617]
**Bug description:**
In mobile view, System crash occurs when try to delete supporting documents from review page

**Steps to reproduce:**
1. In mobile view login as Field agent
2. Create a death application
3. add supporting documents
4. Go to review page
5. Click on the attachment
6. Click delete

**Actual result:**
System crashes when try to delete attachment from review page

**Expected result:**
It should not crash!
~There should be no delete option in review page of mobile view as there is no delete option in web view~

**Screen recording:**
https://images.zenhubusercontent.com/91778759/999e5f78-f927-4377-9a98-de8d63a1eadc/should_not_have_delete_option_of_attachment_from_review.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by jpye-finch** [comment]
@SyedaAfrida I removed the expected result "There should be no delete option in review page of mobile view as there is no delete option in web view"

An improvement idea is to add button on the Review page for desktop. So you can view supporting documents full screen (black background)

Same as clicking the document name on mobile: 
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/0f51f5d3-d20c-4d95-945d-9476bd607417)

**Comment by jpye-finch** [comment]
so this ticket should just be about fixing the bug causing the crash

**Comment by euanmillar** [comment]
@jpye-finch I dont understand what you are getting at with your comment.  I think what @SyedaAfrida is suggesting is fine.  I guess we need to discuss.

**Comment by euanmillar** [comment]
Lets hide the button from the review page.

**Comment by CornelMaze** [comment]
@jpye-finch From what screen size should I hide the delete button? I did for 760px but on clicking the delete button the app still crashed.

**Comment by jpye-finch** [comment]
This ticket is not about hiding and delete buttons. We shouldn't be hiding it.

Is just to stop the app from crashing

**Comment by jpye-finch** [comment]
If anything. We should add a dialog to confirm you want to delete the supporting document

**Comment by jpye-finch** [comment]
If anything. We should add a dialog to confirm you want to delete the supporting document

**Comment by Zangetsu101** [comment]
@jpye-finch We can delete the document if we go to the documents section in the form so is there a need for it be present in the review?

**Comment by jpye-finch** [comment]
@Zangetsu101 do want you feel is needed to fix the app crashing. 

There is a ticket to update the documentPreview on the Review page and the full page preview
https://www.figma.com/file/SsqCzO2eherXXCKyixmli9/OpenCRVS-Design-System-v2-WIP?node-id=1008%3A12210

If we can make it easier to navigate back to the supporting document page to delete the supporting document. Plus add documents. Then we can remove the delete button all screen sizes.

**Comment by jpye-finch** [comment]
If we remove the delete button. We should do so on all screen sizes

**Comment by anny320** [comment]
completed
