### ISSUE TITLE
Configure Date of birth/ Year of birth setting

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3625]
### **Problem statement**

Advanced configuration of the date of birth or year of birth to allow capture on more than one date formats? 

### **Proposed work**

(High-level overview of what we're building and why we think it will solve the problem).

### **Success criteria**

(The criteria that must be met in order to consider this piece of work a success)

### **User stories**

(How the product should work for various user types)

-

### **Scope**

(Current requirements)

### **Future work**

(Future requirements)

**Comment by jpye-finch** [comment]
@anny320 this ticket needs to be split into separate Epics
