### ISSUE TITLE
As a National Registrar / National Sys Admin I want to view available VS exports

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3636]
### Description
- adds sub menu option to Performance for National Registrar and National Sys Admin . Dashboard and Reports
- adds Reports page

### Acceptance criteria
GIVEN I log in as a National Registrar / National Sys Admin
WHEN I click on Performance
THEN it defaults to the menu option Dashboard

GIVEN I have clicked on Performance
WHEN I click on the sub menu option Reports
THEN navigate to the Reports page

GIVEN I click on Reports
THEN I can view a list of available VS exports by year

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=7010%3A143342

### Dev tasks

- [x] In the LeftNavigation bootstrap a new page called "VS Exports" and make a folder called "vsexports" in packages > Client > SysAdmin > Performance to store the VSExprt.tsx Page.  Setup Content component with tabs. Keep a comment with TODO to refactor using `Frame` component when component-library-v2 is merged in - 2
- [x] Create a metrics handler to return everything in the metrics vsexport collection - 1
- [x] Create a gateway query to return everything in the metrics vsexport collection ('register', 'performance', 'certify', 'sysadmin', 'validate' JWT scopes can use it) - 2
- [x] Enable the export button to download the right csv in birth and death tabs (direct link to Minio) - 2

**Comment by jpye-finch** [comment]
@anny320 @euanmillar  What is a full year? What is our start and end month? should this be configurable?

**Comment by SyedaAfrida** [comment]
**Bug:**
Vital statistics page keeps on loading and do not show list by year
![vs export](https://user-images.githubusercontent.com/94350336/206146967-5274dd87-ff6a-473e-b2e6-be6827cd9094.png)

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![fixed](https://user-images.githubusercontent.com/94350336/209638449-149a0273-c73e-4c33-9a84-34fa78377739.png)

**Comment by anny320** [comment]
completed
