### ISSUE TITLE
As a National Registrar / National Sys Admin I would like to generate vital statistics data for a selected period for births and deaths events

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3637]
### Description
As a National Registrar / National Sys Admin I would like to generate vital statistics data for a selected period for births and deaths events

...

### Acceptance criteria

GIVEN when  user clicks on the vital statistics link and navigate to the vital statistics export page
WHEN user selects births and the [year] OR deaths and [year]: THEN user should be able to download the .CSV file

### Design

(Link to Figma)

### Dev tasks

- [ ] Task 1

**Comment by jpye-finch** [comment]
we can close this. We aren't generate custom VS report in this version
