### ISSUE TITLE
As a National Registrar / National Sys Admin I would like to be alerted of the file size of the export before downloading the vital statistics .csv file

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3638]
### Description

- show a  prompt alerting of the file size of the export before downloading

...

### Acceptance criteria

GIVEN
WHEN a user clicks the generate button, 
THEN user should see a prompt with a notification of the download size of the .CSV file

### Design

(Link to Figma)

### Dev tasks

- [ ] Task 1

**Comment by jpye-finch** [comment]
closing. combined ac into https://app.zenhub.com/workspaces/opencrvs-core-5afeded64a54b06b54a969b2/issues/opencrvs/opencrvs-core/3639
