### ISSUE TITLE
As as (Registration Agent/ Registrar/ National Registrar/ Local and National System Admin) I would like to view the user profile page

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3640]
### Description
- Renables links to User Audit/Profile page
- Adds User Summary section
- Same permission for those who can access the Team page 
https://www.notion.so/opencrvs/User-Audit-9b5377f3d8f54601b778080f4dfa5f6d

### Acceptance criteria
GIVEN I have access to the Team page
WHEN I click on a user
THEN navigate to the User Audit/Profile page

GIVEN I am viewing a User Profile
THEN I can view their summary data. (Captured during New user flow)

- Name
- Status
- Assigned Office
- Role
- Phone no.
- National ID
- Username
- Device

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=2216%3A45558 

### Dev tasks
- [x] Use Pyry's Summary component branch as a base branch: [component-library-v2](https://github.com/opencrvs/opencrvs-core/tree/component-library-v2)
    - Combine `UserProfile.tsx` and `UserAuditList.tsx` into a component called **UserAudit** and deprecate the term UserProfile / UserAuditList. The UserAudit component should use the `Content` component.
    - Refactor the query results to use the `TableView` component.  Use `Pagination` component like we do in the History component of RecordAudit [(reference)](https://github.com/opencrvs/opencrvs-core/blob/component-library-v2/packages/client/src/views/RecordAudit/History.tsx#L309). - 2
- [x] In the UserAudit, populate the TableView and pagination to show 10 items per page. - 2
- [x] Enable filtering on the TableView headers ( use the route param for saving the data) - 2
- [x] Enable links from Tracking ID through to a search result ( Field Agent, RegistrationAgent and Registrars) - 1
- [x] For these users only, E.G. NOT Field Agent, enable links from Record Audit through to User Audit. In App.tsx, for the UserAudit route add the appropriate scopes so that fieldAgents can't access that page. - 1

**Comment by euanmillar** [comment]
@jpye-finch if the user is offline or has

**Comment by euanmillar** [comment]
@jpye-finch I think we need pagination in this page
