### ISSUE TITLE
 The icon color of review and declaration pages should match with the status of that declaration

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3650]
**Bug description:**
 The icon color of review and declaration pages should match with the status of that declaration

**Steps to reproduce:**
1. Login to RA/ local registrar/ national registrar
2. Click Requires updates/ In progress> field agent
3. Download> assign to any record
4. Click Update
5. Observe the icon color of review and declaration pages

**Actual result:**
The icon color is always yellow for all status

**Expected result:**
The icon color should be red for requires updates application
The icon color should be purple for in progress application

**Screen recording:**
https://images.zenhubusercontent.com/91778759/295bafb1-4653-4253-a10e-cab0e4123e50/icon_in_rejected__1_.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/196656582-fa51c3d9-497a-4b39-9aec-4d2120643ba9.mp4

**Comment by anny320** [comment]
completed
