### ISSUE TITLE
My draft applications should show downloaded icon ( pointed downwards) instead of uploaded icon

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3651]
**Bug description:**
My draft applications should show downloaded icon ( pointed downwards) instead of uploaded icon. The icon is supposed to symbolise what is stored local/available offline

**Steps to reproduce:**
1. Login as RA/ local registrar/ national registrar
2. Click in progress> My draft
3. Observe the icon in workqueue/ record audit page

**Actual result:**
showing uploaded icon( pointed upwards)

**Expected result:**
My draft applications should show downloaded icon ( pointed downwards)

**Screen recording:**
https://images.zenhubusercontent.com/91778759/b6139570-3bd5-4f78-b95a-c9abafcde065/download_point_up.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
We have what we need in terms of design so this is good to go.

**Comment by SyedaAfrida** [comment]
**Bug:**
In record audit page also, draft applications should show downloaded icon

https://user-images.githubusercontent.com/94350336/196411177-be781409-3a57-4f77-b377-d455f98c56a4.mp4

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![4](https://user-images.githubusercontent.com/94350336/199419341-5052e9c1-3669-4389-8be2-7a4b02004c28.png)
![3](https://user-images.githubusercontent.com/94350336/199419346-f957cbb3-38bf-4b84-9640-249556ddfaf1.png)
![2](https://user-images.githubusercontent.com/94350336/199419352-2fccf9bf-9a02-4b3b-b7c4-a72e2e2cb76d.png)
![1](https://user-images.githubusercontent.com/94350336/199419355-ee4e83a7-ab60-4274-b962-cb82000093cf.png)

**Comment by anny320** [comment]
completed
