### ISSUE TITLE
Field agent should not unassign others from rejected records

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3652]
**Bug description:**
Field agent should not unassign others from rejected records

**Steps to reproduce:**
1. Login as RA/ local registrar/ national registrar
2. Click requires updates
3. Click download> assign to any record
4. Logout
5. Login as FA
6. Click requires updates
7. Click to unassign/ download that record
8. logout
9. Login as RA/ local registrar/ national registrar
10. Click requires updates
11. Click update
12. Make change and click register/ sent for approval
13. Observe

**Actual result:**
shows unassign message

**Expected result:**
Field agent should be able to download records(assigned/ unassigned) from requires updates **But** should not unassign someone else from that record

**Screen recording:**
https://www.loom.com/share/7679ba3733f14029a0eb2c484d956d12

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/186104384-d88d8070-6fd9-4988-a0e6-6f234d041b2d.mp4

**Comment by anny320** [comment]
completed
