### ISSUE TITLE
Refactor application config

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#3656]
- [ ] Refactor the three tabs i.e. General Tab, Birth Tab & Death tab to follow a structure similar to the current Settings page

**Comment by SyedaAfrida** [comment]
**Bug:**
User is able to upload logo of more than 2mb. No error message is shown that "Logo image file must be less than 2mb". later the **system crash** occurs after user logs out and try to login again.
![image_2022_08_04T12_16_41_048Z](https://user-images.githubusercontent.com/94350336/183064435-c1d160ed-916c-4c70-9800-33535c938d40.png)

Check the figma design for error state of gov logo
https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=713%3A13002

**Comment by SyedaAfrida** [comment]
@anny320 the bug for this ticket is now fixed, so this ticket can be closed

https://user-images.githubusercontent.com/94350336/185909056-ddeba847-e869-4714-9530-17b3c135c5d0.mp4

**Comment by anny320** [comment]
completed
