### ISSUE TITLE
System keeps on loading for infinite time, when a declaration is in outbox and the page is refreshed

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3658]
**Bug description:**
System keeps on loading for infinite time, when a declaration is in outbox and the page is refreshed

**Steps to reproduce:**
1.  Login to any user
2. Declare an event
3. Submit the declaration
4. when the application is in outbox, refresh the page

**Actual result:**
System keeps on loading for infinite time,  even if you’d try to log in again

**Expected result:**
infinite loader should not persists

**Screenshot:**
![image (3).png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/df108c9d-e38e-4b84-a88f-fd8617c177e7)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
@Zangetsu101 this is the bug I was referring to earlier

**Comment by SyedaAfrida** [comment]
**Bug:**
When the application is in the outbox and the page is refreshed, the application is still found in the outbox, though the application is actually submitted

https://user-images.githubusercontent.com/94350336/183412337-4d55b749-5b3e-40da-86f5-a0064df2bc13.mp4

**Comment by euanmillar** [comment]
@SyedaAfrida @anny320 this is expected behaviour.  In 15 minutes it will disappear.  We cant change this.  In my opinion it isnt a bug and can be closed.

**Comment by euanmillar** [comment]
@SyedaAfrida @anny320 regarding the refresh/outbox issue 1 this is expected behaviour.  In 15 minutes it will disappear.  We cant change this.  Regarding 2 & 3, in search results, we should check the filterProcessingDeclarationsFromQuery function and hide any search result currently in the outbox, until the 15 minutes have passed and the outbox has had a chance to sync properly

**Comment by SyedaAfrida** [comment]
@anny320 Bug -2 & 3 are fixed. so this ticket can be closed

https://user-images.githubusercontent.com/94350336/185875421-c847ea5c-05c5-484a-bc44-8fbae33f2bc7.mp4

**Comment by anny320** [comment]
completed
