### ISSUE TITLE
Workqueue pagination improvement

### ISSUE THREAD

**Issue by tahmidrahman-dsi** [opencrvs/opencrvs-core#3671]
According to the current implementation, the workqueue pagination does not fulfill the best user experience. There are two observations regarding pagination. 

1.  After navigating to any page other than page 1, when clicking the informant name the user is taken to the `RecordAudit` page. But after clicking the back button from the `RecordAudit`, it shows that the current page is 1. The expected behavior is to keep that current page from where the user went to `RecordAudit`. 

https://user-images.githubusercontent.com/42269993/180182264-627e1277-ee44-4399-9ac5-285e35745b00.mp4

2. Moving through the pages of workqueue, the back button does not take the user to the previously visited pages which was expected. It navigates the user to the performance page instead. 

https://user-images.githubusercontent.com/42269993/180183160-a2ee88d3-3645-42ee-9791-05478d1e2fe6.mp4

A possible solution to all these problems is to keep the pagination state in the history, URL params might be used in this case.

**Comment by euanmillar** [comment]
Great improvement request @tahmidrahman-dsi !  Lets prioritise as I cant see any breaking change implication

**Comment by SyedaAfrida** [comment]
**Bugs:**
1. For all tabs, same records are showing in all pages and when clicked next page 1 record is added at the end of each page

https://user-images.githubusercontent.com/94350336/196164059-c7e1b644-c3fc-4f35-8c45-8421bc3fef08.mp4

2. My draft pagination do not work unless clicked on field agent/ health system

https://user-images.githubusercontent.com/94350336/196164610-f987f9ad-41d8-4f9a-a6e4-9c55aa1b9751.mp4

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/196393216-a16918e2-eaf8-42ad-b52e-5a8aa13c5e44.mp4

**Comment by anny320** [comment]
completed
