### ISSUE TITLE
Move the sending logic out of notification service into a country config package handler

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3673]
Currently countries are forced to use either Infobip or Clicktel.  

We have considered moving the notification service into the country config package but it doesnt make sense for core functionality to be built in another repo and not independently built.

So, we decide to keep notification service in core and do the message retrieval and translation step in core but we should move the sending logic to a handler in countryconfig like we do for registration validation, so that it can be coded to support any 3rd party API gateway.

- [x] Rename the [sendSMS](https://github.com/opencrvs/opencrvs-core/blob/90ba937d5711c89d55ccd42ead83518a1ff09441/packages/notification/src/features/sms/service.ts#L107) function in core notification to notifyCountryConfig and POST the data to the Farajaland handler.  Do not throw any error, just return 201.
- [x] The provider selection logic in this file: https://github.com/opencrvs/opencrvs-core/blob/develop/packages/notification/src/features/sms/service.ts  should be moved into Farajaland into a new route "notification" and handler called notificationHandler inside a new "notification" feature.  The handler will pick the provider and send the message.
- [x] Move the reading of all clickatell and infobip and provider related environment variables out of the constants.ts file in notification service in core and move them into the Farajaland constants file.
- [x] In Farajaland, move the SMS provider secret out of notification service in docker-compose.countryconfig.prod-deploy.yml into the countryconfig.  
- [ ] Update this documentation page: "https://documentation.opencrvs.org/setup/3.-installation/3.3-set-up-a-server-hosted-environment/3.3.3-create-docker-secrets-and-provision-an-sms-gateway"  to document the new location for the environment variables.

**Comment by yeasinhossain-dsi** [comment]
Assigning @euanmillar for the Last sub task: updating the document.
