### ISSUE TITLE
Client / Login: Check if Sentry config variable exists and only add if it exists index.ts

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3682]
Currently the application assumes Sentry is configured.  

~Also the populate default config for Farajaland contains a Logrocket URL.  That URL is no longer in use and should be removed. So we dont need to populate it.  Just change it to an empty string.~

- [x] In login - Check if Sentry config variable exists and only add if it exists index.ts
- [x] In client - Check if Sentry config variable exists and only add if it exists index.ts
- [x] Set Logrocket URL to an empty string in login-config.js, login-config.prod.js, client-config.js and client-config.prod.js

**Comment by Zangetsu101** [comment]
Closed by #3700 & https://github.com/opencrvs/opencrvs-farajaland/pull/324

**Comment by Zangetsu101** [comment]
Closed by #3700 & https://github.com/opencrvs/opencrvs-farajaland/pull/324
