### ISSUE TITLE
In review page Proof of legal guardian document is skipped or showing wrong verbiage in dropdown of review

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3683]
**Bug description:**
In review page Proof of legal guardian document is showing Informant's birth certificate in dropdown of review or completely skipped in review page if Informant's birth certificate is provided

**Steps to reproduce:**
1. Login as FA
2. Declare a birth event 
3. Go to supporting document page
4. Upload only Proof of legal guardianship
5. Go to review page and observe dropdown
7. Again go to supporting document page
8. Upload Informant's birth certificate also
9. Go to review page and observe dropdown

**Actual result:**
When only Proof of legal guardianship is given, the verbiage is showing Informant's birth certificate
When both Informant's birth certificate & Proof of legal guardianship is given, roof of legal guardian document is skipped in review page

**Expected result:**
Proof of legal guardianship should be shown in review page

**Screenshot:**
https://images.zenhubusercontent.com/91778759/80b985a4-fad7-4e30-a792-37fc6bbc29f8/proof_of_legal_guardianship_is_skipped_in_review_page.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![3683](https://user-images.githubusercontent.com/94350336/186128643-319069a9-c246-4c11-8b9f-b932a714097d.png)

**Comment by anny320** [comment]
completed
