### ISSUE TITLE
Replace Jest with Vitest

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#3687]
Replace Jest with [Vitest](https://vitest.dev/) in 
- `packages/client` 
- `packages/login`. 

Jest can still be used for our server-side packages.

Start with a singular test suite and expand. This task will be quite complex as we depend on Jest's mocking mechanism. It's probably not the only Jest-specific thing in our test suite. It's good to try and keep the test core otherwise as-is so that the scope of this task won't grow out of proportions. 

**After**
Once the tests work, remove all dependencies to craco and other things that remain to create react app. 

For example:
https://github.com/opencrvs/opencrvs-core/blob/5b176d25ec5a717e9a1276090eb07169e65485a1/package.json#L60-L65

Base branch for this should be the feature: CRA to Vitest: https://github.com/opencrvs/opencrvs-core/pull/3694
- [x] Replace jest with vitest in login, ensure coverage is reporting, update types and research if more work is required than expected
- [x] Ensure all dependencies of create-react-app and craco are removed in login
- [ ] Replace jest with vitest in client
- [ ] Ensure all dependencies of create-react-app and craco are removed in client

**Comment by Zangetsu101** [comment]
Done in #3703
