### ISSUE TITLE
SENTRY_DSN is hardcoded in core

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3696]
SENTRY_DSN must be provided as an environment variable to all the backend services including countryconfig in Farajaland's docker-compose files.

The URL should be: https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604

**Comment by Zangetsu101** [comment]
@euanmillar In which docker file should we put the `SENTRY_DSN` variable in?

**Comment by Zangetsu101** [comment]
Completed in #3713 and https://github.com/opencrvs/opencrvs-farajaland/pull/325
