### ISSUE TITLE
System crash when clicked certified from history of audit record page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3701]
**Bug description:**
System crash when clicked certified from history of audit record, only if that application is once corrected from certificate preview tab

**Steps to reproduce:**
1. Login as Local/ national registrar
2. Go to ready to print
3. Download> assign any record
4. Click Print> select any option> Print
5. Search that record with tracking id/ name
6. Download
7. Go to record audit page
8. Click Print
9. Go to certificate preview page> Click correct record
10. make any correction and submit
11. Search that record with tracking id/ name
12.  Go to record audit
13. Click Certified from history

**Actual result:**
system crash when clicked Certified

**Expected result:**
User should see certified audit page

**Screenshot:**
![new crash.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/147fe98a-8a03-4eef-a9a5-d1acf1b0b64c)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by yeasinhossain-dsi** [comment]
To reproduce this bug, we must print certificate choosing `Print in advance` as `Certificate collector`.
After fixing it, it seems that under `Printed on collection` there are empty rows. 

![Screenshot from 2022-08-04 18-23-59](https://user-images.githubusercontent.com/8198236/182847068-2d53549c-ad52-402c-ad73-79f48b8c3b6b.png)


@jpye-finch What should we display here?
1. Should we show `Printed on advance`
2. keep as it is
or 
Something else?

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed 
![certified passed](https://user-images.githubusercontent.com/94350336/185614521-c7a6b108-aada-46b7-ae53-715acc336452.png)

**Comment by anny320** [comment]
completed
