### ISSUE TITLE
When father and mother's details is set no there should be no upload option of supporting document in review page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3707]
**Bug description:**
when father and mother's details is set no there should be no upload option of supporting document in review page

**Steps to reproduce:**
1. Login as any user
2. Declare a birth event
3. Select Informant type anything except - Mother/ father
4. In Mother's detail page, Select No details
5 In Father's detail page, Select No details
6. Go to review page and observe supporting document option beside father & mother section
7. Click upload in mother / father section

**Actual result:**
1. There is upload option for mother and father document
2. There is no option to upload supporting document of mother and father in supporting document page, since their details are not available

**Expected result:**
1. The upload option for mother and father document should be hidden,  since their details are not available

**Screen recording:**
https://images.zenhubusercontent.com/91778759/c034cb17-66c7-4fe2-9b6b-32db19a02e4f/when_father_and_mother_s_details_is_set_no_there_should_be_no_upload_option_of_supporting_document_.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

- [ ] In ReviewSection, where DocumentViewer and LinkButton is rendered, only render the button if mothers or fathers details exist.  To do this, you need to create a new utility function, that checks that mother and father details exist. The conditional is:  "draftData && draftData.mother && !draftData.mother.detailsExist && !mothersDetailsExistBasedOnContactAndInformant" for mother and "draftData && draftData.father && !draftData.father.detailsExist && !fathersDetailsExistBasedOnContactAndInformant" for father.  The values mothersDetailsExistBasedOnContactAndInformant and fathersDetailsExistBasedOnContactAndInformant are calculated [here](https://github.com/opencrvs/opencrvs-core/blob/b32b9fc6b6f67f937536b1b0dd9c286112c15bbb/packages/client/src/forms/utils.ts#L531)

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/195032850-689170f1-668a-4dcb-b568-5d2beedcd663.mp4

**Comment by anny320** [comment]
completed
