### ISSUE TITLE
Tab name getting changed to "Loading" after refresh in Can't login page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3717]
**Bug description:**
Tab name getting changed to "Loading" after refresh in Can't login page

**Steps to reproduce:**
1. Click can't login
2. Refresh the page and observe

**Actual result:**
Tab name getting changed from Farajaland CRS to Loading

**Expected result:**
Tab name should be same after refresh

**Screen recording:**
https://images.zenhubusercontent.com/91778759/5d635b1b-2f48-43c6-ab7a-e8c0b923cb0f/tab_name_getting_changed_to__loading__after_refresh.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
We have what we need in terms of design so this is good to go.

**Comment by anny320** [comment]
completed
