### ISSUE TITLE
 Write a migration script for the field-agent started by bug

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3729]
- [ ] Create another script for mongo-migrate, connects to InfluxData, loops through every entry associated with the issue to get the composition id, but ignore hearth and get the task directly from mongo,  and update the started by property in Indexed DB to the correct value

**Comment by Zangetsu101** [comment]
@euanmillar Only the `declarations_rejected` measurement is affected. So only the points in this measurement need to be considered

**Comment by euanmillar** [comment]
@Zangetsu101 I tested this on the migration server again after your recent fix, but unfortunately it is still not working
