### ISSUE TITLE
Prepare backup of previous version data from production

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3732]
- [x] In production environment, we must create a registration and an in progress application that has the mistake in legal guardian proof before we make a backup for QA migration test. - 1
- [x] Reject some declarations created by multiple fieldAgents so that the startedBy tag in influxDB can be migrated - 1
- [x] Write a github action to run the emergency-backup script on production using config server IP to be the backup server. SSH into config and label the backups as v1.0.1.  - 2

**Comment by Zangetsu101** [comment]
The github action will need to be modified a bit to use the migration server.
