### ISSUE TITLE
In Review page of death application, since there is no separate option for Other documents of 'Proof of death of deceased' and 'Proof of cause of death', these documents are skipped or replaced

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3735]
**Bug description:**
1. When Other document of 'Proof of deceased's ID' is given and both other document of 'Proof of death of deceased' and 'Proof of cause of death' given, in review page only Other document of 'Proof of deceased's ID' is shown
2. When Other document of 'Proof of death of deceased' and 'Proof of cause of death' given only, in review page only Other  document of 'Proof of death of deceased' is shown

**Steps to reproduce:**
1. Login to any user
2. Declare a death event
3. Go to supporting document  page
4. Upload Other document of 'Proof of deceased's ID' 
5.  Upload Other document of 'Proof of cause of death
6. Upload Other document of 'Proof of death of deceased'
7. Go to review page

**Actual result:**
1. When Other document of 'Proof of deceased's ID' is given and both other document of 'Proof of death of deceased' and 'Proof of cause of death' given, in review page only Other document of 'Proof of deceased's ID' is shown
2. When Other document of 'Proof of death of deceased' and 'Proof of cause of death' given only, in review page only Other  document of 'Proof of death of deceased' is shown

**Expected result:**
Documents of 'Proof of cause of death' and 'Proof of death of deceased' should appear beside event details in review page

**Screen recording:**
https://images.zenhubusercontent.com/91778759/846b4c85-e849-4483-8543-a68a3273b3a6/library___loom___4_august_2022.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

- [ ] ReviewSection. prepSectionDocuments function should be refactored slightly to use the document subject and document type as a key in order to differentiate between "other" documents.  Select option label in this case should use the form field select labels on the document page followed by other like this in order to differentiate the 4 potential "Others":

"Proof of deceased's ID: Other"

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/195837323-6cf58d61-7d98-4a32-9c52-a736e97f89d3.mp4

**Comment by anny320** [comment]
completed
