### ISSUE TITLE
Migration approach for OpenHIM

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3738]
- [x] Create a nothing to v1.0.1 openhim base config migration script that populates openhim db into mongo directly. - 1
- [x] Create a v1.0.1 to v1.1.0 migration script to add the new channel directly into MongDB that was added to base config in [this PR](https://github.com/opencrvs/opencrvs-core/pull/3678) - 1
- [x] Yarn dev should run migrations - 1/2
- [x] Yarn setup.sh should run migrations after db is populated - 1/2
- [ ] yarn db:backup:restore should run migrations after the default backups are loaded in.

**Comment by Zangetsu101** [comment]
Done in #3847
