### ISSUE TITLE
Brand Storybook to OpenCRVS logo & colors

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#3743]
Add OpenCRVS logo and colors to Storybook. Just minimal configuration to be in line with the brand.

**Comment by jpye-finch** [comment]
![discourse-logo-dark](https://user-images.githubusercontent.com/46478402/183635520-11185642-4796-4323-ad67-72a5610b9b08.png)
![discourse-logo](https://user-images.githubusercontent.com/46478402/183635530-aed9706a-70f3-471a-b00d-b528a5d826c7.png)

Brand colour: #0058E0

**Comment by naftis** [comment]
@jpye-finch 
<img width="312" alt="image" src="https://user-images.githubusercontent.com/1322608/183843752-33f1cfeb-1f23-4b5c-ac21-51c5b9287a43.png">
Do we wanna use OpenCRVS favicon & maybe change the "Storybook" to "OpenCRVS Design System" or something 🤔

**Comment by jpye-finch** [comment]
Yep, the favicon file is above. That name works for me
