### ISSUE TITLE
Create RECORD_SEARCH system client to perform advanced search, return maximum number of full compositions

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3753]
- [x] Create a new system client with "recordsearch" scope. - 1
- [x] Create a new gateway query bound to this scope only, it calls the search service with these parameters.... all optional - 2

```
event 
eventLocationId
childFirstName
childLastName
childsDob
deceasedsIdentifier(NID)
deceasedsFirstName
deceasedsLastName
deceasedsDob
dateOfDeath

dateOfEventStart
dateOfEventEnd  === dob / date of death (within maximum 1 months), if supplied then ignore childsDob/dateOfDeath

mothersFirstName
mothersLastName
mothersDob
mothersIdentifier(NID)
fathersFirstName
fathersLastName
fathersDob
fathersIdentifier(NID)
informantsFirstName
informantsLastName
conatctNumber
brn - if supplied return 1 result
drn - if supplied return 1 result
trackingId - if supplied return 1 result
dateOfRegistration

dateOfRegistrationStart
dateOfRegistrationEnd (within maximum 1 months), if supplied then ignore dateOfRegistration
```

- [x] In search make a new advancedRecordSearch handler, it searches Elastic, gets maximum of 5 (ideally 1) compositionIds, if more than 5 return a response ("Too many results Please narrow your search"). (Only REGISTERED and CERTIFIED declarations should be returned) - 2

- [x] In gateway use functionality fetchBirthRegistration and fetchDeathRegistration functions for each of these max 5 comopositionIds.  We want to markRecordAsDownloaded by the system client practitioner so we need to save a Task to Hearth from gateway for each composition, but we do NOT want to assign the record. - 3

- [x] Make graphQL playground available in production - 1
- [x] Introduce a quota for individual recordsearch client. DESCRIPTION TO BE UPDATED MORE

- [ ] Update documentation for the new system client

**Comment by euanmillar** [comment]
@yeasinhossain-dsi could you possibly open a PR for this with a "work-in-progress" label asap so that @shukladhaval25 can monitor its development.  As soon as it is merged into develop we can share a Dockerhub githash so that they can use the pre-release in time for their schedule.

**Comment by yeasinhossain-dsi** [comment]
> @yeasinhossain-dsi could you possibly open a PR for this with a "work-in-progress" label asap so that @shukladhaval25 can monitor its development. As soon as it is merged into develop we can share a Dockerhub githash so that they can use the pre-release in time for their schedule.

@euanmillar PR is given:
https://github.com/opencrvs/opencrvs-core/pull/3834

**Comment by yeasinhossain-dsi** [comment]
After completing the 4th sub-task, The System admin name gets displayed on the history as he was the user to create the system client. May be we need to have a discussion on this.

![Screenshot from 2022-08-31 18-04-46](https://user-images.githubusercontent.com/8198236/187674900-27188de5-72a4-42d1-8bec-23adba5d4ab1.png)

**Comment by euanmillar** [comment]
Lets add MOSIP_UINTOKEN identifier as an optional search parameter too when this PR (https://github.com/opencrvs/opencrvs-core/pull/3724) merges in.  Expected next week.

**Comment by yeasinhossain-dsi** [comment]
Feedback from Demo, on history we should may show `External system search (API)` instead of `Downloaded`

**Comment by euanmillar** [comment]
I must make a Postman test collection

**Comment by Zangetsu101** [comment]
@euanmillar Merging #4251 might make the RecordAudit crash for the time being if there was an advanced search performed by a RECORD_SEARCH system client. We will address this in #3588

**Comment by euanmillar** [comment]
AdvancedSearch, Integrations and Health Integration V2 Epics all have an impact on how the record search works.  I cant test it.

https://github.com/opencrvs/opencrvs-core/issues/3753#issuecomment-1313186244
Comment on #3753 Create RECORD_SEARCH system client to perform advanced search, return maximum number of full compositions
@euanmillar Merging #4251 might make the RecordAudit crash for the time being if there was an advanced search performed by a RECORD_SEARCH system client. We will address this in #3588
<https://github.com/opencrvs/opencrvs-core|opencrvs/opencrvs-core>opencrvs/opencrvs-core | Nov 14th | Added by GitHub





1:37
https://github.com/opencrvs/opencrvs-core/pull/4251/files
1:38
The following lines got removed
  let user: IUserModel | null = await User.findOne(criteria)
  if (null === user) {
    user = (await System.findOne(criteria)) as IUserModel | null
  }
