### ISSUE TITLE
Show component names under React DevTools

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#3767]
It'd be nice to see `<Dropdown>` in React DevTools instead of `<styled.div>`. 

https://styled-components.com/docs/tooling#better-debugging

**Comment by Zangetsu101** [comment]
We should wait for the `vite` PR to be merged before proceeding with this as we won't be using webpack anymore then

**Comment by naftis** [comment]
Closing as stale. Let's re-open if someone finds this useful while developing the frontend.
