### ISSUE TITLE
Assess `<Layout>` component and create proper examples of layout usage

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3777]
We have alot of layout components in the app it seems:

- client/components/Page.tsx
- client/components/StyledPage.tsx
- packages/client/src/components/TransitionWrapper.tsx??
- client/src/views/SysAdmin/SysAdminContentWrapper.tsx
- client/App.tsx has const MainSection
- BodyContent
- components/layout/Page.tsx
- components/layout/PageWrapper.tsx
- components/src/components/layout/Content.tsx
- components/layout/Wrapper.tsx
- components/interface/ActionPageLight.tsx
- Lots of example of Wrappers and Containers redefined in Views. 

This ticket is to review and define an approach and refactor to layout components. To support the different template pages in OpenCRVS. 
https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=5497%3A14780

---

- [x] Create new `<Frame>` component
- [x] Create solid examples how to use it

**Comment by naftis** [comment]
(wip)

`packages/components/src/components/layout/Page.tsx` Only applies dimensions
* `App.tsx` which initialises the software

`packages/components/src/components/layout/PageWrapper.tsx` Applies dimensions and background-color
* `StyledErrorBoundary.tsx` -component
* `ForgotPIN.tsx` -view
* `Unlock.tsx` -view

**Comment by naftis** [comment]
## How do we use the current components?

`packages/components/src/components/layout/Page.tsx` Only applies dimensions
* `App.tsx` which initialises the software

`packages/components/src/components/layout/PageWrapper.tsx` Applies dimensions and background-color
* `StyledErrorBoundary.tsx` -component
* `ForgotPIN.tsx` -view
* `Unlock.tsx` -view

`packages/client/src/components/TransitionWrapper.tsx` This seems to be a wrapper for animation transitions between routes
* `App.tsx`

`packages/client/src/views/SysAdmin/SysAdminContentWrapper.tsx` Layout for SysAdmin view
* lots of views in `SysAdmin`
