### ISSUE TITLE
Addition of Multiple offices per District 

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3778]
### Description
The current[ setup for Farajaland ](https://documentation.opencrvs.org/default-configuration/opencrvs-configuration-in-farajaland/user-role-mapping)is designed to support one office per district level and the roles are mapped in the same way. The administrative design of Nigeria requires an expansion of this feature to support multiple offices per district.
_Background on Nigeria_ 
Nigeria is a federal republic with 36 self-governing states and a federal capital territory. Each state is further divided into Local Government Areas (LGAs). Currently, there are 774 LGAs.
The civil registration hierarchy is as follows:
Deputy Registrar-General:  The Deputy Registrar-General, heads the Vital Registration Department and oversees the operation of the registration system throughout the country.
Chief Registrar:  Each State has a Chief Registrar, also called a State Director, who supervises the system in the Local Government Areas (LGAs).  The Chief Registrar co-ordinates the registration system and forwards monthly and annual reports to the Registrar-General.
Deputy Chief Registrar:  The Deputy Chief Registrar, also called Comptroller, is the officer in charge of LGA’s civil registration system. The Deputy coordinates and supervises at least five registration centres under him/her and reports to the State Director.
Registrar:  This is the officer who registers vital events and issue certificates at local registration centers. There are a total of 4000 local registration service centres in the country.

**Scope**
- Enable addition of more than one office in a district setup
- Add new Map users roles for offices
- Link records  to appear in correct work queues aligned  to the new offices
...

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

(Link to Figma)

### Dev tasks

- [ ] Task 1

**Comment by euanmillar** [comment]
@anny320 & @eduffus & @jpye-finch Riku have tested multiple offices in the same district in Nigeria, for example PHC Karu office and NPC OFFICE KARU, in Karu district and the workqueues and performance all look fine suggesting this is currently possible.  Can you re-write this and expand on what you would like and what you feel is missing as the title of this ticket "Addition of Multiple offices per District" is already possible in OpenCRVS.

**Comment by anny320** [comment]
closing ticket, multiple offices per district currently works
