### ISSUE TITLE
Install Minio and refactor registration attachments to use Document Store

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3781]
- [x] Create docker-compose block for the minio docker image - 2
- [x] Bootstrap a documents microservice - 2
- [x] Write a handler to upload an image to the minio store - 2
- [x] Provision the encrypted shared volume for minio in Ansible - 2

https://docs.min.io/docs/javascript-client-api-reference.html

- [x] Expose documents.opencrvs.org through Traefik - 2

### regstration attachments

- [x] In gateway fhir-builders where FHIR DocumentReferences are created, we send the base64 or converted base64>file to the minio handler and retrieve a minio url.  The format of the minio url must contain uuid() so that it is secure.  Then we save that URL as the DocumentReference value - 2
- [x] In the client, where the document is rendered we change the approach from rendering base64 to an img tag where the src is the minio url - 3
- [ ] When the declaration downloads, ie in requestWithStateWrapper function, before the resolve, we need to loop through any Minio URLs that may exist in the declaration, if any exist we need to fetch the images so that the Browser caches them before resolving. 
 declaration. In src-sw.js registerRoute ensure that Minio urls are cached in the Service Worker.

### re mounting encrypted mino directory
- [ ] on system reboot.service & reboot.sh we need to mount the minio directory - BLOCK
- [ ] Documentation to update
- [ ] Migration to move all exsting document references into minio urls
- [ ] Set up authorization for the minio image

**Comment by Zangetsu101** [comment]
Done in #3858
