### ISSUE TITLE
In configuration, if a draft is saved, the version appears in In preview tab and shows error when try to Publish that draft

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3788]
**Bug description:**
In configuration, if a draft is saved, the version appears in In preview tab and shows error when try to Publish that draft

**Steps to reproduce:**
1. Login as national system admin
2. Click Configuration > Click Declaration forms
3. Click Configure/ Edit
4. make any change
5. Click Save> add description > Click save
6. Go to to In preview
7. Observe the version number of that event
8. Click Publish > Publish

**Actual result:**
shows error-
"Something went wrong. Please try again"

**Expected result:**
1. The version number of the draft should not appear in "in preview" before clicking Preview from 3 dot menu
2. After a version comes to In preview, admin should be able to Publish that version
![image](https://user-images.githubusercontent.com/29002716/185594897-bb19cf18-59e1-4e71-a334-379e317a26c3.png)

**Screen recording: **
https://images.zenhubusercontent.com/91778759/fc6d5c6b-6edf-4ac1-8a6b-1ae2b2b2132b/in_preview_error.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
@jpye-finch the suggested design change we are thinking to bundle with the future feature "post installation form config" as we will be refactoring this view a lot at that time.

**Comment by SyedaAfrida** [comment]
**Bug**: Cannot publish a configuration after it is made In preview. Publish link in In preview tab should be disabled when the version is saved as draft, **But** should be enabled after it is made In preview

https://user-images.githubusercontent.com/94350336/190333331-db9207d5-ffeb-4ed7-8fa4-1a2a00487659.mp4

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/190640400-50083a49-c524-41c2-8154-0b31d1ec1ea1.mp4

**Comment by anny320** [comment]
completed
