### ISSUE TITLE
Records/Notifications declared and registered should only appear in workqueues  of offices where they were created

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3789]
**Describe the bug**
when a record is declared / registered etc. it is now visible in WQs of every other office in the country. For example, in the screenshot below, the declaration of death was created by Kalusha in Ibombo District Office and is viewable in the "Ready for Review" WQ of Derrick Bulaya in Ilanga District Office. 
**To Reproduce**
Steps to reproduce the behaviour:
1. Login as a fieldagent make a birth/death notification
2. Submit the record for review or Register a record from ready to review workqueue
3.Login as a registrar from same office first then from a different office
4. You will notice that in the workqueues Ready for review and Ready to print the records appear in the workqueues
**Expected behaviour**
Records declared/Notified should only appear in work queues of offices they were created and only accessible via search function if being completed in different office by a registrar
**Screenshots**
![image (20).png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/38e8762d-7121-4e43-ba79-75078ed38347)If applicable, add screenshots to help explain your problem.
_**Track solomon king created by Kalushya from Ibombo**_ also, visible to Joshua in both ready to review and ready to print workqueue
![Screenshot 2022-08-16 at 11.15.17.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/c2d7064a-6ac3-4b90-893c-0ee92213ce4f)
![Screenshot 2022-08-16 at 11.20.06.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/b40f572b-8800-4fc1-bdeb-c5f9fd14b3ed)
**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/186608112-6ba9492c-745a-4725-8f8f-f314b919a25c.mp4

**Comment by anny320** [comment]
completed
