### ISSUE TITLE
Ensure that Document Store folder, clears, backs up and restores 

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3791]
- [x] Update Farajaland backup-metadata.sh, clear-all-data.sh to perform similar actions for Minio's db / store - 3
- [x] Update Farajaland emergency-backup-metadata.sh, emergency-restore-metadata.sh, restore-metadata.sh scripts to perform similar actions for Minio's db / store - 2

**Comment by SyedaAfrida** [comment]
This ticket do not require QA testing
