### ISSUE TITLE
Digitise paper record / Form versioning: Manage different forms over time -associate a record with a form configuration

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3798]
When legacy records are being digitise, they likely use a different version of the form.  Should their data be represented in the modern form with new potentially required fields blocking correction of that record until the data is supplied, or should a legacy record be associated with a different form configuration.  What should the user experience be for this?

Its possible that countries may decide to change their form configuration over time.  What if every declaration were linked to a specific version of the form configuration? That would make it possible to add/remove/modify fields later on without old declarations needing to be updated. If you’d open up a declaration from 10 years ago, it could be rendered using the form field configuration from the same period.

Form version is currently stored in config microservice: https://github.com/opencrvs/opencrvs-core/blob/4be3f5c7f7ca1a544fa945b6bf2b835211898049/packages/config/src/handlers/forms/formsHandler.ts#L73

**Comment by jpye-finch** [comment]
We've ticket for: Reference data version   [Form versioning #7463](https://github.com/opencrvs/opencrvs-core/issues/7463)
