### ISSUE TITLE
In sent for approval, a record is seen not assigned in workqueue but assigned in record audit, when registrar actually assign himself to the record

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3814]
**Bug description:**
From registration agent, In sent for approval, a record is seen not assigned in workqueue but assigned in record audit. In both cases, Registration agent should see Registrar is assigned to the record.

**Steps to reproduce:**
1. Login as Registration agent
2. Go to Ready to review tab
3. Click Download> assign > Review to any record
4. Click Sent for approval
5. Logout from RA
6. Login as Registrar
7. Go to ready for review
8. Click Download> assign to that record
9. Logout from Registrar
10. Login to RA
11. Go to sent for approval
12. Observe the record in work queue and Record audit page

**Actual result:**
1. The record is seen not assigned in workqueue by registrar but assigned in record audit
2. Registration agent is able to unassign registrar from the record in sent from approval tab

**Expected result:**
The record should be assigned to registrar in workqueue also
2. Registration agent should not be able to unassign registrar from the record in sent from approval tab

**Screen recording:**

https://user-images.githubusercontent.com/94350336/185867905-ad7fae2f-9aa3-4407-9e2d-e7ad76e1ebc2.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

- [ ] Make sure the assignment is shown in workqueue as well - 2
- [ ] When a registrationAgent downloads a sent for approval declaration, it should not be assigned to him/her - 1

**Comment by SyedaAfrida** [comment]
@anny320 This bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/190349269-117c8c3b-f7fe-480f-a66e-2f9988d30edd.mp4

**Comment by anny320** [comment]
completed
