### ISSUE TITLE
Missing features in record audit history details

### ISSUE THREAD

**Issue by yeasinhossain-dsi** [opencrvs/opencrvs-core#3816]
- Requester is not showing for `Corrected record` Action https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications-v1?node-id=1%3A3541
- Reason for Request (Other) the custom reason is not showing
- The ID check is always showing `No ID match` https://user-images.githubusercontent.com/94350336/185591197-a8fa9d6d-9aaa-49a3-836b-a7a5d4350d23.png

- [x] Make sure that the Corrector value is saved properly in backend and in record audit history we show the Corrector - 2
- [x] Save the custom reason in the backend and show the reason properly in record audit history - 2
- [x] Send the value of ID check to backend properly - 1

**Comment by yeasinhossain-dsi** [comment]
@anny320 This is how we are getting the requester. Not exactly like the figma design. Should we keep it as it is?

![Requester](https://user-images.githubusercontent.com/8198236/190139548-70df8825-d620-4f1b-a0b5-633c3449a673.png)

**Comment by jpye-finch** [comment]
expectation if it was requested by someone other than the informant. ie. no id check table
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications-v1?node-id=7667%3A135512

**Comment by yeasinhossain-dsi** [comment]
for Mother, Informer etc do we need to show the name also, because right now it is only showing the relation.

**Comment by jpye-finch** [comment]
@yeasinhossain-dsi let's block the ticket for now. 

Noticed some improvements we should make. Capturing more details if 'someone else' is requesting a correct. Similar to if 'someone else' is requesting a certificate be printed

**Comment by jpye-finch** [comment]
yep. @anny320 we can create an improvement ticket to capture the details of the certificate collector.

**Comment by euanmillar** [comment]
@anny320 @jpye-finch great, I will unblock this.  @yeasinhossain-dsi @Zangetsu101 which PR contains the work you did on this before it was blocked?  I want to link it and get this on QA / Closed.

**Comment by SyedaAfrida** [comment]
**Bug:**
When there is no ID match, still shows "ID verified" in corrected record of record audit page

https://user-images.githubusercontent.com/94350336/199482302-417ad1e5-c198-42fe-b6a6-f2b360a814c1.mp4

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![a](https://user-images.githubusercontent.com/94350336/204268732-236de106-045f-462b-9c02-e46f0b50f459.png)

**Comment by anny320** [comment]
completed
