### ISSUE TITLE
System crash if clicked back after printing or making correct record

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3818]
**Bug description:**
System crash if clicked back after printing or making correct record

**Steps to reproduce:**
1. Login as local/ national Registrar
2. Go to ready to print
3. Click print> print any record
4. Click back after coming to ready to print tab and observe
5. Again Login as local/ national Registrar
6. Go to ready to print
7. Download> Assign > Click any record
8. Click Correct record
9. Make any correction
10. Click Back button after coming to ready to print tab and observe

**Actual result:**
System crash if clicked back after printing or making correct record

**Expected result:**
User should not be able to go back after printing or correcting record

**Screen recording:**
1.
https://images.zenhubusercontent.com/91778759/c006ef27-2797-477e-81cf-63e756db59f6/system_crash_for_print.mp4

2.
https://images.zenhubusercontent.com/91778759/f7e5c934-2366-4fd2-8df5-9b450eec867d/system_crash_for_correct_record.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

- [ ] In ReviewCertificateAction and Payment and VerifyCollector, if no declaration can be found using the route parameter id in mapStateToProps for example, redirect the user to the readyToPrint tab

**Comment by euanmillar** [comment]
@jpye-finch this is why I hate these back buttons!  :D

**Comment by euanmillar** [comment]
@favour234 I would like this to be a hotfix release.  Could you checkout the branch release-v1.1.0 and start from there rather than develop please?  Please make a new branch from that called hotfix-v1.1.1-ocrvs-3818. Then your PR would have a base branch of release-v1.1.0.  Please discuss with @Zangetsu101 if you have any questions.

**Comment by favour234** [comment]
Alright..

**Comment by SyedaAfrida** [comment]
**Bug:** System crash still occurs when clicked back button multiple times after correction is made

https://user-images.githubusercontent.com/94350336/202365564-97fdb944-f775-4bf8-afbc-a8c89c1b5247.mp4

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/208373961-3aa5fde6-1c88-4b7e-bdbd-e4bf2a9fe160.mp4

**Comment by anny320** [comment]
completed
