### ISSUE TITLE
Rejected action appears twice in history of record audit page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3836]
**Bug description:**
When a  record is downloaded from Sent for approval tab, later since that record is found in downloaded state in requires update tab, after re-assigning again rejected action appears twice

**Steps to reproduce:**
1. Login as registration agent
2. Go to sent for approval
3. Download > assign any fresh record
4. Logout from RA
5. Login as Registrar
6. Go to ready to review
7. Download > assign that record
8. Click review
9. Click reject> Add comment> reject
10. Logout from Registrar
11. Login to RA
12. Go to requires Update
13. Click the record and observe history
14. Unassign from the record
15. Again assign to the record and observe history

**Actual result:**
Rejected action appears twice in history of record audit page- once shown rejected from registrar ( which is correct), another shown rejected from RA (which is incorrect)

**Expected result:**
Should show rejected once

**Screen recording:**
https://images.zenhubusercontent.com/91778759/d5b8a2c5-90a9-4867-8ef7-cc0b80d2deed/library___loom___23_august_2022.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/189605634-05b2785e-8f81-47a1-9d05-ec387830c2e6.mp4

**Comment by anny320** [comment]
completed
