### ISSUE TITLE
Calling the vs export endpoint in metrics from a new "schedulers" package

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3837]
We want to move all crons gradually into our stack as we can control our stack independently of the outside hardware 

- [x] Bootstrap a package called "schedulers" with a Dockerfile initialises a ubuntu:18.04 image and installs required dependencies like curl.  Package contains the crontab file and the shell script that the cron run.  Docker compose just deploys the image in 1 replica only.  Maybe comment in Docker Compose "# Never increase above 1". https://levelup.gitconnected.com/cron-docker-the-easiest-job-scheduler-youll-ever-create-e1753eb5ea44 in docker compose. - 3

- [x] The  job calls the metrics microservice to start the VS data export file generation process. We can use the approach used for backing up Influxdb in emergency-backup-metadata.sh that's in Farajaland. - 2

**Comment by SyedaAfrida** [comment]
blocked for #3639

**Comment by SyedaAfrida** [comment]
This ticket do not require QA testing
