### ISSUE TITLE
Create a github action to clear and restore the config environment that any Git user can use

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3839]
So that Syeda and Anne can clear the config env themselves.

No need to redeploy anything

Script SSH's into env, clears and restores the data

- [ ] Create a GitHub action that takes in a input of the environment to clear.
- [ ] ssh into the environment and run /opt/opencrvs/infrastructure/clear-all-data.sh 1 
  environment Input and make sure to provide the required secrets to the script
- [ ] After clearing the data run the opt/opencrvs/infrastructure/restore-metadata.sh 1 
  environment Input and make sure to provide the required secrets to the script as well

**Comment by Zangetsu101** [comment]
Done in #3876
