### ISSUE TITLE
Link Button

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3841]
Our Linkbutton component can only be regular or bold 16. 

Also has 'margin-left: -8px;'... 

This ticket is to refactor so that LinkButton can be:

Regular or Bold
Font size: 12, 14, 16, or 18
Colour: Primary, Disabled, Positive, Neutral or Negative 

Be apart of Button.tsx or keep separate?

**Comment by naftis** [comment]
We closed this in https://github.com/opencrvs/opencrvs-core/pull/4002 by creating `<Link>` which is a button that looks like a link.
