### ISSUE TITLE
When an application is created in one office and rejected from another office, the record should appear in the work queue of Requires Update of the office from which it is rejected from

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3845]
**Bug description:**
When an application is created in one office and rejected from another office, the record should appear in the work queue of Requires Update of the office from which it is rejected from

**Steps to reproduce:**
1. Login to registrar of location A
2. Copy the tracking ID of any Ready to review record
3. Logout
4. Login to Registrar of location B
5. Search the record with the tracking ID
6. Click Download> Assign > Review
7. Click Reject > Set comment > Reject
8. Observe the Work queue of Requires Update tab
9. Logout
10. login to Registrar of Location A
11. Go to Requires update tab
12. Observe the Work queue of Requires Update tab

**Actual Result:**
Rejected record is found in Workqueue of Requires update tab of Location A

**Expected result:**
Rejected record should appear in Workqueue of Requires update tab of Location B

**Screen recording:**
https://images.zenhubusercontent.com/91778759/a2d51b02-a638-4072-8153-05eca6f8d0eb/library___loom___25_august_2022.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
@eduffus @anny320 @jpye-finch is this a regression bug or a new use case we never considered previously?  The change request makes sense to me, but I just would like you to confirm, if it is being rejected by another office, is that office taking over responsibility for the rest of the process associated with this declaration?

**Comment by anny320** [comment]
Currently working correctly. The rejected record should be viewed by the registration agent that sent it for approval. to a bug.
