### ISSUE TITLE
In Can't login, Error message is not showing for empty input in security question and wrong verification code

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3846]
**Bug description:**
In Can't login, Error message is not showing for empty input in security question and wrong verification code

**Steps to reproduce:**
1. Click Can't Login
2. Click Password reset/ User reminder
3. Enter valid phone number> Click Continue
4. Enter invalid Verification code
5. Click Continue and observe
6. Enter valid Verification code > Click Continue
7. Keep answer field empty 
8. Click Continue and Observe

**Actual result:**
No error message is showing  for empty input in security question and wrong verification code

**Expected result:**
Should show invalid input

**Screen recording:**
https://images.zenhubusercontent.com/91778759/90c16b6e-2fda-4a4a-8cff-f1217301635c/error_message_not_showing_for_empty_string_and_wrong_verification_number.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

- [ ] In Farajaland, if practitioner.environment === 'development', we should hardcode 3 security question [keys](https://github.com/opencrvs/opencrvs-core/blob/b32b9fc6b6f67f937536b1b0dd9c286112c15bbb/packages/login/src/utils/authApi.ts#L51) and answers for test employee import [here](https://github.com/opencrvs/opencrvs-farajaland/blob/cfcd8ef9b90811ccfc35f6c230b8bb444dbc7fef/src/features/employees/scripts/service/index.ts#L224) we should populate some example security questions and answers.  The answers must be encrypted like we do in [activateUser](https://github.com/opencrvs/opencrvs-core/blob/b32b9fc6b6f67f937536b1b0dd9c286112c15bbb/packages/user-mgnt/src/features/activateUser/handler.ts#L58)

- [ ] We need to make a new default backup for the user-mgnt.gz and hearth-dev.gz so that developers and QA can test the fix

 - [ ] Update documentation for this [page](https://documentation.opencrvs.org/setup/3.-installation/3.2-set-up-your-own-country-configuration/3.2.4-set-up-employees-for-testing-or-production/3.2.3.1-prepare-source-file-for-test-employees)

- [ ] Fix to the bug is blocked until we can replicate with test users

**Comment by euanmillar** [comment]
@SyedaAfrida @anny320 doesnt sound like a regression bug as we havent worked on this area of the app at all.  I think this is a new bug, so we should move to Priority Bugs for discussion in Delivery Grooming

**Comment by euanmillar** [comment]
@SyedaAfrida which phone number on QA did you use to find this issue?

**Comment by SyedaAfrida** [comment]
@euanmillar though I found this issue for a newly created field agent's phone number, this issue actually appears for any newly created user

**Comment by euanmillar** [comment]
@SyedaAfrida when this merges, then you should be able to QA the cant login journeys on QA using the answer "test" for all security questions.   Security code is: 000000

**Comment by SyedaAfrida** [comment]
We can now test Can't login feature with any existing user like kennedy.mweene etc but the mentioned bug of this ticket is not fixed

**Comment by euanmillar** [comment]
So, the outstanding task is to check the error validation.

**Comment by asifjoardar** [comment]
@anny320 this ticket is fixed and can be closed.

[error-validation.webm](https://user-images.githubusercontent.com/35629053/210228174-96ed2104-2c1b-4085-9229-e4ef3e60fa16.webm)

**Comment by anny320** [comment]
completed
