### ISSUE TITLE
Add "By office" breakdown in performance

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#3848]
Related to: https://github.com/opencrvs/opencrvs-core/issues/3778

**Comment by euanmillar** [comment]
As per bug #3209 it isnt possible to show completeness rates for offices as they do not have population and crude birth rates.  This becomes an impossible problem when multiple offices share the same district

**Comment by euanmillar** [comment]
@jpye-finch @anny320 @eduffus can you discuss what you would like with @rikukissa and prioritise in design and product backlog alongside other core requirements.

**Comment by euanmillar** [comment]
Closing as performance view to be deprecated.  By office stats are achievable in Metabse
