### ISSUE TITLE
Update form config to include Conditionally fields shown

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#3852]
### Description
In Nigeria, we have added a field "State of origin" for both Mother's and Father's details. This information should only be collected when the person's nationality (the field above) is set to be Nigeria. Otherwise the field should be hidden.

<img width="314" alt="image" src="https://user-images.githubusercontent.com/1206987/186830611-13cdf828-3e3f-4c2c-8643-7ce26bea087c.png">

**Scope**
For this, I suggest we add a new configuration option for fields added through form config. 

...

### Acceptance criteria

a) In the health facility question if "Other" is selected THEN show a dropdown select with more options for places of birth (like a car, plane, church etc)
b) Given when you select Nigeria as nationality, THEN you can select a dropdown field showing the state of origin questions

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7293%3A7380

### Design Notes

- adds toggle to show Conditional fields
- adds headers with icon to each section. Use the new <Text> component if possible to make this easy

### Dev tasks

**Backend:** 

- [x] Include a conditional array in the config database that contains an object containing the target fieldId, and regexp. - 1
- [x] Ensure that the conditional field "question" handlers in the config microservice and gateway mutations can submit and retrieve the question with the conditional. - 1

**Frontend:** 

- [x] Ensure that the conditional array is returned correctly in the client in the [questionsTransformer](https://github.com/opencrvs/opencrvs-core/blob/b9fe6fdf048ada0800f770dd04fb44e859e99f34/packages/client/src/forms/questionConfig/transformers.ts#L130) function - 1
- [x] Ensure that the conditional array can be parsed by the client and applied to the custom field in the [createCustomField](https://github.com/opencrvs/opencrvs-core/blob/b9fe6fdf048ada0800f770dd04fb44e859e99f34/packages/client/src/forms/configuration/customUtils.ts#L33) function. - 1

A conditional looks like this:

```
conditionals: [
                  {
                    action: 'hide',
                    expression:
                      'draftData?.deathEvent?.causeOfDeathEstablished !== "true"'
                  }
                ],
```

We need to create a reusable function probably somewhere [here](https://github.com/opencrvs/opencrvs-core/blob/b9fe6fdf048ada0800f770dd04fb44e859e99f34/packages/client/src/forms/utils.ts#L521) for all custom field conditionals which creates the expressions string using the event, the final portion of the fieldId and parses the regexp appropriately.

- [x] Ensure that in the [Canvas > FormConfigElementCard](https://github.com/opencrvs/opencrvs-core/blob/b9fe6fdf048ada0800f770dd04fb44e859e99f34/packages/client/src/components/formConfig/Canvas.tsx#L133), if a conditional exists on the custom question, then add the icon and the fieldId to the card as we see in the Figma design - 1

![Screenshot 2022-09-23 at 11.00.06.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/d51dfdaa-6a04-4b49-a923-0a872f2f8282)

- [x] In CustomFieldTools.tsx, add the toggle to display the conditional parameters form.  When selected generate the select and the regexp required input.  - 1
- [x] In order to populate the conditionals fieldId select, we need to loop through all groups and sections in the event form and getFieldId using the sections and groups identifiers. Populate the select with options where the value and label is equal to the fieldId (only default fields) - 1
- [x] Ensure that the initial state, conditional form validation and submission saves the correct question configuration into the draft from CustomFieldTools - 1

**Comment by euanmillar** [comment]
@anny320 @eduffus @jpye-finch this is a high priority community requirement that both Nigeria and Mauritius have asked for.  So can it be designed soon?  Up to you.

**Comment by SyedaAfrida** [comment]
https://user-images.githubusercontent.com/94350336/197195629-b1fe98e1-5216-4ebd-9842-5e664750e54b.mp4

**Comment by SyedaAfrida** [comment]
**Bug:**
System crash occurs when try to edit a configuration from in preview

https://user-images.githubusercontent.com/94350336/199224448-9c835f1c-e427-4310-afe2-5bef812945dc.mp4
 
Cannot test #3927 also for this bug

**Comment by SyedaAfrida** [comment]
**BUG:**
1. Should not have the following dropdown options:
- birth.registration.who-is-applying-view-group.informantType
- birth.registration.contact-view-group.contactPoint
- birth.child.child-view-group.seperator
- birth.mother.mother-view-group.seperator
- birth.father.father-view-group.seperator
- death.registration.who-is-applying-view-group.informantType
- death.registration.contact-view-group.contactPoint
- death.deceased.deceased-view-group.seperator

2. System crash occurs when creating birth or death declaration when regvalue is wrong

https://user-images.githubusercontent.com/94350336/205601419-b6111468-693a-49aa-be86-d025bfeba6ec.mp4


3. able to save without french label and also regvalue

https://user-images.githubusercontent.com/94350336/205598471-248e29dc-a0aa-4296-9d90-58e9e106774b.mp4

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and I have created a new improvement ticket #4462 for the last bug as this would require tech design separately. So you may close this ticket.

https://user-images.githubusercontent.com/94350336/207524740-31302d65-4a1a-4a45-80bb-8f51e57dc672.mp4

**Comment by anny320** [comment]
completed
