### ISSUE TITLE
Critical information goes missing from logs

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#3854]
<img width="417" alt="image" src="https://user-images.githubusercontent.com/1206987/186833441-be3c9843-65a0-40af-8263-20754fc8ace6.png">

Logger info seems to support only one argument, so in many places, we lose the most critical piece of the logged information. Maybe it would make sense to have a shared "logger" module in packages/common?

```
{"level":30,"time":1661446944792,"pid":28,"hostname":"426f178a9a1f","msg":"isDemoUser"}
20:02:24.793
{"level":30,"time":1661446944793,"pid":28,"hostname":"426f178a9a1f","msg":"Sending a verification SMS"}
```

**Comment by Zangetsu101** [comment]
Weird because the type signature actually says that it supports multiple arguments

**Comment by rikukissa** [comment]
I think the rest argument is for filling placeholders if the first argument is a format string

```
* @param ...args: format string values when `msg` is a format string
```

**Comment by Zangetsu101** [comment]
ok makes sense now why it's not working as expected

**Comment by euanmillar** [comment]
This is a coding mistake that TypeScript doesnt catch.  All of these logs should be reformatted into string interpolation like this:

```
logger.info(`My message: ${JSON.stringify(obj)}`)
```
