### ISSUE TITLE
New input type for form config: dropdown / autocomplete

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#3855]
### Description

We need an input type from which the user can select an option from a predefined list of possible inputs. This is done instead of text input to improve the data quality for analytics purposes.

**Our use case**
We've added two new fields that we collect both for the Mother and Father of a child:

State of Origin (A state in Nigeria)
Ethnic Origin

<img width="780" alt="image" src="https://user-images.githubusercontent.com/1206987/186839069-af71bd97-1944-4b62-a774-b52adcf7c1cd.png">

We needed to define both of these as text fields, but for performance & analytics purposes, this isn't the ideal solution as users might, for example, use different spellings for the same state, which would make calculating the total registration by that State of Origin difficult.

According to Wikipedia, Nigeria has 36 states and around 400 different ethnic groups.

**Scope**

Create an input type that only allows selecting one option from a predefined group of values. National system admin can define these values as a list, separated by a line break.

### Acceptance criteria

1. Given when you select Nigeria as nationality, you can select a dropdown field showing the state of origin questions

2. Given  when  "mother or father details" are selected THEN show the dropdown select Ethnicity Origin select option

### Design

(Link to Figma)

### Dev tasks

- [ ] Task 1

**Comment by euanmillar** [comment]
In my view this should be low priority

**Comment by euanmillar** [comment]
The config UI for creating a select would need to be able to add options for the select.  A select option has a value with is what database stores and a label.  The labels need to be added for all languages. https://www.w3schools.com/tags/tag_select.asp

**Comment by anny320** [comment]
linking this ticket to https://github.com/opencrvs/opencrvs-core/issues/3990
