### ISSUE TITLE
Allow multiple spellings / names for an office / lga / state

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#3856]

**Comment by euanmillar** [comment]
@rikukissa could you be more specific describing this requirement?  How does it relate to FHIR Location alias use and translations?  Could you give some rough tech and design thoughts to help @anny320 define it with @jpye-finch please?  Moving to product backlog for prioritisation

**Comment by rikukissa** [comment]
This was related to some lga / state names having different spellings in different datasets, which we thought was because of different regional spellings. However, apparently, at least in Nigeria, there is an official spelling for each of them that we should use. We can close this for now.

**Comment by anny320** [comment]
ticket closed
