### ISSUE TITLE
Print button on mobile  not working correctly

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3859]
**Describe the bug**
Print button on mobile redirecting to a page that doesn't load.

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as a registrar on a mobile device
2. Click on  ready to print, assign file, after following the prompts, click the print button
3. It opens a new page that doesn't load and is blank

**Expected behaviour**
A printable version of the certificate should load correctly on a new page

**Screenshots**
![Screenshot 2022-08-29 at 08.33.54.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/600fd2cd-55a9-4679-af40-4e956934f5bf)
https://images.zenhubusercontent.com/91778759/3f8ef726-608b-4cbe-a4d3-dffd5b0d56cd/xrecorder_edited_28082022_182918.mp4

**Smartphone (please complete the following information):**
 - Device: Android
*  also tested  on Oppo A9 android v11.1 and bug reappears
**Additional context**

**Possible fixes**

Relevant link to review https://pdfmake.github.io/docs/0.1/getting-started/client-side/supported-browsers/
https://github.com/bpampuch/pdfmake/issues/800

- [ ] For mobile device, close the empty when printing the certificate

**Comment by Zangetsu101** [comment]
@anny320 In mobile we decided to not show the "empty" new tab. But the modal description says "A PDF of the certificate will open in a new tab - please print from there". We might need to change that

**Comment by jpye-finch** [comment]
@Zangetsu101 

On ios. After clicking Print in the model. You get another Print preview. So you can then Print. Is this not possible on Android?
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/b1cbb2d8-f8d9-4762-8e68-e203ab67f4b1)

**Comment by Zangetsu101** [comment]
@jpye-finch Chrome on Android doesn't have built in PDF viewer. So it just directly downloads the file

**Comment by euanmillar** [comment]
@sadmananik I would like this to be a hotfix release.  Could you close your existing PR, checkout the branch release-v1.1.0 and start from there rather than develop please?  Please make a new branch from that called hotfix-v1.1.1-ocrvs-3859. Then your PR would have a base branch of release-v1.1.1 (I will make this branch).  Please discuss with @Zangetsu101 if you have any questions.

**Comment by SyedaAfrida** [comment]
@anny320 I have tested this ticket both in browser stack and real device. Seems like we can close this ticket now. 

https://user-images.githubusercontent.com/94350336/194541828-165dc059-1f65-43df-a0db-65770e07c50e.mp4


https://user-images.githubusercontent.com/94350336/194541878-046498f5-ef3b-4e50-840a-6feebbd60065.mp4

**Comment by anny320** [comment]
completed
