### ISSUE TITLE
System crash when trying to print an application after printing it multiple times

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3864]
**Bug description:**
System crash when trying to print an application after printing it multiple time. Seems like crash occurs at 6th time while printing.

**Steps to reproduce:**
1. Login as registration agent/ registrar
2. Print any application 5 times
3. Search that application again
4. Go to record audit page
5. Click Print
 
**Actual result:**
system crash occurs

**Expected result:**
User should be able to print as many times as required

**Screen recording:**
https://images.zenhubusercontent.com/91778759/e6e9952f-6d45-448e-895c-d71a1027d6dc/system_crash_for_print_2.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
This issue is not properly fixed. Currently after a record is certified, when searched with the tracking Id, shows "No name is provided" in header and "no date of birth/death" in audit record page. Also when this record is printed again, Certified row is not added in history action.

https://user-images.githubusercontent.com/94350336/189628218-687ca2e0-83be-4e1f-acff-5dc674ba8aa3.mp4

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/190388063-60f49969-f609-48fa-9a7d-054d30bc56a1.mp4

**Comment by anny320** [comment]
completed
