### ISSUE TITLE
Supporting documents details should not be in updated action of history 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3868]
**Bug description:**
Supporting documents details should not be in updated action of history 

**Steps to reproduce:**
1.  Login as registrar
2. Go to any tab> click record
3. Click Updated action

**Actual result:**
Supporting document details is shown in updated action with invalid data

**Expected result:**
Supporting documents details should not be in updated action of history 

**Screenshot:**
![no need of adding supporting documents details in updated action of history .png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/1772fcee-36ad-49ef-a096-21e50bccd599)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by euanmillar** [comment]
If a document is changed or edited, in the edited column show the translation key constants.updated

We do not save the original filename or thenew filename in the database.  So to prevent this from a being a breaking change, we will just show copy saying that the document was updated.

**Comment by anny320** [comment]
closed, based on the updated copy fix.
