### ISSUE TITLE
System crash when testing Validate the view of performance tab when failed to load

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3870]
**Describe the bug**
The system is throwing an error when a user is navigating from offline state to online in performance  tab for a National Sys Admin
**To Reproduce**
Steps to reproduce the behaviour:
1. Login as a national sys admin
2. Click on performance tab
3. Go offline state  and refresh the tab to test that a message loads to show a user that the page cannot load when offline
4. Go online and refresh page, system throws an ops error 

**Expected behaviour**
System should reload the performance tab without crashing
**Screenshots**
![Screenshot 2022-08-31 at 05.49.32.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/1fc1b0e9-cc59-48be-ae3b-facb0236cc39)
https://images.zenhubusercontent.com/91778759/2a7a6e57-156d-447b-9f3b-09a8266ee4fd/screen_capture__41_.mp4
**Desktop (please complete the following information):**
 - chrome

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/189318648-8fc4db28-1f5d-463a-b540-a50c247ae6c7.mp4

**Comment by anny320** [comment]
completed
