### ISSUE TITLE
When offline Change link beside password in settings page should be disabled

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3873]
**Bug description:**
When offline Change link beside password in settings page should be disabled. Because user is able to set password offline but when link Confirm shows wrong error message. To avoid confusion  Change link  should be diabled.

**Steps to reproduce:**
1. Login to any user 
2. Go offline
3. Go to settings
4. Click Change link
5.  Enter valid current password, New password and Confirm password
6. Click Confirm

**Actual result:**
 shows error- "Current password incorrect. Please try again."

**Expected result:**
Change link should be disabled 

**Screen recording:**
https://images.zenhubusercontent.com/91778759/91d17091-11bd-48ec-ba7f-5dbd3d3bcc5d/password_change_offline.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/189301729-3762ff05-00ac-44da-b224-a50288ac2887.mp4

![oofline pswd](https://user-images.githubusercontent.com/94350336/189301755-7a5cd2de-5e6a-4bf5-ac77-25ee5d031644.png)

**Comment by anny320** [comment]
completed
