### ISSUE TITLE
Remove current Outbox blue bar and replace with a dedicated Outbox page accessible on the sideNav

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3894]
### Description
1. The new outbox page link on the sidenav should be placed at the bottom of the workqueue
2. Add Outbox link  for these users FieldAgent, Registration Agent, Registrar, National Registrar
3. Outbox link should be visible for desktop view and mobile view

### Acceptance criteria

Given that a user is scrolling the side Nav WHEN Outbox is clicked THEN it should load the Outbox page

### Design

https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7169%3A3338

### Dev tasks

- [ ] Task 1

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is tested. You can review outbox testcases and close the ticket.

https://user-images.githubusercontent.com/94350336/197960549-a92d552c-7b30-4913-8554-98325c825c48.mp4

![outbox3](https://user-images.githubusercontent.com/94350336/197960587-c282ed8a-f164-4d51-8555-11f666d3deb5.png)
![outbox 2](https://user-images.githubusercontent.com/94350336/197960590-dd6445d8-4520-467c-b301-730b5d97f84a.png)

**Comment by anny320** [comment]
completed
