### ISSUE TITLE
Records in the outbox page should appear in a table format

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3897]
### Description
Create a table with 4 columns for outbox page. The column titles are Record,Event, Date of Event and the last column for the action.
The record column should include the icon of the work queue it just left.
...

### Acceptance criteria

Given that a user navigates to the outbox page WHEN there are records being processed in the outbox, THEN Records should appear in a table with columns. The table should include the Icon of the work queue it just left + Record column, Event (birth/death), Date of Event, Action and Status icon.

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7170%3A3964

**Comment by euanmillar** [comment]
@anny320 Tahmid already made dev tasks for this in the Epic which was created on 28th June and discussed in Delivery Backlog Grooming on 9th August.  So this ticket can be considered a test case.  Not any dev required, once Tahmid's PR merges in

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is tested. You can review outbox testcases and close the ticket.

https://user-images.githubusercontent.com/94350336/197960549-a92d552c-7b30-4913-8554-98325c825c48.mp4

![outbox3](https://user-images.githubusercontent.com/94350336/197960587-c282ed8a-f164-4d51-8555-11f666d3deb5.png)
![outbox 2](https://user-images.githubusercontent.com/94350336/197960590-dd6445d8-4520-467c-b301-730b5d97f84a.png)

**Comment by anny320** [comment]
completed
