### ISSUE TITLE
Add pagination to the outbox page

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3899]
### Description
If multiple records are being processed in the outbox, add pagination to support navigation of the records.
...

### Acceptance criteria

GIVEN there are multiple records being processed in the outbox page, when a user scrolls past 10 records, they should see pagination and be able to navigate to next page

### Design

https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7170%3A3473
### Dev tasks

- [ ] Task 1

**Comment by euanmillar** [comment]
@jpye-finch @anny320 @eduffus  we dont see any benefit of adding pagination to the outbox.  It increases dev time, and essentially this is just a log where you can monitor what is being sent.  You cant do anything with these entries as record audit links will be disabled.  Pagination improves visual representation of the data but pagination is a user experience benefit if you need to say jump to page 3 and remember that declaration X was on page 3. There is no user requirement for that in the Outbox, so for now can we just have a scrolling list please.

**Comment by anny320** [comment]
Hi @euanmillar  we are OK with the scrolling list, @JPF will reach out but this ticket can be unblocked

**Comment by euanmillar** [comment]
@anny320 this should be closed then as not required I guess

**Comment by anny320** [comment]
closed
