### ISSUE TITLE
Outbox link on sidenav should show count of records being processed

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3900]
### Description
Increase or decrease the count of records in the outbox and show the count of records in the side nav next to outbox label
...

### Acceptance criteria

1. Given there are unsent records in the outbox WHEN a record is sent from the outbox, THEN the count of the items pending in the outbox decreases by 1
2. Given that the user is viewing the WQs, WHEN a record enters the outbox, THEN the count of the items pending in the outbox increases by 1

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7170%3A3964
### Dev tasks

- [ ] Get all declarations in outbox that are in progress and ready status and send the sum of these as a count to Navigation.tsx - 1

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is tested. You can review outbox testcases and close the ticket.

https://user-images.githubusercontent.com/94350336/197960549-a92d552c-7b30-4913-8554-98325c825c48.mp4

![outbox3](https://user-images.githubusercontent.com/94350336/197960587-c282ed8a-f164-4d51-8555-11f666d3deb5.png)
![outbox 2](https://user-images.githubusercontent.com/94350336/197960590-dd6445d8-4520-467c-b301-730b5d97f84a.png)

**Comment by anny320** [comment]
completed
