### ISSUE TITLE
Smarter way to verify stack is up before clearing data on deployment

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#3903]
https://github.com/opencrvs/opencrvs-core/blob/develop/deploy.sh#L301

We've noticed that our deployment script randomly fails because Elasticsearch isn't ready to receive connections after 120 seconds.

This task should be planned to be a part of https://github.com/opencrvs/opencrvs-core/issues/3675

**Comment by euanmillar** [comment]
I think I can close this in favour of the Epic now
