### ISSUE TITLE
Configure SMS messages to informant and users

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3910]
https://www.notion.so/opencrvs/7d321101427640088c305b8bf630aa21?v=cd71becb0d0e4c14a13e67ba38fba1ac&p=1694d85b830d4e04a834d6a8fa1e507f&pm=s

### **Problem statement**
Not all countries want to use SMS to notify informants of progress to a record; it is an added cost. Especially if the process is being done in the community and printed on the spot (case study Nigeria).

So countries don’t have to custom configure OpenCRVS the option to select what SMS’s to send should be made available as part of Communication management 

### **Proposed work**
Add config option for each SMS to toggle on/off
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8837%3A63545

### **Scope**
SMS messages to informant

### **Future work**
Consider other comms channels eg. email and whatsapp

**Comment by euanmillar** [comment]
So this would require a design from @jpye-finch in application configuration, including an explanation of whether or not this affects 2FA SMS messages.  Moving to Product Backlog for prioritisaion.

**Comment by anny320** [comment]
@jpye-finch have added the context for this ticket, the disabling of 2FA would require an alternative available for login,  and @euanmillar  also informed that if the SMS code is not configured then SMS to informants is not enabled. Please work on the next ticket and up this back in backlog till when we are able to add other forms of login. cc @eduffus
