### ISSUE TITLE
Configuration of changes after install like reference data, form fields etc

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3912]
### Description
Configuration changes after installation (once there is live data in the system) reference data changes, and modified form fieldset.
...

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

(Link to Figma)

### Dev tasks

- [ ] Task 1

**Comment by jpye-finch** [comment]
@anny320 This needs further clarification of what is required. What function and tasks does it link to?

**Comment by euanmillar** [comment]
Closing as will be addressed by functionality inherent in #3798
