### ISSUE TITLE
Configure what vital events to register

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3925]
### Description
 As a national system admin I need to be able to toggle on/off functionality in the configuration panel that I want to make available to users in order to have greater control of my QA/Prod environments and make functionality available as it is ready.
Toggle on/off:
- Vital events that can be registered (e.g. birth/death/marriage) -> if off, then vital event is not an option when you click the blue +

...
...

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

(Link to Figma)

### Dev tasks

- [ ] Task 1

**Comment by euanmillar** [comment]
Exists in 1.3.0
