### ISSUE TITLE
Has a cause of death been established? should be defualted to No

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3926]
**Bug description:**
Has a cause of death been established? should be defualted to No and use checkbox in place of radio button

**Steps to reproduce:**
1. Login as FA/ RA/ registrar
2. Declare a death event
3. Go to Event details page
4. Observe " Has a cause of death been established?" 

**Actual Result:**
Has a cause of death been established? is defualted to Yes and uses radio button

**Expected result:**
Has a cause of death been established? should be defualted to No and use checkbox in place of radio button

**Screenshot:**
![image (4).png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/8b7ee192-faa5-420d-bbaf-de0d40859837)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

- [x] Remove the radio button component from default.ts and replace with a CheckboxGroup.  Retain as many of the default.ts JSON props as possible.  In CheckboxGroup, if only one option is passed to it, do not wrap the component in a List.

**Comment by jpye-finch** [comment]
Design https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications-v1?node-id=3791%3A91578

**Comment by euanmillar** [comment]
We have what we need in terms of design so this is good to go.

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/202141673-3e1ffe01-bc0c-418d-a50c-4ecd486fd24b.mp4

![mob for death](https://user-images.githubusercontent.com/94350336/202141694-83d36317-f79b-4db8-9be1-1590cdff4719.png)

**Comment by anny320** [comment]
completed
