### ISSUE TITLE
Add field ID section on the right side nav  in form config

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3927]
### Description
In form config where we show content keys, also add a section showing the fieldID
...

### Acceptance criteria

GIVEN when a field is selected in form config
WHEN clicked
THEN show Field ID on the right side Nav 

### Design

https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7296%3A8167

### Dev tasks

- [ ] Ensure that the selected fieldId is visible in DefaultFieldTools

**Comment by SyedaAfrida** [comment]
**Bug:**
System crash occurs when try to edit a configuration from in preview

https://user-images.githubusercontent.com/94350336/199224448-9c835f1c-e427-4310-afe2-5bef812945dc.mp4

**Comment by CornelMaze** [comment]
I could not reproduce this error.

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is tested and can be closed

https://user-images.githubusercontent.com/94350336/205565123-57f9deba-c8d8-4a17-997d-7527e6d6a658.mp4

**Comment by anny320** [comment]
completed
