### ISSUE TITLE
In "Print" and "Correction record" if a change is made and then clicked back, old data still appear after user try to print or correct record the next time

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3933]
**Bug description:**
In "Print" and "Correction record" if a change is made and then clicked back, old data still appear after user try to print or correct record the next time. All the old data should be cleared after user clicks back.

**Steps to reproduce:**
1. Login as Registrar
2. Go to ready to print
3. Download> Assign any record
4. Click on that record
5. Click Correct record
6. Make some changes
7.Keep on clicking back and come to record audit page
8. Again click correct record and observe

Again
1. Go to ready to print
2. Download> Assign any record
3. Click on that record
4. Click Print
5. Fill up some information
6.  Keep on clicking back and come to record audit page
7. Again click Print

**Actual result:**
User can see old filled up 

**Expected result:**
All the old data should be cleared after user clicks back because sometimes Continue button might be disabled (example Correct record)

**Screen recording:**
https://images.zenhubusercontent.com/91778759/8bc8d0ba-4688-4e6e-8989-e4f496349c3d/cache_not_cleared_in_correct_record.mp4

https://images.zenhubusercontent.com/91778759/1d61d6f8-bef7-4598-87d5-7d7f047c8c7a/cache_not_cleared_in_print.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
We have what we need in terms of design so this is good to go.

**Comment by euanmillar** [comment]
Lets just clear the radio group on component dismount

**Comment by anny320** [comment]
completed
