### ISSUE TITLE
Upload supporting document page should not appear when correcting a record

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3940]
**Bug description:**
Upload supporting document page should not appear when correcting a record. Currently when a record has supporting document, in correction record Upload Supporting document page appears. Bur it do not appear when a record do not have any supporting document.

**Steps to reproduce:**
1. Login as registrar
2. Go to ready to print tab
3. Download> assign any record which has supporting document in it
4. Click Correct record
5. Go to correct record page
6. Click any Change link
7. Keep on clicking Continue to see if Upload supporting document page appears

**Actual result:**
Shows Upload supporting document page

**Expected result:**
Should not show Upload supporting document page

**Screen recording:**
https://images.zenhubusercontent.com/91778759/773e9b5d-09fc-43f9-a46a-46bd9fbd1fea/library___loom___16_september_2022.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
@SyedaAfrida I was referring back to this ticket: https://app.zenhub.com/workspaces/opencrvs-core-5afeded64a54b06b54a969b2/issues/opencrvs/opencrvs-core/2401 in the Correct Record initial requirements.  It says the page should appear but the delete button should be disabled.  Isn't that the bug?  The delete button on any document should not appear for a record correction?  What do you think @jpye-finch @anny320 ?  Moving to Product Backlog for further discussion.

**Comment by anny320** [comment]
Its ok for it to appear to support the record correction
