### ISSUE TITLE
As a Registration Agent/ Registrar/ National Registrar/ Local or National System Admin, I would like to audit a user recent actions

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3942]
### Description
- adds History table to User Audit
- adds time period filter
- adds additional system actions eg logged in. 
- disabled action links for system admins
- disabled action links for actions performed by a system admin. if a RA/Reg/National/Reg is viewing a System Admin use audit page

**Table of audit actions**
https://www.notion.so/opencrvs/User-Audit-9b5377f3d8f54601b778080f4dfa5f6d

**New system actions**
- Logged in
- Logging out
- Username reminder sent
- Password reset
- Changed password
- Changed phone number

**New system actions by system admins**
- Created User
- Edited user
- Reactivated
- Deactivated

### Acceptance criteria

GIVEN I am on a User Profile Page
THEN I can view a list of recent actions (Last 30 days)

GIVEN I am on a User Profile Page
WHEN I click on the time period filter
THEN open the time period filter model

GIVEN I change the time period filter
WHEN I click confirm
THEN show the loading state for the History table

**GIVEN I am a National or Local System Admin
WHEN I navigate to a RA/Registrar/ National Reg user page
THEN I record action links and Tracking IDs are disabled**

---

GIVEN a user logs in successfully
[THEN the system should record the action 'Logged In'
](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7343%3A13106)

GIVEN a user resets their password
THEN the system should record the action 'Reset password'

GIVEN a user requests a username reminder
THEN the system should record the action 'Username reminder requested'

GIVEN a user logs out
THEN the system should record the action 'Log out'

GIVEN a user changes their password from the Settings page
THEN the system should record the action 'Changed password'

GIVEN a user changes their phone number
THEN the system should record the action 'Phone number changed'

---

### Local and National System Admin

GIVEN I am a National or Local System Admin
WHEN I navigate to a National or Local System Admin user page
THEN I can see a History table of actions

GIVEN I am a RA/Registrar or National Registrar
WHEN I navigate to a National or Local System Admin user page
THEN I action links are disabled

GIVEN a system admin edits a user
THEN the system should record the action 'Edit user'

GIVEN a system admin creates a user
THEN the system should record the action 'Created user'

GIVEN a system admin deactivates a user
THEN the system should record the action 'Deactivated user'

GIVEN a system admin reactivates a user
THEN the system should record the action 'Reactivates user'

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7087%3A1020

- [RA/Registrar/National Registrar viewing another RA/Registrar/National Registrar 
](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7746%3A21617)

- [Local/National System Admin viewing a RA/Registrar/National Registrar](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7292%3A8515)

- [Local/National System Admin viewing another Local/National System Admin  
](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7344%3A6009)

- [RA/Registrar/National Registrar viewing a Local/National System Admin  ](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7913%3A22961)

### Dev tasks

Front end outstanding tasks:

- [x] Connect client to new user audit backend (https://github.com/opencrvs/opencrvs-core/pull/3949) - 3
- [x] Build the UI for the date range picker - 2
- [x] Populate the new history columns including add metadata to the user audit table (user agent and ip address)
- [x] Ensure that the ResponsiveModal opens for each audit event with the information in the Notion document and Figma design - 2

Back end tasks - 5

For the following system related actions, ensure that the user agent and ip address headers are receivable in auth microservice and that the metrics microservice tracks an appropriate user audit action from **user-mgnt**. The user-mgnt microservice requires the URL to metrics in docker-compose. In these cases the practitionerId would be the user using the app

- [x] Username reminder sent (login app)
- [x] Password reset (login app)

- [x] Changed password (client settings)
- [x] Changed phone number (client settin**gs)

For the following system related actions, ensure that the user agent and ip address headers are receivable in auth microservice and that the metrics microservice tracks an appropriate user audit action from **auth**.  The auth microservice requires the URL to metrics in docker-compose. In these cases the practitionerId would be the user using the app

- [x] Logged in ( call from [here](https://github.com/opencrvs/opencrvs-core/blob/3cd67f5966c1eb4dd590a3765e8979bc718dac36/packages/auth/src/features/verifyCode/handler.ts#L52) after 2FA passes)
- [x] Logging out (send practionerId inside the authApi invalidateToken POST alongside the token so that we can track the audit event [here](https://github.com/opencrvs/opencrvs-core/blob/3cd67f5966c1eb4dd590a3765e8979bc718dac36/packages/auth/src/features/invalidateToken/handler.ts#L26) )

For system administrators performing the following actions on behalf of a user, the practitionerId would be the system admin's practitionerId, but lets save the subject of the action's practitionerId in the audit event too just in case we need it.  Call it subjectPractitionerId.

- [x] Changed phone number (Team) -  We should pass the sys admin's practionerId through the createOrUpdateUser mutation from the client. In user-mgnt, we should check that the incoming mobile number is different from the existing before dispatching the audit action [here](https://github.com/opencrvs/opencrvs-core/blob/3cd67f5966c1eb4dd590a3765e8979bc718dac36/packages/user-mgnt/src/features/updateUser/handler.ts#L55)

**Comment by euanmillar** [comment]
@jpye-finch @anny320 my bad.  Sorry we can't track 2FA failed attempts after all so we have to remove this audit item.  Essentially we cant get enough user information from Login during 2FA

**Comment by euanmillar** [comment]
@jpye-finch we thought about the cases where a sys admin is changing someone else's password or phone number.  we need to think about these too right?

**Comment by jpye-finch** [comment]
@euanmillar currently defined in a separate issue https://app.zenhub.com/workspaces/opencrvs-core-5afeded64a54b06b54a969b2/issues/opencrvs/opencrvs-core/3972

**Comment by anny320** [comment]
Update: Removed the 2FA=Failed acceptance criteria notes and added the system admin acceptance criteria from #3972

**Comment by SyedaAfrida** [comment]
**Bug:**
1.  Following actions do not appear in user auidit history- sent incomplete, update, certified, archived, reinstated to inprogress/ reinstated to ready for review/ reinstated to Requires Updates, Retrieved

https://user-images.githubusercontent.com/94350336/200825139-7702738c-efdc-4f10-952b-cc7a52f0a67c.mp4

2. following action names need to be changed- "Sent notification - complete" to "Declaration started", "Registered vital event" to "Registered", "Corrected" to "Corrected record"
3. When RA himself creates a record and send for approval, then in user audit "Send for approval" action is not showing

https://user-images.githubusercontent.com/94350336/200826297-d9238857-6d06-46af-9ac5-7098feec4f2f.mp4

4. font size issue-
![font size to 14px](https://user-images.githubusercontent.com/94350336/200826433-86dad6be-4a57-4649-820f-9e1729567192.png)

5. Mobile and tablet view design needs to update. Check the design:
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=9532%3A54496
tablet design https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=9532%3A55868

6. action links should be enabled in mobile view

https://user-images.githubusercontent.com/94350336/200829145-6008ca90-6911-44a5-af1b-c4ee9d1068ca.mp4


**Note:**
following actions cannot be tested unless other bugs(4199, 4208, 4209 ,4218, 4232) are fixed- 
New system actions-
Password reset
Changed password
Changed phone number

New system actions by system admins-
Created User
Edited user
Reactivated
Deactivated

**Comment by SyedaAfrida** [comment]
**Bugs:**
1. Sent incomplete action not showing

https://user-images.githubusercontent.com/94350336/208880722-355b192d-7e16-4f56-99c2-a9e7b0be1578.mp4



2. Reinstated to requires update action is showing as Rejected

https://user-images.githubusercontent.com/94350336/208881357-5c540746-72a6-453b-9246-42a9a0cf55e9.mp4



3. In User audit, Updated action should show in modal-item, orginal, edit
![in User audit, Updated action should show table-item, orginal, edit](https://user-images.githubusercontent.com/94350336/208881800-81478947-e7a1-4ff6-97c5-1e1119a153d1.png)

4. In User audit, corrected action should show in modal -- Reason, ID Check, in table show 3 columns: Item, Original, Edit
![In User audit, Correct record not showing table](https://user-images.githubusercontent.com/94350336/208881893-899629c8-08bb-47ca-989b-42e94d2e1abb.png)

5. In User audit, Rejected action should show  -- Reason, Comments
![In user audit rejected action not showing reason and comment](https://user-images.githubusercontent.com/94350336/208881953-6ec18443-0a6c-4d62-a6ee-0ff869baa0fb.png)

6. Create User, Edit user, Deactivate user & Reactivate user modal showing only User name row. Follow the figma design to view the modal
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7343%3A13555&t=2z08lsD9gUKjdQGa-0

7. In mobile view of user audit, should be able to show full table by scrolling side wise similar to that of record audit

https://user-images.githubusercontent.com/94350336/208882059-6acb4384-9e30-4edb-8a06-8861017de500.mp4


8. Create user, edit user, deactivate user, Reactivate user, Sent password, username reminder- these actions should be disabled when logged in from RA/ registrar and viewed user audit page of any local or national system admin
![in RA or reg, sys admin's special actions should be disabled](https://user-images.githubusercontent.com/94350336/208882236-6c6f7902-562e-43d7-a2c7-43371155faa9.png)

**Comment by euanmillar** [comment]
@jpye-finch @eduffus @anny320 We need to talk about these ones (4,5,6).  The knock-on effect of having modals in user audit that show the record correction / comment details that you see in the modals of record audit cannot currently be done.  The reasons for this are based on downloading and auditing & technical performance.  In Record Audit, the user has downloaded the full record (including all Task history containing the relevant PII, comments etc) and had this download action audited against that record in the backend.  In user audit this has not been done, so the data is inaccessible to us at this point without a download and audit action.  Secondly, user audit is architected to track actions in the metrics microservice (designed in 2022) so that they can be quickly received on this page, we just get all metrics for a given user in the InfluxDB = fast. If we were searching all registration FHIR Compositions and FHIR Tasks in Hearth to find any task a user's FHIR Practioner ID has performed, then mash those results up with the InfluxDB metrics (logged-in/out) etc = slow.  So, for these reasons there now seems little value in keeping a modal overlay in user audit.  The TrackingID is already a link, which takes you to the Record Audit page, where you can download the full record and have the access to PII audited appropriately.  My suggestion is therefore to remove modals from the User Audit page as all the current user audit modal information is already visible n the table.

**Comment by euanmillar** [comment]
@SyedaAfrida regarding the Figma link you shared regarding how user audit modals should look in (6), this is a Figma link in a ticket #3972 which @anny320 closed.  The Figma link on this story doesnt show those modals.  So these modals did not get technically designed or built.  Are they in fact required @jpye-finch ?

**Comment by SyedaAfrida** [comment]
@anny320 Bug (3,4,5) is not fixed as user should not be able to see the detailed information of the record from user audit without assigning/ downloading the record. For bug (6) we need confirmation from @jpye-finch.   For bug (8) Sent password, username reminder cannot be kept disabled as this can be done from both team and Can't login option. 
Other than this rest of the bugs are now fixed

https://user-images.githubusercontent.com/94350336/210532334-6e0527c7-5e04-45fc-bc74-8bf966f7dbac.mp4

**Comment by jpye-finch** [comment]
6) Should be 'Sent for updates' and yes with Comments.

Note that the Reason (the checkboxes in the Send for updates model) are being removed in another ticket

**Comment by jpye-finch** [comment]
4) the copy should be 'Record corrected'

**Comment by jpye-finch** [comment]
Please note the actions done on a record. Should be exactly the same as those in Record Audit. Need to ensure the copy is the same and the same content is shown in the model.

So there is no difference between the User Audit view and Record Audit view

https://www.notion.so/opencrvs/632eb35dbb4e43bb97e3927c8640ff7d?v=38f05b50daf7428cb8cde2f9a08372d8

**Comment by jpye-finch** [comment]
Noe the copy for the actions done on a record should be exactly the same as those in Record Audit. 
https://www.notion.so/opencrvs/632eb35dbb4e43bb97e3927c8640ff7d?v=38f05b50daf7428cb8cde2f9a08372d8

**Comment by jpye-finch** [comment]
yes @euanmillar didn't add model design or ac's... sorry and assumed the same code would be used as in Record Audit... as those actions and model should be the same. So we need to the discuss the point you raised above about how that data is fetched when you assign/download the record

**Comment by jpye-finch** [comment]
imo. if we just make sure the name of the action is the same as that in Record audit. We can close the ticket

**Comment by anny320** [comment]
completed
