### ISSUE TITLE
Component / <Checkbox>

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3970]
### Description
- review and refactor checkbox component
- improves hover state and click area (as small variant is also 40x40px)
- adds small and large variant

### Design
https://www.figma.com/file/SsqCzO2eherXXCKyixmli9/OpenCRVS-Design-System-v2-WIP?node-id=210%3A8932

### Dev tasks

- [x] Check the proposed design and ensure that all checkboxes in the application use the refactored Checkbox.  Update the component-status.stories file to show that Checkbox is ready.

**Comment by Zangetsu101** [comment]
Completed in #4329 & #4531
