### ISSUE TITLE
User history table for System Admins

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3972]
### Description
- adds system actions by a National or Local System Admin to the User Audit History table
- only viewable by another National or Local System Admin user

### Acceptance criteria

GIVEN I am a National or Local System Admin
WHEN I navigate to a National or Local System Admin user page
THEN I can see a History table of actions

GIVEN I am a National or Local System Admin
WHEN I click on am action
[THEN I can see additional details in a dialog](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7343%3A13555)

GIVEN I am a Registration Agent or Registrar
WHEN I navigate to a National or Local System Admin user page
THEN [I **don't** see a History table of actions. Just summary details. ](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7466%3A12695)

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7344%3A6009

### Dev tasks

- [ ] Task 1

**Comment by euanmillar** [comment]
@jpye-finch title and description is weird as it doesnt refer to registrars.  I think we are fine with the ticket #3942 we already have and suggest this is closed if you can copy anything else into #3942

**Comment by jpye-finch** [comment]
yes only other system admins should be able to see system admin actions in my view. Other users just see the system admin summary details. Not the History table

**Comment by jpye-finch** [comment]
Q. How to handle content eg. tables running over two pages?

**Comment by euanmillar** [comment]
@jpye-finch as I said above though ... " I think we are fine with the ticket #3942 we already have and suggest this ticket is closed if you can copy anything else that is missing into #3942"

**Comment by anny320** [comment]
closing this ticket, #3942 has been updated  with the additional criteria
