### ISSUE TITLE
Lets remove Cypress check from every push and only manually run them when merge to develop

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3975]
- [x] Delete e2e.yml
- [ ] Amend check-before-build.sh so that the OpenCRVS image names are read from the compose file rather than a [hardcoded array](https://github.com/opencrvs/opencrvs-core/blob/e8a27c16a2045cabfc8ce106ecf4ddfc40856e8a/check-before-build.sh#L41) which has to be maintained.  E.G.  like we do in this function in deploy.sh but ignore a hardcoded list of dependencies like Elasticsearch, Influx, Minio etc https://github.com/opencrvs/opencrvs-core/blob/e8a27c16a2045cabfc8ce106ecf4ddfc40856e8a/deploy.sh#L226

**Comment by Zangetsu101** [comment]
Should already be fixed with https://github.com/opencrvs/opencrvs-core/pull/3961

**Comment by euanmillar** [comment]
Blocked until Traefik upgrade on staging is complete

**Comment by Zangetsu101** [comment]
Completed in #4106
