### ISSUE TITLE
"No. of previous birth" data is getting deleted after an application is submitted

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3977]
**Bug description:**
"No. of previous birth" data is getting deleted after an application is submitted

**Steps to reproduce:**
1. Login as Field agent/ Registration agent
2. Declare a birth event
3. In mother's details page, fill up No. of previous birth
4. Submit the record
5. Logout
6. Login as Registrar
7. In ready for review, Download> assign that record
8. Click review
9. Observe No. of previous birth

**Actual result:**
Data for "No. of previous birth" getting deleted 

**Expected result:**
 Should be able to view No. of previous birth data

**Screen recording:**
https://images.zenhubusercontent.com/91778759/2b4c0bc9-f08a-4e8e-a030-f9482fbc66cc/no__previous_births.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en
https://login.farajaland-config.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed 

https://user-images.githubusercontent.com/94350336/191965687-2a35fdef-e8d6-48d0-b231-e7eb808c2291.mp4

**Comment by anny320** [comment]
completed
