### ISSUE TITLE
OCRVS-3852 conditional fields back end and 

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3980]
- [ ] Include a conditional array in the config database that contains an object containing the target fieldId, and regexp.
- [ ] Ensure that the conditional field "question" handlers in the config microservice and gateway mutations can submit and retrieve the question with the conditional.
- [ ] Ensure that the conditional array is returned correctly in the client in the [questionsTransformer](https://github.com/opencrvs/opencrvs-core/blob/b9fe6fdf048ada0800f770dd04fb44e859e99f34/packages/client/src/forms/questionConfig/transformers.ts#L130) function
- [ ] Ensure that the conditional array can be parsed by the client and applied to the custom field in the [createCustomField](https://github.com/opencrvs/opencrvs-core/blob/b9fe6fdf048ada0800f770dd04fb44e859e99f34/packages/client/src/forms/configuration/customUtils.ts#L33) function.

A conditional looks like this:

```
conditionals: [
                  {
                    action: 'hide',
                    expression:
                      'draftData?.deathEvent?.causeOfDeathEstablished !== "true"'
                  }
                ],
```

We need to create a reusable function probably somewhere [here](https://github.com/opencrvs/opencrvs-core/blob/b9fe6fdf048ada0800f770dd04fb44e859e99f34/packages/client/src/forms/utils.ts#L521) for all custom field conditionals which creates the expressions string using the event, the final portion of the fieldId and parses the regexp appropriately.

- [ ] Ensure that in the [Canvas > FormConfigElementCard](https://github.com/opencrvs/opencrvs-core/blob/b9fe6fdf048ada0800f770dd04fb44e859e99f34/packages/client/src/components/formConfig/Canvas.tsx#L133), if a conditional exists on the custom question, then add the icon and the fieldId to the card as we see in the Figma design

![Screenshot 2022-09-23 at 11.00.06.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/d51dfdaa-6a04-4b49-a923-0a872f2f8282)

- [ ] In CustomFieldTools.tsx, add the toggle to display the conditional parameters form.  When selected generate the select and the regexp required input.  
- [ ] In order to populate the conditionals fieldId select, we need to loop through all groups and sections in the event form and getFieldId using the sections and groups identifiers. Populate the select with options where the value and label is equal to the fieldId
- [ ] Ensure that the initial state, conditional form validation and submission saves the correct question configuration into the draft from CustomFieldTools

**Comment by jpye-finch** [comment]
@euan close?

**Comment by Zangetsu101** [comment]
Closing this as we have deprecated form config UI
