### ISSUE TITLE
Accessibility / `Workqueue`

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#3983]
Assess and review the accessibility of Workqueue component in a Frame

* Is component contrast & colors okay. Testable through Storybook "accessibility" -addon tab.
<img width="462" alt="image" src="https://user-images.githubusercontent.com/1322608/192256337-2abc85c4-aac5-4fa0-890a-801367287da8.png">

* Does the component have icons and do they have text alternatives?
* Can the component be tabbed through? Can you clearly see where the focus is? Are there focus traps?
* Can there be errors? Are errors visible and accessible by audio?

This ticket is also to learn what kind of action we need to take per each component to achieve WCAG 2.1 A-level accessibility.

**Comment by jpye-finch** [comment]
@naftis can this ticket be closed?
