### ISSUE TITLE
Newly added configurable fields cannot be made not required

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3985]
**Bug description:**
Newly added configurable fields cannot be made not required. To check which are the newly added configurable fields check the notion link- 
https://www.notion.so/opencrvs/Default-form-config-fields-0d27f0edac2f42fa956c0ece91e45984

**Steps to reproduce:**
1. Login as national system admin
2. Click Configuration> Declaration form
3. Click Configure/ Edit in Death
4. Click any Newly added configurable field eg. In informant page Click DOB
5. Disable Required for registration
6. Save> add description> Save
7. Click Edit again and Observe DOB of informant

**Actual result:**
Required for registration in informant's page- Date of birth not getting disabled

**Expected result:**
in informant's page- Date of birth should be non-mandatory field

**Screen recording:**
https://images.zenhubusercontent.com/91778759/f4f1e7f6-bdb4-4dbf-aa58-2d87256a55cf/newly_customizable_fields_cannot_be_made_not_mandatory.mp4

**Tested on:**
https://login.farajaland-config.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/195345255-db9e9d4f-5410-433a-a6dc-8712bbeaef3a.mp4

**Comment by anny320** [comment]
completed
