### ISSUE TITLE
Create and show the handlebar for a custom input in form configuration

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3989]
### Description
- dynamically creates handlebar based on english label. 
- show custom input handlebar in form config right sidebar.

### Acceptance criteria

GIVEN I create a custom input
WHEN I add a english label
THEN generate a handlebar

GIVEN I I create a new custom form field
WHEN the label is the same
THEN and a 1 to the handlebar. 

eg.
Label for all custom inputs = Custom Text Input

- customTextInput
- customTextInput1
- customTextInput2
- customTextInput3

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7296%3A7445
 

### Dev tasks

- [ ] Task 1

**Comment by euanmillar** [comment]
@jpye-finch I think we need a Figma design for this so that QA know what to test

**Comment by Zangetsu101** [comment]
We could generate the fieldId on the go as the user changes the label but whether it would be valid or not is a separate matter (i.e. The field name could be duplicate).

**Comment by euanmillar** [comment]
@jpye-finch do we need custom input values on the Nigeria certificate, this is the critical prioritisation question

**Comment by jpye-finch** [comment]
No we don't

**Comment by euanmillar** [comment]
Great, lets do this another time then

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is tested and can be closed

https://user-images.githubusercontent.com/94350336/205565783-ff5cb8e5-4598-4ae1-97c1-6e7e2dd81d42.mp4

**Comment by anny320** [comment]
completed
