### ISSUE TITLE
.CSV file validator) As a System Admin, I want to create a custom select field for my form configuration

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3990]
### Description
- adds custom select field in form configuration
- user uploads the data using a csv file. Of all options in all languages
- adds a .csv validator for checking the csv file. 
- alerts users to errors
- adds the option to choose an existing data source. eg health institutions
- shows preview in form configuration.
- provide a sample template for the configuration of the select options

This ticket will be used to support the upload of select custom fields for this ticket https://github.com/opencrvs/opencrvs-core/issues/3855
...

### Acceptance criteria

GIVEN I am a system admin
WHEN I add a custom select field
THEN show the custom select config panel

GIVEN I click the select data source
THEN show the available data sources

GIVEN I click upload a data source
THEN open the native file select

GIVEN I have chosen a .csv file
WHEN I click Open
THEN open a dialog and start uploading the .csv file

GIVEN I the .csv file has uploaded
THEN show a confirmation Alert and start validating it 

GIVEN I the .csv file has successfully been validated
THEN show a confirmation Alert and the preview bottomAction button

GIVEN I click Preview
THEN close the dialog and open the Select dropdrown... 
(is this possible

GIVEN the .csv file has errors
THEN show an error Alert and list the errors

GIVEN the .csv with the same name already exists
THEN show an error Alert 

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8230%3A34542

### Dev tasks

**ocrvs-3990-file-select-link - File select link component**
- [x] Create `FileSelectLink` -component which is a `<Link>` which allows selecting 1 file from users machine. Allow selecting only csv files.
`<FileSelectLink onFileChange={file => doSomething(file)} accept="text/csv">Upload</FileSelectLink>` - 1
- [x] Create a FileSelectLink.stories.tsx. Create a couple of examples and a description about why the component exists. For an example, see stories of Stack or Alert. Update `releases.stories.mdx` to include the new component in a corresponding version change log. - 1

**ocrvs-3390-import-csv - Prepare the backend to import CSV**
- [x] Create a new MongoDB model to config-microservice  _(* see [example FormDatasetSchema](https://github.com/opencrvs/opencrvs-core/issues/3990#user-content-form-dataset-schema))_ and amend the [`questions` -model ](https://github.com/opencrvs/opencrvs-core/blob/081db29c9397f3ac4f51900098c7245e76a7efcc/packages/config/src/models/question.ts#L86) in config to [populate](https://mongoosejs.com/docs/populate.html) it with a FormDataset - 1
- [x] Create a gateway mutation which calls a new `createFormDataset` endpoint in config. The mutation takes a file input. Create a gateway query `fetchDatasets` which calls a `getDatasetsHandler` in config. - 2
- [x] Create a CSV validation service to config microservice _(* see [an idea of the CSV format](https://github.com/opencrvs/opencrvs-core/issues/3990#user-content-csv-format))_ which parses the uploaded CSV for insert to Mongo `datasets` collection. Validate that a `option` -key exists, and validate that a `translation_LANG` exists for every language configured to the application. - 2
- [x] Create a gateway query which calls `getFormDataset` endpoint in config to fetch already uploaded csv. - 2

**ocrvs-3990-sysadmin-form-config - Prepare the frontend to import CSV**
- [x] Declaration Form -> Birth/Death Configure -> Add new field to right panel: "Custom select". Pressing it opens a side panel view, which is a new component `CustomSelectFieldTools`, similar to CustomFieldTools. Use existing form components to create the view. - 2
- [x] Form config inputs in preview are disabled by default. Add a prop to `FormConfigElementCard` be able to enable (to later show a preview of the possible options in the input) - 1
- [x] Populate the Custom Select in canvas with newly uploaded csv file options. - 1
- [ ] Call the gateway mutation when uploading a new dataset from the Upload-link. Add a new dataset to the existing datasets in the select options. Handle validation error toasts and success toasts from backend according to the design. - 3
- [ ] Handle pressing Save-button on the form configuration. The `datasetId` should be added to QuestionInput types and handled accordingly in the gateway and config. **Does a new question type need [to be added on input?](https://github.com/opencrvs/opencrvs-core/blob/bae4fefbc6ff40375c39de098a92c9bf93056d28/packages/client/src/utils/gateway.ts#L473) @Zangetsu101 ?**

**ocrvs-3990-output-datasets - Output the datasets to FormFieldGenerator**
- [ ] `SELECT_WITH_OPTIONS` -type of input in FormFieldGenerator should be amended to handle this new type of select. The backend `questions` should automatically populate the dataset in it, but the new dataset-field needs to be handled accordingly in https://github.com/opencrvs/opencrvs-core/blob/093c5f4360a40450bdca2e188503278dd566ab50/packages/client/src/forms/mappings/deserializer.ts#L333

---

<h3 id="form-dataset-schema">proposed `FormDatasetSchema`</h3>

[See `message` schema. Handle translations similarly](https://github.com/opencrvs/opencrvs-core/blob/081db29c9397f3ac4f51900098c7245e76a7efcc/packages/config/src/models/question.ts#L70)

```
const FormDatasetSchema = new Schema({
  _id: Schema.Types.ObjectId,
  options: [
      {
        type: message,
        required: true
      }
  ],
  fileName: { type: String, required: true },
  createdBy: { type: User, required: true },
  createdAt: { type: Date, default: Date.now, required: true }
})

// also amend the questions schema:
const questionSchema = new Schema({
 ...,
  dataset: { type: Schema.Types.ObjectId, ref: 'FormDataset' }
});
```

<h3 id="csv-format">proposed csv format</h3>

```csv
option,en,fr
green,Green,Vert
red,Red,Rouge
blue,Blue,Bleu
```

**Comment by naftis** [comment]
@jpye-finch @euanmillar Can we remove the CSV option lists after uploading them?

**Comment by euanmillar** [comment]
@jpye-finch @eduffus @anny320 we just realised that administrative structure & health institutions can be (and has been in the past) a huge list, hence the reason why we created a LocationSearch input type.   So perhaps these options should only be available in a future "Add Custom Location Search" component?

**Comment by jpye-finch** [comment]
hmm yeh for me this should just be the < Select /> component or variant of. For all use cases of searching for a location.  https://react-select.com/advanced#advanced

Maybe we don't show the dropdown matches until you type one of two characters ...

**Comment by euanmillar** [comment]
@jpye-finch that isnt what I meant.  Essentially all of our administrative locations are bundled together.  I assume what you want is for the user to be able to decide, do I want a custom select using only states, or districts or other admin levels that have been configured right?  You dont care what the names of the states are in this tool you just want to choose between either "States" or "Districts".  My user experience point is ... what would you call these options?  In our form we have the text copy "State" or "District" or "Location level 3" etc.  But for correct English, in this case, you would want to use a plural e.g. "States", "Districts", "Locations at level 3" etc.  We do not have plurals of these content keys.  Should we create plurals of these content keys for this purpose?

**Comment by jpye-finch** [comment]
ah ok. Yes would be useful to do so then

**Comment by naftis** [comment]
@jpye-finch

![image](https://user-images.githubusercontent.com/1322608/203018656-ecd90a75-c1a0-4de1-b725-00aa5d57d4a5.png)
 The validating and uploading would actually only be an one step as they're done at the same time in the backend. Should we just say "Validating csv file..." in the very first dialog alert?

**Comment by yeasinhossain-dsi** [comment]
@jpye-finch About the Preview button, do we really need this? What would happen if someone dosen't click preview & just clicks cross.
![Screenshot from 2022-11-21 15-53-02](https://user-images.githubusercontent.com/8198236/203020260-f04112f9-ab74-4f9c-ba67-5aefd4e66e8f.png)

**Comment by euanmillar** [comment]
@SyedaAfrida @anny320 in order to QA this, you should test a good CSV file.  This is the format we will use:

```
option,en,fr
green,Green,Vert
red,Red,Rouge
blue,Blue,Bleu
```

**Comment by euanmillar** [comment]
Then you can mess with this format to deliberately test the validation.  E.G. 

```
BANANA,en,APPLES
green,Green,Vert
red,Red,Rouge
blue,Blue,Bleu
```

**Comment by anny320** [comment]
completed
