### ISSUE TITLE
Expose a REST API to get, insert, update & archive for a FHIR Location

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3992]
The API endpoints must exist in a REST format in the Gateway routes, external to graphQL and install the plugin hapi-swagger for them.

The INSERT, UPDATE, ARCHIVE endpoints, must be restricted to a Nat Sys Admin JWT token

The GET should be auth false. 

A GET API should use FHIR search filters as they are implemented in hearth.  Essentially we are trying to expose the Hearth API just for this FHIR resource type

Currently there is no way after OpenCRVS has been initially configured, to insert or rename a Location, add a Facility or add an extra years worth of CBR and population data on an administrative Location. We must expose an API to do this.

The UPDATE API MUST NOT UPDATE IDs nor partOf values.  Research task: We should do a test to see what happens when partOf is changed in production.

Archiving should only work for health facilities and change the status prop.  Archived health facilities would not appear as places of birth or death in the birth or death form, but they would still exist in the system as places of birth and death on legacy registrations.

In the future this could lead to: Allow admin structure to be edited in a UI.

```
{
   "resourceType":"Location",
   "identifier":[
      {
         "system":"http://opencrvs.org/specs/id/statistical-code",
         "value":"ADMIN_STRUCTURE_AWn3s2RqgAN"
      },
      {
         "system":"http://opencrvs.org/specs/id/jurisdiction-type",
         "value":"STATE"
      }
   ],
   "name":"Central",
   "alias":[
      "Central" // used for other character set
   ],
   "description":"AWn3s2RqgAN", // In Bangla the statistical dept has a geocode that we use here
   "status":"active",
   "mode":"instance",
   "partOf":{
      "reference":"Location/0"
   },
   "type":{
      "coding":[
         {
            "system":"http://opencrvs.org/specs/location-type",
            "code":"ADMIN_STRUCTURE"
         }
      ]
   },
   "physicalType":{
      "coding":[
         {
            "code":"jdn",
            "display":"Jurisdiction"
         }
      ]
   },
   "extension":[
      {
         "url":"http://hl7.org/fhir/StructureDefinition/location-boundary-geojson",
         "valueAttachment":{
            "contentType":"application/geo+json",
            "data":"<base64>"
         }
      },
      {
         "url":"http://opencrvs.org/specs/id/statistics-male-populations",
         "valueString":"[{\"2007\":214275},{\"2008\":207428},{\"2009\":225250},{\"2010\":218551},{\"2011\":222568},{\"2012\":224450},{\"2013\":162537},{\"2014\":140674},{\"2015\":321276},{\"2016\":329269},{\"2017\":315012},{\"2018\":329397},{\"2019\":372808},{\"2020\":372995},{\"2021\":387162}]"
      },
      {
         "url":"http://opencrvs.org/specs/id/statistics-female-populations",
         "valueString":"[{\"2007\":200754},{\"2008\":196169},{\"2009\":212379},{\"2010\":207788},{\"2011\":210183},{\"2012\":211088},{\"2013\":155454},{\"2014\":138895},{\"2015\":321542},{\"2016\":328719},{\"2017\":311254},{\"2018\":320242},{\"2019\":308227},{\"2020\":329978},{\"2021\":299071}]"
      },
      {
         "url":"http://opencrvs.org/specs/id/statistics-total-populations",
         "valueString":"[{\"2007\":414977},{\"2008\":403572},{\"2009\":437579},{\"2010\":426327},{\"2011\":432706},{\"2012\":435471},{\"2013\":317995},{\"2014\":279569},{\"2015\":642817},{\"2016\":657989},{\"2017\":626267},{\"2018\":649640},{\"2019\":681033},{\"2020\":702973},{\"2021\":686234}]"
      },
      {
         "url":"http://opencrvs.org/specs/id/statistics-crude-birth-rates",
         "valueString":"[{\"2007\":9.925},{\"2008\":10.4875},{\"2009\":9.024999999999999},{\"2010\":8.75},{\"2011\":9.7875},{\"2012\":9.9375},{\"2013\":9.450000000000001},{\"2014\":10.100000000000001},{\"2015\":9.162500000000001},{\"2016\":8.8},{\"2017\":8.225},{\"2018\":7.875},{\"2019\":7.1625},{\"2020\":6.8375},{\"2021\":6.987499999999999}]"
      }
   ],
   "meta":{
      "lastUpdated":"2022-06-27T12:04:39.175+00:00",
      "versionId":"39d24680-f610-45bd-8d74-2becd7defea2"
   },
   "id":"7dbf10a9-23d9-4038-8b1c-9f6547ab4877"
}
```
- [x] Create a GET endpoint `/locations` in gateway which has auth false and just forward this request to the FHIR_URL inside gateway using the `fetchFhir` function. The request needs to be passed as is so that we can leverage the GET api already available to us in HEARTH
- [x] Bootstrap swagger on gateway
- [x] Create a POST endpoint restricted to national system admins to add a new location. We can follow the approach used in the function `composeFhirLocation` in farajaland. The joi validation needs to make sure we take either Location or Facility type of input from the user

Before creating the location check that the statisticalID is unique by searching FHIR for a Location with an identifier like: `ADMIN_STRUCTURE_${String(location.statisticalID)}`.  If it is not unique throw an error.

```ts
type LocationStatistic = {
  year: number
  male_population: number
  female_population: number
  population: number
  crude_birth_rate: number
}

type Location = {
  statisticalID: string
  name: string
  alias: string
  partOf: string
  code: string // CRVS_OFFICE, ADMIN_STRUCTURE, HEALTH_FACILITY
  jurisdictionType: string // STATE, DISTRICT
  physicalType: string // Jurisdiction, Building
  statistics: LocationStatistic[]
}
type Facility = {
  statisticalID: string
  name: string
  partOf: string
  code: string
  physicalType: string
  district: string
  state: string
}
```
- [x] Follow the `generateStatisticalExtensions` function on how to add the statistics to the fhir location object
- [x] And a PUT endpoint to modify the location. Check the HEARTH endpoint to see if it enables modifying the id. If it does then we need to manually restrict this in the handler.
- [x] Restrict updates to `partOf` property

**Comment by SyedaAfrida** [comment]
This ticket do not require QA testing
