### ISSUE TITLE
Export a performance report

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4001]
### Description
- adds export button to performance dashboard
- export based on current selected filters 
- dialog lets you decide on the sections to export
- creates a pdf report
- completeness rates includes table of locations 
- shows the number of pages
- has a header and footer on each page
eg. if farajaland = table of provinces. If a Province - table of districts in that province

### Acceptance criteria

GIVEN I am on the performance dashboard
WHEN I click on 'Export report'
THEN open the Export dialog

GIVEN the Export dialog is open
THEN I can see the filters I have selected (location, event, time period)

GIVEN the Export dialog is open
WHEN I click 'Export'
THEN export a PDF based on the sections i have chosen

GIVEN my location is set to an office
WHEN I click 'Export'
[THEN the section Completeness rates is not available](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7683%3A19949)

GIVEN I click 'Export'
THEN show the loading Toast

GIVEN the export is ready
THEN show the system file saver

**File name requirements**
location-event-timePeriod.pdf
eg.
farajaland_births_May2022-April2022.pdf
farajaland_deaths_June2021-June2022.pdf

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7492%3A12993

### Dev tasks
- [ ] Task 1

**Comment by euanmillar** [comment]
@jpye-finch we are ok with this to tech design with exception of the save file prompt.  We would want to open the print dialogue as we do with certs.  Users can "Save as" PDF from the print dialogue and choose a name.  A file save dialogue would be much more complex in terms of effort.

**Comment by euanmillar** [comment]
Closing as stale
