### ISSUE TITLE
Remove automatic change of documents on review page

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4004]
### Description
- Currently as you scroll down the page on the declaration review page. The documentViewer auto changes. This ticket is to remove this feature
- all supporting documents are added to the select dropdown in documentViewer
- user must manually select the document they want to see
- means a document can be compared in all sections Child, Mother, Father. 

In Nigeria. They are uploading the registration form called the B1 form. This must be compared against the data entered in openCRVS. So should be visible as you scroll down the view page. 

This change makes the review page more adaptable to other country configurations. 

### Acceptance criteria

GIVEN I am on the review page
WHEN I click on the document viewer select
THEN I ca see all supporting document uploaded

GIVEN I am on the review page
WHEN I scroll to another section
THEN I must manually change the document viewer to see the necessary document

GIVEN I am on a mobile
WHEN I am on the review page
THEN I can see all supporting documents at the bottom of the page

### Dev tasks

- [ ] Let's use a constant perhaps named `ENABLE_REVIEW_SCROLLING` when true, it will enable the scrolling section document change and disable it otherwise. And also all the attachments should show up in the Select options in that case

**Comment by euanmillar** [comment]
@jpye-finch do we need a Figma design for this?  If not, would you remove the Design section in the description?

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/199459857-0a195adc-4c8d-4c98-a55f-76387f338018.mp4


https://user-images.githubusercontent.com/94350336/199459905-d1df6f7b-08dc-4717-a2ba-b5a0a24f861b.mp4

**Comment by anny320** [comment]
completed
