### ISSUE TITLE
In side navigation, Not published message is showing even after configurations are actually published

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4019]
**Bug description:**
In side navigation, the message "Nothing is currently published. Awaiting to be published:" is showing even after configurations are actually published.

**Steps to reproduce:**
1. Login as National system admin
2. Go to Configuration> Declaration forms
3. Go to In preview
4. Click Publish in both birth and death
5. Observe the side navigation message of published

**Actual result:**
 In side navigation showing "Nothing is currently published. Awaiting to be published:""

**Expected result:**
This message should not appear since both birth and death are published

**Screenshot:**
![publish message.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/f6ee73f3-ef14-49b5-afbe-34256be8e15b)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by naftis** [comment]
https://github.com/opencrvs/opencrvs-core/blob/develop/packages/client/src/views/SysAdmin/Config/Forms/Home/FormConfigHome.tsx#L62
`events.length > 0` conditional is missing if the component is `compact`

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed 

![msg1](https://user-images.githubusercontent.com/94350336/197966206-2eab3ed0-2ebf-4590-8297-f1c8d74c955d.png)
![msg2](https://user-images.githubusercontent.com/94350336/197966200-a3183c51-eb2f-48b8-9fb6-0ac6fc720e39.png)
![msg3](https://user-images.githubusercontent.com/94350336/197966194-f97a2729-00e5-4976-a927-48aa46a0489c.png)

after publication in other users:
![after publish msg](https://user-images.githubusercontent.com/94350336/197966186-f2a9fd80-582e-4a6e-9826-e0c2d7a9797d.png)

**Comment by anny320** [comment]
completed
