### ISSUE TITLE
Improve GraphQL and TypeScript types

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#4020]
Discussion that led to this ticket: https://opencrvsworkspace.slack.com/archives/C02UN28EJ9M/p1664364491443759

When we started the project, we thought the form schema would be way more dynamic than it actually turned out to be.  We use the "IDynamicValues" in quite many places in component library to avoid having to use "any". However, in practice, those are the same thing. It could be a good thing to have a proper look to the TypeScript types in some sprint.

Most GraphQL (both input and response) are not strict enough, which makes relying on these types difficult in our frontend code and when OpenCRVS is used to integrate with. 

In this example, none of the fields can be trusted to exists, even when we know most of them are required and exist without exception:

```graphql
type User {
  id: ID
  userMgntUserID: ID
  practitionerId: String
  name: [HumanName]
  username: String
  mobile: String
  role: String
  type: String
  email: String
  status: String
  underInvestigation: Boolean
  primaryOffice: Location
  catchmentArea: [Location]
  localRegistrar: LocalRegistrar
  identifier: Identifier
  signature: Signature
  creationDate: String
  avatar: Avatar
  device: String
}
```

`role` is also a fixed set of values that we do know in advance, so an enum would be more useful.

Another example, an input value, is what we have when a birth declaration is submitted. Of course, sometimes declarations do get sent as incomplete and that's ok. Some fields like `createdAt` and `updatedAt` can still be made required. We could also consider making a completely separate queries for incomplete & completed declarations to make the contract between the client and the API more strict.

```graphql
input BirthRegistrationInput {
  _fhirIDMap: Map
  registration: RegistrationInput
  child: PersonInput
  mother: PersonInput
  father: PersonInput
  informant: RelatedPersonInput
  eventLocation: LocationInput
  birthType: BirthType
  questionnaire: [QuestionnaireQuestionInput]
  weightAtBirth: Float
  attendantAtBirth: AttendantType
  otherAttendantAtBirth: String
  birthRegistrationType: BirthRegType
  childrenBornAliveToMother: Int
  foetalDeathsToMother: Int
  lastPreviousLiveBirth: Date
  createdAt: Date
  updatedAt: Date
}
```

## Goals
- Make GraphQL types as strict as possible
  - Non-nullable value should be the default for all fields of all types. Optional is the exception. Add comments to *.graphql files explaining why certain columns are optional so we remember
- Get rid of all `any`'s and `IDynamicValues`
- Get rid of the type dependency between `@opencrvs/client` and `@opencrvs/gateway`
  - Client typing should be dictated by the types we generate from the GraphQL queries and not by what is available
- Remove custom frontend types like `IUserDetails`, `IAvatar`, `IGQLLocation`, `IIdentifier`
  - No guarantees that these types are what we get from the backend or query for
- Remove all `something as GQL*`
  -  `names = (deathReg && (deathReg.deceasedName as GQLHumanName[])) || []` should just be `names = deathReg && deathReg.deceasedName || []`
- Enable `strict: true` in TypeScript for all projects
- Find missing language items for dynamic values. Remove deprecated language items
- Remove explicit types made for language object `interface IValidationMessages extends Record<string | number | symbol, MessageDescriptor> {` as these do not improve type safety

**Comment by euanmillar** [comment]
Would help new developers and anyone wanting to integrate with the future OpenCRVS API

**Comment by Eezi** [comment]
- [ ] Make GraphQL types as strict as possible. (This is done for the User and the UserInput type)
- [ ] Get rid of all the any's.
- [ ] Get rid of all the IDynamicValues.
- [ ] Remove custom frontend types like IUserDetails, IAvatar, IGQLLocation, IIdentifier.
- [ ] Get rid of the type dependency between @opencrvs/client and @opencrvs/gateway.
- [ ] Remove all something as GQL* .
- [ ] Enable strict: true in TypeScript for all projects.
- [ ] Find missing language items for dynamic values. Remove deprecated language items.
- [ ] Remove explicit types made for language object interface IValidationMessages extends Record<string | number | symbol, MessageDescriptor> { as these do not improve type safety.
