### ISSUE TITLE
In history of record audit, location should be blank when the record is sent by health system

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4022]
**Bug description:**
In history of record audit, location should be blank when the record is sent by health system

**Steps to reproduce:**
1. Declare a birth/ death application from health system
2. Observe the record audit page of that record

**Actual result:**
Ibombo office is shown in location

**Expected result:**
Location field should be blank

**Screenshot:**
![health system.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/0692f724-18a3-4aca-ac90-82cef3717d8f)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by jpye-finch** [comment]
@anny320 we chatted about this I think in Slack.. about using the Health Institution name..?
