### ISSUE TITLE
device operational tools (e.g. flush data) available as standard

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#4026]
### Description
this is related to the fact that we are still having spinning blue wheel issues and this must not happen in Prod

...

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

(Link to Figma)

### Dev tasks

- [ ] Task 1

**Comment by jpye-finch** [comment]
@euanmillar @rikukissa ticket still required?

**Comment by rikukissa** [comment]
I don't think so – This is a nice to have but the bookmarklet everyone's using imo is enough for now
