### ISSUE TITLE
Forget pin options moves left side of the screen and when clicked forget password shows "undefined undefined" in user name

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4032]
**Bug description:**
Forget pin options moves left side of the screen and when clicked forget password shows "undefined undefined" in user name

**Steps to reproduce:**
1.  Go to lock screen
2. Click Forgotten pin
3. Observe the screen
4. Click Forgot password
5. Observe user name

**Actual result:**
1) Forget pin options moves left side of the screen 
2)  shows "undefined undefined" in user name

**Expected result:**
1)  Forget pin options should be in the center
2) should show user name correctly

**Screen recording:**
https://images.zenhubusercontent.com/91778759/21629673-f217-4bf9-a670-4b81bbfe511e/forgot_pin_issue.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by SyedaAfrida** [comment]
**Bug:**
when the language is set to french and clicked forget password, all the can't login pages are showing in English

https://user-images.githubusercontent.com/94350336/199191049-0eec69bf-01cd-4727-983a-e63bbb6c2a1a.mp4

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/205615629-19225d48-3f49-4477-a382-5f3ce41dbf62.mp4

**Comment by anny320** [comment]
completed
