### ISSUE TITLE
Allow number of and 2 character set administrative levels to be configurable.

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#4033]
If a country has only 1 administrative level (Jamaica), we would only need to show the state dropdown in the address UI

If a country has more than 2 administrative levels configured (Bangladesh / Nigeria), then subsequent selects after district in the address UI should dynamically add as Location level 3,4,5.

The jurisdiction import script in Farajaland should be changed so that you can import up to 5 csvs.  Each should map to a Location Level.  Once the full number of locations are imported, the location API should return to the metrics, elasticsearch and client the number of configured location levels so that the correct analytics and search data can be saved.

### Farajaland & Client

- [x] Deprecate the referenceAPI loadPilotLocations request and pilotLocations route in Farajaland - 1

- [x] Deprecate the locations/locationsHandler, fhir-locations,fhir-locations/{id}/locationsFhirHandler, facilities, facilitiesHandler in Farajaland and refactor the referenceAPI loadLocations and loadFacilities requests in client to use the open GET Gateway endpoint that was developed in #3992 - 2
																
### Client 

- [x] In getAddressFields window.config.ADMIN_LEVELS must be understood by getPlaceOfEventAddressFields, getPrimaryAddressFields and getSecondaryAddressFields, then every select from districtPrimary or districtSecondary onwards should dynamically generate depending on ADMIN_LEVELS prop that has been configured. - 3

When creating fields, the selects after districts should be referred to as locationLevel3, locationLevel4 and locationLevel5 and map to address line array indices: 10, 11 & 12 respectively.  The content key labels should use location.jurisdictionType.LOCATION_LEVEL_3, location.jurisdictionType.LOCATION_LEVEL_4 & location.jurisdictionType.LOCATION_LEVEL_5

In addresses.ts and Farajaland deprecate the content keys form.field.label.district, form.field.label.state and form.field.label.cityUrbanOption in favour of location.jurisdictionType.STATE, location.jurisdictionType.DISTRICT and location.jurisdictionType.CITY respectively

### Metrics

- [ ] Add locationLevel1 to all schemas and queries (in the point generator function as well) - 1

### Farajaland import script

Write a script to convert humdata csv format into the FHIR csv format.  For example: https://data.humdata.org/dataset/cod-ab-irq/resource/3f20c1af-c51d-45f9-b283-072168ec2ab2

- [x] The script starts by reading all supplied headings and forcing all headings UPPERCASE.

admin0Name_en: The script needs to understand that "admin0Name" or "admin0Name_en" is equal to the country name
admin0Name_ar: The script needs to understand that "admin0Name_<any other language code>" is equal to the country alias

- [x] The script needs to find the highest number of headings that start with "admin", then set the ADMIN_LEVELS number appropriately in the config database.  Refactor out popoulate-default-config.ts and instead run that function at the end in order to save ADMIN_LEVELS

- [x] The statisticalID is going to deprecated in favour of the

admin1Pcode
admin2Pcode

- [x] In Facilities import script, deprecate the columns physicalType, district and state, and just hardcode physicalType.

### Config 

- [x] In the config microservice model, add a new prop ADMIN_LEVELS: number (by default it should be 2) - 1

### Farajaland validate "src/scripts/validate-source-files.ts"

- [x] We also need to make sure that there are no duplicate locations or statistics.  Same applies to all files we are import.  If there are any duplicate rows, we would error. 
- [ ] You could accumulate all child statistics and add to the parent location in the import script too.  Crude birth rate: you need to an average, so you have to count the children

### Performance 

- [ ] In metrics microservice, where completeness rates are calculated, we need to check and potentially change the logic.  It should check if statistics exist for that Location first, and only do the calculation of accumulated child location stats if it doesn't exist.  

### Testing

const locationLevelName = [
    'COUNTRY',
    'STATE',
    'DISTRICT',
    'LOCATION_LEVEL_3',
    'LOCATION_LEVEL_4',
    'LOCATION_LEVEL_5'
  ]

- [ ] I created Bangladesh and Jamaica admin structures.  They import fine.  But we need to create a 5 row statistitcs, employees, facilities csvs for Bangladesh and Jamaica, run the import, and check that the address dynamically changes as it is coded to work.  Check the Team / User / Performance pages.  Check searching.  You may see something like "LOCATION_LEVEL_4, Abaipur" or concatenated in a similar way in other places.  Thats correct.

**Comment by naftis** [comment]
@euanmillar Do we want to check for duplicate names too. Made a simple helper to check for duplicates in `validate-source-files.ts` and got this in `health-facilities.csv`:
```ts
Validating health facilities file.
Line 45, column "name": Duplicate value "Chisamba Rural Health Centre"
```

Currently I'm validating:
```ts
const HealthFacilities = HealthFacility.array().superRefine(
  zodValidateDuplicates('adminPcode', 'name')
)
const CRVSFacilities = CRVSFacility.array().superRefine(
  zodValidateDuplicates('adminPcode', 'name')
)
const Employees = Employee.array().superRefine(
  zodValidateDuplicates('email', 'username')
)
const Statistics = Statistic.array().superRefine(
  zodValidateDuplicates('adminPcode', 'name')
)
```

Shortly `zodValidateDuplicates` is `zodValidateDuplicates(...columnsToCheckForDuplicates: string[])`

**Comment by euanmillar** [comment]
@naftis regarding duplicate locations, it is a bit tricky.  We must have entirely unique Pcodes by level.  So all the admin1Pcodes must be unique, then admin2 etc.  Maybe we would need to copy over logic used in import-locations.ts to parse and understand the locations by level

**Comment by naftis** [comment]
> @naftis regarding duplicate locations, it is a bit tricky. We must have entirely unique Pcodes by level. So all the admin1Pcodes must be unique, then admin2 etc. Maybe we would need to copy over logic used in import-locations.ts to parse and understand the locations by level

so if we had

```
admin2Pcode,admin1Pcode,admin0Pcode
x,a,1
y,a,2
z,b,2
```

that would pass, but if admin1Pcode would have 1/2 or x/y/z it would fail for example. So:

* any of the `admin\dPcode`s cannot appear in any other `admin\dPcode` fields
* the most granular one shouldn't have any duplicates in its column

**Comment by euanmillar** [comment]
@naftis yes that's exactly it
