### ISSUE TITLE
UI issue: In audit all the table data should be left aligned 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4034]
**Bug description:**
UI issue: In audit all the table data should be left aligned 

**Steps to reproduce:**
1. Login to FA/ RA/ Registrar
2. Click any record
3. Click any actions: Rejected/ Updated/ Correct record
4. Observe the table

**Actual result:**
all the table data became right aligned

**Expected result:**
all the table data should be left aligned

**Screenshot:**
![imp1.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/9f7402f8-aa03-4d18-8f04-fc43a6d64c7a)
![imp2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/4e439eae-b5c6-44a2-bc70-062293b74d80)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by rabiulislamanik** [comment]
@Zangetsu101 I verified that , this PR of mine https://github.com/opencrvs/opencrvs-core/pull/4009 fixed this ticket.

**Comment by SyedaAfrida** [comment]
@anny320 this issue is fixed and can be closed
![1](https://user-images.githubusercontent.com/94350336/194307500-ead3ee9b-80dd-42d2-881a-6086466cc11a.png)
![2](https://user-images.githubusercontent.com/94350336/194307520-0e2bdfbf-e6cf-4481-9005-5d94b88e57a5.png)

**Comment by anny320** [comment]
completed
