### ISSUE TITLE
Hide PII from user audit for all users

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4037]
### Description
- removes username, phone number and national ID from user audit

### Acceptance criteria

GIVEN I am on a user audit page
THEN I can see summary details for Assigned office, Role type and Device

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7746%3A21617

### Dev tasks

- [ ] Task 1

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is passed and can be closed-
![anne](https://user-images.githubusercontent.com/94350336/200830022-3692c10f-8157-4e92-8c2e-9666bfac0f7b.png)

**Comment by anny320** [comment]
completed
