### ISSUE TITLE
As a Local or National System Admin, I want to send a username reminder to user

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4038]
### Description
- system admin can trigger an SMS with the user username

### Acceptance criteria

GIVEN I am system admin
WHEN a user's status is active or pending
THEN I can select the option 'Send username reminder'

GIVEN I have select the option 'Send username reminder'
WHEN I confirm in the dialog
THEN send an SMS with the user's username to their phone number

SMS copy:
Your username for {{applicationName}} is: {{username}}

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7891%3A22217

### Dev tasks

- [x] For sysadmins, add an option 'Send username reminder' in the 3 dots menu in teams page which when clicked opens up a modal according to the design and clicking the send button would call a mutation 'usernameSMSReminder' which will take the userId as input and will return the username on success. - 2
- [x] In gateway, create a mutation called 'usernameSMSReminder' which takes a `userId` as input. Check the user scope to make sure that only sysadmins can call this mutation. It will `/usernameSMSReminder` route which we will create a handler for in the next task. - 1
- [x] In user-mgnt create a route `/usernameSMSReminder` which has a payload of the userId. Find the username using the userId. And call the `/retrieveUserNameSMS` which we already have in Notification service. - 1

**Comment by SyedaAfrida** [comment]
**Bug:**
1. Username reminder option not showing in user audit page 

https://user-images.githubusercontent.com/94350336/201840476-e76cfabb-b410-4597-aef3-201e848e1b47.mp4

2. Typo
![unr](https://user-images.githubusercontent.com/94350336/201840575-4cd1ce7b-50fc-4df8-b773-83b4fc4e3bf5.png)

**Comment by SyedaAfrida** [comment]
This ticket will be tested after SMS is enabled in QA/ config environment

**Comment by anny320** [comment]
completed
