### ISSUE TITLE
As a Local/National System admin, I want to reset a user's password

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4039]
### Description
- system admin can reset a user password
- send temporary password to user's phone
- on successful login attempt. User is prompted to create a new password and security questions

### Acceptance criteria

GIVEN I am system admin
WHEN a user's status is active or pending
THEN I can select the option 'Send username reminder'

GIVEN I have select the option 'Send username reminder'
WHEN I confirm in the dialog
THEN send an SMS with the user's username to their phone number

SMS copy:
Your password has been reset. Please login to {{applicationName}} with the temporary password: {{password}}. 

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7891%3A22217

### Dev tasks

- [x] For sysadmins, add an option 'Reset Password' in the 3 dots menu in teams page which when clicked opens up a modal according to the design and clicking the send button would call a mutation 'resetPasswordSMS' which will take the userId as input and will return the username on success. - 2
- [x] In gateway, create a mutation called 'resetPasswordSMS' which takes a `userId` as input. Check the user scope to make sure that only sysadmins can call this mutation. It will call `/resetPasswordSMS` route in user-mgnt which we will create a handler for in the next task. - 1
- [x] In user-mgnt create a route `/resetPasswordSMS` which has a payload of the `userId`. Create a handler that generates a temporary password similar to `resendSMSInvite` and calls another function `sendPasswordNotification` which will be similar to `sendCredentialsNotification`. (Make sure to change the user status to `PENDING`) - 1
- [x] Create a new route called /resetPasswordSMS in notification service and a handler similar to `sendUserCredentials` which gets the translation from farajaland and sends the SMS. - 2
- [x] Add the new notification transaltion in farajaland

**Comment by SyedaAfrida** [comment]
**Bug:**
1. Reset password option not showing in user audit page and active user should not have resend sms invite option in user audit

https://user-images.githubusercontent.com/94350336/201841274-53156080-80d3-4921-ad9c-585845a57e98.mp4

2. Typo
![rp](https://user-images.githubusercontent.com/94350336/201841440-e0fcda70-9369-4c31-b373-cc0785bd798b.png)

**Comment by SyedaAfrida** [comment]
**Bug:**
When a password is reset, then sms is not send to user with temporary password

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![Screenshot_20230105-183122_Messages](https://user-images.githubusercontent.com/94350336/210781242-63eee2fd-35b3-444e-bcf7-61391693ddea.jpg)
![1233321](https://user-images.githubusercontent.com/94350336/210781248-f6520168-cfe7-4813-8497-d512efc5905f.png)

**Comment by anny320** [comment]
completed
