### ISSUE TITLE
As a user whose password had been reset, I want to create a new password and security questions

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4040]
### Description
- when a user's password has been reset by a system admin
- they are prompted to create a new password and security questions

### Acceptance criteria

GIVEN I have had my password reset
WHEN I log in with my temporary password
THEN show the create new password screen

GIVEN I created a new password
THEN show set security question screen

GIVEN I set my security questions
THEN show the review page

GIVEN I set I confirm my details
THEN show loading state

GIVEN my details have been updated
THEN show confirmation page

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7916%3A24686

### Dev tasks

- [ ] Task 1

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/201843913-4ce572d0-b506-4f7e-9b86-920b37bfc0e4.mp4

**Comment by anny320** [comment]
completed
