### ISSUE TITLE
Update onboarding SMS messages

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4041]
### Description
- current SMS for onboarding includes messaging about updating username. but this is not possible. 

### Current

userCredentialsNotification: 

**English**
You can login to OpenCRVS with this temporary username: {{username}} and password: {{password}}         

**French**
Vous pouvez vous connecter à OpenCRVS avec ce nom d'utilisateur temporaire : {{username}} et ce mot de passe : {{password}}.

### Proposed

userCredentialsNotification: 

**English**
Your OpenCRVS account has been created.  Please login with your username: {{username}} and temporary password: {{password}}"         

**French**
Votre compte OpenCRVS a été créé. Veuillez vous connecter avec votre nom d'utilisateur : {{username}} et votre mot de passe temporaire : {{password}}.

### Acceptance criteria

GIVEN the System Admin is creating a new user
WHEN they click Create
THEN send an SMS notification to the new user phone number

### Design
https://www.notion.so/opencrvs/System-notifications-407adf6dd1654b8b81240520ce7ad7e8

### Dev tasks

- [x] Task 1

**Comment by jpye-finch** [comment]
@anny320 we should review and document current SMS messaging in Notion

**Comment by Zangetsu101** [comment]
Completed in https://github.com/opencrvs/opencrvs-farajaland/pull/400
