### ISSUE TITLE
Capture the paper secuirty number when printing a certificate

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#4044]
### Description
during the certificate printing process, capture the certificate number (on the paper) and add it to the record.
- enables capture of additional details in a text field to support audit when printing certificates
...

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

(Link to Figma)

### Dev tasks

- [ ] Task 1

**Comment by euanmillar** [comment]
Closing as stale
