### ISSUE TITLE
In correction summary page, hide "ID check" table when correction is requested by " Another registration agent or field agent"/ "Me"

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4048]
**Bug description:**
In correction summary page, hide "ID check" table when correction is requested by " Another registration agent or field agent"/ "Me" since "Check proof of ID" page is skipped when  correction is requested by " Another registration agent or field agent"/ "Me".

**Steps to reproduce:**
1. Login as Local/ National registrar
2. Go to ready to print
3. Click Download> assign to any record
4. Click on that record
5. Click Correction record
6. Select " Another registration agent or field agent"/ "Me"
7. Observe ID check table in correction summary page

**Actual Result:**
In ID check table, shows ID verified

**Expected result:**
In correction summary page should not show "ID check table since "Check proof of ID" page is skipped 

**Screenshot:**
![image (5).png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/c69af865-579f-4cc8-b4fd-4e28260646df)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![cor 4](https://user-images.githubusercontent.com/94350336/198955912-412976b0-10f0-4e9f-96fd-9c8ef8badfef.png)
![cor3](https://user-images.githubusercontent.com/94350336/198955921-2175cf11-8ae4-445a-bbe3-1aa5b6535c81.png)
![cor 2](https://user-images.githubusercontent.com/94350336/198955926-22229052-88f2-4430-9e4b-4318075ff661.png)
![cor 1](https://user-images.githubusercontent.com/94350336/198955928-7bf7d920-30f7-426c-8999-328693b70b01.png)

**Comment by anny320** [comment]
completed
