### ISSUE TITLE
Supporting document do not appear in correct record after the record is corrected once

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4073]
**Bug description:**
Supporting document do not appear in correct record after the record is corrected once

**Steps to reproduce:**
1. Login as Registrar
2. Register any record with supporting document
3. Go to ready to print
4. Click Download > Assign to that record
5. Click Correct record
6. Make any change > Do correct record
7. again click Correct record
8. Go to review page and observe

**Actual Result:**
In correct record review page no supporting document is showing

**Expected result:**
Should show supporting document 

**Screen recording :**
https://images.zenhubusercontent.com/91778759/fcc01091-ea0f-4630-93a6-a78a75535970/do_not_show_supporting_documents_after_a_record_is_corrected_once.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/199486342-d587814f-c6a8-4f47-a188-bec30a9c4109.mp4

**Comment by anny320** [comment]
completed

**Comment by euanmillar** [comment]
@sadmananik this migration takes a long time to run in production.  Please can you output progress logs as you did in 20221110092434-add_identifiers_DOB_gender_location.js as there is no indication that the migration is running.

**Comment by sadmananik** [comment]
@euanmillar I have added paginations and logs for this migration.
