### ISSUE TITLE
Migrate legacy documents to minio

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#4087]
We need to write a migration that will migrate all the legacy documents to minio storage

- [ ] Create a migration in the migrations package using the command `yarn create:hearth migrate-documents-to-minio`. Connect to minio client, add all the necessary environment variables, go through every document in `DocumentReference` collection in hearth, upload the base64 image that we have in `content[0].attachment.data` to minio and store the url returned in there instead of the base64 image. Log the progress appropriately.

**Comment by euanmillar** [comment]
We need to add the following in docker-compose.deploy.yml for the migration: block ```
depends_on:
  - minio
```

**Comment by Zangetsu101** [comment]
Unfortunately `depends_on` does not work on docker swarm instead we need to use `WAIT_HOSTS` as we are using the `docker-compose-wait` script
