### ISSUE TITLE
In certificate config, file name is showing "undefined" when printed in mobile

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4092]
**Bug description:**
In certificate config, file name is showing "undefined" when printed in mobile

**Steps to reproduce:**
1. Login to national system admin from mobile
2. Click Configuration> Certificates
3. Click 3 dot menu
4. Click Print and observe the file name

**Actual result:**
In mobile file name is showing undefined

**Expected result:**
the file name should be same as in web view

**Screen recording:**
https://images.zenhubusercontent.com/91778759/f51476a5-59d8-4bcf-873d-94a7d5179565/certificate_config_file_names_is_showing_undefined_when_downloaded_in_mobile.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by jpye-finch** [comment]
@SyedaAfrida is this ticket still required?

**Comment by euanmillar** [comment]
Closing as no UI exists anymore
