### ISSUE TITLE
Capture informant agreement to submit declaration with signature

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#4099]
https://www.notion.so/opencrvs/7d321101427640088c305b8bf630aa21?v=cd71becb0d0e4c14a13e67ba38fba1ac&p=97128adb4d3d4312863d1af4b7949344&pm=s

### **Problem statement**
Currently in many countries; the signature of the informant is mandated by law on the paper declaration form. Confirming that the details in the declaration form are true and correct to the best of their knowledge. With a digital form the option for a handwritten signature is not possible, so an alternative is required for the informant to confirm the declaration. 

### **Proposed work**
- Informant is asked add a digital signature on the review page
- Using a mouse or trackpad on a desktop computer
- Using their finger on a mobile screen 
- Option to toggle this feature ON/OFF in the configuration settings

https://www.figma.com/file/63OIwbkg9g1CSzwgyjVxQ3/Informant-signature?node-id=0%3A1&t=CR8kIE4M3Xwcd8ub-1

### **Success criteria**
- informant is willing to provide a digital signature
- informant can easily sign the device with their finger
- informants can easily sign the device with a mouse or trackpad

### **User stories**
- As an informant I want to confirm the details in the declaration form using a signature
- As an informant I want to confirm the details in the declaration form using a signature on a mobile device

**Comment by euanmillar** [comment]
@anny320 should this be moved to the Community column?

**Comment by anny320** [comment]
@jpye-finch  to indicate areas that should be ignored on the designs for this ticket to proceed to be actioned.

**Comment by cinojopencrvs** [comment]
@Zangetsu101 @anny320 please update the status

**Comment by anny320** [comment]
completed
