### ISSUE TITLE
As a Reg Agent, Registrar or National Registrar I would like to start an Advanced search

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4105]
### Description
- adds Advanced search to Search type dropdown 
- updates Search type dropdown to Tracking ID, Registration No, National ID and Phone no. 

### Acceptance criteria

GIVEN I am a Reg Agent, Registrar or National Registrar 
WHEN I click on the Search type select
THEN I can see a menu of options (Tracking ID, Registration No, National ID and Phone no, Advanced search)

GIVEN I am a Reg Agent, Registrar or National Registrar 
WHEN I click either Tracking ID, Registration No, National ID and Phone no
THEN the search updates to my selection

GIVEN I search by Tracking ID
THEN the [search results reflect my selection](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7109%3A2293)

GIVEN I search by Registration no.
THEN the [search results reflect my selection](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7841%3A29634)

GIVEN I search by National ID
THEN the [search results reflect my selection](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7841%3A30124)

GIVEN I search by  Phone no.
THEN the [search results reflect my selection](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7841%3A29858)

GIVEN I am a Reg Agent, Registrar or National Registrar 
WHEN I click Advanced search
THEN then navigate to the [Advanced search page](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8052%3A25819)

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7109%3A2293

#### Front End:

- [x] In Client > Header.tsx add National ID as an option in search types, and add Advanced Search as a customised search type.  In SearchTool in the component library, handle the Advanced Search customised search type in the DropDownWrapper,  Create the NationalID icon in the component library using react-feather "credit-card". Ensure button focus states and keyboard nav worked as before - 2
- [x] In Navigation goToSearchResult function, if the user is performing an Advanced Search from Header.tsx, then redirect the user to a new route to load the AdvancedSearch.tsx view. In SearchResult.tsx and client > search > queries add nationalId as a search parameter. Tidy some tech debt ... Delete unused queries.ts file next to SearchResult.tsx and all other references to the deprecated FETCH_REGISTRATION_BY_COMPOSITION and  fetchRegistrationByComposition query (requiresUpdate.test.tsx / OfficeHome). -2

#### Back End - Search by NationalID:

- [x] In gateway add nationalId as a parameter to searchEvents resolver, add to the searchCriteria that is posted to the search service. - 1
- [x] The search microservice is not robustly storing the National ID in motherIdentifier or fatherIdentifier.  NationalID may not be item [0] in the array. It should be refactored to select the National ID from the identifier array.  There may be more identifiers in here in future. Refactor:

a) [here](https://github.com/opencrvs/opencrvs-core/blob/968d7e38efee6de5c7fac3621d3369fabcd6cd87/packages/search/src/features/registration/birth/service.ts#L245)

&

b) [here](https://github.com/opencrvs/opencrvs-core/blob/968d7e38efee6de5c7fac3621d3369fabcd6cd87/packages/search/src/features/registration/birth/service.ts#L276) - 1

- [x] Breaking change: The search microservice is not tracking informant identifiers for birth nor death, nor deceased's identifiers for death.  

a) In registration > birth > service createInformantIndex method the body.informantIdentifier must be added following a similar process for the above motherIdentifier

&

b) In registration > death > service createDeceasedIndex method the body.deceasedIdentifier must be added following a similar process for the above motherIdentifier

&

c) In registration > death > service createInformantIndex method the body.informantIdentifier must be added following a similar process for the above motherIdentifier - 1

- [x] In the search microservice searchDeclaration handler / searchComposition service allow nationalId as a search parameter passing to the queryBuilder function.  The motherIdentifier, fatherIdentifier match in advancedQueryBuilder must be duplicated in queryBuilder where params.nationalId exists. Similar match logic for informantIdentifier and deceasedIdentifier must be added. - 1

**Comment by SyedaAfrida** [comment]
**Bug:**
1. When searched with NID show all records. When searched with NID should show specific  record like that of tracking ID.
![1](https://user-images.githubusercontent.com/94350336/206447733-5b65883b-85bc-4542-8093-e45366833a27.png)

2. Field agent should not have advance search option
https://user-images.githubusercontent.com/94350336/206447989-eaac1818-c058-4cbb-ba97-20baf2c68781.mp4

3. System crash occurs when clicked advanced search from Registration Agent  & national Registrar
![System crash occurs when clicked advanced search from RA   national Registrar](https://user-images.githubusercontent.com/94350336/206448166-738bde1e-d78e-4959-bdf1-e2001a4ff2df.png)

**Comment by SyedaAfrida** [comment]
@anny320 bug(5) needs tech design. So created a new ticket for that #4487 . Other than this, all the bugs are fixed and can be closed.

https://user-images.githubusercontent.com/94350336/208668420-0af7bd9a-ce7c-4f3e-af1e-02948d295e95.mp4

**Comment by anny320** [comment]
completed
