### ISSUE TITLE
As a Reg Agent, Registrar or National Registrar I would to enter search parameters for a birth record

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4112]
### Description

- adds birth tab. 
- adds new [Accordion component](https://www.figma.com/file/SsqCzO2eherXXCKyixmli9/OpenCRVS-Design-System-v2-WIP?node-id=1073%3A12421)
- Date range ticket:
- Address entry in model ticket:

Registration details
- Place of registration (location search)
- Date of registration (Date input)
- Exact date unknown (Date range select)
- Status of record (Select)

Child's details
- Date of birth (Date input)
- Exact date unknown (Date range select)
- First name(s)
- Last name
- Sex
- Place of birth (address model input)

Mother's details
- Date of birth (Date input)
- Exact date unknown (Date range select)
- First name(s)
- Last name

Father's details
- Date of birth (Date input)
- Exact date unknown (Date range select)
- First name(s)
- Last name

Informant's details
- Date of birth (Date input)
- Exact date unknown (Date range select)
- First name(s)
- Last name

### Acceptance criteria

GIVEN I am on the Advanced search page 
WHEN I enter at least two search parameters
THEN the Search button becomes enabled

GIVEN I click on an Accordion section 
THEN expand that section

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8122%3A27115

### Dev tasks

Front End

Accordion component work is in ticket:

Date Range Picker component work is in ticket:

- [x] In client > src > forms mark up the advanced search form JSON using the ACCORDION_WITH_NESTED_FIELDS type and all other fields.  - 2

"Place of registration" is a LOCATION_SEARCH_INPUT with dynamicOptions resource being CRVS_OFFICES & ADMIN_STRUCTURE.  Note that the sub label is the InputField prop "helperText".  This needs content such as "Search for a province, district or registration office"

Configure a conditional where if the date range is not null in any of the groups, the Date field is made disabled.

For the Status of record select, the values are:

"Any status":  ALL
"In progress": IN_PROGRESS
"In review": IN_REVIEW (In the backend we need to parse this to search for both WAITING_VALIDATION and VALIDATED statuses)
"Requires updates": REJECTED
"Registered": REGISTERED
"Certified": CERTIFIED
"Archived": ARCHIVED

When selected and sent to GraphQL the value should be an Array of strings

Ignore the Place Of Birth fields / Place Of Death fields as this will be refactored in #4095

- [x] While none of the fields are required, code a custom validation. At least 2 field values must be set AND the user must be online, before the search button is enabled. - 2

Note that all Formik form values will eventually map to these query values:

```
{
  event?: string
  registrationStatuses?: string[] // An array because the "In review" option refers to 2 statuses or ALL statuses
  dateOfEvent?: string // used to be deathDate
  dateOfEventStart?: string
  dateOfEventEnd?: string
  registrationNumber?: string
  trackingId?: string
  dateOfRegistration?: string
  dateOfRegistrationStart?: string
  dateOfRegistrationEnd?: string
  declarationLocationId?: string // used if the Place of registration selected is an office
  declarationJurisdictionId?: string // used if the Place of registration selected is a district or state
  eventLocationId?: string // used for place of birth / death if it is a facility
  eventLocationLevel1?: string // used for state of place of birth / death if it is an address
  eventLocationLevel2?: string // used for district of place of birth / death if it is an address
  eventLocationLevel3?: string // used for location level 3 of place of birth / death if it is an address
  eventLocationLevel4?: string // used for location level 4 of place of birth / death if it is an address
  eventLocationLevel5?: string // used for location level 5 of place of birth / death if it is an address
  childFirstNames?: string
  childLastName?: string
  childDoB?: string
  childDoBStart?: string
  childDoBEnd?: string
  childGender?: string
  deceasedFirstNames?: string
  deceasedFamilyName?: string
  deceasedGender?: string
  deceasedDoB?: string
  deceasedDoBStart?: string
  deceasedDoBEnd?: string
  motherFirstNames?: string
  motherFamilyName?: string
  motherDoB?: string
  motherDoBStart?: string
  motherDoBEnd?: string
  fatherFirstNames?: string
  fatherFamilyName?: string
  fatherDoB?: string
  fatherDoBStart?: string
  fatherDoBEnd?: string
  informantFirstNames?: string
  informantFamilyName?: string
  informantDoB?: string
  informantDoBStart?: string
  informantDoBEnd?: string
}
```

**Comment by SyedaAfrida** [comment]
**Bug:**
1. Cannot find result when searched with District/ province in place of registration,  Date of registration & Child last name

https://user-images.githubusercontent.com/94350336/206449265-b6c633da-8089-4cbe-9ff0-600105c99feb.mp4


2. Should have Validated drop down in status of record, When clicked in review should show records of in review. When clicked Validated should show records of Validated.
![validated](https://user-images.githubusercontent.com/94350336/206449736-c4e219dd-5d5c-4d4f-a9b7-cb9a0b4bc7d4.png)

3. Cannot find result when in event details country is farajaland but Province is anything other than Central 

https://user-images.githubusercontent.com/94350336/206450387-b32d5207-de75-4591-9b52-39d280833141.mp4


4. When searched with any DOB shows error- "An error occurred while searching" as DOB cannot input 1 digit in date/month. Like 2022-1-1 
![mom DOB](https://user-images.githubusercontent.com/94350336/206450498-3d6dbe06-a263-4650-99ae-da844c4260d9.png)

5. Shows wrong records when searched with father's DOB 

https://user-images.githubusercontent.com/94350336/206450988-bf6112ea-d8d3-48d3-9638-44c0474a7d3e.mp4

**Comment by asifjoardar** [comment]
**Bug:**

1. Can't find exact search results from advanced search.
[advanced-search-birth.webm](https://user-images.githubusercontent.com/35629053/209326124-5a7606be-41d6-447b-b977-d6cc9ca85b76.webm)

**Comment by Zangetsu101** [comment]
Let's keep the fuzziness of the name search

**Comment by asifjoardar** [comment]
@anny320 this ticket is fixed and can be closed.


https://user-images.githubusercontent.com/35629053/212814804-f9ad6181-1b92-4d4d-84f9-7ec931663094.mp4


https://user-images.githubusercontent.com/35629053/212814884-e9199ce8-f3a9-4e4e-b9fa-153c75bb693c.mp4


https://user-images.githubusercontent.com/35629053/212814902-c346823a-b4e9-480e-b46b-1701bc0459ea.mp4


https://user-images.githubusercontent.com/35629053/212815011-4b899d7a-141d-4a6b-b23c-a2c7cbfd629f.mp4


https://user-images.githubusercontent.com/35629053/212815063-6fcdc7f1-eb8a-40a4-96de-e6bcc579ca69.mp4

**Comment by anny320** [comment]
Completed
