### ISSUE TITLE
As a Reg Agent, Registrar or National Registrar I would to enter search parameters for a death record

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4113]
### Description

- adds death tab. 
- adds parameter to perform an advanced search

Registration details
- Place of registration (location search)
- Date of registration (Date input)
- Exact date unknown (Date range select)
- Status of record (Select)

Deceased details
- Date of birth (Date input)
- Exact date unknown (Date range select)
- First name(s)
- Last name
- Sex

Event details
- Date of death
- Exact date unknown (Date range select)
- Place of death (Date input)

Informant's details
- Date of birth (Date input)
- Exact date unknown (Date range select)
- First name(s)
- Last name

### Acceptance criteria

GIVEN I am on the Advanced search page 
WHEN I click the death tab
THEN the search criteria updates to Death

GIVEN I click on an Accordion section 
THEN expand that section

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8122%3A26601

### Dev tasks

- [x] Mark up the death form JSON as we did for birth (refer to specific requirements in the description above)

**Comment by SyedaAfrida** [comment]
**Bug:**
1. Cannot find result when searched with District/ province,  Date of registration ,Deceased DOB , Deceased last name, place of death (residencial area)

https://user-images.githubusercontent.com/94350336/206451448-9480a98a-b76d-40d5-8398-f5209434868a.mp4



2. Should have Validated drop down in status of record, When clicked in review should show records of in review. When clicked Validated should show records of Validated.
![validated](https://user-images.githubusercontent.com/94350336/206451576-5a687aa5-7f72-4810-840e-bbf608e685d0.png)


3. Cannot find result when searched with Exact DOB unknown for informant

https://user-images.githubusercontent.com/94350336/206451664-8949c1ac-0190-4063-994d-b4941ce298a4.mp4

**Comment by alamin-7** [comment]
**Bug:**

1.  Can't find any result when search with Health Institution.
2.  But get result when the death place "Deceased's usual place of residence" selected and search with that.
[screen record for advance search with the parameter of Health Institution bug.webm](https://user-images.githubusercontent.com/38520477/209326160-f3ee7d56-d605-4071-b27a-72e18cf6336b.webm)

**Comment by Zangetsu101** [comment]
The name search is working as expected as we have fuzziness enabled.

**Comment by alamin-7** [comment]
@anny320 this ticket is fixed and can be closed

**Screen of test:**

[search-health-institution.webm](https://user-images.githubusercontent.com/38520477/209914740-37038226-4e94-4af0-9148-88e509d4f102.webm)

**Comment by alamin-7** [comment]
**Test of issue no 1:**
 **Result when searched with District/ province**
 1. Date of registration 
 2. Deceased DOB 
 3. place of death (residential area)

**Screen record:**

https://user-images.githubusercontent.com/38520477/212815889-18710d94-680f-456b-8a34-0549e38f53d3.mp4

**Test of issue no 2:**
**Search with review status**

**Screen record:**
https://user-images.githubusercontent.com/38520477/212816256-58f102cc-e986-4db6-b453-698e780ed615.mp4

**Test of issue no 3:**
**Search with "unknown DOB of Informant"**

**Screen record:**

https://user-images.githubusercontent.com/38520477/212816568-5be414b6-966b-4738-967b-d3d170963de3.mp4

**Test of issue no 4:**
**"First name" and "Last name" label in deceased's details.**

**Screenshot:**
![name_label](https://user-images.githubusercontent.com/38520477/212816840-4db65e33-4ddd-4ace-9346-a015fe64d28d.png)

**Comment by anny320** [comment]
Completed
