### ISSUE TITLE
As a Reg Agent, Registrar or National Registrar I would like to see the results of my advanced search

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4114]
### Description

- search loading state
- adds summary of search query using <Pill />
- adds Edit button to navigate back to Advanced search
- shows results in existing format

### Acceptance criteria

GIVEN I am on the Advanced search page 
WHEN I enter at least two search parameters
THEN the Search button becomes enabled

GIVEN I am on the search results page
THEN show the loading state

GIVEN I am on the search results page
WHEN results have been found
THEN display the results

GIVEN I am on the search results page
WHEN no results have been found
THEN show the no results state

GIVEN I am on the search results page
THEN show a summary of my search query

GIVEN I am on the search results page
WHEN I click Edit in the search query summary 
THEN navigate back to the Advanced search. 

GIVEN I click Edit 
WHEN I navigate back to Advanced search
THEN I can see my previous advanced search query

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8122%3A27115

### Client

When the user has selected a minimum of 2 properties and the search button is enabled, the user can redirect to SearchResults with the advanced search parameters.  We will need a reducer to temporarily store the currently active advanced search parameters as there are so many it does not make sense to put in the URL as params.

- [x] Create a reducer and selector in client > src > search to store and retrieve the active advanced search parameters - the values from the Formik form.  We will need some optional additional values "searchId", "saved", "error" and "name", which are only used later in some edge cases.  Register the reducer in store. - 2
- [x] Connect the location input fields with resources to show suggestions - 2
- [x] Create transformers to transform the formValues to the search parameters listed below - 1
- [x] When the Search button is clicked in Advanced Search ... - 3

a) dispatch an action to save the form values in the reducer, then redirect the user to the Search Results page.  

b) You will need to set a constant in searchText and searchType which will configure the Search Result page to behave differently. 

c) In SearchResults, if the searchText and searchType are set to an Advanced Search in URL params, then the advanced search parameters received in mapStateToProps should be used to pass to SEARCH_EVENTS which will be like searchEvents with the payload, and sort properties.  locationIds will be deprecated.  The payload will be interpreted as IAdvancedSearchParams in the gateway so ensure that the form values map correctly:

```
{
  event?: string
  dateOfEvent?: string // used to be deathDate
  dateOfEventStart?: string
  dateOfEventEnd?: string
  registrationNumber?: string
  trackingId?: string
  dateOfRegistration?: string
  dateOfRegistrationStart?: string
  dateOfRegistrationEnd?: string
  declarationLocationId?: string // used if the Place of registration selected is an office
  declarationJurisdictionId?: string // used if the Place of registration selected is a district or state
  eventCountry?: string
  eventLocationId?: string // used for place of birth / death if it is a facility
  eventLocationLevel1?: string // used for state of place of birth / death if it is an address
  eventLocationLevel2?: string // used for district of place of birth / death if it is an address
  eventLocationLevel3?: string // used for location level 3 of place of birth / death if it is an address
  eventLocationLevel4?: string // used for location level 4 of place of birth / death if it is an address
  eventLocationLevel5?: string // used for location level 5 of place of birth / death if it is an address
  childFirstNames?: string
  childLastName?: string
  childDoB?: string
  childDoBStart?: string
  childDoBEnd?: string
  childGender?: string
  deceasedFirstNames?: string
  deceasedFamilyName?: string
  deceasedGender?: string
  deceasedDoB?: string
  deceasedDoBStart?: string
  deceasedDoBEnd?: string
  motherFirstNames?: string
  motherFamilyName?: string
  motherDoB?: string
  motherDoBStart?: string
  motherDoBEnd?: string
  fatherFirstNames?: string
  fatherFamilyName?: string
  fatherDoB?: string
  fatherDoBStart?: string
  fatherDoBEnd?: string
  informantFirstNames?: string
  informantFamilyName?: string
  informantDoB?: string
  informantDoBStart?: string
  informantDoBEnd?: string
}
```

d) We are no longer going to restrict Registration Agents from submitting searches for areas outside their offices.  So, remove the locationIds variable from the SEARCH_EVENTS query. The query will pass declarationLocationId (If Place of registration select is an office) or declarationJurisdictionId (If place of registration is a district or state ADMIN_STRUCTURE) to cater directly for the back end requirements of the search service for place of registration.

- [x] HANDLE PAGE REFRESH ... If searchText and searchType are set to an Advanced Search and the page is refreshed, thus clearing out the reducer, redirect the user to the HOME - 1
- [x] The loading, empty state and search results will be handled the same as other simple searches, but for an advanced search create individual Pill components with each parameter as per the design.  Display an edit link.  Clicking edit will return the user to the AdvancedSearch.tsx page.  
- [x] In AdvancedSearch.tsx, use mapStateToProps to get any search parameters currently in the reducer and set initialValues in the Formik form. - 2
- [x] In SearchTool, whenever the user initiates any new AdvancedSearch, ensure that any existing advanced search in the reducer is deleted so that the form is cleared in that case. - 1
- [x] Add pagination in the search results - 1

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/206452323-2e76c501-7de0-4824-a174-a83f71a1e686.mp4

**Comment by anny320** [comment]
completed
