### ISSUE TITLE
As a Registration Agent, Registrar and National Registrar, I want to favourite my search result query

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4117]
### Description
- adds favourite button (<Icon medium /> to the search results page
- onClick a dialog shows prompting them to name their query
- adds a menu option to the sideNav
- onClick of the menu option show the search results for the query
- unchecking the favourite icon deletes the menu option

### Acceptance criteria

GIVEN I am on the search results
WHEN I click the star button 
THEN [open the save dialog](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7822%3A21080)

GIVEN the save dialog is open
WHEN I enter a name for the search query
THEN [enable the confirm button](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7841%3A27974)

GIVEN I click confirm button
THEN [add a menu option to the sideNav](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7841%3A27619)

GIVEN I click my save search query in the SideNav
THEN show the search results for my saved query

GIVEN my search results if favourited
WHEN I click on the Star button (Yellow = favourited)
THEN remove the shortcut from the sideNav

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7822%3A21080

### Dev tasks

- [x] Create a star toggle in the component library by using Toggle and use a <Button type=icon so that - 2

a) it can be used like this: <Toggle type="StarIcon" /> 
b) so that it can be used with another Icon type in future.  
c) so that it uses the same hover and focus states used in <Button type=icon

Custom star icon with empty / filled variants is here:

https://www.figma.com/file/SsqCzO2eherXXCKyixmli9/OpenCRVS-Design-System-v2-WIP?node-id=10%3A3264

- [x] In the SearchResult page, as long as - 3

a) the user is performing an Advanced Search & 
b) the user is online ... 
c) No searchId exists in the reducer

display the empty star icon toggle to be able to save the search.

- [x] When the empty star button is clicked launch the Modal and create the simple form to name the query.  Disable the confirm button if the name is empty or the user is offline.

- [x] When you click confirm, ..

a) submit the advanced search parameters along with the name of the query into the mutations created in ticket #4127 to either create or update the saved search.  

b) From the response, update all the saved searches in userDetails and IndexedDB that you created in #4127.   

c) You should save the searchId for this search into the reducer so that you can toggle the star icon button to a filled state

- [x] If the query fails with any error, show a Toast notification with the message "Sorry, something went wrong. Please try again"

- [x] In the SearchResult page, as long as 

a) the user is performing an Advanced Search & 
b) the user is online ... 
c) A searchId exists in the reducer

display the filled star icon toggle to be able to edit the search.

- [x] When the filled star button is clicked call the Delete mutation.  From the response, update all the saved searches in userDetails and IndexedDB that you created in #4127, and delete the searchId from the reducer to return the star toggle to an empty state

- [x] In Navigation.tsx, create a section for the saved searches.  - 2

a) Load all "searches" from the userDetails and display buttons containing the name and a star icon.

b) If any saved search button in the Navigation refers to an Advanced Search currently in a saved state in the active SearchResult page, ie with a searchId in the reducer, ensure that the button is disabled.

d) When the saved search button in the Navigation is clicked, (replace the search in the reducer with details from the saved search in userDetails and redirect the user to SearchResults with the searchText and searchType set to an Advanced Search in URL params.

**Comment by SyedaAfrida** [comment]
**Bug:**
Favourite bookmark list do not appear in side navigation after log out and show error message in search result 

https://user-images.githubusercontent.com/94350336/206446742-2eb0959a-6163-42b1-9778-e6d84ba9b41d.mp4

**Comment by Zangetsu101** [comment]
Should be fixed with #4390

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![fixed](https://user-images.githubusercontent.com/94350336/209086506-95eef07d-1fcb-4548-bbb2-1b8a18413cb2.png)

**Comment by anny320** [comment]
Completed
