### ISSUE TITLE
As a Reg Agent, Registrar or National Registrar I would like to see the details of a record when I click the View button

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#4119]
### Description
- Adds a view button to the record  for the search results page alongside the existing review button and download icon 
- Adds a view button  to the record in the record audit page alongside the correct record button, update button and download icon
- The view button when clicked navigates to a read-only page with the record and event details, no change buttons, text area or action buttons are enabled.
- The read-only page enables viewing of any supporting documents attached
- If there are no supporting documents attached then a copy message should show ["no supporting documents for ... "](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8034%3A25910)
...

### Acceptance criteria

GIVEN I  am a Reg Agent, Registrar or National Registrar  
WHEN I click on the record details and navigate to the record audit page
THEN I can see the View button alongside the Correct Record button, Update button and download icon

GIVEN I  am a Reg Agent, Registrar or National Registrar  
WHEN   I click the VIEW button on the record 
THEN it navigates to a [READ-ONLY page showing a summary of the event details](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8034%3A25910).

GIVEN I  am a Reg Agent, Registrar or National Registrar  
WHEN  I scroll on the read-only view page
THEN no change buttons, text area or action buttons are enabled.

GIVEN  I  am a Reg Agent, Registrar or National Registrar  
WHEN I scroll on the read-only record view 
THEN I can see supporting documents attached to the record

GIVEN  I  am a Reg Agent, Registrar or National Registrar  
WHEN  there are no supporting documents attached to the record
THEN I can see a message No supporting documents for the ...

### Design
search results view
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8165%3A31337

record audit view
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8186%3A32390

### Dev tasks ocrvs-4119-view-record

- [x] In RecordAudit->ActionButtons add a `View` button for RegAgent, Registrar or National Registrar which would redirect the user to a new page with route `/:declarationId/viewRecord` - 1
- [x] Create a new directory views->ViewRecord. Create a `query.ts` inside this directory and write a gql query inside this file named `viewRecord` which will use the `fetchRegistration` query already defined in gateway. The query parameters would be similar to `GET_BIRTH_REGISTRATION_FOR_REVIEW` and `GET_DEATH_REGISTRATION_FOR_REVIEW`. As this query returns a Union result (BirthRegistration | DeathRegistration) we need to use fragments for this query. We can take a look at `FETCH_REGISTRATION_BY_COMPOSITION` to get an idea
- [ ] Create a new page `ViewRecord` against the route mentioned above inside views->ViewRecord. It will execute the `viewRecord` query to get the declaration data and use `gqlToDraftTransformer` & `createReviewDeclaration` to create the declaration done similarly in [here](https://github.com/opencrvs/opencrvs-core/blob/fe7fbec0b409575036384dc28fef66463be555c4/packages/client/src/declarations/index.ts#L1299). Use `AppBar/FixedEventTopBar` for the header and `ReviewSection` component to render the view. - 3

### ocrvs-4119-review-section

- [x] Pass an optional prop `viewRecord `to `ReviewSection` which will hide all the change buttons and the footer section. To hide all the change buttons, in the mapStateToProps function inside `ReviewSection`, we need to modify the `registerForm` (which contains all the form definitions) and make all the fields readonly. - 1
```
for section in sections
  for group in section.groups
    for field in group.fields
      field.readOnly = true
      if field.nestedFields
        for key of field.nestedFields
          for nestedField in field.nestedFields[key]
            nestedField.readOnly = true
```
- [x] Similarly if `viewRecord` is true we will not render the [footer area](https://github.com/opencrvs/opencrvs-core/blob/fe7fbec0b409575036384dc28fef66463be555c4/packages/client/src/views/RegisterForm/review/ReviewSection.tsx#L1633-L1660) at the bottom part of `LeftColumn` inside ReviewSection->render method and the [link button](https://github.com/opencrvs/opencrvs-core/blob/fe7fbec0b409575036384dc28fef66463be555c4/packages/client/src/views/RegisterForm/review/ReviewSection.tsx#L1679) for documents
- [x] Add an optional prop disabled to `TextArea` component and pass the disabled prop to the `TextArea` component used [here](https://github.com/opencrvs/opencrvs-core/blob/fe7fbec0b409575036384dc28fef66463be555c4/packages/client/src/views/RegisterForm/review/ReviewSection.tsx#L1622) when `viewRecord` is true - 1

**Comment by SyedaAfrida** [comment]
**Bug:**
the updated changes in record do not appear in view record unless newly logged in

https://user-images.githubusercontent.com/94350336/204262259-4e85f788-ca96-457c-a15a-0a60862e2f73.mp4

**Comment by alamin-7** [comment]
@anny320  this ticket is fixed and can be closed

**Screen Record of test:**

[edit-test-in-view.webm](https://user-images.githubusercontent.com/38520477/209620121-c75cc9ea-3800-44f1-bad3-0c7ef1c74938.webm)

**Comment by anny320** [comment]
Completed
