### ISSUE TITLE
As a Reg Agent, Registrar or National Registrar, I would like the record audit history table updated with the action Viewed when I view a record

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#4120]
### Description

- Updates the record audit history table with the action "Viewed " and the device, IP, date and time details of the user

### Acceptance criteria

GIVEN I am a Reg Agent, Registrar or National Registrar
WHEN  I view a record 
THEN the record audit  history table  is updated with the action Viewed, 
 and the date and time details are included.

### Design

(Link to Figma)

### Dev tasks

- [x] In gateway features->registration->root-resolvers->fetchRegistration forward the call to workflow after adding a new extension for view-record (similar to fetchBirthRegistration)
- [x] In workflow->features->events->handler add a new event VIEW_RECORD
- [x] Detect the event similarly to DOWNLOADED in `detectEvent` function
- [x] Add a new case for the VIEW_RECORD event in `fhirWorkflowEventHandler`. We should be able to use the `actionEventHandler` similar to the DOWNLOADED event. 
- [x] In gateway->features->registration->schema.graphql add a new value in the enum `RegAction`
- [x] Modify the `getActionFromTask` to return the new RegAction
- [x] In client generate new graphql schema using `yarn generate-gateway-types`. Add the message for the new action in `regActionMessages`

**Comment by Zangetsu101** [comment]
@anny320 Are we supposed to show the device and IP in the History in RecordAudit page for the viewed action? Shouldn't it be similar to the other History rows?

**Comment by anny320** [comment]
Hi @Zangetsu101 you are correct, should be the same with the history rows

**Comment by SyedaAfrida** [comment]
**Bug:**
1. View modal wrong
![vieqw modal wrong](https://user-images.githubusercontent.com/94350336/204261649-c0022cd7-af19-418b-b3ad-b1c287ee7f43.png)
2. view and unassigned do not appear after once, unless a submission or rejection is made to another record

https://user-images.githubusercontent.com/94350336/204261901-9934066f-4e63-43c2-8532-936576f70597.mp4

**Comment by asifjoardar** [comment]
@anny320 this ticket is fixed and can be closed
[record-audit-history.webm](https://user-images.githubusercontent.com/35629053/209550116-60a22d8b-fccb-4768-b46c-bb4c8ad98df0.webm)

**Comment by anny320** [comment]
Completed
