### ISSUE TITLE
As a Reg Agent, Registrar or National Registrar, I would like to see a loading icon when the read-only record view page is being retrieved

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#4121]
### Description
- Adds a loading icon  to show the progress of the record retrieval when the details of the read-only record view page are loading
...

### Acceptance criteria

GIVEN I am a Reg Agent, Registrar or National Registrar,
WHEN I click the view button and it navigates to a new page
THEN I see a loading icon showing the progress of the record retrieval.

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8193%3A33196
### Dev tasks

- [x] Link the works from #4119 and #4120 - 1
- [x] Create the loading state according to the design - 1

**Comment by SyedaAfrida** [comment]
@anny320 this ticket has passed and can be closed

https://user-images.githubusercontent.com/94350336/204262907-13561268-0e44-48c8-9780-0b7e6ae86a8b.mp4

**Comment by anny320** [comment]
completed
