### ISSUE TITLE
As a Reg Agent, Registrar or National Registrar, on mobile  I would like to see the View button while on the record audit page

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#4122]
### Description
- On mobile view adds a view button to the record audit page
...

### Acceptance criteria

GIVEN I am a Reg Agent, Registrar or National Registrar
WHEN I click on the record details and navigate to the record audit page
THEN I can see the Update, Correct Record and View buttons

### Design

https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8186%3A32697

### Dev tasks

- [ ] Task 1

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![Screenshot_20221221-170213_Chrome](https://user-images.githubusercontent.com/94350336/208903894-b012ff3c-a181-4753-b9ed-04d79ac66e42.jpg)
![Screenshot_20221221-165948_Chrome](https://user-images.githubusercontent.com/94350336/208903946-47a6b824-18d9-4841-84e0-e1929f61da79.jpg)
![Screenshot_20221221-165958_Chrome](https://user-images.githubusercontent.com/94350336/208903974-15cf3841-f6de-479b-b6a5-d16526546951.jpg)

**Comment by anny320** [comment]
Completed
