### ISSUE TITLE
Our fhir.Bundle and other fhir types are too loose leading to defensive coding

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#4126]
Because fhir.Bundle can contain anything we have a lot of conditional coding like this which makes functions hard to read when we know for sure already what is in the bundle.

![image.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/86d474bf-1310-496d-91c7-703460781fc5)

We could replace blocks like this with a function or a stricter custom extension of a fhir type

**Comment by Zangetsu101** [comment]
Updating the fhir types to 0.035 would enable us to use generics in some of the types (e.g. Bundle, BundleEntry) which should make composing the types easier

**Comment by rikukissa** [comment]
https://github.com/opencrvs/opencrvs-core/pull/5879
https://github.com/opencrvs/opencrvs-core/pull/5877

These two PRs have improved the situation a lot. There are still many places in the code where we do this or make assumptions of for instance Composition always being the first entry of a bundle
