### ISSUE TITLE
Component / <Accordion> 

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#4134]
### Design
Note:
- the whole div is hoverable
- see the GovUk for a similar example https://design-system.service.gov.uk/components/accordion/

https://www.figma.com/file/SsqCzO2eherXXCKyixmli9/OpenCRVS-Design-System-v2-WIP?node-id=1073%3A12421

- [x] Create an Accordion component in the component library like RadioGroup which has NestedFields so that it can be used with FormFieldGenerator. Use ACCORDION_WITH_NESTED_FIELDS fieldDefinition.type which we would configure using JSON like the RADIO_GROUP_WITH_NESTED_FIELDS.  Refer to how [RadioGroup's nestedChildren](https://github.com/opencrvs/opencrvs-core/blob/1661712afe63451160fd90cc7960d4dc5fdc2be4/packages/client/src/components/form/FormFieldGenerator.tsx#L315) prop is used.

Use the details HTML element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![accordian](https://user-images.githubusercontent.com/94350336/206452881-825e40ce-f83e-456a-b20e-9770a09132af.png)

**Comment by anny320** [comment]
completed
