### ISSUE TITLE
Prepare `user-mgnt` to handle the new integrations

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#4146]
- [x] Amend the system schema in `user-mgnt`: change `name` to be a plain `string` and the `createdBy` to be the user ID of the user that has created the system. Amend `registerSystemClient` / `getSystemHandler` / `getAllSystemsHandler` in `user-mgnt` to use these values instead of the previous `{ use: String, given: [String], family: String }`
- [x] Amend the system schema in `user-mgnt`: add a `type` which can be either `HEALTH`, `NATIONAL_ID`, `RECORD_SEARCH`
- [x] Amend `registerSystemClient`: **disallow** creating a `NATIONAL_ID` -type System if one already exists.
- [x] Update `registerSystemClient` to populate `scope` with [`systemScopeMapping`](https://github.com/opencrvs/opencrvs-core/blob/20752517229bcf9c413232975df61325a4bb2744/packages/user-mgnt/src/utils/userUtils.ts#L35)  based on the payload input of `type`.

**Comment by Zangetsu101** [comment]
Done in #4170
