### ISSUE TITLE
As a System admin, I want to create a Webhook client integration

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#4160]
### Description

* Adds a new Type to "Create client" in Views -> Integrations

### Acceptance criteria

GIVEN I am creating a new integration client
WHEN I select type "Webhook"
THEN Show an explainer copy in Alert under the Type-dropdown

GIVEN I am creating a new integration client
WHEN I select type "Webhook"
THEN I am able to select the Birth details I want the webhook to contain with checkboxes

GIVEN I am creating a new integration client
WHEN I select type "Webhook"
THEN I am able to select the Death details I want the webhook to contain with checkboxes

GIVEN I have added a name. Selected a type Webhook. Not selected any details Birth/Death
WHEN I click create
THEN Create button is disabled

GIVEN I have added a name, selected a type Webhook and selected the details I want
WHEN I click create
THEN [show the loading state]

GIVEN the client has been created
THEN show the keys

GIVEN there was an error creating the client
THEN show the error. ‘There was a problem creating the client Webhook. Please try again.’

### Design

https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8478%3A44119&t=VLFCQHKirR7tq7cB-0
Note: No PII is not needed.

### Dev tasks

- [x] Add a new integration type "WEBHOOK" in `user-mgnt` system schema. Add  ``` { WEBHOOK: 'webhook' }``` to [systemScopeMapping](https://github.com/opencrvs/opencrvs-core/blob/20752517229bcf9c413232975df61325a4bb2744/packages/user-mgnt/src/utils/userUtils.ts#L35) 
- [x] To "Create client" -modal in Integrations, add a new type "Webhook". Selecting a webhook appends the modal with a  checkbox form. Submitting the form calls the create integration mutation and returns Client ID, Client Secret and Sha Secret according to the design.  Modify GraphQL create integrations mutation to allow inputting an array of permissions (for example `['REGISTRATION_DETAILS', 'CHILDS_DETAILS']`). Modify System-model in user-mgnt to allow inputting an array of 'permissions'. - 2
- [x] To Integrations 3-dot menu, **add** "Edit" for Webhook-types. Edit would open [a modal (Figma link)](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8645%3A51152) where you can edit the checkboxes. Confirming the modal call a **new** mutation in gateway which would call a **new** user-mgnt route to allow editing a System. - 2
- [x] Add the "permissions" to `applicationConfigHandler` so that they are loaded to frontend. Then in the frontend, list the permissions for a Webhook-type [according to the design](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8639%3A50893) - 2
- [x] Webhooks service: "transformBirthBundle" and "transformDeathBundle" should be amended to handle system scope "webhook". It then should fetch the System from user-mgnt, and check the permissions of the system. Push the corresponding data to the bundle. (See `nationalId` -scope in the transformBundles for example) - 2

**Comment by Zangetsu101** [comment]
@jpye-finch The design needs some updates. I've left some comments in the Figma link

**Comment by SyedaAfrida** [comment]
will be tested after the system crash mention in #2277 is fixed

**Comment by SyedaAfrida** [comment]
**Bug:**
When no details is selected from birth or death tab, the create button should be disabled and user should not be able to create webhook integration
 
![webhook](https://user-images.githubusercontent.com/94350336/209130204-ed5a9cb2-d1e9-4f29-8d73-0ccba3e08b03.png)

**Comment by Zangetsu101** [comment]
@SyedaAfrida Now I'm thinking it could be that some client only want to be notified about a birth event but don't want any details so selecting any checkbox might not be necessary. So I will be blocking this for now. Let's wait till Euan's back

**Comment by Zangetsu101** [comment]
We agreed that we should keep it the way it is currently

**Comment by alamin-7** [comment]
System admin can create a client without selecting any details (Birth or Death) which is ok and @Zangetsu101 mentioned it above. 
So @anny320 This ticket can be closed.

**Comment by anny320** [comment]
completed
