### ISSUE TITLE
When an application is submitted by field agent without last name, in place of blank shows "undefined" in review page title

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4167]
**Bug description:**
When an application is submitted by field agent without last name, in place of blank shows "undefined" in review page title when viewed by RA or registrar

_Note: This bug only appears after being submitted by FA_

**Steps to reproduce:**
1. Login as FA
2. Declare a birth/ death application
3. In child/ deceased details page keep last name empty
4. Submit the incomplete application
5. Logout from FA
6. Login to RA/ registrar
7. Click In progress> Field agent
8. Click Download> Assign> Update on that record
9. Observe the title of the review page

**Actual result:**
In place of blank (since no last name is given) shows undefined

**Expected result:**
should not show undefined

**Screen recording:**
https://images.zenhubusercontent.com/91778759/f69af351-9973-4cce-ab71-1bb6bb6c7d4b/undefined_in_name.mp4

**Tested in:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/203726632-95c058e3-3376-4881-aa8e-401b377b02da.mp4

**Comment by anny320** [comment]
completed
