### ISSUE TITLE
Implement the UI for creating an integration client in Configuration -> Integrations

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#4170]
Add a "[Create client]" button to the Configuration->Integrations `<Content>`. Pressing the button will open up a `<Modal>` according to the design. Selecting different types should show a short description of the system type.  After pressing "Create", the modal will display placeholder values as "Client ID", "Client Secret" and "Sha secret". - 1.5

https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8479%3A50384

**Comment by Zangetsu101** [comment]
Done in #4138
