### ISSUE TITLE
When a draft is saved and later tried to update , multiple default data of drop down not appearing in review page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4171]
**Bug description:**
When a draft is saved and later tried to update , multiple default data of drop down not appearing in review page But actually those fields are set as Farajaland by default in dropdown.

**Steps to reproduce:**
1. Login as Field agent
2. Declare a birth/ death event
3. Fill up upto contact number page
4. Click Continue
5. Click Save and exit
6. Click Update button of that application
7. Observe Informant, Mother, father details data

**Actual result:**
Though in the beginning the nationality, Usual page of residence, Is father/ mother details available data is not available. later when clicked change from each section all the data are available in drop down. And when Clicked back to review, all the data appear in review page as expected

**Expected result:**
the nationality, Usual page of residence, Is father/ mother details data should be available 

**Screen recording:** 

https://user-images.githubusercontent.com/94350336/198283944-9a7714bf-21c3-4c6d-9664-5c5cb9d6c8a9.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
@euanmillar @SyedaAfrida @anny320 This is the expected behavior as the default data for a particular section should show up only after a user has actually went through that particular section

**Comment by anny320** [comment]
closed
