### ISSUE TITLE
In record audit page, Applicant's name not appearing correctly before download when the language is set to french

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4175]
**Bug description:**
In record audit page, Applicant's name not appearing properly before download when the language is set to french

**Steps to reproduce:**
1. Login to FA/ RA/ Registrar
2. Go to settings
3. Change Language to french
4. Go to any application side menu (Ex- Ready to print)
5. Click any record (before download) and observe
6. Click Download> Assign to that record
7. Observe the Applicant's name

**Actual Result:**
 Before download Applicant's name is showing "No name provided" in french
After Download Applicant's name is showing correctly

**Expected result:**
Before Download Applicant's name should show correctly

**Screen recording:**
https://images.zenhubusercontent.com/91778759/0a4bed19-e40c-433e-8f88-a09b09e62396/french_bug.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=fr

- [ ] The name should default to using the defaultLanguage as a fallback instead of showing no name provided

**Comment by euanmillar** [comment]
Linked to configurability of character sets on names

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/203788500-c5d9443d-e09d-4e05-a603-dc135f81de93.mp4

**Comment by anny320** [comment]
completed
