### ISSUE TITLE
If a record is corrected from search, the reason of correction row disappears from "corrected record" action

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4185]
**Bug description:**
If a record is corrected from search, the reason of correction row disappears from "corrected record" action

**Steps to reproduce:**
1. Login as Local / national Registrar
2. Search any registered record
3. Download > assign to that record
4. Click Correct record
5. Make any correction
6. Search that record
7. Download > assign to that record
8. Click Corrected record and observe

**Actual result:**
 The reason of correction row disappears if a record is searched and then corrected
But it reappears if another correction is done from ready to print tab

**Expected result:** 
The reason of correction row should show always in corrected record action

**Screen recording:**
https://images.zenhubusercontent.com/91778759/96313f9d-d196-4a92-9de6-9ded12635aa0/if_a_record_is_corrected_from_search__the_reason_of_correction_row_disappears_from_corrected_record_.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by favour234** [comment]
Just observed that the issue has been resolved.
https://user-images.githubusercontent.com/69504395/203271871-fa5398db-8341-4a39-b0e3-2f5b954d6abf.mov

9.55.43.mov

**Comment by SyedaAfrida** [comment]
@anny320 this bug no longer exists. so this can be closed.

https://user-images.githubusercontent.com/94350336/203779499-4a2e93bd-0609-4df6-8fdb-c14e71c7cd7e.mov

**Comment by anny320** [comment]
closed
