### ISSUE TITLE
Misspelling of RegStatus in Metrics for in progress declarations

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#4187]
The pointGenerator script misspells the Reg Status when saving in_complete_fields.

This line must be fixed and then a migration written to fix any misspelled entries.

https://github.com/opencrvs/opencrvs-core/blob/0c7c13ef98916ea12e102fec8d966bfa7f578da4/packages/metrics/src/features/registration/pointGenerator.ts#L121

There may be no visual impact of this at this time, but the metrics being stored in the database are not accurate for form fields left incomplete in the database.  Should there be a future design that displays incomplete fields, then the bug will be noticeable.  

Our recommendation is to fix the issue early so that it doesnt become a larger problem in the future, although it is not a huge issue.

- [x] Correct the spelling mistake mentioned above
- [x] We will need to create a migration which would amend the measurment `in_complete_fields` to correct the spelling mistake as well

**Comment by euanmillar** [comment]
@anny320 we need a ticket in the backlog to show which fields havent been completed regularly by a field agent or registration agent in the performance dashboard

**Comment by jpye-finch** [comment]
@anny320 has this ticket been created?

**Comment by SyedaAfrida** [comment]
This ticket do not require QA testing

**Comment by anny320** [comment]
closed

**Comment by anny320** [comment]
@jpf @euanmillar added a placeholder ticket #4465
