### ISSUE TITLE
On server restart/invalid JWT, sys admin doesnt redirect to the login page

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#4190]
Whenever we redeploy the site, if the JWT is invalid or the cache is cleared then this error occurs.  It seems that a request to the backend interrupts the logic on ProtectedPage to redirect the user to login.  Maybe the solution is to do a JWT check in the Apollo Client component and redirect the user to login there like we do in ProtectedPage? I really dont know 

![Screenshot 2022-11-01 at 15.04.35.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/23fd1c61-c4ec-4415-a90b-f5f996b85317)

Some more steps to reproduce:

1. Login as jonathan.campbell  (or j.campbell as it’s currently on QA)
2. Make your login token invalid by removing the last character from it. Open DevTools -> Application tab -> Storage, Local 3. Storage and edit the value with a Key opencrvs
4. Reload the page

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![a](https://user-images.githubusercontent.com/94350336/205619010-b422ddf3-49b3-4fc0-9cc3-5feb47e54bb1.png)

**Comment by anny320** [comment]
completed
