### ISSUE TITLE
As a National System Admin, I want to configure if the informant signature is required

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4191]
### Description
- adds a config option to form config in global settings
- toggles on/off if the informant signature is required
- toggle to set if it is mandatory or optional

### ACs
GIVEN I a National System Admin
WHEN on the global setting page for form config
THEN I can set the informant signature to be required

Options:
- Disabled
- Enabled 
- Enabled (Required for registration)

GIVEN the informant signature capture is enabled
[THEN the required for registration toggle should be active
](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=9333%3A51060&t=auJuRSgAus1FqcKv-1)

GIVEN the informant signature capture is disabled
[THEN the required for registration toggle should be disabled
](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=9333%3A51011&t=auJuRSgAus1FqcKv-1)

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=9819%3A64556&t=auJuRSgAus1FqcKv-1
#### Client

- [x] In ticket #4005 we made the config database changes for this.  In the ReviewForm, hide the informant signature option if in offlineCountryConfiguration: INFORMANT_SIGNATURE is set to false.

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

**Comment by anny320** [comment]
completed
