### ISSUE TITLE
As an informant I want to confirm the details in the declaration form using a signature

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4192]
### Description
- Adds a signature CTA to the bottom of the declaration review page
- onClick informant is prompter toa dd signature
- either using mouse or trackpad on desktop
- or finger on a mobile device
- this was implemented for Nigeria. So code could be reused in Core

### ACs
GIVEN I a declaration is in progress
WHEN on the the review page
THEN I a prompted to add the informant signature

GIVEN I I click the signature CTA
WHEN open the signature dialog
THEN the informant can scribble into the signature box

GIVEN I am on a mobile device
[WHEN on the signature model is open (horizontal fullscreen dialog)
](https://www.figma.com/file/63OIwbkg9g1CSzwgyjVxQ3/Informant-signature?node-id=1%3A1729&t=CR8kIE4M3Xwcd8ub-1)
THEN I can sign with my finger 

GIVEN I have added a signature
WHEN I click remove
[THEN then show the confirmation model](https://www.figma.com/file/63OIwbkg9g1CSzwgyjVxQ3/Informant-signature?node-id=1%3A3542&t=CR8kIE4M3Xwcd8ub-1)

### Design
https://www.figma.com/file/63OIwbkg9g1CSzwgyjVxQ3/Informant-signature?node-id=0%3A1&t=CR8kIE4M3Xwcd8ub-1

### Dev

- [x] Copy all the changes in this PR into a new feature branch based on develop for v1.3.0: https://github.com/opencrvs/opencrvs-core/pull/4133/files#diff-726a9af27c9743ef8297d3252c8582639e70a755f8bc92b5cdc81e4a8bf92627

**Comment by euanmillar** [comment]
@euanmillar needs to check that the signature bugfix is added to this PR regarding correct record

**Comment by SyedaAfrida** [comment]
**Bug:**
1. signature not appearing in review page when application is submitted by FA/RA

https://user-images.githubusercontent.com/94350336/215472491-45d825a8-b7ea-44ae-ac1c-83798d933894.mp4

2.  Error in modal
![modal error](https://user-images.githubusercontent.com/94350336/215472874-e9837549-36a7-491f-91d7-fa504f43c71d.png)

**Improvement:**
1. Currently when try to upload signature, we can upload any file type. But we should only support png file type like we supported for signature of registrar. And for any other file type show error "Only png supported"
2. keep sign button and upload link disabled in view option

https://user-images.githubusercontent.com/94350336/215473746-ecffbc3d-2269-42f5-8576-1eef01bc964f.mp4

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/217809430-ed26e9b6-fddb-4de6-9838-692aaf24d27d.mp4

**Comment by anny320** [comment]
completed
