### ISSUE TITLE
Cannot reset password from Can't login option

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4199]
**Bug description:**
Cannot reset password from Can't login option

**Steps to reproduce:**
1. Click Can't login
2. Click Password reset and Continue
3. Enter valid Phone number and Continue
4. Enter verification code and Continue
5. Enter Correct answer to security Question and Continue
6. Enter Same password in New password and Confirm password
7. Click Confirm

**Actual Result:** 
cannot navigate to "password reset successful" page 

**Expected result:**
should be able to navigate to "password reset successful" page 

**Screen recording:**
https://images.zenhubusercontent.com/91778759/8f01939d-1502-4324-9669-57783cc72643/cannot_reset_password_from_can_t_login_option.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by SyedaAfrida** [comment]
@anny320 This bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/201874162-af52f1c4-3baa-424f-b5a7-3167c3b26789.mp4

**Comment by anny320** [comment]
completed
