### ISSUE TITLE
When searched an assigned application, in record audit page it is showing not assigned

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4201]
**Bug description:**
When searched an assigned application, in record audit page it is showing not assigned

**Steps to reproduce:**
1. Login as FA/ RA/ Registrar
2. Copy the tracking id of any application which is assigned to someone else
3. Search with that tracking id
4. Observe workqueue and record audit page

**Actual result:**
In workqueue it is showing assigned but in record audit page it is showing not assigned

**Expected result:**
It should should assigned in record audit page also

**Screen recording:**
https://images.zenhubusercontent.com/91778759/2fd05a71-33c0-42f8-9f3e-404fae0219f7/when_searched_an_assigned_application__in_record_audit_page_it_is_showing_not_assigned.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/207855163-6e9b5023-bd86-478b-98d2-f455e4d321bc.mp4

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/208671319-fc04151b-e1fc-428d-9894-5bb4070feedd.mp4

**Comment by anny320** [comment]
completed
