### ISSUE TITLE
Back and forward button gets disabled after going back or getting forward one time

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4203]
**Bug description:**
Back and forward button gets disabled after going back or getting forward one time

**Steps to reproduce:**
1. Login to any user
2. Switch multiple side menu
3. Click back button and observe
4. Click forward button and observe

**Actual result:**
Back and forward button gets disabled after going back or getting forward one time

**Expected result:**
1. User should be able to go back and forward until there is no other pages to go
2. Initially back and forward should be disabled

**Screen recording:**
https://images.zenhubusercontent.com/91778759/1f0b7e02-633f-4a88-905c-c9bb76251b79/back_and_forward_button_gets_disabled_after_going_back_or_getting_forward_one_time.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by anny320** [comment]
completed
