### ISSUE TITLE
Update copy of Registration by status in performance

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4206]
### Description
- it can be a bit confusing to differentiate the performance data and the Registration by status module 
- it not clear what the difference is

Options:
- update copy of statuses (In progress, In review, Requires updates, Validated, Registered)
- update heading copy to Record statuses or Current status of records
- link to User Support (start of the User support function). With additional commentry on what it is, how to use this data. video?
- move to a new page? 

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

(Link to Figma)

### Dev tasks

- [ ] Task 1

**Comment by euanmillar** [comment]
Closing this as we are deprecating this view and we can do in Metabase
