### ISSUE TITLE
Error occurs in verification code page when try to update phone number from settings page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4208]
**Bug description:**
Error occurs in verification code page when try to update phone number from settings page and do not update phone number. But later when Logged out and logged in, the update phone number is shown in the settings page.

**Steps to reproduce:**
1. Login to any user
2. Go to settings
3. Click change beside phone number
4. Enter new phone number and Continue
5. Enter valid verification code and Continue

**Actual result:**
Shows invalid verification code and do not update phone number.  But later when Logged out and logged in, the update phone number is shown in the settings page.

**Expected result:**
User should be able to update phone number properly

**Screen recording:**
https://images.zenhubusercontent.com/91778759/621a144a-febb-4336-a03b-40f7b5febea4/settings_phone_number_error.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/203509896-204d91d6-d3ed-4ac3-b910-f7a79f8a1fa4.mp4

**Comment by anny320** [comment]
completed
