### ISSUE TITLE
Error message is showing when trying to update password when actually the password is updated

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4209]
**Bug description:**
Error message is showing when trying to update password when actually the password is updated

**Steps to reproduce:**
1. Login as any user
2. Go to settings
3. Click Change in password
4. Enter old password, new password and confirm password
5. Click Continue

**Actual result:**
Shows error message "current password incorrect. Please try again." But when logged out , user can log in with the updated password.

**Expected result:**
Should not show error message and should show toast "Phone number is updated"

**Screen recording:**
https://images.zenhubusercontent.com/91778759/e79769ec-650b-4069-a673-e8f5139a0edd/error_message_is_showing_when_trying_to_update_password_when_actually_the_password_is_updated.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
https://www.loom.com/share/33c8d59cd50e4069b60824a3275357c5

**Comment by anny320** [comment]
completed
