### ISSUE TITLE
Notify user when they reconnect

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4211]
### Description
- https://www.notion.so/opencrvs/7d321101427640088c305b8bf630aa21?v=cd71becb0d0e4c14a13e67ba38fba1ac&p=93c8e39eb95b464b9911027ba7d62a9c&pm=s
- adds a Toast when they reconnect to the internet
- Toast copy??: 'Back online', Connection reestablished' 

![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/84838b0b-e8a1-4909-a60b-55e4183b2b1b)

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
<Toast type=positive / >

### Dev tasks

- [ ] Task 1

**Comment by euanmillar** [comment]
Replaces the service worker one

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![c](https://user-images.githubusercontent.com/94350336/204270361-0f0f3cbe-852d-4dba-bef6-02a21598f50b.png)
![b](https://user-images.githubusercontent.com/94350336/204270369-3cb79947-3935-438d-9e9b-2365ee1402c0.png)
![a](https://user-images.githubusercontent.com/94350336/204270372-efc6b662-4afe-4482-bfe0-446087554641.png)

**Comment by anny320** [comment]
completed
