### ISSUE TITLE
Enable reordering of default form fields in form config

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4214]
### Description
- In V1 we only allowed reordering to custom form fields
- In some countries such as Nigeria and Madagascar they would like to ask for the Lastname first. Then Firstname(s)
- this ticket it to enable all fields to be reordered

### Acceptance criteria

GIVEN I am a National System Admin
WHEN in form configuration and a default field is active
THEN I can choose to reorder the field

### Dev tasks

- [ ] Task 1

**Comment by SyedaAfrida** [comment]
**Bug:**
In review page fullname gets changed when first name and last name are reordered

https://user-images.githubusercontent.com/94350336/207255868-82e450e8-596b-4603-9aae-6c9542c4261a.mp4

**Comment by SyedaAfrida** [comment]
@anny320 this issue is fixed for review page only and the rest of the part will be fixed in #4464 . So this ticket can be closed

https://user-images.githubusercontent.com/94350336/209648733-49ba406e-324c-433c-95af-224dfc5d54c6.mp4

**Comment by anny320** [comment]
Completed
