### ISSUE TITLE
Add certificate handlebars to all form fields

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4216]
### Description
- Not all form fields in Form Config have cert handlebars
- Some countries want to add alot of details to the certificate!
- this ticket is to show cert handlebars for all form fields

### Acceptance criteria

GIVEN I am a National System Admin
WHEN in Form Config
THEN all form fields have a cert handlebar shown in the rightSideMenu

### Dev tasks

- [x] In default.ts we would need to add template mapping for all the fields that don't have one
- [x] In FormConfig->DefaultFieldTools we would need to show handlebars for all the default fields

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/207275687-63422db7-7279-40e7-9feb-d56616e1c92e.mp4

**Comment by euanmillar** [comment]
Please note that address handlebars are not set up yet and blocked by #4373

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/208622024-d7b5ca38-e634-43b2-916f-682c334424ed.mp4

**Comment by anny320** [comment]
Completed
