### ISSUE TITLE
Registration by status page of performance is broken

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4217]
**Bug description:**
Registration by status page of performance is broken

**Steps to reproduce:**
1. Login as Registrar
2. Click Performance
3. Click any link of registration by status
4. Observe the page

**Actual result:**
https://images.zenhubusercontent.com/91778759/dfe171ca-934b-49b0-8e29-58f7a15440e5/registration_by_status_page_is_broken.mp4

**Expected result:**
 The table should fit into the screen

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by CornelMaze** [comment]
I could not reproduce this bug.https://images.zenhubusercontent.com/91778759/9c7b8bc5-d514-4900-8033-528a43274547/screen_recording_2022_11_21_at_1_25_42_pm.mov

**Comment by SyedaAfrida** [comment]
@CornelMaze this bug appears in large screen. To reproduce it is in small screen, the screen needs to be zoomed out

https://user-images.githubusercontent.com/94350336/203057044-168d226b-601c-4dff-a3e0-1b99e3b7deed.mp4

**Comment by CornelMaze** [comment]
@SyedaAfrida You are right. I just found it.

**Comment by SyedaAfrida** [comment]
This ticket can be tested properly after bug fixes of advance search.

**Comment by SyedaAfrida** [comment]
**Bug:**
Though this issue is fixed for large screen, but registration by status page now gets broken in mobile view

https://user-images.githubusercontent.com/94350336/208886582-0b79ff22-9065-4fd3-896a-368d9be68159.mp4

**Comment by asifjoardar** [comment]
**Bug:**
1. Registration by status page is broken if we zoom out the page.

[4217.webm](https://user-images.githubusercontent.com/35629053/210528022-b0cc4054-a853-4dda-ad4f-a89b6ea4ed66.webm)

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/210752935-bafc3c03-e4cd-4f41-8212-137d1ee1b18f.mp4

**Comment by anny320** [comment]
completed
