### ISSUE TITLE
"Corrections" is hardcoded in SysAdmin / Performance / CorrectionsReport.tsx

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#4234]
This prevents it from being localised.  This must be resolved in a hotfix

![CorrectionsReportLine41.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/5beb9b08-a560-430f-b85a-69c5877fe7ff)

**Comment by anny320** [comment]
completed
