### ISSUE TITLE
Sometimes cannot print a certificate with Print in advance option

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4235]
**Bug description:**
Sometimes cannot print a certificate with Print in advance option and show error "Please select who is collecting the certificate".

**Steps to reproduce:**
1. Login to RA/ Local Registrar/ National Registrar
2. Go to ready to print tab
3. Click Download > Assign to any record
4. Click Print from Work queue or Record audit page
5. Click Print in advance > Continue

**Actual result:**
Sometimes show error "Please select who is collecting the certificate" and cannot go to next page

**Expected result:**
User should be able to print certificate with Print in advance option

**Screen recording:**
https://images.zenhubusercontent.com/91778759/f5b6bf9e-c110-44f6-a8b7-112a4a9acd92/print_in_advance_bug.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by CornelMaze** [comment]
Could not reproduce this bug.
https://images.zenhubusercontent.com/91778759/96dbb57e-3bb6-497c-944b-31915b26dc57/screen_recording_2022_11_21_at_1_25_42_pm.mov

**Comment by rabiulislamanik** [comment]
Couldn't reproduce this bug.

https://www.loom.com/share/80e488a82e3949ca896ead49593ffe45

**Comment by anny320** [comment]
complete![Screenshot 2023-03-14 at 09.56.59.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/32080625-2e89-4fd5-a8b3-fac21b5645e6)d
