### ISSUE TITLE
In Application config- Currency modal, the verbiage is showing wrong

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4248]
**Bug description:**
In Application config- Currency modal, the verbiage is showing wrong

**Steps to reproduce:**
1. Login as national system admin
2. Click Configuration> Applications
3. Click Change in currency and observe

**Actual result:**
the verbiage of logo is showing

 **Expected result:** 
should show "Select your currency for your CRVS

**Screenshot:**
![currency.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/06ba0dfa-6f34-4ec2-b595-2722e781df3c)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![corrency](https://user-images.githubusercontent.com/94350336/203728511-f7f9ee77-f19f-40fd-a4ca-6ee4989a60eb.png)

**Comment by anny320** [comment]
completed
