### ISSUE TITLE
The modal title of delay registration in birth tab is showing wrong

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4249]
**Bug description:**
The modal title of delay registration in birth tab is showing wrong

**Steps to reproduce:**
1. Login as national system admin
2. Click Configuration> Applications> birth
3. Click Change in delayed registration and observe

**Actual result:**
Showing legally specified time period for birth registration

**Expected result:**
should be delayed registration time period for birth registration

**Screen recording:**
https://images.zenhubusercontent.com/91778759/0caae3a0-b8bc-41e3-a250-d50e7425f6f5/when_clicked_delayed_registration_wrong_title_is_showing.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![4249 fixed](https://user-images.githubusercontent.com/94350336/203746711-b2b366a7-03c5-45c9-999e-4e4663ea83a7.png)

**Comment by anny320** [comment]
completed
