### ISSUE TITLE
In application config, Within legally specified time gets changed when delayed registration fee is changed

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4250]
**Bug description:**
In application config, Within legally specified time gets changed when delayed registration fee is changed

**Steps to reproduce:**
1. Login as national system admin
2. Click Configuration> Applications> Birth
3. Click change in delayed registration fee
4. Set a number and Confirm
5. Observe both  Within legally specified time and delayed registration fee 

**Actual result:**
Within legally specified time gets changed when delayed registration fee is changed

 **Expected result:**
Within legally specified time should not change

 **Screen recording:**
https://images.zenhubusercontent.com/91778759/2b26165b-8805-40ac-a6d0-843868e75045/within_legally_specified_time_gets_changed_when_delayed_registration_fee_is_changed.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/203731839-db3c7381-ede6-4d43-9795-8a33af1b585b.mp4

**Comment by anny320** [comment]
completed
