### ISSUE TITLE
Audit the username reminder and password reset events

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#4258]
In #2272 we added 2 new feature to for sysadmins to send a username reminder for a particular user and reset a particular user's password. But we are not auditing these events.

- [x] In metrics in the userAudit handler add two new event types for usename reminder and password reset - 1
- [x] user-mgnt in the handlers for these two events, we need make a call to the userAudit endpoint in metrics - 1
- [x] In userAudit history, add translations for these 2 events - 1

**Comment by SyedaAfrida** [comment]
**Bug:**
username is getting removed from user audit page and all modal when language is changed to french

https://user-images.githubusercontent.com/94350336/208911031-e403019f-d272-4464-9c8b-c508eaacb507.mp4

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/209542192-1e50fd84-2e15-4609-9499-d1f355191fa4.mp4

**Comment by anny320** [comment]
completed
