### ISSUE TITLE
Update username notification not sending updated username

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#4259]
when user’s firstname + lastname is changed by a sysadmin, we generate a new username for them. This triggers an SMS notification for the user to receive a new username.

What we try to send [here](https://github.com/opencrvs/opencrvs-core/blob/00a7543dcec90f4c15b63111f0b737ecbcc13de2/packages/user-mgnt/src/features/updateUser/handler.ts#L150) is undefined  as `user`  is whatever the system admin inputted. As the username is only generated by [this](https://github.com/opencrvs/opencrvs-core/blob/00a7543dcec90f4c15b63111f0b737ecbcc13de2/packages/user-mgnt/src/features/updateUser/handler.ts#L124-L131) code, it should be existingUser.username/newUserName (check line 129) we should be using here

**Comment by SyedaAfrida** [comment]
This ticket will be tested after SMS is enabled in QA/ config environment

**Comment by alamin-7** [comment]
@anny320 This ticket is ok and can be closed.

**Screenshot of SMS:**
![sms](https://user-images.githubusercontent.com/38520477/210497751-25c087c6-25ec-4c1e-a301-657c9982383b.png)

**Screen Record of testing:**

[sms_test.webm](https://user-images.githubusercontent.com/38520477/210497898-4eb11ad8-b3f3-4c8e-9c22-f442d24db791.webm)

**Comment by anny320** [comment]
completed
