### ISSUE TITLE
In Certificate preview, the prints in certificate are not clear

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4262]
**Bug description:**
In Certificate preview, the prints in certificate are not clear

**Steps to reproduce:**
1. Login to RA/ National registrar/ Local registrar
2. Go to ready to print 
3. Click Download> Assign > Print to any record
4. Click print in advance> Continue
5. Observe the certificate

**Actual result:**
the prints in certificate are not clear

**Expected result:**
the prints in certificate should be clear

**Screenshot:**
![cer.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/cd7a6515-c4d3-41d7-be6a-8c975a0a7d66)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by euanmillar** [comment]
@SyedaAfrida @anny320 I cant replicate this at all

**Comment by SyedaAfrida** [comment]
@euanmillar you should be able to find this bug in QA environment

https://user-images.githubusercontent.com/94350336/203512482-b16f8171-60a6-4db1-9b7c-23cf539b086b.mp4

**Comment by euanmillar** [comment]
Unfortunately none of us can replicate this issue.  If this is just a bug on @SyedaAfrida 's machine with PDF preview, and the printed PDF itself prints OK, then I think this can be mentioned as low priority until we can find a way to replicate it.

**Comment by SyedaAfrida** [comment]
@euanmillar this bug is only appearing in Windows, not in linux. I have verified it from multiple machines. Anyone trying to replicate this bug needs to use Windows

**Comment by euanmillar** [comment]
Can we experiment with different rendering approaches?  https://github.com/diegomura/react-pdf/issues/1649

**Comment by modupeadeonojobi** [comment]
This problem is unique to the Chrome browser in Windows. By default, "Use hardware acceleration when available" is enabled.
I was able to clearly preview the certificate after disabling it.

![hardware-acceleration](https://user-images.githubusercontent.com/66411673/206451457-374fd10e-06ee-4b52-b4be-f6af52f1eaab.png)
![certificate-preview](https://user-images.githubusercontent.com/66411673/206451493-57f16101-f81a-4ba3-b8f2-3629a7186117.png)

**Comment by SyedaAfrida** [comment]
@modupeadeonojobi thanks, I was able to resolve this issue.
@anny320 closing this ticket as it's not a bug
![cer](https://user-images.githubusercontent.com/94350336/206674940-992530c6-7c97-4d15-971e-6e310d04c5df.png)
