### ISSUE TITLE
IP Addresses are not correct for Audit Actions

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#4265]
https://dockerswarm.rocks/traefik/#getting-the-client-ip

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![ip](https://user-images.githubusercontent.com/94350336/209082946-33b31887-8641-4ba9-b191-29f388ea2f46.png)

**Comment by anny320** [comment]
Completed
