### ISSUE TITLE
Searching for duplicates is only considering Birth declaration related fields

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#4276]
The [buildQuery](https://github.com/opencrvs/opencrvs-core/blob/de9df3870566bec0b1d97e617cb7a0ccb9a2b10d/packages/search/src/elasticsearch/utils.ts#L265) function is only considering birth related fields and we use this query to search for duplicates.

**Comment by euanmillar** [comment]
Closing this as now we have a ticket for it
