### ISSUE TITLE
As a National System Admin I want to configure the SMS message sent to informant

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4287]
### Description
- adds new navigation section called Communications
- adds sub pages. Informant notifications
- toggle for each SMS notification

### Acceptance criteria

GIVEN I am National System Admin
[WHEN I toggle off an SMS
](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8837%3A63545&t=yqYqZJFcLGb566gc-1)
THEN don't send the SMS!

GIVEN I am National System Admin
WHEN I change the language
THEN change the copy of the SMS to my selected language

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=8837%3A63545&t=yqYqZJFcLGb566gc-1

### Dev tasks

- [x] Create a new model in config microservice called InformantSMSNotifications which would have an array of `{ name: string, enabled: boolean }`. Add a GET endpoint to retrieve them all and another PUT endpoint to modify one. These should be restricted to natlsysadmin - 2
- [x] The `informantSMSNotifications` query would call the GET endpoint in config and the `content/notification` endpoint in farajaland, then merge them into the required format and return them - 2
- [x] The `toggleInformantSMSNotification` mutation should use the PUT endpoint in config to update the smsNotification configuration.
- [x] In the LeftNavigation, add a new section communications. Inside that add informantNotifications. Selecting it should go to the InformantSMSNotification page. Handle the expanded, selected states - 1
- [x] Use the `informantSMSNotifications` query to render the view according to design. Clicking save would call the `toggleInformantSMSNotification` mutation. Disables the toggle button when the mutation is in progress. handle the success and error states properly. - 2
- [x] Inside `sendEventNotification` function in workflow, get the InformantSMSNotification configurations, don't send the notification if the value for a particular SMSNotification is false. (We assume it's true by default) - 1
- [x] Write a migration to store informant SMS content on application-config DB from Farajaland for the first time- 1
The names of the SMSNotifications : `birthInProgressSMS, birthDeclarationSMS, birthRegistrationSMS, birthRejectionSMS`
```gql
type SMSNotification {
  name: String!
  message: String!
  enabled: Boolean!
}

input SMSNotificationInput {
  name: String!
  enabled: Boolean!
}

type Query {
  informantSMSNotifications(): [SMSNotification!]
}

type Mutation {
  toggleInformantSMSNotification(smsNotification: [SMSNotificationInput!]): [SMSNotification!]
}
```

**Comment by SyedaAfrida** [comment]
Since the toggle button is not working properly could not complete the test.
**Bug:**
https://user-images.githubusercontent.com/94350336/222704435-b2ba70a6-ec04-4d43-8d76-641dc9b01fce.mp4

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is tested. The bugs are mentioned in- #4845

**Comment by anny320** [comment]
completed
