### ISSUE TITLE
As a National System Admin, I want to configure the SMS messages sent to a user

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4288]
### Description
- adds new navigation section called Communications
- adds sub pages. User notifications
- toggle for each SMS notification
- Note does not include 2 factor SMS! 

### Acceptance criteria

GIVEN I am National System Admin
[WHEN I toggle off an SMS message to a user 
](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=9722%3A61338&t=yqYqZJFcLGb566gc-1)
THEN don't send the SMS!

GIVEN I am National System Admin
WHEN I change the language
THEN change the copy of the SMS to my selected langauge

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=9722%3A61338&t=yqYqZJFcLGb566gc-1
### Dev tasks

- [ ] Task 1

**Comment by Zangetsu101** [comment]
I think we can close this as we won't be doing the language select
