### ISSUE TITLE
UI issue in modal of certificate config for large file names 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4294]
**Bug description:**
UI issue in modal of certificate config for large file names 

**Steps to reproduce:**
1. Login as national system admin
2. Click Configuration > Certificate
3. Click 3 dot menu> Upload
4. Enter an svg with large file name and observe

**Actual Result:**
![cer modal.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/7a0bebfb-f16f-48e2-9225-138e59c72a58)

**Expected result:**
 large file names should properly fit to the modal

**Tested On:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by jpye-finch** [comment]
I can push a PR for this. Which fixes outstanding ui issues ![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/36924c5f-5483-412a-94e4-feae427549e6)

**Comment by anny320** [comment]
@jpye-finch any update on the progress of this ticket?

**Comment by jpye-finch** [comment]
Yes my PR never made it :(

We should be truncating (adding ...) the text if it is too long

**Comment by anny320** [comment]
@Zangetsu101 please look into this ticket too

**Comment by kayumuzzaman** [comment]
![Screenshot from 2023-04-27 16-20-59](https://user-images.githubusercontent.com/46846503/234835654-77bb0c67-220d-41f4-a3fc-d081bc0acaf7.png)
@Zangetsu101 this issue already solved in another PR

**Comment by ShohelaTasin** [comment]
@anny320  this ticket is fixed! Can be closed Now! 
![Screenshot (67)](https://github.com/opencrvs/opencrvs-core/assets/41486148/d0d1ac61-6b5f-4a1c-ae47-fe9a0e1f99ac)

**Comment by ShohelaTasin** [comment]
@anny320  Fixed! Can be closed Now! 
![Screenshot (111)](https://github.com/opencrvs/opencrvs-core/assets/41486148/bcc549cc-d1d6-41a5-b42d-84791bbb4eca)
