### ISSUE TITLE
As a user (except FA) I want to navigate the organisation tree of administrative levels and offices (location)

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4304]
### Description
- adds new section Organisation for all users except FA
- Default to level 1 eg List of States
- Clicking a level 1 item updates the list to level 2 items within level 1 🤪
- Add new component < Breadcrumb />
- Icon button links to the performance page for that location

### Acceptance criteria

GIVEN I am a user (except FA)
WHEN I click Organisation in sidemenu
THEN navigate to the Organisation page (defaulted to level 1)

GIVEN I click a location ie level 1 location
THEN update the Breadcrumb to my selection + show the locations within level 1

GIVEN I click an office
THEN navigate to the team page for that office

GIVEN I click the performance button
THEN navigate to the performance page for that location/office

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=9532%3A56465&t=kqOKTJz7eO8Wo3R4-1

### Dev tasks

- [x] Create a new empty view for the application and a link to navigate to this view to the left sidebar. This link should be shown for all users except for field agents. (1)
- [x] Find the list of locations & offices from Redux state (hint: look for offlineData). Render top-level (level 1) locations in the view in a list. [Use ListView component from our component library](https://ui-kit.farajaland-staging.opencrvs.org/?path=/docs/data-list-view--default). (1)
- [x] When the user clicks on any of the locations, they should now see locations that are under (part of) the location they just clicked on (2)
  - Notice that different countries can have a different number of administrative levels. How can we make this dynamic?
- [x] Create a new Breadcrumb component to component library according to the designs
- [x] Render a breadcrumb to all pages showing the user where they have currently navigated to. Use Breadcrumb component from the component library  (1)
- [x] Add the "performance icon" to every list item. Click this should take the user to the Performance view, so that the same location's data is shown by default

**Comment by euanmillar** [comment]
@jpye-finch we would love to give this to the Cameroon team as a good first issue.  Is there any way the design could be finished as it doesnt look finished to me in this Figma link?

**Comment by euanmillar** [comment]
@jpye-finch @anny320 @eduffus the AC says:  "GIVEN I click an office
THEN navigate to the team page for that office" and the ticket says "As a user (except FA)".  But only nat sys admins can navigate to a Team page for another office.  Are you saying you want to change that for Reg Agent and Registrar. If so, I assume they should not see the 3 dot menu on each row per user on the Team page of any office, nor the "add user" button, but why not let them have the location search?  I think we need AC for this so that test cases are updated as this it sounds like permissions are changing.  ![Screenshot 2023-01-16 at 13.29.59.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/1b335a43-13e5-40dd-b952-52f7adc81448)

**Comment by rikukissa** [comment]
@euanmillar 
>If so, I assume they should not see the 3 dot menu on each row per user on the Team page of any office, nor the "add user" button, but why not let them have the location search?

This is the current behaviour, right? Having the location search button for every user (except FA) makes sense if we let any user browse users from all offices. 

This is my Team view as a registrar:
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/1206987/213099954-fa0806e8-16c2-466a-ba4c-788a8191eeb9.png">

**Comment by jpye-finch** [comment]
Yes currently we only System Admins get the CTA to edit a user, add, search

**Comment by nsamadavid** [comment]
No Breadcrumb component as described in the task.

**Comment by rikukissa** [comment]
Yea, sorry about that. I missed it when doing dev design, but it was mentioned in JPF's description

>Add new component < Breadcrumb />

**Comment by SyedaAfrida** [comment]
**Improvement:**
Ilanga district office should be under Ilanga district and Isamba district office should be under Isamba district
![2](https://user-images.githubusercontent.com/94350336/218389107-eb67b4d8-feb9-4ea2-a27b-382ea33a239e.png)
![1](https://user-images.githubusercontent.com/94350336/218389113-8eed663e-fe46-4cf1-80c8-3b2212f35507.png)
