### ISSUE TITLE
UI issue for mobile view: Overlapping data in Completeness rate table

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4306]
**Bug description:**
UI issue for mobile view: Overlapping data in Completeness rate table

**Steps to reproduce:**
1. Login as national registrar/ national system admin rom mobile
2. Go to performance
3. Click View in Completeness rate section
4. Observe the table

**Actual result:**
Overlapping data in Completeness rate table

**Expected result:**
should not overlap

**Screenshot:**
![per.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/170a7474-f191-4eb4-9b86-eab4827d0a19)

**Tested on:**
browserstack and real device

**Comment by jpye-finch** [comment]
The table needs to overflow. As we do on other pages

![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/e6fabd42-e00b-4aec-83d2-534a20663426)

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![fixed](https://user-images.githubusercontent.com/94350336/209093407-523de452-9d02-41ae-b66a-838846257dca.png)

**Comment by anny320** [comment]
Completed
