### ISSUE TITLE
UI issue in Form config: icon of error message not clearly visible

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4307]
**Bug description:**
UI issue in Form config: icon of error message not clearly visible

**Steps to reproduce:**
1. Login as National system admin
2. Click Configuration> Form declaration
3. Click Configure
4. Create any custom field with label example- "new field" in both english and french
5. Click Save 
6. Create another custom field with same label name "new field" and observe

**Actual result:**
![Screenshot from 2022-11-15 16-19-11.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/4fd465e5-ac18-4306-a647-62e75aaa88b1)

**Expected result:**
 icon of error message should be clearly visible

**Tested on:**
https://login.farajaland-config.opencrvs.org/

**Comment by jpye-finch** [comment]
There might be multiple fields that have the same label. eg. Phone number on Mother details and Phone number on Father's details.

So we should append 1 maybe to the handlebar. {{PhoneNumber1}},  {{PhoneNumber2}}

**Comment by Zangetsu101** [comment]
@jpye-finch This error shows up for custom fields and the user gives the name of the field as input. So we need to show the error message in case duplicate names are found

**Comment by jpye-finch** [comment]
so we can't have two custom fields with the same label?

**Comment by jpye-finch** [comment]
ok so we can't have a two custom fields with the same label in the same section. eg. Father details

We should throw the error entering the label and disable the Save button. 
<img width="272" alt="image" src="https://user-images.githubusercontent.com/46478402/206414675-8448f178-ce65-4de9-98f7-6a9263534541.png">

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![4307](https://user-images.githubusercontent.com/94350336/208427470-101c23b0-f6a4-44ae-a01a-04a4e0d9f35f.png)

**Comment by anny320** [comment]
completed
