### ISSUE TITLE
In form config multiple content keys are not correct

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4309]
**Bug description:**
In form config multiple content keys are not correct

**Steps to reproduce:**
1. Login as National system admin
2. Click Configuration> Form declaration
3. Click Configure in both birth and death

**Actual result:**
1. Informant's first and last name in both birth and death
![s.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/8d03b547-bcb3-45ea-9148-a56c917f0d0e).

2. Certificate handlebar of Child's sex
![s1.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/f13c41a7-7696-40a9-a68a-2d63e240aecc)

3. Father's date of birth
![s2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/84b9a94c-a12e-42bc-b3ce-797330b4b893)

4. Father's level of education
![s3.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/8c5cc4c8-0146-4e87-983c-dbffddc80bdf)

5. Informant's date of birth in both birth and death
![s4.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/1f52a530-758c-4fc9-8c7f-4a25dc2d44a9)

6. informant's nationality in both birth and death
![s5.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/c38cd9f7-32f1-49e4-b2ec-5a89f1c83728)

**Tested on:**
https://login.farajaland-config.opencrvs.org/

**Comment by euanmillar** [comment]
We need to rename the content keys where the labels are the same for mother and father for example.

**Comment by favour234** [comment]
> We need to rename the content keys where the labels are the same for mother and father for example.

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/209112764-4481140a-6098-490d-b180-30550004b517.mp4

**Comment by anny320** [comment]
Completed
