### ISSUE TITLE
In correction record, when Country is change from farajaland to anther country, invalid data shows in state and district

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4310]
**Bug description:**
In correction record, when Country is change from farajaland to anther country, invalid data shows in state and district

**Steps to reproduce:**
1. Login as registrar
2. Go to ready to print
3. Download > assign any record
4. Correct record
5. in review page> mother's/ father's/ informant's section, change location from farajaland to any other country
6. Observe the change in review page and correction summary page

**Actual result:**
Invalid data shows for original location

**Expected result:**
should show real location- central ibombo

**Screen recording:**
https://images.zenhubusercontent.com/91778759/8a4a8723-07a7-4b7f-9373-5e4fcbf69e03/loc_id.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
**Bug:**
1. When location is changed from farajaland to any other country, invalid data is showing in correction summary page and record audit (corrected record modal)

https://user-images.githubusercontent.com/94350336/209521518-1e8d7071-289b-47b9-8a21-82a31377eaca.mp4


2. when location is changed from other country to farajaland, then the old state and district is showing blank in correction summary page and  audit page

https://user-images.githubusercontent.com/94350336/209521683-fba570b8-0a20-41ae-8f14-5fcd4d080453.mp4

**Comment by asifjoardar** [comment]
**Bug**

1. Father's "[fathers-usual-place-of-residence.webm](https://user-images.githubusercontent.com/35629053/210041764-d647d2ac-ecab-4e05-9ae1-83ca0c532e30.webm)(Same as mother's usual place of residence?)" field is selected to "yes" by default, even if i change it it remains "yes".

**Comment by asifjoardar** [comment]
**Bug**

1. Father's "usual place of residence(Same as mother's usual place of residence?)" field is selected to "yes" by default, even if i change it remains "yes".

[fathers-usual-place-of-residence.webm](https://user-images.githubusercontent.com/35629053/210041873-23c23205-e473-4671-96bb-d5f75863db97.webm)

**Comment by yeasinhossain-dsi** [comment]
> **Bug**
> 
> 1. Father's "usual place of residence(Same as mother's usual place of residence?)" field is selected to "yes" by default, even if i change it remains "yes".
> 
>  fathers-usual-place-of-residence.webm

This is not a bug, 
You have selected Usual address of father as different address of mother, but the country, state & district is same as mother. That's why it is happening. If you select different country or state or district then you will see it is being stored.

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/210232949-a63b98c7-b355-41fc-b0d1-bacaa190c067.mp4

**Comment by anny320** [comment]
Completed
