### ISSUE TITLE
Reinstate action name not showing correctly

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4311]
**Bug description:**
Reinstate action name not showing correctly

**Steps to reproduce:**
1. Login as RA/ registrar
2. Click Download> assign to any record which is reinstated
3. Check the action in record audit

**Actual result:**
![reinstate.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/fd13231a-2340-4c48-aa0a-a580c69495e3)

**Expected result:**
Should be Reinstated to in progress/ reinstated to ready for review/ reinstated to requires updates

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![reinstate 2](https://user-images.githubusercontent.com/94350336/207044425-a2612357-7461-4979-ad0b-4f8d6f96a32a.png)
![reinstate1](https://user-images.githubusercontent.com/94350336/207044433-a35f9109-5b5f-4069-81d6-881fd07d664c.png)

**Comment by anny320** [comment]
completed
