### ISSUE TITLE
Unit should be mentioned beside weight at birth

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4312]
**Bug description:**
Unit should be mentioned beside weight at birth

**Steps to reproduce:**
1. Login as FA/ RA/ registrar
2. Declare a birth event
3. Put value at weight at birth and observe in review page

**Actual result:**
![kg.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/e5e573b2-9e5b-42ec-a79e-ddaf834e02da)

**Expected result:**
![image (1).png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/5eb4c581-d616-455e-bd16-76b445aec694)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by jpye-finch** [comment]
@Zangetsu101 @euanmillar Is a holistic solution to show the postfix and prefix in the review page. 

So if a custom input has a postfix value it is shown in the review

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![kg](https://user-images.githubusercontent.com/94350336/206656458-bd62dd9c-919b-44b2-9992-a826a97c2af0.png)

**Comment by anny320** [comment]
completed
