### ISSUE TITLE
Enable Configuration of Supporting Documents List

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#4321]
### **Problem statement**

Supporting documents list is currently a backend task done at the point of installation of the OpenCRVS. This makes it difficult to update the document requirements later in the product.
We would like to enable a view where a system administrator can easily configure the supporting document lists.

### **Proposed work**

(High-level overview of what we're building and why we think it will solve the problem).

### **Success criteria**

(The criteria that must be met in order to consider this piece of work a success)

### **User stories**

(How the product should work for various user types)

-

### **Scope**

(Current requirements)

### **Future work**

(Future requirements)

**Comment by jpye-finch** [comment]
closing as now possible with new form config
