### ISSUE TITLE
Change the frequency of the VSExport as it will not work for countries of Nigeria's scale

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#4327]
We are expecting 7m births per year for a country the size of Nigeria.  This would take 2800 hours to export if performed in one go.

The scheduler needs to instead export the previous day's data every night, and append to the end of a .csv file for 1 month.  At the end of a month, a new csv is created.  The table should have rows for monthly data, instead of years and use pagination for previous years.

The copy should inform the user that a large CSV cannot be opened in Excel and should therefore be opened in a statistical program such as [RStudio/Posit](https://posit.co/)

### Dev tasks

- [x] Update VSExportGenerator to export the previous day's data every night, and append to the end of a .csv file for 1 month.  At the end of a month, a new csv is created.  This may require 2 schedulers, one will run every night to append the csv file and another one will run every month to upload the file in the minio server and entry that on mongo.  Update crontab appropriately.
- [x] Update Vital Statistics UI so that it includes rows for every month and has pagination.  Update queries as necessary to support pagination
- [x] Change the copy in the UI from:

"The previous year's vital statistics data (based on vital event registrations occurring within that year) will become available for you to export as of 1st January."

to

"The previous month's vital statistics data (based on vital event registrations occurring within that month) will become available for you to export as of the 1st of every month.  Large CSV files cannot be opened in Excel and should therefore be opened in a statistical program such as [RStudio/Posit](https://posit.co/)."
- [x] Address the copy requirements, and column issues described in the comments below

- [x] Shared volume to temporarily store the monthly generated data
- [x] Update the playbooks
- [x] update the backup and restore scripts

**Comment by euanmillar** [comment]
@sadmananik can you additionally perform these minor updates on the CSV columns and headers please?

**Renaming of header for birth CSV file:**

“OFFICE LOCATION” should be the first column
“PLURALITY OF PREGNANCY” to “Type of birth”
“BODY WEIGHT MEASURED” to “Weight at Birth”
“ATTENDANT TITLE” to “Attendant at birth”
“PRESENT AT REG” - remove this column as this is no longer used
 “MOTHER NATIONALITY” column missing
“FATHER NATIONALITY” column missing
“INFORMANT NATIONALITY” column missing
“INFORMANT OCCUPATION” - remove this column as this is no longer used
“INFORMANT RELATIONSHIP” - remove this column as this is no longer used

**Renaming of header for death CSV file:**

DECEASED NATIONALITY” column missing
When HEALTH CENTER is selected, “DEATH CITY”, “DEATH STATE” & “DEATH DISTRICT” should be blank. Similarly when “DEATH CITY”, “DEATH STATE” & “DEATH DISTRICT” is selected “HEALTH CENTER” should be blank
“OFFICE LOCATION” should be the first column
“UNCERTIFIED MANNER OF DEATH” to “Manner of death”
Sequence of column should be - CAUSE OF DEATH ESTABLISHED > SOURCE OF CAUSE OF DEATH > VERBAL AUTOPSY DESCRIPTION> MEDICALLY CERTIFIED CAUSE OF DEATH DESCRIPTION. Currently the sequence is- 
VERBAL AUTOPSY DESCRIPTION
CAUSE OF DEATH METHOD
CAUSE OF DEATH ESTABLISHED

 Remove columns- CAUSE OF DEATH, NUM MALE DEPENDENTS ON DECEASED, NUM FEMALE DEPENDENTS ON DECEASED
INFORMANT NATIONALITY” column missing
“INFORMANT MARITAL STATUS” , “INFORMANT OCCUPATION” & “INFORMANT RELATIONSHIP”- remove this column as this is no longer used

**Comment by sadmananik** [comment]
@euanmillar Should I also remove 'INFORMANT MARITAL STATUS', and 'INFORMANT EDUCATION' for birth declaration? Since these are not available in the form definition.

**Comment by sadmananik** [comment]
Regarding `When HEALTH CENTER is selected, “DEATH CITY”, “DEATH STATE” & “DEATH DISTRICT” should be blank. Similarly when “DEATH CITY”, “DEATH STATE” & “DEATH DISTRICT” is selected “HEALTH CENTER” should be blank ` task

Previously this was like this but then I changed it on this [ticket](https://github.com/opencrvs/opencrvs-core/issues/4319)

Can you please ensure? Is it okay to have “DEATH CITY”, “DEATH STATE” & “DEATH DISTRICT”  even when HEALTH CENTER is selected?

**Comment by euanmillar** [comment]
@Zangetsu101 @sadmananik I deployed this to the migrate server.  There are 298 birth registrations that I registered on the day I deployed it.  But the Birth_Report.csv is blank.
