### ISSUE TITLE
Merge Ansible playbooks

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#4347]
Currently, we have separate playbooks for different cluster sizes with 1, 3 and 5 nodes and a lot of repeating configurations in each file. 99% of the files, however, are identical. Refactoring options:

1. Let's only have one .ini file and detect the number of servers based on that and then dynamically apply cluster-size specific options
2. Let's keep three separate playbooks but move ansible tasks to their separate files only keeping imports to these tasks + the cluster-size specific options in the main playbooks

https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse.html

**Comment by Kalpesh-18** [comment]
I would like to work on it
