### ISSUE TITLE
Configure Document Filter Scrolling on the Review Page On/Off

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#4348]
### **Problem statement**

Currently, the OpenCRVS review page enables automatic scrolling of the documents are you review details. Some countries have requested the option of manual selection of the supporting documents on the review page instead of autoscrolling
### **Proposed work**

(High-level overview of what we're building and why we think it will solve the problem).

### **Success criteria**

(The criteria that must be met in order to consider this piece of work a success)

### **User stories**

(How the product should work for various user types)

-

### **Scope**

(Current requirements)

### **Future work**

(Future requirements)

**Comment by jpye-finch** [comment]
closind as done
