### ISSUE TITLE
Image not loading in mobile view

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4353]
**Bug description:**
Image not loading in mobile view

**Steps to reproduce:**
1. Login as FA/ RA/ Registrar from mobile
2. Click Download> assign> review to any record that have supporting document
3. Click to the supporting document link

**Actual Result:**
Image not loading in mobile view

**Expected result:**
 should be able to view the supporting document image from mobile and tab

**Screenshot:**
![image not loading in mobile view.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/a0e57f7e-d0d9-499b-b0b1-72051f0ac7e9)

**Tested on:**
browserstack

**Comment by Zangetsu101** [comment]
Possibly the document viewer for mobile view is not using the `MINIO_URL` for the image src

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![4353 fixed](https://user-images.githubusercontent.com/94350336/209523490-1350827d-bafb-410b-9a45-f4cb66dfca4d.png)

**Comment by anny320** [comment]
Completed
