### ISSUE TITLE
Track issuance of certificate

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4354]
https://www.notion.so/opencrvs/Track-issuance-of-certificate-2c4f0429009d41769c06f9d6675e7dd2

### **Problem statement**
Currently we support the option to print a certificate in advance. This means the Registrar or agent can prepare all certificate (print and sign) in advance of collection by the informant. As it has been observed that some office have a certificate collection day. 

However OpenCRVS does not track and audit the issuance of the certificate. Confirming that the certificate has been given to the informant or someone else and payment taken. 

### **Proposed work**
- Create a new workqueue 'Ready to issue'
- New status: ‘Issued
- New audit action. ‘Issued’
- Any records certified in advance of collection move to this workqueue.
- Ready to issue workqueue is synced for all user. Conflicts management is not a concern. So any user can click Issue, complete the flow and send the record to the Outbox.
- On collection by the Informant the Registrar or Reg Agent find the record and complete the issuance

# Process
|  |  |
| --- | --- |
| Actors and permissions | Reg Agent, Registrar |
| Pre-condition: What activities must take place before the use case can be started? | Record is in ready to print |
| Triggers: What event starts the use case? | Record is printed in advance, Bulk printing |
| Standard flow: What are the user actions and system responses that will take place during execution of the use case under normal, expected conditions? | 1. User clicks prints 2. User select print in advance 3. User previews certificate and prints 4. Record moves to Outbox 5. Record is processed and moved to Ready to issue 6. Informant comes to collect certificate 7. User clicks Issue 8. Confirms ID 9. Collects payment 10. Click issues 11. Record goes to Outbox 12. Record is processed and status updated to Issued |
| Post-condition: What marks the end of the use case? | Record status set to Issued  |
| Flow variations and responses: What variations or error conditions could occur and how does the system respond? |  |

### **Future work**
- Receipt design configuration
- Certified copies printing in advance

**Comment by euanmillar** [comment]
@jpye-finch I think this should go to In Design column until we talk about it.  I have a bunch of questions.

**Comment by euanmillar** [comment]
existing collector flow should also track issuance
