### ISSUE TITLE
As a Registrar or Reg Agent I want to issue a certificate printed in advance

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4357]
### Description
- We need to audit the issuance of a certificate
- Adds a new workqueue 'Ready to issue'
- If a certificate is printed in advance the record is moved to this work-queue
- Capture who is collecting, ID check if informant
- Payment collection and print reciept

### Acceptance criteria

GIVEN I print a certificate in advance
WHEN I click confirm
THEN change the record status to Certified and move to Ready to Issue

GIVEN a record is in the Ready to issue work-queue
WHEN I click Issue
THEN navigate to the [Issue certificate workflow](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=12120%3A93278&t=JtZ3x2q7KXbfDHaA-1)

GIVEN I select Issue to informant
THEN navigate to the [ID Check](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=12120%3A93204&t=JtZ3x2q7KXbfDHaA-1)

GIVEN I select Issue to someone else
THEN navigate to the [Collector details](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=12120%3A93141&t=JtZ3x2q7KXbfDHaA-1)

GIVEN I have checked the id or captured the collector details 
THEN navigate to[ Collect payment ](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=12120%3A93247&t=JtZ3x2q7KXbfDHaA-1)

GIVEN I there is no payment required
THEN navigate to[ No payment required screen ](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=12130%3A98006&t=JtZ3x2q7KXbfDHaA-1)

GIVEN I click Issue certificate
THEN move the record to the Outbox and update the record audit

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=12120%3A93131&t=JtZ3x2q7KXbfDHaA-1
### Dev tasks

- [x] Create a new workqueue "Ready to issue" which would show the Certified records. Change the workqueue query as required to accommodate this change. Show the workqueue table according to the design. - 2
- [x] Amend the record audit for the new certified state of the declaration - 2
- [x] Create a new issue certificate flow similar to print certificate flow. Create a Collector form which would take the details if someone else is selected. - 2
- [x] Build the proof of ID view, show modal if no id match selected. - 2
- [x] Show the collect payment view with the appropriate fee according to the registration delay - 2
- [x] Clicking issue Certificate would set the action of the declaration to be ISSUE_CERTIFICATE from #4355 - 1

**Comment by jpye-finch** [comment]
duplicate...

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/224958566-71646800-e72d-482c-b5eb-bb548abb1853.mp4

**Comment by anny320** [comment]
completed
