### ISSUE TITLE
As a user I want to audit when a certificate was issued

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4362]
### Description
- Adds new audit line item 'Certified and issued' 
- Adds new audit line item - 'Issued' 

### Acceptance criteria

GIVEN a record is printed and issued 
THEN show the audit line item Certified and issued

GIVEN a record is printed in advance
THEN show the audit line item Certified

GIVEN a record is printed in advance
WHEN the record is issued
THEN show the audit line item Issued

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=10381%3A64768&t=4VbkamxwtyZTwWnj-1

### Dev tasks

- [ ] Task 1

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/224932459-cc771680-059c-4093-b478-1c835b14ee93.mp4

**Comment by anny320** [comment]
completed
