### ISSUE TITLE
Delete integration

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#4366]
- [x] Gateway mutation
- [x] user-mgnt handler
- [x] delete option in the 3 dot menu
- [x] Copy button

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/209291498-d9dfa9aa-d70a-4c57-8783-cf0e5c1725eb.mp4

**Comment by anny320** [comment]
Completed
