### ISSUE TITLE
Add certificate handlebars for all individual address fields

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#4373]
We need a mapping / template function so that we can create certificate handlebars for every address field.

We need a template block for every address field in the primary and secondary address function
https://github.com/opencrvs/opencrvs-core/blob/a3e1850ee06f71a0dd87d24e5581a269cbf5932b/packages/client/src/forms/configuration/administrative/addresses.ts#L632

We need a template block for every address field in the lace of event function

https://github.com/opencrvs/opencrvs-core/blob/a3e1850ee06f71a0dd87d24e5581a269cbf5932b/packages/client/src/forms/configuration/administrative/addresses.ts#L1511

**Comment by yeasinhossain-dsi** [comment]
Yes, Your are right @euanmillar seems like i missed the part for address no 2.

**Comment by Zangetsu101** [comment]
Done in #4593
