### ISSUE TITLE
Configure the date format

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4375]
### Description
- Adds date format configuration to App Config
- Support two formats: DD Month YYYY, Month DD, YYYY
- Default to DD Month YYYY

Pages:
- Declaration review
- Record Audit
- User Audit
- ID Check in certificate print
- ID Check in correct record
- Certificate

### Acceptance criteria

GIVEN I am a National System Admin
WHEN I set the date format
THEN update all instance to my chosen date

### Design
tbd

### Dev tasks

- [ ] Task 1

**Comment by rikukissa** [comment]
Implementation should be done with a i18n item in client.csv

**Comment by rikukissa** [comment]
Closing in favour of https://github.com/opencrvs/opencrvs-core/issues/6791
