### ISSUE TITLE
National ID integration - form pre-population

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#4389]
### **Problem statement**
- When an integration is done with a national ID system, the details are not prepopulated in the form.
- Currently one has to always enter the parents' details afresh when registering additional children from that parent. While this is time-consuming, it also limits the possibility of linking parents' children's details in the system which would be necessary for future features like person-centricity.
- We would like to enable form pre-population after the National ID reference check (if systems are integrated)
* Request recommended by Somaliland

### **Proposed work**

- If we have already captured a mother's details when registering a second child from the parent the proposal is to prepopulate the mother's details from the ID check
### **Success criteria**

(The criteria that must be met in order to consider this piece of work a success)

### **User stories**

(How the product should work for various user types)

-

### **Scope**

(Current requirements)

### **Future work**

(Future requirements)

**Comment by euanmillar** [comment]
This is enabled by the MOSIP integration using their standards. For any other NID system, this is a unique country requirement.
