### ISSUE TITLE
When a registrar's role is changed to field agent, the current role of the user is shown in history beside old user's actions

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4391]
**Bug Description:**
When a registrar's role is changed to field agent, the current role of the user is shown in history beside old user's actions.
_Note: This issue also appears when  registrar's role is changed to Registration agent_

**Steps to reproduce:**
1. Login to any registrar
2. Create a birth or death application
3. Logout 
4. Login to National system admin
5. Go to team
6. Click 3 dot menu> Edit user beside that registrar name
7. Click change beside role> Change to Field agent> select type
8. Click confirm
9. Logout
10. Login to the newly edited Field agent
11. Go to Sent for review
12. Download> click on that record
13. Observe the history

**Actual result:** 
shows field agent has registered that record

**Expected result:**
should show registrar has registered that record as that user was registrar at the time when the action occured

**Screenshot:**
![a.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/e65635f1-09c2-44e3-b225-00f918a864ec)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by euanmillar** [comment]
I started this but I could not finish.  The PR is here: https://github.com/opencrvs/opencrvs-core/pull/4401

Read my comment

**Comment by SyedaAfrida** [comment]
**Bug:**
after a user's role is changed, cannot create a birth/ death declaration

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/209633451-c1b77351-f5be-4f16-8c0a-a3f5e7ed17cf.mp4

**Comment by anny320** [comment]
Completed
