### ISSUE TITLE
System crash occurs when a field agent's role is changed to any other role 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4395]
**Bug description:**
System crash occurs when a field agent's role is changed to any other role 

**Steps to reproduce:**
1. Login as Field agent
2. Create a birth / death application
3. logout
4. Login to National system admin
5. Go to team
6. Change the field agent's role to RA/ registrar/ system admin
7. Logout
8. Login to the newly edited role

**Actual result:**
System crash occurs when a field agent's role is changed to any other role 

**Expected result:**
field agent should be able to change role 

**Screen recording:**
https://images.zenhubusercontent.com/91778759/e7348dea-2be6-4552-8ee6-2fb9c9ef1726/system_crash_when_changed_role_from_fa_to_ra_or_reg.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/208379383-979d63a0-8857-4c10-b973-bef9c9fe75d8.mp4

**Comment by anny320** [comment]
completed
