### ISSUE TITLE
Custom Field in form configuration becomes conditional field

### ISSUE THREAD

**Issue by yeasinhossain-dsi** [opencrvs/opencrvs-core#4410]
- [x] Bug 1: The custom field becomes conditional field:
1. Go to Configuration -> Declaration -> Birth
2. Add a custom field & save the draft. 
3. Edit the draft
4. Refresh the page

You will see that the newly added field is a conditional field even through you didn't add it as conditional field.

- [x] Bug 2: Certificate handlebars gets appended with Section & event
1. After you Completing the steps on bug 1 above, make the field non-conditional field click save. Do it few times, you will see on every iteration the handlebars is growing like following image:
![Screenshot from 2022-12-06 16-52-41](https://user-images.githubusercontent.com/8198236/205892257-434fe49e-3395-4d4c-87f4-6a6e5c3a54cb.png)

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/208405525-9835d479-5099-4cef-befe-54348de0f011.mp4

**Comment by anny320** [comment]
completed
