### ISSUE TITLE
As a user I want to preview the certificate with the QR code

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#4416]
### Description
- adds the QR code to the certificate preview
- when configure the certificate then the designer/admin can choose where to place the QR
- add documentation on how to do this 

### Acceptance criteria

GIVEN I am on the certificate preview page
THEN I can see the QR code in my chosen location

### Dev tasks
https://github.com/opencrvs/opencrvs-core/blob/develop/packages/client/src/forms/configuration/README.md#L1

- [x] Expose a QR code image data as a template placeholder for certificates to enable following definition to work in a certificate template.
```
<image
  width="54" height="56"
  x="53.8555" y="499.5"
  xlink:href="{{ qrCode }}"
/>
```
This should render a QR code onto the certificate.

>Placeholder variables are `{{ childName }}` style variables than can be used in the birth / death certificate templates [(docs)](https://documentation.opencrvs.org/setup/4.-functional-configuration/4.4-configure-a-certificate-template). Definitions for available variables are defined in `default.ts` file under `mapping.template` [(here)](https://github.com/opencrvs/opencrvs-core/blob/develop/packages/client/src/forms/configuration/default.ts#L558-L592). 
The purpose of these `mapping.template` definitions are to act as transformers that take in all the form data, and select the field that we want to expose as a template variable. 

**Note that a similar definition has been made in OpenCRVS Nigeria implementation:**
  - [Template variable definition](https://github.com/opencrvs/opencrvs-core/blob/release-v1.1.0-nigeria/packages/client/src/forms/configuration/default.ts#L104-L107)
  - [Transformer implementation](https://github.com/opencrvs/opencrvs-core/blob/release-v1.1.0-nigeria/packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts#L526-L543)

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![4416 fixed](https://user-images.githubusercontent.com/94350336/229472631-ae6546c9-de8e-4912-aaeb-dee9007f6ad2.png)

**Comment by jpye-finch** [comment]
@SyedaAfrida can this issue be closed? I think so.

**Comment by SyedaAfrida** [comment]
Yes This ticket is fixed. So closing this ticket
