### ISSUE TITLE
As a user I want to verify a certificate

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#4418]
### Description
- Adds a certificate verification page
- Navigable from the certificate QR
- A valid QR shows the Valid Alert
- An invalid QR shows the Invalid Alert
- A prompt to check domain to stop domain spoofing. The app populates the address with the country domain. 
- Domain check Alert
- After 1 minute show Toast prompt to close window
- Page timeout after 10 minutes
- Desktop and mobile designs

### Acceptance criteria

GIVEN a user scans the QR code 
[THEN a show the loading page
](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=11611%3A87763&t=bYFZ9c4NIBoO60Bp-1)

GIVEN the page has load
THEN show the partial record data

GIVEN a the QR is valid
[THEN a show valid Alert
](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=10573%3A105398&t=bYFZ9c4NIBoO60Bp-1)

GIVEN a the QR is invalid
THEN a [show invalid Alert](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=11652%3A91142&t=bYFZ9c4NIBoO60Bp-1)

GIVEN the certificate preview page is opened from the app
AFTER 1 minute
THEN show the Toast prompt to close

GIVEN the certificate preview page is opened from the app
AFTER 10 minute
THEN timeout the page

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=10573%3A105397&t=bYFZ9c4NIBoO60Bp-1

### Dev tasks

Notice that many of the tasks here have been done in the Nigeria implementation. Inspiration can be gotten for example from [here](https://github.com/opencrvs/opencrvs-core/blob/release-v1.1.0-nigeria/packages/client/src/views/PrintCertificate/VerifyDetails.tsx).

- [x] Create a new view: `/verify-certificate/<id>`. This view can be accessed without the user being logged in.  **(1)**
- [x] Create a new GraphQL query (to packages/gateway) for fetching record details by composition id. This query should be enabled for also users that haven't logged in. You can only get the details needed for verifying a certificate through this query. Create a temporary JWT for the user querying the data so they can access workflow and other services (3) 
- [x] Fetch the record data by the id in the url. If the record cannot be found, show "Invalid QR code" error. Only show the error on 404 error from the backend. Other errors should be handled with a more generic "Something went wrong" type of messaging, so valid certificates never get flagged as invalid. (2)
- [x] Render all details of the record onto the page as per Figma design (2)
- [x] After 1 minute show a toast that prompts the user to close the tab (1)
- [x] After 10 minutes, clear the view and show timeout page (1)

**Comment by SyedaAfrida** [comment]
@anny320 the bugs for this ticket is mentioned in #5002 , #5003  & #5006 . So this ticket can be closed.

**Comment by anny320** [comment]
Completed
