### ISSUE TITLE
As a registrar, I want to check for potential duplicates before registering a record

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4442]
### Description
- adds duplication check for registrars
- 

### Acceptance criteria

GIVEN I confirm to Register a record
WHEN the record is in the outbox
THEN first check for duplicates 'Checking for duplicates...'

GIVEN there are no potential duplicates
THEN show the messaging 'Registering...'

GIVEN the potential duplicate is in Ready for review
THEN I can see the duplicate icon

GIVEN I am in the duplicate record audit
THEN I can see the potential duplicates it matches with (Alert box)

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7087%3A1031&t=bVvysRXDt9MgtZe2-1

### Dev tasks

branch: **potential-duplicates**

- [x] Create an endpoint to search-microservice to ask for birth duplicates https://github.com/opencrvs/opencrvs-core/pull/4054/commits/e3ac0344081bd7ed29ac9c1b191fd46d0cde8480#diff-eff532c90ecfcc41ee10077c59deee895f66c168247f0af31e03b5c10fd0f246 2
- [x] In gateway, ask from the search-microservice if the birth duplicate exists. Return a response to frontend 1
- [x] After a record has been created, toast the user with a link to the potential duplicate 2

**Comment by euanmillar** [comment]
@rikukissa can you point me to the PR that you worked on for Nigeria to implement this please?

**Comment by euanmillar** [comment]
@jpye-finch as we mentioned before the break, the Outbox messaging cannot be done as there is no communication between the backend and front end regarding the stage of the backend process ... So we muct remove these acceptance criteria:

**GIVEN I confirm to Register a record
WHEN the record is in the outbox
THEN first check for duplicates 'Checking for duplicates...'

GIVEN there are no potential duplicates
THEN show the messaging 'Registering...'**

**Comment by naftis** [comment]
Can we test the de-duplication logic? Is there a way to make unit tests to clearly show what kinds of records get marked as duplicates, and what kinds of don't? Could potentially be useful also in the future, if different countries have different de-duplication logic.

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
