### ISSUE TITLE
As a National System Admin, I want to view the roles for each system role

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4445]
### Description
- adds a new configuration page 'User roles'
- Available for National System Admin

### Acceptance criteria

GIVEN I am a National System Admin
WHEN I click on User roles in sideNav
THEN present the User roles page

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7625%3A21530&t=yWlpvBgCMc6CWnT0-1

### Dev tasks

- [x] Create a user-mgnt migration which will change the `role` field of the user to `systemRole` and change the `type` field to be `role` instead. The value of the role would need to hardcoded for the different users and for field agents it would be a bit different as it already has a value for that field. The type of the `role` field will be like the type given below but for `systemRole` we should use an enum. Use #4315 as the base branch for this PR
- [x] We also need to migrate the `Role` collection, change the name of the collection to be `SystemRole` and `type` to be `roles`. The title field is not used anymore so we should be able to remove that as well -3
The type of the new role field should be similar to this:
```ts
type Role = Array<{
  lang: string
  label: string
}>
```
- [x] Refactor all the `role`'s used in the codebase to `systemRole` and `type` to `role`. - 2
- [x] Add `User roles` option in navigation
- [x] Use the `getRoles` query to render the User roles view. We should probably refactor this to `getSystemRoles` - 3
- [x] Showing the roles in a different language in this page needs to be handled manually as the reducer won't have the intlMessageDescriptors at this point. So use a function which takes in the Role data and currently selected language to show the roles in the view

**Comment by SyedaAfrida** [comment]
**Bug:**
1. Except for local and national system admin, Invalid data are showing for roles in team page and user audit page
![bug 4- UR 2](https://user-images.githubusercontent.com/94350336/218712316-360a61f0-1a65-4a57-a468-66b3d9c4231a.png)
![bug 4- UR 1](https://user-images.githubusercontent.com/94350336/218712333-c672208f-78a8-444c-82a1-f96ec4191b44.png)

2. broken page when view FA from performance
![user role bug1- broken page when view FA from performance](https://user-images.githubusercontent.com/94350336/218712559-ca230fc4-4e60-4929-b56f-8020c776f222.png)

3. In performance registrar number is always showing 0 in stats
![user role bug 3- In performance registrar number is always showing 0 in stats](https://user-images.githubusercontent.com/94350336/218712732-c9432e16-ec4a-4d69-a4c5-141976ff6690.png)

4. English & french role not updated in settings page
![user role bug 5- eng   french role not updated in settings page](https://user-images.githubusercontent.com/94350336/218713041-32fb5d65-8a3c-4f24-9d61-2961ba9f884c.png)

**Comment by SyedaAfrida** [comment]
@anny320 all the bugs for this ticket is fixed, so this ticket can be closed.

https://user-images.githubusercontent.com/94350336/222130102-f2a72b46-7177-47d1-8543-4baa1aa64591.mp4

![usrad fixed](https://user-images.githubusercontent.com/94350336/222130188-3e8550e7-cfb6-4371-a5ac-596acaea7e1d.png)
