### ISSUE TITLE
As a National System Admin, I want to change or add a role for a system role

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4446]
### Description
- adds option for adding and editing existing roles

**updated requirements 4/2/2023**
- In the create new user page, hide/remove the system role column and only show the roles column 
- In the profile icon on the dashboard, update from the previous system role to the new role e.g instead of a field agent- Village leader/or police office /health worker. Apply these changes for the following roles if applicable-  Field Agent, Registration Agent, Registrar, National Registrar and Performance Manager

### Acceptance criteria

GIVEN I am a National System Admin
WHEN I click change on a system role
THEN present the system role model

GIVEN the role edit model is open
[THEN present the existing roles](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=10606%3A77598&t=yWlpvBgCMc6CWnT0-1)

GIVEN the role edit model is open
WHEN a role has already been added
THEN disable the field

GIVEN i click on the edit icon
THEN enable the field

GIVEN I enter a new role
WHEN I click on the plus button
THEN disabled the field
AND add a new input field and plus button (so I can add another)
Given I am a system admin on the create a new user page
when I click select role
THEN show a dropdown with only role types

Given I am a FA/RA/R/NRA/Performance manager
WHEN I click the profile  icon on the dashboard
THEN user sees my type example Village leader/or police officer /health worker instead of the system role Field Agent

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=10606%3A77598&t=yWlpvBgCMc6CWnT0-1

#### Frontend
- [x] Let's create a `useModal` hook similar to this [blog](https://www.esveo.com/en/blog/O5).
- [x] Clicking change button would open a modal which will use the roles of the current row and clicking apply would return the updated roles. - 2
The modal will maintain a internal state which would use the given roles as it's default value and render the view with the components below:
- [x] We will need a language select modal to get the roles in different languages. (There is no design regarding this now, we can do something similar to custom field tools) - 2
- [x] Create a customized input component which will take value as a prop and an onChange function to notify about change. Clicking the edit button should focus on the input field. When the input field has focus, the edit button should be hidden. - 2
- [x] The create role component should just add a new role to the array if the value of the input field is not empty when the plus button is pressed. - 1
- [x] The apply button should be disabled if the roles prop is equal to the internal roles array state. - 1/2

#### Backend
- [x] Create a mutation which would take the id of a  systemRole and the updated roles. Restricted to national system admin
- [x] Create an endpoint in user-mgnt to update the roles of a particular systemRole. -3

#### Merger
- [ ] Connect the new mutation with the frontend. Change the roles in the view on success and show an error toast on failure - 2

**Comment by euanmillar** [comment]
@anny320 @eduffus @jpye-finch what do we do with translations?  In your absence ... we have decided to add an English / French select in the modal and disable the Apply button until all translations are entered, exactly as we do in Form Config, add custom field.

**Comment by anny320** [comment]
about the translations, this will do for now until we migrate to a content management system @Zangetsu101  New requirement for the changes to the create new user page have been added above in the description.

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/218750410-4d9c3ffc-28b0-400f-a66d-f3e8e1181695.mp4

**Comment by anny320** [comment]
Completed
