### ISSUE TITLE
As a National System Admin or Local System Admin, I want to select from a list of added role types when creating a new user

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4447]
### Description
- add role select in New User creation
- same as Field Agents. Applied to all users
- dropdown list dependent on User roles configuration
- updates labels to System role and Role

### Acceptance criteria

GIVEN National System Admin or Local System Admin
WHEN I select the system role (eg. FA, RA, Reg)
THEN a conditional select field shows to select the role

GIVEN National System Admin or Local System Admin
WHEN I am on the review page
THEN I can see the system role and role selected

### Design

![Screenshot 2022-12-21 at 10.12.35.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/9aa74638-3e85-44f2-8d40-064a1b9dcefb)

### Dev tasks

Lets deprecate the terms type in the code and role becomes systemRole.  Lets do a migration too

Essentially in the form "Role" becomes "System role" and "Type" becomes "Role" and is required for every system role.

- [x] In userFormReducer on offine ready action, instead of deserializing the form, fetch the  systemRoles, dispatch a ROLES_LOADED action with the roles data derived from the systemRoles, then generate the form using the systemRoles and roles data and finally deserialize the form. - 2
- [x] Remove/Refactor PROCESS_ROLES, UPDATE_FORM_FIELD_DEFINITIONS, FETCH_USER_DATA, UPDATE_DEFINITIONS_AND_FORM_DATA actions as needed. - 1
- [x] Create a generic function to convert role data into intlMessageDescriptor - 1
- [x] On the ROLES_LOADED action, in the i18n reducer generate roles messages and add them to the reducer. - 2

The systemRole field would be a SELECT_WITH_OPTIONS field with the options generated from the data returned from the query.

The role field would be a SELECT_WITH_DYNAMIC_OPTIONS field with the dependency as the systemRole field and options value being an object with each systemRole value mapped to the role value array. Checkout the IDynamicOptions type. Use the previously declared function to get messageDescriptors

**Comment by SyedaAfrida** [comment]
**Bug:**
 Though creating user is working, there is an error when try to edit a user

https://user-images.githubusercontent.com/94350336/218747507-6da53eb3-cde2-478e-bf03-861b82fef035.mp4

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/222356988-cbe38893-aed3-490b-9387-f6e689a347a0.mp4

**Comment by anny320** [comment]
completed
