### ISSUE TITLE
As a user, I want to see the users role when auditing a record or user

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4448]
### Description
- replaces the **System role** description show in user audit and in the record audit table with the **Role**
- eg.instead of Field Agent. We show Healthcare Worker

### Acceptance criteria

GIVEN I am on the record audit page
WHEN reviewing the history
[THEN I can see the role of the user who performed the action. (not System role)
](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=10599%3A75712&t=yWlpvBgCMc6CWnT0-1)

GIVEN I am on the user audit page
WHEN reviewing their summary details
[THEN I can see the role of the user who performed the action. (not System role)
](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=10443%3A66683&t=yWlpvBgCMc6CWnT0-1)

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=10599%3A75712&t=yWlpvBgCMc6CWnT0-1

### Dev tasks

- [x] Update RecordAudit and UserAudit to show the new Role value using the generic function to get the intlMessageDescriptor, created in the previous ticket

**Comment by sadmananik** [comment]
This is done by [4616](https://github.com/opencrvs/opencrvs-core/pull/4649)

**Comment by SyedaAfrida** [comment]
**Bug:**
In record audit when language is changed to french, roles are still showing in english
![user role bug 6- in record audit when language is changed to french, roles are still showing in english-48](https://user-images.githubusercontent.com/94350336/218748176-fd221a3a-18a2-4e21-8adf-47134ddd85b0.png)

**Comment by SyedaAfrida** [comment]
**Bug:**
Old bug not fixed yet. In record audit when language is changed to french, roles are still showing in english
![4448 not fixed](https://user-images.githubusercontent.com/94350336/222141571-75b1a97d-bc13-4c7c-86f4-19b8027da0fc.png)

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![4448 fixed](https://user-images.githubusercontent.com/94350336/229778100-0863cdfa-968c-4b8d-9d54-1f7a4e74f9a1.png)
