### ISSUE TITLE
Unable to assign any in progress record and after that error occurred also to able to assign record of any other workqueue

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4449]
**Bug description:**
Unable to assign any in progress record and after that error occurred also to able to assign record of any other workqueue

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Go to in progress> field agent
3. Click download and observe

**Actual result:**
record keeps on downloading . after that error occurred also to able to assign record of any other workqueue

**Expected result:**
User should be able to download/ assign to any in progress record

**Screen recording:**
https://images.zenhubusercontent.com/91778759/dd7873b4-6f6f-4129-8894-0a5fcac896e8/unable_to_assign_to_any_in_progress_record_and_later_unable_to_assign_record_of_any_other_workqueue_also.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by yeasinhossain-dsi** [comment]
Seems like the bug no longer exists.

**Comment by Zangetsu101** [comment]
@yeasinhossain-dsi Could you try to reproduce this on staging please? I think it not be appearing in dev environment

**Comment by SyedaAfrida** [comment]
Was able to generate this bug all over again. Check the bug with the tracking ID-DZH5TUX in QA environment
![image](https://user-images.githubusercontent.com/94350336/209627722-ec42a55a-9acf-4318-b96b-b244e744fefa.png)

**Comment by SyedaAfrida** [comment]
This bug is not fixed yet.

https://user-images.githubusercontent.com/94350336/213644949-97ec7d34-1fb1-448d-a275-29ac42653e4b.mp4

**Comment by Zangetsu101** [comment]
Should be fixed with #4593

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/213689570-eb71a26b-0160-4ddb-bf96-dad65fef618f.mp4

**Comment by anny320** [comment]
Completed

**Comment by anny320** [comment]
Completed
