### ISSUE TITLE
Resolve CRITICAL warning before Elasticsearch 8

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#4456]
```{"type": "deprecation.elasticsearch", "timestamp": "2022-12-13T15:31:18,341Z", "level": "CRITICAL", "component": "o.e.d.r.a.d.RestIndexAction", "cluster.name": "docker-cluster", "node.name": "14a0180ee2ba", "message": "[types removal] Specifying types in document index requests is deprecated, use the typeless endpoints instead (/{index}/_doc/{id}, /{index}/_doc, or /{index}/_create/{id}).", "key": "index_with_types", "category": "types", "cluster.uuid": "N00ZOQveTZuJaJGNRouy7g", "node.id": "PdGjeZ2dS5aCV2e6aliVfA"  }```

**Comment by yeasinhossain-dsi** [comment]
Could not reproduce it or find it in the staging environment. A little more description on reproducing would help
