### ISSUE TITLE
As a Registrar, I want to compare a declaration against a flagged record

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4469]
### Description
Registrar is able to navigate to the review pages of a potential duplicate. The user user presented with the record and tabs to each of the matching records. This ticket os about building these pages. Subsequent tickets are about building the 'Not a duplicate' or 'Mark as a duplicate' flows.

- note the similarities with the current Review page (tho existing does not use < Frame /> or < Content .> yet)
- new < ListViewSimplied > variant required for the side by side view
- side by side DocumentViewer

### Acceptance criteria

GIVEN I am register
WHEN I click Review a potential duplicate is in my Ready for review
THEN navigate to the Potential Duplicate Review page

GIVEN I am on the Potential Duplicate Review page
WHEN I click on a tab of a matching record
THEN navigate to review page

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=11037%3A102980&t=MC7dYAnBJQvrJmiN-1

### Dev tasks

- [x] In gateway packages, for fetchBirthRegistration & fetchDeathRegistration also returns duplicate tracking ids [packages/gateway/src/features/registration/schema.graphql](https://github.com/opencrvs/opencrvs-core/blob/1a6b055dcc300b02ec1a0111f4aa3693ded98315/packages/gateway/src/features/registration/schema.graphql#L425) file, add `trackingId` at the duplicate field with compositionId. 
like this 
```ts
type DuplicatesInfo {
  compositionId: ID
  trackingId: String
}
duplicates: [DuplicatesInfo]
```

1

- [x] Refactor [ReviewSection.tsx](https://github.com/opencrvs/opencrvs-core/blob/1a6b055dcc300b02ec1a0111f4aa3693ded98315/packages/client/src/views/RegisterForm/review/ReviewSection.tsx) component to show duplicates trackingId in Tabs and also shows content for duplicates with text and buttons according to [design](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=11037%3A102980&t=3VeNLEqBHwJJUD4E-4). And hide the change Link action for duplicate view. Lets not implement the Accordion here.

2

- [x] When you are downloading a record in the "Ready for review" page, it should also call the `fetchRegistrationForViewing`  to fetch the details of the potential duplicates. - 2

- [x] In the potential duplicate review page, Clicking on the duplicate tracking id tabs will call [fetchRegistrationForViewing](https://github.com/opencrvs/opencrvs-core/blob/b2204e5454bab00534bb7addedf3096238398ac9/packages/gateway/src/features/registration/root-resolvers.ts#L152) query with fetch-policy [cache-first](https://www.apollographql.com/docs/react/data/queries/#cache-first) and show the compare of two declarations.
Make a functional component to show duplicate data comparison, that will take two declaration data and show compares side by side like this [design](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=10962%3A95718&t=3VeNLEqBHwJJUD4E-4). Ignore the accordion for now. - 3

After the #4371 is merged; 
- [ ] When we are downloading a declaration for review, we should prefetch the duplicates and store the registrations for offline viewing in IndexedDB

**Comment by naftis** [comment]
@jpye-finch Do we need an accordion here? For the scrolling experience it can be kinda janky if the user hides/shows the accordion. And would the user actually ever need to hide the data?
<img width="471" alt="image" src="https://user-images.githubusercontent.com/1322608/211543199-5aad1003-3504-4220-9b22-13c128fbb73f.png">

**Comment by euanmillar** [comment]
@sadmananik regarding the table ListViewSimplified. I think we need some specifications regarding how it should work on mobile.  As we have finished planning, I have asked @jpye-finch to consider that effort in a new ticket #4024 .  Perhaps that ticket needs documented and prioritised for a future sprint?  I think we need some specs around how labels, headings and values work in this mobile table clearly explained.  It has been suggested that the table could just overflow on mobile, but I think we would need that decided as currently this table does not overflow as you can see: https://ui-kit.farajaland.opencrvs.org/?path=/docs/data-list-view--plain-list FYI: @cinojopencrvs

**Comment by euanmillar** [comment]
@sadmananik the correct component to use is explained in the ticket #4582

**Comment by SyedaAfrida** [comment]
@anny320 the bug for this ticket is mentioned in #4927 . So this ticket can be closed
