### ISSUE TITLE
As a Registrar, I want to mark the record as not a duplicate

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4470]
### Description 
If the declaration is not a duplicate of any of the flagged records they can click the CTA. 'Not a duplicate' This opens a confirmation model. After confirming the user is then navigate to the declaration review page

_Updated copy:
This record was flagged as a potential duplicate of: JSDFKSN3, ADSKN2E3. Please review these existing records by clicking on each tracking ID  in the tab section to view a side-by-side comparison below, and confirm if this record is a duplicate.
### Acceptance criteria

GIVEN I am a Registrar
WHEN on the Potential Duplicate Review page
THEN I can click Not a duplicate

GIVEN I am a Registrar
WHEN I can click Not a duplicate
THEN open a confirmation model

GIVEN I have confirmed it is not a duplicate
THEN navigate the user to the declaration review page for them to register the record or send it for updates

GIVEN I have marked it not a duplicate
WHEN on record audit
THEN [show the action Marked not a duplicate
](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=10381%3A64768&t=lhvBLB4j8B8bIfzT-1)

### Design
Prototype: https://www.figma.com/proto/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?page-id=10864%3A84664&node-id=10967%3A96936&viewport=-2366%2C6102%2C0.58&scaling=min-zoom&starting-point-node-id=10864%3A84665
Press R to reset

### Dev tasks

- [x] In the potential duplicate review page, clicking on the 'Not a duplicate' button will open a modal. The modal will have a cancel button and confirm button.  
-  Clicking the Cancel button on the modal will close the Not a duplicate modal.
- Clicking the Confirm button will land the user on the review declaration page with a change links action to change potential duplicate values and register the declaration - 2
- [x] Registering or rejecting the application will remove the potential duplicates from the FHIR bundle & ElasticSearch. - 1

- [x] Modify the notADuplicate mutation (rename it to markEventAsNotDuplicate possibly) to send a payload to workflow with an action extension added to task.
- [x] Handle the event similar to #4286 in workflow.
- [x] In the review page when we mark a declaration as not a duplicate, we need to save a flag in the declaration which we will use to dispatch the notADuplicate mutation when registering the declaration from submission handler. Similar for the rejection event as well
- [x] The marked as not a duplicate action should show up in record audit and clicking it should open up modal according to design

**Comment by naftis** [comment]
Not a duplicate will not do a backend request. Only when the user reviews the document after confirming it's not a duplicate and registers or rejects it, `relatesTo` is being removed from FHIR.

**Comment by jpye-finch** [comment]
@naftis added extra AC for the record audit history table

**Comment by anny320** [comment]
@Zangetsu101  copy updated inside the ticket (updated copy) section

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is tested and can be closed

https://user-images.githubusercontent.com/94350336/227201182-796deee0-250c-4dbc-b512-1600f879001d.mp4

**Comment by anny320** [comment]
completed
