### ISSUE TITLE
As a Registrar, I want to mark a declaration as a duplicate

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4471]
### Description
If a Register deems a record is a duplicate then they are prompted to give a reason and select the matching record. The record can then be archived and audit of this decision is tracked

### Acceptance criteria

GIVEN I am a Registrar
WHEN I can click Mark as a duplicate
THEN open the Mark as a duplicate dialog

GIVEN the archive dialog is open
WHEN I enter a reason why it is a duplicate and select the matching record
[THEN enable the Archive button](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=11037%3A106020&t=MC7dYAnBJQvrJmiN-1)

### Design
Prototype: https://www.figma.com/proto/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?page-id=10864%3A84664&node-id=10967%3A96936&viewport=-2366%2C6102%2C0.58&scaling=min-zoom&starting-point-node-id=10864%3A84665
Press R to reset

### Dev tasks

- [x] In the potential duplicate review page, clicking on the 'Mark as duplicate' button will open a modal. The modal will have a drop-down to select duplicate with tracking id and a text box to describe the reason.  
-  Disable the `Mark as a duplicate` button on the modal if a duplicate with tracking is not selected from the drop-down list.
- Clicking the Cancel button on the modal will close the mark as a duplicate modal.

2

- [ ] After clicking the `Mark as a duplicate` button on the modal, dispatch `archiveDeclaration`. Modify the action to take in an optional duplicateTrackingId parameter. In submissionmiddleware, pass that id to both markEventAsDuplicate and archive declaration mutation.
The work for marking as a duplicate has already been done here #4286 for the backend part. We need to add the trackingId in this task.

2

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
https://www.loom.com/share/acef3dad28224830a26f224829bd65c3
