### ISSUE TITLE
As a user, I want to view if a record has been reviewed as a potential duplicate (Record/User audit)

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4472]
### Description
On the Record Audit and User Audit pages we update the History table to any flagged potential duplicates by the System and audit any action taken by a Registrar. 

New Actions are:
- Flagged as a potential duplicate
- Archived (duplicate)
- Marked not a duplicate

### Acceptance criteria

[**Flagged as a potential duplicate**
](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=10381%3A64768&t=jdVOMtLcr80Hzc9p-1)GIVEN the System flags a potential duplicate 
WHEN on the Record Audit page
[THEN I can see a line item action 'Flagged as a potential duplicate'
](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=11061%3A88832&t=jdVOMtLcr80Hzc9p-1)
GIVEN the System flags a potential duplicate 
WHEN I click on 'Flagged as a potential duplicate'
THEN show a dialog model and list the tracking ids of the potential duplicates

[**Marked not a duplicate**
](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=10381%3A64768&t=jdVOMtLcr80Hzc9p-1)GIVEN the Registrar marks the record as not a duplicate
WHEN I on the Record Audit page
THEN I can see the Action 'Marked not a duplicate'

GIVEN the Registrar marks the record as not a duplicate
WHEN I on the User Audit page
THEN I can see the Action 'Marked not a duplicate'

[**Archived (duplicate)**
](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=11060%3A88459&t=jdVOMtLcr80Hzc9p-1)GIVEN the Registrar marks the record as a duplicate
WHEN I on the Record Audit page
THEN I can see the Action 'Archived (duplicate)'

GIVEN the Registrar marks the record as a duplicate
WHEN I on the User Audit page
THEN I can see the Action 'Archived (duplicate)'

GIVEN I have clicked on 'Archived (duplicate)'
[THEN I open a dialog with to show any comments, matched record, and the marked as a duplicate Pill flag
](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=9784%3A71672&t=jdVOMtLcr80Hzc9p-1)

### Dev tasks

- [ ] Write a migration to add 2 channels in openhim for marked as duplicate and marked not a duplicate, which forwards events to the metrics microservice
- [ ] Create handlers in metrics for these 2 events which calls the `createUserAuditPointFromFHIR` function with the appropriate events.
- [ ] In client add messages for the new events for userAudit page

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![4472fixed](https://user-images.githubusercontent.com/94350336/231095914-084145e3-9def-4ccb-b22f-8d5b1e4a9695.png)

**Comment by anny320** [comment]
completed
