### ISSUE TITLE
create a dropdown list with options for informants relationship to child in form config 

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#4481]
### Description
Add additional options in the dropdown as below:     (Nigeria recommendation)
- Mother's brother
- Mother's sister
- Father's brother
- Father's sister
...

### Acceptance criteria

GIVEN 
WHEN
THEN

### Design

(Link to Figma)

### Dev tasks

- [ ] Task 1

**Comment by jpye-finch** [comment]
no longer required
