### ISSUE TITLE
In performance - Registrations page, the current month is not showing when viewed over time and records of current month is showing in the last month

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4482]
**Bug description:**
In performance - Registrations page, the current month is not showing when viewed over time and records of current month is showing in the last month. The last month in the table should be the current month( for now December 2022) and all the records of December 2022 is showing in November 2022. This should also work of different offices also.

**Steps to reproduce:**
1. Go to registrar
2. Create a birth/ death declaration
3. Click performance
4. Click view beside registrations
5. Click over time
6. Observe the table

**Actual result:**
1. the current month is not showing
2. the record of current month is showing in the previous month

**Expected result:**
1. Should show the current month in the table
2. the record statistics should show properly when searched over time

**Screen recording:**
https://images.zenhubusercontent.com/91778759/615dcce3-da88-4a5d-acc7-8d754e214609/207810111_b30f0465_8058_4fdc_9db2_d801e52d0de5.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
**Bug:**
In registrations Home death calculation is showing wrong

https://user-images.githubusercontent.com/94350336/212277397-3db04de9-8c44-4ee5-8f4e-7041c5a08f2b.mp4

**Comment by SyedaAfrida** [comment]
**Bug:**
Though the above bugs are fixed but new calculation bug araised. Health facility death calculation is showing wrong

https://user-images.githubusercontent.com/94350336/213417569-1e4fbdf6-dc0d-4013-9563-0be7b292e4e7.mp4

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/213687011-729e37a7-6f0c-4502-a98f-c8cf13a215ed.mp4

**Comment by anny320** [comment]
Completed
