### ISSUE TITLE
Records/Notifications declared and registered should only appear in workqueues of offices where they were created

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4485]
**Bug description:**
Records/Notifications declared and registered should only appear in workqueues of offices where they were created. Example record created in Ibombo Office should appear in the workqueue of Kennnedy mweene, not in Derrick Bulaya.

**Steps to reproduce:**
1. Login to registrar of location A
2. Create a birth/ death declaration
3. Observe the workqueue
4. Logout
5. Login to registrar of location B
6. Observe the workqueue

**Actual result:**
 Record created in location A is appearing in location B

**Expected Result:**
 Record created in location A should not appear in location B

**Screen recording:**
https://images.zenhubusercontent.com/91778759/f238f50d-9020-4e6d-b78f-fc87f57e66a9/workqueue_of_different_office.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/209072054-505a8ede-66fd-485e-9ce6-8b07eae8275e.mp4

**Comment by anny320** [comment]
Completed
