### ISSUE TITLE
Overlap of bookmark

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4487]
**Bug description:**
Overlap of bookmark

**Steps to reproduce:**
1. Login to RA/ local or national Registrar
2. Click Search> advance search
3. select any 2 filters > Search
4. Click on favourite star mark> add name > Confirm
5. Repeat step 2-5 few more times and observe

**Actual result:**
In side nav, bookmarks are getting overlapped with other text

**Expected result:**
should not overlap

**Screenshot:**
![206974452-f6625317-b005-46ec-82d6-76d3a6876184.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/436d936c-dfa0-4cda-8c6d-ae39075b8419)
**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
We need to refactor all the pages with the `Frame` component before fixing this as trying to fix this now breaks other views

**Comment by euanmillar** [comment]
@Zangetsu101 can we not make the left navigation above the warning scrollable for the time being?

**Comment by euanmillar** [comment]
Lets refactor.  Lets move the warning and the release version inside the navigation and make the whole left navigation scrollable

**Comment by asifjoardar** [comment]
@anny320 this ticket is fixed and can be closed.
[Overlap-of-bookmark.webm](https://user-images.githubusercontent.com/35629053/209915008-1fe41b1c-02fc-4bbb-b31e-7622d68eee3c.webm)

**Comment by anny320** [comment]
Completed
