### ISSUE TITLE
When language is set to french, arabic letters are coming in province and district dropdown

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4492]
**Bug description:**
When language is set to french, arabic letters are coming in province and district dropdown

**Steps to reproduce:**
1. Login to FA/ RA/ local Regsitrar/ National registrar
2. Set language to french
3. Create a birth/ death declaration
4. Observe all location dropdown

**Actual result:**
All the values for province and district are appearing in arabic

**Expected result:**
These values should appear in English since they are names of location

**Screenshot:**
![in french, arabic letters are coming in province and district dropdown.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/fd00df79-f28c-49b1-97a2-7cfc7a7fb136)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=fr

**Comment by euanmillar** [comment]
I left the Iraq district and states in the csv when testing multilingual location names using the "alias" prop. I guess we can remove them from the Farajaland CSV and make a new backup.

**Comment by asifjoardar** [comment]
@anny320 this bug is fixed and can be closed.

![4492](https://user-images.githubusercontent.com/35629053/212283901-bd6de836-1d06-4005-a6d6-71b8687eb489.png)

**Comment by anny320** [comment]
completed
