### ISSUE TITLE
In french language, when user try to navigate to record audit page from other places like- search/ team/ performance, then the title shows "no name provided" in french before assigning that record

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4493]
**Bug description:**
In french language, when user try to navigate to record audit page from other places like- search/ team/ performance, then the title shows "no name provided" in french before assigning that record

**Steps to reproduce:**
1. Set language to french
2. Login to RA/ Local or national registrar
3. Copy the tracking id of any record that is  not assigned
4. Search with that tracking id
5. Click on the record and observe
6. Again Click Performance
7. Click any link in Registration by status
8. Click on any tracking id and observe
9. Again Click on team
10. Click on any username (FA/RA/Registrar)
11. Click on any tracking id and observe

**Actual result:**
The declaration title shows "No name provided" in french before download

**Expected result:**
The declaration title should show actual name before download

**Screen recording:**
https://images.zenhubusercontent.com/91778759/eef740ba-f88c-4389-8fe7-d546507456ae/in_french_language__when_user_try_to_navigate_to_record_audit_page_from_other_places_like_search__team__performance.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=fr

**Comment by alamin-7** [comment]
@anny320 his ticket is fixed and can be closed

**Screen record of test:**

[language-change.webm](https://user-images.githubusercontent.com/38520477/209940304-4ac5935c-f733-44d7-9865-60f60f871465.webm)

**Comment by anny320** [comment]
completed
