### ISSUE TITLE
When creating a Webhook integration, the form checkboxes are not clickable

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#4498]
![Screenshot 2022-12-22 at 12.10.15.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/f84e087e-4aa1-46e3-8f97-eee7d64fb3c2)

**Comment by Zangetsu101** [comment]
So this seems to be working fine on desktop. In mobile view, if you press the label it works just fine but not if you press the checkbox itself. So the issue with the component itself

**Comment by Zangetsu101** [comment]
Should be fixed #3970

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![webhook](https://user-images.githubusercontent.com/94350336/210535537-cad96b1d-a160-4f77-bdf7-91563b16b62f.png)

**Comment by anny320** [comment]
completed
