### ISSUE TITLE
yarn db:backup:restore fails on environments when deploying

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#4499]
```
Failed: openhim-dev.log: error creating collection openhim-dev.log: error running create command: (NamespaceExists) Collection already exists. NS: openhim-dev.log
```

Can we remove the openhim-dev.log as part of yarn db:bacup:create, before the backups are created?

**Comment by Zangetsu101** [comment]
Could we perhaps use this [--drop](https://www.mongodb.com/docs/database-tools/mongorestore/#std-option-mongorestore.--drop) option? We are dropping the collections before restoring them anyway so it should get rid of the error.

**Comment by Zangetsu101** [comment]
infrastructure/restore-metadata.sh, restore-metadata.sh & emergency-restore-data.sh in farajaland

**Comment by Zangetsu101** [comment]
@euanmillar It seems we were already using the `--drop` option when restoring.
