### ISSUE TITLE
Update data-generator where users are created

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#4512]
- [ ] When creating the users in data generator, fetch the systemRoles, set the role of a user randomly from the available roles for a systemRole

**Comment by euanmillar** [comment]
@Nil20 I think we need to stop this work so @eduffus can input into what system roles he would like to see

**Comment by Zangetsu101** [comment]
@euanmillar I'm unblocking it as the data-generator is not working right now due to the changes in user roles. We can amend it later when the user roles for the demo environment are fixed

**Comment by Zangetsu101** [comment]
We need to amend the open PR as we had made some changes to the userRole collection afterwards so the changes in the PR have become obsolete
