### ISSUE TITLE
Records do not appear in any workqueue when submitted, after configuring a birth/death form

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4532]
**Bug description:**
Records do not appear in any workqueue when submitted, after configuring a birth/death form

**Steps to reproduce:**
1. Login to national system admin
2. Configure birth/ death form
3. Save with comment
4. Click 3 dot menu
5. Click in preview
6. Logout
7. Login to registrar
8. Declare a birth/ death record
9. Click register and observe

**Actual result:** 
The new record is not found in any workqueue

**Expected result:** 
The new record should be in ready to print

**Screen recording:**
https://images.zenhubusercontent.com/91778759/77df78cd-8332-441c-9db3-882fd20d7a79/farajaland_tester___9_january_2023.mp4

**Tested on:**
https://login.farajaland-config.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
We weren't able to reproduce this. I'm guessing there were some issues with the deployment when it was encountered. So moving this back to QA

**Comment by alamin-7** [comment]
@anny320 This ticket is ok and can be closed.

**Screen record:**

https://user-images.githubusercontent.com/38520477/212243266-7095e2ce-eb5a-47dc-a9c1-666f2c12a608.mp4

**Comment by anny320** [comment]
completed
