### ISSUE TITLE
Completeness rates calculated too high for Central Province

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#4533]
After running the data generator, more births appear to be registered within 30 days than expected for the Central province.

In these 2 views many more births appear to be registered than expected ....

![Screenshot 2023-01-09 at 09.21.26.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/0da3d6c8-8c2a-4e9a-abda-a06dbf75324a)

![Screenshot 2023-01-09 at 09.21.03.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/3990bdc5-e5b2-4a1c-8cc5-1c635665f22e)

The strange thing is, if you click the By Locations tab the numbers and percentages look fine!!

![Screenshot 2023-01-09 at 09.17.59.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/b484b906-8576-4f8c-9cff-b44c37effdac)

It looks to me like "Estimated number of births" is being calculated too low on the first two screens, but I dont know if this is a stats or a logic fault.

**Comment by euanmillar** [comment]
I will share a backup of all data in production that the developer can restore from in order to test locally.

**Comment by euanmillar** [comment]
To restore from a backup locally, in Farajaland repo run: 

```
./emergency-restore-metadata.sh 2023-01-09 0
```

**Comment by rabiulislamanik** [comment]
@euanmillar @Zangetsu101 , this following payload will update the central province's estimation data ( summation of district estimations, and average of district crude rates).

```
{
  "statistics": 
    {
      "year": 2021,
      "male_population": 387162,
      "female_population": 299071,
      "population": 686233,
      "crude_birth_rate": 6.99
    }
  
}
```
