### ISSUE TITLE
In team page, Location not showing properly

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4536]
**Bug description:**
In team page, Location not showing properly

**Steps to reproduce:**
1. Login to any user except FA
2. Click Team

**Actual result:**
![in team district and province not showing.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/f22f3705-889d-4105-885a-1caa511695e7)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by asifjoardar** [comment]
@anny320 this bug is fixed and can be closed

![4536](https://user-images.githubusercontent.com/35629053/212241498-9e8560d4-9448-4605-bb5c-39ccbcb603f0.png)

**Comment by anny320** [comment]
completed
