### ISSUE TITLE
When location of user is changed, birth or death record created do not appear in any workqueue

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4538]
**Bug description:**
when location of user is changed, birth or death record created do not appear in any workqueue

**Steps to reproduce:**
1. Login to national system admin
2. Click team
3. Click 3 dot menu> Edit user
4. Change the location of the user> Confirm
5. Logout
6. Login to the user which was edited
7. Create a birth/ death declaration> submit

**Actual result:**
the new record do not appear in any workqueue

**Expected result:**
The new record should appear in workqueue

**Screen recording:**
https://images.zenhubusercontent.com/91778759/35a3df57-f86a-483a-a4e0-f2bbd9abccfb/when_location_of_user_is_changed__birth_or_death_record_created_do_not_appear_in_any_workqueue.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by alamin-7** [comment]
@anny320 This ticket is ok and can be closed.

**Screen record:**

https://user-images.githubusercontent.com/38520477/212285874-53b29f65-f77e-44c9-ae39-b321357e6c24.mp4

**Comment by anny320** [comment]
completed
