### ISSUE TITLE
Validation of "National ID" text field for birth Informant's details page

### ISSUE THREAD

**Issue by asifjoardar** [opencrvs/opencrvs-core#4543]
**description:**
If informant "National ID" and mother/father "National ID" is same then no error is showing.

**Steps to reproduce:**
      1. Login to Field Agent
      2. Create a birth event where Informant type should be anyone except mother/father.
      3. keep informant's "National ID" and mother/father "National ID" same.

**Actual result:**
No error is showing when informant's "National ID" and mother/father "National ID" are same.

**Expected result:**
If informant's "National ID" and mother/father "National ID" same then error should be appear.

**Screen recording:**

https://images.zenhubusercontent.com/91778759/c0c4ec5c-72cb-473a-8da3-65b4b1e70676/informant_nid_validation.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by asifjoardar** [comment]
@anny320 this bug is fixed and can be closed.

https://user-images.githubusercontent.com/35629053/212281453-5752b0fc-9fe4-44e2-a94b-8795cadbc910.mp4

**Comment by anny320** [comment]
completed
