### ISSUE TITLE
Showing incorrect Device/IP Address.

### ISSUE THREAD

**Issue by alamin-7** [opencrvs/opencrvs-core#4544]
**Bug Description:**
Showing incorrect Device/IP Address.

**Steps to reproduce:**
1. Login as Registration Agent/Registrar/National Registrar except Field Agent.
2. Click the Team tab.
3. Click a user.
4. Observe Device/IP Address for reset password action.

**Actual result:**
Device/IP Address column is not correct.

**Expected result:**
Device/IP Address should have to be same.

**Screenshot:**![reset_pass.png](https://images.zenhubusercontent.com/639837d28ba3304b5b9edc2c/ac82d460-9f3c-4dee-a6a8-7ad943a67a2f)

**Tested on:**
https://register.farajaland-qa.opencrvs.org/

**Comment by alamin-7** [comment]
@anny320 This ticket is ok and can be closed.

**Comment by anny320** [comment]
completed
