### ISSUE TITLE
when there is no data for date of birth/death or place of birth/death, the fields are showing blank in record audit page

### ISSUE THREAD

**Issue by asifjoardar** [opencrvs/opencrvs-core#4545]
**description:**
when there is no data for date of birth/death or place of birth/death in a record then date of birth/death or place of birth/death field showing no message in record audit page.

**Steps to reproduce:**
      1. Create a birth/death event where date of birth/death or place of birth/death data should not be given.
      2. Go to in progress -> Click on the created application
      3. Observe the record information

**Actual result:**
date of birth/death or place of birth/death field showing no message in record audit page.

**Expected result:**
"No date of birth/death" and "No Place of birth/death" message should be appear.

**Screen recording:**

https://images.zenhubusercontent.com/91778759/951dc1b5-47f3-4f22-8d6a-50ac62f8b88a/validate_audit_record.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by asifjoardar** [comment]
@anny320 this bug is fixed and can be closed

![4545](https://user-images.githubusercontent.com/35629053/212237377-dec47f2f-b6ba-46a4-b60e-edaf3020dc3c.png)

![4545](https://user-images.githubusercontent.com/35629053/212237763-c5ae351d-6732-4d18-92ed-536a713e85eb.png)

**Comment by anny320** [comment]
completed
