### ISSUE TITLE
Column name incorrect in performance tab for death when filter with locations

### ISSUE THREAD

**Issue by alamin-7** [opencrvs/opencrvs-core#4551]
**Bug Description:**
Column name incorrect in performance tab for death when filtering with locations.

**Steps to reproduce:**
1. Login as Registration Agent/ Registrar/ National System Admin except Field Agent.
2. Click on performance tab.
3. Click view beside total of registration part.
4. Select type as Death
4. Set Location to district/ province or country.
5. Click By Locations.
6. Observe the table column.

**Actual result:**
Showing Home Birth and Health facility birth.

**Expected result:**
Should show Home death and Health facility death.

**Screenshot:**![death_field.png](https://images.zenhubusercontent.com/639837d28ba3304b5b9edc2c/cf23ad39-43b8-4c6f-8c49-db402163cc2f)

**Tested on:**
https://register.farajaland-qa.opencrvs.org/

**Comment by alamin-7** [comment]
@anny320 this ticket is ok and can be closed.

**Screenshot:**
![death__](https://user-images.githubusercontent.com/38520477/212281625-617f8ede-e060-4c59-a95e-ebdf0d54afe5.png)

**Comment by anny320** [comment]
completed
