### ISSUE TITLE
In the webhooks microservice, the client's sha_secret should encrypt the webhook payload

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#4552]
This is so that the data cannot be intercepted and can only be decrypted by a client that knows the sha_secret

The [payload](https://github.com/opencrvs/opencrvs-core/blob/c10b974f1f8a56c6c29e125d9d2a1fa58db5086f/packages/webhooks/src/features/event/handler.ts#L77) must be encrypted using the **webhookToNotify.sha_secret**

**Comment by euanmillar** [comment]
I need to check with MOSIP if the payload should be removed entirely and only leave the encrypted hmac

**Comment by euanmillar** [comment]
@rikukissa this would be required for the MOSIP integration in Uganda which will be designed in 1.7.0

**Comment by rikukissa** [comment]
@euanmillar is there more documentation to how this needs to be done (method of encryption...). HTTPS of course does fully encrypt all payloads between our system and the receiving client but I have seen similar arrangements elsewhere

**Comment by euanmillar** [comment]
@rikukissa I think it's documented in W3C WebSub docs

**Comment by rikukissa** [comment]
Where is this requirement coming from @euanmillar ? The WebSub specification describes [content signing](https://www.w3.org/TR/websub/#signing-content) but I couldn't find anything about content encryption

**Comment by euanmillar** [comment]
@rikukissa the requirement came from me. Probably because I misunderstood the docs! :-D.  I think we already sign using the sha secret so this can be closed.
