### ISSUE TITLE
Change copy in configuration modals

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4556]
**Syeda raised this bug.  The solution to it is just a copy change in the comments below.**

**Bug description:**
When birth is configured and made in preview, then old records created with death configuration disappears
 
**Steps to reproduce:**
1. Login to National system admin
2. Configure Death event
3. bring it to in preview
4. Logout
5. Login to registrar
6. Create a death declaration
7.Logout
8. Login to National system admin
9. Configure birth event
10. bring it to in preview
11. Logout
12. Login to registrar and observe

**Actual result:**
Old death record disappears

**Expected result:**
This works as expected, but the copy in the modals when you preview and publish should be made clearer that all submitted delarations and registrations sent while testing the configuration will be deleted in order that OpenCRVS is clean in production.

**Screen recording:**
https://images.zenhubusercontent.com/91778759/678577b2-4704-4dc4-a3d0-c24999b6739b/when_birth_is_configured_and_made_in_preview__then_old_records_created_with_death_configuration_disappears.mp4

**Tested on:**
https://login.farajaland-config.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
We need to check the copy in the modal's to let the users know that the data will be cleared

**Comment by euanmillar** [comment]
![Screenshot 2023-01-19 at 11.28.38.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/15efd858-fa19-4d68-85c8-5fb7a941ff55)![Screenshot 2023-01-19 at 11.28.23.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/0056af26-520a-4803-a76e-e113eccd7ace)

In the preview and publish modals the copy should tell the user that all previous applications that have been created in this testing stage are going to be deleted.

**Comment by euanmillar** [comment]
Change the copy in the modals to be:

"When you preview or publish a form configuration, all submitted declarations and registrations that have been previously submitted will be deleted.  This is to ensure a clean OpenCRVS system is used in production."

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![2](https://user-images.githubusercontent.com/94350336/230867080-4e19e833-0ff9-46a8-a5c2-7e72fc360288.png)
![1](https://user-images.githubusercontent.com/94350336/230867085-96f2aa30-efe9-46a3-a380-a6f0ca57d180.png)

**Comment by anny320** [comment]
completed
