### ISSUE TITLE
Form config - If National ID APIs are integrated, remove the ability to make National ID hidden or mandatory

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#4560]
If National ID APIs are integrated (MOSIP / OSIA / Other), then in form configuration, the rules for hiding or making National ID a required field must not be able to be overridden by a National System Admin so we should disable the toggles.

**Comment by jpye-finch** [comment]
@euanmillar close as no longer relevant?

**Comment by euanmillar** [comment]
Closing as his should be handled by 1.3.0 form config and interop requirements, uniques for any given country
