### ISSUE TITLE
In Performance, when clicked back from Completeness rate or registration page, always navigate back to default home page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4562]
**Bug description:**
In Performance, when clicked back from Completeness rate or registration page, always navigate back to default home page

**Steps to reproduce:**
1. Login to any user except FA
2. Click Performance
3. Click Location filter
4. Change location
5. Click view beside Completeness rate or registration
6. Click back

**Actual result:**
User gets back to default location of performance page

**Expected result:**
User should get back to change location page of performance

**Screen recording:**
https://images.zenhubusercontent.com/91778759/285d6152-2d87-4fff-8b8e-1c70e09d8542/in_performance__when_clicked_back_from_completeness_rate_or_registration_page__always_navigate_back_to_default_home_page.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/213391431-34849083-1b8a-4081-8082-e368d9157b85.mp4

**Comment by anny320** [comment]
completed
