### ISSUE TITLE
In performance tab, showing incorrect percentage of female for late registration

### ISSUE THREAD

**Issue by alamin-7** [opencrvs/opencrvs-core#4564]
**Bug Description:**
In performance tab, showing incorrect percentage of female for late registration

**Steps to reproduce:**
1. Login as Registration Agent/ Registrar/ National System Admin except Field Agent.
2. Click performance tab.
3. Observe the Registration part of late registration female percentage value.
4. Click the '+' icon for creating new birth record.
5. Create for a female and difference of current date and birth date have to be within 45 to 300 days.
6. Register the record.
7. Repeat the 3rd step.

**Actual result:**
No change in value of female percentage.

**Expected result:**
Female percentage value should have to be increased.

**Screen record:** 

https://user-images.githubusercontent.com/38520477/212050971-51d221cc-942e-4e91-be64-173a4d12a3c8.mp4

**Tested on:**
https://register.farajaland-qa.opencrvs.org/

**Comment by anny320** [comment]
completed
