### ISSUE TITLE
In Performance, wrong calculation is showing in Source of application> Field agent, Health system(integration) and registration agent

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4568]
**Bug description:**
In Performance, wrong calculation is showing in Source of application> Field agent, Health system(integration) and registration agent

**Steps to reproduce:**
1. Login as any user other than FA
2. Click Performance
3. Observe Source of application

**Actual Result:**
Showing 0 in Field agents and Registration agent number with percentage

**Expected Result:**
Should show exact number and percentage

**Screen recording:**
https://images.zenhubusercontent.com/91778759/e5098059-3750-4ab5-9727-db76490a4605/in_performance__wrong_calculation_is_showing_in_source_of_application__field_agent_and_registration_agent.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
Potential copy change

**Comment by Zangetsu101** [comment]
@jpye-finch

**Comment by jpye-finch** [comment]
Having reviewed the screen recording. I think this is a bug. 

Source of applications. Shows who started the declaration. 

In the screen recording. An FA sent on declaration. So they had started 1 declaration and sent it for review. 

But in source of applications it says 1. 

Side note. We should change the copy in the FA table from: 'Declaration sent' to 'Sent for review'

**Comment by euanmillar** [comment]
Should the copy "Sources of applications" be changed to "Sources of applications that have been registered"?

**Comment by euanmillar** [comment]
Change the title on the Performance Home page from "Sources of applications" to "Sources of registrations" and this is fixed in the view of the design team.

**Comment by euanmillar** [comment]
So, under the heading, I guess there should be a paragraph text like this:

"The number and percentage of declarations started by the each system roles that have been registered"

@septlowe we have to remember to also add a French translation please

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/217780832-3c577b69-2092-48bc-9934-b53fb2100276.mp4

**Comment by anny320** [comment]
completed
