### ISSUE TITLE
Birth deduplication logic

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4570]
### Description

- improves birth deduplication logic
- adds 3 types of [Birth Criteria Checks
](https://www.notion.so/opencrvs/d05eb41695fc4fb8a97678880ca5f0c6?v=5328241fa62a4734ac887b22e329ecbe)
- create documentation on how the logic can be customised

### Acceptance criteria

**Standard check**
GIVEN a new birth declaration is submitted
WHEN we believe it is an exact match or very similar to an existing record
THEN flag as a potential duplicate

**Same mother two births within 9 months of each other**
GIVEN a new birth declaration is submitted
WHEN we believe it is the same mother on another record who had a child within the last months of the new declaration
THEN flag as a potential duplicate

**Child age increase/decrease**
GIVEN a new birth declaration is submitted
WHEN we believe it is the same child but their date of birth year is different (+/- 3 years)
THEN flag as a potential duplicate

### Dev tasks

The work for this ticket can be continued in this ticket: https://github.com/opencrvs/opencrvs-core/issues/4541

- [ ] [`searchForDuplicates`](https://github.com/opencrvs/opencrvs-core/pull/4541/files#diff-f1ee21482bf25e832b890c7a5d40825103ec072bf33ec84275d4022b12adfd75L56) should be amended to identify duplicates by the logic that is defined here: [Birth Criteria Checks
](https://www.notion.so/opencrvs/d05eb41695fc4fb8a97678880ca5f0c6?v=5328241fa62a4734ac887b22e329ecbe) The current function already does something kind of similar, but it needs to be tweaked.

**Comment by SyedaAfrida** [comment]
@anny320 the bug for this ticket is mentioned in #4907 . So this ticket can be closed
