### ISSUE TITLE
Death deduplication logic

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4571]
### Description
- adds death deduplication logic
- adds 1 type of [Death Criteria Checks
](https://www.notion.so/opencrvs/918928632672491295d5a42cfa9a4088?v=b4ec9138178d4e8ebb4664a3b82c72fc)
- create documentation on how the logic can be customised

### Acceptance criteria

**Standard check**
GIVEN a new death declaration is submitted
WHEN we believe it is an exact match or very similar to an existing record
THEN flag as a potential duplicate

### Dev tasks

Continue death deduplication after the birth deduplication has been created in #4570

- [x] Currently `search` microservice has route `search/duplicates`. We need to have 2, `search/duplicates/birth` and `search/duplicates/death`. Function for searching birth duplications already exists (searchForDuplicates), but we need to create one that searches for death duplicates. - 2
- [x] Amend the event deduplication logic to also include deaths. Currently, it only checks for births. 
  - In [detect event](https://github.com/opencrvs/opencrvs-core/blob/27d46f6e3e11bd530d1826a4694d2f42cfdfb855/packages/workflow/src/features/events/handler.ts#L92) the new death declaration needs to go to Ready for review, similarly as when a birth is a duplicate
  - [buildFHIRBundle](https://github.com/opencrvs/opencrvs-core/blob/d0d870375fe85c7209abafbcc5c603846078e37b/packages/gateway/src/features/registration/fhir-builders.ts#L3615) needs to be amended to also handle death duplicates. - 2
- [x] Call `detectAndUpdateDuplicates` in death handler similar to the birth one
- [ ] In the query for download declaration, add the duplicates field so that the comparison view works. Show the label BRN/DRN depending on the event - 1

**Comment by SyedaAfrida** [comment]
**Bug:**
Death deduplication not working

https://user-images.githubusercontent.com/94350336/226907494-ca8380e4-fc34-4cc4-8834-8b1eb74e7ea9.mp4

**Comment by Zangetsu101** [comment]
@SyedaAfrida This one is related to Registrar directly registering a duplicate declaration. It should be fixed in the next deploy. For the time being you could test the duplicates by creating declarations using field agents or registration agents.

**Comment by SyedaAfrida** [comment]
Death deduplication is working for FA but not for RA and Registrar. Need to test after next deploy.

**Comment by SyedaAfrida** [comment]
@anny320 the bug for this ticket is mentioned in #4918. so this ticket can be closed.

**Comment by anny320** [comment]
completed
