### ISSUE TITLE
As a user, I want to audit if a record certificate has been verified

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4578]
### Description

- adds record audit action. Certificate verified
- no data for. By, Type and Location
- model show. IP address. 

### Acceptance criteria

GIVEN I am on the Record Audit page
WHEN a certificate has been verified
THEN show the action Certificate verified

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=11663%3A89062&t=eZhxMArrJD8CW0Av-1

### Dev tasks

- [x] When a record is fetched for verification purposes, the backend should create a new record audit log event.

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![4578 fixed](https://user-images.githubusercontent.com/94350336/229471381-7f786d38-ab5f-46fb-9dbc-1ca5b6f90da5.png)

**Comment by anny320** [comment]
completed
