### ISSUE TITLE
when download button is clicked for a record from "Sent for review" tab then some records are disappeared from the list(except the records with status -> In review)

### ISSUE THREAD

**Issue by asifjoardar** [opencrvs/opencrvs-core#4579]
**description:**
when download button is clicked for a record from "Sent for review" tab then some records are disappeared from the list(except the records with status -> In review).

**Steps to reproduce:**
1. Login to Field Agent and click on Sent for review tab
2. download a record and observe.

**Actual result:**
some records are disappeared from the list(except the records with status -> In review) and appeared after refreshing the page.

**Expected result:**
every record from "Sent for review" tab should be as it is, only download button of that specific record should be changed.

**Screen recording:**

https://images.zenhubusercontent.com/91778759/4b6bd0f8-ab21-4f5a-8e58-7338d9be6dcb/sent_for_review.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/213646098-86f72a0c-7065-4651-b266-f3a65634d9cf.mp4

**Comment by anny320** [comment]
Completed
