### ISSUE TITLE
Component: List view for duplicate review

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4582]
### Description
- adds a new type of List (maybe a variant of ListViewSimplified, maybe not) 
- adds a Header to a List
- onDesktop it has Three columns. One is the Label and two are for data
- onMobile the Headings and Data stack into two columns under the Label

### Design
[Figma component
](https://www.figma.com/file/SsqCzO2eherXXCKyixmli9/OpenCRVS-Design-System-v2-WIP?node-id=28%3A6010&t=fV92h89VfCNsbQG5-1)
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/0f1b884f-a23d-4b5e-9962-25c7377b6339)

Deduplication desktop: https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=10960%3A93026&t=DkJe2CDmsnLp7j5j-1
Deduplication mobile: https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=11883%3A91871&t=DkJe2CDmsnLp7j5j-1

### Dev tasks

- [x] Task 1

**Comment by Zangetsu101** [comment]
Done in #4604
