### ISSUE TITLE
Sometimes when an incomplete application is completed and registered, it goes to waiting validation status

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4583]
**Bug description:**
Sometimes when an incomplete application is completed and registered, it goes to waiting validation status. 

_Note: This might occur due to deployment issue. But later that record do not get registered any way_

**Steps to reproduce:**
1. After deployment Login to registrar
2. Click In progress> Field agent> Download> assign
3. Complete the record
4. Click Register and observe

**Actual result:**
Record goes to waiting validation status

**Expected result:**
Record should be registered properly

**Screenshot:**
![waiting validation.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/6795d94a-b3c5-47db-933d-abbdfad467c5)

**Tested on:**
browserstack

**Comment by euanmillar** [comment]
@rikukissa can you help with this please?  We think it is related to the countryconfig's token validation check.  See this: https://opencrvsworkspace.slack.com/archives/C02P91N0E1W/p1674043552099319

**Comment by euanmillar** [comment]
Blocked awaiting tech design and prioritisation

**Comment by rikukissa** [comment]
> I was able to register the application BRACCX9. I just logged in as a registrar (k.mweene), searched for it using a tracking ID and then I registered it. **But first I had to empty my browser cache.** We think it might be related to the token that countryconfig gets from auth service when countryconfig starts. Because the cause of this issue is that the _"validate/registration"_ req fails with invalid token. It may not be so serious.

Sounds likely. It seems the implementation in Farajaland that should update the public key is missing a critical piece: it should also try to update the public key when requests start failing with unauthorised. You can see how it's done in [Nigeria](https://github.com/newlegacydigital/opencrvs-nigeria/blob/develop/src/index.ts#L73-L100). Without this, the only way for the public key to update is when the server restarts. Sometimes we deploy new versions only for core which would then cause country config not to restart at all causing it to have outdated public key.

**Comment by anny320** [comment]
need to test again after a deployment since today's test registered immediately![Screenshot 2023-03-14 at 10.31.03.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/c0547cc0-1e6a-4be3-a141-9a096ae978f2)

**Comment by anny320** [comment]
completed
