### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4591]
**Bug description:**
There are few console errors which are not currently affecting any functionality but needs to be fixed

**Screenshots:**
![con1.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/812fc420-ee31-4ce1-bd45-4d5f14304a56)
![con2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/3869e0b4-309e-4b11-9458-5383c8a902ef)![con3.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/a5849abb-62f2-4399-bb53-6c5fd0829a95)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by jpye-finch** [comment]
@SyedaAfrida ticket still required?

**Comment by SyedaAfrida** [comment]
These errors no longer appear in QA
![er](https://github.com/opencrvs/opencrvs-core/assets/94350336/82df28e1-b567-4c8a-8a33-4e1494843a11)
