### ISSUE TITLE
Though NID is unique, still showing unique error after registration

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4594]
**Bug description:**
Though NID is unique, still showing unique error after registration

**Steps to reproduce:**
1. Login to RA
2. Click Ready to print> Assign to any birth declaration
3. Click Review
4. Make sure mother and father's NID is unique
5. Click Register
6. Logout
7. Login to Registrar
8. Click Ready to review
9. Click Assign> Review to that record and observe

**Actual result:**
Showing that mother and father's NID is not unique and register button gets disabled

**Expected result:**
Should not show error since NID is unique

**Screen recording:**
https://images.zenhubusercontent.com/91778759/371ea077-9729-4922-90f9-e9503c331735/nid_is_unique_still_showing_error.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 This bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/213671591-c43879ba-4c35-4caf-838e-e86480bb02ab.mp4

**Comment by anny320** [comment]
Completed
