### ISSUE TITLE
As a Reg Agent of Registrar, I want to print and issue a certificate

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4607]
### Description
- Updates copy of the confirmation dialog when printing a certificate and issuing to the informant
- updates status to Issued

### Acceptance criteria

GIVEN I am a Registrar of Reg Agent
WHEN I choose to print and issue to collector
[THEN show the confirmation dialog 'Print and issue certificate?'](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=10282%3A66899&t=4VbkamxwtyZTwWnj-1)

GIVEN I have printed and issued a certificate
THEN update the status to Issued

### Dev tasks

- [ ] Task 1

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/224930658-eebc4206-a53a-4868-953b-53d88ba2e5b1.mp4

**Comment by anny320** [comment]
completed
