### ISSUE TITLE
Change User and Userroles schema

### ISSUE THREAD

**Issue by rabiulislamanik** [opencrvs/opencrvs-core#4615]
1. Create a new collection 'Role'. Use the RoleSchema and LabelSchema from 'SystemRoles' schema. And in 'SystemRoles',   clean up the  'RoleSchema' and 'LabelSchema' and then use a reference to the list of ObjectIds of 'Role' document.

2. Currently in User model, role is an enum. 
```
export enum FIELD_AGENT_TYPES {
  HEALTHCARE_WORKER = 'HEALTHCARE_WORKER',
  POLICE_OFFICER = 'POLICE_OFFICER',
  SOCIAL_WORKER = 'SOCIAL_WORKER',
  LOCAL_LEADER = 'LOCAL_LEADER'
}
```
```
  role?: FIELD_AGENT_TYPES
```
* Change the User model's role property to be a reference for 'Role' ObjectId like this

**Comment by Zangetsu101** [comment]
Done in #4576
