### ISSUE TITLE
Amend PractitionerRole

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#4616]
- [x] In PractitionerRole -> code[0] -> coding[0] -> code we store the systemRole. We need to instead store role. So we will need a migration for the existing data and amend the createUser, updateUser handlers in user-mgnt accordingly. - 2
- [x]  In gateway -> registration -> typeResolvers, the user resolver for History needs some amend to modify the role data instead of systemRole - 1

**Comment by Zangetsu101** [comment]
@nsamadavid I'm afraid this ticket is dependent on #4615

**Comment by nsamadavid** [comment]
okay i see. thank you.
