### ISSUE TITLE
Demo env: data-generator created system clients should use real hospital names

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#4638]
Currently the Event Notification client names are like this: "tiger". "lion" etc. That wasnt a problem before because they were invisible. But as we now have an Integrations GUI and you can see these names in demos, they should be the hospital names in the facilities to make sense

[https://github.com/opencrvs/opencrvs-farajaland/blob/develop/src/data-generator/users.ts#L289](Here) is the part of code where the random noun is generated. 

Dev tasks:
- [ ] Replace the part of code where the random noun is generated. Replace it with a random health facility. You can create `getHealthFacilities` taking example from [`getFacilities`](https://github.com/opencrvs/opencrvs-farajaland/blob/develop/src/data-generator/location.ts#L55) and assign them randomly.
The random facility selected, must be within the same district as the officeLocation. So we need to find all hospitals in the district that the script is currently operating within, and choose a random facility from only that sub-set
- 1

**Comment by euanmillar** [comment]
The random facility selected, must be within the same district as the officeLocation.  So we need to find all hospitals in the district that the script is currently operating within, and choose a random facility from only that sub-set
