### ISSUE TITLE
As a Registrar I want to create a marriage declaration

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4641]
## Description
- adds a new event type and form
- adds date of birth validation for groom and bride (both be 18 years old) (this will become a config option in future)

Pages: 
- Informant type
- Main contact
- Groom
- Bride
- Witnesses
- Supporting documents
- Review page

## ACs

GIVEN I am a FA, Reg Agent or Regsitrar
WHEN I select new delcaration
THEN I can select Marriage

GIVEN I select Marriage
THEN I can complete the Marriage form 

## Design
https://www.figma.com/file/LbhDHe7yCMYVdhs2Kd0UuA/Declaration%2FFarajaland%2FMarriage?node-id=0%3A1&t=M7bOxAMQ0XKqkIhu-1

- [x] Configure the new marriage event in the default.ts & the addresses.ts - 5
- [x] Add validation for bride & groom for their min age - 1

**Comment by anny320** [comment]
completed
