### ISSUE TITLE
As a Registrar I want to capture a digital signature from the Groom, Bride and Witnesses

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4642]
## Description
- Adds digital signature capture for all parties on review page: Bride, Groom, Witness 1, Witness 2

## ACs

GIVEN I am completing a marriage declaration
WHEN on the review page
THEN I am prompted to capture the digital signature for Bride, Groom and witnesses

## Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=12475%3A98356&t=xMoNGDswTFYqkfvj-1

- [ ] Move the Signature logic into a separate component. Depending on the event, either render the informant signature or the bride, groom, witnesses signature. Add the transformers as well similar to the informantsSignature

**Comment by SyedaAfrida** [comment]
@anny320 This ticket is fixed and can be closed
https://www.loom.com/share/38a7fb5cea364a06b9c695183e176b51

**Comment by anny320** [comment]
completed
