### ISSUE TITLE
Configure marriage registration time periods and fees

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4645]
## Description
- Adds a new marriage tab to the Application settings
- Adds options to set the registration time period and fees. Same as Death

## ACs
GIVEN I am a national system admin
WHEN on the Application config page
THEN I can select Marriage

GIVEN I select Marriage tab
THEN show the default settings for the registration times and fees

GIVEN I select change to the legally specified time 
THEN open the config model

GIVEN I select change to fees
THEN open the config model

## Design

https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=12473%3A98133&t=xMoNGDswTFYqkfvj-1

### Back-End
- [x] Modify the ApplicationConfig model in config -> models -> config to include a new schema for marriage. Create a migration for the updated data. Update the handlers, Joi schema where needed.
- [x] Amend the updateApplicationConfig mutation as needed with the new option.
- [x] Amend the updateApplicationConfig mutation used in client to return the new value as well. Amend the IApplicationConfig type used throughout client - 3

### Front-End
- [x] Create a new tab marriage in application configuration similar to death. Add similar interactions that are available for the death tab. - 2

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/229092548-94618ff4-0b73-428f-99b4-b89a27edee63.mp4

**Comment by anny320** [comment]
completed
