### ISSUE TITLE
Configure marriage certificate

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4646]
## Description
- Adds option to configure marriage certificate to existing cert config page
- Allows designer to choose placement of all digital signatues. Groom, Bride, Witness 1, Witness 2 and Registrar

## ACs
GIVEN I am designing the marriage certificate
WHEN editing the SVG
THEN I can enter the handlebar for each signature

## Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=12678%3A99115&t=KYq0wBzUOGApgnKr-1

Farajaland marriage certificate: https://www.figma.com/file/fOUJWiaqHcOAwj2qaXV2w4/Farajaland?node-id=301%3A82&t=j5k0EnbMR5fXcxrH-1

- [x] Prepare the Marriage certificate svg from the figma. Replace the values with {{ }}. The handlebars will be the same as for birth/death except for a couple extra/modified ones: instead of childFirstNames & childLastName, we'll have brideFirstName, brideLastName, groomFirstName & groomLastName. And a couple of extra handlebars for brideSignature, groomSignature, registrarSignature & qrCode - 2
- [x] Create a migration to add marriage certificate - 1
- [x] Add a new tab for the marriage event in the certificates configuration view
- [x] Include the options to upload/print/preview/download the certificate
- [x] Add the print in advance toggle option - 3

**Comment by Zangetsu101** [comment]
@jpye-finch We are changing the certificate configuration designs in #4361 so the marriage ones should be similar to those no?

**Comment by jpye-finch** [comment]
@Zangetsu101  oh nice. I wasn't sure that ticket was being worked on

I have updated the design

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and an be closed
![4646 fixed 2](https://user-images.githubusercontent.com/94350336/229764315-6cce21a8-f271-4e04-837c-bc587a10ad62.png)
![4646 fixed](https://user-images.githubusercontent.com/94350336/229764350-3bfcc5f0-b662-40ff-931b-6a77b9709717.png)

**Comment by anny320** [comment]
Completed
