### ISSUE TITLE
Print a marriage certificate

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4647]
## Description
- Adds print option to marriage
- Same flow and experience as we have for brith and death

## ACs
GIVEN I am on the Ready to print workqueue
WHEN I click Print on a marriage record
THEN nav to the print flow

GIVEN I am in the printing a marriage certificate
WHEN the reg is printing and issuing 
THEN ask for the collector, id check and payment, THEN show preview

GIVEN I am in the printing a marriage certificate
WHEN the reg is printing in advance
THEN show the marriage certificate preview

**Comment by anny320** [comment]
completed
