### ISSUE TITLE
As a user, I want to print another certificate of an issued record

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4652]
## Description
- Allows re-printing of an issued certificate

## ACs
GIVEN a record has been certified and issued
WHEN a user clicks print on Record Audit
THEN navigate to the print certificate workflow
THEN allow them to complete the print flow. As if printing for the first time. 

GIVEN a user prints another certificate
WHEN they print in advance
THEN send the record to Ready to issue

GIVEN a user prints another certificate
WHEN they print on collections 
THEN the record does not appear in any workqueue

GIVEN a user prints another certificate
WHEN on Record Audit
THEN show the record action Certified
THEN show the record action Issued

- [x] Update record audit for Issued declaration to show the print button. Clicking print would go to the print certificate flow
- [x] Searching for an Issued declaration should also show the Print button similar to how it was previously for Certified ones
- [x] For issued declaration, in the record audit should show BRN/DRN no. Issued declaration icon

**Comment by Zangetsu101** [comment]
@anny320 @jpye-finch We should probably add the correct record button as well for an Issued record?

**Comment by jpye-finch** [comment]
yes that is correct

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/224962785-e2042ba8-255c-4eeb-b429-dc0517c68591.mp4

**Comment by anny320** [comment]
completed
