### ISSUE TITLE
Sysadmin side panel menu doesn't handle active state properly

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#4668]
<img width="265" alt="image" src="https://user-images.githubusercontent.com/1322608/216977743-ceeb789e-1724-4863-b612-b6dace187e76.png">
When logging is as `j.campbell`, the left menu doesn't handle active states properly. "Performance", "Organisation" and "Team" don't show active state like "Vital statistics" does (see picture). "Vital statistics" text color is a darker black when active, while other ones are grey when active.

The submenus work properly.

This should be addressed when refactoring the left side panel in https://github.com/opencrvs/opencrvs-core/pull/4453

**Comment by jpye-finch** [comment]
closed as done
