### ISSUE TITLE
Username should not get updated when phone number is changed

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4677]
**Bug description:**
Username should not get updated when phone number is changed
 _Note: Currently Username is getting updated if any field is changed, Not only phone number_

**Steps to reproduce:**
1. Login as National system admin
2. Click Team
3. Click 3 dot menu > Edit details beside any user
4. Click change beside any phone number
5. Change The number
6. Click Continue> Confirm
7. Click 3 dot menu > Edit details beside that user and observe

**Actual result:**
Username gets updated with incremental number

**Expected result:**
Username should not get updated when phone number is changed

**Screen recording:**
https://images.zenhubusercontent.com/91778759/44ebf18c-bd34-4ee8-a1f7-dc743297d347/username_should_not_get_updated_when_phone_number_is_changed.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Nil20** [comment]
https://user-images.githubusercontent.com/32668488/223984146-c77510c0-7234-4d57-be74-566629b71285.mp4

**Comment by anny320** [comment]
working correctly https://www.loom.com/share/f647526cefa2475ea0b48c1760d0e2ea 
completed

**Comment by rikukissa** [comment]
@anny320 I don't think this is working. I just managed accidentally create a with username `p.jumbo1` even when I had no `p.jumbo` user in the database. 

The way I managed to do it was:
- Create a user but use a phone number that is already in use
- Change the phone number and try again
- Now the user has a number prefix

For whomever is working on this next:
- Remove `UsernameRecord` collection and references to it from generateUsername.

Implement this type of logic instead:

```
i = 1
while(usernameTaken) {
  username = proposedUsername + 1
  usernameTaken = await checkUsername(username)
}
```

**Comment by rikukissa** [comment]
Another way to reproduce an issue:

- Add a user in the default dataset with a username `jonathan.campbell`, `riku.rouvila`, `spiderman` or similar
- Change the user details as a system admin
- See their username change automatically

This should not happen either!

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://github.com/opencrvs/opencrvs-core/assets/94350336/0cc325ff-4606-417c-890d-253b22b79011

**Comment by anny320** [comment]
completed.
