### ISSUE TITLE
As a informant, I want to authorise my National ID

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4689]
## Description
- On click redirects to MOSIP authenticate screens
- User clicks on "Authenticate", gets to E-Signet & MOSIP flow
- User gets back to OpenCRVS, with a E-Signet signed token in URL. This token is later used to fetch informant details.

https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=12824%3A98487&t=PoC6QvK6Xk8BGwz6-4

## ACs

WHEN I am on the mother, father, deceaseds, informant, marriage/divorce TBC
GIVEN I select Farajaland for my nationality
THEN I should see the National ID Authenticator

WHEN I am on the mother, father, deceaseds, informant, marriage/divorce TBC
GIVEN I select any other nation for my nationality
THEN I should see the National ID Text Input

## Dev Tasks

E-Signet is a authentication service which implements OpenID Connect. MOSIP is integrated with E-Signet, and therefore we can implement a OpenID Connect flow to support verifying the user with National ID.

- [x] Create a random UUID "nonce", and save it to LocalStorage - 1
- [x] [See E-Signet documentation.](https://docs.esignet.io/integration-guides/relying-party-integration#add-a-button-on-your-login-screen) Clicking the <kbd>✔️ Authenticate</kbd> button should 1) save the draft declaration 2) redirect to [see URL 1] - 2
- [x] Create a new client route `localhost:3000/mosip-callback`. When the user is redirected there from E-Signet, check the `state` query parameter and redirect the user back to the previous form path. Pass `code` query parameter to the form.
Check in `mosip-callback` that `nonce` matches the one saved in IndexedDB. If it doesn't, throw an error. - 2

---

[URL 1]
```
${openIdConnectIdPBaseUrl}/authorize?nonce=${nonce}&state=${state}&client_id=${openIdConnectClientId}&redirect_uri=${redirect_uri}/mosip-callback&response_type=${response_type}&scope=openid%20profile&acr_values=mosip:idp:acr:static-code&claims=${claims}&display=page&prompt=consent&max_age=21&claims_locales=${languageCode}&ui_locales=${languageCode}
```
* redirect_uri = `${CURRENT_HOST}/mosip-callback`
* response_type = 'code'
* state needs to include the form path, so we can redirect the user back there later, for example `/drafts/00c90c71-b984-497a-ae43-5a4fdf24f7c7/events/birth/informant/group/informant-view-group`
* languageCode = [ALPHA3 language code stored in IndexedDB. ](https://github.com/opencrvs/opencrvs-core/blob/f615f294881b751464692236a965477fcb0af5cb/packages/login/src/i18n/utils.ts#L27)
* `%7B%22userinfo%22:%7B%22given_name%22:%7B%22essential%22:true%7D,%22phone_number%22:%7B%22essential%22:false%7D,%22email%22:%7B%22essential%22:true%7D,%22picture%22:%7B%22essential%22:false%7D,%22gender%22:%7B%22essential%22:false%7D,%22birthdate%22:%7B%22essential%22:false%7D%7D,%22id_token%22:%7B%7D%7D`

**Comment by naftis** [comment]
Open question to @jpye-finch

"Type of ID" should probably be a mandatory field that is always there. "National ID" should also probably always be an option of that field, if a national id integration has been set up. Maybe it should be always there, even if the integration hasn't been set up?

Can we configure the types of ID's, or do we start with just hard-coded "National ID", "Birth certificate", "Passport", and "No ID"? 

Do we have the "Type of ID" field available, if we don't have a national id integration? I guess yes, because otherwise:
what happens if a form is published and a National ID integration is being added afterwards?
