### ISSUE TITLE
When logged in with any user other than local/ national system admin, an error appears in console

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4692]
**Bug description:**
When logged in with any user other than local/ national system admin, an error appears in console

**Steps to reproduce:**
1. Login to Fa/ Ra/ Local or national Registrar
2. Observe console

**Actual result:**
![t.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/0147b89d-2f11-440a-9b2a-5234a2155af8)

**Expected result:**
should show no error

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this ticket can be closed as the mentioned console errors are fixed now and we have separate ticket for the new errors
![4692-fixed](https://user-images.githubusercontent.com/94350336/222346956-14a78d36-1ed0-4811-91f0-982a3e5f5df1.png)

**Comment by anny320** [comment]
closed
