### ISSUE TITLE
As a Registration Agent, I want to review and decide on a potential deduplicate

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4697]
### Descrption

- Adds Reg Agent to new deduplication experience (comparison view)
- Reg Agent can mark the record as a duplicate or not a duplicate
- If marked not a deduplicate then the Reg Agent can send for approval

### ACs

GIVEN I am a Registration Agent
WHEN a record is flagged as a potential duplicate
THEN I can review the record against potential duplicates

GIVEN I am a Registration Agent
WHEN I mark a record not a duplicate
THEN I can send the record for approval

GIVEN I am a Registration Agent
WHEN I mark a record as a duplicate
THEN archive the record

GIVEN I am a Registrar
WHEN a record has been marked not a duplicate by the RA
THEN I can review the record and register or reject (normal review experience)

### Dev tasks

- [x] Don't check for duplicates in search micorservice if a declaration is already validated
- [x] Investigate why the new flow is not working in the base branch after the merge
- [x] Mark as a duplicate and not a duplicate for death declaration
- [ ] When we are dowloading a declaration, we need to downoad the duplicate declarations as well so we need to add the @persist directive in those queries

**Comment by anny320** [comment]
completed
