### ISSUE TITLE
Back to home link not working after system crash

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4700]
**Bug description:**
Back to home link not working after system crash for any feature. So user has to always clear cache after any system crash, which is not convenient

**Steps to reproduce:**
1. After any system crash click Close
2. Click back to home

**Actual result:**
The crash page keeps on appearing

**Expected result:**
Back to home link should work

**Screen recording:**
https://images.zenhubusercontent.com/91778759/becefc0c-3107-49a8-a293-c2f2a84ee78c/back_to_home_link_not_working_after_system_crash.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@Zangetsu101 the console logs-
![ss](https://user-images.githubusercontent.com/94350336/218746440-cde3b01f-fc06-4853-884d-fb2eac5beb47.png)


https://user-images.githubusercontent.com/94350336/218746347-1bbf510e-c99e-460a-906f-38407e06df35.mp4

**Comment by Zangetsu101** [comment]
Thanks @SyedaAfrida, the logs will help us out quite a bit

**Comment by rabiulislamanik** [comment]
Fixed by #4716 

[4700_fix.webm](https://user-images.githubusercontent.com/35958228/220569076-28c1922f-81af-423b-b592-edb2eff5577c.webm)

**Comment by rabiulislamanik** [comment]
Fixed by #4716

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed with #4693 . So this ticket can be closed.

**Comment by anny320** [comment]
completed
