### ISSUE TITLE
System crash occurs when try to go to record audit page of a draft

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4714]
**Bug description:**
System crash occurs when try to go to record audit page of a draft

**Steps to reproduce:**
1. Declare a birth/death declaration
2. Fill up the fields
3. Click save & exit
4. Click In progress tab
5. Click to that record

**Actual result:**
System crash occurs 

**Expected result:**
User should be able to view record audit page of any draft

**Screen recording:**
https://images.zenhubusercontent.com/91778759/6ed32d8b-4824-46e7-8091-c529acb674a9/system_crash_occurs_when_try_to_go_to_record_audit_page_of_a_draft.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by rabiulislamanik** [comment]
Fixed by #4716

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/222071918-534559ee-ad99-47e4-bc08-5d7f69553420.mp4

**Comment by anny320** [comment]
completed
