### ISSUE TITLE
Marriage Declaration gateway task

### ISSUE THREAD

**Issue by sadmananik** [opencrvs/opencrvs-core#4723]
Gateway Task
- [x] Create MarriageRegistrationInput and MarriageRegistration schema - 1
 
Write mutations for following - 2

- [x] 1. createMarriageRegistration
- [x] 2. markMarriageAsValidated 
- [x] 3. markMarriageAsRegistered
- [x] 4. markMarriageAsCertified
- [x] 5. markMarriageAsIssued

Write Queries for following - 1

- [x] 1. fetchMarriageRegistration
- [x] 2. Amend EventRegistration `__resolveType`

- [x] Add fhir builders for bride, groom, witnessOne and witnessTwo - 2
- [x] Modify TypeResolver for extra marriage declaration property

Client tasks for marriage

- [x]  Modify fetchAllMinioUrlsInAttachment on client to get documents from minio - 1
- [x] Check the whole registration flow after merging all the backend - 1

**Comment by Zangetsu101** [comment]
Done in #4703
