### ISSUE TITLE
Divorce registration

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4724]
# Problem statement

The lack of “Declaring a divorce” feature on OpenCRVS currently. This leads to high abandonment rates by the potential customers, system integrators (SIs) and donors. The goal is to showcase the new feature to the potential customers/donors/SIs to cover an additional vital event in the OpenCRVS system."

# Requirements
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=13995%3A99949&t=YQKgLKf8hyEWk04F-1

V1:
- Registrar can declare a divorce from the Marriage audit page
- Capture details about the divorce
- Upload supporting documents from the court
- Review and register the declaration

# Process

| Actors and permissions | Registrar |
| --- | --- |
| **Pre-condition** What activities must take place before the use case can be started? | A marriage has been registered in OpenCRVS |
| **Triggers** What event starts the use case? | Court order that the marriage has been annulled |
| **Standard flow** What are the user actions and system responses that will take place during execution of the use case under normal, expected conditions? | 1. Registrar searches for the marriage 2. Clicks Divorce 3. Enters details about the divorce 4. Uploads supporting documents 5. Reviews the declaration 6. Registers the divorce |
| **Post-condition** What marks the end of the use case? | - The marriage has been annulled - Status changes to Divorce |
| **Flow variations and responses** What variations or error conditions could occur and how does the system respond? |  |

---

# Future considerations

- Reinstating a marriage
- Printing a divorce certificate

**Comment by cinojopencrvs** [comment]
@euanmillar @Zangetsu101 - declare a divorce is ready for tech design.

**Comment by jpye-finch** [comment]
duplicate of [#4726](https://github.com/opencrvs/opencrvs-core/issues/4726)
