### ISSUE TITLE
Divorce: Audit a marriage that has been divorced

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4728]
## Description
- New status: Divorced. When a marriage record has been annulled (divorced) 
- New history action: Divorced
- User can only View the record
- Divorce Action Model: 

## ACs
GIVEN a marriage record has been divorced
WHEN on the record audit page
THEN show the status as Divorced

GIVEN a marriage record has been divorced
WHEN on the record audit page
THEN show the history line item Divorced

GIVEN a user clicks Divorced in the history table
THEN show the metadata

## Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=13995%3A100004&t=YQKgLKf8hyEWk04F-1

## Dev tasks

**Comment by euanmillar** [comment]
Closing as #7052 Events v2 will cover divorce with the addition of: #4726
