### ISSUE TITLE
Bug in phone number transformations

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#4750]
In Cameroon local phone number formats are in this format: 6640xxxxx which translates to international format of +237 6640xxxxx . Notice that local number has 9 digits, international 3+9. This is a little different from what at least I’m used to with my local number of 0504700715 translating to international number +358 504700715 . 10 -> 9 + 3 digits.

I have one number stored in my database as +237629567456 . When I review the declaration, I see it as 0629567456  which is incorrect. It should be 629567456 .

This bug is caused by the **convertToLocal** and **msisdnTransformer** functions in the client.

Our logic is too simple and must be replaced by this library to convert to and from country code + local numbers:

https://github.com/jackocnr/intl-tel-input

**Comment by nsamadavid** [comment]
Going through the library, i want to ask some this question:

on thinking about the implementation on this task, i see that using the library, there is need to reference the input as a node element and that may have an effect on the input form. should the input form interface be changed with respect to the library?

**Comment by euanmillar** [comment]
@nsamadavid I am not sure that the fix is working. I see that tests must have failed, but your solutions to fix the tests, are just bypassing what the tests should be checking for, and therefore I think something went wrong.

**Comment by euanmillar** [comment]
@nsamadavid I was speaking with Riku and we are thinking maybe to use this lib instead.  Dont worry about it, I will take a look and do this later. https://www.npmjs.com/package/google-libphonenumber

**Comment by Zangetsu101** [comment]
@euanmillar We need to deploy to config to make sure sms's are working properly
