### ISSUE TITLE
Allow special characters in human names

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#4763]
Allow the following special characters in human names:

`0-9` (Richard the 3rd)
`_` (John_Peter)
`-` (John-Peter)
`‘` (O’Neill)

Ensure that the characters work in:
- Birth & death declaration forms
- Certificates
- Review page
- Admin user creation

**Comment by Zangetsu101** [comment]
Reopening as this needs to go through QA first

**Comment by SyedaAfrida** [comment]
**Bug:**
Not all types of numbers are supported in name field
![special char bug2](https://user-images.githubusercontent.com/94350336/228158635-fe28f33f-6c68-4caa-b0ef-7f2742c0af61.png)
![special char bug1](https://user-images.githubusercontent.com/94350336/228158832-b3653b0c-7757-4e76-a635-2bf57bb91cb2.png)

**Comment by ShohelaTasin** [comment]
@anny320  This ticket is fixed! Can be closed Now!
![special_ch_check](https://user-images.githubusercontent.com/41486148/230368033-c1b28d2e-a960-4392-a566-e632da2d4a08.png)

**Comment by anny320** [comment]
Completed
