### ISSUE TITLE
Cannot input in any date fields of advance search

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4772]
**Bug description:**
Cannot input in any date fields of advance search

**Steps to reproduce:**
1. Login to RA/ Local or national Registrar
2.  Click Search option> Advance search
3.  Expand child details
4. Try to input in Date of birth field

**Actual result:**
User cannot input in any date fields of advance search

**Expected result:**
User should be able to input in date fields

**Screen recording:**
https://images.zenhubusercontent.com/91778759/25faff1d-9c9f-4b92-a195-2c50beed1e56/cannot_input_in_any_date_fields_of_advance_search.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by anny320** [comment]
completed
