### ISSUE TITLE
Add a “unit” option for new number inputs

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#4775]
When creating a new number input, the user should have the option to use any postfix like “cm” or  “€”. It should be possible to use a different one for different languages.

![image.png](https://images.zenhubusercontent.com/61dc3c9c2cdd207c355831e1/9419c9bc-a753-42f5-a3c2-9c3dc853ae3f)

### Dev tasks
- [x] Add a new input "Unit" for custom field configuration. This field should show a similar "Kg" suffix after the input field as the "Weight at birth" 
- [x] Add "Height at birth" field for birth declaration for in opencrvs-cameroon

**Comment by jpye-finch** [comment]
For the unit you could add kg, cm, m etc in the post fix right?
But best if this is done from a dropdown option so we know the type of input exactly.

**Comment by rikukissa** [comment]
@wilrona take a note of @jpye-finch 's comment. Let's use a dropdown for selecting the unit. I suggest we have the following units for now:

- `g`
- `kg`
- `cm`
- `m`

@jpye-finch anything you'd add?
