### ISSUE TITLE
Console error for Field agent

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4776]
**Bug description:**
Console error for Field agent

**Steps to reproduce:**
1. Login to Field agent
2.  Observe console log

**Actual result:**
Shows console error

**Expected result:**
Console error must be removed

**Screenshot:**
![con for fa.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/703e5ddf-a1d1-4b54-88cc-87e9105992c8)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by anny320** [comment]
The console error is fixed ![Screenshot 2023-03-13 at 11.16.26.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/5f92c3ce-307a-404d-9509-c40feb43244f)d
completed
