### ISSUE TITLE
Error shows when tried to view bookmark

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4777]
**Bug description:**
Error shows when tried to view bookmark

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Click Tracking ID> Advance search
3. Search any record
4. Bookmark that record
5. Logout
6. Login again
7. Click on that bookmark and observe 

**Actual result:**
Shows error "An error occurred while searching"

**Expected result:**
User should be able to view the record with bookmark

**Screen recording:**
https://images.zenhubusercontent.com/91778759/8974c8d8-b0bc-4793-bca5-f924e3d2f173/error_shows_when_tried_to_view_bookmark.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by anny320** [comment]
the error is still recurring https://www.loom.com/share/5fed95056d1d434db5774f911e18992f

**Comment by ShohelaTasin** [comment]
@anny320  This ticket is fixed! Can be closed!   
Recording : 
https://www.loom.com/share/3bb6b688a89c45cd93fe86ef1a82ef47

**Comment by anny320** [comment]
completed
