### ISSUE TITLE
Issue a marriage certificate

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#4791]

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![issued fixed](https://user-images.githubusercontent.com/94350336/228788164-d96de9a2-3f2c-435c-b4cb-26d6be0d7415.png)

https://user-images.githubusercontent.com/94350336/228788177-f5637648-3407-4068-8f9d-6556b4a21550.mp4

**Comment by anny320** [comment]
completed
