### ISSUE TITLE
No error message showing when Date of death is before Deceased DOB and deceased should be of any age

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4798]
**Bug description:**
1. No error message showing when Date of death is before Deceased DOB 
2. deceased should be of any age

**Steps to reproduce:**
1. Login to National system admin
2. Click Configuration> Declaration forms > Configure
3. Click Settings> make Toggle on for exact date of birth unknown
4. Logout
5. Login to Registrar
6. Declare a death event
7. In deceased details page Enter age less than 12 and observe
8. Enter age of deceased> Enter Date of death before date of birth and observe

**Actual result:**
1. User cannot enter age less than 12 yrs for deceased
2. User is able to enter Date of death before date of Birth when age is selected

**Expected result:**
1. Deceased should be of any age
2.  Date of death should not be before date of Birth. There should be validation message

**Screen recording:**
1.
![deceased can be of any age](https://user-images.githubusercontent.com/94350336/222669722-8c11d65a-bf03-4a57-9f6f-cef7eb7ccfdb.png)

2.

https://images.zenhubusercontent.com/91778759/8876a86f-d09c-4df4-892e-1b20b87dd248/no_error_message_showing_when_date_of_death_is_before_deceased_dob.mp4
**Tested on:**
https://login.farajaland-config.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![4798-2](https://user-images.githubusercontent.com/94350336/230851204-ac62b492-1fb8-4403-a445-345dde210ceb.png)
![4798 fixed](https://user-images.githubusercontent.com/94350336/230851211-1e7e6d09-51e7-4864-bd41-3cd87a719905.png)

**Comment by anny320** [comment]
completed
