### ISSUE TITLE
Office names interchanged in Illanga and Isamba district

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4800]
**Bug description:**
Ilanga district office should be under Ilanga district and Isamba district office should be under Isamba district

**Steps to reproduce:**
1. Login to local/ nation system admin
2. Go to Organisation / Team
3. Check office of Illanga district & Isamba district

**Screenshot:**
![2](https://user-images.githubusercontent.com/94350336/218389107-eb67b4d8-feb9-4ea2-a27b-382ea33a239e.png)
![1](https://user-images.githubusercontent.com/94350336/218389113-8eed663e-fe46-4cf1-80c8-3b2212f35507.png)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
There seems to be a discrepancy in  `partOf` column of `facilities/source/crvs-facilities.csv` & `admin2Pcode` of `administrative/source/farajaland.csv`.

**Comment by ShohelaTasin** [comment]
![Screenshot (27)](https://user-images.githubusercontent.com/41486148/232408474-09c961af-1d02-4bcc-85c6-1fb0a119cd34.png)
@anny320 this ticket is fixed! Can be closed Now!

Screenshots:  
![Screenshot (26)](https://user-images.githubusercontent.com/41486148/232407888-21dd8584-aad2-4f34-b415-d37fe4e02aba.png)
![Screenshot (24)](https://user-images.githubusercontent.com/41486148/232407894-287fa38b-b1ac-4375-8d22-fcd65fbbe340.png)
![Screenshot (25)](https://user-images.githubusercontent.com/41486148/232407899-a42895b7-d247-442f-938f-1c0c782a2320.png)

**Comment by anny320** [comment]
completed
