### ISSUE TITLE
Allow multiple signatures on a certificate

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#4806]
### Dev tasks
- [x] In create / edit user form there should be a signature field for all user types. 
This field should be optional for all users. 
- [ ] Create handlebars for at least the registrar and registrationAgent in the process. Both handlebars should be made with [nested input objects](https://handlebarsjs.com/guide/#nested-input-objects) so that all details of these staff members could be gotten from under the same namespace
   - `{{ registrar.signature }}` and `{{ registrationAgent.signature }}`

**Comment by naftis** [comment]
How would the SVG be created, if all signature fields are optional? Wouldn't it be difficult to design as we're not sure which ones will be present? Would the handlebars actually be something like

```
{{ signatures.primary }}
{{ signatures.optional[0] }}
{{ signatures.optional[1] }}
{{ signatures.optional[2] }}
```

**Comment by jpye-finch** [comment]
what if there are multiple reg agents in an office?
what if a registration agent wasn't involved in the record review (ie. sent it for approval)?

**Comment by jpye-finch** [comment]
One idea is:
- On the review page. The reg agent is prompted to add/append their digital signature to the record. 
- We would then know what signature to add to the certificate
- IF it gets rejected and sent for updates by the registrar then the agent signature would need to be removed

**Comment by rikukissa** [comment]
> How would the SVG be created, if all signature fields are optional? Wouldn't it be difficult to design as we're not sure which ones will be present? Would the handlebars actually be something like
> 
> ```
> {{ signatures.primary }}
> {{ signatures.optional[0] }}
> {{ signatures.optional[1] }}
> {{ signatures.optional[2] }}
> 
> --- or
> 
> {{#each signatures.optional}}
> <img src="{{this}}" />
> {{/each}}
> ```

@naftis I was thinking you could use if-statements to do

```
if fieldAgent
  render fieldAgent.signature
else if registrationAgent
  render registrationAgent.signature  
```

> what if there are multiple reg agents in an office? what if a registration agent wasn't involved in the record review (ie. sent it for approval)?

@jpye-finch I think same applies here. These placeholders would indicate the different roles that were part of the registration process. I'm guessing there cannot be multiple field-agents or registratiton agents as a part of one record, right?

**Comment by jpye-finch** [comment]
@rikukissa 
Another requirement which I am trying to get clarified. Is that these fields relate to the user who first started the declaration.
Which could be a FA. 

- Declaration date
- Declarant fullname
- Declarant status/role
