### ISSUE TITLE
All the 3 dot menu and profile icons not working after consecutive second click

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4810]
**Bug description:**
All the 3 dot menu and profile icons not working after second click

**Steps to reproduce:**
1. Login to National system admin
2. Click team/ Click Configuration certificates
3. Click 3 dot menu
4. Again click to close the modal
5. Again click to open the modal and observe
6. Click the profile menu
7. Again click to close the profile menu
6. Again click to open the profile menu and observe

**Actual result:**
All the 3 dot menu and profile menu modal do not open after consecutive second click

**Expected result:**
All the 3 dot menu and profile menu modal should work after every click

**Screen recording:**
https://images.zenhubusercontent.com/91778759/e88b1210-c609-4adf-b7d2-5535d88e659d/all_the_3_dot_menu_and_profile_icons_not_working_after_send_click.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by anny320** [comment]
completed
