### ISSUE TITLE
Discrepancy of registration status between Record Search API and Advanced Search 

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#4820]
**Describe the bug**
A registration status of REGISTERED, or CERTIFIED returns correct results using the Record Search API, but the Advanced Search UI is too specific. 

Searching for a REGISTERED record using the Advanced Search UI, where the status is CERTIFIED returns no result.  Using "Any status" works. 

**Potential solution:  Advanced Search UI should submit the **registrationStatuses** array from the value chosen item in the "Status of record" select** 

Expected result:

In the Advanced Search API, if the user selects REGISTERED, then results should be returned if the status is REGISTERED, CERTIFIED or CORRECTED.

![Screenshot 2023-03-06 at 18.09.46.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/9f43946b-2cbc-4940-b9d9-c7cb7bbc6a03)

Status is CERTIFIED so it should appear
![Screenshot 2023-03-06 at 18.09.55.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/195ae407-b524-4fe2-99bf-84d5b52fc675)

![Screenshot 2023-03-06 at 18.11.08.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/9e5528df-c45d-40e6-9905-25f77e4ab136)

![Screenshot 2023-03-06 at 18.11.17.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/914db4b6-4f4c-499f-87b7-5e915ef951f9)

Using the API it returns even if registration status param is REGISTERED

![Screenshot 2023-03-06 at 18.09.02.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/55e953f6-b161-4832-9c60-2a87f9de21b4)

**Comment by Zangetsu101** [comment]
@euanmillar I'm not sure if you remember but when we worked on the record search api, we restricted the declarations that can be viewed using this api to be only the `REGISTERED` and `CERTIFIED` ones. So no matter which status you provide in the payload (when using the record search jwt token) all the `REGISTERED` and `CERTIFIED` ones will be searched through. But that is not the case for Advanced Search UI. It has the fine grained control to search for declarations in specific statuses.

**Comment by Zangetsu101** [comment]
When "Registered" status is selected, return declarations in "REGISTERED, CERTIFIED, ISSUED" statuses

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/230031669-a33443c5-5c50-44d9-8323-1ac6ef652a4e.mp4

**Comment by anny320** [comment]
Completed
