### ISSUE TITLE
Bookmark icon is changed

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4821]
**Bug description:**
Bookmark icon is changed

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Make bookmark and observe icon

**Actual result:**

![bookmark icon is changed 1.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/0e60dc1c-be93-4ff2-9d35-d1e1cab7d298)
![bookmark icon is changed 2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/07dc6102-b9c4-42fc-98a9-6ee9cdc30c23)

**Expected result:**
![new.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/2ffd1c12-b326-4439-a72d-237138c32abe)
**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![icon](https://user-images.githubusercontent.com/94350336/227165661-89e7e933-e5a5-45c4-b2a4-eb8c0f0c128c.png)

**Comment by anny320** [comment]
completed
