### ISSUE TITLE
Place of birth configuration

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#4822]
https://balsamiq.cloud/sgl8zod/p4vxbmw/r8E04

### **New custom field:** Place of birth
- Municipality: list of municipalities with default to logged in user's office's municipality
- Locality: list of localities in selected municipality
  - note that we do not have support for dynamic options for custom fields, so just list all for now

### Rename Place of delivery as "Delivery site".
Delivery site dropdown should have two options
- Health facility
- Community (current Residential address)

**If Health facility selected**
- A list of health facilities just as we have today

**If Community selected**
- Show two list fields for **Municipalities** and **Localities**
- Default municipality from user’s office and allow change
- Filter localities list by municipality
- Provide “Not on the List” option and a text input

**Comment by rikukissa** [comment]
Blocked as we have no locality -> municipality mapping table yet

**Comment by Dahlia-NLD** [comment]
Place of birth is not Site of birth. Place of Birth is ALWAYS the locality regardless of the delivery site (hospital, home, prison, transportation, etc).

The list suggested here is for Delivery Site not place of birth.

**Comment by rikukissa** [comment]
@Dahlia-NLD @djiathink please make sure the Balsamiq designs are up to date and reflect Dahlia's comment above
