### ISSUE TITLE
As a OpenCRVS user, I want to verify a certificate

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4828]
### Description
- adds login screen when someone scans the QR code on a certificate
- adds close button 

### Acceptance criteria

GIVEN I scan a QR code of a certificate
THEN navigate to the OpenCRVS login screen

GIVEN I am a OpenCRVS user (**logged out**)
WHEN I scan a QR code
[THEN navigate to the login screen](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=14168%3A101158&t=TUbptlYW37XHRbtg-1)

GIVEN I am a OpenCRVS user (**logged in**)
WHEN I scan a QR code
[THEN navigate to QR loading screen](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=14282%3A102638&t=TUbptlYW37XHRbtg-1)

GIVEN I am viewing the certificate data
WHEN I click close
THEN navigate back to my default page (eg. work-queue for Registrar, Performance for Performance Manager)

GIVEN a user verify a certificate
THEN a log of this action should show in Record Audit. 

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=10573%3A105397&t=TUbptlYW37XHRbtg-1

### Dev tasks

- [x] Currently the verify certificate page is using an unprotected route. We need to move that into a protected route.
- [x] If the user is not logged in, the login modal would open up. We need to provide a redirect url before sending the user back to login. Either keep the redirect URL in redux or URL param.
- [x] After the user has logged back in, send the user back to the app using the redirect url
- [x] Remove the anonymous directive from the query used

**Comment by cinojopencrvs** [comment]
@SyedaAfrida @anny320 Consider this ticket and ACs while writing the verify a certificate test cases.

**Comment by cinojopencrvs** [comment]
@Zangetsu101 for 1.3 scope

**Comment by jpye-finch** [comment]
@SyedaAfrida yes all user types can scan qr, login and view the partial record details

**Comment by Zangetsu101** [comment]
@jpye-finch Are there any changes in the RecordAudit row for the verify certificate action? Because previously it was by an anonymous user but not anymore

**Comment by jpye-finch** [comment]
@Zangetsu101 yes good point. The Record Audit should document who did the action.

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
https://drive.google.com/file/d/1cvjb2Rn9IVH_10cgkvKMsTEQ783qW6v2/view?usp=share_link

**Comment by anny320** [comment]
Completed
