### ISSUE TITLE
Handle the marriage event in webhooks

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#4832]
Currently the marriage events forwarded to webooks are erroring. We either need to handle marriage events in webhooks or not send them to it at all

**Comment by rikukissa** [comment]
@euanmillar would you consider this a bug, missing functionality or something else? I'll bump priority to medium now as it seems like something we want to add sooner or later

**Comment by euanmillar** [comment]
@rikukissa I think this is not a bug.  It's a feature of completing Marriage registration.  It should be in 1.7.0 milestone

**Comment by euanmillar** [comment]
Custom events will enable for all future countries #7052
