### ISSUE TITLE
As a field agent I would like to view the team page of my office

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#4833]
### Description
Tasks
- Adds team  to the sidenav of a Field agent view
- Enables the field agent to view details of the team for his office
- No links are enabled to view the user audit.
...

### Acceptance criteria

GIVEN a field agent logs in
WHEN he scrolls the SideNav
THEN he can see a link to the team page

GIVEN  a field agent clicks on the team page
WHEN the page loads
THEN he can see details of his office team members

GIVEN a field agent clicks on a name in the team page
THEN nothing happens - not redirected to user audit view. FA has no access to User Audit

### Design

https://www.notion.so/opencrvs/View-office-team-ddc8d0e18c9440ebb5f47fb10ed34256

##![Screenshot 2023-03-09 at 11.45.08.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/e67c47b9-4983-4981-831d-b6dcba72a325)# Dev tasks

- [ ] Task 1

**Comment by rikukissa** [comment]
@jpye-finch do you think this is still relevant? Is this tech related or more of a functional enhancement?

**Comment by rikukissa** [comment]
Note: there's a security implication for this as well #7498

**Comment by euanmillar** [comment]
Closing as stale
