### ISSUE TITLE
As a Registration Agent and as a Registrar I would like to view the team page of other offices

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#4834]
### Description
- Adds a location search button on the team page of the registration agent and registrar
- Disables any user audit links for other offices that are not the registration agent or registrar office

### Acceptance criteria

GIVEN when a registration agent or registrar loads the team page
THEN they can see a location search button to enable searching team members from other offices

GIVEN a registration agent or registrar  clicks the search button on the team page
WHEN they enter another office name
THEN they can see team members of the other office details

GIVEN a registration agent or registrar   click on the username of the team members
THEN they are not redirected to the user audit page of a team member from another office. They should not have access to the user audit page of team members from other offices.

### Design

https://www.notion.so/opencrvs/View-office-team-ddc8d0e18c9440ebb5f47fb10ed34256
![Screenshot 2023-03-09 at 12.16.46.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/b97de142-2899-4f64-91ea-f186af1ecb9b)

### Dev tasks

- [ ] Task 1

**Comment by euanmillar** [comment]
Closing as stale
