### ISSUE TITLE
Add missing fields & reorganise mother & father sections

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#4838]
Reference:
https://balsamiq.cloud/sgl8zod/p4vxbmw/r8E04

**Add the following fields**
- [x] Domicile
- [x] (Skip, done in another issue) Profession
- [x] Phone number
- [x] Nationality
- [x] Reason of presence in Cameroon
- [x] Type of document
- [x] Number of children living in lifetime
- [x] Number of fetal deaths
- [x] (Skip, done in another issue) Date of last living death

**Remove these fields**
- [x] Occupation
- [x] Usual place of residence
- [x] No. of previous births

**Change / Rename**
- [x] Change label National ID -> Document ID
- [x] Level of education options
- [x] Marital status options

After making these changes, make sure 
- the form is in the correct order
- same fields are also added to Father (if in Balsamiq)

**Comment by Dahlia-NLD** [comment]
There is a mistake here. There is profession on mother page, it is correct on the system.
