### ISSUE TITLE
Bugs for configure the SMS message sent to informant 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4845]
**Bug description:**
Bugs for configure the SMS message sent to informant:
1. Message not sent for Notification sent to Office
2.  Sms is received for Declaration registered even if toggle is off

**Steps to reproduce:**
1. Login to National system admin
2. Click Communications › Informant notifications
3. Make toggle on for Notification sent to Office
4. Make toggle off for Declaration registered
5. Click Save
6. Login to FA
7. Sent an incomplete birth/ death application and wait for sms
8. Again login to Registrar
9. Go to Ready to review
10. Register any birth/ death event and check sms

**Actual result:**
1. Message not sent for Notification sent to Office
2.  Sms is received for Declaration registered even if toggle is off

**Expected result:**
1. Since toggle is ON for Notification sent to Office, user should receive sms
2. Since toggle is OFF for Declaration registered, User should not receive sms

**Screen recording:**

https://images.zenhubusercontent.com/91778759/636e66ac-7afb-44e3-b6a7-32e133d8240b/farajaland_crs____10_march_2023.mp4

![sms pic.jpg](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/4c9586e4-2d5c-4edb-b4b0-4ec10b867d86)

**Tested on:**
https://login.farajaland-config.opencrvs.org/?lang=en

**Comment by sadmananik** [comment]
The second bug is fixed. But the first bug is clocked until infobip error is debugged properly.

**Comment by SyedaAfrida** [comment]
@anny320 these bugs are fixed and can be closed
1.
![Screenshot_20230410-130215_Messages](https://user-images.githubusercontent.com/94350336/230846547-ab89eb0f-a283-4a5a-83d4-79c89e516968.jpg)

2. No sms received for registering when toggle is off

https://user-images.githubusercontent.com/94350336/230846673-c9e3f484-4291-4198-b2b4-1097270c0161.mp4

**Comment by anny320** [comment]
completed
