### ISSUE TITLE
Though all the fields are filled up, Sent for approval and Register button still remains disabled

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4846]
**Bug description:**
Though all the fields are filled up, Sent for approval and Register button still remains disabled

_Note: This bug also appears in review page of correction record_

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Click Ready to review/ Requires update
3. Click download> Assign> Review
4. Observe Sent for approval and Register button

**Actual result:**
Though all the fields are filled up, Sent for approval and Register button still remains disabled

**Expected result:**
If all the fields are filled up, Sent for approval and Register button should be enabled

**Screen recording:**

https://images.zenhubusercontent.com/91778759/7b89a676-20cd-4899-8e66-5ea1cda0f3ec/though_all_the_fields_are_filled_up__sent_for_approval_and_register_button_still_remains_disabled.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by anny320** [comment]
completed working correctly.

https://www.loom.com/share/300d2f49462b4e46b134dfc18cd2e19d
