### ISSUE TITLE
correction record flow is broken after a record is certified and issued

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4856]
**Bug description:**
Correction record flow is broken after a record is certified and issued

**Steps to reproduce:**
1. Login to registrar
2. Click Ready to print
3. Print any record in Print in advance
4. Issue that record from Ready to issue
5. Search that record with tracking ID / name
6. Click on that record
7. Click Correct record and observe the flow

**Actual result:**
In correction record review page, general review page is showing

**Expected result:**
Should show correct record review page

**Screen recording:**

https://images.zenhubusercontent.com/91778759/24255f86-827d-45c7-814b-aea4a3dba673/correction_record_flow_is_broken_after_a_record_is_certified_and_issued.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
Though the previous bug is fixed but a similar type of bug is appearing in correction record.
**Bug:**
Record cannot be corrected ( no change link and continue link available), after a duplicate record is marked as not a duplicate and issued
https://drive.google.com/file/d/18TSq28hHHBdBdeHlnfPjNgZHPgg4l_VQ/view?usp=share_link

**Comment by Nil20** [comment]
https://github.com/opencrvs/opencrvs-core/pull/5071
this PR has this issue fixed

**Comment by SyedaAfrida** [comment]
Though the old bug is fixed, a similar bug appeared after this fix.

Correct record option should not appear when clicked on Ready to issue tab . Correct record should only appear in Ready to print and after searching an issued record.
![correct record](https://user-images.githubusercontent.com/94350336/231719636-15649d8a-bf9e-4826-a53e-d8eadecff1e7.png)

**Comment by Nil20** [comment]
https://github.com/opencrvs/opencrvs-core/pull/5100
this PR has this recent issue fixed

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
https://www.loom.com/share/3e76e6d3d2924b289c3097815daefab0

**Comment by anny320** [comment]
completed
