### ISSUE TITLE
Create custom time input

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#4860]
See Death form -> Information on death -> Time of death for reference.
Create an input that takes two integers (hours and minutes). Inputting a zero-prefixed value is also allowed 03. 
The input emits the submitted value as in the HH:MM format.

When this input is ready. Place it on the Death form -> Information on death page correctly as per [Balsamiq design](https://balsamiq.cloud/sgl8zod/p4vxbmw/rB1BF).

**Comment by Dahlia-NLD** [comment]
If I move forward in pages then press Back, the entered time is lost.

The message about the correct format is not red. Wasn't noticeable.
