### ISSUE TITLE
As a  Performance manager or National System Admin, I would like my default landing page after login to be the dashboard

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#4868]
### Description
- Updates default landing page after login to be the dashboard instead of the old performance page.
...

### Acceptance criteria

GIVEN a Performance manager or National System Admin logs in successfully,
WHEN the page loads
THEN they see the dashboard as a default view.

### Design

(Link to Figma)

### Dev tasks

- [ ] In `OfficeHome`, if the user is a performance manager, national registrar, or national system admin, redirect to dashboard instead of showing the default home. https://github.com/opencrvs/opencrvs-core/blob/afbcf128c9fcce81a16322366bbf8c20c46ed514/packages/client/src/views/OfficeHome/OfficeHome.tsx#L286

**Comment by Zangetsu101** [comment]
@anny320 There is a "X" button in dashboard which goes back to the previous page. But if the dashboard page is the landing page, then there won't be any page to go back to. So what happens is that clicking "X" doesn't do anything.

**Comment by jpye-finch** [comment]
@Zangetsu101 @anny320  
Suggest we navigate back to the Reports page:
Performance Manager -> Reports
System Admins -> Reports

**Comment by Zangetsu101** [comment]
We can perhaps store a temporary state in the router to detect if are being redirected to the dashboard again after clicking the cross button, in that case, redirect to the reports page

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
https://www.loom.com/share/2255550923f6480cbecea2a36e97cedd

**Comment by anny320** [comment]
completed
