### ISSUE TITLE
System crash occurs in performance page when clicked on the link( in Progress, any status) of Registration by status

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4876]
**Bug description:**
System crash occurs in performance page when clicked on the link( in Progress, any status) of Registration by status
**Steps to reproduce:**
1. Login to RA/ local registrar
2. Click performance
3. Click in progress link of Registration by status and observe
4. Select any status from event filter and observe

**Actual result:**
1. When clicked in progress shows- "Sorry, we couldn't load the content for this page"
2. When clicked any status, system crash occurs

**Expected result:**
user should be able to see both in progress and any status records

**Screen recording:**

https://images.zenhubusercontent.com/91778759/aadf55f0-49eb-49f2-9533-0a80883e9444/system_crash_occurs_when_clicked_on_the_link__in_progress__any_status__of_registration_by_status.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by ShohelaTasin** [comment]
@anny320 This ticket is fixed! Can be closed now!

**Recording :** https://www.loom.com/share/d45afdca842c42cf8144241a3a362206

**Comment by anny320** [comment]
completed
