### ISSUE TITLE
Minio attachment URLs need to be secured

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#4896]
- [x]  Write a endpoint in gateway to fetch minio documents that validate token
- [x] Modify fetchAllMinioUrlsInAttachment function and use the newly create gateway endpoint to fetch documents in client
- [x] In `opencrvs-core/packages/client/src/src-sw.js` and `postMinioUrlsToServiceWorker` function change minio url with new endpoint that matches the regex in workbox

**Comment by euanmillar** [comment]
Can we try and see if this solution works: https://stackoverflow.com/questions/56627446/docker-compose-how-to-use-minio-in-and-outside-of-the-docker-network/61214488#61214488
