### ISSUE TITLE
Flag declaration as potential duplicate by system

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#4901]
- [x] Similar to [updateCompositionWithDuplicates](https://github.com/opencrvs/opencrvs-core/blob/develop/packages/search/src/features/registration/birth/service.ts#L425), we need to update the task associated with the composition and add a new extension FLAGGED_AS_POTENTIAL_DUPLICATE. Taking a look at b678719 might help
- [x] In record audit, for FLAGGED_AS_POTENTIAL_DUPLICATE action, show the system as the user in the by column & empty for the role column.
- [x] Show the potential duplicate trackingIds in the modal

Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=10381-64768&t=VYDvwPiJIDjzHJLh-0

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/230350013-25f47392-55f5-4f7c-8edd-1fa348ecaca0.mp4

**Comment by anny320** [comment]
Completed
