### ISSUE TITLE
Resend sms feature showing error toast when clicked from Verification code page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4902]
**Bug description:**
Resend sms feature showing error toast when clicked from Verification code page. However the feature is working correctly. User is able to receive sms when clicked on resend sms.

**Steps to reproduce:**
1. Login to any user with username and password> Click continue
2. Click Resend sms

**Actual result:**
On first click shows nothing
On second click showing error toast "Incorrect verification code. Please try again"

**Expected result:**
should show "Invite sent"

**Screen recording:**

https://images.zenhubusercontent.com/91778759/b19fdb07-d315-4445-a33b-383059088070/resend_sms_feature_showing_error_toast_when_clicked.mp4

**Tested on:**
https://login.farajaland-config.opencrvs.org/

**Comment by SyedaAfrida** [comment]
when clicked Resend sms should show toast " Invite sent"

https://user-images.githubusercontent.com/94350336/230875643-e9c73ca2-b357-4f4d-82b8-79e8d05770cd.mp4

**Comment by Zangetsu101** [comment]
@SyedaAfrida I'm not sure if we really need a toast because if you take a look below the logo it says "Authentication code resent". One improvement we should do is to disable the resent sms button for 30 seconds or so after clicking it

**Comment by anny320** [comment]
completed
