### ISSUE TITLE
When mother's name is same but their nid and DOB is different , there is a duplicate warning toast  

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4911]
**Bug description:**
When mother's name is same but their nid and DOB is different , there is a duplicate warning toast  

**Steps to reproduce:**
1. Login as FA/ RA/ Registrar
2. Create a birth application
3. Note Child's first and last name,  mother's NID, First name, Last name and DOB
4. Submit the record
5. Create another birth record
6. Keep Child's first and last name same
7. Keep mother's first and last name same
8. Change mother's NID and DOB
9. Submit the record and observe

**Actual result:**
there is a duplicate warning toast  

**Expected result:**
There should be no duplicate warning toast as two mother may have same name

**Screen recording:**
https://www.loom.com/share/60306b0b7fc1407781e794a5f365fce1

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://www.loom.com/share/b447448863924577bc95425dee728ecb
Uploading 4911 fixed.mp4…

**Comment by anny320** [comment]
completed
