### ISSUE TITLE
In duplicate comparison page the DOB of child or date of death is automatically becoming same

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4916]
**Bug description:**
In duplicate comparison page the DOB of child or date of death is automatically becoming same

**Steps to reproduce:**
1. Login as RA/ Registrar
2. Click download> assign> review to any not duplicate record
3. Observe the date of death/ DOB in review page
4. Now  Click download> assign> review to that record's duplicate record
5. Click the tracking ID tab of the old record and observe DOB/ Date of death

**Actual result:**
the DOB of child or date of death is automatically becoming same even though they were different 

**Expected result:**
the DOB of child or date of death should be different according to the review page

**Screen recording:**
https://www.loom.com/share/cfac42478f1d48ca8b7d4a0ff635ecc5

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/230355028-cd08e00b-1935-405e-a2ad-69b5ad5f96d9.mp4

**Comment by anny320** [comment]
Completed
