### ISSUE TITLE
Registration location data missing in certificate

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4924]
**Bug description:**
Registration location data missing in certificate

**Steps to reproduce:**
1. Login to RA/ registrar
2. Click ready to print
3. Click Print
4. Go to certificate preview page and observe

**Actual result:**
Though registration office is appearing in certificate, location(province/ district) is not showing

**Expected result:**
In certificate registration location(province/ district) should show

**Screenshot:**
![svg image.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/de786276-1483-4b54-ad87-2529d923c7ef) 
![cer imag.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/3422ff02-91bb-4a41-9fca-cc979abdc255)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![download (2)](https://user-images.githubusercontent.com/94350336/231138112-0f7905f0-c635-4cc4-8a7f-99d5c86f938b.png)

**Comment by anny320** [comment]
completed

**Comment by anny320** [comment]
completed
