### ISSUE TITLE
feat: Field Agent can select which registration office to send notifications too

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4926]
### Description
- Allows a Field Agent to choose an Office to send a declaration to
- OnReview page. Select dropdown has list of Offices with a Registrar
- Select is defaulted to FAs Supervisory office

### Acceptance criteria

GIVEN I am Field Agent
WHEN on the review page
THEN default the select to my supervisory office

GIVEN I am Field Agent
WHEN I click on the select 'Assign a registration office' 
THEN I can select an office to send the declaration too
THEN only show locations with a Registrar in. (filter locations with no Registrar/ not a Registration Office)

GIVEN I am Field Agent
WHEN on the review page
THEN default the select to my supervisory office

GIVEN I click Send for review
THEN send the declaration to the selected office 

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=14744%3A115508&t=XGHsAYNhabHx8Ed9-1

![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/746a1a8c-b052-4b4b-a48d-ea2e39e4e585)

### Dev tasks

- [ ] Task 1

**Comment by jpye-finch** [comment]
@rikukissa how was this feature built for Cameroon? is it available in Core?

**Comment by euanmillar** [comment]
@jpye-finch @eduffus will this not be addressed by #6454 ?

**Comment by eduffus** [comment]
#6454 will address this issue in a more consistent way. It should not be the FA who decides where the declaration goes - instead the administrative structure will define which offices will review the declarations from sub-offices.

**Comment by jpye-finch** [comment]
@eduffus @euanmillar 
This came from Cameroon, tho not applicable with their decentralised setup....

A Field Agent is assigned to an office. Where the bulk of declaration should be sent to. However they have the option to send to another office. As the informant lives closer to that office.

**Comment by euanmillar** [comment]
Closing as stale
