### ISSUE TITLE
In mobile view, when navigate to the comparison review page of a duplicate record the tracking id is getting changed

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4927]
**Bug description:**
In mobile view, when navigate to the comparison review page of a duplicate record the tracking id is getting changed

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Click download>Assign> Review
3. Click tracking id tabs

**Actual result:**
tracking id is getting changed

**Expected result:**
tracking id should not change

**Screen recording:**

https://images.zenhubusercontent.com/91778759/38bf2302-4d3a-4810-a1c5-d676254eb018/comparison_bug.mp4
**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed.

https://user-images.githubusercontent.com/94350336/230578451-b136e1c9-fd1e-4a65-b2ad-547352e9cbe3.mp4

**Comment by anny320** [comment]
Completed
