### ISSUE TITLE
When RA mark a record as duplicate, registrar can see the record as assigned to RA in workqueue when they search

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4928]
**Bug description:**
When RA mark a record as duplicate, registrar can see the record as assigned to RA in workqueue when they search

**Steps to reproduce:**
1. Login to RA
2. Click Download>Assign> Review any duplicate record
3. Click Mark as duplicate
4. Logout
5. login to Registrar
6. Search that record with tracking id 
7. Observe the workqueue and observe record audit page

**Actual result:**
In Workqueue the record is showing assigned to RA but in record audit it is not. Actually the record is not assigned to RA

**Expected result:**
In Workqueue the record should not show assigned to RA 

**Screen recording:**

https://www.loom.com/share/94d40b1dc4714e4689aeaf3086a6ed5a
**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
https://www.loom.com/share/1004cf3ae2d745f0aeb286daa8487c38

**Comment by anny320** [comment]
completed
