### ISSUE TITLE
duplicate icon not showing in view page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4929]
**Bug description:**
duplicate icon not showing in view page

**Screen recording:**
https://images.zenhubusercontent.com/91778759/e640b532-7904-48d5-8f2e-411c6d83e607/duplicate_icon_not_showing_in_view_page.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by ShohelaTasin** [comment]
@anny320 This ticket is fixed! Can be closed!

Recording : https://www.loom.com/share/51d394d69bc04dd98e7d5a499d655dc8

**Comment by anny320** [comment]
Completed
