### ISSUE TITLE
Copy change in name field

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4944]
**Bug description:**
Copy change in name field

**Steps to reproduce:**
1. Declare a birth/death event
2. Observe the name fields with invalid input in : Child/ mother/father/ informant/ deceased details page
3. Again Login to local/national system admin
4. Click Team> Create new user
5. Observe the name fields with invalid input

**Actual result:**
Shows " Must contain only English characters" 

**Expected result:**
should show error message: " Input contains invalid characters. Please use only letters (a-z), numbers (0-9), hyphens (-), and underscores (_)" 

**Screenshot :**
![special char bug1.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/7c5cdfc7-5c3d-40a4-8672-2ad97863b868)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
@anny320 @SyedaAfrida Shouldn't we mention apostrophe(') as well?

**Comment by Zangetsu101** [comment]
Input contains invalid characters. Please use only letters (a-z, A-Z), numbers (0-9), hyphens (-), apostrophes(') and underscores (_)

**Comment by anny320** [comment]
@Zangetsu101 proposed copy is ok, please proceed

**Comment by ShohelaTasin** [comment]
@anny320  This ticket is fixed! Ready to deploy! 
![bugReport](https://user-images.githubusercontent.com/41486148/237058735-7655cb7e-8bbd-4c2f-9a0e-b6b398e5d569.png)

**Comment by Zangetsu101** [comment]
@ShohelaTasin That seems to be the correct warning message tho?

**Comment by ShohelaTasin** [comment]
@anny320  This ticket is fixed! Can be closed now!

**Comment by anny320** [comment]
completed
