### ISSUE TITLE
When a incomplete marriage declaration with only bride's name is saved as draft or sent incomplete then & appears before bride's name in review page, workqueue , search result and record audit page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4946]
**Bug description:**
When a incomplete marriage declaration with only bride's name is saved as draft or sent incomplete then & appears before bride's name in review page, workqueue  search result and record audit page

**Steps to reproduce:**
1. Login to FA
2. Declare a marriage event
3. Enter only bride's name > Click Save & Exit
4. Observe the draft in workqueue, Record audit page, search result and review page
5. Click sent review from review page
6. Observe the record from sent from review

**Actual result:**
& appears before brides name

**Expected result:**
& should not appear before bride's name

**Screen recording:**

https://images.zenhubusercontent.com/91778759/fc381f06-84fe-4c64-b9a9-21f1f2ffd650/farajaland___google_chrome___28_march_2023.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
This bug is not fixed properly. 
When an incomplete marriage record is submitted with only bride's name, then no name provided appear in workqueue and after assigning shows undefined in workqueue.

https://www.loom.com/share/763aa84198d04b0382ddde845f8e3745

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://www.loom.com/share/cbd27bbeb52b45a7bb94e397290522e0

**Comment by anny320** [comment]
completed
