### ISSUE TITLE
Incomplete declarations not appearing in In progress> Field agent workqueue

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4947]
**Bug description:**
Incomplete declarations not appearing in In progress> Field agent workqueue

**Steps to reproduce:**
1. Login to FA
2. Declare a marriage event
3. Send an incomplete  record
4. Logout
5. Login to RA/ Registrar
6. Click In progress> Field agent and observe workqueue

**Actual result:**
Incomplete declarations not appearing in In progress> Field agent workqueue but appears when searched with tracking Id

**Expected result:**
Incomplete declarations should appear in In progress> Field agent workqueue

**Screen recording:**

https://images.zenhubusercontent.com/91778759/cb37cfa8-640c-4dd2-af19-7868a8a96fb7/incomplete_declarations_not_appearing_in_in_progress__field_agent_workqueue.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![4947 fixed](https://user-images.githubusercontent.com/94350336/230588475-5177a29d-6b24-488e-af1e-90a01ea43463.png)

**Comment by anny320** [comment]
completed
