### ISSUE TITLE
Date of event do not appear in draft of a marriage event

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4949]
**Bug description:**
Date of event do not appear in draft of a marriage event

**Steps to reproduce:**
1. Login to FA/ RA/ registrar
2. Declare a marriage event
3. Add date of marriage
4. Click Save & exit
5. Observe the record in workqueue

**Actual result:**
Date of event do not appear in draft of a marriage event

**Expected result:**
Date of event should appear in draft of a marriage event

**Screen recording:**

https://images.zenhubusercontent.com/91778759/4e08ae82-ded7-41d8-bc40-727f0e686453/date_of_event_do_not_appear_in_draft_of_a_marriage_event.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![4949 fixed](https://user-images.githubusercontent.com/94350336/230582383-437383f8-fc9c-48b3-8ffe-5078bc6dfa63.png)

**Comment by anny320** [comment]
Completed
