### ISSUE TITLE
CAMEROON: Declarant/informant page in Birth form

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4952]
### Description
- THIS IS CUSTOM FOR CAMEROON. NOT FOR CORE
- Informant = person providing information (as we have today)
- Declarant = the person submitting the form the registration office (eg. FA or the informant if starting in the office)
- **Informant details page is always shown**

### Acceptance criteria

GIVEN the informant is a Mother or Father
WHEN on the Declarant page
[THEN hide the Informant details section
](https://www.figma.com/file/YJwg976XbGk1qau5Rvu4qZ/Declaration%2FCameroon%2FBirth?node-id=2558-660&t=OKQCKl9Ji4IBnlHI-4)

GIVEN a Field Agent is completing the declaration
WHEN on the Declarant page
THEN populate the FA details

GIVEN the details entered for the Declarant
WHEN printing a certificate
THEN populate the certificate with the declarant details
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/0183baf6-9c98-4e16-9f34-c553b855e7cd)

IF Declarant = Informant
THEN {{ DECLARANT STATUS }} = Informant type eg. Mother

IF Declarant does not = Informant
THEN {{ DECLARANT STATUS }} = User status (new form field in user creation)

### Design
https://www.figma.com/file/YJwg976XbGk1qau5Rvu4qZ/Declaration%2FCameroon%2FBirth?node-id=2529-383&t=OKQCKl9Ji4IBnlHI-4

### Dev tasks

- [ ] Task 1

**Comment by Dahlia-NLD** [comment]
There is a mistake here on the last sentence. The status must always read from the input on the declaration form. The declaration form may read from the user data but the certificate always reads from the declaration.
