### ISSUE TITLE
CAMEROON: Declarant/Informant page in Death form

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4953]
### Description
- THIS IS CUSTOM FOR CAMEROON. NOT FOR CORE
- Informant = person providing information (as we have today)
- Declarant = the person submitting the form to the registration office (eg. FA or the informant if starting in the office)

### Acceptance criteria

GIVEN an informant is selected and main contact added
THEN show the Informant/Declarant page

GIVEN a Field Agent is completing the death declaration
WHEN on the Declarant page
THEN populate the FA details

GIVEN the form was started by a Registrar or Registration agent
WHEN on the Declarant page
THEN auto check the checkbox 'Same as informant' 

GIVEN the details entered for the Declarant
WHEN printing a certificate
THEN populate the certificate with the declarant details

IF Declarant = Informant
THEN {{ DECLARANT STATUS }} = Informant type eg. Son

IF Declarant does not = Informant
THEN {{ DECLARANT STATUS }} = User status (new form field in user creation)

### Design
https://www.figma.com/file/kJoT6Eth5nngbAWgNbYU1s/Untitled?node-id=0%3A1&t=RBVrCoAXnnvUmCmi-1

### Dev tasks

- [ ] Task 1

**Comment by rikukissa** [comment]
Implemented by:
https://github.com/opencrvs/opencrvs-core/issues/4977

**Comment by Dahlia-NLD** [comment]
Test Cases:
TC1: Check that the page always appears
TC2: Check that if a Field Agent is completing the death declaration, FA details appear (check all fields)
TC3: Check that if it is a Registrar or Registration agent, checkbox 'Same as informant' is auto-checked and can be unchecked and data changed
TC4: Check that declarant data shows on printed certificate
TC5: Check that on the certificate, IF Declarant = Informant; {{ DECLARANT STATUS }} = Informant type eg. Son
IF Declarant does not = Informant, THEN {{ DECLARANT STATUS }} = What is in the Status field

Note on the ticket: It says that the declarant status is read from the user profile. It should be read from this form. The value on the user profile is only defaulted here if FA.
