### ISSUE TITLE
CAMEROON: Adds freeform field 'Status' to user creation

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4954]
### Description
- CUSTOM FOR CAMEROON. NOT FOR CORE
- Adds mandatory field to user creation 'Status' for all users
- Status is kinda like role.. but is a custom of describing their role

Q. Will the system admin know what the user chosen Status is???
Q. Let users change their status in Settings? 
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/3cf12cd8-64a1-4af4-be4c-abf2039925fc)

### Acceptance criteria

GIVEN I am a system admin
WHEN I am creating a new user
THEN I can add a status 
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/e50d46b1-10a9-410c-99da-49662ff1bc6c)

GIVEN a Field agent create a declaration
THEN use their status on the certificate 
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/f59aa623-2ba8-4d69-84f7-bac562178b10)

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=14830%3A108805&t=HrRBs0pgxzLHMnID-1

### Dev tasks

- [ ] Task 1

**Comment by Dahlia-NLD** [comment]
User can't now change their status, but since we have no explicit requirement for this, we can close for now.
