### ISSUE TITLE
Cannot search a marriage record with name and NID

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4956]
**Bug description:**
Cannot search a marriage record with name and NID

**Steps to reproduce:**
1. Login with FA/ RA/ Registrar
2. Create a marriage declaration
3. Search the declaration with Name / NID and observe
 
**Actual result:**
Cannot search a marriage record with name and NID can only search with tracking ID and Phone number

**Expected result:**
should be able to search with all search criteria

**Screen recording:**
https://www.loom.com/share/701de34e1ee3422bab5746a42bc257c8

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by ShohelaTasin** [comment]
@anny320  This ticket is fixed! Can be closed Now!

**Recording :** https://www.loom.com/share/773be9c9bf914eac968bac462ae589a0

**Comment by anny320** [comment]
completed
