### ISSUE TITLE
In Performance completeness rate, duplicate rows are appearing in table

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4957]
**Bug description:**
In Performance completeness rate, duplicate rows are appearing in table

**Steps to reproduce:**
1. Login to any user except FA
2. Click Performance
3. Click View in Completeness rate
4. Observe the table

**Actual result:**
In Performance completeness rate, duplicate rows are appearing in table

**Expected result:**
Table should show all the months

**Screenshot:**
![completeness view bug.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/81a9bee4-5cb5-47ea-a0c1-42daa6c58178)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
This might be similar to #4482 where we need to use flux for querying month wise data. Most likely when the time is close to the start or end of the month, duplicate time ranges are getting populated

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![4957 fixed](https://user-images.githubusercontent.com/94350336/231112317-590b6590-3413-47e1-8ff2-1e55b3df2ca8.png)

**Comment by anny320** [comment]
completed
