### ISSUE TITLE
when supporting documents are added in marriage declaration, record is not submitted properly and stays in outbox

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4961]
**Bug description:**
when supporting documents are added in marriage declaration, record is not submitted properly and stays in outbox

**Steps to reproduce:**
1. Login to FA
2. Declare a marriage event
3. Add supporting documents and submit

**Actual result:**
Record is not submitted properly and stays in outbox

**Expected result:**
Should be able to submit marriage declaration with supporting documents

**Screen recording:**
![ss.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/4bb4c8f5-6e82-4a3d-a486-84157013497a)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by ShohelaTasin** [comment]
@anny320 this ticket is fixed! Can be closed now!

Screenshot : 
![BugRes](https://user-images.githubusercontent.com/41486148/231115453-286050f2-03ec-42e6-86ee-18cd1d9e53bd.png)

**Comment by anny320** [comment]
completed
