### ISSUE TITLE
In outbox bride's name appear twice when sending a marriage declaration

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4963]
**Bug description:**
In outbox bride's name appear twice when sending a marriage declaration

**Steps to reproduce:**
1. Login to FA/ RA/ registrar
2. Declare a marriage event
3. Submit the record and observe outbox

**Actual result:**
In outbox bride's name appear twice and groom's name is not shown

**Expected result:**
In outbox groom's name & bride's name should show for a marriage declaration

**Screenshot:**
![outbox1.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/2e18c7dd-5e70-48b4-9cc3-b391ac0b5700)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![4963 fixed](https://user-images.githubusercontent.com/94350336/231139866-fd6391ff-46d1-4aeb-a1cd-e2252f10c76c.png)

**Comment by anny320** [comment]
completed
