### ISSUE TITLE
Marriage declaration disappears after submission

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4964]
**Bug description:**
Marriage declaration disappears after submission

_Note: This might occurs for large size of file in signature. There should be a validation for the size of file in signature_

**Steps to reproduce:**
1. Login to FA
2. Declare a marriage event
3. Submit the complete declaration and observe

**Actual result:**
After going to outbox the record do not appear in any workqueue

**Expected result:**
All marriage record should appear in workqueue

**Screen recording:**

https://images.zenhubusercontent.com/91778759/95e228d3-7efd-4c21-a3e1-95d691cfc0ff/marriage_declaration_disappears_after_submission.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
Let's add a 2mb size limit to the signatures

**Comment by Zangetsu101** [comment]
We need to store the signature files in minio as well. So blocking this until #4896 is done

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
https://www.loom.com/share/1ed43a7258f0483ab3cc847e01fb204b
