### ISSUE TITLE
Correction record option should not show in a marriage certificate preview page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4965]
**Bug description:**
Correction record option should not show in a marriage certificate preview page

**Steps to reproduce:**
1. Login to registrar
2. Click Ready to print
3. Click Download> Assign > Print any marriage record
4. Click Print in advance
5. Click "No, Make correction" and observe

**Actual result:**
 there is system crash when clicked
 
**Expected result:**
Should not show correction record option for marriage declaration

**Screen recording:**

https://images.zenhubusercontent.com/91778759/f91955ea-474a-498b-bfb1-7336eaa1133a/correction_record_option_should_not_show_in_a_marriage_certificate_preview_page.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by ShohelaTasin** [comment]
@anny320  This ticket is fixed! Can be closed Now!

**Recording :** https://www.loom.com/share/31fc3426afa141468a50e1991cb18de6
