### ISSUE TITLE
Add Secretary user

### ISSUE THREAD

**Issue by tahmidrahman-dsi** [opencrvs/opencrvs-core#4967]
- Add secretary role
- Add a user having secretary role to the reference data

Dev tasks: 

- Update populate scripts so that add a script that adds the secretary role to the roles collection which will run after migrations
- Update employees csv to add a user having a corresponding role

**Comment by Dahlia-NLD** [comment]
Is this related to the requirement "change role from reg. agent to secretary"?

**Comment by rikukissa** [comment]
@Dahlia-NLD Yes, precisely 👍
