### ISSUE TITLE
When a marriage declaration is rejected, the record stays in  "In review" status

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4971]
**Bug description:**
When a marriage declaration is rejected, the record stays in  "In review" status

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Go to Ready for review
3. Click Download> Assign> Review to any marriage record
4. Click Reject> Add comment> Sent for updates and observe

**Actual result:**
The record do not appear in requires update workqueue and stay in ready for review and status is "In review"

**Expected result:**
The record should go to Requires update and status should be Requires update

**Screen recording:**
https://images.zenhubusercontent.com/91778759/7efd01c6-4647-4214-80b3-85662603710e/when_a_marriage_declaration_is_rejected__the_record_stays_in___in_review___status.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by ShohelaTasin** [comment]
@anny320 @SyedaAfrida @Nil20  This ticket is not fixed yet! Need to fix!   

Recording : https://www.loom.com/share/a53957a8df9b4962aab860a851ea831a

**Comment by Zangetsu101** [comment]
Sorry guys it was my bad. This ticket would require the qa environment to be cleared. I'll move this to qa along with #4800

**Comment by anny320** [comment]
completed
