### ISSUE TITLE
System crash occurs when tried to view Health system record

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4991]
**Bug description:**
System crash occurs when tried to view Health system record

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Click In progress > Health system
3. Click any record 
4. Click view

**Actual result:**
System crash occurs when tried to view Health system record

**Expected result:**
User should be able to view record

**Screen recording:**
https://images.zenhubusercontent.com/91778759/9ba7452b-2351-43bb-ab37-b763ed23f76c/syestem_crash_occurs_when_tried_to_view_health_system_record.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/230874474-c35e40fd-599c-40d0-89db-423b59d8b574.mp4

**Comment by anny320** [comment]
Completed
