### ISSUE TITLE
Remove "Unknown" from Sex dropdowns

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#4993]
@Eezi is working on this.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/1206987/229087753-043f93f9-500a-4104-9968-ac0e77327dfb.png">

Should be 
<img width="368" alt="image" src="https://user-images.githubusercontent.com/1206987/229087782-37a78c98-aa23-45d0-b316-1252749ae443.png">

**Comment by Eezi** [comment]
Is it okey if I take this issue?
