### ISSUE TITLE
User can create multiple bookmark (entries) using same search parameter and same bookmark name

### ISSUE THREAD

**Issue by ShohelaTasin** [opencrvs/opencrvs-core#5001]
Bug description: User can create multiple bookmark (entries) using same search parameter and same bookmark name

**Steps to reproduce:** 

1.log in as RA/Registrar
2.Go to Advanced search
3.Seach any entries multiple time using same parameter
4.Name exactly same each bookmark
5.See duplicate bookmarks for same user using same search parameter

**Actual result:**
  Multiple bookmarks occurs for same user and same parameter while searching 

**Expected result:**
If multiple entries occur using same name and same search parameter 
they should be replaced by single entry or some pop up text should be there! 

**Screen recording:**
https://www.loom.com/share/270c15fc1c944ff6ae7fbc4733fba86c

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by anny320** [comment]
the functionality is working as built. Users can save any bookmark names to their preference. closing ticket
