### ISSUE TITLE
Place of birth or place of death is showing null in the beginning when the location is not health institution 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5002]
**Bug description:**
Place of birth or place of death is showing null in the beginning when the location is not health institution 

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Go to ready to print
3. Click Print> Print in advance
4. Scan the QR code and observe the data

**Actual result:**
 For Place of birth or place of death is showing null in the beginning when the location is not health institution 

**Expected result:**
Null should not appear in  Place of birth or place of death

**Screen recording:**

https://drive.google.com/file/d/1cvjb2Rn9IVH_10cgkvKMsTEQ783qW6v2/view?usp=share_link

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
most likely we need some similar logic to showing the place of birth as we have in record audit. If possible, extract the logic from there and use the same function in both places

**Comment by Nil20** [comment]
https://user-images.githubusercontent.com/32668488/230319849-3bee8915-2bf0-489f-9141-f5fabe543079.mp4

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![5002 fixed](https://user-images.githubusercontent.com/94350336/231435148-fb2627ae-47d7-4454-9e98-cc49e667e84b.png)

**Comment by anny320** [comment]
completed
