### ISSUE TITLE
When Place of birth or place of death is different than Farajaland, then Invalid QR code shows after scanning

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5003]
**Bug description:**
When Place of birth or place of death is different than Farajaland, then Invalid QR code shows after scanning

**Steps to reproduce:**
1. Login to RA/ registrar
2. Declare a birth or death declaration where Place of birth or place of death is different than Farajaland
3. Register that record
4. Click Ready to print> Print> Print in advance
5. Scan the QR code and observe

**Actual result:**
 Invalid QR code shows after scanning

**Expected result:**
User should be able to see data after scanning for any location of birth or death

**Screen recording:**
https://images.zenhubusercontent.com/91778759/06aa47de-38b2-44fb-9e14-b669c1b392a8/invalid_mobile.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by anny320** [comment]
completed
