### ISSUE TITLE
Marrriage: Verify a marriage certificate ( Add QR code to certificates)

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5007]
Was raised as a bug. but making it as ticket as we have not built "verify a marriage certificate"

**Bug description:**
QR code not appearing in marriage certificate

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Click Ready to print
3. Click Print in any marriage record
4. Click Print in advance and observe the certificate

**Actual result:**
QR code not appearing in marriage certificate

**Expected result:**
QR code should appear in marriage certificate

**Screenshot:**
![QR code not appearing in marriage certificate.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/7ffffee7-269a-4f80-82e6-9e9a41660bc3)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
@SyedaAfrida @anny320 We haven't implemented the QR code feature for marriage

**Comment by euanmillar** [comment]
Custom events will enable for all future countries #7052
