### ISSUE TITLE
System crash occurs when try to send an incomplete marriage declaration

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5008]
**Bug description:**
System crash occurs when try to send an incomplete marriage declaration

**Steps to reproduce:**
1. Login to FA
2. Create an incomplete marriage declaration
3. Click Send for review and observe

**Actual result:**
System crash occurs when try to send an incomplete marriage declaration

**Expected result:**
User should be able to submit an incomplete marriage declaration

**Screen recording:**

https://images.zenhubusercontent.com/91778759/fa30960c-703a-4e72-a16f-3aab09cd3530/system_crash_occurs_when_try_to_send_an_incomplete_marriage_declaration.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by ShohelaTasin** [comment]
@anny320  This ticket is fixed! Can be closed!

**Recording :** https://www.loom.com/share/e682f6b47645428ebc2b471f8d11edaa

**Comment by anny320** [comment]
completed
