### ISSUE TITLE
OSIA standardised OSIA_UIN_VID_NID must be generated before registration webhook is dispatched

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5012]
If a failure occurs the application should be rejected

- [x] In Farajaland we need to use the base branch [Feature: SI Hackathon](https://github.com/opencrvs/opencrvs-farajaland/pull/532), then make a pull request from this feature branch called "feature-osia-generate-uin".  In this branch we need to change this [createWebHookResponseFromBundle function](https://github.com/opencrvs/opencrvs-farajaland/blob/5bcea2bee93490f5d727c9c3afc5f3bba0999480/src/features/validate/service.ts#L31), so that it returns OSIA_UIN_VID_NID along with the registration number, only if an integratingSystemType === OSIA from user-mgnt. - 2

- [x] To generate OSIA_UIN_VID_NID, we must prepare a [fetch](https://osia.readthedocs.io/en/latest/technical/uin.html#services) to the OSIA_UIN_MANAGEMENT_URL, with a Bearer token header where the OSIA_JWT value is a docker secret (Later will replace this with OSIA auth and we dont want to store it in GIT by mistake during the Hackathon).  transactionID could be the tracking ID.  Handle all errors. - 1

- [x] To generate OSIA_UIN_VID_NID for the INGroupe solution, we must prepare a fetch to the OSIA_UIN_MANAGEMENT_URL - FYI in testing the URL is: "https://test.utoconnect.com/crvs/eid", with a Bearer token header where the OSIA_JWT value is a docker secret.  Hopefully we will not need another integratingSystemType. The INGroup payload is:

```
{
  "firstName": "paolitto",
  "lastName": "Dupond",
  "legalName": "",
  "gender": "MALE",
  "birthDate": "2022-11-11",
  "birthPlace": "",
  "authority": "CRVS"
}

```

Euan can share the JWT for testing.  Error codes and response format TBC - 1

-  [x] In core, make a PR from the [feature branch](https://github.com/opencrvs/opencrvs-core/pull/5029) workflow service, invokeRegistrationValidation function, if an error occurs, instead of just throwing an error, we need to reject the application.  The application status should be in a something like WAITING_FOR_VALIDATION state,  we need to change the state to REJECTED with a rejection message saying "Birth registration number generation failed".  We will merge this into develop as a 1.3 bugfix.  In another pull request, if integratingSystemType === OSIA, it can say this: "Birth registration number & OSIA UIN generation failed."  The user associated with the rejection can be the Registar user in the bundle. - 2

- [ ] In workflow, if the OSIA_UIN_VID_NID generation was successful, then store it as an identifier in the child's FHIR Patient identifiers array as we do with BRN.  We need to include OSIA_UIN_VID_NID on the birth certificate, as we do with mosipAid, so we need typeResolvers, fhirBuilders, queries, mutations and registration-mappings to retrieve/populate this identifier when downloading / correcting a record. - 2

**Comment by rabiulislamanik** [comment]
This PR is dependent on [this farajaland PR](https://github.com/opencrvs/opencrvs-farajaland/pull/540)
