### ISSUE TITLE
When any incomplete birth record is sent by FA, there should be no  duplicate warning toast

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5021]
**Bug description:**
When any incomplete birth record is sent by FA, there should be no  duplicate warning toast

**Steps to reproduce:**
1. Login to FA
2. Declare an incomplete birth record
3. Click Sent for review and observe

**Actual result:**
When any incomplete birth record is sent by FA, There is a duplicate warning toast

**Expected result:**
Should not show duplicate warning toast as the record is not duplicate and it is incomplete

**Screen recording:**

https://images.zenhubusercontent.com/91778759/dccb4004-da44-4fa8-8e5d-fcce58b00045/when_any_incomplete_birth_record_is_sent_by_fa__there_is_a_duplicate_warning_toast.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
Is it so that sending any incomplete declaration is showing this duplicate warning toast? @SyedaAfrida

**Comment by SyedaAfrida** [comment]
@Zangetsu101 Yes this issue occurs only while sending incomplete birth declaration. And we do not expect any incomplete declaration to be duplicate, since the form yet is not completely filled up

**Comment by Zangetsu101** [comment]
@anny320 @euanmillar Need clarification on if we want to flag an incomplete declaration as duplicate or not

**Comment by euanmillar** [comment]
@Zangetsu101 @SyedaAfrida @anny320 Ed says that running de-dupe on in-complete declarations is desirable and edge cases exist where empty fields may exist. But @SyedaAfrida we need clarity.  Every single in-complete declaration is being flagged as a duplicate, yes or no?  That would obviously be some kind of bug we need to look into, otherwise there must be some other data being sent which is legitimately a duplicate

**Comment by SyedaAfrida** [comment]
@euanmillar Yes, Every single incomplete Birth declaration is being flagged as a duplicate. Just showing the duplicate warning toast at the bottom. And it occurs only for birth declarations.

**Comment by euanmillar** [comment]
@Zangetsu101 lets test and discuss the de-dupe logic in tech design to de-bug and provide more direction if the logic needs to change.  Not every in-progress application should be being flagged as a duplicate, and the toast cant keep popping up.

**Comment by euanmillar** [comment]
The issue can be solved if ...

In [searchForBirthDuplicates](https://github.com/opencrvs/opencrvs-core/blob/86d9a70ad325aae5bddf41e991e5ebe603b1a437/packages/search/src/features/registration/deduplicate/service.ts#LL59C14-L59C38) method, return an empty array if these are all not available:

Birth case:
childs first name or childs last name
childs d.o.b.
mothers first name or mothers last name
mothers d.o.b

Death case:
deceaseds first name or deceaseds last name
deceaseds d.o.b
deceaseds d.o.d

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://github.com/opencrvs/opencrvs-core/assets/94350336/62541ec7-3d1b-4677-9437-7fade9234d07
