### ISSUE TITLE
When a record is archived from record audit page, then old comment shows in the archived action modal

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5022]
**Bug description:**
When a record is archived from record audit page, then old comment shows in the archived action modal

**Steps to reproduce:**
1. Login To RA/ Registrar
2. Click In progress/ Ready for review
3. Click Download> assign> Review
4. Click Reject> Add comment> Archive
5. Search for the record and reinstate
6. Again Click Download > assign
7. Click Archive from Record audit page
8. Again search for that record
9. Click Download > assign
10. Click Last Archived action and observe

**Actual result:**
When a record is archived from record audit page, then old comment shows in the archived action modal

**Expected result:**
When a record is archived from record audit page, No comment should show in archived action modal

**Screen recording:**
https://www.loom.com/share/2e3029766fe549cbbf8b036f3a2e62d8

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
https://www.loom.com/share/78a220a15d4d45f38f06323004a644ca

**Comment by anny320** [comment]
completed
