### ISSUE TITLE
Groom's name appears twice in Workqueue when sent an incomplete marriage record and system crash occurs after trying to reject that record

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5028]
**Bug description:**
Groom's name appears twice in Workqueue when sent an incomplete marriage record and system crash occurs after trying to reject that record

**Steps to reproduce:**
1. Login with FA
2. Create an incomplete marriage record with groom and bride's name
3. Click sent for rereview
4. Logout
5. Login to RA/ Registrar'
6. Click In progress> Field agent
7. Observe the record in the workqueue
8. Click Download>Assign> Update
9. Click Reject> Add comments> Requires Update and observe

**Actual result:**
1. Groom's name appears twice in Workqueue
2. System crash occurs when try to reject an incomplete marriage record

**Expected result:**
1. Groom and bride's name should appear properly in workqueue
2. Should be able to reject an incomplete marriage declaration

**Screen recording:**
https://www.loom.com/share/075ffe38f13445aa8c86e2d7130a66cb

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
The system crash is most likely related to #5008 but yeah we need to fix the workqueue name issue

**Comment by SyedaAfrida** [comment]
will be tested after next deploy

**Comment by Zangetsu101** [comment]
yeah sorry the reject part would require data to be cleared

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
https://www.loom.com/share/dec800a94e3c49c3be84a33d26325b57

**Comment by anny320** [comment]
completed
