### ISSUE TITLE
When no first name is captured and the surname is short, in the review page, the spacing in the table makes it difficult to read when the error message is included.

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#5040]
**Describe the bug**
There is a spacing issue making it difficult to read full name correctly 
No first name captured / surname is short --> review page the spacing does not allow easy reading.

**To Reproduce**
Steps to reproduce the behaviour:

1. Login as a FA/RA/ Registrar
2. Go to birth application, start a new record and follow prompts.
3. Do not add first name but add a short last name
4. go to review page
5. See an error on the full name field

**Expected behaviour**
If no first name and a short second name, to accommodate the error the name should flow onto two lines for easier reading

**Screenshots**
![image (29).png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/7bb2c765-3d0c-4c73-acdb-b1f5721e173c)
**OpenCRVS Core Version:**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Possible fixes**
(If you can, link to the line of code that might be responsible for the problem)

**Reproducible demo**

**Comment by ShohelaTasin** [comment]
@anny320 this ticket is fixed! Can be closed now!

**Screenshot :** 
![anneBug](https://user-images.githubusercontent.com/41486148/231714944-ca307ad5-65f5-4366-a191-aec1f7ed265a.png)

**Comment by anny320** [comment]
completed
