### ISSUE TITLE
OSIA standard National ID validation 

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5044]
Will follow a similar user experience process to the MOSIP authentication with the exception being that the National ID input field is visible above the authorise button.

All of this should only happen if integratingSystemType===OSIA:

When the NID field is empty, disable the authorise button

When the NID field has a value, when you click Authorise, we 

[https://osia.readthedocs.io/en/latest/technical/dataaccess.html#services](https://osia.readthedocs.io/en/latest/technical/dataaccess.html#services)

matchPersonAttributes (authenticate) - equivalent to authorise (Send NID)

readPersonAttributes (pre-populate) -  called by gateway

Once again we are using the 1 year valid JWT for OSI Access

## Dev tasks

No form pre population is needed! Only verification!

- [x] Add environment variables `OSIA_REST_URL` and `OSIA_PERSISTENT_JWT` to use in gateway.
- [x] Create a gateway endpoint called OSIAUserInfo. It will send a post message to OSIA like described earlier in the OSIA docs, and verify that the user information was correct
- [x] Handle all responses, including error responses - 1
- [x] Amend `FormFieldGenerator` to handle `: field.type === NID_VERIFICATION_BUTTON` `onClick` differently, if integratingSystemType is OSIA instead of MOSIP. In that case, it needs to immediately fetch the data from the backend endpoint created in earlier tasks. Consider refactoring the onClick away from FormFieldGenerator to not bloat the file. - 2
- [x] Similar to `MOSIP_PSUT_TOKEN_ID`, create `OSIA_NID`. This identifier gets populated with the ` { nationalId: string }` response from previous task. This confirms that the user has verified. - 2
- [x] Amend forms/configuration/default/*.ts to only show <kbd>Authenticate</kbd> if National ID, DoB, first name & last name are inputted & the integratingSystemType is OSIA - 1

**Comment by naftis** [comment]
MOSIP integration is coupled with the redirect -> callback action, where the callback page fetches the data and passes it to the form.

For OSIA I think we need a separate https://github.com/opencrvs/opencrvs-core/blob/96f1015bfef66ab6ea587b8215a1a4e67dafb547/packages/client/src/components/form/FormFieldGenerator.tsx#L997 form field type `NID_VERIFICATION_FETCH_BUTTON` that handles the onClick differently doing a fetch similarly to the `FetchButton`. I'll continue this tomorrow Thursday and update.

**Comment by naftis** [comment]
@euanmillar https://osia.readthedocs.io/en/latest/technical/dataaccess.html#data-model The `Person` data model doesn't include the current address of the person, just the place of birth. I don't think we can pre-fill the form data with this address for other than testing purposes

**Comment by euanmillar** [comment]
https://github.com/SecureIdentityAlliance/osia-reference-implementation

**Comment by euanmillar** [comment]
Blocked awaiting participation of an OSIA compliant Pop Reg
