### ISSUE TITLE
OSIA SI Hackathon: OSIA does not use REGISTERED webhook, must be an API call in country config: contains only event type and UIN

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5045]
OSIA will not subscribe to the REGISTERED webhook.  

Instead, immediately before/after dispatching the webhook, from workflow, if integratingSystemType===OSIA we must call a custom endpoint in Farajaland, which then notifies OSIA synchronously that the registration is complete using the "publish "notification API: https://osia.readthedocs.io/en/latest/technical/notification.html#post--v1-topics-uuid-publish.  The payload contains 2 strings: type of event and UIN

[https://osia.readthedocs.io/en/latest/technical/notification.html#notification-message](https://osia.readthedocs.io/en/latest/technical/notification.html#notification-message)
Let's call the endpoint after saving the UIN's to hearth to make sure there weren't any errors

**Comment by sadmananik** [comment]
@euanmillar  What should be the uuid here "POST /v1/topics/{**uuid**}/publish"

**Comment by euanmillar** [comment]
So this API has to be called after that process has completed, at the same time as the REGISTERED webhook is dispatched, if the integratingSystemType === OSIA

**Comment by Zangetsu101** [comment]
Shouldn't that be the UIN of the child?

**Comment by Zangetsu101** [comment]
It looks like you can get the topics using this api: https://osia.readthedocs.io/en/latest/technical/notification.html#get--v1-topics but I don't know if they would already have a topic for birth event or something like that
