### ISSUE TITLE
Issue : In Supporting doc page while adding new records select bar option can be selected twice!

### ISSUE THREAD

**Issue by ShohelaTasin** [opencrvs/opencrvs-core#5051]
***Bug description:***
In Supporting doc page while adding new records select bar option can be selected twice!     

***Steps to reproduce:***
1.Log in Registrar/RA
2.Create New record for death/birth
3.Go to supporting document page 
4. Select one item and try to upload from select option 
5.While in slow network try to select another option before first one is uploaded ! e.g. - if uploading national id try to select passport 

***Actual result:***
1. Only one upload and one select for one item should be possible
2. No OTHER documents in mobile application

***Expected result:***
1.User can upload twice for same select option
2. OTHER doc shows in mobile view for the same record

***Screen recording:***
https://www.loom.com/share/4c216dc3e3b946e38da5e1b575bddbab

*Tested on:*
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
Looks like when a document is being uploaded, that option shouldn't stay in the dropdown. We also need to make sure that the option gets back to the select in case the upload failed

**Comment by ShohelaTasin** [comment]
@anny320 This ticket is fixed now! Can be closed!

**Recording :** https://www.loom.com/share/82dfce655b034a4f8b0dd32bfeff7daa

**Comment by anny320** [comment]
completed
