### ISSUE TITLE
When a record is marked as not a duplicate, after issue should not show duplicate icon and warnings

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5053]
**Bug description:**
When a record is marked as not a duplicate, after issue should not show duplicate icon and warnings

**Steps to reproduce:**
1. Login to Register
2. Click Ready for review
3. Download> Assign> Review any duplicate record
4. Click Mark as not a duplicate
5. Click register
6. Click Ready to print
7. Click Print> Select any option except print in advance> Print
8. Search that record with name/ tracking id and observe

**Actual result:**
1. Duplicate icon is showing in workqueue and record audit
2. Duplicate warning message is showing in  record audit

**Expected result:**
Should not show  Duplicate icon and warning message as the record is marked as not a duplicate

**Screen recording:**
https://www.loom.com/share/4622a00e3c094ce1ba28eed59bb5b24a

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
https://www.loom.com/share/b0720c3d9d444c54b721eae49a5baa49

**Comment by anny320** [comment]
completed
