### ISSUE TITLE
When a draft is deleted from declaration config, all submitted declarations and registrations that have been previously submitted gets deleted

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5072]
**Bug description:**
When a draft is deleted from declaration config, all submitted declarations and registrations that have been previously submitted gets deleted

**Steps to reproduce:**
1. Login to National system admin
2. Click Configuration> Declaration forms
3. From Draft click 3 dot menu> Delete> Delete
4. Logout
5. Login to FA/RA/ Registrar and observe

**Actual result:**
All submitted declarations and registrations that have been previously submitted gets deleted

**Expected result:**
1. All submitted declarations and registrations that have been previously submitted should not get deleted
2. Only the draft should be deleted
3. All submitted declarations and registrations that have been previously submitted should only get deleted when form goes to in preview/ published

**Screen recording:**

https://images.zenhubusercontent.com/91778759/040f5df4-c31c-45dd-b153-d087ca1e6c83/when_a_draft_is_deleted_from_declaration_config__all_submitted_declarations_and_registrations_that_have_been_previously_submitted_gets_deleted.mp4

**Tested on:**
https://login.farajaland-config.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://www.loom.com/share/902bf478f0ea4e22aa7dd688849103d1

**Comment by anny320** [comment]
completed

**Comment by anny320** [comment]
completed
