### ISSUE TITLE
Issue : Register button is enabled while adding only one signature in review Page for marriage!

### ISSUE THREAD

**Issue by ShohelaTasin** [opencrvs/opencrvs-core#5073]
***Bug description:***
Register button is enabled while adding only one signature in review Page for marriage!

***Steps to reproduce:***
1.Log in as Registrar 
2.Go to Ready for Review
3.Go to any marriage record
4.Click Review
5. Add Signature for any one out of four

***Actual result:***
Register button is enabled when you add only one signature whereas you need four !

***Expected result:***
Register button should disable till four signature added!

***Screen recording:***
https://www.loom.com/share/3add11e7184f4b04be2a99c6819a81e7

***Tested on:***
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by ShohelaTasin** [comment]
@anny320 this ticket is fixed! Can be closed Now!

Recording : https://www.loom.com/share/39a9d9d4ea7c4b679a5f5cfe12afb616

**Comment by anny320** [comment]
completed
