### ISSUE TITLE
Spelling should be two instead of Tow for 2nd witness while declaring marriage records!

### ISSUE THREAD

**Issue by ShohelaTasin** [opencrvs/opencrvs-core#5078]
Steps to reproduce :
1.login as RA/ Registrar
2.Declare any marriage records
3.Go to signature upload page
4.Observe

**Bug Screenshot :**
![BugTwo.png](https://images.zenhubusercontent.com/64228745932c6179b3fb3fb2/65e8a1d0-6831-4228-afc7-3a16ef49e7ee)

**Comment by ShohelaTasin** [comment]
@anny320 This ticket is fixed! Can be closed Now!

**Screenshot:** 

![tested](https://user-images.githubusercontent.com/41486148/232410029-4339050c-229e-4edc-8cfc-fa01241b74b0.png)

**Comment by anny320** [comment]
completed
