### ISSUE TITLE
After saving marriage draft with only groom's name if submitted incomplete then the record gets disappeared

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5083]
**Bug description:**
After saving marriage draft with only groom's name if submitted incomplete then the record gets disappeared

**Steps to reproduce:**
1. Login to FA
2. Declare an incomplete marriage event with only Groom's name
3. Click save and exit
4. Click Update on that record
5. Click Sent for review

**Actual result:**
The record disappears after going to outbox

**Expected result:**
Should be able to submit incomplete marriage record which was previously saved as draft with only groom's name

**Screen recording:**

https://images.zenhubusercontent.com/91778759/e5f5ab40-3ba1-4dde-acdf-d3d51a7592e4/after_saving_marriage_draft_with_only_groom_s_name_if_submited_record_gets_disappeared.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
![image](https://user-images.githubusercontent.com/29002716/231989278-65f29321-288b-4207-9697-e4a114720010.png)

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/232416121-c462d8e0-5251-499e-aa6b-427330d5cf99.mp4

**Comment by anny320** [comment]
completed
