### ISSUE TITLE
Mother details are not available showing on Review if the if False

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#5087]
**Describe the bug**
The line item on the Reivew page . Mother details are not available' should only show if the checkbox has been clicked ie. True. 

If the statement is false. ie checkbox unclicked. Then it should not show on the review page. 

![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/d8c08c2c-de4d-414c-afb3-a35719c16656)

**To Reproduce**
1. Create new declaration
2. Nav to review page
3. See error. Mother details are not available | No

**Expected behaviour**
Line item should not show on review page

IF the checkbox is selected. THEN on the review page show.  Mother details are not available | Yes

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![5087 fixed 2](https://github.com/opencrvs/opencrvs-core/assets/94350336/8702cbc4-8158-4cd7-a6b4-e374f351cb3f)


![5087 fixed](https://github.com/opencrvs/opencrvs-core/assets/94350336/d081591d-599c-468c-8ca9-c20df6eef3b5)

**Comment by anny320** [comment]
completed
