### ISSUE TITLE
Disallow registration without secretary signature 

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#5119]
**When working on a death record:** (this was already done for birth [here](https://github.com/opencrvs/opencrvs-core/pull/5109))

Registrar shouldn't be allowed to register a record if a registration agent has not validated the record first (record status !== VALIDATED).

We prevent them from registering by disabling the "Register" button. Also notice the different copy around the button.

This work needs to be done as a core customisation

Design: 
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/1206987/228823926-678b5071-5caf-4847-8599-4acff8125666.png">

**Comment by Dahlia-NLD** [comment]
Is the screenshot in the ticket correct? I only see a dimmed Register button

**Comment by rikukissa** [comment]
It is correct yes, but the implementation isn't currently. @wilrona is fixing it currently
