### ISSUE TITLE
Setup 4-level administrative structure

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#5120]
0: Country
1: Region
2: Division
3: Subdivision

**Comment by rikukissa** [comment]
Updated 👍

**Comment by Dahlia-NLD** [comment]
How do we test this?

**Comment by rikukissa** [comment]
@Dahlia-NLD login as system admin `malep.job` and navigate to [Organisation](https://register.cameroon-qa.opencrvs.org/organisation/) from the sidebar. You should see the current structure here and then be able to navigate to offices from the lowest level

<img width="873" alt="image" src="https://user-images.githubusercontent.com/1206987/234792039-42486539-79ec-4755-95bd-182f092fe0e0.png">

**Comment by Dahlia-NLD** [comment]
Looks good to me. Can close. Only looked at one language of course.
