### ISSUE TITLE
Apostrophe should be supported in names and Married last name title is wrong

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5127]
**Bug description:**
Apostrophe should be supported in names and Married last name title is wrong

**Steps to reproduce:**
1. Declare a marriage event
2. In Groom and bride's details page, Enter a name with apstrophe like- O’Neill
3. Observe Married last name title

**Actual result:**
1. when given apostrophe shows "The field should only accept English characters"
2. shows - "Last name at birth (if different from above)"

**Expected result:**
1. User should be able to input names with apostrophe,  like- O’Neill
2. titles of the field should be "Married Last name (if different)"

**Screenshot:**
![apostrophe not supported in names.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/2dbc089a-b31a-43d5-808c-f287f27d61e4)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![5127 fixed](https://github.com/opencrvs/opencrvs-core/assets/94350336/3fd43210-c941-4bb0-9a6f-5cca05212b7c)

**Comment by anny320** [comment]
completed
