### ISSUE TITLE
EMAIL: Configure onboarding channel (email or sms)

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#5145]
### Description
- adds email to new user creation
- uses email to onboard new users instead of sms

### Acceptance criteria

GIVEN i am a system admin
WHEN a creating a user
THEN i can add an email (no validation)

GIVEN email is configured
WHEN a new user is created
THEN send an email invite with temporary password and username

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=14626%3A103097&t=sOLYrr6PVoLzhwY4-1

### Dev tasks

Capture email when creating an user: 
- [ ] Save the email similarly as user's phone number when creating a user. Any valid email can be passed. If the email is already in use, we need to show an error. Based on the `USER_NOTIFICATION_DELIVERY_METHOD` environment variable, either phone number or email should be mandatory when creating an user. We should pass the env variable from country-config client-config.js to client. - 3
- [ ] In user-mgnt, pass the user email when notifying [in create user service](https://github.com/opencrvs/opencrvs-core/blob/18d910cbe35e311694b8c0357c48ca7d02af1d76/packages/user-mgnt/src/features/createUser/service.ts#L292) to allow sending the 2FA emails to users. - 1

**Comment by naftis** [comment]
@jpye-finch How do we handle users that don't have emails?

**Comment by SyedaAfrida** [comment]
This ticket is tested

![create user](https://github.com/opencrvs/opencrvs-core/assets/94350336/66b8f2ae-2ef8-409b-9a09-e83daa4d3a73)

![create user 2](https://github.com/opencrvs/opencrvs-core/assets/94350336/55247f65-9427-4882-b6e7-0a5d41c3ec13)

![c u email](https://github.com/opencrvs/opencrvs-core/assets/94350336/1ceb4c37-c628-42d0-a5d7-40cdfad89fb7)
