### ISSUE TITLE
EMAIL: Use email to send 2fa code

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#5146]
### Description
- sends 2fa codes to the users email. 
- configured in the background by developer. SMS or email supported. 
- Google authenticator in the backlog for 1.4

### Acceptance criteria

GIVEN email is configured for 2fa
WHEN a user logins in
THEN send the 2fa code to their email address

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=15567%3A109522&t=hovPBMKXpEhEG4JR-1

### Dev tasks

- [ ] Depending on the env variable `USER_NOTIFICATION_DELIVERY_METHOD` show a different 2FA copy depending if it's SMS or Email - 1

**Comment by SyedaAfrida** [comment]
This ticket is tested
when configured to email

https://github.com/opencrvs/opencrvs-core/assets/94350336/cf43cf04-ce12-4162-862f-caec83fc56c2

![m1](https://github.com/opencrvs/opencrvs-core/assets/94350336/bb92ef37-b795-4c4b-b215-bd6a62851452)
