### ISSUE TITLE
EMAIL: Username reminder and password reset flows use email

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#5147]
### Description
- Sends username reminder to the users email
- Sends password reset 2fa code send to users email

### Acceptance criteria

**Username reminder**

GIVEN I am requesting a username reminder 
[WHEN i have entered my email] (https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications-v1?node-id=8775%3A138731&t=yTBMLdqUnXhQ5IGG-1)
THEN send an authentication code

Email: https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=15567%3A110299&t=hovPBMKXpEhEG4JR-1

**Password reset**

GIVEN I am requesting a password reset 
[WHEN i have entered my email] (https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications-v1?node-id=8775%3A138835&t=yTBMLdqUnXhQ5IGG-1)
THEN send an authentication code

Email: https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=15567%3A110323&t=hovPBMKXpEhEG4JR-1

### Design
Emails:
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=15567%3A109522&t=hovPBMKXpEhEG4JR-1

### Dev tasks

- [ ] Depending on the environment variable when doing username reminder, we need to show either phone number or email input. We also need to update user-mgnt handlers. We also need to validate the email here and show an error if it's not valid. - 2

**Comment by SyedaAfrida** [comment]
This ticket is tested

https://github.com/opencrvs/opencrvs-core/assets/94350336/5579ad9e-a123-4a90-978a-ba08126aa3f4

![ur1](https://github.com/opencrvs/opencrvs-core/assets/94350336/4269ed4d-c9ce-4783-b9e4-4293aab159ca)


https://github.com/opencrvs/opencrvs-core/assets/94350336/9c9b0619-e45f-4ff9-942c-6e21545295a5
