### ISSUE TITLE
Marriage declaration cannot be archived properly from any workqueue

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5155]
**Bug description:**
Marriage declaration cannot be archived properly from any workqueue

**Steps to reproduce:**
1. Login to RA/ registrar
2. Click In progress/ Ready for review/ Requires update
3. Click download> Assign to any marriage record
4. Click the record
5. Click Archive> Archive and observe

**Actual result:**
1. the record stays in the workqueue and status is not changed
2. when searched with tracking id, shows the record in archieved in the record audit page

**Expected result:**
1. after archiving, the record should not appear in the workqueue
2. when searched with tracking id, the status & icon all should be changed to archived in both workqueue and record audit page

**Screen recording:**
https://www.loom.com/share/1e604d757c3a419591f91df03c0f4ac5

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
This would require the environment to be reset to be tested properly after deploy

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://github.com/opencrvs/opencrvs-core/assets/94350336/09de54a5-7da4-4d5c-850d-33b9df7605c0
