### ISSUE TITLE
In review page, supporting document changes to topmost supporting document in the dropdown when typing comment

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5157]
**Bug description:**
In review page, supporting document changes to topmost supporting document in the dropdown when typing comment

**Steps to reproduce:**
1. Login to FA/ RA/ Registrar
2. Declare a birth/ death/ marriage declaration with multiple supporting documents
3. In review page select any dropdown on supporting document
4. Start typing comment and observe

**Actual result:**
supporting document changes to topmost supporting document in the dropdown when typing comment

**Expected result:**
supporting document should not change while typing comments

**Screen recording:**

https://images.zenhubusercontent.com/91778759/8576c567-becb-4469-8569-e93eb986a0d9/supporting_document_changes_to_first_document_when_typing_comment.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://github.com/opencrvs/opencrvs-core/assets/94350336/d2ba223c-3265-43cb-99aa-6946770b5d95

**Comment by anny320** [comment]
completed
