### ISSUE TITLE
As part of user creation, select default health facility for user

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#5159]
- Dropdown in the user creation form shown only if user type is field agent
- Dropdown is labelled as "Organisation"
- Mandatory field
- Stored as a new field `primaryHealthFacility` in user-mgnt -> users

Implemented as a core modification in `release-v1.4.0-cameroon` branch

**Comment by Dahlia-NLD** [comment]
We need another field Organisation Type, even if the only value there is Health Facility. This way, we can add more as we go. For ex, court will be needed soon enough.

**Comment by rikukissa** [comment]
@Dahlia-NLD good catch! We'll add that
