### ISSUE TITLE
EMAIL: System admin sending username reminder and resetting password

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#5160]
### Description
- When a system admin sends username reminder. Based on configuration it is sent via SMS of email
- When a system admin resets password. Based on configuration it is sent via SMS of email

###Acceptance criteria

**Username reminder**

GIVEN email is configured as comms channel
GIVEN I am a system admin sending a username reminder
WHEN I click Send username reminder
THEN send a username reminder via email

Email: https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=15567%3A110298&t=XjLEVKUGAtdZA51H-1

**Password reset**

GIVEN email is configured as comms channel
GIVEN I am a system admin resetting a user's password
WHEN I click Reset password
THEN reset password and send email with temp password

Email: https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=15567%3A110275&t=XjLEVKUGAtdZA51H-1

Design
Emails:
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=15567%3A109522&t=hovPBMKXpEhEG4JR-1

**Comment by SyedaAfrida** [comment]
This ticket is tested
Username reminder:
![username reminder 1](https://github.com/opencrvs/opencrvs-core/assets/94350336/7470e5c6-d031-4cb2-aaa6-d9d5968c7675)
![usrname reminder 2](https://github.com/opencrvs/opencrvs-core/assets/94350336/add4e0b4-2c3b-4d6f-8482-12c21b171bbd)

Password reset:
![reset pswd 1](https://github.com/opencrvs/opencrvs-core/assets/94350336/a3f6da4a-53a8-4615-877e-1c7616d70953)
![reset  pswd 2](https://github.com/opencrvs/opencrvs-core/assets/94350336/185be9cd-c789-42f3-970d-9e3208034540)
