### ISSUE TITLE
EMAIL: 2FA code when changing phone or email needs to use the correct method of delivery

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#5161]
### Description
- When email is configured as the coms channel. Then send 2fa code via email

### Acceptance criteria

GIVEN I am changing my phone number
WHEN I enter my new number
THEN send an email with an auth code

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=15567%3A110482&t=XjLEVKUGAtdZA51H-1

![image](https://user-images.githubusercontent.com/1322608/235648531-b70523ab-f032-42a5-ab2e-ceecc7653798.png)

### Dev tasks

- [ ] So checking from the client-config.js, lets display the correct copy after changing phone or email in user settings - 1

**Comment by SyedaAfrida** [comment]
This ticket is tested
when configured to email
1)  for changing phone number

https://github.com/opencrvs/opencrvs-core/assets/94350336/63ad6f0f-eb91-4e42-bafa-27b64d153a80


2)  for changing email address:
![11](https://github.com/opencrvs/opencrvs-core/assets/94350336/24f5396c-a9f7-4c31-9915-0d48047a74ff)
![unnamed](https://github.com/opencrvs/opencrvs-core/assets/94350336/82532145-155d-4de0-bb2b-6b12d21e73f5)
