### ISSUE TITLE
Change email

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#5162]
### Description
- allows a user to change their email

### Acceptance criteria

GIVEN I am a user
WHEN on the Settings page
THEN I can see my current email address and click Change

GIVEN I click change email
WHEN enter my new email
THEN send auth code to my new email

GIVEN I enter correct auth code
THEN update my email

### Design

![image](https://user-images.githubusercontent.com/1322608/235646556-0bdc1773-bf08-473c-9b21-656cb6479256.png)

### Dev tasks

- [ ] We need to amend the user setting page to add a way to change the email of the current user. We need to validate the email. We need to check that no other user is currently using the email. - 2

**Comment by SyedaAfrida** [comment]
this ticket is tested 
for changing email address:
![11](https://github.com/opencrvs/opencrvs-core/assets/94350336/24f5396c-a9f7-4c31-9915-0d48047a74ff)
![unnamed](https://github.com/opencrvs/opencrvs-core/assets/94350336/82532145-155d-4de0-bb2b-6b12d21e73f5)
