### ISSUE TITLE
When a record is archived from reject modal, shows marked as duplicate pill if it was previously marked as duplicate and archived

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5164]
**Bug description:**
When a record is archived from reject modal, shows marked as duplicate pill if it was previously marked as duplicate and archived

**Steps to reproduce:**
1. Login as RA/ Registrar
2. Click in progress> Field agent/ Ready for review
3. Click Download>assign> Update any record
4. Click Reject
5. Enter Comment> Click mark as duplicate> archive
6. Search and observe archive modal
7. Click Reinstate
8. Again Click Download>assign> Update to that record
9. Click Reject
10. Enter Comment> archive
11. Search and observe archive modal

**Actual result:**
 When archived clicking marked as duplicate, shows marked as duplicate pill. Later when the same record is reinstated and archived without clicking marked as duplicate, still shows marked as duplicate pill

**Expected result:**
when a record is archived without clicking marked as duplicate, should not show marked as duplicate pill

**Screen recording:**
https://www.loom.com/share/9e6224aba5f04fd6b47f67a3c279c7a4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
https://www.loom.com/share/9b905ed1ad6a4977bdcb80bbefa1c916

**Comment by anny320** [comment]
completed
