### ISSUE TITLE
Overflow of text occurs in marriage certificate for long names

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5168]
**Bug description:**
Overflow of text occurs in marriage certificate for long names

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Declare a marriage event with long spouse names
3. Register
4. Click Ready to print
5. Click Print> Print in advance and observe

**Actual result:**
Overflow of text occurs in marriage certificate for long names

**Expected result:**
Should not overflow, if possible Print names in two lines to avoid overflow

**Screenshot:**
![long name.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/6886441c-5480-4201-b81f-ee00e471e636)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
@jpye-finch Any thoughts on this one?

**Comment by jpye-finch** [comment]
yeh will provide a template with the names on two lines

**Comment by jpye-finch** [comment]
![marriagev2](https://github.com/opencrvs/opencrvs-core/assets/46478402/b99217c1-9c66-4c9d-9359-ec10ede3bab6)

**Comment by ShohelaTasin** [comment]
![buglongstring](https://github.com/opencrvs/opencrvs-core/assets/41486148/e4fa0b53-4021-48ee-9eb0-3f06a646452b)


Actual Result : While utilizing full string Len for first name and last name, facing this scenario!
Expected Result :  Should be enclosed by margin!

**Comment by Zangetsu101** [comment]
@jpye-finch any thoughts on this?

**Comment by jpye-finch** [comment]
My understanding is we can't wrap text in the SVG. We should close this bug. Farajaland is an example country. So this is an example certificate. Each country is going to have to test their template for long string lengths.

**Comment by anny320** [comment]
closed, see comment above

**Comment by SyedaAfrida** [comment]
Had to reopen this ticket as this bug is appearing again
![mr](https://github.com/opencrvs/opencrvs-core/assets/94350336/eb42f7fb-15a9-4b8e-b487-d0a7fa7a0072)

**Comment by Nil20** [comment]
![Screenshot from 2023-09-01 16-09-32](https://github.com/opencrvs/opencrvs-core/assets/32668488/72386697-fea1-4a83-b60a-0c6e38dc6c82)
Currently, the marriage certificate's svg shows the groom's name and the bride's name in different rows, so overflow like in this screenshot is unlikely to occur.

**Comment by SyedaAfrida** [comment]
Closing since the bug appeared for wrong svg file
