### ISSUE TITLE
Email: Create all email HTML templates and allow sending emails from country config

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#5175]
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=15567%3A109522&t=hovPBMKXpEhEG4JR-1

### HTML templates in Farajaland

Base pull request: https://github.com/opencrvs/opencrvs-farajaland/pull/554

- [x] Create the HTML templates to Farajaland, taking example from [onboarding-invite.html](https://github.com/opencrvs/opencrvs-farajaland/blob/2fa-email/src/email-templates/onboarding-invite.html). Also amend `email-service.ts` with corresponding variables & templates. - 2
  - [x] Onboarding invite
  - [x] 2 factor authentication
  - [x] Password reset
  - [x] Password reset by system admin
  - [x] Username reminder
  - [x] Change phone number
  - [x] Username updated
- [ ] Refactor the Farajaland notification handler to handle SMS's and emails. Move [this handlebars templating logic](https://github.com/opencrvs/opencrvs-core/blob/develop/packages/notification/src/features/sms/utils.ts#L54-L80) to Farajaland. Use nodemailer to send the emails using SMTP. Riku will provide SendGrid SMTP server details to test. These SMTP details need to be configured in Farajaland environment variables, similar to Infobip or Clickatell. - 3

**Comment by Zangetsu101** [comment]
Completed in #5260
