### ISSUE TITLE
Change phone number from settings is not working

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5181]
**Bug description:**
Change phone number from settings is not working

**Steps to reproduce:**
1. Login to any user
2. Go to settings
3. Click change besides phone number
4. Enter new Phone number >click continue

**Actual result:**
Continue button is not working

**Expected result:**
User should be able to navigate to Verify phone number page

**Screen recording:**

https://images.zenhubusercontent.com/91778759/bdbb4901-8fc2-4a0a-a69b-6fd099005ae2/change_phone_number_from_settings_is_not_working.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by anny320** [comment]
completed
