### ISSUE TITLE
Organisation view missing in Side Nav for Performance Manager

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#5190]
**Describe the bug**
- Missing link for organisation on side nav
**Which feature of OpenCRVS your bug concern?**

**To Reproduce**
Steps to reproduce the behaviour:

1. Login as a performance manager '...'
2. Scroll down the side nav for organisation
5. See error

**Expected behaviour**
Organisation should be visible for performance manager

**Actual behaviour**
Write what happened. Please add screenshots!

**Screenshots**
![Screenshot 2023-04-28 at 14.59.47.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/be2f2338-c697-4bca-9a4b-ee13599b7c13)
**OpenCRVS Core Version:**

- v1.1.0 (Git branch: master / release-v1.1.0)

**Country Configuration Version:**

- v1.1.0 (Git branch: master / release-v1.1.0)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Possible fixes**
(If you can, link to the line of code that might be responsible for the problem)

**Reproducible demo**

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by Nil20** [comment]
https://user-images.githubusercontent.com/32668488/236409781-3ff008eb-3449-4e16-acea-64f7a937d142.mp4

**Comment by Zangetsu101** [comment]
Blocking this for further discussion. @anny320 @jpye-finch

**Comment by anny320** [comment]
Hi @Zangetsu101  an update on this ticket: we will also remove the organisation view for the Performance Manager so we can proceed to close this ticket. FYI @SyedaAfrida  we will remove this  QA testcase too

**Comment by Zangetsu101** [comment]
Alright!
