### ISSUE TITLE
Multiple blank spaces are in the user address if some of the fields are empty

### ISSUE THREAD

**Issue by ShohelaTasin** [opencrvs/opencrvs-core#5192]
Improvement : 
Description : 
After entering data into address fields while creating a new records, 
we face a trivial view from review page!  

Actual Result : 

Data seems in a noisy manner! 
No clue for what data indicate what specific field! 
And seems blank spaces while entering non adjacent/non immediate fields!

Expected Result :  
No additional line gaps should exist 

Screen Recording : https://www.loom.com/share/278910ad33334a039581e828b6053675

![Screenshot (40).png](https://images.zenhubusercontent.com/64228745932c6179b3fb3fb2/1e84c7e7-a5a1-48a3-be03-eccac7579e2e)

**Comment by jpye-finch** [comment]
We should remove the blank lines if no data is entered.

So the above example would read:

El Salvador
Mohakhali
District required for registration
United
Land

**Comment by euanmillar** [comment]
@eduffus @SyedaAfrida this seems trivial and needs a re-test and re-prioritisation

**Comment by jpye-finch** [comment]
@SyedaAfrida @euanmillar 

Flagging this ticket for reprioritisation. Would be good to fix. 

![Image](https://github.com/user-attachments/assets/08e6851c-fa8a-4b9b-b39d-c8571d2d06f3)
