### ISSUE TITLE
Email: Improve the configurability of the notification logic

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#5201]
### Description

We wanna improve the configurability of notification logic, to allow countries to be flexible using SMS/Email/Whatsapp/whatever

### Core backend

- [ ] Refactor [`buildAndSendSMS`](https://github.com/opencrvs/opencrvs-core/blob/623f3c7d4cf30ee7514ab0ed5ed09e31df366e17/packages/notification/src/features/sms/utils.ts#L82):
  - rename it to `sendNotification`
  - instead of building the handlebars, send the variables directly to Farajaland `${COUNTRY_CONFIG_URL}/notification`
  - See payload example type below
  - Either pass the identifier as route or in payload, to identify which template we wanna use - 2
- [ ] Refactor existing calls to `buildAndSendSMS`: in birth-handler & death-handler pass `'sms'` (as the notifications are being sent to informants phone number), and in user-handler pass either `'sms' | 'email'` depending on a environment variable called `USER_NOTIFICATION_DELIVERY_METHOD`. - 2

```
// Example payload type
type Notification = 
  { type: 'sms'; recipient_msisdn?: string; variables: { ... } } |
  { type: 'email'; recipient_email?: string; variables: { ... } } 
```

**Comment by Zangetsu101** [comment]
completed in #5260
