### ISSUE TITLE
User should not be able to save any draft when clicked back without doing save and exit

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5202]
**Bug description:**
User should not be able to save any draft when clicked back without doing save and exit

**Steps to reproduce:**
1. Login as FA
2. Declare a birth/ death/ marriage event
3. Continue till main point of contact page
4. Enter null or a wrong phone number
5. Click Back> Back> Cross and observe
6. Click update and complete the whole form except phone number
7. Click Send for review and observe

**Actual result:**
1) When Clicked back without doing save and exit the record gets save as draft
2) Later when the record is completed and send for review, The record gets stuck in outbox

**Expected result:**
User should not be able to save any draft when clicked back without doing save and exit

**Screen recording:**
https://www.loom.com/share/50a5c23dc10a4e2bad623638dd22aa7b
![ph](https://user-images.githubusercontent.com/94350336/235636741-3cebc627-0aa9-40c3-a58c-d9b7e8729e9b.png)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by euanmillar** [comment]
@SyedaAfrida @eduffus @anny320 @jpye-finch the user experience here allows this to happen.  What if the user adds some information that they want.  They click save and exit in the correct place. Then they re-open the application and delete the information, including the phone number and go backwards and hit cross.  You dont want the entire draft deleted.  So I think that the cross and save functionality shouldnt change.  Instead we need to:

1. Disable the send for review button if a phone number is absent.
2. Ensure Record Audit page gracefully handles the absence of a phone number for FA

**Comment by anny320** [comment]
completed
