### ISSUE TITLE
Should not allow to create/edit new user with phone number used by another user

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5203]
**Bug description:**
Should not allow to create/edit new user with phone number used by another user

**Steps to reproduce:**
1. Login to national system admin
2. Click Team
3. Create new user
4. In phone number enter a phone number of an existing user
5. Click Continue> Confirm

**Actual result:**
Able  to create/edit new user with phone number used by another user

**Expected result:**
Should show error below phone number field and review page- "This phone number is already used by another user"
User should not be able to confirm without entering new phone number

**Screen recording:**

https://www.loom.com/share/47096483e67e4ee89f8b761ead5fee00

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by sifulovi** [comment]
@SyedaAfrida. Could not produce this issue locally, it's working as expected.

[screen-capture (4).webm](https://user-images.githubusercontent.com/11840131/236387681-110ea860-73ef-47a5-961d-622d210db429.webm)

**Comment by ShohelaTasin** [comment]
@anny320 this ticket is fixed! Can be closed now! 
Recording : https://www.loom.com/share/dcccf0c2052e4759a72594731f25ae5a

**Comment by anny320** [comment]
completed
