### ISSUE TITLE
Incorrect fonts in certificates

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#5204]
Two fonts are used in certificate currently
- Noto Sans Light
- Noto Sans Regular

![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/5d681f37-c1fe-4ca9-ba81-9a64b0995d27)

See code:
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/314a5222-869f-47b9-b627-c742e2f26739)
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/4cc824c0-14a8-4679-8d38-d19d7a8024de)
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/d7a1198f-1db0-42d5-bbf6-0b31f0afd3a6)

We should be using:
- Noto Sans Regular
- Noto Sans Semibold

Think we need to replace NotoSans-Light.tff and it's base 64 code to NotoSans-SemiBold. 

![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/46d59586-992b-4097-b0be-cbb1c99e3d74)

**Comment by SyedaAfrida** [comment]
fixed
