### ISSUE TITLE
ANALYTICS_MONGO_URL isn't passed on deploy but the migrations try to use it

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#5214]
When deploying, migrations service is giving this:
```
$ /usr/src/app/node_modules/.bin/migrate-mongo status --file ./migrate-mongo-config-performance.js
ERROR: connect ECONNREFUSED 127.0.0.1:27017 MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:2701
```

The IP address it's trying to connect seems to be wrong. I think it's because we don't set it in docker-compose.yml.

Compare "OPENHIM_MONGO_URL":
![image](https://user-images.githubusercontent.com/1322608/235890540-5680e8eb-ffc8-4f6a-a2b3-a3b4da42e2d9.png)

To:
![image](https://user-images.githubusercontent.com/1322608/235890568-9f71fbec-f554-4e57-b6c3-130a57d35a71.png)

**Comment by Zangetsu101** [comment]
@naftis There seems to another issue with it now
![image](https://github.com/opencrvs/opencrvs-core/assets/29002716/578d5e7f-a178-41bd-9fa9-9f8b2dd4d68d)
