### ISSUE TITLE
Should show original state when anything is changed in the modal and closed / cancelled without being applied

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5216]
**Bug description:**
Should show original state when anything is changed in the modal and closed / cancelled without being applied

**Steps to reproduce:**
1. Login as National System admin
2. Click Configuration> Declaration forms> Configure> Settings
3. Click any Change link
4. Make any toggle ON/ Or change any radio button from 1 to 2
5. Click Cross/ Cancel and observe
 
**Actual result:**
The change made in the toggle/ radio button appears after cancel/ cross

**Expected result:**
User should not see the change as it was cancelled or crossed

**Screen recording:**

https://images.zenhubusercontent.com/91778759/686309a6-3026-4dd0-b351-0182bac46960/should_show_original_state_when_anythin_is_changed_in_the_modal_and_closed__cancelled_without_being_applied.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Nil20** [comment]
https://github.com/opencrvs/opencrvs-core/assets/32668488/2d89a357-c6e2-4159-b8e5-7e80350bc47a

**Comment by anny320** [comment]
Completed
