### ISSUE TITLE
Phone numbers in backups have spaces, need to understand why

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5223]
For some reason the data in Pyry's user-mgnt.users has +260 92 1681112  spaces between the numbers

I’m not convinced that this PR is right: 

https://github.com/opencrvs/opencrvs-core/pull/5143 

If you look at the use of phoneUtil.format, maybe we need to clear any spaces on the generated numbers in core Farajaland & Cameroon.

This caused a bug Pyry discovered when testing 2FA

**Comment by euanmillar** [comment]
@rikukissa FYI ...

**Comment by rikukissa** [comment]
Fixed in this PR: https://github.com/opencrvs/opencrvs-farajaland/pull/555
