### ISSUE TITLE
When an existing user role is editted, the updated  role is not showing in record audit in english

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5236]
**Bug description:**
When an existing user role is editted, the updated  role is not showing in record audit in english

**Steps to reproduce:**
1. Login to National system admin
2. Click Configuration> User roles> any change link
3. Click any edit button> make update
4. Change dropdown in french> Click edit> Update in french> Apply
5. Logout
6. Login to the updated user role
7. Click Download> assign> name and observe the role name in english
8. From settings Change Language to french
9. Again observe the role name in french

**Actual result:**
The updated role in english is not showing in record audit . However correctly showing in french

**Expected result:**
When an existing user role is editted, the updated  role should show correctly both in english and french

**Screen recording:**
https://www.loom.com/share/2dcb37a111ad45eabee35286acb7f48e

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
@anny320 @SyedaAfrida The issue is that at the time of "Send notification for review" the field agent was still a "Social Worker". So that part is correct. Instead what I would suggest is that even after changing to french, it should still show the english label of that time as we only store the english role for every record audit history action

**Comment by anny320** [comment]
hi, @Zangetsu101 I think with @SyedaAfrida that if the language is set to French or English,  the label should reflect the language setting. i.e. It should show the updated user role in English and French for the record. Or, it should show properly the old role in English and French. But it should not show English role while the language is in French

**Comment by Zangetsu101** [comment]
We need to save the label of default language

**Comment by euanmillar** [comment]
@Zangetsu101 please also check that the right label is being assigned in the first place re #5302 as it looks entirely wrong. Gondwe has never been a social worker.

**Comment by Zangetsu101** [comment]
@euanmillar As you had mentioned previously, we need to take into account what the default language is when saving the role label. So we that value in both the user-mgnt & gateway microservices. But we have a bit of tech debt here as we only know about the default language in client & login.

**Comment by Zangetsu101** [comment]
- [ ] When creating/editing a user, make sure we are storing the all roles as a JSON string as mentioned in the above comment
- [ ] In gateway type resolver for History->user, merge the user role with the one found in practitionerRole
The way to test this is: create a declaration using a field agent, then update the role of that field agent to some other role. Perform another action on that previous declaration with the same user, say assign it, then check the history of that declaration and make sure the roles are appearing correctly even after changing the language. The started by row should show the role "Field Agent" while the assigned row should show the new role

**Comment by SyedaAfrida** [comment]
**Bug:**
 Updated user role is not showing in both english and french. This is now happening for both existing and newly created user type
https://www.loom.com/share/7d306f60b5d54829a9ab44ecef70665b?sid=4a5f552d-3102-470b-b3e0-d3df99e33c19

**Comment by Zangetsu101** [comment]
@euanmillar If we don't let the users edit an existing role & they can only add a new role then it would enable us to resolve the bug we are facing currently. We could also let a role be permanently deleted (from the user's perspective) & in the system save it as inactive.

**Comment by Zangetsu101** [comment]
We need to come to a decision about this before the release otherwise it would require a migration afterwards

**Comment by Zangetsu101** [comment]
@jpye-finch @eduffus Fixing this bug requires a solution that we will be implementing when integrating with G2P-connect which would require months. In the meantime, let's remove the edit button instead and we can bring it back afterwards. What do you think?

**Comment by eduffus** [comment]
@Zangetsu101 as discussed, agree with your proposal. Let's disable the role edit capability for now. If a country wants to change a role (e.g. title) they will have to create a new role and then move existing users to this new role.
@jpye-finch please help with UI modifications for this.

**Comment by SyedaAfrida** [comment]
This ticket is fixed

https://github.com/opencrvs/opencrvs-core/assets/94350336/fa79d6f2-dfde-4b56-8243-99d07cee447a
