### ISSUE TITLE
While entering into correction record for birth registration Bride and Groom these options seems unproductive in correction requester page!

### ISSUE THREAD

**Issue by ShohelaTasin** [opencrvs/opencrvs-core#5237]
Bug description:
Bride and Groom options seem available for Birth registration of a child!

Steps to reproduce:
1. log in as Registrar
2. Go to ready to print for any birth records
3. Go to correction records 
4. GO to Correction Requester page

Actual Result : 
Bride and Groom option seems available!

Expected result:
No need of Bride and Groom options for a child while correcting a birth record!![Screenshot (54).png](https://images.zenhubusercontent.com/64228745932c6179b3fb3fb2/30dc4133-560b-417a-8f21-84873ee81208)

**Comment by ShohelaTasin** [comment]
@anny320 This ticket is fixed! can be closed now!  
![ok](https://github.com/opencrvs/opencrvs-core/assets/41486148/8344da01-f680-47fe-af9d-a92419a559f5)

**Comment by anny320** [comment]
completed
