### ISSUE TITLE
In correction records warning is appearing in correction summary page even after entering correction payament doc! 

### ISSUE THREAD

**Issue by ShohelaTasin** [opencrvs/opencrvs-core#5238]
Bug description:
After uploading payment receive document for correction records , user will see the same text before uploading the doc!  

Steps to reproduce:

 1. Log in as Registrar
 2. Go to any records
 3. Go to correction records 
 4. Do some changes
 5. Go to Fees required 
 6. Select Yes
 7. Input fee value and upload doc
 8. Observe

Actual Result :
After uploading payment receipt, user will able to see text like Document required! 

Expected result:
No text should be seen after completing upload!

Recording : https://www.loom.com/share/12668f1013004e689d61285866f39d13

**Comment by ShohelaTasin** [comment]
@anny320  This ticket is fixed! Can be closed Now!   

Recording :  https://www.loom.com/share/fb62334994d546e9937c1effecd8f0b1

**Comment by anny320** [comment]
Completed
