### ISSUE TITLE
Invalid data showing in correction record when location is changed!

### ISSUE THREAD

**Issue by ShohelaTasin** [opencrvs/opencrvs-core#5240]
Bug Description : 
Invalid data showing in correction record when location is changed!

Steps : 
1. Log in as Registrar 
2. Go to ready to print
3. Go to correction record
4. Do some changes
5. Make a correction 
6. Then click into the same application from ready to print
7. Check the status
8. Go to corrected record 
9.Observe

Actual Result : 
Invalid data showing in while checking correction record

Expected Result : 
User should face only relevant information!

Scrrenshot :![Screenshot (58).png](https://images.zenhubusercontent.com/64228745932c6179b3fb3fb2/22c159a6-ce14-4778-b7c1-2a8a0ee8a4ed)![for death in cor rec 1.png](https://images.zenhubusercontent.com/64228745932c6179b3fb3fb2/a5542ef4-6e97-4864-8e54-908e2c1c57b8)

**Comment by Zangetsu101** [comment]
I'm guessing this is working for primary address but not for the secondary address. The fix for primary address is in this PR(https://github.com/opencrvs/opencrvs-core/pull/4508). Need to add the names of the secondary address fields

**Comment by ShohelaTasin** [comment]
@anny320 This ticket is fixed! Can be closed Now!

Recording : https://www.loom.com/share/16e776f5ef9e434ba63eef8a80fe37df

**Comment by ShohelaTasin** [comment]
All related data seems inappropriate while corrected records(correction) done multiple times for the same record! 

Recording : https://www.loom.com/share/516071997a7b42a3a172068d93472a11

**Comment by SyedaAfrida** [comment]
this ticket is fixed
https://www.loom.com/share/be39a70e76b042e395c9b2b510cf0151?sid=b2d3bc0d-46d8-4777-a3e6-f7b35fbd98be
