### ISSUE TITLE
If "usual place of residence" is submitted as "Yes"  then shows "No" after the declaration is viewed/ reviewed

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5244]
**Bug description:**
If "usual place of residence" is submitted as "Yes"  then shows "No" after the declaration is viewed/ reviewed

**Steps to reproduce:**
1. Login as FA/ RA/ Registrar
2. Declare a death event
3. In informant page, select yes radio button in usual place of residence is same as informant
4. Observe the review page and submit the record
5. Find the record from workqueue
6. Click Download> Assign> Review/ view
7. Observe usual place of residence option

**Actual result:**
Before submitting record, shows yes in usual place of residence in review page. But after submitting, shows no in usual place of residence in review page. 

**Expected result:**
Should show yes in usual place of residence before and after submitting record

**Screenshot :**
before submitting
![usual place or res2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/0cf5eb45-c1a2-4390-b0bf-53793e385526)

after submitting
![after sub in view.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/0f2d9b94-8ac6-4478-9fc3-3fb3aa2bd9b3)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://github.com/opencrvs/opencrvs-core/assets/94350336/bd04d220-84d3-46c6-ab40-4d2a7d565972

**Comment by anny320** [comment]
Completed
