### ISSUE TITLE
In mobile view, cannot view side navigation options

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5258]
**Bug description:**
In mobile view, cannot view side navigation options

**Steps to reproduce:**
1. Login as any user from mobile
2. Click in the side nav option and observe

**Actual result:**
User cannot view side navigation options

**Expected result:**
User should be able to view side navigation options

**Screen recording:**

https://images.zenhubusercontent.com/91778759/4ceeaf9d-12b6-4cbd-b3bc-87c50641f6c8/side_nav_not_working_in_mobile_view.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by jpye-finch** [comment]
this was introduced by me. Will push a fix
