### ISSUE TITLE
Ready to review workque should not update record count when Registration agent sends a record for approval

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#5268]
**Describe the bug**
Ready to review work queue count is updating briefly (flashing) when a registration agent sends a record for approval
**Which feature of OpenCRVS your bug concern?**

**To Reproduce**
Steps to reproduce the behaviour:

1. Login as FA, send a complete declaration.
2. Login as RA and review a record and click send for approval. 
3. Observe the behavior in the workqueues, (Ready for review blinks to 3 then disappears then sent for approval increases to 2.)
Note: This is happening for all the workqueues, not only ready for review
**Expected behaviour**
Only the sent for approval workqueue count should update when a record is sent for approval

**Actual behaviour**
Ready for review blinks to 3 then disappears then sent for approval increases to 2(pause on the12th second in the recording)

**Screenshots**
https://www.loom.com/share/fa33631f939f41778ba38d27295bea22

**OpenCRVS Core Version:** v1.3

- v1.1.0 (Git branch: master / release-v1.1.0)

**Country Configuration Version:**

- v1.1.0 (Git branch: master / release-v1.1.0)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Possible fixes**
(If you can, link to the line of code that might be responsible for the problem)

**Reproducible demo**

**Comment by SyedaAfrida** [comment]
@anny320 this bug can be closed

https://github.com/opencrvs/opencrvs-core/assets/94350336/d345ab83-fc46-4e5d-b207-e2a74fe1938a

**Comment by anny320** [comment]
completed
