### ISSUE TITLE
Remove the extra witness label from marriage form

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#5276]
![image](https://github.com/opencrvs/opencrvs-core/assets/29002716/0a8b838f-b044-49e3-be83-de0288986703)
We don't want the "Witness 1" label to be present here. Same goes for witness 2

**Comment by ShohelaTasin** [comment]
@anny320  This ticket is fixed! Can be closed Now!
![Screenshot (103)](https://github.com/opencrvs/opencrvs-core/assets/41486148/49484863-2530-4560-bb7a-21cf5490ca48)
![Screenshot (104)](https://github.com/opencrvs/opencrvs-core/assets/41486148/c135ab32-ba41-4f14-9f3c-bdcbf2aad8d3)
