### ISSUE TITLE
While filling up a form if clicked back all the data disappears

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5280]
**Bug description:**
While filling up a form if clicked back all the data disappears

**Steps to reproduce:**
1. Login to FA/ RA/ Registrar
2. Start filling up a birth/ death/ marriage declaration
3. Click back and observe

**Actual result:**
While filling up a form if clicked back all the data disappears

**Expected result:**
While filling up a form if clicked back, user should be able to view all the inputted data that he filled up previously 

**Screen recording:**

https://www.loom.com/share/657d3bee2395498e9cfd49bac7953794

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by ShohelaTasin** [comment]
Not fixed! 
Recording : https://www.loom.com/share/202d15de6e0b4a6aba5186a8f5573f89

**Comment by SyedaAfrida** [comment]
This bug is fixed.

https://github.com/opencrvs/opencrvs-core/assets/94350336/6e28df66-6cf0-42ac-9b23-f04152699bee
