### ISSUE TITLE
upgrade workbox from v4 -> v6

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#5283]
This should close this dependabot alert: https://github.com/opencrvs/opencrvs-core/security/dependabot/85
Or perhaps we switch to using https://github.com/vite-pwa/vite-plugin-pwa

**Comment by SyedaAfrida** [comment]
This ticket is fixed

https://github.com/opencrvs/opencrvs-core/assets/94350336/76f4bf1b-aba4-459e-8111-f7e2abde6bb1
