### ISSUE TITLE
Cannot view supporting document in offline state

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5289]
**Bug description:**
Cannot view supporting document in offline state

**Steps to reproduce:**
1. Login to RA/ Registrar
2. In online state Assign any record that has supporting document and signature
3. Go offline
4. Click Review and observe supporting document

**Actual result:**
User cannot view supporting document in offline state

**Expected result:**
User should be able to view supporting document in offline state

**Screen recording:**
https://www.loom.com/share/e0718913e7614c708c6d55df2d2ca539

**Tested on:**
browserstack

**Comment by Zangetsu101** [comment]
@SyedaAfrida Could you please try this with a physical device and let us know?

**Comment by SyedaAfrida** [comment]
@Zangetsu101 this is actually not a mobile bug. Rather it is related to the connectivity of the device. I was able to reproduce this bug in slow connectivity from web. If you assign the record in slow 3g. then go offline and review, it is not able to view the document. 
 Check this recording-
https://www.loom.com/share/7be4f45b08594c08957b3e9a2c1679db

In the recording, the file size was 434 kb which we were not able to see in offline state.
