### ISSUE TITLE
In history, Time value is not appearing for Started Action

### ISSUE THREAD

**Issue by ShohelaTasin** [opencrvs/opencrvs-core#5300]
Bug Description : In history, Time value is not appearing while clicking on started  action

Steps to reproduce: 
1. Log in as RA
2. create a marriage record
3. Save and Exit
4. Go to In progress
5. Check drafts
6. Check History
7. Click on started 

https://images.zenhubusercontent.com/91778759/bf5a99be-2957-450f-ac9e-b7df366f5553/screenrecording_11_4_2023_18_11.mp4
Actual Result : Time value is not appearing while clicking on started  
Expected Result : Time value should be appeared correctly!

**Comment by ShohelaTasin** [comment]
@anny320 This ticket is fixed! Can be closed Now! 
![bugTestSuc](https://github.com/opencrvs/opencrvs-core/assets/41486148/7f8ef079-d0dc-4f02-b7d8-a9d658b98892)

**Comment by anny320** [comment]
completed
