### ISSUE TITLE
Wrong user role is showing in record audit for an existing user

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5302]
**Bug description:**
Wrong user role is showing in record audit for an existing user.
In illanga district Patrick Gondwe is a Local Leader. However in record audit it is showing as social worker.

**Steps to reproduce:**
1. Login to p.gondwe
2. Declare any event
3. In sent for review, retrieve the record and observe history
 
**Actual result:**

![t.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/95ced8be-cc5f-449f-820e-593a67211bb8)

**Expected result:**
In record audit, should show local leader

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
This is related to the migration of PractionerRole. Previously only the role (e.g. FIELD_AGENT) of the user was stored in it, not the type (e.g. LOCAL_LEADER). So in the migration we just went with Social Worker for all the field agents. I'm blocking this for now as we need to figure out what to do about it

**Comment by euanmillar** [comment]
Lets make 1.2 migrating users: "Field Agent" and they can change this in the UI

**Comment by Zangetsu101** [comment]
https://github.com/opencrvs/opencrvs-core/blob/develop/packages/migration/migrations/hearth/20230127063226-update-practitioner-role.js#L103 change 'Social worker' to 'Field agent'

**Comment by Zangetsu101** [comment]
In this migration: https://github.com/opencrvs/opencrvs-core/blob/develop/packages/migration/migrations/user-mgnt/20221229110512-modify-user-roleAndtype-fieldName.js, we were creating 3 roles for FieldAgents namely Local leader, Police worker & Social worker instead now we want only have one role which will be just "Field Agent"

**Comment by SyedaAfrida** [comment]
This bug is fixed
![fa](https://github.com/opencrvs/opencrvs-core/assets/94350336/da877651-cd74-4663-8ed0-58f1be8c9a06)
