### ISSUE TITLE
Update status of reinstated potential duplicates field from Archived to In review in the duplicate review page

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#5305]
1. Potential duplicate is marked as duplicate and automatically archived.
2. Reinstated the record by the Registrar
3. Record appears (correctly in Ready for Review)
4. Status of the record is still "archived" whereas it should be "In Review"

![image (35).png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/6f768f26-5b6f-4f71-8f21-cfcd4da7dbf4)
Screenshot

**Comment by jpye-finch** [comment]
@SyedaAfrida does this bug still exisit?
