### ISSUE TITLE
Death: only show "Please specify field" when manner of death = other

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#5311]
Only show the "Please specify" field when the "Other" option is selected. Rename "manner undetermined" to "Other".

<img width="406" alt="image" src="https://github.com/opencrvs/opencrvs-core/assets/1206987/589c86ec-13a2-4b92-a086-019c067e528e">

**Comment by tahmidrahman-dsi** [comment]
Should be fixed by https://github.com/agence-digital/opencrvs-cameroon/pull/98/
