### ISSUE TITLE
Change copy and resend the onboarding invite

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5328]
When creating a new user, there is a 3 - dot menu option: "Resend SMS Invite" - rename to "Resend invite", then make sure either the SMS or Email is sent.

![Screenshot 2023-05-16 at 09.53.24.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/4ac4d8eb-b1ef-46a1-9b36-16f1a7f42e44)

**Comment by SyedaAfrida** [comment]
This ticket is tested
![3](https://github.com/opencrvs/opencrvs-core/assets/94350336/3e152002-a8ad-4c27-84d7-73279a650bd6)
![2](https://github.com/opencrvs/opencrvs-core/assets/94350336/f8f09597-db4a-4f48-8c46-38e53ddd9c67)
![1](https://github.com/opencrvs/opencrvs-core/assets/94350336/e517b46b-d0ca-4ade-8e0b-57751a48050e)
