### ISSUE TITLE
Configurable informant type / contact page & docs (Email / SMS / Validations on/off)

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5329]
Some countries use SMS for informant contact

Some countries e.g Niue use Email

Some countries (Cameroon) dont want any informant contact and complain about the screen

Some countries dont like informant type

Some countries dont like document validations

We need a solution for the informant type and contact type pages

We need a solution for the Review page - declaration details

We need a solution for the Record Audit page

We need a solution for mothers fathers details not available (dumb down validations)

We need a solution for documents page (dumb down validations)

We need a solution for saving a draft

Using an environment variable you should be able to configure these pages and validations on / off. If it is off, then all Record Audit screens, Document pages Review Screens need to not depend on the phone number or email

If the page is configured on, we should be able to select if both the phone or email are mandatory or not

If the page is configured on, we should be able to select if both the phone or email are visible or not

**Comment by jpye-finch** [comment]
@euanmillar can this be closed?
