### ISSUE TITLE
In marriage declaration, place of marriage should show district state and country when country is other that farajaland

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5333]
**Bug description:**
In marriage declaration, place of marriage should show district state and country when country is other that farajaland

**Steps to reproduce:**
1. Login to any user
2. Declare a marriage event
3. In place of marriage select any country other than farajaland and enter state and district
4. Submit declaration
5. Click Download> Assign > record name of that declaration
6. Observe place of marriage

**Actual result:**
Place of marriage is showing only country name

**Expected result:**
Place of marriage should show district, state, country name

**Screenshot:**

![in marriage declaration, place of marriage should show district state and country when country is other that farajaland.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/397ac396-aaea-4234-8194-556f7b39ec3b)
![in marriage declaration, place of marriage should show district state and country when country is other that farajaland--2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/308ed495-2596-482f-b87f-bec4f23c8235)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![5333](https://github.com/opencrvs/opencrvs-core/assets/94350336/295c982b-23f3-45a0-951e-f857c9de15cb)

**Comment by anny320** [comment]
completed
