### ISSUE TITLE
When fails to download any record as offline, name changes to 'No name provided'

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5345]
**Bug description:**
When fails to download any record as offline, name changes to 'No name provided'

**Steps to reproduce:**
1. Login to any user
2. Click download to any record
3. Go offline before download completes
4. Observe the name of the record

**Actual result:**
When fails to download any record as offline, name changes to 'No name provided'

**Expected result:**
Should show the original name in workqueue and record audit page even if download fails

**Screen recording:**

https://images.zenhubusercontent.com/91778759/9990b281-d9d5-4be1-9f02-b1e89b42156a/screen_recording_20230517_161645_chrome.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://github.com/opencrvs/opencrvs-core/assets/94350336/baf02fbb-a8ff-4e15-966a-13f3d264044a

**Comment by anny320** [comment]
completed
