### ISSUE TITLE
Role field on user audit row showing incorrect data (mobile)

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#5352]
Steps to recreate
1. Login as a registrar
2. Select any record in inprogress tab
3. Assign.
4. Scroll to history table and click user eg Kalusha , redirects to useraudit table
5. Observe role field. See error
![Screenshot_2023-05-18-04-17-07-66_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://images.zenhubusercontent.com/61d3cc06859638b515717606/36343bba-82dc-4d68-b4e7-bc3fd26d8603)

Note: same error recurring in team page![Screenshot_2023-05-18-04-35-37-85_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://images.zenhubusercontent.com/61d3cc06859638b515717606/b52ddeac-3f29-41cb-a72b-87e977770cb8)

**Comment by sifulovi** [comment]
It raises when the network is too slow. Otherwise, there are no issues.

![1684914678197](https://github.com/opencrvs/opencrvs-core/assets/11840131/ef2206d4-53e5-4c30-8556-075b1fd1eb84)

**Comment by Zangetsu101** [comment]
@anny320 This looks like a pretty rare edge to appear and which even goes away after refreshing. I don't think it's worth the effort to fix

**Comment by anny320** [comment]
closed.
