### ISSUE TITLE
For duplicate records, sometimes comparison review page do not appear after click in tracking id

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5359]
**Bug description:**
For duplicate records, sometimes comparison review page do not appear after click in tracking id

**Steps to reproduce:**
1. Login to any user
2. Download> Assign> Review any duplicate record
3. Click tracking id
4. Logout
5. Login again
6. Click review> tracking id of the same record and observe

**Actual result:**
comparison review page do not appear after click in tracking id takes a lot of time

**Expected result:**
Should view comparison review page immediately after click

**Screen recording:**

https://images.zenhubusercontent.com/91778759/7d22963c-db23-43d9-91fc-79de672c5201/videoeditor_20230518_034212.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
This looks to me as if apollo-cache-persist isn't working as expected for some reason.

**Comment by Zangetsu101** [comment]
I tested this locally & on staging as well. It seems to be working there so @SyedaAfrida could you revisit this and let me know if you encounter this again?

**Comment by ShohelaTasin** [comment]
@anny320  This ticket is fixed! Can be closed Now!
Recording : https://www.loom.com/share/ffcf126d675947e68b3595156b92fe42

**Comment by anny320** [comment]
completed
