### ISSUE TITLE
In mobile view, heading is missing in multiple places 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5361]
**Bug description:**
In mobile view, heading is missing in multiple places 

**Actual result:**
User role:
![header missing in mobile view 1.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/141f193e-3a77-4a30-a76d-634e46e17e42)

informant notification:
![informant notification header missing .png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/08befe0d-1e18-421c-82db-41cf574a50ac)

Vital statistics:
![declarations heading in vital statistics.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/1ff1e29e-52e1-4e0c-903e-bd7cb4bd3ef8)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by ShohelaTasin** [comment]
@anny320 This ticket is fixed! Can be closed Now!

![Screenshot (121)](https://github.com/opencrvs/opencrvs-core/assets/41486148/0cbdca4b-2637-4cb7-8897-9eaca5972753)
![Screenshot (122)](https://github.com/opencrvs/opencrvs-core/assets/41486148/4a115bcd-8bdd-44e9-b547-720be2ea970f)
![Screenshot (123)](https://github.com/opencrvs/opencrvs-core/assets/41486148/9d0f8762-303f-4ef9-befc-793a60253783)

**Comment by anny320** [comment]
completed
