### ISSUE TITLE
Death: "Please specify" field should appear inly if the user choose "Other" in "Circumstances of death" field

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#5363]
<img width="750" alt="image" src="https://github.com/opencrvs/opencrvs-core/assets/1206987/3254e32d-6fc2-4091-934d-ec0753d3151e">

**Comment by wilrona** [comment]
I've tested it and I can see that it works.

**Comment by rikukissa** [comment]
Agreed. It does work.
