### ISSUE TITLE
In Statistics, district filter not showing any option

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5368]
**Bug description:**
In Statistics, district filter not showing any option

**Steps to reproduce:**
1. Login as national system admin
2. Click Statistics
3. Click district filter and observe

**Actual result:**
In Statistics, district filter not showing any option

**Expected result:**
Should show all the district of selected state

**Screen recording:**

![tam.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/a565fb31-81a5-4ce0-9efb-f079202b4ecb)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
The related column for the district filter wasn't selected by default. I had to do it manually so we need to amend the questions sql file locally to have these selected by default

**Comment by Zangetsu101** [comment]
I think that was only for the map

**Comment by rikukissa** [comment]
Yup, the filter options are based on values in database documents

**Comment by anny320** [comment]
please advise on next steps for this ticket, we close it?

**Comment by SyedaAfrida** [comment]
This bug is fixed

https://github.com/opencrvs/opencrvs-core/assets/94350336/75dad273-4550-44ce-9838-2375eedd8caf
