### ISSUE TITLE
Dashboard: Update default time period widget to Current instead of previous 12 months

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#5371]
Currently, the user has to keep updating the default time period to see data correctly (due to lack of previous data), update the default period to the Current Month

Steps to recreate:
1. Log in as National Sys admin
2. click dashboard
3. observe (no data showing in some widgets)

Expected behavior: ![Screenshot 2023-05-18 at 15.47.43.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/c906ed2a-c4dc-444b-8f4d-1affd0e0f564)update the default period to the Current Month

Then the last month appears to spike its calculation dramatically

Steps to recreate:
Refer to Euan's comment below

**Comment by euanmillar** [comment]
I am also not convinced that when the current month is included that the query works properly.  In production, last 12 months looks like this:

![Screenshot 2023-05-19 at 06.07.58.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/1c9937b8-70a8-4c34-86f0-9dce3b09beb9)

**Comment by SyedaAfrida** [comment]
@anny320 since by default we can view data when the filter is previous 12 months (including this month), this ticket can be closed
![d](https://github.com/opencrvs/opencrvs-core/assets/94350336/232f3fae-ad79-470c-b02a-70fe4c510efe)

**Comment by anny320** [comment]
Completed
