### ISSUE TITLE
Dashboard:  Missing label "issued" for the widgets -  % of Total Registrations Certified 

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#5373]
1. Log in as a National Sys Admin
2. Select Dashboard
3. Scroll to the widget % of Total Registrations Certified
4. Observe, the missing label for the Certified section

![Screenshot 2023-05-18 at 15.42.55.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/99bd692f-0b49-4b63-b195-6f2aa84d600e)

![issued missing](https://github.com/opencrvs/opencrvs-core/assets/94350336/6be01ac4-a58a-42b5-b839-b447865fc011)

Expected behaviour: add the label for the 'issued' Section

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![f](https://github.com/opencrvs/opencrvs-core/assets/94350336/9cf8f7bb-901f-44ff-bc2e-746d5e57446f)

**Comment by anny320** [comment]
Completed
