### ISSUE TITLE
Dashboard: Missing label for the widget in Statistics section for Live Births by Place of Births

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#5375]
1. Log in as National Sys Admin
2. Click on the statistics view on the side nav
3. Adjust time period to current
4. Observe the widget for Live births by place of birth- Missing label
5. 

![Screenshot 2023-05-18 at 15.39.37.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/830c945d-dc66-4ad3-8303-64b43d087137)

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![s](https://github.com/opencrvs/opencrvs-core/assets/94350336/a9b2b659-078c-4b28-b595-137aedaa24df)
