### ISSUE TITLE
In dashboard- States and districts do not appear in filters unless they are synced after every deployment

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5403]
**Bug description:**
In dashboard- States and districts do not appear in filters unless they are synced after every deployment

**Steps to reproduce:**
1. After deployment login to National system admin/ national registrar/ performance manager
2.  Click Dashboard and observe states filter

**Actual result:**
All the states options do not appear unless synced

**Expected result:**
Should be synced automatically

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
Not sure if it's related to deployment. Do the new filter values appear automatically otherwise?

**Comment by Zangetsu101** [comment]
Apparently new values for filters are synced once everyday. So @SyedaAfrida could you please confirm this? Like create a registration in a new district/state, then check if the new filter value appears within the next 24 hrs?

**Comment by SyedaAfrida** [comment]
@anny320 this ticket can be closed as all the filters of dashboard and statistics are synced after a certain time everyday but not immediately
![d](https://github.com/opencrvs/opencrvs-core/assets/94350336/b5419636-8334-46e2-afb1-a6af971aba2c)
