### ISSUE TITLE
Combine font usage for certificate preview and printing

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5420]
1. When uploading a certificate, there should be a way to upload all fonts used in the certificate. Then we do not have to embed the font into the certificate SVG.  If the certificate fonts could be loaded into the application separately, perhaps asynchronously, then the loading time would decrease.

2. Currently we have Noto Sans n `common_vfs.ts` in client and coming from Google Fonts in `src/index.ts`.  We should self host this font and then we could remove Google font API requests in nginx-default-config

**Comment by euanmillar** [comment]
@rikukissa I dont think we can fix this without a UI to upload the fonts used in the certificate as its only in our case that Noto Sans is used in all cases.  Some countries may use different fonts in each so we cant assume that the loading of Noto Sans can be optimised.

**Comment by rikukissa** [comment]
We are actually using Arial in Cameroon certificates which wasn't possible without a core modification. To make this possible, @tahmidrahman-dsi embedded Arial into our certificates, removed `common_vfs.ts` completely and instead read and used the certificate-embedded fonts for the PDF renderer configuration.  So now we have

- Noto Sans once as it's required for the UI
- Arial once per certificate as we need to have it in the templates

So we got down to 4/5 fonts which is better but not best. The next optimisation from here would be to have certificates not embed the base64 font but instead refer to `https://countryconfig.cameroon.opencrvs.org/Arial.ttf` which the browser could then cache indefinitely. This would get us to 2/5 fonts and there wouldn't be a need for a UI.

**Comment by jpye-finch** [comment]
@euanmillar @rikukissa for font's that are used for labels and other headings etc. We could require the country/designer to 'outline stroke' before exporting. So it essentially becomes a shape. 

So we would only support one font for the "data" that populates the certificate. 

Would then just need a UI to select the font you want to use for the data.

**Comment by euanmillar** [comment]
@jpye-finch what if the handlebar text has to appear in a certain font or style?

**Comment by jpye-finch** [comment]
Have yet to see an example of that beyond colour differences. But yes that could be a possible requirement.

**Comment by euanmillar** [comment]
Font usage in certs was updated in 1.3.1 so we should make a new ticket for improving font load
