### ISSUE TITLE
Fix backups and migrations properly for the different use cases

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5424]
Backups automatically revert migrations so that new migrations can be QA-ed.  That is a strange approach.  Instead backups should be forced to the previous version for QA deployments. Perhaps this is achieved in a Git action.

Remove reverting migrations from backup create and chain migrations, then db:populate and then db:backup:create together.
- [ ] update the db:populate script to create data in v1.3 state while previously we were going to the valid state through migrations.  amend the db:populate command to now do the following in sequence: clear:all:data -> run migrations -> db:populate -> backup zips creation. Deprecate db:backup:create command in package.json - 2
- [ ] Make sure that migrations run properly on an empty database - 1
- [x] create userroles before creating the users. change the users csv accordingly to somehow map to a created userrole by having an extra column.  Maintain a separate csv for the userroles - 2
- [ ] the following migrations need to be emulated, using gateways API (certs) or new constants in populate-default-config script - 2
```
20221221093004-store-informant-sms-notification.js
20230113115411-country-background.js
20230208081755-add-marriage-configuration.js
20230301124048-add-marriage-certificate-configuration.js
20230518055204-upload-certificate-templates-to-minio.js
```

- [ ] For openhim, make sure the password is set to the one mentioned in the readme before creating the backup zips
- [ ] Maintain backup zips for minio as certificate templates are saved there.  Edit all clear-all-data, restore-metadata - 1

**Comment by Zangetsu101** [comment]
Closing this as we will be working on refactoring farajaland completely.
