### ISSUE TITLE
Trackind id/ brn/drn and nid shows result with special characters!

### ISSUE THREAD

**Issue by ShohelaTasin** [opencrvs/opencrvs-core#5434]
Bug description:
Trackind id/ brn/drn and nid shows result with special characters!

Steps : 
1.log in as FA/RA/LR
2.Go to search
3. Search any record for a valid tracking id /BRN/CRN/ NID
4. search same tracking id for some special character
5. Observe

Actual Result : Manage to find tracking id or NID or BRN CRN!
Expected Result 1 : No search found! 

Expected Result 2 : No special character can not be in the text field while entering tracking id or BRN or NID!

Tested on : Mobile and Web

 ![Screenshot (116).png](https://images.zenhubusercontent.com/64228745932c6179b3fb3fb2/6171f8de-e346-40f0-b2b7-31085c95ced3):

**Comment by Zangetsu101** [comment]
we don't think this hinders the user with searching for records
