### ISSUE TITLE
Update password copy to suggest 12 character long passphrase

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5461]
Update password length to be 12 characters

Have some copy in the password popup to advise a pass phrase

“It is more secure, and easier for you to remember, if you use three random words.”

Therefore, as a user I might use: “S5us@gesandbeans”

“Y5kinukutoK!mchi”

**Comment by euanmillar** [comment]
@jpye-finch  We should also increase complexity of passwords and address copy associated when creating the passwords with green ticks etc: https://opencrvsworkspace.slack.com/archives/GHCFF9M6X/p1682167875658019

**Comment by eduffus** [comment]
Left in v1.4 for now but changed status to "blocked" based on @rikukissa comment here: https://opencrvsworkspace.slack.com/archives/GHCFF9M6X/p1697460995585359

**Comment by euanmillar** [comment]
I updated the description based on the agreedd approach
