### ISSUE TITLE
Subheading shows in Review page

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#5508]
### Description
- When designing the form you can use SubHeading
- This ticket is to show the subheading in the review page. 
- This will help to separate content in the review page so that is clearer to read and review. 
- Will help us to better support single page designs

### Acceptance criteria

GIVEN my form has a SubHeading
WHEN on the review page 
THEN show the Subheading
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=16985%3A131191&t=XgfmCfJdY0LtS145-1

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=16985%3A131742&t=XgfmCfJdY0LtS145-1

### Dev tasks

- [x] Code review and merge JPF's PRs: https://github.com/opencrvs/opencrvs-core/pull/5552 & https://github.com/opencrvs/opencrvs-core/pull/5558 resolve any conflicts and responsive problems in order to align form to new design - 1
- [x] Clicking continue button should move the scroll to the top of the page - 1
- [x] With SubSectionDivider - it needs to render on the review page in a different style. Add it randomly in the form and ensure that it appears in the Review page & DuplicateFormTabs but in a smaller font. - 2
- [x] Based on the dependent PRs update the form config in Farajaland to use the Heading-3 and dividers where necessary for birth, death and marriage. - 1

**Comment by euanmillar** [comment]
Explain that this goes on the review page in code comments
