### ISSUE TITLE
Saving and Exiting a declaration form

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#5510]
### Description
- separates exiting Saving & Exit into two buttons. Save & exit and Exit
- adds a confirmation dialog to Save & exit button
- adds confirmation dialog on Exit button
- use the new Dialog component

!! As art of this work can we replace EventTopBar with AppBar?? 

### Acceptance criteria

**In progress, In Review Requires Updates declarations**

**_Save and exit_**
GIVEN the declaration is open
WHEN I click Save & exit
[THEN show the confirmation dialog
](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=16985%3A132582&t=fFjqCWVLSzPAX3Kp-1)

GIVEN I the Save and Exit confirmation dialog is open
WHEN I click Confirm
THEN save any changes and close the declaration

**_Exit_**
GIVEN their are no changes
WHEN the user clicks Exit
THEN close the declaration

GIVEN their are unsaved changes
WHEN the user clicks Exit
[THEN show the Exit confirmation model
](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=17041%3A123583&t=BP8rYf7tx7PYi5aN-1)

GIVEN I the Exit confirmation dialog is open
WHEN I click Confirm
THEN close the declaration and discard any changes

**Event select**
Update the Exit button for Event Select a record to use Secondary / withIcon / medium
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=16858%3A120014&t=fFjqCWVLSzPAX3Kp-1

**View record**
Update the Exit button for viewing a record to use Secondary / withIcon / medium
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=16985%3A123619&t=fFjqCWVLSzPAX3Kp-1

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=16985%3A132582&t=XgfmCfJdY0LtS145-1

### Dev tasks

- [x] Work with JPF to refactor out EventTopBar with AppBar in Form. - 2
- [x] Build out Dialogs and draft saving / exiting process & logic for the form - refer to AC. - 2
- [x] Build exiting process & logic for View record - 1
- [x] Build out Dialogs and draft saving / exiting process logic for the review - refer to AC. - 1
- [x] Build exiting process & logic for the duplicate review page - 1

**Comment by SyedaAfrida** [comment]
**Bug:**
After once a change is made and save & exit is clicked, if any other change is made later and Exit is clicked, Exit modal do not appear and the changes starts getting saved. Moreover, there is no consistency between the changes in workqueue and record audit if change is made on names.

https://www.loom.com/share/49a1eb5f62c843b59e41bd5dd9b20892?sid=43d4a4fa-f775-48c8-b3aa-793d9a424cee

_Note: This bug only appear after save & exit is clicked. Before that exit functionality works properly_

**Comment by SyedaAfrida** [comment]
The above mentioned bug is fixed for complete declaration but not working for incomplete declarations. This bug is occurring for all events incomplete declarations

https://github.com/opencrvs/opencrvs-core/assets/94350336/1bad8e6c-2746-4353-b652-de28cc5fea83

**Comment by SyedaAfrida** [comment]
this ticket is fixed
