### ISSUE TITLE
Update birth form for Farajaland

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#5512]
### Description
- updates Farajaland default birth form
- flow > https://www.figma.com/file/pkvL1mtFzA8cbJZLhIohK2/Declaration%2FFarajaland%2FBirthv2?type=whiteboard&node-id=0%3A1&t=uLYkLuRqja4xieRa-1
- UI > https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=16691%3A118605&t=XgfmCfJdY0LtS145-1

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
https://www.figma.com/file/pkvL1mtFzA8cbJZLhIohK2/Declaration%2FFarajaland%2FBirthv2?type=whiteboard&node-id=0%3A1&t=uLYkLuRqja4xieRa-1

### Dev tasks

- [x] Refactor informantType, contactPoint, registrationPhone etc into informants details page - 1
- [x] Apply Rabiul's fixes to address [line](https://github.com/opencrvs/opencrvs-core/pull/5547) refactor to all addresses - 2
- [x] Refactor birth form into reusable functions in Farajaland - 2
- [x] Ensure that the completed form submits into Gateway and is retrievable in review on download.  Perform a manual e2e test from notification to certification min/max input and ensure all data works - 2
- [x] Create a fhir-builder and and type-resolver for Task,  RelatedPerson and Person email address so that the email address creates another ContactPoint with "email" type, amend any microservice that is expecting a single Person ContactPoint or a single Task ContactPoint - 2
- [x] Add email to ElasticSearch - 1

**Comment by Zangetsu101** [comment]
We will need the base branch to be up to date with develop then change the base branch for Rabiul's PR

**Comment by SyedaAfrida** [comment]
This ticket is completed
