### ISSUE TITLE
Update death form for Frajaland

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#5514]
### Description
- updates Farajaland default death form
- flow > https://www.figma.com/file/NbLGi3Y4hLVFhKCyui0cEH/Declaration%2FFarajaland%2FDeathv3?type=whiteboard&node-id=0%3A1&t=g4aSGI2vUhlqLHUw-1
- mange change is the informant page. which now includes the first to existing pages (Informant type and main point of contact)

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
https://www.figma.com/file/NbLGi3Y4hLVFhKCyui0cEH/Declaration%2FFarajaland%2FDeathv3?type=whiteboard&node-id=0%3A1&t=g4aSGI2vUhlqLHUw-1

### Dev tasks

- [x] Refactor death form into reusable functions in Farajaland - 2
- [ ] Ensure that the completed form submits into Gateway and is retrievable in review on download.  Perform a manual e2e test from notification to certification - 2

**Comment by SyedaAfrida** [comment]
This ticket is completed
