### ISSUE TITLE
Update Record audit contact summary item

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#5515]
### Description
- Updates contact number summary line item in Record Audit

### Currently it is:

**Informant**   {type} • {phoneNumber}

### Updated is:

**Contact** {phoneNumber}
                     {emailAddress}

or 

**Contact** {phoneNumber}

or 

**Contact** {emailAddress}
              
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/2a2fd3da-4dc4-4166-99ba-b9e1527bdf3b)

### Acceptance criteria

GIVEN a declaration is exist
WHEN the form is configured to capture phone number
THEN show the phone number

GIVEN a declaration is saved
WHEN the form is configured to capture email address
THEN show the email address

GIVEN a declaration is saved
WHEN the form is configured to capture phone number and email address
THEN show the phone number and email address

GIVEN a declaration is saved
WHEN no contact is entered
THEN 

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=7822%3A33590&t=XgfmCfJdY0LtS145-1

### Dev tasks

- [ ] Use a new content key for the "Contact" label, and order informant phone number and email appropriately

**Comment by euanmillar** [comment]
@jpye-finch will un block when the email informant tickets are made, note need type resolvers, fhir prop

**Comment by SyedaAfrida** [comment]
**Bug:**
1. When declaration is send with both email address and phone number, then only phone number is submitted though Email is mandatory field

https://www.loom.com/share/980229df04cf482c9cb572cfb60f2cd7?sid=850132b0-6c08-40a8-9908-d4c9e7b4d18a


2. In death declaration is send with only email address, email do not appear in record audit and review page but appears in email

https://github.com/opencrvs/opencrvs-core/assets/94350336/47b2d0e4-8afa-4997-babc-8bf9456937c7


https://github.com/opencrvs/opencrvs-core/assets/94350336/f610ee6b-abd2-4c49-a92b-ecacafc332e9

**Comment by SyedaAfrida** [comment]
**Bug:**
In marriage declaration, Email address not appearing in record audit and review page though appearing in view. This is happening when a record with only email is submitted or both phone number and email.


https://github.com/opencrvs/opencrvs-core/assets/94350336/810e937d-0ae9-467e-a977-1eb93edf72b2

**Comment by SyedaAfrida** [comment]
This ticket is tested

https://github.com/opencrvs/opencrvs-core/assets/94350336/8d386130-c754-40e0-a7a6-9e0cc5edfe31
