### ISSUE TITLE
Updates marriage form for Farajaland

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#5517]
### Description
- updates Farajaland default marriage form
- flow > https://www.figma.com/file/LbhDHe7yCMYVdhs2Kd0UuA/Declaration%2FFarajaland%2FMarriage?type=whiteboard&node-id=0%3A1&t=DxnIFChkTRfQ9Ofo-1

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
https://www.figma.com/file/LbhDHe7yCMYVdhs2Kd0UuA/Declaration%2FFarajaland%2FMarriage?type=whiteboard&node-id=0%3A1&t=DxnIFChkTRfQ9Ofo-1

### Dev tasks

- [x] Refactor marriage form into reusable functions in Farajaland - 2
- [ ] Ensure that the completed form submits into Gateway and is retrievable in review on download.  Perform a manual e2e test from notification to certification - 2

**Comment by SyedaAfrida** [comment]
This ticket is completed
