### ISSUE TITLE
Searching and downloading records is broken

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5523]
Herve has discovered a critical bug that seems to be reproducible also in core environments, including demo. 

This is most likely regression:
Login as a registrar here; https://register.farajaland.opencrvs.org/
Use search to get a list of records. Download a birth record
Record loads indefinitely

![image.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/9ea5cbf3-f7d5-47fa-9a20-6caa92f32718)

**Comment by SyedaAfrida** [comment]
This ticket is fixed

https://github.com/opencrvs/opencrvs-core/assets/94350336/3cee1c63-69c7-4ef1-aa0f-70e8ab8b17ee
