### ISSUE TITLE
Should not allow spaces in email fields like phone number fields

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5526]
**Bug description:**
Should not allow spaces in email fields like phone number fields

**Steps to reproduce:**
1. Login to national system admin
2. Try to create user with space in email
3. Go to settings
4. Try to edit email with spaces
5. Logout
6. Click Cant login
7. Try to reset password or user name reminder with spaces in email

**Actual result:**
Allows spaces in Email field

**Expected result:**
Should not allow spaces in email fields like phone number fields

**Screen recording:**
https://images.zenhubusercontent.com/91778759/e7448d80-d197-4ae1-94b2-1437122ec7da/should_not_allow_spaces_in_email_fields__1_.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
I could see in the recording that if you put in a space then it shows an error. That is the expected result isn't it?

**Comment by SyedaAfrida** [comment]
@Zangetsu101 In settings when changing phone number, we don't allow entering space. In can't login and team, even if we enter space user can continue to the next page. But in email we show error message when there is a space. This is functionally correct but email fields should work similar to phone numbers. Either do not allow entering space or even if there is a space, save it without a space a and allow user to continue to next page. Because it is sometimes hard to detect single space where the error message is saying invalid email address. I am changing the label to improvement for this ticket.

**Comment by SyedaAfrida** [comment]
Not a bug
