### ISSUE TITLE
Deprecate contentful export and associatedd files

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5543]
- [x] Write a script that takes in available languages as input and checks the client, login & notification json file to make sure all the messages are available for each language. Show the errors in a understandable way like how it is in the extract:translations now - 2
- [x] Write a github action that calls this script on every PR - 1
- [x] We need to copy the extract-translations.ts amends to the login app. They were only applied to the client app - 1

**Comment by naftis** [comment]
Handled in https://github.com/opencrvs/opencrvs-farajaland/pull/604

**Comment by euanmillar** [comment]
2 things are outstanding:

1. As discussed here: https://github.com/opencrvs/opencrvs-core/pull/4934, we need something in a country config PR github action that checks all available languages to see if a translation has been added for ALL languages.

2. We need to copy the extract-translations.ts amends to the login app.  They were only applied to the client app
