### ISSUE TITLE
Form field names should be unique so they can be added to any section

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5549]
We dont know how a country will arrange form sections, so the following enums are deprecated in core:

export enum BirthSection {
  Registration = 'registration',
  Child = 'child',
  Mother = 'mother',
  Father = 'father',
  Informant = 'informant',
  Documents = 'documents',
  Preview = 'preview'
}

export enum DeathSection {
  Registration = 'registration',
  Deceased = 'deceased',
  Event = 'deathEvent',
  Informant = 'informant',
  DeathDocuments = 'documents',
  Preview = 'preview'
}

export enum MarriageSection {
  Registration = 'registration',
  Groom = 'groom',
  Bride = 'bride',
  Event = 'marriageEvent',
  WitnessOne = 'witnessOne',
  WitnessTwo = 'witnessTwo',
  Documents = 'documents',
  Preview = 'preview'
}

The following are the only guaranteed sections:  'registration', 'documents', 'preview'

- [ ] Use names like mothersNationalId, mothersOccupation, mothersDob and adjust any mapping function that uses the field name directly if you need to if this causes a problem. - 2
- [ ] Deprecate any function that requires a section constant to exist in Verify Collector and Verify Correction - 2

**Comment by Zangetsu101** [comment]
@euanmillar Changing this now might break quite a few places so we decided not to do this for now. As the field names could be anything, all the places in client where we are using the data from draft(apart from the form) will need to be refactored to use `draftToGql` perhaps as that would give us a concrete schema to work with

**Comment by euanmillar** [comment]
@Zangetsu101 I understand.  I can also see functionality like this being broken: https://github.com/opencrvs/opencrvs-core/pull/5646. The problem is, where field names must be set to a certain value in order for other functionality to work, then we must then have these required field names typed in Farajaland where appropriate.  Can you list other field names such as registrationPhone that MUST NOT CHANGE?  Then we can create a type

**Comment by euanmillar** [comment]
Lets tidy this up in a future release

**Comment by euanmillar** [comment]
Wondering if this can be closed if it will be addressed in #7052

**Comment by Zangetsu101** [comment]
@rikukissa we've considered this in events v2 right?

**Comment by rikukissa** [comment]
Yea, this requirement won't be relevant anymore in Events v2
