### ISSUE TITLE
Diff Cameroon emergency backup script and Farajaland

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5553]
Because Riku discovered a bug in the Cameroon backup related to Minio

- [x] Diff Cameroon emergency backup script and Farajaland and fix in 1.3 - 1
- [ ] Provide a hotfix for 1.2 for Madagascar (assign to euan)

**Comment by euanmillar** [comment]
Once fixed, @euanmillar will do the hotfix

**Comment by naftis** [comment]
About the hotfix, do we need to provide it, if in 1.2 the migrations run after backup restore?

**Comment by naftis** [comment]
Handled here: https://github.com/opencrvs/opencrvs-farajaland/pull/628
