### ISSUE TITLE
Email: Capture email in declaration form

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#5570]
### Description
- lets a country add email as a form of contact in the declaration form
- allows a country choose email as the method of sending informant notifications (sms or email) 
- note a country can choose to capture phone and email. but must which will be used to send notifications 
- error validations "Please enter a valid email address"

### Acceptance criteria

GIVEN I am a developer
WHEN configuring the form
THEN I want to add email field to the form

GIVEN a user enters an email
WHEN the email is not valid
THEN show the error message "Please enter a valid email address"

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=16530%3A124575&mode=design&t=MZ3Te9TwIcq0cPs7-1

### Dev tasks

- [ ] Add the email field to the forms, client queries and mutations and add use email validator that exists.  Backend is addressed in ticket #5512

**Comment by SyedaAfrida** [comment]
This ticket is fixed
![s](https://github.com/opencrvs/opencrvs-core/assets/94350336/f7e5f70b-638a-47b7-99d9-62b762e84460)
