### ISSUE TITLE
Email: Send email notifications to informant

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#5572]
### Description
- adds email templates for sending notifications to informant
- sends email if email set as method to notify
- developer/country can choose what emails to send
- version of each email template for each event

**Notification types:**
-  emailNotifcation1 > Complete your declaration  (sent incomplete)
-  emailNotifcation2 > Declaration in review
-  emailNotifcation3 > Declaration requires updates
-  emailNotifcation4 > Declaration registered

### Acceptance criteria

GIVEN a FA sends an declaration incomplete to an office
WHEN email set as method and emailNotifcation1 is enabled 
THEN send the email! 

GIVEN a FA sends a declaration complete to an office
OR GIVEN a RA sends a declaration for approval to an office
WHEN email set as method and emailNotifcation2 is enabled 
THEN send the email! 

GIVEN a RA or REG sends a declaration for updates
WHEN email set as method and emailNotifcation3 is enabled 
THEN send the email! 

GIVEN a Reg registers a declaration
WHEN email set as method and emailNotifcation4 is enabled 
THEN send the email! 

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=17187%3A124112&mode=design&t=MZ3Te9TwIcq0cPs7-1

### Dev tasks

- [x] Create email templates for all messages - use a handlebar for event type - 2
- [x] Create a new notification method constant like INFORMANT_NOTIFICATION_DELIVERY_METHOD, then send notifications to users by email instead of SMS based on the value of that prop. That would allow the possibility for both USER and INFORMANT methods to be individually configurable.
- [x] Make informant email or sms field required based on that constant

**Comment by euanmillar** [comment]
@jpye-finch I think we need an improvement ticket to change the design of the notification settings UI in sys admin, because the copy would be different between SMS and email. I think the solution may be not to show copy but a description of the intention of the message there

**Comment by jpye-finch** [comment]
@euanmillar yes was just thinking that this morning also

**Comment by SyedaAfrida** [comment]
**Bug:**
Declaration sent for review and Declaration rejected is not working for both birth and death event. Email is not send

**Comment by SyedaAfrida** [comment]
Bug:
1. Declaration rejected is not working for both birth and death event.
2.  in Complete your declaration  (sent incomplete)
![b1](https://github.com/opencrvs/opencrvs-core/assets/94350336/4a284f93-8ba3-4816-8612-49bf025dd566)
![d1](https://github.com/opencrvs/opencrvs-core/assets/94350336/a84cf98e-44b7-47ac-accf-227decb1aba7)


3. in Declaration in review
![d2](https://github.com/opencrvs/opencrvs-core/assets/94350336/e2d766b5-2939-4d25-9f48-8565e024e69d)
![b2](https://github.com/opencrvs/opencrvs-core/assets/94350336/6ebc5253-42eb-4469-af7a-4196b4133a6c)

**Comment by SyedaAfrida** [comment]
This ticket is fixed
![d4](https://github.com/opencrvs/opencrvs-core/assets/94350336/f098bd84-46f0-4196-bde3-e28f704a40cc)
![b4](https://github.com/opencrvs/opencrvs-core/assets/94350336/dc73ec7d-1eda-4587-9cbd-7d044b77b339)
![d3](https://github.com/opencrvs/opencrvs-core/assets/94350336/96313180-2d35-4ad4-873e-de4d7c0c7262)
![b3](https://github.com/opencrvs/opencrvs-core/assets/94350336/c047eec8-f4fd-47ab-897d-29360c3e40d9)
![d2](https://github.com/opencrvs/opencrvs-core/assets/94350336/fe7280d9-fa1a-4304-925e-59f7019aa2f1)
![b2](https://github.com/opencrvs/opencrvs-core/assets/94350336/ef1bc259-e7bf-4cd5-b1ee-b4cf38957f7d)
![d1](https://github.com/opencrvs/opencrvs-core/assets/94350336/04644f1c-aa14-4de6-bbdd-34c098d94e80)
![b1](https://github.com/opencrvs/opencrvs-core/assets/94350336/6e40dbf0-2c29-4c6a-a930-192a2b18c231)
