### ISSUE TITLE
Registrar login for the first time (no data stored locally)

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5582]
**Description**

We need to write a performance test that loads ALL API, GraphQL and Asset network requests that are called when a Registrar logs in and completes when the final GraphQL request completes.

Refer to this video:

![opencrvs-load.gif](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/2739b55c-26bb-4eec-b40e-4f5271398459)

**Acceptance Criteria**

User type: Registrar

Load is within 20 seconds (page renders to spinner stops in the In Progress WQ)

10 records available across all the WorkQueues

Concurrent requests up to 3 requests/sec

Network must be throttled to mimic 3G connectivity: 3 Mbps when running the test

**Dev Tasks**

- [x] Entirely remove the "integration" package in core.  We now use this separate repo to perform performance tests: https://github.com/opencrvs/performance-tests/tree/master.
- [x] Upgrade https://github.com/opencrvs/performance-tests to use Typescript: https://github.com/grafana/k6-template-typescript
- [x] Write a "login" performance test that loads ALL API, GraphQL and Asset network requests for a Registrar
- [ ] Euan to run the test in August

**Comment by rikukissa** [comment]
Test documented here with result from Farajaland QA
https://github.com/opencrvs/performance-tests/tree/master/scenarios/registrar-login
