### ISSUE TITLE
Retrieve search results based on BRN query

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5583]
**Description**

We need to write a performance test that calls the search API

Refer to this video:

![search.gif](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/1b358044-f263-4bb6-a518-5a97f4b6d1fb)

**Acceptance Criteria**

User type: Registrar

Load is within 3 seconds

Concurrent requests up to 3 requests/sec

Network must be throttled to mimic 3G connectivity: 3 Mbps when running the test

**Dev Tasks**

- [x] Write a "search" performance test in https://github.com/opencrvs/performance-tests that calls the search API using a BRN
- [ ] Euan to run the test in August

**Comment by rikukissa** [comment]
Test implemented here: https://github.com/opencrvs/performance-tests/tree/master/scenarios/1500-records-in-database#search-by-tracking-id

Read comment https://github.com/opencrvs/opencrvs-core/issues/5586#issuecomment-1645246225 to understand the changes in implementation
