### ISSUE TITLE
Send a birth declaration for approval with 3 x 0.4MB attachments, including duplicate check

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5585]
**Description**

We need to make a separate declaration test "declaration-with-attachments"  that does the same but this time with 3 x 0.4MB image attachments

**Acceptance Criteria**

User type: Registration Agent

Transaction time within 30 seconds

Concurrent requests up to 3 requests/sec

Total attachements = 3 (each original image size of 4MB - each image should compress to 0.4MB)

Network must be throttled to mimic 3G connectivity: 3 Mbps when running the test

**Dev Tasks**

- [ ] Duplicate the declaration.js performance test so that the payload of "declaration-with-attachments" contains 3 x 0.4MB attachments
- [ ] Euan to run the test in August

**Comment by rikukissa** [comment]
Test implemented here: https://github.com/opencrvs/performance-tests/tree/master/scenarios/fresh-installation#creating-a-declaration

Read comment https://github.com/opencrvs/opencrvs-core/issues/5586#issuecomment-1645246225 to understand the changes in implementation.
