### ISSUE TITLE
When exact date of birth known is clicked, clear DOB field in form and show "Exact date of birth unknown" for DOB in review page even if there is data provided

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5598]
**Bug description:**
When exact date of birth known is clicked, clear DOB field in form and show "Exact date of birth unknown" for DOB in review page even if there is data provided
**Steps to reproduce:**
1. Login from FA/ RA/ Registrar
2. Declare a birth/ death/ marriage event
3. Go to Child/ Mother/ Father/ Informant/ Deceased/ Bride/ Groom details page
4. Fill up Date of birth field
5. Click Exact date of birth unknown
6. Enter Age
7. Go to review page and observe DOB and Age fields
8. Again Click change
9. Remove age field
10. Click Back to review and observe  DOB and Age fields

**Actual result:**
When Date of birth is provided and also clicked Exact date of birth unknown, both DOB and Age field is showing in review page

**Expected result:**
When Date of birth is provided and also when exact date of birth known is clicked-
1) Clear the data in date of birth
2) In review page show-
Date of birth   Exact date unknown     Change link
3) Show Age field in review

![d](https://github.com/opencrvs/opencrvs-core/assets/94350336/5d10d545-f2fa-454f-88fe-96996203a5db)

**Screen recording:**

https://images.zenhubusercontent.com/91778759/663c9867-c6ad-46ed-bcd4-fceb564c3f92/hide_dob_field_even_if_there_is_data_provided__when_exact_date_of_birth_known_is_clicked___trim.mp4
**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
let's hide the dob field if "exact data of birth unknown" true

**Comment by SyedaAfrida** [comment]
This bug is fixed

https://github.com/opencrvs/opencrvs-core/assets/94350336/73df2402-278f-455e-b15b-86995563bb36
