### ISSUE TITLE
Enforce minimum TLS 1.2 in Traefik config

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5606]
The Deprecated TLS Detection vulnerability refers to a security weakness found in outdated versions of TLS (Transport Layer Security) and SSL (Secure Sockets Layer) protocols, specifically TLS 1.1 and SSLv3. This vulnerability puts sensitive data at risk of interception by hackers. It is crucial to update to newer, more secure protocols to protect against potential attacks.

https://doc.traefik.io/traefik/https/tls/

- [ ] Amend Traefik config to minVersion: VersionTLS12

**Comment by naftis** [comment]
We need to create a Traefik config file to update this configuration. There isn't a no-config support for this:
https://github.com/traefik/traefik/issues/5507

Traefik 2.9 on the other hand has TLS 1.2 by default if I understand this PR correctly: https://github.com/traefik/traefik/pull/8951

Lets upgrade to 2.9 instead? @Zangetsu101

**Comment by Zangetsu101** [comment]
Sounds good to me!
