### ISSUE TITLE
Remove unsafe-inline from the CSP

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5607]

**Comment by euanmillar** [comment]
@naftis I still see unsafe-inline in the CSP despite this fix. https://github.com/opencrvs/opencrvs-core/pull/5627  Do you know why that didnt cause an error?  Is it OK to remove it please?

**Comment by naftis** [comment]
@euanmillar It was removed from `script-src` in the PR. That is the problematic one. There is still unsafe-inline for `style-src` though. After brief Googling, it shouldn't be needed either anymore, but the CSP evaluator doesn't consider it as an issue
