### ISSUE TITLE
Dialog alert to prompt password roatation

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#5615]
### Description
- Dialog prompt if password change is required
- or is it our first App notification

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=17290%3A124116&mode=design&t=mUqEY7u4RmAhLUuo-1

![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/525273cd-ac83-463d-9f7d-7f8a4f72a10e)

### Dev tasks

- [ ] Task 1

**Comment by euanmillar** [comment]
decided that this actually does not improve security
