### ISSUE TITLE
Allow custom fonts for certificate handlebars

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#5631]
### Description
- countries want to use different fonts on the certificate
- any fonts can be used for labels and other static text. by 'outline text' before export
- this ticket is to support different fonts for dynamic text ie {{handlebars}} 

**Solution**:
1. Country can add font files to their country resource package. 
2. Country designs and applies fonts and styles to the certificate. 
3. Certificate is exported
4. If the certificate is correctly designed and exported the fonts will be applied. 

### Acceptance criteria

GIVEN I have added a font to my country resource package. ie Comic Sans Italic
WHEN I use Comic Sans Italic in my certificate template svg
THEN the text correctly renders as Comic Sans Italic

### Dev tasks

- [ ] Task 1

**Comment by euanmillar** [comment]
This is now possible in 1.3.0
