### ISSUE TITLE
In Duplicate review page rename "Registered at" to "Declaration captured at" and "Registered by" to "Declaration captured by"

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5659]
**Bug description:**
In Duplicate review page rename "Registered at" to "Declaration captured at" and "Registered by" to "Declaration captured by"

**Steps to reproduce:**
1. Login to FA
2. Declare a birth/ death record
3. Logout
4. Login to Registrar
5. Declare a birth /death record with same information
6. Download>assign>review that duplicate record
7. Click tracking id and observe

**Actual result:**
In Declaration details last two columns are Registered at (showing Ibombo though one record is not registered yet) and Registered by (one record showing field agent's name)

**Expected result:**
In Duplicate review page rename "Registered at" to "Declaration captured at" and "Registered by" to "Declaration captured by"

**Screen recording:**
![image (6).png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/7d98cebd-ded5-4825-8dd6-678eec0b2a56)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
If the declaration is not registered yet, let's keep those fields blank

**Comment by SyedaAfrida** [comment]
This bug is not properly fixed. the 1st column is not updating correctly
![duplicate](https://github.com/opencrvs/opencrvs-core/assets/94350336/1da40040-444a-4bc0-a438-78aa98b9867d)

**Comment by SyedaAfrida** [comment]
This bug is fixed
![f](https://github.com/opencrvs/opencrvs-core/assets/94350336/2a62cdad-40d8-4057-b8e0-782d5edbd969)
