### ISSUE TITLE
Marriage: Correct a Marriage record

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#5671]
### Description
- adds support for correcting a marriage record
- similar experience as correcting a birth or death
- IF bride and groom are requesting. Then both ID's should be checked??

### Acceptance criteria

GIVEN a marriage record has the status (Regsitrered, Certified, Issued)
WHEN on the Record Audit page
THEN I can click Correct record

GIVEN I click Correct Record
WHEN the Correction Requester page 
THEN I can choose from 
`Informant ([Relationship to couple]), Bride & Groom, Bride, Groom, Court, Someone else`

WHEN on the review page 
THEN same experience as birth and death

WHEN on the Upload supporting documents
THEN same as birth and death

WHEN on the Reason for correction
THEN same as birth and death

WHEN on the Correction summary
THEN same as birth and death

--

Record Audit

WHEN on the Record Audit for a marriage
THEN the history line items would behave the same as birth and death

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=17723%3A132009&mode=design&t=vl7DshSwvt1jqRfj-1

### Tasks
- [ ]

**Comment by euanmillar** [comment]
@jpye-finch @eduffus I suggest removing the option "Bride & Groom" to simplify the ID Check, Correction & Audit flow. Lets keep this to individuals. Bride, Groom as separate radio buttons.  

The code is then far easier to maintain and we dont have to store more individual details in the FHIR Task such as links to multiple FHIR Patients.  We can then reduce the size of effort

**Comment by euanmillar** [comment]
Custom events will enable for all future countries #7052
