### ISSUE TITLE
Email does not appear for any incomplete declaration if informant's/child's/deceased name is not provided properly

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5744]
**Bug description:**
Email does not appear for any incomplete declaration if informant's/child's/deceased name is not provided properly

**Steps to reproduce:**
1. Login to FA
2. Create an incomplete birth/ death declaration
3. Provide email address only and submit

**Actual result:**
Email do not appear for in progress declaration if
1) Informant's name is missing

Email do not appear for rejected declaration if
1) Informant's / child's name is missing in birth declaration
2) Informant's / deceased's name is missing in death declaration

**Expected result:**
Needs discussion if email should be provided if informant's/child's/deceased name is missing as these fields are requiredin email template

https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=15567-109522&mode=design&t=FcRSd0cljdOTRNh4-0

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
@jpye-finch

**Comment by jpye-finch** [comment]
IMO. We should support sending of emails even is the dynamic data is missing

So for the In Progress Email Notification: 

"Hello {{InformantFirstnameLastname}},"

As the {{InformantFirstnameLastname}} is empty. The email would be. 

"Hello, "

**Comment by tareq89** [comment]
is this screen okay? I meant the text here is not user friendly!
![Image](https://github.com/opencrvs/opencrvs-core/assets/4245521/e6fe83dc-3b4f-4ad3-a717-8c8c8871892c)

**Comment by tareq89** [comment]
Also, this screen:

![Image](https://github.com/opencrvs/opencrvs-core/assets/4245521/052229ef-5121-4e1e-b90d-2acff24907de)

**Comment by tareq89** [comment]
The log is correctly printing in qa logs even when informant name is null. But slack does not receive any email in email channel.

![Image](https://github.com/opencrvs/opencrvs-core/assets/4245521/e569bbc8-ee7e-446b-b4f1-e15e0c35caaf)


![Image](https://github.com/opencrvs/opencrvs-core/assets/4245521/5bb22c10-733c-4af5-853d-f6905edb8380)

**Comment by tiri39** [comment]
This ticket is fixed.

https://github.com/opencrvs/opencrvs-core/assets/113257751/fe271bac-1746-4c97-a927-dca42a07e3e9
