### ISSUE TITLE
Kibana logging

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#5746]
logging wasn't working after removing the port mapping from logstash service so I added that back in this commit: https://github.com/opencrvs/opencrvs-farajaland/commit/527677784bb3de336aa58ca55e27451fde5aac04. But this exposes the port to the outside world. This could be a potential solution: https://github.com/docker/for-linux/issues/690#issuecomment-1666961476

- [ ] Try out the solution in staging

**Comment by kayumuzzaman** [comment]
deployed the changes to staging and checked the open ports, but didn't found  port 12201 as open. checked with nmap and others online tool: 

with nmap:

![nmap](https://github.com/opencrvs/opencrvs-core/assets/46846503/42b2208b-8b48-4559-9141-24a28e984fbc)

with a tool: 

![port-12201](https://github.com/opencrvs/opencrvs-core/assets/46846503/689531b3-4f89-4b91-b23b-96903024e64e)
