### ISSUE TITLE
Remove Save & exit button from correction record review pages

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5764]
**Bug description:**
Remove Save & exit button from correction record review pages

**Steps to reproduce:**
1. Login to Registrar
2. Click Ready to print
3. Click Download> Assign> Correct record in any birth/ death record
4. Go to review page
5. Click any change and observe

**Actual result:**
Save & exit button exists in correction record review pages

**Expected result:**
Remove Save & exit button from correction record review pages
Should only show Exit button

**Screen recording:**

https://images.zenhubusercontent.com/91778759/dec45f51-6752-4ee4-a7fe-698ed2dac35f/remove_save___exit_button_from_correction_record_review_pages.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by euanmillar** [comment]
@jpye-finch I think that the copy should change in the modal for correct record as it suggests to the user there is another way they can save their changes.  With this functionality it isnt possible to save a draft in correct record, so I think that the copy should reflect that there is no way back for this user when correcting a record.  

Modal title could be: Confirm exit
Modal text could be: Are you sure you want to exit?  Any corrections you have made will not be saved.

![Screenshot 2023-08-15 at 11.25.35.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/cb576830-679e-49d4-9a50-923690e3dfcd)

**Comment by jpye-finch** [comment]
Yes agree. Would suggest a different title. 

Title: Exit correct record?

**Comment by euanmillar** [comment]
Perfect. I have made appropriate comments on the ticket

**Comment by SyedaAfrida** [comment]
This bug is fixed

https://github.com/opencrvs/opencrvs-core/assets/94350336/c427bb67-cf31-49dd-9771-b750c536ae34
