### ISSUE TITLE
When RA tries to print a death certificate, collect fee page is not appearing

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5767]
**Bug description:**
When RA tries to print a death certificate, collect fee page is not appearing

**Steps to reproduce:**
1. Login to RA
2. Go to ready to print
3. Click Download> Assign> Print any death declaration
4. Select Informant and Continue
5. Observe till certificate preview page

**Actual result:**
When RA tries to print a death certificate, collect fee page is not appearing

**Expected result:**
collect fee page should appear for all users

**Screen recording:**
https://images.zenhubusercontent.com/91778759/b4f1dfde-c9af-4857-a72b-c1f25dd328af/collection_fee_page_not_appearing_in_ra_for_death_declarartion.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Nil20** [comment]
[collectPayment.webm](https://github.com/opencrvs/opencrvs-core/assets/32668488/af870fc0-89f8-4861-ad51-efffbab8bd3d)


This bug wasn't reproducible

**Comment by SyedaAfrida** [comment]
This ticket can be closed
