### ISSUE TITLE
Cameroon improvements into core

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5793]
Cameroon have implemented a lot of changes in this spreadsheet.

The commits in this spreadsheet need cherry picked into core and adapted if necessary:

https://docs.google.com/spreadsheets/d/1CscMMY7_KEQT7agjfzF9ERtrWPYbEYS6QJ1g9PqvYns/edit#gid=656002201

- [x] Add separate validator dateNotPastLimit
- [x] Login masking fixes
- [x] Potentially fixes for 2ndary language
- [x] Fixes for detecting an alive ES connection
- [x] Improved status endpoint
- [x] Add a past date limit for child's birthdate
- [x] use process env DOMAIN as sentry environment
- [x] add sourcemaps to build
- [ ] Handle empty section data in record audit
- [x] update certificate create/update endpoint type so that it's possible to use the endpoint also for creating new certificates
- [ ] Add "organisation" information for users - Blocked for now
- [x] Add support for defaulting location level 3 of field agent's in address inputs

**Comment by tahmidrahman-dsi** [comment]
@rikukissa @Zangetsu101 I am not sure if the task "Handle empty section data in record audit" is still relevant, as we do not use custom datasets now and seem to update address-related code. So, I haven't cherry-picked this commit in https://github.com/opencrvs/opencrvs-core/pull/6054.
