### ISSUE TITLE
Introduce longitudinal record searching based on NID

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5801]
A eCRVS system needs a way to longitudinally link events together so you can match children to marriages to deaths to adoptions divorces ... 

We can either use Elastic search or create a utility function in the search microservice which will link records using Fellegi-Sunter.

The DCI response is hoping for something like this:

```
"birthplace": {
 },
"deathplace": {
 },
isAlive: true / false,
isMarried: true / false
wifePersonId: 
```

I think we should respond like this:

```
"birthplace": {
 },
"deathplace": {
 },
isAlive: {
 result: true / false,
 finalWeights: 8.9 // e.g. Elastic Explain API score / Fellegi-Sunter likelyhood
},
isMarried:{
 result: true / false,
 finalWeights: 8.9 // e.g. Elastic Explain API score /  Fellegi-Sunter likelyhood
},
wifePersonId: {
 result: uuid for FHIR Person ?,
 finalWeights: 8.9 // e.g. Elastic Explain API score /  Fellegi-Sunter likelyhood
}
```

Connecting systems need to understand that the response is never 100% accurate and we should suggest that we return either the finalWeights ration, percentage or threshold of likelyhood that the matching details/result is correct.

https://en.wikipedia.org/wiki/Record_linkage

I think that the steps may be ... 

1. Edit data generator according to the comments below to create large amounts of test data where linkages can be found, saving a log file for all linkages created. We use the logfile in quality assurance to determine how successful our linkage searching algorithm has been.
2. Option A: Use Elastic / Felligi Sunter to connect records at the point of search or registration ... We could possibly store linkages of  records together in the same way we do with MOSIP birth and death.  So records are immutable and via connection we determine how likely it is that a birth person is deceased.  We should save the finalWeights for the matching so that external systems can decide how trustworthy the match is. Do we update the FHIR Patient deceased / married prop or not based on the finalWeights? Thats an open question.  We could decide not to store linkages to avoid the problem of mismatching and complex migrations.
2. Option B: When searching using the API get Elasticsearch to search for all records that match the search params coming from the search API using Elastic's Explain API, return Explain API scores without storing the linkages.
3. Return results with the finalWeights

to support countries where dates of birth are unknown, when searching by date of birth, it may be useful to always additionally search for records set to the 1st of January that year where ageOfIndividualInYears was supplied https://github.com/opencrvs/opencrvs-core/pull/5676

---

Dev tasks:
- [x] Look into whether we can leverage the existing record search to search longitudinal records with National ID only. Create dev tasks if core changes are needed to return/search for all required data. - 2
- [x] Return the matching records, if a person with records with the NID is being found. Also merge the data into a `Person` -record explained here https://digital-convergence-initiative-d.gitbook.io/dci-standards-1/standards/1.-crvs/6.5-data-standards/6.5.1-data-elements#do.01-person - 2
- [x] Go through the items in Pyrys comment in 14. Sep, and go through our API responses if we are returning all the correct data. Amend if not. - 1

**Comment by euanmillar** [comment]
I asked ChatGPT to give it a go ...

```
interface Record {
  id: number;
  name: string;
  age: number;
  // Add other attributes here...
}

interface FieldWeights {
  name: number;
  age: number;
  // Define weights for other fields...
}

function calculateSimilarity(record1: Record, record2: Record, weights: FieldWeights): number {
  const nameSimilarity = record1.name === record2.name ? weights.name : 0;
  const ageSimilarity = Math.abs(record1.age - record2.age) < 5 ? weights.age : 0;
  // Calculate similarities for other fields...

  // Calculate total similarity score
  const totalSimilarity = nameSimilarity + ageSimilarity;
  return totalSimilarity;
}

function expectationMaximization(records1: Record[], records2: Record[], initialWeights: FieldWeights, numIterations: number): FieldWeights {
  let currentWeights = { ...initialWeights };

  for (let iteration = 0; iteration < numIterations; iteration++) {
    const expectedWeights: FieldWeights = { ...currentWeights };
    const counts: FieldWeights = { ...currentWeights };

    for (const record1 of records1) {
      for (const record2 of records2) {
        const similarity = calculateSimilarity(record1, record2, currentWeights);
        const weightSum = expectedWeights.name + expectedWeights.age; // Sum of all weights

        const weightRatio = {
          name: expectedWeights.name / weightSum,
          age: expectedWeights.age / weightSum,
          // Calculate ratios for other fields...
        };

        counts.name += similarity * weightRatio.name;
        counts.age += similarity * weightRatio.age;
        // Update counts for other fields...
      }
    }

    expectedWeights.name = counts.name / (records1.length * records2.length);
    expectedWeights.age = counts.age / (records1.length * records2.length);
    // Calculate updated weights for other fields...

    currentWeights = expectedWeights;
  }

  return currentWeights;
}

// Example usage
const records1: Record[] = [
  { id: 1, name: "John Doe", age: 30 },
  // Add more records...
];

const records2: Record[] = [
  { id: 101, name: "Jane Smith", age: 28 },
  // Add more records...
];

const initialWeights: FieldWeights = {
  name: 0.5,
  age: 0.5,
  // Define initial weights for other fields...
};

const numIterations = 10;
const finalWeights = expectationMaximization(records1, records2, initialWeights, numIterations);
console.log("Final weights:", finalWeights);
```

I think we may find functionality in Elasticsearch which does the above

**Comment by euanmillar** [comment]
In order to decide the weight ratios, we need to perform tests based on large amounts of data generated by the data generator.  We need to edit the data generator to create real linkages between people occasionally when registering a marriage, rather than create a new bride or groom, select 2 children from the database and use that data for the couple.  Do the same for deaths etc.  Data generator should output the linkages it makes to a logfile, so that when we are testing the search, we can compare the results with the logfile to determine how successful the search was. in this way we can adjust the weights accordingly.  An interesting paper on how Fellegi Sunter weights were applied to newborns ... https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9336505/

**Comment by euanmillar** [comment]
Perhaps another way to approach this task is to use Fellegi Sunter searching on point of registration.  For a birth, we should register as usual, but then search through all records to find a spouse & child that is likely the mother or father.  Then we can add identifiers linking the records. Likewise do this at point of death even if MOSIP is not integrated.

**Comment by naftis** [comment]
Fellegi-Sunter is a machine-learning algorithm. We need to think if it's realistic to maintain a Python project of this kind. I feel like if any machine learning-related stuff is implemented, it's worth implementing it with proper tools like Python and its ML libraries. Maintaining a more structured DB like an SQL-based one could be needed as well.

This is a solid record-linking package written in Python
https://moj-analytical-services.github.io/splink/ 

I feel that given our team's current knowledge on a subject like this we should explore simpler options or externalize the record linking altogether to the system that wants to connect with OpenCRVS

**Comment by euanmillar** [comment]
I would love to use Splink for this if that is possible.  Noticing that others are also investigating it: https://www.gov.uk/government/publications/joined-up-data-in-government-the-future-of-data-linking-methods/splink-mojs-open-source-library-for-probabilistic-record-linkage-at-scale

**Comment by euanmillar** [comment]
@naftis I [investigated](https://moj-analytical-services.github.io/splink/topic_guides/backends/backends.html) the Splink tool a bit ... I think technically we would need:

1. A docker image running PySpark, Splink, Apache Spark & maybe [Livy](https://livy.apache.org/) for REST API access?

2. A new microservice package to handle registration handlers and scheduled tasks

On registration we save the minimal data we will use for matching into Apache Spark. such as: 

Splink [**unique_id**](https://moj-analytical-services.github.io/splink/demos/tutorials/01_Prerequisites.html) would be the FHIR Patient ID for child, deceased, mother, father, bride, groom, informant (spouse only).
Other columns are: first name (no middle name), last name, dates of birth, email addresses, phone numbers, BRN/DRN/MRN, NID ... any others recommended to us by an external data scientist.

3. A scheduled task links records together with weights and stores the linked [FHIR IDs into Patient records](https://github.com/opencrvs/opencrvs-core/blob/e34fe4b99616817d66402d4933172735515d4a76/packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts#L812) as we do with MOSIP integration.  This is a scheduled task as it can take a long time on large data sets

**Comment by euanmillar** [comment]
A notable point that @naftis made was: doing this on search rather than on registration, reduces the risk associated with having to manage complex migrations especially if something is mismatched.

**Comment by naftis** [comment]
Non-NID search is not in our immediate scope, so I updated the development tasks to implement only a NID-based longitudinal record searching.

**Comment by naftis** [comment]
Updated as far as we could, and functionally we are only missing searching births by NID. That is tracked here: https://github.com/opencrvs/opencrvs-core/issues/5858 

I'm blocking this as we don't fully know how to answer from the API, before the Gitbook has been updated to match the DCI OpenAPI types.
