### ISSUE TITLE
Research and potentially implement integration access to use OAuth

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5803]
Our existing integration is created by a National System Admin login, then never ending client_id and client_secret which can be exchanged for a 10 minute long JWT.

We made this bespoke without following any OAuth compliance standards: https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow

In the DCI Apis they have a signature header which I assume needs to store the tokens to access the system, but surely we should be using an authorization header.  

We need to understand the OAUth specification and determine if we need to make any changes.  We need to make proposals about how authentication should work strategically and then implement them

**Comment by naftis** [comment]
Closing this one in favour of: https://github.com/opencrvs/opencrvs-core/issues/5830
