### ISSUE TITLE
Develop synchronous search API for the standard in the mediator

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5804]
- [x] Create a synchronous `/registry/sync/search`. Look into the [child allowance scheme](https://digital-convergence-initiative-d.gitbook.io/dci-standards-1/standards/1.-crvs/1.2-process/6.4.5-process-enrollment-in-child-allowance-scheme) and at first we can try and implement that flow - 3
- [x] Handle responding [with death declarations](https://digital-convergence-initiative-d.gitbook.io/dci-standards-1/standards/1.-crvs/1.2-process/6.4.3-process-ceasing-allowance-upon-death-notification) as currently only birth declarations are supported - 1
- [x] Check and implement the support for "6.4.2 Process: Enrollment in the old age allowance scheme"- 0.5
- [x] Check and implement the support for "6.4.3 Process: Ceasing allowance upon death notification"
- [x] Get the record ids from record search, but get the registration from fetchRegistration. This allows us to return values that aren't saved into ElasticSearch (like the place of death below) - 1
- [x] Check and implement the support for "6.4.4 Process: Enrollment in widow allowance scheme"
- [x] Check and implement the support for "6.4.6 Process: Proactive enrollment in child allowance scheme"
- [x] Allow searching with `id` which comes from the QR code. We need to figure out which identifier_type is this, we already allow searching by "BRN" but we can treat this as "OPENCRVS_RECORD_ID" at first - 0.5
- [x] Handle errors according to [the API specs](https://spdci.github.io/standards/release/html/registry_core_api_v1_0.0.0.html#tag/Sync/operation/post_reg_sync_search) - 1

Blocked stuff:
- [ ] (blocked! [The GitBook](https://digital-convergence-initiative-d.gitbook.io/dci-standards-1/standards/1.-crvs/1.2-process/6.4.4-process-enrollment-in-widow-allowance-scheme) needs updating: see example 4 response) Return divorce data, with "date_of_divorce", "marital_status", .. etc.
- [ ] Add "date_of_marriage", the information about the searched person, and information of the spouse to a Marriage result - 1
- [ ] Allow searching with: "the applicant's complete name, date of birth, contact number, mother's name, and other relevant parameters can be used to search for their records" - 1

**Comment by naftis** [comment]
Blocking before we implement longitudinal search with NID, to better understand what the outcoming response would be.

**Comment by naftis** [comment]
Blocked stuff:
- [ ] (blocked! [The GitBook](https://digital-convergence-initiative-d.gitbook.io/dci-standards-1/standards/1.-crvs/1.2-process/6.4.4-process-enrollment-in-widow-allowance-scheme) needs updating: see example 4 response) Return divorce data, with "date_of_divorce", "marital_status", .. etc.
- [ ] Add "date_of_marriage", the information about the searched person, and information of the spouse to a Marriage result - 1
- [ ] Allow searching with: "the applicant's complete name, date of birth, contact number, mother's name, and other relevant parameters can be used to search for their records" - 1

Let's review if these ones are still needed. Unblocking this as the pull request is already merged.
