### ISSUE TITLE
Exact Date of Birth Unknown option not appearing in death and marriage form

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5812]
**Bug description:**
Exact Date of Birth Unknown option not appearing in death and marriage form

**Steps to reproduce:**
1. Login to FA/ RA/ Registrar
2. Declare a death/ marriage event
3. Observe deceased, informant, Groom and bride page

**Actual result:**
Exact Date of Birth Unknown option not appearing in death and marriage form and after submission shows required for registration
![exact](https://github.com/opencrvs/opencrvs-core/assets/94350336/0d000b5f-5292-443e-af3d-69ed0fd7b13b)

**Expected result:**
Should show Exact Date of Birth Unknown option

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Nil20** [comment]
https://github.com/opencrvs/opencrvs-farajaland/pull/675

this should fix this issue as well

**Comment by SyedaAfrida** [comment]
This bug is fixed
![mar](https://github.com/opencrvs/opencrvs-core/assets/94350336/68fe6af6-1dfe-461e-98bc-28d5627144f2)
