### ISSUE TITLE
If in a draft, Mother's/Father's  details are not available is selected with reason, Later the informant is selected mother/father, then all the data for mother/father page should be cleared

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5820]
**Bug description:**
If in a draft, Mother's  details is not available is selected with reason, Later the informant is selected as mother, then all the data for mother page should be cleared and should show all the questions for mother's page. Same should be followed for father

**Steps to reproduce:**
1. Login to FA/RA/ Registrar
2. Save a draft with Mother's/ Father's  details is not available is selected with reason
3. Click Update
4. Select relationship to child as mother/ father
5. Continue and observe

**Actual result:**
Can submit a record with no mother/father's details when informant is mother/father

**Expected result:**
If relationship is mother then Mother's  details is not available question and reason should not show, and all questions should be showing
If relationship is father then Father's  details is not available question and reason should not show, and all questions should be showing

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/b8d04916-ad85-4769-8be1-8c57e2729144

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
**Bug :** 
When relationship changed from father to mother or vice versa and submitted, then the record disappears after going to outbox. When searched, status is showing different in workqueue and record audit

https://github.com/opencrvs/opencrvs-core/assets/94350336/ded1aee5-1a54-40a8-ab23-129e30610382

**Comment by Nil20** [comment]
This one should be fixed through this.
https://github.com/opencrvs/opencrvs-core/pull/5875

**Comment by SyedaAfrida** [comment]
This ticket is fixed

https://github.com/opencrvs/opencrvs-core/assets/94350336/b52452a4-3955-454b-8155-33a747aa0e8c
