### ISSUE TITLE
UI issue in registration by status in performance

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5824]
**Bug description:**
UI issue in registration by status in performance

**Steps to reproduce:**
1. Login as RA/ Registrar / System admin / performance manager
2. Click Performance
3. filter any office
4.  Click any status link and observe

**Actual result:**
UI issue in registration by status in performance

**Expected result:**
should not overlap data

**Screen recording:**
![per](https://github.com/opencrvs/opencrvs-core/assets/94350336/4a2667a9-b7f4-4f1b-a0b3-42dd87e85a6f)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
@Nil20 Could you verify with @SyedaAfrida if it's reproducible or not?

**Comment by SyedaAfrida** [comment]
Not a bug. Can be closed
