### ISSUE TITLE
VS export: verify it's working properly after form refactor

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#5826]

**Comment by SyedaAfrida** [comment]
This ticket is tested and can be closed
[Month-August-Farajaland-death-event-statistics (1).csv](https://github.com/opencrvs/opencrvs-core/files/12509991/Month-August-Farajaland-death-event-statistics.1.csv)
[Month-August-Farajaland-birth-event-statistics (1).csv](https://github.com/opencrvs/opencrvs-core/files/12509993/Month-August-Farajaland-birth-event-statistics.1.csv)
