### ISSUE TITLE
Migration bug: 20230127063226-update-practitioner-role.js

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5839]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGxKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--68d55391a2e23cdad2eb0e55dd3cc5555080de29/Screenshot%202023-08-29%20at%2011.30.52.png)

**Comment by Zangetsu101** [comment]
Completed in #5843
