### ISSUE TITLE
Place of birth/ death/ marriage not appearing in certificates

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5841]
**Bug description:**
Place of birth/ death/ marriage not appearing in certificates

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Click Ready to print
3. Print any certificate

**Actual result:**
Place of birth/ death/ marriage not appearing in certificates

**Expected result:**
Should show Place of birth/ death/ marriage in certificates

**Screen recording:**
![cer](https://github.com/opencrvs/opencrvs-core/assets/94350336/fcd17081-9ae3-4249-b1eb-9ccb51331f97)

**Tested on:**

**Comment by Zangetsu101** [comment]
@SyedaAfrida This will get fixed after we reset the QA

**Comment by SyedaAfrida** [comment]
**Bug:**
health institution name not appearing in birth/ death certificate

https://github.com/opencrvs/opencrvs-core/assets/94350336/f9194d98-649c-4a00-9fde-925c803d0b15

**Comment by euanmillar** [comment]
Awaiting new certs from @jpye-finch

**Comment by SyedaAfrida** [comment]
**Bug:** health institution name not appearing in certificate

https://github.com/opencrvs/opencrvs-core/assets/94350336/e743fa56-9d8d-4382-87dc-ba52333a3c25

**Comment by eduffus** [comment]
The original bug showed no place of birth/death/marriage appearing at all, which is priority high before R1.3 is launched.
For Farajaland we only require Ibombo District, Central Province, Farajaland to show on the cert. 
There is no requirement for the Health Institution to be shown, but a core improvement ticket would allow the possibility to add health facility to the cert (which some countries may want). Low priority for R1.4.

**Comment by SyedaAfrida** [comment]
fixed already
