### ISSUE TITLE
QR code should be in certificates by default

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5847]
**Bug description:**
QR code should be in certificates by default

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Click Ready to print
3. Print any certificate and observe

**Actual result:**
QR code not showing since there is no QR code in svg of certificates by default

**Expected result:**
QR code should be in certificates by default

**SVG:**
Provided by Jonathan (with dummy QR code)
![marriage](https://github.com/opencrvs/opencrvs-core/assets/94350336/8b0ba724-afc5-445d-965f-cdd3aeb9dddd)
![birth](https://github.com/opencrvs/opencrvs-core/assets/94350336/6aaf865b-c3be-43e0-b090-7d49a52cf6e9)
![death](https://github.com/opencrvs/opencrvs-core/assets/94350336/1d75c412-2931-44c4-a990-1ae9e167c378)

working svg (can take help from here)
![Death svg with QR (1)](https://github.com/opencrvs/opencrvs-core/assets/94350336/9e895e77-44bd-448b-b96e-f96f5b5a9fa7)
![Birth svg with QR (1) (1)](https://github.com/opencrvs/opencrvs-core/assets/94350336/5f6782ac-8add-4fcf-baf6-0c7f7aca5a0a)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
Awaiting new certs from @jpye-finch

**Comment by SyedaAfrida** [comment]
This ticket is fixed
[903c64cb-50c5-47d6-9af7-b3c60c6ab418.pdf](https://github.com/opencrvs/opencrvs-core/files/12657393/903c64cb-50c5-47d6-9af7-b3c60c6ab418.pdf)

![Screenshot_20230919-140400_Samsung Internet](https://github.com/opencrvs/opencrvs-core/assets/94350336/96f12b10-ef32-4dce-8710-260694e6bbe8)
