### ISSUE TITLE
Deploy Storybook to GitHub Pages

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#5857]
Currently, we don't deploy Storybook at all, and that is understandable because the actual installations of OpenCRVS don't need a running Storybook. We could investigate deploying it with [GitHub Pages](https://pages.github.com/) for free.

At the same time we could remove it from development runtime, it takes time to start up and hogs some memory. Think it could be started on-demand.

Dev tasks:
- [ ] Deploy Storybook to GitHub Pages. Create an GitHub Action to do this on develop merge
- [ ] Remove Storybook from default local development. It can be started on-demand

**Comment by rikukissa** [comment]
Depends on https://github.com/opencrvs/opencrvs-core/issues/7440

**Comment by euanmillar** [comment]
Closing as this is already hosted at ui-kit
