### ISSUE TITLE
New handlebars  required for Philippines

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5864]
We have these:

```
{
            fieldName: certificateHandlebars.registrar,
            operation: 'userTransformer',
            parameters: ['REGISTERED']
          },
          {
            fieldName: certificateHandlebars.registrationAgent,
            operation: 'userTransformer',
            parameters: ['VALIDATED']
          },
          {
            fieldName: certificateHandlebars.registrarName,
            operation: 'registrarNameUserTransformer'
          },
          {
            fieldName: certificateHandlebars.role,
            operation: 'roleUserTransformer'
          },
```

- [ ] refactor the above so that there is a certificateHandlebar.user object and "registrar",  "registrationAgent" and "fieldAgent" can be passed as a parameter

- [ ] Amend userTransformer so that the users office state and district location readable name can be extracted in a certificate handlebar e.g.:  {{ registrar.state }}  {{ registrar.district }} {{ registrar.city }}

- [ ] Amend userTransformer so that the field agent details can be accessed office state and district location readable name can be extracted in a certificate handlebar e.g.:  {{ fieldAgent.name }}  {{ fieldAgent.role }}
fieldAgentName

- [ ] Deprecate roleUserTransformer, registrarNameUserTransformer

Create new functions for:

sentForApprovalDate
trackingId
comment

**Comment by Zangetsu101** [comment]
instead of adding fieldAgentRole, registrationAgentRole why don't we have a handlebar that exposes details of the user ( we only expose what we need now, then latter on we can add more as requirements come) associated with the declaration till Registration? Kind of a merger with #5794

**Comment by Zangetsu101** [comment]
Even the stateOfRegistration & districtOfRegistration can be acquired from the details of the Registrar's office location

**Comment by euanmillar** [comment]
@tahmidrahman-dsi I updated the description based on @Zangetsu101 feedback
