### ISSUE TITLE
After correcting any birth record by changing relationship to child from mother to father or vice versa, all the information of mother and father's details is getting changed

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5866]
**Bug description:**
After correcting any birth record by changing relationship to child from mother to father or vice versa, all the information of mother and father's details is getting changed

**Steps to reproduce:**
1. Login to Registrar
2. Correct any birth record where relationship to child is mother or father
3. Change relationship from mother to father or father to mother
4. Correct the record
5. Later view that record

**Actual result:**
After correcting any birth record by changing relationship to child from mother to father or vice versa, all the information of mother and father's details is getting changed (becoming duplicate)

**Expected result:**
Information of father and mother's details should not change

**Screenshot:**
before correction

![before corection](https://github.com/opencrvs/opencrvs-core/assets/94350336/11344b4a-1447-4924-ab59-a22e0ac934a5)

after correction

![after correction](https://github.com/opencrvs/opencrvs-core/assets/94350336/f3d5f4d7-6b40-439d-88bf-52e752cdca88)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Nil20** [comment]
https://github.com/opencrvs/opencrvs-core/pull/5875

Cannot connect the issue through github. Thus, commented here.

**Comment by SyedaAfrida** [comment]
When the informant is changed from mother/ father to any other informant then keep all the fields(first name, last name, nid etc ) empty. Otherwise all the information gets duplicated in both the pages

https://github.com/opencrvs/opencrvs-core/assets/94350336/39998e6b-6edd-45a4-8a25-b163ceeb9b63

**Comment by Nil20** [comment]
Could not determine the proper way to fix this. So I moved to other tickets since the priority of fixing bugs is high.
