### ISSUE TITLE
Even if supporting document is provided, showing "No supporting document " and upload link below attachments

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5867]
**Bug description:**
Even if supporting document is provided, showing "No supporting document " and upload link below attachments

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Review / View/ Correct record any record with supporting documents

**Actual result:**
![sup doc](https://github.com/opencrvs/opencrvs-core/assets/94350336/de95741b-d19d-4494-8b11-e07c0f73b8bd)

**Expected result:**
should only show attachments

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Nil20** [comment]
![image](https://github.com/opencrvs/opencrvs-core/assets/32668488/7ae63165-c35c-47a3-95d4-0039d0544ff1)
This one's probably fixed

**Comment by SyedaAfrida** [comment]
This issue is fixed

https://github.com/opencrvs/opencrvs-core/assets/94350336/38969d62-309a-4199-8f1f-cfa179cda6fa
