### ISSUE TITLE
Bride and Groom signature not getting updated in marriage certificate

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5869]
**Bug description:**
Bride and Groom signature not getting updated in marriage certificate

**Steps to reproduce:**
1. Login to Registrar
2. Download> Review any marriage certificate
3. Update Bride/ Groom signature
4. Click Register
5. Click Ready to Print
6. Print that certificate and observe

**Actual result:**
Bride and Groom signature not getting updated in marriage certificate

**Expected result:**
Should show updated bride and groom signature

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/642d3f53-4ce1-4e76-bbb0-1a0d10676f28

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Nil20** [comment]
https://github.com/opencrvs/opencrvs-core/pull/5878

**Comment by SyedaAfrida** [comment]
This bug is fixed
https://www.loom.com/share/8493d5a1db4346eaa6300dc23844b545?sid=b7419ccc-d7c0-4a24-8cb6-fe47103ec8ed
