### ISSUE TITLE
If user first name has space at the end, then cannot login will that user

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5897]
**Bug description:**
If user first name has space at the end, then cannot login will that user

**Steps to reproduce:**
1. Login to National system admin
2. Create a new user with space in the end of user first name
3. Logout
4. Login with the new user name and observe

**Actual result:**
If user first name has space at the end, then cannot login will that user

**Expected result:**
User should be allowed to login

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/7987ca45-4e00-4294-a4ee-5fb674d44d84

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by euanmillar** [comment]
Sanitise input from form fields please

**Comment by SyedaAfrida** [comment]
This bug is fixed

https://github.com/opencrvs/opencrvs-core/assets/94350336/23c10d89-9bd5-490e-80d8-63f380167937
