### ISSUE TITLE
Cannot delete any client from integration

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5922]
**Bug description:**
Cannot delete any client from integration

**Steps to reproduce:**
1. login to national system admin
2. Configuration> integration
3. Click 3 dot> Delete> Delete

**Actual result:**
Cannot delete any client from integration

**Expected result:**
should be able to delete

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/c1d0e626-8d0b-4330-baee-e95fdc03f7b1

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Nil20** [comment]
> @SyedaAfrida @eduffus @Zangetsu101
> 
> There appears to also be an issue with data generator, because in production, migrations do not complete with this error
> 
> ```
> ERROR: Could not migrate up 20230602090436-update-identifier-with-system.js: Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer at new BSONTypeError (/app/node_modules/bson/lib/error.js:41:28) at new ObjectId (/app/node_modules/bson/lib/objectid.js:67:23) at file:///app/packages/migration/build/dist/src/migrations/hearth/20230602090436-update-identifier-with-system.js:45:34
> ```

I'm gonna take a look at the migration issue. @euanmillar

**Comment by SyedaAfrida** [comment]
This bug is fixed
![5922 fixed](https://github.com/opencrvs/opencrvs-core/assets/94350336/52a1b9b3-6d14-4cc4-87c3-c386722a4b4b)
