### ISSUE TITLE
Rate limiting must be introduced on external services: prevent brute force

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5930]
The externally facing services below should have a common rate limiting approach in commons package:

auth
gateway
webhooks
countryconfig
config
dashboards

The externally facing dependencies below need researched and a rate limiting approach should be added.

openhim
kibana
minio

**Comment by naftis** [comment]
Think a Hapi plugin is a smart decision as we can re-use it between our microservices. I see 2 different attack vectors here: 1) DDoS and 2) brute-forcing a password or other user details. The best protection for DDoS is hiding all services behind a VPN. Any in-server DDoS protection can be abused by just getting the server stuck processing all the 'valid' spammed requests. Third-party options include for example CloudFlare. Many VPS providers like DigitalOcean also offer DDoS mitigation services. 

Then the 2) brute force, we could limit routes with https://github.com/futurestudio/hapi-rate-limitor for instance. Every route could have a default rate limit. We need to be able to initially receive quite many requests, like 50 when the page loads. But no one should be making ~500 requests/minute.

**Comment by naftis** [comment]
Separate task for making auth sturdier:
- [ ] Disallow making external requests to auth. This requires Traefik changes?
- [ ] Refactor services that make external requests to auth. This includes login + documentation updates?

**Comment by euanmillar** [comment]
@rikukissa we need to tech design a fix for data-generator and seeding

**Comment by naftis** [comment]
@euanmillar Do you mean this? https://github.com/opencrvs/opencrvs-core/pull/6218 there's a fix where `bypassratelimit` scope has been added for `o.admin`. This should allow data generator and seeding to bypass rate limiting.

**Comment by naftis** [comment]
This just needs to be tested that it actually works in a deployed environment, to close this off? @Zangetsu101

**Comment by Zangetsu101** [comment]
That's about right.
>there's a fix where bypassratelimit scope has been added for o.admin. This should allow data generator and seeding to bypass rate limiting.
Do we need to do something similar for e2e?

**Comment by naftis** [comment]
This has been shown to work with E2E, the only issue that has occurred is being tracked in this ticket https://github.com/opencrvs/opencrvs-core/issues/7077#issuecomment-2185799921

**Comment by SyedaAfrida** [comment]
**Bug:**
Error is shown after 4/5 consecutive actions on team page. This page was not working even after refresh or logout and logging in completely fresh. Started working after 2/3 mins




![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/f3a2cdba-11c6-4d1d-bc26-8da1d5b17cd2)

**Comment by naftis** [comment]
It should rate limit after 10 consecutive actions on the team page, and you should be able to continue after 1 minute. It works as expected, but if you are running into it with normal usage, we should raise the rate limit to for example 20 tries instead of 10.

https://github.com/opencrvs/opencrvs-core/assets/1322608/df2a127c-10bc-49ce-a5f9-cef4e5f3b8c7

**Comment by SyedaAfrida** [comment]
@naftis yes it would be better because we are encountering this very frequently

**Comment by SyedaAfrida** [comment]
This ticket is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/3667397d-7591-4aac-bda4-80112fcfd848
