### ISSUE TITLE
Ask for existing password first before a user can change phone number or email

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5931]
### Description
- adds prompt to enter current password. after the user has entered their new number or email address

### Acceptance criteria

**Email address**
GIVEN I am on the Settings page
WHEN I click change email
THEN[ open the change email dialog](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=18637-6510&mode=design&t=zggQttWgMvlfJwjm-11)

GIVEN I enter a valid email addresss
WHEN I click continue
THEN [open the password confirmation dilalog](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=18637-6583&mode=design&t=zggQttWgMvlfJwjm-11)

GIVEN I enter my password
WHEN it is correct
THEN [close the dialog and show the Toast loading state](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=18637-6768&mode=design&t=zggQttWgMvlfJwjm-11)
THEN the Toast confirmation message

**Phone number**
GIVEN I am on the Settings page
WHEN I click change phone number
THEN[ open the change phone number dialog](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=18637-6637&mode=design&t=zggQttWgMvlfJwjm-11)

GIVEN I enter a valid phone number
WHEN I click continue
THEN [open the password confirmation dilalog](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=18637-6697&mode=design&t=zggQttWgMvlfJwjm-11)

GIVEN I enter my password
WHEN it is correct
THEN [close the dialog and show the Toast loading state](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=18637-6777&mode=design&t=zggQttWgMvlfJwjm-11)
THEN the Toast confirmation message

---
**Error states**
GIVEN i enter an invalid email addres
THEN [show the error state](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=18637-6858&mode=design&t=zggQttWgMvlfJwjm-11)

GIVEN i enter an invalid phone address
THEN [show the error state based on my country configuration (phone number regex)](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=18637-6885&mode=design&t=zggQttWgMvlfJwjm-11)

GIVEN i enter a password
WHEN it is wrong
THEN [show the error state](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=18637-6583&mode=design&t=zggQttWgMvlfJwjm-11)

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=14417%3A102007&mode=design&t=CLGaOrDYGvmOPI0d-1

![Image](https://github.com/opencrvs/opencrvs-core/assets/46478402/55a23015-8e20-4ace-b916-015897f730ad)

### Dev tasks

- [ ] Task 1

**Comment by naftis** [comment]
Hi, can we add to the description why we have decided to change this? AFAIK, this doesn't change anything security-wise as we're already checking the current password 
![image](https://github.com/opencrvs/opencrvs-core/assets/1322608/09dfb31e-7510-4742-92d3-2a8e09a361f8)

**Comment by rikukissa** [comment]
Seems to be same in latest develop 
![image](https://github.com/opencrvs/opencrvs-core/assets/1206987/b24bec81-b692-4d72-b944-f2766f90d977)

But indeed, if we are already asking it here then we don't need to ask it again

**Comment by tahmidrahman-dsi** [comment]
@jpye-finch, @euanmillar, the current implementation has 2FA code verification when changing email/phone. Do you think we should still check the current password? 


https://github.com/opencrvs/opencrvs-core/assets/42269993/e911298d-9155-49f7-a63a-e320700b55ac



https://github.com/opencrvs/opencrvs-core/assets/42269993/7f91a3dc-91f9-4289-b0ab-2eda0c618f0b

**Comment by rikukissa** [comment]
2FA is more secure than just asking a password, so in the name of keeping it simple, I'd leave it as is.

**Comment by jpye-finch** [comment]
@rikukissa @tahmidrahman-dsi @euanmillar 
This feature request came out of the security audit as something that was missing and required

**Comment by rikukissa** [comment]
Blocked for now. Euan to check with the Guardian project

**Comment by euanmillar** [comment]
Guardian project have approved our approach so we can close this issue as not required.
