### ISSUE TITLE
Check environment variables are set before services start

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5932]
Before starting any service in packages/service, ensure all environment variables are set. If vars such as CHECK_INVALID_TOKEN are missed or set incorrectly in production, it can expose the application.

The impact of this is reduced risk of misconfiguration and significant reduction of time spent debugging in OpenCRVS instances installed either by us or SIs.

This can for instance be done using [envalid library](https://github.com/af/envalid). Implement this also for country config.

## Dev tasks

- Install envalid to all microservices.
- Search and remove unused environment variables.
- Define environment variables and types as strictly as possible, so that strings like `"true"` never escape to the application code before being converted to boolean
<br>

Look into how Riku has done this on these services, and create a pull request that adds the environment validation to the remaining services.

- [x] Metrics **check out [Riku's PR](https://github.com/opencrvs/opencrvs-core/pull/7559/files)**
- [x] Search **check out [Riku's PR](https://github.com/opencrvs/opencrvs-core/pull/7559/files)**
- [x] Workflow **check out [Riku's PR](https://github.com/opencrvs/opencrvs-core/pull/7559/files)**

**Comment by rikukissa** [comment]
We do now have validation for deployment time environment variables. Having a process-level validation would still make a lot of sense however, as we have no control over deployment infrastructure of an implementing country
