### ISSUE TITLE
Where no supporting docs are required needs text to read "No supporting documents are required."

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5938]
**Bug description:**
Where no supporting docs are required the page looks blank, with no instructions. Needs text to read "No supporting documents are required."

**Steps to reproduce:**
1. Login to Fa/ RA/ Registrar
2. Declare any  birth/ death/ marriage event
3. Go to supporting document page

**Actual result:**
Where no supporting docs are required the page looks blank, with no instructions.

**Expected result:**
Where no supporting docs are required needs text to read "No supporting documents are required."

**Screenshot:**

![no sup](https://github.com/opencrvs/opencrvs-core/assets/94350336/f2f73b2e-015a-4066-959b-661cc11bb97e)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by jpye-finch** [comment]
Can be achieved with form configuration. 

Showing a conditional heading when no supporting documents are required
