### ISSUE TITLE
In the certify record page, all the options should not be "print and issue to informant (***)" as informant is only one

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5939]
**Bug description:**
In the certify record page the first 2 options are "print and issue to informant (mother)" and "print and issue to informant (father)", however only the mother was the formal informant in this case. It should read:
- "print and issue to informant (mother)" 
- "print and issue to father" 

**Steps to reproduce:**
1. Login RA/ Registrar
2. Try to print any certificate
3. Observe certify record page

**Actual result:**
For birth declaration-the first 2 options are "print and issue to informant (mother)" and "print and issue to informant (father)", however only the mother was the formal informant in this case. 

**Expected result:**
It should read:
- "print and issue to informant (mother)" 
- "print and issue to father" 

It should be reverse if the informant is father

**Screenshot:**
![image (6)](https://github.com/opencrvs/opencrvs-core/assets/94350336/b34fa0fa-623f-4572-be46-36392b863e70)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
Does
"print and issue to mother"
"print and issue to father"
work?
Because doing the other way would require some effort on our part

**Comment by SyedaAfrida** [comment]
This bug is fixed by #5994 


![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/b930fcb0-f333-48e7-a864-d39e457c9641)
![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/2675418c-bc32-4a67-91dc-c10130044a88)
