### ISSUE TITLE
Username change issue

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5954]
**Bug description:**
 Username change issue

**Steps to reproduce:**
1. Default users have two users
Riku Rouvila – r.rouvila – Registrar
Riku Rouvila – ri.rouvila – National system admin
2. Any update is performed on ri.rouvila
System tried to generate a new username (like it currently does for any change in user details)
3. It takes the initial of first name and surname and creates a proposed username: r.rouvila
4. Now it checks if a user already exists with the username – yes it does, the Registrar
5. Now the 1  get’s added to the proposed username r.rouvila1 , we check again and no user exists this time
6. Proposed username != original username and this means the username changes

**Expected result:**
If the user’s real name hasn’t changed, we shouldn’t try to update their username either. An alternative approach would be bringing the username field to the UI so that it can be defined by the admin user and validated right then and there. 

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by jpye-finch** [comment]
Will specify and document to how a username is generated.

@rikukissa How would ri.rouvila get generated.

**Comment by tiri39** [comment]
Could not reproduce this one in QA env.
