### ISSUE TITLE
When a draft is completed or edited, should not show correction or dash sign

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5956]
**Bug description:**
 
When a draft is completed or edited, should not show correction or dash sign

**Steps to reproduce:**
1. Login to FA/ RA/ Registrar
2. Create a draft with only names
3. Click save and exit
4. Click Update
5. make changes and complete declaration

**Actual result:**
Correction or dash sign is showing when updating a draft declaration. This should only appear when RA/ Registrar is making changes in any submitted declaration by FA”

**Expected result:**
When I edit my draft **- do not show the red dash**

**Screenshot:**

https://www.loom.com/share/e7a6a48944e94b99986b88eb7085d359?sid=2fd0036b-469e-4d0a-bb4c-529294b76420

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Nil20** [comment]
https://github.com/opencrvs/opencrvs-core/pull/5983

This PR should fix this issue as well

**Comment by SyedaAfrida** [comment]
This bug is fixed

https://github.com/opencrvs/opencrvs-core/assets/94350336/0c3f9e4f-5021-41bf-89a9-d10408772086
