### ISSUE TITLE
Signature header missing in Confirm details page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5964]
**Bug description:**
Signature header missing in Confirm details page

**Steps to reproduce:**
1. Login to national or local system admin
2. Click Team
3. Click 3 dot menu> Edit user of any registrar

**Actual result:**
Signature header missing in Confirm details page

**Expected result:**
Should show signature header

**Screen recording:**

![sig header missing](https://github.com/opencrvs/opencrvs-core/assets/94350336/23022919-7d31-45ed-bbdc-2c6bbb90dbe3)

**Design:**

![sig design](https://github.com/opencrvs/opencrvs-core/assets/94350336/738f399b-1817-4a02-97cf-f973d2778776)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by jpye-finch** [comment]
**Design**
<img width="637" alt="image" src="https://github.com/opencrvs/opencrvs-core/assets/46478402/76866249-46b7-47be-ab68-23ba50ef9100">

**Comment by Nil20** [comment]
This is addressed in https://github.com/opencrvs/opencrvs-core/pull/5862/files

**Comment by Zangetsu101** [comment]
@Nil20 Could you please confirm if this is already addressed in the PR you mentioned?

**Comment by Nil20** [comment]
> @Nil20 Could you please confirm if this is already addressed in the PR you mentioned?

Yeah, it's actually not addressed in the PR. Only about the header of the page is fixed in the PR.

**Comment by SyedaAfrida** [comment]
This bug is fixed
![mob](https://github.com/opencrvs/opencrvs-core/assets/94350336/908a4cc8-d94d-4617-85cc-0477590eda26)
![sig header](https://github.com/opencrvs/opencrvs-core/assets/94350336/417b104a-e772-41e8-bc9f-e149c21fb08c)
