### ISSUE TITLE
Cannot create any declaration for health system when date of birth/ death is not given

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5981]
**Bug description:**
Cannot create any declaration for health system when date of birth/ death is not given

**Steps to reproduce:**
1. From postman post any birth/ death declaration without date of birth/ death
2. Observe in progress workqueue of RA/ Registrar

**Actual result:**
Record  do not appear in in progress workqueue

**Expected result:**
Record  should appear in in progress workqueue

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/6842

**Comment by SyedaAfrida** [comment]
This bug is fixed


![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/bb3b2d1d-4be3-4803-9ce8-67fab6de79ed)
