### ISSUE TITLE
Queue sorting by times has a number of problems requiring refactor

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5991]
### **Problem statement**

(Describe the problem you're trying to solve by doing this work)

### **Proposed work**

(High-level overview of what we're building and why we think it will solve the problem).

### **Success criteria**

(The criteria that must be met in order to consider this piece of work a success)

### **User stories**

(How the product should work for various user types)

-

### **Scope**

(Current requirements)

### **Future work**

(Future requirements)

**Comment by rikukissa** [comment]
I think the same might apply to how we Task's are sorted in the gateway. `lastUpdated` and `meta.lastModified` times in QA database just seem a little off i.e. sometimes REGISTERED came before VALIDATED according to these
