### ISSUE TITLE
Cannot create a user when phone number is not available

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6022]
**Bug description:**
Cannot create a user when phone number is not available. Since there is another user with no phone number, so the system is showing that this phone number is already been used.

**Steps to reproduce:**
1. Login to national system admin
2. Click Team> New user create sign
3. Fill up all field expect Phone number
4. Click Create user

**Actual result:**
shows error "is already used by another user. Please use a different phone number"

**Expected result:**
User should be able to create user without phone number when phone number is not the mandatory field

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/831d71ee-c061-4cef-9974-d6e5ef0e8657

**Comment by SyedaAfrida** [comment]
Fixed in Niue but need to test in core

**Comment by SyedaAfrida** [comment]
This bug is fixed

https://github.com/opencrvs/opencrvs-core/assets/94350336/062c9a1f-52cd-466b-8a08-12209a940576

**Comment by SyedaAfrida** [comment]
This bug reappear in latest version
**Environment:** https://login.farajaland-staging.opencrvs.org/?lang=en
**Version:** V1.3.3

https://github.com/opencrvs/opencrvs-core/assets/94350336/11da1163-ac7b-4a9d-8c06-38aa7b986dd8

**Comment by euanmillar** [comment]
The migration to add an index for mobile should have fixed this but it might not work if the index already exists.

**Comment by SyedaAfrida** [comment]
This bug is fixed in V1.3.3


https://github.com/opencrvs/opencrvs-core/assets/94350336/46f1eec3-5324-4918-9550-ba261dc2bbfb
