### ISSUE TITLE
Marriage: Deduplication check and review

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6033]
### Description

- Adds deduplication suport for marriages
- Same experience as birth and death

Criteria:

- Similar groom's firstname(s)
- Similar groom's lastname
- Same National ID (if available)
- Similar date of birth (within 5 days) or same age

- Similar bride's firstname(s)
- Similar bride's lastname
- Same National ID (if available)
- Similar date of birth (within 5 days) or same age

### Acceptance criteria

GIVEN a FA submites a marriage declaration
THEN perform a dedup check

GIVEN a RA creates a marriage declaration and sends for review
THEN perform a dedup check

GIVEN a REG creates a marriage declaration and registeres it 
THEN perform a dedup check

GIVEN a marriage declaration is flagged as a possible duplicate
THEN move it to the Ready for review queue for the Registrar

GIVEN I am a Registrar
WHEN I click Review on a flagged record
THEN load the duplicate review side by side

GIVEN I mark not a duplicate
THEN behaviour is the same as birth and death

GIVEN I mark the record as a duplicate
THEN behaviour is the same as birth and death

### Dev tasks

- [ ] ..

**Comment by euanmillar** [comment]
Custom events will enable for all future countries #7052
