### ISSUE TITLE
Marriage: Search and advance search for marriage records

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6035]
### Description

- Adds search for a marriage record
- Adds advance search for a marriage record

### Acceptance criteria

GIVEN I am searching for a record
WHEN I search by tracking id, MRN, Name, and Phone number then check for marriage records
THEN given a match is found then show the marriage records

GIVEN I select Advanced search
WHEN I select the marriage tab
[THEN I can see the marriage advanced search options](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=18293%3A96237&mode=design&t=iksunCP8jqOh4nOA-1)

GIVEN I perform an advanced marriage seach
THEN I can favourite the search ⭐️

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=18293%3A96237&mode=design&t=iksunCP8jqOh4nOA-1

### Dev tasks

- [ ] Task 1

**Comment by euanmillar** [comment]
@jpye-finch FYI, the Figma link goes to a design that is wrong as it has deceased's details on it. I think this is a SMALL task so changing the HL Estimate

**Comment by euanmillar** [comment]
Custom events will enable for all future countries #7052
