### ISSUE TITLE
Marriage: application settings

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6067]
### Description

- Adds marriage application settings
- Registration periods same logic as Death (Legally specified and Delayed)
- Fees same logic as Death (Legally specified and Delayed)

### Acceptance criteria

GIVEN I am National System Admin
WHEN on the Application Tab
THEN I can select Marriage

GIVEN I am on the Marriage application settings
THEN I can set the Legally specified period for marriage registration
THEN I auto set the delayed registration period

GIVEN I am on the Marriage application settings
THEN I can set the fees for Legally specified
THEN I can set the fees for Delayed

### Dev tasks

- [ ] Task 1

**Comment by euanmillar** [comment]
Custom events will enable for all future countries #7052
