### ISSUE TITLE
Collection workflow updates

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6073]
### Description

- For the Certificate collector form when selecting Someone else the user nav to a different page
- On the Correction requester page we just ask for the Relationship to child/deceased
- This ticket is to move the questions to one page and ask the same for birth/death/marriage

Someone else form questions:
1. Type of ID
2. Firstname(s)
3. Lastname
4. Relationship to [child]/[deceased]/[married couple]
5. Email address
6. Phone No. 

### Acceptance criteria

**Certifying**
GIVEN I am printing a record
WHEN I select Print and issue to someone else
THEN expand the RadioGroup and show the someone else form questions

**Issueing**
GIVEN I am printing a record
WHEN I select Issue to someone else
THEN expand the RadioGroup and show the someone else form questions

**Correct record**
GIVEN I am printing a record
WHEN I select Someone else
THEN expand the RadioGroup and show the someone else form questions

### Design

![Image](https://github.com/opencrvs/opencrvs-core/assets/46478402/2ec5fd8b-83c3-46b1-91e2-7f2b376e26d7)

### Dev tasks

- [ ] In certificate collector flow, remove the 2nd page after "Someone else" is selected as the collector. Bring the inputs to the same radio group to be visible after "Someone else" is selected. This applies also for nested fields.
- [ ] In correction flow, show the same inputs instead of "Relationship to child".
  - [ ] In Hearth, verify RelatedPerson stores all the captured information of Relationship to x. 
- [ ] In correction flow, after Someone else was selected and we show "Proof of ID" prompt, make sure the correctors information is shown correctly
- [ ] In both collector and corrector form, make sure depending on the event type the "Relationship to ___" is printed correctly.

**Comment by jpye-finch** [comment]
Blocking in favor of applying the approach considered for Revoke registration.

**Comment by euanmillar** [comment]
@jpye-finch I think we should unblock as revoke registration is unlikely to be built in 1.7.0

**Comment by jpye-finch** [comment]
ok yeh we need to discuss an approach. As the solution for me now is to have a configurable form for each Record Action

instead of making updates to a hardcoded page

**Comment by euanmillar** [comment]
Moved this out of 1.7 as it wasnt in an existing Epic @jpye-finch @marcio-opencrvs

**Comment by euanmillar** [comment]
Moved the description to the IET project ticket: #6831
