### ISSUE TITLE
refactor: civil registeration staff member select for the correction requester

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6074]
### Description

- Currently we have two options in the Correction requester page (Me & Another registration agent or field agent)
- This ticket is to combine the option into one 'Civil registeration staff member'
- On selection the user can search and select for the user
- Or if two tricky. Freeform enter their name

### Acceptance criteria

GIVEN I am correcring a record
WHEN civil registeration staff member is requesting the change
THEN I can choose/enter the name of the user

### Design

![Image](https://github.com/opencrvs/opencrvs-core/assets/46478402/b284e264-5506-4e45-a789-8082ab21a5bc)

### Dev tasks

- [ ] Task 1

**Comment by jpye-finch** [comment]
Blocking in favour of making this page a configurable form for countried

**Comment by euanmillar** [comment]
@jpye-finch moved requirement to #6906
