### ISSUE TITLE
feat: send email/sms notification if a RegAgent starts a declaration and sends for approval

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6095]
Currently when a regsitration agent starts a declaration and sends it for approval. We don't send any sms/email notification to the user.

This ticket is to fix and send the **inReview** email template - for this situation

### ACs
GIVEN I am a Reg Agent
WHEN I start a declaration and send it for approval
THEN send an SMS/Email notification to the informant using the inReview template message

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/6659

**Comment by SyedaAfrida** [comment]
This bug is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/a00c5688-b962-4d73-bbc8-b14f3727cab2
