### ISSUE TITLE
docker compose v1 to v2

### ISSUE THREAD

**Issue by adrienramiliharivelo** [opencrvs/opencrvs-core#6096]
_From July 2023 Compose V1 stopped receiving updates. It's also no longer available in new releases of Docker Desktop._

**The code including the "docker-compose" command for installing open crvs in the setup must be updated to "docker compose".**
![docker_compose_v2](https://github.com/opencrvs/opencrvs-core/assets/117841912/11f154b9-9165-4106-bcc6-39a430c4a016)

_PS: I would like to be a member of contributor. What can I do for ? Thank you._

**Comment by Zangetsu101** [comment]
Completed in #6098, #6099,#6717
