### ISSUE TITLE
Fix locations seeding when there are many locations

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#6124]
Seed script throws 500 if there are many locations in the country. Has happened with three country configurations so far.

https://github.com/newlegacydigital/opencrvs-cameroon/actions/runs/6656594836/job/18089489538

**Comment by euanmillar** [comment]
@rikukissa I think this has to be solved ASAP.  When we go into Uganda or Philippines in the New Year.  We must be able to seed thousands of locations.

**Comment by rikukissa** [comment]
Agreed!
