### ISSUE TITLE
If using Exact date of birth unknown feature,  then show only year in date of birth field in the certificate

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6129]
**Bug description:**
IF a country adds the dateofBirth handlebar to the certificate.
AND only Age in years was capture in the form
THEN show YYYY in the certificate 
**Steps to reproduce:**
1. Login to Registrar
2. Print any declaration where Exact date of birth unknown feature is selected
3. Observe certificate

**Actual result:**
If using Exact date of birth unknown feature, then in certificate Date of birth is shown as "01 January Year(according to calculation of age)"

**Expected result:**
IF a country adds the dateofBirth handlebar to the certificate.
AND only Age in years was capture in the form
THEN show YYYY in the certificate 

**Screenshot:**
![cert](https://github.com/opencrvs/opencrvs-core/assets/94350336/b94ee455-bf28-4695-b253-81a336609a64)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
Need to fix in Niue but fixed in 1.5.0

**Comment by euanmillar** [comment]
So @Zangetsu101 thinks this a fix was applied in Cameroon so we need to apply to the Farajaland repo, and then to the Niue repo

**Comment by Nil20** [comment]
Farajaland's certificates don't seem to have any date of birth fields which can be unknown by the `exactDateOfBirthUnknown` handlebar controlled by the checkbox in the forms. So, this ticket may not be necessary for core.

**Comment by Zangetsu101** [comment]
Okay so core already exposes the required handlebars required and only changes in certificate templates is required

**Comment by euanmillar** [comment]
Closing as this bug has been moved to the Niue project.
