### ISSUE TITLE
Allow the country nationality to show on the certificate

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6137]
### Description
- We capture the country for Nationality in the form dropdown. eg. Somalia. 

This ticket is to:
1. Review the country data for this dropdown
2. Allow a country to convert the option into the nationality for the certificate

eg.
- Somalian instead of Somalia
- Cameroonian instead of Cameroon

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
... 

### Dev tasks

- [ ] Task 1

**Comment by euanmillar** [comment]
Its possible to have a nationality select to show this
