### ISSUE TITLE
refactor: Update Farajaland birth declaration supporting documents to remove Other

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6138]
### Description
- Adds logic to show Proof of Legal Guardianship if the informant is Legal Guardian
- Note backlog ticket to improve how we upload supporting docs with just one option (it removes the select -  find ticket and replace here [todo])
- Remove Proof of Legal Guardianship from Other

### Acceptance criteria

GIVEN the informant is Legal Guardian
WHEN on the Supporting docs page
THEN show the option Proof of legal guardianship with the option Proof of legal guardianship

### Design
..

### Dev tasks

- [ ] Task 1

**Comment by euanmillar** [comment]
Closing as a config issue with Farajaland to address later
