### ISSUE TITLE
For new Name fields in Birth and death declaration, Overflow of text occurs in certificate since there is no limit set for input characters                

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6150]
**Bug description:**
1. In birth declaration
"First name(s) if altered after registration" & "Surname if altered after registration" field , set limit for input character                     
2. In death declaration
"First name(s) at birth" & "Surname at birth" field , set limit for input character            

**Steps to reproduce:**
1. Login to RA/ Registrar/ National registrar
2. Declare a birth/ death 
3. In child's details page and Deceased details page, Provide long names in "name(s) if altered after registration" and  "name at birth" field
4. Register the declaration
5. Print the certificate

**Actual result:**
Overflow of text occurs in certificate since there is no limit set for input characters             

**Expected result:**
set 32 input characters limit

**Screenshot:**

![m](https://github.com/opencrvs/opencrvs-core/assets/94350336/975f5bcb-ea10-489f-b261-f0716fb033ee)

**Tested on:**
https://login.niue.opencrvs.org/?lang=en

**Comment by euanmillar** [comment]
Max chars now set to 32
