### ISSUE TITLE
In Dashboard, Statistics and Leaderboard, Gender filter showing only male option

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6158]
**Bug description:**
In Dashboard, Statistics and Leaderboard, Gender filter showing only male option

**Steps to reproduce:**
1. Login to National Registrar/ Performance manager/ National Sys admin
2. Click Dashboard, Statistics and Leaderboard
3. Click Gender filter

**Actual result:**
In Dashboard, Statistics and Leaderboard, Gender filter showing only male option

**Expected result:**
Should show both male and female

**Screenshot:**
![gender](https://github.com/opencrvs/opencrvs-core/assets/94350336/5b13024e-47ea-4671-b254-4f1cdca8f18a)

**Tested on:**
https://login.niue.opencrvs.org/?lang=en

**Comment by euanmillar** [comment]
@SyedaAfrida this is not a bug.  Filters are only available for registrations that have been submitted.  As soon as a female is registered the filter should appear
