### ISSUE TITLE
When a user is created with phone number, later cannot preview that number

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6169]
**Bug description:**
When a user is created with phone number, later cannot preview that number

**Steps to reproduce:**
1. Login to National registrar
2. Click Team
3. Create a new user
4. Enter phone number
5. Confirm
6. Click 3 dot menu> edit
7. Observe the phone number field

**Actual result:**
When a user is created with phone number, later cannot preview that number

**Expected result:**
should be able to view that number

**Screenshot:**

https://www.loom.com/share/1e4a9437acd94efa846bf3e279d6141c?sid=cb6ffb0c-e499-4e30-8cc4-f1f033205da5

**Tested on:**
https://login.niue.opencrvs.org/?lang=en

**Comment by jpye-finch** [comment]
No UI Design required

**Comment by Zangetsu101** [comment]
We weren't able to reproduce it in farajaland. access to the niue repo is probably required to get to the bottom of this

**Comment by euanmillar** [comment]
Closing as only refers to Niue project
