### ISSUE TITLE
Nationality showing in short form in certificate

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6171]
**Bug description:**
Nationality showing in short form in certificate
Nationality shows as NU for Niue on certificate
NC for Netherlands...

**Steps to reproduce:**
1. Login to RA/Local/ National registrar
2. Print any birth/ death certificate

**Actual result:**
Nationality showing in short form in certificate

**Expected result:**
Should show full name in certificate

**Screenshot:**
![nationality](https://github.com/opencrvs/opencrvs-core/assets/94350336/61ea1e26-c4a9-49e8-b025-8587952d82b9)

**Tested on:**
https://login.niue.opencrvs.org/?lang=en

**Comment by euanmillar** [comment]
@SyedaAfrida the bug says for death certificate too, but I think the bug only applies to birth certificates right?

**Comment by SyedaAfrida** [comment]
@euanmillar yes only for birth certificate. My bad

**Comment by SyedaAfrida** [comment]
This bug is fixed
![6171 fixed](https://github.com/opencrvs/opencrvs-core/assets/94350336/4fd9482f-a1ee-4ea2-a993-21e01a8e2169)
