### ISSUE TITLE
Disable form submission for field agents if any field has an invalid data format

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#6175]
There is an issue where field agents are able to submit declarations with validation errors, such as incorrect date formats (e.g., '01 01 45' instead of '01 01 2023'). This results in exceptions on the backend. The task is to refine the review page logic to disable the submission button when any field contains a validation error, except when the fields are empty, as field agents are permitted to leave mandatory fields blank. This change will prevent the submission of forms with invalid data while still allowing the flexibility needed by field agents.

**Acceptance Criteria:**

- The submission button must be disabled if any form field has a validation error and is not empty.
- Fields with validation errors but left empty should not disable the submission button.
- Ensure that this logic applies only to the field agent role.

**Comment by SyedaAfrida** [comment]
This ticket is fixed
https://www.loom.com/share/3dfa2d717cba444e8281392d7bdccf7c?sid=3397bad3-5b0d-4baf-9e12-e0e25a7e6d99
