### ISSUE TITLE
In deceased details page, change Age of informant to Age of deceased

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6187]
**Bug description:**
In deceased details page, change Age of informant to Age of deceased

**Steps to reproduce:**
1. Declare a death event
2. In deceased details page, select exact date of birth unknown
3. Observe

**Actual result:**
Showing Age of informant

**Expected result:**
In deceased details page, change Age of informant to Age of deceased

**Screen recording:**
![age](https://github.com/opencrvs/opencrvs-core/assets/94350336/8c513430-3d3b-4e8c-a86b-ced2db3351a8)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by naftis** [comment]
![image](https://github.com/opencrvs/opencrvs-core/assets/1322608/4efc0ed4-4ce1-435a-9c5e-cc4b5b2de257)
Exact date of birth unknown -checkbox isn't available on QA or v1.3.3 branch. Is this still an issue?

**Comment by SyedaAfrida** [comment]
@naftis Exact date of birth unknown feature is currently disabled in QA. Will be enabled in next deploy

**Comment by SyedaAfrida** [comment]
This bug is fixed already
![fixed](https://github.com/opencrvs/opencrvs-core/assets/94350336/a89a4512-fd0d-4a39-b066-1da4fb30a2f6)
**Tested on:** https://login.farajaland-qa.opencrvs.org/?lang=en
**Version:** V1.4.0
