### ISSUE TITLE
"how to configure a certificate?" link not redirecting to correct page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6190]
**Bug description:**
"how to configure a certificate?" link not redirecting to correct page

**Steps to reproduce:**
1. Login to national system admin
2. Click configuration> certificates
3. Click "how to configure a certificate?" link

**Actual result:**
"how to configure a certificate?" link not redirecting to correct page

**Expected result:**
"how to configure a certificate?" link should redirect to correct page

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/7e54ab6a-fa26-421a-977d-6176cc59f02d

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by eduffus** [comment]
Propose to remove the hyperlink in this and any other area of the application to avoid broken links.

**Comment by Zangetsu101** [comment]
@jpye-finch What should the copy be in that case? Probably mentioning [documentation.opencrvs.org](https://documentation.opencrvs.org/) perhaps

**Comment by Zangetsu101** [comment]
Closing this as the relevant page will get removed in #6975
