### ISSUE TITLE
Date of birth of deceased needs to be calculated using date of death when exact date of birth is unknown

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#6191]
When the age of an individual is provided, we calculate the birth date of that individual from the current date which is fine but in case of the deceased, if we have the death date available (incomplete declaration might not have it) then we should calculate it from that.

**Comment by tahmidrahman-dsi** [comment]
Fixed in https://github.com/opencrvs/opencrvs-core/pull/6196
