### ISSUE TITLE
In review page Change the verbiage from sms to email in Send for approval section and in introduction page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6192]
**Bug description:**
- In review page Change the verbiage from sms to email in Send for approval section. According to informant notification preference (email/sms) change the verbiage in action section of review page
-  in introduction page change from Sms to email

**Steps to reproduce:**
1. Login to RA
2. Click Review in any declaration
3. Observe send for approval section

**Actual result:**
Showing the informant will receive sms when email is configured
in introduction page showing  Sms when email is configured
**Expected result:**
According to informant notification preference (email/sms) change the verbiage in action section

**Screen recording:**

![sms](https://github.com/opencrvs/opencrvs-core/assets/94350336/ffb4d221-f2d8-4741-9815-090731487951)

![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/f02105d8-624b-48d5-9202-6b1f61d807f2)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by naftis** [comment]
https://github.com/opencrvs/opencrvs-farajaland/pull/868

**Comment by SyedaAfrida** [comment]
This bug is fixed in V1.3.3 (staging)


![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/09238c66-2347-4c68-9531-7b4f0a2522d1)
![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/d047fe2f-1770-42b2-bf0d-6fc4e7b13a36)
