### ISSUE TITLE
Can not download incomplete declaration

### ISSUE THREAD

**Issue by Nil20** [opencrvs/opencrvs-core#6197]
When a declaration is sent from field agent as incomplete(without the address of place of birth, place of death etc), it shows "failed to download" as error when one tries to download the record. 

![Screenshot from 2023-11-16 14-02-53](https://github.com/opencrvs/opencrvs-core/assets/32668488/01d9f56e-772e-45d1-a5ce-d446a523b925)

**Comment by SyedaAfrida** [comment]
This bug is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/c7e9403b-5d43-41c3-81ca-c68467b31eaa
