### ISSUE TITLE
Allow search-package to search for a birth place by a province, district or the exact place

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#6198]
This could be done by always saving all the eventLocationIds going up the tree of a location. This would require us to do a migration for all the ElasticSearch items. We already have the `eventLocationId` in ElasticSearch though. Could we create a query, where we fetch all of the child locations of a location, and then just have a (massive) `{query} WHERE eventLocationId = $1 OR eventLocationId = $2 .. OR .. OR .. .. ` ? Something more eloquent would be nice though.

**Comment by Zangetsu101** [comment]
@naftis I think we can already achieve this with the latest refactor? I think it was possible to do so even before that 🤔

**Comment by euanmillar** [comment]
Closing as stale
