### ISSUE TITLE
Add Proof of identity document select to Farajaland forms

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6202]
### Description
- To help test different IDs and the log to show hide National ID as a search term. 
- We are adding type of ID select to the form

This ticket is to update all instances where we currently ask for:

**National ID**
/ freeform / 

and changing it to 

**Proof of identity document** *  
[ National ID ] [ Passport ]
[ Birth Certificate]
[ None ] 

-> IF proof of identity document selected
**Document No.**
/ Freeform / <-

### Acceptance criteria

GIVEN a form configuration asks for National ID
THEN show the search criteria option National ID

GIVEN a form configuration doesn't ask for National ID
THEN hide the search criteria option National ID

### Dev tasks

- [ ] Task 1

**Comment by SyedaAfrida** [comment]
**Bug:**
No Id option available in basic search


![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/ee038c98-c79e-459e-bae7-291d00fc7d5e)

**Comment by SyedaAfrida** [comment]
**Bug:**


![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/63d6f9c3-aa55-44a9-84af-3cc35b4ebdc3)

**Comment by SyedaAfrida** [comment]
This ticket is fixed


![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/1e779f81-df15-4dc6-ab6f-d39357313e5a)
