### ISSUE TITLE
Add a custom field to Farajaland death form 

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6203]
### Description
- Adds a custom field to Farajaland death form to help with QA. 

Custom Field:
**No. of dependants**
/ Number / 

https://www.figma.com/file/NbLGi3Y4hLVFhKCyui0cEH/Declaration%2FFarajaland%2FDeathv2?type=whiteboard&node-id=1-19&t=SzpskP1OQgVcrjQq-4

### Dev tasks

- [ ] Task 1

**Comment by SyedaAfrida** [comment]
This ticket is fixed


![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/a21bb087-ff44-4fc8-a74e-d6b4a2987bc4)
