### ISSUE TITLE
Add a Spouse page to the Farajaland death form

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6204]
### Description
Adds a Spouse page to the Farajaland death form to help with QA testing

### Acceptance criteria

GIVEN I am completing a death form
WHEN if the informant is not the Spouse
THEN show the informant details question fields

GIVEN I am on the Spouse details page
WHEN the informant is the Spouse
THEN hide the checkbox 'Deceased does not have a spouse/or their details are unknown'

### Design
https://www.figma.com/file/NbLGi3Y4hLVFhKCyui0cEH/Declaration%2FFarajaland%2FDeathv2?type=whiteboard&node-id=1115-129&t=SzpskP1OQgVcrjQq-4

### Dev tasks

- [ ] Task 1

**Comment by SyedaAfrida** [comment]
**Bug:**
Showing Exact date of birth unknown checkbox when spouse details is not available


![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/8994f8df-8f18-4605-ad19-22054a8eb714)

**Comment by SyedaAfrida** [comment]
This bug is fixed


![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/c732f46c-5a04-44d2-ad2a-e3052787ff40)
