### ISSUE TITLE
Performance data should load in background and not affect app load

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6210]
## Tech design

At the moment we are looping through all top level locations. That causes the servers and the client to slow down. Therefore we are going to remove the loop & caching and instead we only download the first view beforehand so that opening up the performance view still feels instant. 

- [ ] Only the first view of Performance should be loaded when the app starts
  - For National system admin  - See what their default location is and cache only that
  - For Registrar  - See what their default location is and cache only that
  - For National registrar - See what their default location is and cache only that
  - For Performance manager - See what their default location is and cache only that

**Comment by SyedaAfrida** [comment]
This ticket is fixed
