### ISSUE TITLE
Cannot issue any record

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6216]
**Bug description:**
Cannot issue any record

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Click Ready to print
3. Click Print in any record
4. Select print and issue any certificate
5. Print the certificate

**Actual result:**
The record goes to Ready to issue workque and status becomes certified
Moreover cannot issue any record from ready to issue workqueue. Stays in the same workqueue and status is certified

**Expected result:**
Record should not appear in any workqueue and the status for the record should be issued

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/3b4e0a26-7646-4e33-ad27-fc7152ffd972

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by euanmillar** [comment]
@Nil20 @Zangetsu101 what was the problem here?  Is this a 1.40 problem or a hotfix?

**Comment by Zangetsu101** [comment]
It's 1.4 related. And we'll remove the detectEvent function eventually so this is a stop gap solution til then

**Comment by SyedaAfrida** [comment]
This bug is not fixed. moreover showing incorrect toasts and certified modal is having blank fields


https://github.com/opencrvs/opencrvs-core/assets/94350336/e2a3ae72-0331-4d97-b161-dfe37e47e9e0

**Comment by Nil20** [comment]
[Screencast from 19-3-24 02:53:30 অপরাহ্ণ +06.webm](https://github.com/opencrvs/opencrvs-core/assets/32668488/ecd49633-423c-4e7f-85f1-41272af3a767)
@jpye-finch @SyedaAfrida We could show this now for issuing in record history. I've kept it blank for now like we had previously.

**Comment by Nil20** [comment]
This is ready for review. https://github.com/opencrvs/opencrvs-core/pull/6624

**Comment by SyedaAfrida** [comment]
This bug is not fixed

**Steps to reproduce (differently):**
1. Print the certificate by informant 1 (id verified)
2. Observe certified modal by search
3. Again print the certificate by informant 2 (id not verified)
4. Observe certified modal by search
5. Will observe certified modal got exchanged
6. Again print the certificate by informant 3 (id verified)
7.  Will observe certified modal got exchanged again
8. Again print the certificate by informant 1(id not verified)
9. Will see toast of unassign and the status becomes certified instead of issued



https://github.com/opencrvs/opencrvs-core/assets/94350336/9d545e1b-b584-4fba-a800-b378a370b986

**Comment by SyedaAfrida** [comment]
This bug is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/373ca6f2-c8fd-4fb7-8496-aa85ed53506e
