### ISSUE TITLE
Show correct record option in certificate preview page when trying to print by RA

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6224]
**Bug description:**
Show correct record option in certificate preview page when trying to print by RA

**Steps to reproduce:**
1. Login to RA
2. Go to Ready to print
3. Click Download>Assign> Print that record
4. Observe Certificate preview page

**Actual result:**
No button to correct record from Certificate preview page

**Expected result:**
Should show correct record option in certificate preview page when trying to print by RA
 
**Screen recording:**
![ra](https://github.com/opencrvs/opencrvs-core/assets/94350336/4890f86b-3a9b-4926-9bdd-9732eb487de9)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by anamulhaquemollah** [comment]
fix: https://github.com/opencrvs/opencrvs-core/pull/6834

**Comment by SyedaAfrida** [comment]
This bug is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/c970c088-b719-44ad-b050-f3f7551ffac9
