### ISSUE TITLE
In record audit- correction requested modal- the difference of original and correction is not shown

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6225]
**Bug description:**
In record audit- correction requested modal- the difference of original and correction is not shown

**Steps to reproduce:**
1. Login to RA/Registrar
2. Go to Ready to review/ Sent for approval  workqueue
3. Download any record where correction is requested by RA
4. Go to record audit page
5. Click correction requested modal

**Actual result:**
In record audit- correction requested modal- the difference of original and correction is not shown

**Expected result:**
Should show a table of item, original and correction
 
**Screenshot:**

![diff](https://github.com/opencrvs/opencrvs-core/assets/94350336/9fd7bc95-cae6-4bad-8139-d1cdaf165427)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/6959

**Comment by SyedaAfrida** [comment]
this is fixed

![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/84020b47-d3d6-483f-a231-c418ceea91a9)
