### ISSUE TITLE
QR code is currently not working- getting invalid QR for all certificates

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6230]
**Bug description:**
QR code is currently not working- getting invalid QR for all certificates

**Steps to reproduce:**
1. Login to Registrar
2. Print any certificate
3. Scan the QR code

**Actual result:**
QR code is currently not working- getting invalid QR for all certificates

**Expected result:**
QR code should be working
 
**Screen record:**
![invalid qr](https://github.com/opencrvs/opencrvs-core/assets/94350336/73af187e-b273-471c-97e4-c41dd51affb0)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Nil20** [comment]
This is related to fetch registration refactoring(getRecordById) which is not available in 1.3.1.  @euanmillar

**Comment by euanmillar** [comment]
Thanks!

**Comment by SyedaAfrida** [comment]
This ticket is fixed 


![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/2652043e-447d-4295-bf4f-6055ad567278)
