### ISSUE TITLE
In send for approval workqueue, on clicking download should have retrieved action rather than assign

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6234]
**Bug description:**
In send for approval workqueue for records with correction requested status, on clicking download should have retrieved action rather than assign. Currently In send for approval workqueue for records with correction requested status, the record gets assigned

**Steps to reproduce:**
1. Login to RA
2. Correct any record from Ready to print workqueue
3. Click Send for approval
4. Click download and observe

**Actual result:**
- Assign modal appears
- In history shows assigned action
- When the record is viewed by Registrar, shows the record is assigned to RA

**Expected result:**
- The record should be retrieved
- When the record is viewed by Registrar, the record should not be assigned to anyone

 
**Screen record:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/957f4fed-2547-4516-981c-27f0d2f5dfaf

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@Zangetsu101 please review this ticket before assigning this ticket to any developer as it is related to design

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/7007

**Comment by SyedaAfrida** [comment]
This bug is fixed For RA when record is in correction requested status

https://github.com/opencrvs/opencrvs-core/assets/94350336/0c8f0295-91c2-407c-92c3-8b1f6b7a24b9

But this broke the retrieve functionality of FA. FA should be able to retrieve Records in Sent for review and Requires update tab

https://github.com/opencrvs/opencrvs-core/assets/94350336/5c297f36-dada-4cb7-b8b7-ba1cd19f1ae7

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/7124

**Comment by SyedaAfrida** [comment]
This ticket is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/3855dee7-7abf-47b3-93ce-7a91a178a8e2
