### ISSUE TITLE
Platform refactor: Workflow state transition

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6244]
Express the status diagram as code in workflow: https://www.figma.com/file/MpIAfLSCAGAVKBbciSNHrT/Status-WorkFlow?type=whiteboard&node-id=0-1&t=p91wzyMN5VuB4o6X-0 and exhaustively using the same naming convention in the Audit tab of this doc: https://docs.google.com/spreadsheets/u/0/d/1ZKYmYTj9qd9vG1jbcNVXFw0GeZGL0xk5pD8c8UaxsZ0/htmlview?pli=1#

This document outlines our technical progress on this task:

[State transitions progress ](https://www.notion.so/State-transitions-progress-d875303f269a400ba6497d06ae134110?pvs=21)

- [x] Merge the new-validated & validated events - tameem
- [x] send full record to search instead of task bundle - ashikul
- [x] move duplicates updates in hearth from search to workflow - tahmid
- [x] clean up detect event and openhim related stuff
- [x] Update country config calling openhim on confirm registration, make it to call workflow instead
- [x] forward timeLoggedMs & comment value from gateway to different events - ashikul
- [ ] state diagrams

**Comment by Nil20** [comment]
State diagrams: https://github.com/opencrvs/opencrvs-core/pull/6603
