### ISSUE TITLE
Download CSV of all staff for update comms

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6245]
During deployment / upgrades in progress applications can get lost

Solution is a button in UI for National System Admin, to download a CSV of all staff’s details so they can mass broadcast the comms: “ message all staff 1 week before an upgrade to make sure that all drafts are submitted through the outbox before the upgrade date.  ”

**Comment by rikukissa** [comment]
Good idea, makes it easier to implement as well. I think that still fulfils the requirement, doesn't it?

**Comment by euanmillar** [comment]
@rikukissa BCC is limited to 500 recipients in Gmail I just discovered.  I wonder how that would affect our design as other accounts may have less.  Sorry, maybe not such a good idea after all

**Comment by rikukissa** [comment]
I believe it could still work as a low-effort MVP. If an organisation has, for instance, over 200 OpenCRVS users, not to mention 500, they would likely already have an established messaging channel or some sort. It also becomes a question of if on that level, OpenCRVS should be used to inform the employees. 

Another option would be an announcement feature in the app. Or an inbox of some sort.

**Comment by euanmillar** [comment]
@jpye-finch what do you think about this?

**Comment by jpye-finch** [comment]
This ticket is to be deprioritised. Archive @eduffus ?

Instead we will create a simple messaging ui to send comms to all users email address
https://github.com/opencrvs/opencrvs-core/issues/6410

**Comment by euanmillar** [comment]
Closing in favour of #6410
