### ISSUE TITLE
Registrar of any location should be able to review a correction request 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6247]
**Bug description:**
Registrar of any location should be able to review a correction request 

**Steps to reproduce:**
1. Login to RA
2. Send a correction request
3. Login to a Registrar of another location
4. Search that record
5. Observe Review button from both Workqueue and record audit page

**Actual result:**
- Review button only available in workqueue, not in record audit page
- Registrar see view page with no change link/ approve/ reject button

**Expected result:**
- Review button should show both in workqueue and record audit page
- Registrar should be able to approve / reject correction request

 
**Screen record:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/db45d714-acbb-48d8-ab67-05be6f31bfb3

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
Review button should  be available in both workqueue and record audit page

**Comment by SyedaAfrida** [comment]
This ticket is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/7a6dbab8-6df0-44c9-bc3d-61301804f6fe

**Comment by SyedaAfrida** [comment]
This bug is fixed but got broken for RA. When RA search their correction request record, from workqueue they are able to assign and review their record. However  since the record is in sent for approval , they should be able to retrieve and not review. This  bug is  only  for workqueue , not record audit

https://github.com/opencrvs/opencrvs-core/assets/94350336/0683b704-1490-4343-8816-42757b27b4fb

**Comment by euanmillar** [comment]
@tahmidrahman-dsi can you look at this please?  It appears there is a bug in the solution you worked on.

**Comment by tahmidrahman-dsi** [comment]
Thanks @euanmillar i am on it

**Comment by tahmidrahman-dsi** [comment]
fix: https://github.com/opencrvs/opencrvs-core/pull/7226

**Comment by SyedaAfrida** [comment]
**Bug:** This bug in RA is fixed for basic search, but still there for advance search


https://github.com/opencrvs/opencrvs-core/assets/94350336/10adf609-3c8f-4321-88c5-d9a72f6ff760

**Comment by SyedaAfrida** [comment]
This ticket is fixed

https://github.com/opencrvs/opencrvs-core/assets/94350336/f37a920e-1178-4121-8583-69f2a34a6e84
