### ISSUE TITLE
Feature flags, and first flag to disable print review page

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6250]
Feature flags are a standard practice that allows us to hide functionality from some or all users. In our context, this could for instance mean making a feature only available in the Cameroon environment even when it’s shipped to everyone using 1.3.0. Feature flags also allow us to disable functionality in production if we for instance encounter a critical bug.  

From a development process point of view, a clear benefit is also that we can merge code in before we intend to release it thus allowing the developer to move onto their next task faster with reduced number of stale code branches and context switching.

## Technical design

- [ ] In Farajaland implement the following structure for toggling features on and off

`src/api/application/application-config-default.ts`

```ts
FEATURES: {
  INFORMANT_SIGNATURE: true,
  MARRIAGE_REGISTRATION: true,
},
```
- [ ] In gateway, client and config service update queries and types
- [ ] Replace the current conditional logic of `MARRIAGE_REGISTRATION`, `INFORMANT_SIGNATURE`, `DEATH_REGISTRATION` to user the new feature flags
- [ ] Make "Print declaration" controllable with feature flags

### Known corner cases

- If user is offline and feature is toggled, they will still see it in the previous state

### Next iteration

- Consider https://github.com/Unleash/unleash

**Comment by euanmillar** [comment]
We are going to refactor application config settings a bit, without a migration reqd.

**Comment by Zangetsu101** [comment]
hm we have the option to disable it now but perhaps we want to keep it enabled for Farajaland?

**Comment by SyedaAfrida** [comment]
This ticket is fixed
