### ISSUE TITLE
Update Farajaland cert design to include multiple fonts, custom questions and a data layout more like Somalia

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6260]
Designs to Farajaland Birth, Death and Marriage certificates:
https://www.figma.com/file/fOUJWiaqHcOAwj2qaXV2w4/Farajaland?type=design&node-id=1034%3A1691&mode=design&t=Yi9QO6CiSxf2ck7D-1

Fonts:
Noto Sans Normal
Noto Sans Bold

![Image](https://github.com/opencrvs/opencrvs-core/assets/46478402/c70c3542-fc81-4777-9439-ea2b4ad79117)
![Image](https://github.com/opencrvs/opencrvs-core/assets/46478402/1b1313f6-9844-442e-bea8-c3099422bf6b)
![Image](https://github.com/opencrvs/opencrvs-core/assets/46478402/43e98e4d-01e5-43ac-992a-c6723b67e601)

**Comment by rikukissa** [comment]
@jpye-finch please upload the content and links for this so Ashikul can get started

**Comment by euanmillar** [comment]
@jpye-finch we need to add the custom form field "Number of dependants" into the death certificate so that we know that custom fields are always supported in certificates for catching any regression bug.

**Comment by euanmillar** [comment]
We are going to have a form question, "Reason for late registration", which we will check the birth date and time required for late / delayed registrations.

@jpye-finch can you think about the A/C please, e.g.
Given that the date of birth plus (days to current date) is greater than either LATE / DEAYED time, then show this field

**Comment by SyedaAfrida** [comment]
This ticket is tested


[dea.pdf](https://github.com/opencrvs/opencrvs-core/files/14279689/dea.pdf)
[bir.pdf](https://github.com/opencrvs/opencrvs-core/files/14279690/bir.pdf)


[mar.pdf](https://github.com/opencrvs/opencrvs-core/files/14279691/mar.pdf)

custom fields will be tested in different ticket
