### ISSUE TITLE
Stop Sentry being spammed with Unauthorised and similar errors

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#6263]
Errors that are not unexpected should not end up in Sentry. This is important because false positives hide actual issues and we stop taking user exceptions seriously. 

![Image](https://github.com/opencrvs/opencrvs-core/assets/1206987/64974fdf-b7ea-489a-9931-f978e9ba32cd)

One way to reproduce the issue:

1. Login as a National system admin
2. Go to Users page
3. Invalidate your authorisation token by for example, removing a character from it. Reload page.
4. Verify your url looks like http://localhost:3000/?lang=en&redirectTo=/team/users?locationId=a7c74ecf-db6c-4421-b4e2-71c75b11da8d
5. Login in with a field agent and at least in deployed environment, the GraphQL errors you'll receive will trigger errors

**Comment by euanmillar** [comment]
Also this: https://opencrvs-foundation.sentry.io/issues/4625211684/?project=5830610&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=3

**Comment by euanmillar** [comment]
Finally this: https://opencrvs-foundation.sentry.io/issues/4603404227/?project=5830610&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=5

**Comment by tahmidrahman-dsi** [comment]
@Zangetsu101 should we rebase https://github.com/opencrvs/opencrvs-core/pull/6362 to `release-v1.3.3` ?

**Comment by rikukissa** [comment]
Looking at the changes, the potential regression impact should be small. Do we all agree?

**Comment by Zangetsu101** [comment]
Sounds good to me
