### ISSUE TITLE
In countries that dont have a phone number, the metrics microservice throws this Sentry error

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6277]
# Error
 
POST /audit/events

Unable to retrieve user mobile number. Error: 401 status received

https://opencrvs-foundation.sentry.io/issues/4660822118/events/cbaa595ecfae4443ac68d3f532140eb0/

**Comment by rikukissa** [comment]
# Error
 
POST /audit/events

Unable to retrieve user mobile number. Error: 401 status received

**Comment by rikukissa** [comment]
@euanmillar do you see the Details for this in Sentry. I only see this 
<img width="1670" alt="image" src="https://github.com/opencrvs/opencrvs-core/assets/1206987/f15588cd-fd13-4748-9bcd-528815802364">

**Comment by euanmillar** [comment]
@rikukissa I will move this to Niue and find a fix for it if one is required in core.  Closing for the time being.
