### ISSUE TITLE
Handle administrative changes / Re-assign registrations & users to a different office when admin structure changes

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6329]
Political decisions are made regarding administrative boundary changes where in just a few days staff have new offices and registration locations can no longer exist.

We need to discuss the best approach for administrative changes in the application, regarding what to do with legacy (old registrations must retain links to the old location) / in-progress registrations, how do affected staff move offices / changes to performance metrics / dashboards etc.

Operationally staff comms may be required

### Goal 1: enable fixing incorrectly seeded reference data 

So in other words, make it possible to "override" existing details. In this workpiece we build the foundation for temporality of Locations. 

- [ ] Decide how validFrom and validUntil should be represented in FHIR. 
- [ ] Create a MongoDB view `locations` that combines Location and Location_history to a simplified Location model (id, name, type, parent, validFrom, validUntil, isActive)
- [ ] Build an encapsulated "office resolver" that you can supply a location id and it returns a list of office ids and validity periods under the location. `(locationId: LocationID) => Array<{locationId: LocationID, validFrom: Date, validUntil: Date}>`
- [ ] Refactor full paths to be leaf references in ES, InfluxDB
  - Performance and record searches should now be 
- [ ] Write support for country configs location API to read and serve new columns found in country config location CSV: validFrom, validUntil. Both fields are optional.
- [ ] Write logic to OpenCRVS startup: 
  - If any item of location list has changed:
    - if country config API does not provide `validFrom`, we assume it's the same as originally
    - if country config API does not provide `validUntil`, we assume it's the same as originally
    - First invalidate the existing location by changing its status to `inactive` and validUntil date to supplied validFrom date
    - Then write a new location with the details given by country config
  - If items have been added: create a new location
    - `validFrom` - default if not exist: 1/1/1970
    - `validUntil`- default if not exist: 1/1/3000
  - If items have been removed: invalidate the existing location by changing its status to `inactive` and validUntil to current date

**Comment by euanmillar** [comment]
New MOSIP Location wrapper should give us legacy location capability

**Comment by euanmillar** [comment]
There’s a source data bug in Cameroon where an office has been placed under a wrong municipality. So we need to change the partOf of the office.
We have also identified it’s not enough to only make this change as we have other references to the “full path” from office all the way to the country, so for instance in ES we have
"declarationLocationId" : "3e0c04e5-0750-4cc1-9739-0f8e1d81eb1c",
"declarationJurisdictionIds" : [
  "3e0c04e5-0750-4cc1-9739-0f8e1d81eb1c",
  "885ecced-16f3-4465-b184-9565021c5d7d", <- this is wrong
  "19fb296b-fe43-4dd7-9680-5841135511c6",
  "abde49fc-4d6f-4290-abeb-ab1f41b4f7b6"
],
So places we need to update:

- hearth-dev.Location -> partOf needs to be updated for the office
- hearth-dev.PractitionerRole -> location
- task.extensions
- user-mgnt.users -> user catchment areas need to be updated
- "catchmentAreaIds" : [ "3e0c04e5-0750-4cc1-9739-0f8e1d81eb1c", "885ecced-16f3-4465-b184-9565021c5d7d", "19fb296b-fe43-4dd7-9680-5841135511c6", "abde49fc-4d6f-4290-abeb-ab1f41b4f7b6" ]
- ES -> ocrvs index
- Influxdb measurements
- Metabase

Elastic index should not need migration but instead a admin UI button “reindex record”
InfluxDB should work the same
We should always only save leaf level ids, not the full path (including search and metrics)
A primary database with foreign key references would help a lot

**Comment by rikukissa** [comment]
Initial thoughts:
- Locations might one day be fetched from an API. Let's encapsulate it somehow

**Comment by rikukissa** [comment]
Playground for validity period behaviour
https://docs.google.com/spreadsheets/d/1F9_3loWLe57vzikYGRHFNePuFXo8j5ngNxRVsRlDPfQ/edit#gid=0

**Comment by rikukissa** [comment]
Closing this in favour of:
- https://github.com/opencrvs/opencrvs-core/issues/6679
- https://github.com/opencrvs/opencrvs-core/issues/6691
