### ISSUE TITLE
Rich form field configuration – PII, analytics, identifiers...

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#6372]
Make it possible for the backend to connect an input datapoint with its original field definition. This enables counties to configure fields

```ts
{
  fieldId: 'child.nationalId',
  deduplication: {
    unique: true
  },
  allowCorrection: false,
  pii: true,
  identifier: true,
  identifierType: 'NID'
},
{
  fieldId: 'mother.educationLevel',
  allowCorrection: true,
  pii: false,
  statistic: true
}
```

### Why this is important
Overall, this will reduce core's reliance on forms fields and allows more dynamic form creation and different type of forms without a Medium+ development project. 

In the long term, this will enable countries for example to
- Allow selecting which fields can be corrected
- Mark form fields are PII. This will also enable us to build integrations where PII is removed before data gets sent. 
- Define which fields to use as identifiers (passport, NID). This would enable countries to add more ID types without core changes.
- Specify fields that are stored for statistics purposes. These could be made different per country.
- Define how custom fields should be converted to FHIR

Related:
- https://github.com/opencrvs/opencrvs-core/issues/6330

**Comment by rikukissa** [comment]
Changing this to an experiment so we get this moving quicker

**Comment by euanmillar** [comment]
@rikukissa do you want to combine this ticket with #5651 and a ticket related to #7052 ?

**Comment by rikukissa** [comment]
I think we can even close this now that we have a better definition for what those "rich features" would be
