### ISSUE TITLE
If user has an invalid language in their query parameters when logging in, default to default language

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#6379]
Small thing, but in Cameroon someone managed to have "jy" in the language parameter which broke the app

**Comment by SyedaAfrida** [comment]
this ticket is not fixed yet

![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/c81a3673-9fac-415e-af29-31b372c6ba62)

**Comment by SyedaAfrida** [comment]
This bug is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/3c34a20c-ff6a-4a9f-b4c1-b5677b8cb145
