### ISSUE TITLE
Mass email to all users

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6410]
### Description
- Adds a simple messaging box for a National System Admin to send a custom email to all user
- Messages are sent via email to users
- If configuration does not use emails. Then feature is disabled
- [Custom message is added to the template {{body}}](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=18752%3A9869&mode=design&t=gEOwhmLgKQzyils1-1)
- This is an important feature to ensure that Nat Sys Admin can warn users to complete draft declarations before a system upgrade (when they will be lost).

### Acceptance criteria

GIVEN I am a National System Admin
WHEN I click on the side menu item 'Communications' > 'Message all users'
THEN load the Message all users page

GIVEN my configuration does not use email
THEN hide the menu option from the side nav

GIVEN I am a National System Admin
WHEN I add a custom message
THEN enable the send button

GIVEN I am a National System Admin
WHEN I click send
[THEN show the confirmation Dialog](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=18752%3A8476&mode=design&t=gEOwhmLgKQzyils1-1)

GIVEN I am a National System Admin
WHEN I click confirm
THEN close the dialog box and show the confirmation toast "Email sent to all users"

GIVEN I have already sent an email 
WHEN I add a new message AND click send
THEN show the error toast "Only one email can be sent per day"

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=9778%3A63926&mode=design&t=J1zv7FQGrE6I2rTs-1

### Dev tasks

Tech design: https://www.tldraw.com/r/jkv9vQVq9T7T176KgNubU?viewport=576,-4087,4125,2010&page=page:page

Please consider, what are the responsibilities of country config and notification-microservice:

- **notification**: queueing, sending the notification to country config, handling the (error) response
- **country config**: 'dumbly' sends the notifications
- The notification-service doesn't need to know about the exact templates country config has: https://github.com/opencrvs/opencrvs-core/blob/e0d02579c4fc6751338e620da368d763afdeeee5/packages/notification/src/i18n/messages.ts#L27 It should only emit events with a `Record<string, any>` payload.

Dev tasks:

- [x] Create the UI for the form, popup and toast notifications
- [x] Create a gateway query to forward the request to notification. Fetch all the users from user-mgnt. Return success or backend failure to client to display success or failure toast
- [x] Inside the notification service, create an endpoint which takes a list of emails in, which were fetched in gateway. Create a "queue" database to store the subject, message, bcc list for max 500 users in a row at a time. Then return success or failure to gateway on any db error
- [x] Create generic all staff email endpoint in countryconfig service to recieve an email with BCC list, returns a 200 or 500 error if email cant be sent
- [x] notification service will loop through the queue and dispatch the email to countryconfig microservice for the last row in the database. If a 200 is received from the countryconfig service, remove the row from the database.
- [x] If any error occurs in notification / countryconfig service then send a Sentry error
- [ ] Add a count in gateway redis to prevent forward mail request more than once a day

**Comment by eduffus** [comment]
@jpye-finch need acceptance criteria based on large numbers of users.

**Comment by eduffus** [comment]
@jpye-finch added additional description point: 
- This is an important feature to ensure that Nat Sys Admin can warn users to complete draft declarations before a system upgrade (when they will be lost).

**Comment by euanmillar** [comment]
@eduffus @rikukissa It may be that bulk email configuration is different for each provider e.g. SendGrid or Office365.  I think that the emails should be sent as a scheduled task and from a queue handling timeouts.  Refer to my Slack message regarding a notification database for all messages.  We need to know if emails fail to send. I think that this could be a larger task than we anticipate to guarantee as an AC that potentially 1000s of staff members can be successfully contacted.  It would also be very difficult to QA in bulk.

**Comment by jpye-finch** [comment]
@ed @euanmillar Yes my last (placeholder) AC. Only being able to send one email a day or when the current email had finished being sent to all users. Was with regards to 'large numbers of users'.

**Comment by rikukissa** [comment]
It sounds like we've landed on National System Admin a message to **all** users of which there can be anything between 1 and infinity. I'm just explicitly stating this as there is a significant difference in complexity sending the message to 1000 employees compared to sending it to 5000+ employees. What's the maximum number of employees a country can have in the, let's say next two years?

In terms of design, how does the system admin know if sending the email failed? 1000 emails we can send right away and show them a banner indicating if it failed or not. For 10 000 we need to have an additional view where they can check up on the progress of the submission and resend them (?) if it fails.  @jpye-finch @euanmillar

**Comment by tahmidrahman-dsi** [comment]
@jpye-finch @rikukissa what should be the sender's email address? Is it the National System Admin's one or the one with `no-reply`?

**Comment by rikukissa** [comment]
@tahmidrahman-dsi it needs to be `SENDER_EMAIL_ADDRESS` defined in country config. It's best if we again reuse the same sendEmail mechanism and endpoint available in country config

**Comment by tahmidrahman-dsi** [comment]
Thanks @rikukissa , I used `SENDER_EMAIL_ADDRESS` in country config

**Comment by SyedaAfrida** [comment]
**Bug:** All the text in message appears in 1 line in email. Should be separate lines as provided in message edit text.





https://github.com/opencrvs/opencrvs-core/assets/94350336/dc9e5469-d058-4488-98ec-5f0c4038fa74

**Comment by SyedaAfrida** [comment]
This ticket is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/7b699135-27f2-4a96-a4f8-1f483862e36d
