### ISSUE TITLE
Write a script that removes any unused copy in the client and login application from client.json & login.json

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6415]
### Description

I wrote a script to generate Excel files for all the application content here: https://github.com/opencrvs/opencrvs-farajaland/pull/810

However it is a manual task to remove unused copy from the client.json & login.json every time front-end code is deprecated.  Can this be automated somehow in a pre-commit hook, or when publishing a release?

### Dev tasks

- [x] Ensure there are no places in the client code where a `MessageDescriptor` is generated dynamically
- [ ] Revisit `yarn extract:translations`. Verify the script yields identical number of language items found with editor search. Make the script output the found language items as JSON in stdout. 
- [ ] Write a script in country config that calls yarn extract:translations and makes changes to the CSV files in country config accordingly by adding and removing items and updating descriptions.

**Comment by rikukissa** [comment]
Implemented here as a `--outdated` flag and warnings about dynamic message descriptors. We still have a few of these do unused copy cannot be fully removed automatically.
https://github.com/opencrvs/opencrvs-core/pull/6630
