### ISSUE TITLE
Log the notification payload properly instead of [object Object]

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#6418]
https://github.com/opencrvs/opencrvs-core/blob/366bd0577f39e376bbdc0c5dad813d0d54aa1e61/packages/notification/src/features/sms/service.ts#L34
Here the actual log is ```{"level":30,"time":1704874899079,"pid":28,"hostname":"1baf6d22804e","msg":"Sending the following message: \"[object Object]\" to [object Object]"}``` which should be more informative or the Object log should be removed.

**Comment by naftis** [comment]
@euanmillar Yep. The actual log here could print the template name but recipient should be hidden.

**Comment by euanmillar** [comment]
@naftis @rikukissa  It seems incredibly minor then.  Can we just remove this log?  I dont know what purpose it serves if we are hiding the payload.

**Comment by rikukissa** [comment]
There needs to be some indication that an email was sent in the logs. Let's print the template name and for instance a `rik*********.org` so that an implementer can see and verify the alerts email is configured properly

**Comment by Zangetsu101** [comment]
Completed in #7204
