### ISSUE TITLE
Remove all PII from logs.

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#6419]
### Description

Currently we have a lot of log items with PII:
```
"Notification service sendBirthRegistrationConfirmation calling sendSMS: {\"recipient\":{\"sms\":\"+237673479737\",\"email\":null},\"informantName\":\"zy x\",\"name\":\"asdfasdf\",\"trackingId\":\"x\",\"registrationNumber\":\"y z\",\"crvsOffice\":\"asdf\",\"registrationLocation\":\"xxx\"}"}
```

Log files are not secured or access restricted for PII storing purposes. What makes this even more critical is there are users' username and passwords printed in clear text in the notification service logs.

```
{"level":30,"time":1703148856148,"pid":28,"hostname":"1baf6d22804e","msg":"Username: <<REDACTED>>"}
{"level":30,"time":1703148856148,"pid":28,"hostname":"1baf6d22804e","msg":"Password: <<REDACTED>>"}
```

### Sources

- https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html

### Dev tasks

- [ ] Go through QA server logs and find places where we might be printing out PII
- [ ] Look at logger definitions in our codebase. Flag places where we might be printing out PII
- [ ] Replace PII with `<REDACTED>` or similar.
- [ ] Use pino's `redact` to remove
     - req.headers.x-forwarded-for
     - req.headers.x-real-ip
     - req.headers.authorization
     - req.removeAddress

**Comment by naftis** [comment]
We need to understand what PII is, to be able to filter it out correctly. In the following examples, I will classify any data that can on its own be linked to an individual. In case the server logs leak, there is information that can and cannot be linked to a specific person.

| Type of information | Needs to be filtered out | Reason | Further explanation |
| ------------------- | ---------------------- | ------------- | ------------------- |
| IP address          | ✅                           | PII       |                     |
| Name         | ✅                               | PII   |                     |
| Address         | ✅                             | PII     |                     |
| Email, SMS | ✅                               | PII   |                     |
| Username | ✅                               | PII   | In OpenCRVS, usernames are based on first and last name                    |
| Password | ✅ | Sensitive user-owned information, (PII) | PII: Could be linked to a person via non-OpenCRVS password breaches too? |
| User UUID | ❌ | | Cannot be linked to a person on its own without access to a OpenCRVS instances database |
