### ISSUE TITLE
Cannot  preview and print marriage certificate

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6421]
**Bug description:**
cannot  preview and print marriage certificate

**Steps to reproduce:**
1. Login to RA/ registrar
2. Go to Ready to print
3. Download any marriage certificate
4. Go to certificate preview page

**Actual result:**
cannot  preview and print marriage certificate

**Expected result:**
should be able to preview and print marriage certificate

**Screenshot:**
![marr](https://github.com/opencrvs/opencrvs-core/assets/94350336/13340ec0-0141-48a2-aea5-8bd1a5688797)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by euanmillar** [comment]
@rikukissa  Developer must include documentation on how fonts must be treated on certs in comments on this ticket so we can add to docs.

**Comment by SyedaAfrida** [comment]
This bug is fixed
https://www.loom.com/share/aa3fa368bc444021bf7b0865bc744a16?sid=420f59d8-2dc7-4286-ba05-90d78ca6b6bf
