### ISSUE TITLE
Remove Heading in place of death in death declaration form

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6423]
**Bug description:**
Remove Heading in place of death in death declaration form

**Steps to reproduce:**
1. Login to FA/ RA/ Registrar
2. Declare a death event
3. Observe deceased details page

**Actual result:**
Heading in place of death

**Expected result:**

![image (11)](https://github.com/opencrvs/opencrvs-core/assets/94350336/3fd5ac05-501e-4e01-a6c2-f00b19f4e9c0)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
@Zangetsu101 Is this bug related to form configuration package?

**Comment by Zangetsu101** [comment]
yes this is related to form configurations. This should be fixed already in QA. Are you still encountering it?

**Comment by SyedaAfrida** [comment]
Fixed in V1.5.0
