### ISSUE TITLE
Remove hardcoded NotoSans blob in core to reduce bundle size

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6438]
### Description

Remove the PDF generation altogether and try if it can be done with SVG. It can first be done with an query parameter ?svgCert=true to toggle between them and to test if there are issues. We can then fully remove the non-SVG PDF generation in case the SVG one works fine.

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

(Link to Figma)

### Dev tasks

- [ ] Task 1

**Comment by Zangetsu101** [comment]
@SyedaAfrida You need to test if the certificates are working as expected for this ticket

**Comment by SyedaAfrida** [comment]
This bug is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/b7a8b2ab-7790-4a76-9beb-ac6e5e68eb2a
