### ISSUE TITLE
We need to update MOSIP integration for MOSIP Connect / MOSIP Collab

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6457]
### Description

Now that we have created the [DCI CRVS API](https://github.com/opencrvs/dci-crvs-api) , we should refactor the [MOSIP mediator](https://github.com/opencrvs/mosip-mediator) and integrate our new MOSIP dev environment at https://login.farajaland-mosip.opencrvs.org with MOSIP's development(Collab / MEC) environment for the MOSIP Connect conference in Addis Ababa: 5th - 7th March 2024.

### Specific Use Case/Flow:

The same MEC use case as before with no changes:

https://vimeo.com/831177256

![Image](https://github.com/opencrvs/opencrvs-core/assets/3169954/0883b760-ad15-40e3-8210-06f3d364ca2c)

### Environment for running the demo.

Development environment:

OpenCRVS on OpenCRVS Digital Ocean integrating with MOSIP Collab

Production environment:

OpenCRVS on MOSIP AWS integrating with MOSIP MEC

Ownership for setup and configuration of the environment.

Technical: Mono, Euan & Pyry
Admin: Sanchi re UINs: https://docs.google.com/spreadsheets/d/12oR5bIVF2rpBnAaeraZUEccD9ETh3EEX9C1q4dwghYM/edit#gid=390392985

### Establish key milestones for the development, testing, and deployment of the demo.

OpenCRVS aim to have Collab updated with OpenCRVS v1.4 by Monday 19th February to begin QA
OpenCRVS aim to upgrade the MEC environment with OpenCRVS v1.4 by Monday 26th February

### Dev tasks

- [x] If you care about git history, you may need to revert the [opencrvs-mosip](https://github.com/opencrvs/opencrvs-mosip) repo on develop branch to commit https://github.com/opencrvs/opencrvs-mosip/commit/0bc3ed47e71f8e1133876fcb046a6c5a0e2d5cda and pull in latest updates from Farajaland release-v1.4.0 branch ... or alternatively just pull in latest changes from 1.4.0 branch.
- [x] Update [mosip-mediator](https://github.com/opencrvs/mosip-mediator) so that it can login with the new OAuth flow to subscribe to the webhooks.
- [x] Update the [opencrvs-mosip](https://github.com/opencrvs/opencrvs-mosip) reference data (admin structure) to match the MEC reference data: https://github.com/opencrvs/opencrvs-mec/blob/develop/src/features/administrative/source/mosip-mec.csv.  In the copy / app settings we may need the country to be set to India instead of Farajaland
- [x] Fallback: Test of the current MEC end-to-end flow in a call.
- [x] Update opencrvs-mosip repo development environment Ansible scripts & [docker compose](https://github.com/opencrvs/opencrvs-mosip) to include deployment of mosip-mediator & mosip-token-seeder.  Will require some certs for mosip-tokens-seeder and API access to MOSIP's environment from mosip-mediator.  **Need Mono's assistance**. Integrating from OpenCRVS on DIgital Ocean to the MOSIP Collab environment
- [x] Update opencrvs-mosip repo Ansible scripts so that we can differentiate between privisioning on Digital Ocean versus AWS production.  SSH user for example will be different.  Check the Ubuntu version as we may need to change some Ansible commands in production.  Create a production environment in the repo and update production [docker compose](https://github.com/opencrvs/opencrvs-mosip) to include deployment of mosip-mediator & mosip-token-seeder.  Will require some certs for mosip-tokens-seeder and API access to MOSIP's environment from mosip-mediator.  **Need Mono's assistance**. Integrating from OpenCRVS on AWS to the MOSIP MEC environment
- [x] We need to update the birth & death forms (maybe also marriage?) in [opencrvs-mosip](https://github.com/opencrvs/opencrvs-mosip) repo to replace the National ID questions with the Authorize button to have E-Signet intregration for mother, father, informant, deceased, bride & groom.
- [x] Pyry, Euan, Riku, Ed & Annina may need a MOSIP wireguard API to be able to access the Collab & MEC MOSIP Health UI and E-Signet apps. **Need Mono's assistance** - Euan to email Mono with request.
- [x] E-Signet 6 digit codes & MOSIP NID card PDF's should email to a new Gmail alias that then redirects to the #sentry-mosip Slack channel so that everyone can see them.
- [x] We need a lot of updated UINs for birth & death forms for mother, father, informant, deceased for Collab & MEC: https://docs.google.com/spreadsheets/d/12oR5bIVF2rpBnAaeraZUEccD9ETh3EEX9C1q4dwghYM/edit#gid=390392985
- [x] Pull in certificate upgrades in release 1.3.3
- [x] Update the application name. Do the state / locality / translations be updated similarly [as in MEC](https://github.com/opencrvs/opencrvs-mec/commit/e09b8440e1d56ef86a6b805c41747632b8fcfaa8) ?

REFACTOR - IF TIME IS AVAILABLE:

- [ ] For birth integration, previously we had an [endpoint](https://github.com/opencrvs/opencrvs-farajaland/blob/develop/src/api/mediators/mosip-openhim-mediator/handler.ts) in Farajaland to recieve the MOSIP Application ID.  Instead the mosip mediator should be called by the event-registration endpoint in countryconfig.  The event-registration endpoint in this case should not call the confirm registration URL in workflow.  The mosip mediator should call confirm registration URL in workflow.  In workflow we need to add the MOSIP_PSUT_TOKEN_ID, and MOSIP_AID as additional identifiers that can be received here.  Then in workflow we add MOSIP_PSUT_TOKEN_ID to the child and MOSIP_AID to the task in the same way as the mosip-openhim-mediator does in Farajaland.  Then we can delete mosip-openhim-mediator and delete any MOSIP webhook calls.
- [ ] For death integration, our request to mosip-token-seeder is [hardcoded to link the birth and death records together](https://github.com/opencrvs/opencrvs-core/blob/94763edac40561c0fb11eb2b973825c429c1df5f/packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts#L804) in the workflow microservice.  Is this something we want to refactor as we need a universal approach to link all events in future for tickets such as #3947 ?  Lets discuss with Riku.
- [ ] We can then officially release mosip-mediator and reply to this discussion: https://github.com/opencrvs/opencrvs-core/discussions/6395
- [x] Deprecate any mention of OSIA in system integration UI
- [x] Document the mosip integration process in gitbook

**Comment by naftis** [comment]
For E-Signet / NID integration for Collab, we need these environment variables from Mono:
```
NATIONAL_ID_OIDP_CLIENT_ID=abcd3-....
NATIONAL_ID_OIDP_BASE_URL=https://idp.collab.mosip.net/v1/idp/
NATIONAL_ID_OIDP_REST_URL=https://api.collab.mosip.net/v1/idp/
NATIONAL_ID_OIDP_CLIENT_PRIVATE_KEY=<<base64 encoded JWK>>
NATIONAL_ID_OIDP_JWT_AUD_CLAIM=https://api.collab.mosip.net/v1/idp/oauth/token
```

**Comment by naftis** [comment]
https://github.com/opencrvs/opencrvs-core/issues/6457
When Collab environment is running again, please re-check this PR: https://github.com/opencrvs/opencrvs-core/pull/6535

**Comment by naftis** [comment]
The MEC installation can now be continued as the Collab environment is working. I'm currently pending new keystore credentials from MOSIP to continue configuring the environment. 

Pending dev work that still needs clarification and prioritization are:
- address restructuring/unification work
- refactoring mosip-mediator to not directly need to modify the FHIR bundles via countryconfig/OpenHIM. Also necessary for 1.5/1.6 as OpenHIM is getting deprecated?
- streamlining the integration installation by simplifying some of the needed keys, there are duplicates between the services, just in different formats. 
- Nice to have: refactor the E-Signet/OIDP-integration so, that the `redirectUri` actually redirects the user to **countryconfig** and we could have a way between countryconfig/core to add details to a declaration draft. This would make the integration more re-usable

@euanmillar

**Comment by euanmillar** [comment]
Closing as stale
