### ISSUE TITLE
Refactor First name(s) into optionally 2 fields Given and Other

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#6469]
We currently do this:

First name(s): EDWARD JAMES ARTHUR
Family name: DUFFUS

In the back end we separate first name by space and put this into the FHIR HumanName (given) Array like this:

given: [
"EDWARD","JAMES","ARTHUR"
],
family: "DUFFUS"

But Uganda want this:

First name: EDWARD
Middle name: JAMES ARTHUR
Family name: DUFFUS

- [x] So we need to amend the First Name transformers, type-resolvers and fhir-builders to only have 2 strings rather than separate by space
- [x] We need a migration to change old databases
- [x] We have a few pages in the app like NID check, audit where the full name is displayed, so we need one function that always does the name handling in all places.

Do we need to have this as an application configuration option, if we update the create / edit user fields in the same way?

**Comment by Zangetsu101** [comment]
What to do about "OTHER" collector form?

**Comment by SyedaAfrida** [comment]
**Bug:**
If a record is submitted with only first name and middle name then the record goes to waiting for validation status
https://www.loom.com/share/a67cdcfb953b4b26af7832568a4c2c1e?sid=2a4f8162-5ebb-4fdc-abdb-8ad7e9085c26

1. While processing in outbox only first and last name are shown
2. If last name is not provided, record do not appear in workqueue
3. When searched found in different status in workqueue and record audit page
4. When searched and go to In record audit page , before assigning shows first name & last name and after assigning shows first , middle and last name

**Comment by Zangetsu101** [comment]
@SyedaAfrida I've deployed the fixes to the Uganda environment

**Comment by SyedaAfrida** [comment]
This by is fixed
Tested on: https://login.uganda.opencrvs.org/?lang=en
Version: 1.3.3


https://github.com/opencrvs/opencrvs-core/assets/94350336/85f3ec9f-e57d-4e4a-aea5-2ae9a1a4958a
