### ISSUE TITLE
Pagination issue in team when location is changed

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6481]
**Bug description:**
Pagination issue in team when location is changed

**Steps to reproduce:**
1. Login to national system admin
2. Click team
3. Go to 2nd page of any office
4. Change location to any office which has only 1 page

**Actual result:**
shows no users available for that office as it navigates to the 2nd page of that office

**Expected result:**
when location is changed should navigate to the 1st page of the office

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/a8fc26c3-6db4-4e5d-a77a-92e1ca7d61f9

**Environment:**
https://login.farajaland-staging.opencrvs.org/?lang=en
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.3.3,  V1.4.0

**Comment by tiri39** [comment]
This issue is fixed.


https://github.com/opencrvs/opencrvs-core/assets/113257751/dcf9cced-510e-4562-9ba8-f22f3257c144
