### ISSUE TITLE
Consolidate and settle on Ubuntu version

### ISSUE THREAD

**Issue by n1koo** [opencrvs/opencrvs-core#6519]
Currently both on CI and in our documentation we reference various versions of Ubuntu (22.04, 20.04 and latest).

24.04 LTS will be released soon'ish and lets fix all references to that when its out.

This will allow a very long term support without touching the OS version again

**Comment by rikukissa** [comment]
Some existing documentation here: https://app.gitbook.com/o/zub8C4BetmW3a9Bj4Cd4/s/TpMZa3OhuU8OphPGJLBn/servers/upgrading-eol-ubuntu

**Comment by n1koo** [comment]
Seems like Github folks lag behind pretty badly on releases https://github.com/actions/runner-images/issues/9691#issuecomment-2063926929

For short term i'll lock us to 22.04 on everything

**Comment by n1koo** [comment]
Closing this off as we did 22.04 where we could - https://github.com/opencrvs/opencrvs-core/issues/7045 should follow for the upgrade of all-things
