### ISSUE TITLE
In DD and MM field of date of birth/death, if one digit is entered then Reason for delayed/ late registration field do not appear

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6530]
**Bug description:**
In DD and MM field of date of birth/death, if one digit is entered then Reason for delayed/ late registration field do not appear

**Steps to reproduce:**
1. Login to FA/ RA/ Registrar
2. Declare a birth/death event
3. In DOB of Child/ date of death of deceased enter one digit 
4. Observe

**Actual result:**
In DD and MM field of date of birth/death, if one digit is entered then Reason for delayed/ late registration field do not appear

**Expected result:**
Even if one digit is entered in date of birth/death  then Reason for delayed/ late registration field should appear

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/33c4c39e-4172-4b45-a8f1-b7216001788b

**Environment:**
https://login.farajaland-staging.opencrvs.org/?lang=en

**Version:**
 V1.3.3

**Comment by rikukissa** [comment]
https://github.com/opencrvs/opencrvs-farajaland/pull/922

**Comment by SyedaAfrida** [comment]
This bug is fixed


![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/a416fb97-a790-4156-82e7-ddc6444a7e6d)
