### ISSUE TITLE
Fix some issues in setup.sh

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6534]
2 issues with setup.sh script exist, 

1. even if you are using node 20.x.x it says "node version supported", ...
2. the other being it checks if "docker-compose" (which is deprecated) is installed but we require "docker compose" instead.

**Comment by Nil20** [comment]
We seem to have not deprecated `docker-compose` from `1.3.4`.

**Comment by euanmillar** [comment]
This work is just to improve the checks & prompts on what versions of Node & Docker / Compose are installed.

**Comment by Zangetsu101** [comment]
Completed in #6757
