### ISSUE TITLE
When a death record is printed by someone else status becomes certified instead of issued 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6536]
**Bug description:**
When a death record is printed by someone else status becomes certified instead of issued 

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Print a death record
3. Select collector as someone else
4. Print and observe the flow

**Actual result:**
- After printing shows unassigned toast
- Status becomes certified
- Appear in ready to issue workqueue

**Expected result:**

- should not show unassigned toast
- status should be issue

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/66a3e6c4-d45c-4412-973c-5346c843310c

**Environment:**
https://login.farajaland-staging.opencrvs.org/?lang=en

**Version:**
 V1.3.3

**Comment by Nil20** [comment]
Could not reproduce in 1.3.4. This was probably faced because of the unassign issue. 
https://github.com/opencrvs/opencrvs-core/pull/6549 may well have fixed this.

**Comment by SyedaAfrida** [comment]
This bug is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/6dde2c46-c9c9-49cf-a857-714672742995
