### ISSUE TITLE
Recurring per release: review and update Farajaland Configuration

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6552]
This is a re-curring ticket to update the Farajaland configuration to include all new features in the release for a good demo.

**Comment by euanmillar** [comment]
@eduffus @jpye-finch I am confused if this is a feature (if so, can more explanation be given?), or if it is a documentation task.  We have other tickets for configurable user roles and if so can this be combined with that and closed?  Cant really estimate it right now.

**Comment by euanmillar** [comment]
Updated description based on @eduffus feedback

**Comment by rikukissa** [comment]
Regarding this @euanmillar. It would be great for someone in the development team to upgrade Farajaland 1.4.x to 1.5.0 and gather notes of any manual steps a country might need to make

**Comment by euanmillar** [comment]
Closing this as its stale and potentially now covered in process
