### ISSUE TITLE
FA and RA's name appearing in Leaderboard of Registrars 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6571]
**Bug description:**
FA and RA's name appearing in Leaderboard of Registrars 

**Steps to reproduce:**
1. Login to national system admin
2. Click leaderboard
3. Observe

**Actual result:**
FA and RA's name appearing in Leaderboard of Registrars 

**Expected result:**
FA and RA's name should not appear and the calculation of registration should be correct

**Screen recording:**

![image (4)](https://github.com/opencrvs/opencrvs-core/assets/94350336/8290c381-591b-4c0c-aea1-d5d0b0956d75)

**Environment:**
https://login.farajaland.opencrvs.org/?lang=en
https://login.farajaland-staging.opencrvs.org/?lang=en

**Version:**
 V1.3.2,V.14.1

**Comment by tahmidrahman-dsi** [comment]
Could not reproduce in the QA environment, also in local env


![Image](https://github.com/opencrvs/opencrvs-core/assets/42269993/8a27249b-2028-4f5a-9691-77cedc2ce6c2)

**Comment by Zangetsu101** [comment]
Registration agent appeared in leaderboard for registrars after deployment

**Comment by SyedaAfrida** [comment]
RA's name appearing in leadersboard


![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/75f109e1-198b-4b74-bda8-75a4443ba985)

**Comment by tahmidrahman-dsi** [comment]
@rikukissa the query that the view refresher of metrics use is served from here https://github.com/opencrvs/opencrvs-farajaland/blob/develop/src/api/dashboards/queries.ts#L109 .  Ideally, no row should have the value `REGISTRATION_AGENT` in `practitionerRole` column.
One row in the performance database indicates a registration agent registers the declaration. 
https://metabase.farajaland-qa.opencrvs.org/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjozLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjcwfSwidHlwZSI6InF1ZXJ5In0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==
I suspect that somehow the task got updated by a registration agent and that time view refresher ran the query 


![Image](https://github.com/opencrvs/opencrvs-core/assets/42269993/3ae297b5-c0a7-40f7-b92c-93bda6fa148c)

**Comment by SyedaAfrida** [comment]
This bug is fixed in V1.5.0 QA environment

![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/4e86d3ed-5d95-4df8-83f3-8d9bad3a3bc0)
