### ISSUE TITLE
Optimise application package size for faster download on slow connections

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#6575]
### Description

Both the register application and login takes a very long time to download. On slow connections, downloading the application can take long enough for the user to think it is not working at all. This has also happened to us when OpenCRVS has been demoed.

| Package              | Current size | Target size |
|----------------------|--------------|-------------|
| Register application | 9.4MB        | <2.0MB      |
| Login application    | 4.1MB        | <0.5MB      |

### Actions
- [x] Enable gzipping for nginx
- [x] Implement a loading indicator for index.html files

**Comment by manitra** [comment]
The main issue is that there is no "loading icon" while the bundle is  being downloaded. 

So with a 30KB/s download rate, there is a white blank screen during 2 minutes which is insanely long.

Would it make sense to add a static throbber on the app wrapper which would be hidden when the app is loaded on the client side?

**Comment by manitra** [comment]
Okay, there is a continent wide Internet issue currently in west and east Africa. So this small issue became really annoying today 😅

**Comment by rikukissa** [comment]
Indeed, a loading indicator of some sort needs to be added. We need to also investigate what exactly is making the bundles so large. Gzipping configuration seems to at least have been disappeared from Nginx.

**Comment by naftis** [comment]
@jpye-finch We need a loading indicator that appears before the JS bundle has even loaded. I've implemented something similar previously, have a look here: https://codepen.io/naf/pen/rNbjKxg Could you help with the styling?

**Comment by Zangetsu101** [comment]
We have enabled gzip compression for our js bundles & there is a PR open for the loading screen here: https://github.com/opencrvs/opencrvs-core/pull/6894. So we can close this one right?

**Comment by rikukissa** [comment]
Login application is now 737kB and register 2MB. I'm happy with this 👍
