### ISSUE TITLE
Enforce Metabase default admin credentials to be changed

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#6578]
### Description

Modify the Dashboards package in core so that it asks for both the username and password as environment variables and uses these in the `update-database.sh` script and `environment-configuration.sql` file. The existing admin user is updated with these details on startup.

The password should be generated as `bcrypt(<user.PASSWORD_SALT> + <new password>)`

Dashboards service should not start if these are not defined.

**Comment by Zangetsu101** [comment]
@Zangetsu101 will be testing this one

**Comment by Zangetsu101** [comment]
Was able to log into qa with new credentials
