### ISSUE TITLE
Unable to login to Field agent when an incomplete record is previously retrieved by them

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6584]
**Bug description:**
Unable to login to Field agent when a record is previously retrieved by them

**Steps to reproduce:**
1. Login to FA
2. Retrieve any incomplete record
3. Logout
4. Login to RA/ Registrar
5. Change the status of that record (approve/ register)
6. Logout
7. Try to Login to FA

**Actual result:**
Unable to login to Field agent when an incomplete record is previously retrieved by them

**Expected result:**
Should be able to login to Field agent 
**Screen recording:**

![unable login to fa](https://github.com/opencrvs/opencrvs-core/assets/94350336/0cc33dc6-2b2e-4543-a634-39a86adcbb78)

**Environment:**
https://login.farajaland-staging.opencrvs.org/?lang=en

**Version:**
 V1.3.4/ V1.4.1

**Comment by Nil20** [comment]
Fix PR: https://github.com/opencrvs/opencrvs-core/pull/6587

**Comment by SyedaAfrida** [comment]
This bug is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/23735414-0c10-4edc-8d0a-ef756756fa3f
