### ISSUE TITLE
Navigation issue in Registration agent and national registrar

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6589]
**Bug description:**
Navigation issue in Registration agent and national registrar

**Steps to reproduce:**
1. Login to national registrar
2. Click Team, dashboard, statistics, leaderboards
3. Observe
4. Logout
5. Login to RA
6. Click Team
7. Observe

**Actual result:**
1. National registrar is navigated to Performance page
2. RA is navigated to in Progress page

**Expected result:**
1. National registrar should navigated to Team, dashboard, statistics, leaderboards
2.  RA should navigated to Team

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/70d97284-b64d-4d7f-996a-d6dd23ac1549

**Environment:**
https://login.farajaland-staging.opencrvs.org/?lang=en

**Version:**
 V.14.1

**Comment by SyedaAfrida** [comment]
Navigation in national registrar is not fixed yet for dashboard, statistics and leaderboards

https://github.com/opencrvs/opencrvs-core/assets/94350336/a55c63c3-88b5-455f-a6cc-baf751f74bde

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/6598

**Comment by SyedaAfrida** [comment]
This bug is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/f91b48d2-acc7-4876-8c1a-217504c1c78b
