### ISSUE TITLE
Adds handlebar to certificate to hide elements/images on print

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6610]
## Describe the improvement
Some countries use security paper. So the design is not required on the certificate template. This means that on certificate preview. you don't see the final print version.

This ticket is to add a handlebar that hides an element such as a background image. So that on export to PDF. the element/image is hidden

## Acceptance Criteria
GIVEN I have added a background image to show the security paper design
WHEN on the certificate preview page show the image
THEN on click of Print. Hider the background image in the pdf viewer

**Comment by Zangetsu101** [comment]
okay. I know that there is a css property for this. we'll have to figure out whether our pdf library supports it or not you know with SVG rendering and stuff

**Comment by tiri39** [comment]
Not tested on core. 

On Uganda (https://register.uganda.opencrvs.org/) - 

certificate preview page - 

![Image](https://github.com/user-attachments/assets/5b5c3266-1ad6-4caf-91b2-9a824362401a)

pdf, after clicking 'yes, print certificate' - 

![Image](https://github.com/user-attachments/assets/527625c0-dcdf-4aa8-8dc5-49445119e869)
