### ISSUE TITLE
Sometimes complete and incomplete death declaration disappears when submitted 

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6619]
**Bug description:**
Sometimes complete and incomplete death declaration disappears 

**Steps to reproduce:**
1. Login to FA
2. declare a complete/ incomplete death declaration
3. Submit

**Actual result:**
Sometimes complete and incomplete death declaration disappears 

**Expected result:**
should be able to submit any declaration

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/28a3e167-7fef-4b56-b521-1da0334db931

![dd](https://github.com/opencrvs/opencrvs-core/assets/94350336/d9df694b-84cb-487e-a6ad-cfc1f765646c)

**Environment:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/6696

**Comment by SyedaAfrida** [comment]
This bug is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/689880bd-bacb-4aa2-b5f9-3009dd8ff660
