### ISSUE TITLE
Unable to validate/ register incomplete death declaration

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6622]
**Bug description:**
Unable to validate/ register incomplete death declaration

**Steps to reproduce:**
1. Login to FA
2. declare an incomplete death declaration
3. Submit
4. Login to RA/ Registrar
5. Update that record
6. Validate/ register that declaration

**Actual result:**
- Record stays in  in progress workqueue
- status is not changed
- Update do not appear
- Unable to download that record

**Expected result:**
Should be able to validate/ register incomplete death declaration
**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/0e790616-4b41-43fd-a7d1-e0e6cd994e6d

**Environment:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/6696/files
Here some additional fixes are available as well for incomplete declarations.

**Comment by SyedaAfrida** [comment]
This bug is not properly fixed.
Records(birth and death) which are updated and registered don't show registered time in workqueue

https://github.com/opencrvs/opencrvs-core/assets/94350336/cc49f408-df37-4da9-8dbd-623d648a8847
