### ISSUE TITLE
When creating user if first name has more than 1 word, then the second word gets deleted after the user is created

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6631]
**Bug description:**
When creating user if first name has more than 1 word, then the second word gets deleted after the user is created

**Steps to reproduce:**
1. Login to National system admin
2. Click Team
3. Create new user
4. add 2 words in first name
5. Observe after saving

**Actual result:**
 the second word gets deleted after the user is created

**Expected result:**
Should show the names properly

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/aef727d7-94a0-4c0e-bcd7-7567d1ee96c3

**Environment:**
https://login.farajaland-staging.opencrvs.org/?lang=en
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.4.1, V1.5.0

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/6759

**Comment by SyedaAfrida** [comment]
This bug is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/797f1171-3132-48be-804c-139941bfb391
