### ISSUE TITLE
When incomplete declaration is updated by RA and sent for approval, not showing sent for approval and sent for review date

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6635]
**Bug description:**
When incomplete declaration is updated by RA and sent for approval, not showing sent for approval and sent for review date

_Note: Registered time is also not showing when record is updated_

**Steps to reproduce:**
1. Login to FA
2. declare an incomplete declaration
3. Submit
4. Login to RA
5. Update that record
6. Validate that declaration
7. observe sent for approval workqueue
8. login to Registrar
9. Observe sent for review workqueue

**Actual result:**
When incomplete declaration is updated by RA, not showing sent for approval and sent for review date

**Expected result:**
Should show sent for approval  and sent for review date

**Screen recording:**

![inc](https://github.com/opencrvs/opencrvs-core/assets/94350336/ce0966d8-7b1a-4427-9d29-bd6403a84f42)

For registered record:

https://github.com/opencrvs/opencrvs-core/assets/94350336/c494910d-cc42-41e3-b22c-11a831236890

**Environment:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/6741

**Comment by SyedaAfrida** [comment]
This bug is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/b76e09af-b754-4ea9-bc76-9f0fbabf16bb
