### ISSUE TITLE
Accessibility of loading states

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#6641]
### Problem

Let's design a few copy texts for the different spinner states, informing the user what is happening. It also might help us debug in case of errors or large loading times.

States:
1. The application bundle is loading
2. Redux states; either generic "Assets are loading", or individual:
	1. Authenticating (PROFILE/USER_DETAILS_AVAILABLE)
	2. Loading offline data (OFFLINE/GET_OFFLINE_DATA_SUCCESS)
	3. Loading workqueues (DECLARATION/GET_WORKQUEUE_SUCCESS)

https://github.com/opencrvs/opencrvs-core/assets/1322608/95654523-809d-4d89-9c83-88658d5f249e

I'm not sure how synchronous they are, if they're loading at the same time it might make sense to say "Assets are loading"

### Description

When the bundle is loading we should see the spinner, not a white screen.  In console logs we should have any required technical progress alerting we might need.

Wait time & fade, plus progress bar to be shown during bundle load.
During second load, just show the spinner.

**Comment by Zangetsu101** [comment]
We could probably do something like:

Loading assets
      - Forms loading // perhaps a loading spinner
      - Certificates loading
      ...
      
Loading assets
      - Forms loading
      - Certificates loaded
      ...

**Comment by naftis** [comment]
We agreed to leave the loading texts away for now, but a 'fake loading bar' -approach instead of a loading spinner could be a good UX improvement, to show the user that nothing has frozen and the load continues. Waiting for a design from @jpye-finch

**Comment by jpye-finch** [comment]
Design as discussed @naftis https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=19228%3A18923&mode=design&t=w25RICSiGIskyawB-1

**Comment by SyedaAfrida** [comment]
This ticket is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/f62573a7-e4e1-487a-b040-9085b37d319d
