### ISSUE TITLE
Ensure clients and server are always on the same version

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#6695]
### Description

Tameem got this error when he tried to login to QA today.

```
index.15a7d619.js?__WB_REVISION__=49866768f086c45c302328c7d95358b3:156 Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at extractLanguageSelectConfig (index.15a7d619.js?__WB_REVISION__=49866768f086c45c302328c7d95358b3:156:32909)
    at index.15a7d619.js?__WB_REVISION__=49866768f086c45c302328c7d95358b3:156:33039
    at index.15a7d619.js?__WB_REVISION__=49866768f086c45c302328c7d95358b3:1:151
    at index.15a7d619.js?__WB_REVISION__=49866768f086c45c302328c7d95358b3:4433:59098
logger.min.js:1 
```

This is probably related to https://github.com/opencrvs/opencrvs-core/pull/6588 where we removed the AVAILABLE_LANGUAGES_SELECT config variable. The error goes away if I clear cache but users are likely to encounter this when upgrading to 1.4.1

https://opencrvsworkspace.slack.com/archives/C02LU432JGK/p1711520455927719

This is very difficult to QA against at the moment.

## Specification

Gateway should include X-Version: 1.4.1  header to all of its HTTP responses. The value of the header should be derived from package.json version. Both the login client and the register client in turn need to implement a request middleware that for every response gotten from the backend, checks the response version and compares it to the client version. If the version doesn't match, then a modal is shown (let's use the one we show when there's a newer bundle to download) prompting the user to reload the app.

Similar logic should also be applied for communication between core and country config. As part of every request made to country config, core should include the same `X-Version: 1.4.1` header. Country config should have one pre-request middleware that should apply to all handlers that checks if the version is compatible using a range. 

If the range doesn't match, then country config returns a suitable error. The developer should get a descriptive error message already in the seeding phase. Similar errors can be show in console output and in the client similarly as we do with form configuration errors.

### Dev tasks

- [x] Include `X-Version` header in all gateway responses
  - Derive the value from `package.json` version.

- [x] Implement request middleware for login client
  - For every response from gateway, check the `X-Version` header.
  - Compare the response version with the client version.
  - Show a modal to reload the app if versions don't match.

- [x] Implement request middleware for register client
  - For every response from gateway, check the `X-Version` header.
  - Compare the response version with the client version.
  - Show a modal to reload the app if versions don't match.

- [x] Core communication with country config
  - Include `X-Version` header in all requests made to country config.
  - Implement pre-request middleware in country config to check version compatibility using a range.
  - Return a suitable error if the version range doesn't match.

- [x] Descriptive error handling
  - Ensure that developers get a descriptive error message during the seeding phase if the version range doesn't match.
  - Display similar errors in the console output and the client, akin to form configuration errors.

**Comment by rikukissa** [comment]
Marking this as low priority for now as I still need some time to research the standard way of doing this

**Comment by jpye-finch** [comment]
Design required:

Propose a Dialog prompt with messaging. 
CTA: Install 

Can we trigger the hard reset this way?

**Comment by rikukissa** [comment]
We can, yes. I think we did have something similar at one point 🤔

**Comment by Zangetsu101** [comment]
We need to revisit this as it requires a close integration with the service worker otherwise it won't work

**Comment by jamil314** [comment]
> Implement pre-request middleware in country config to check version compatibility using a range.

@rikukissa how should the versions be compared here?
One approach could be to match the major and minor versions and ignore the patch versions.

**Comment by rikukissa** [comment]
@jamil314 It needs to be an exact match as our current versioning schema doesn't give guarantees that frontend - backend communication won't change in patch versions

**Comment by SyedaAfrida** [comment]
@Zangetsu101 Please mention what needs to be tested in this ticket

**Comment by SyedaAfrida** [comment]
Can't be tested by QA
