### ISSUE TITLE
In advance search, all records are not showing properly when searched with residential address in  place of event

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6698]
**Bug description:**
In advance search, all records are not showing properly when searched with residential address in  place of event

**Steps to reproduce:**
1. Login to RA/ registrar
2. Go to advance search
3. select birth/death tab
4. Select place of event> residential address
5. Select address

**Actual result:**
In advance search, all records are not showing properly when searched with residential address in  place of event

**Expected result:**
should show all records properly when searched with residential address in  place of event

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/e66ac7a4-e84a-4964-a1cf-4da5c8c314cc

**Environment:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/6708

**Comment by SyedaAfrida** [comment]
This bug is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/9af7e964-9c08-4ab2-8541-6aac52b1b565
