### ISSUE TITLE
The reset 2FA script is not working

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6764]
The reset 2FA workflow is failing for me after initial install with this error:

![Image](https://github.com/opencrvs/opencrvs-core/assets/3169954/5cb175e6-0642-4145-8427-d478218410c8)

**Country Configuration Version:**
- v1.4.1 (Git branch: master / release-v1.4.1)

**Comment by Zangetsu101** [comment]
`SSH_PORT` is not set in any of the environments, which is causing this workflow to fail. Has that variable been deprecated?

**Comment by rikukissa** [comment]
I think it's still very valid as the port number isn't always 22. In this specific case I've just not taken into account that it might be missing in some environments

**Comment by rikukissa** [comment]
Fixed in this PR:
https://github.com/opencrvs/opencrvs-farajaland/pull/975

**Comment by Zangetsu101** [comment]
Completed in https://github.com/opencrvs/opencrvs-farajaland/pull/975
