### ISSUE TITLE
Changes in correction form do not register leaving the "Continue" button disabled (custom section in form config)

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#6780]
**Describe the bug**

1. Create a new form section to your country config
2. Add a group and a custom field inside of that section. Add the following logic for the group so that it won't be shown in the declaration phase of the process. This might be unrelated to the bug

```ts
{
  action: 'hide',
  expression:
    '!Boolean(draftData?.registration?.registrationNumber)'
}
```
4. Register a new birth
5. Make a correction and add a value for the custom field
6. Notice the "Continue" button stays disabled

In Burkina Faso, we've add a temporary patch to `packages/client/src/views/RegisterForm/review/ReviewSection.tsx`

```diff
  hasFieldChanged(
    field: IFormField,
    data: IFormSectionData,
    originalData?: IFormSectionData
  ) {
-    if (!originalData) return false
+    if (!originalData) {
+      const isCustomSection = data && data[field.name]
+      if (isCustomSection) {
+        this.hasChangesBeenMade = true
+        return true
+      }
+     return false
+  }
```

If this is enough to

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/7023

**Comment by Zangetsu101** [comment]
Tested in Madagascar configuration
