### ISSUE TITLE
Refactor certificate review page so different certificate templates can be displayed

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6816]
ie: Uganda landscape half A4 format, a4, letter, legal paper 

## Tech tasks
- [x] Refactor core code so that it either doesn't define certificate dimensions at all and prints the PDF with the same dimensions the SVG has OR alternatively, we read the width and height of the SVG and use those values

**Comment by tiri39** [comment]
Not tested on core.

On Uganda (https://register.uganda.opencrvs.org/)  -

![Image](https://github.com/user-attachments/assets/b2363f55-6086-4efa-9a51-3d176bc49225)
