### ISSUE TITLE
Make D.O.B. an optional field for witness / informant

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6819]

**Comment by Zangetsu101** [comment]
it looks like informant date of birth is considered as an optional field in core, at least according to the validations. So is this ticket about removing the field from farajaland or something else?

**Comment by rikukissa** [comment]
If this can already be achieved, then I think we can close the ticket.

**Comment by Zangetsu101** [comment]
In that case I'll directly move this to ready to deploy, the Uganda forms only need to be configured this way

**Comment by tiri39** [comment]
Tested on Uganda env (https://register.uganda.opencrvs.org/) , not on core.

D.O.B is mandatory for notifier/ informant for both birth and death declarations - 
![Image](https://github.com/user-attachments/assets/aaf825bc-d148-45b1-84e3-d4838897d557)
![Image](https://github.com/user-attachments/assets/d256b22d-5699-4531-a253-f1f31a0070ae)
