### ISSUE TITLE
Make informant signature conditional based on supporting documentation

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6821]
Death registration form change
- The digital signature section for the Notifier should not be shown on the Review page if the paper form is uploaded as a supporting document since the Notifier already signed on the paper form.

**Comment by Zangetsu101** [comment]
I'm moving this to backlog as this requires tech design

**Comment by Zangetsu101** [comment]
- Do we want the signatures as form fields or do we want them only for the review page?
- if form fields then are we allowing countries to add any form field to the review section e.g. an input field?
@jpye-finch

**Comment by jpye-finch** [comment]
In reply to bullet 1:
Having the signatures as form fields has been discussed. But they are best located on the review page. 
So conditionality between the form and review page is being asked for here

bullet 2:
Good questions. Think best to only allow signatures. Don't see a use case for allowing other form field inputs.

**Comment by rikukissa** [comment]
- Strict validation if preview section, then needs to have `preview-view-group`
- Move signature fields out from ReviewSection completely, introduce as new form input type
- Add a backend validation error if preview section is not defined, guide user in local environment to add from an example
- Add a generic field query/mutation transformer for redirecting the value from preview section to `registration` section
- Refactor the double-key `informantsSignatureURI` + `informantsSignature` to always only be `informantsSignatureURI`. Ultimately the Base64 data is also just an URI. 

Bug? https://github.com/opencrvs/opencrvs-core/blob/develop/packages/client/src/views/RegisterForm/review/ReviewSection.tsx#L2114-L2115

**Comment by Zangetsu101** [comment]
The informant/bride/groom/witness signatures need to be tested for this ticket

**Comment by tiri39** [comment]
Found following issues- 

- Signature section available when an user **Views** a declaration - 

https://github.com/user-attachments/assets/6e6fad56-d80b-44d7-a720-28356addf633

- PNG files are not being uploaded in the Signature section -
when user tries to upload a PNG file, the file doesn't get uploaded and an error message is shown - 'png supported image only'

https://www.loom.com/share/26502ced26394413bf180216e2ef4c86?sid=a8c058d7-fe85-450d-9189-8a2992bd616d

**Comment by Zangetsu101** [comment]
The signature should also not show upwhen correcting a record.

**Comment by tiri39** [comment]
Partially fixed.

- PNG files are not being uploaded in the Signature section -

when user tries to upload a PNG file, the file doesn't get uploaded and **an error message is shown - 'png supported image only'**
https://www.loom.com/share/26502ced26394413bf180216e2ef4c86?sid=a8c058d7-fe85-450d-9189-8a2992bd616d

**Comment by rikukissa** [comment]
@tiri39 can I ask you to please report this as a new bug ticket?

**Comment by tiri39** [comment]
@rikukissa This bug was fixed, we can close this ticket.

https://github.com/user-attachments/assets/3a7c3fee-aec2-447b-a300-7aa64ee99f71
