### ISSUE TITLE
Make supporting documents mandatory

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6822]

**Comment by Zangetsu101** [comment]
@jpye-finch Let's say some documents are mandatory and I fill up everything else apart from uploading the required documents, there should be some form of indication to the user in the review page that says "this document is required" or something similar

**Comment by Zangetsu101** [comment]
waiting for design

**Comment by tiri39** [comment]
Tested on Uganda env (https://register.uganda.opencrvs.org/) , not on core.

Found one issue -  **Declarations can be registered/ sent for approval without uploading mandatory supporting documents.**

**Steps to reproduce -** 

1. Log into Uganda env (https://register.uganda.opencrvs.org/) as RA/registrar.
2. Start creating a death declaration.
3. Choose accident/ suicide/ homicide/ body found as 'Circumstances of death'.
4. Fill out all mandatory fields except the 'proof of death' in the 'upload supporting documents' page.
5. Click continue -> register

**Recording:**

https://github.com/user-attachments/assets/2bbbeece-cc92-4754-8899-380077e2bfb5

**Comment by Zangetsu101** [comment]
@tiri39 The mandatory supporting docs feature is working properly![Image](https://github.com/user-attachments/assets/ff9fd529-0284-449e-a572-2a9f9fb9678b)
Rather the flaw you noticed is related to a configuration error, so could I trouble you to create a entry in Uganda backlog for this instead? I'll move this ticket back to QA
