### ISSUE TITLE
Informant's id becomes empty in a completely submitted declaration when informant is change from mother/father to others

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6855]
**Bug description:**
Informant's id becomes empty in a completely submitted declaration when informant is change from mother/father to others

**Steps to reproduce:**
1. Login to FA
2. Submit a complete/ incomplete birth declaration where informant is mother / father
4. logout
5. Login to RA/ Registrar
6. Download>assign> Review that record
7. Update informant type to any informant other than mother/ father
8. enter ID and complete the form
9. Register/ send for approval
10. Observe the updated action from the record audit page
11. View or review that declaration

**Actual result:**
In Updated action showing informant ID is updated
But in View/ review page ID field is empty

**Expected result:**
Informant's id becomes empty in a completely submitted declaration when informant is change from mother/father to others

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/abefb050-71bf-4719-a38e-6da4f0622ce2

**Environment:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/6979

**Comment by SyedaAfrida** [comment]
This bug is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/0717626a-6a48-4c2b-b0bc-626cf77bd5cc
