### ISSUE TITLE
When a declaration is updated, multiple fields showing wrong update

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6874]
**Bug description:**
When a declaration is updated, multiple fields showing wrong update

Birth-
Fullname (informant), phone (informant), Email (Informant), Nationality (informant, mother, father), Level of education	(mother,father)

Death-
Nationality (deceased,informant,Spouse), No. of dependants (Deceased), Reason for late registration, Fullname (informant), Type of ID(informant),phone (informant), Email (Informant)	

Marriage-
Nationality (informant, bride, groom), phone (informant), Email (Informant), witness first name

**Steps to reproduce:**
1. Login to FA
2. Submit a complete birth /death/ marriage declaration
5. Login to RA/ Registrar
6. Download>assign> Review that record
7. Update 
8. Download>assign> Review that record
9. Observe the updated action from the record audit page
10. View or review that declaration

**Actual result:**
In Updated action showing all the information is updated
But in View/ review page multiple field are not updated properly

**Expected result:**
all information should be updated properly

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/66d2c6a2-c1a7-441a-aace-7528b1cf4dc8

**Environment:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by rikukissa** [comment]
https://github.com/opencrvs/opencrvs-core/pull/6885

**Comment by SyedaAfrida** [comment]
**Bug:** Email address not showing after submitting any declaration and witness 1st name not updating properly


https://github.com/opencrvs/opencrvs-core/assets/94350336/b141a326-67cd-4dd7-bf13-5404153a46cd

**Comment by Nil20** [comment]
Re-fix: https://github.com/opencrvs/opencrvs-core/pull/6960

**Comment by SyedaAfrida** [comment]
This bug is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/074baabc-430b-49b9-ae34-f0bbf6b46e00
