### ISSUE TITLE
Unable to open printed incomplete declaration in new tab

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6893]
**Bug description:**
Unable to open printed incomplete declaration in new tab

_**Note:** Console error also appears when try to print complete declaration_

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Create an incomplete declaration
3. From review page Click Print declaration
4. Observe

**Actual result:**
Unable to open printed incomplete declaration in new tab

**Expected result:**
Should be able to open incomplete declaration in printed form in new tab

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/7f30c500-e5af-432d-a412-e83e5b885051

**Environment:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/6988

**Comment by SyedaAfrida** [comment]
This bug is fixed

https://github.com/opencrvs/opencrvs-core/assets/94350336/ba8d5cda-3c29-42a3-a9d6-04e3814b4b89
