### ISSUE TITLE
Create regression test suites for login section

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#6916]
### Description

Using test cases from [here](https://docs.google.com/spreadsheets/d/1Ppf29wo0whdscmoeE8m4G3wCIVeorfHP/edit#gid=648252876), write Cypress tests in OpenCRVS Farajaland repository for all test cases under **Login**.

Test need to be written as per the testing guidelines [here](https://www.notion.so/opencrvs/E2E-testing-framework-5d14d933c94e4b869220fd52035f60db?pvs=4).

### Dev tasks

- [x] Familiarise yourself with existing test code and helpers related to login
- [x] Create necessary test files for each test case under `cypress/e2e/test-cases/login`
- [x] Submit a PR after finishing the first test file
- [x] Continue work on other login tests until the login section is covered

**Comment by SyedaAfrida** [comment]
Reviewed. Working properly
