### ISSUE TITLE
Use the custom name for the Content title of the saved advanced query

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6934]
GIVEN I have saved an advanced search query 
WHEN the saved search query is clicked on in the side menu
THEN use the custom name as the title

GIVEN the query has finished loading
THEN show the total number of results

This requirement has come from Madagascar to better support custom work-queues

![Image](https://github.com/opencrvs/opencrvs-core/assets/46478402/f59184cf-e6c9-4dfb-b5da-f5141f6ad0be)

**Comment by Zangetsu101** [comment]
@jpye-finch This seems to be completed with #6365

**Comment by Zangetsu101** [comment]
Completed in #6365
