### ISSUE TITLE
Performance view re-work

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6953]
Performance page that we have using React UI to UN standards contains elemts which confuse countries that dont conform and they ask for improvements.  Things like fees being configurable, no concept of late registration, no marriage event etc.  Can we minimise the performance page to global most basic things and instead develop more data-lake type integrations containing no-PII so that a country can use whatever BI tools they want to do whatever data they want.  No longer building out custom performance components.

**Comment by jpye-finch** [comment]
closing in place of: https://github.com/opencrvs/opencrvs-core/issues/7135
