### ISSUE TITLE
Recognition: ability for the Father of a child in an unmarried relationship to "recognise"

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6967]
Ability for the Father of a child in an unmarried relationship to "recognise" the child as their own (before or after registration)

"Proposed approach (pre-registration recognition):
1. Add form field for recognition to birth form
2. Add rules into father section to capture recognition requirements/fields
3. Add field for recognition number
4. Add freetext field for the reason for recognition
5. Display title on birth certificate to reflect status of recognition

Proposed approach (post-registration recognition):
1. Use correct record process for post-registration recognition"

"Enhancement to be designed and built:
1. Add recognition as an event (requirements to be confirmed)
"

**Comment by rikukissa** [comment]
@jpye-finch has the proposed approach been validated with Madagascar? To me it seems like all of this could be configured from country config, except recognition as an event. If a separate event is required, I'll need to do a bit of research on whether we could make custom forms a reality or if this should be again just a hard-coded event.

**Comment by euanmillar** [comment]
@rikukissa this can be done in country config for Madagascar's needs in 1.7.0.  @jpye-finch  Later there may be a distinct recognition as an event ticket.
