### ISSUE TITLE
Role of justice

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6969]
### Description
Using the[ new approach](https://github.com/opencrvs/opencrvs-core/issues/6455) to creating user roles and setting permissions. 

This ticket is to: 
- Create a role called Justice
- Scopes For All Records:
   - Search For All Records
   - View Record 
   - View Record Audit
   - View Comments
   - Add Comments
   - Revoke Registrations
   - Reinstate Registrations

**Comment by jpye-finch** [comment]
Closing as with user scopes and configurable workqueues the Justice role can be created.
