### ISSUE TITLE
Image compression reduction configuration

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6971]
Currently file compression size is hardcoded in client and in the Hapi server config
This needs to be configurable so that Madagascar can launch with 1.5 and improve the upload/download experience

There is a global payload max size of 52.42MB which will remain the absolute hard-limit for uploads.

# Tasks

- [x] Implement a new optional configuration variables for `DOCUMENT_UPLOADER_WITH_OPTION`: 

  - `compressImagesToSizeMB` (float) - This is an optional value if a country wants to enable image compression. Defaults to `0.4` defined in DocumentUploaderWithOptions.tsx. Is only applied if the size of the uploaded image is over the defined value. Can be disabled completely with a falsy value.

  - `maxSizeMB` (float) - This is a validation option preventing users from submitting files that are over the limit. Default value is `0.5` defined in DocumentUploaderWithOptions.tsx. Can be disabled completely with a falsy value.

- [x] Test setting `compressImagesToSizeMB: 0.1` and post the produced output to Slack. If it makes the image completely illegible, we can decide to enforce minimum for this value.

**Comment by tahmidrahman-dsi** [comment]
I think two ways can achieve this to make this configurable from the countryconfig,
 
1. specifying in the default application config in the countryconfig. In this approach, we can either set a global limit or usage-specific limits, as we have several places to upload docs.
2. add a prop `maxImageSize` or something similar to `DocumentUploaderWithOptions` and specify in countryconfig forms. This approach will be confined to the forms only.

**Comment by Zangetsu101** [comment]
The document upload functionality needs to be tested for this ticket.

**Comment by SyedaAfrida** [comment]
This ticket is working

https://github.com/opencrvs/opencrvs-core/assets/94350336/3c4b446e-e383-461b-8aed-f2474d7c84fa
