### ISSUE TITLE
Deprecate some features in National System Admin Config UI menu items and code

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6975]
Deprecate the following:

Application
Certificates
User roles
Communications / Informant notifications
**Keep Confguration / Integrations**

![Image](https://github.com/opencrvs/opencrvs-core/assets/3169954/f798730f-8087-4d5c-a4ba-123417a013b0)

**Comment by naftis** [comment]
Being fixed in https://github.com/opencrvs/opencrvs-core/pull/7155

**Comment by SyedaAfrida** [comment]
This ticket is fixed


![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/9785a8b8-f60c-4d12-9669-9ebe46940934)
