### ISSUE TITLE
Resend email link button not working during password reset flow

### ISSUE THREAD

**Issue by prinzab** [opencrvs/opencrvs-core#6987]
**Bug description:**
Resend email link button not working during password reset flow

**Steps to reproduce:**
1. Click Can't login on the login page
2. Select Password reset 
3. Enter a valid email address to receive the 6-digit code
4. Click 'Resend Email' to receive a different code 
5. Observe page and email inbox  

**Actual result:** 
1. Nothing happens on the UI
2. No email is sent to the user's email inbox 

**Expected result:**
1. User should receive an email with the 6-digit code
2. User should be shown a toast that the email has been sent 

**Screen record:**
<img width="1440" alt="Screenshot 2024-05-14 at 14 18 50" src="https://github.com/opencrvs/opencrvs-core/assets/44720007/087b702f-b3ef-4b67-92c5-cc537d9db72f">

**Environment:**
https://login.farajaland-qa.opencrvs.org/

**Version:**
v1.5.0

**Test URL:** 
[https://login.farajaland-qa.opencrvs.org/recovery-code](https://login.farajaland-qa.opencrvs.org/recovery-code)

**Comment by tiri39** [comment]
This bug has been fixed.

https://github.com/opencrvs/opencrvs-core/assets/113257751/bc381334-7796-472f-8254-f399566fc9f3
