### ISSUE TITLE
The validation for mother and father having same NID is not working

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6999]
**Bug description:**
The validation for mother and father having same NID is not working

In birth declaration informant, mother and father can have same NID
Same  goes for death declaration, where deceased, spouse and informant can have same NID

**Steps to reproduce:**
1. Login to FA/RA/ Registrar
2. Create any declaration
3. Provide Same NID for multiple person like- informant, mother, father
4. Go to review page and Observe

**Actual result:**
informant, mother and father can have same NID

**Expected result:**
The validation for mother and father having same NID is not working

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/ce29983c-51e0-41ff-965e-c3776062fcec

**Environment:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by tiri39** [comment]
This ticket is fixed.

https://github.com/opencrvs/opencrvs-core/assets/113257751/36fcd632-46e6-4816-8bd6-6aa826b630b6
