### ISSUE TITLE
In Birth declaration-Supporting document page, hide Other dropdown when Informant is mother/ father

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7000]
**Bug description:**
In Birth declaration-Supporting document page, hide Other dropdown when Informant is mother/ father

**Steps to reproduce:**
1. Login to FA/RA/ Registrar
2. Create Birth declaration
3. Set informant as mother/father
4. Go to Supporting document page
5. Observe

**Actual result:**
Showing other dropdown

**Expected result:**
In Birth declaration-Supporting document page, hide Other dropdown when Informant is mother/ father

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/4cd917fd-12b6-4e8c-b645-cb68f8353bf0

**Environment:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by jpye-finch** [comment]
@Zangetsu101 assume this is just an update to Farajaland form configuration?

**Comment by Zangetsu101** [comment]
yes that's right

**Comment by SyedaAfrida** [comment]
This ticket is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/713360f3-a547-46d4-8cf8-9fb2a49379f4
