### ISSUE TITLE
Create client modal glitches on Integrations page

### ISSUE THREAD

**Issue by prinzab** [opencrvs/opencrvs-core#7002]
**Bug description:**
Create client modal glitches on Integrations page

**Steps to reproduce:**
1. Login as a National System Admin (p.abraham)
2. Navigate to Configurations > Integrations 
3. Click the Create Client button to open Create client modal 
4. Click the Type dropdown to show the available options 
5. Hover (position your mouse pointer) in-between **Event notification** and **National ID** or **Record search** and **Webhook**
6. Observe the modal 

**Actual result:**
When the Type dropdown is selected on the modal, the modal begins to glitch once the mouse pointer is positioned in-between **Event notification** and **National ID** or **Record search** and **Webhook**

**Expected result:**
When the Type dropdown is selected on the modal, it should show the list of options available in the dropdown, and allow the user hover across each item without glitching. 

**Environment:**
https://login.farajaland-qa.opencrvs.org/

**Version:**
v1.5.0

**Screen record:**
[https://www.loom.com/share/20659cf8a25b4ab99e34627e839daa9c?sid=5b6cf6ba-2837-47ff-877d-16e5f00738eb](https://www.loom.com/share/20659cf8a25b4ab99e34627e839daa9c?sid=5b6cf6ba-2837-47ff-877d-16e5f00738eb)

**Comment by SyedaAfrida** [comment]
This bug is fixed


![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/f851f188-6a4e-4f22-afd8-e1c76d332080)
