### ISSUE TITLE
Session expires and user is logged out when trying to change phone number

### ISSUE THREAD

**Issue by prinzab** [opencrvs/opencrvs-core#7003]
**Bug description:**
Session expires and user is logged out of their account when trying to change their phone number

**Steps to reproduce:**
1. Login as a National System Admin (p.abraham)
2. Click on Settings 
3. Click the Change link button for Phone number (no existing phone number for the user)
4. Enter phone number in the modal 
5. Click the Continue button 
6. Observe > Nothing happens 
7. Click Cancel on the same modal 
8. Observe

**Actual result:**
System tells the user that their session has expired when trying to change their phone number from Settings page

**Expected result:**
User should be able to change their phone number and the new phone number should reflect on the Settings page without the session expiring or the user being logged out

**Environment:**
https://login.farajaland-qa.opencrvs.org/

**Version:**
v1.5.0

**Screen record:**
https://www.loom.com/share/0b17ebf1e9964c8b93a24fe73baaf820?sid=aeb4b4de-0943-42b8-a8b1-7edb0655ffb7

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/7025

**Comment by tiri39** [comment]
This bug is fixed.


https://github.com/opencrvs/opencrvs-core/assets/113257751/cf188fe9-8bf5-4fe9-9287-353f8491f6cf

**Comment by tiri39** [comment]
This bug is fixed.


https://github.com/opencrvs/opencrvs-core/assets/113257751/cf188fe9-8bf5-4fe9-9287-353f8491f6cf
