### ISSUE TITLE
Record can go completely missing in the case of a backend exception

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#7005]
**Describe the bug**
When submitting a declaration, in the case of something going wrong in the backend the client interprets the received errors as a successful submission. This, in the worst case, can cause records to never get stored anywhere leading to permanent data loss

**Which feature of OpenCRVS your bug concern?**
Declaring, registering and all other processes where records are sent to the backend

**OpenCRVS Core Version:**
- v1.5.0 + All previous OpenCRVS versions

**Additional context**
Easiest to reproduce by shutting down the `opencrvs_workflow` service

**Reproducible demo**
https://github.com/opencrvs/opencrvs-core/assets/1206987/af173102-7a54-4514-a232-5a449254211e

## Tasks
- [ ] Change the Outbox logic to only purge the sent record from the queue when there is an id received from the backend

**Comment by rikukissa** [comment]
https://github.com/opencrvs/opencrvs-core/pull/7021

**Comment by jamil314** [comment]
can't reproduce on farajaland-dev: 
![can't reproduce on farajaland-dev](https://github.com/opencrvs/opencrvs-core/assets/52415768/4d986f3a-0f4d-4ea0-a3dd-18938c348aac)

**Comment by jamil314** [comment]
can't reproduce on latest version of release-v1.5.0

![Image](https://github.com/opencrvs/opencrvs-core/assets/52415768/471b2a9a-79a9-4da8-ac5f-6e9e3302a263)

**Comment by jamil314** [comment]
[fix](https://github.com/opencrvs/opencrvs-core/pull/7315)

**Comment by SyedaAfrida** [comment]
This ticket is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/9738fc90-5cf0-4f42-ba79-dda7ced92725
