### ISSUE TITLE
Unable to send incomplete death declaration when informant is someone else

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7011]
**Bug description:**
Unable to send incomplete death declaration when informant is someone else

**Steps to reproduce:**
1. Login to FA
2. declare death
3. Click save and exit from introduction page
4. Click update
5. Provide informant type to someone else
6. Fillup relationship type and email address
7. Send

**Actual result:**
Declaration gets stuck to outbox

**Expected result:**
Should be able to send incomplete declaration

**Screen recording:**
![death inc](https://github.com/opencrvs/opencrvs-core/assets/94350336/da5b2a03-06b0-411d-b84d-5e049d111564)

**Environment:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-farajaland/pull/1010

**Comment by SyedaAfrida** [comment]
This ticket is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/d3bd6425-3176-4ac1-9169-904aa716ce66
