### ISSUE TITLE
Move remaining configurations inside feature flags

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#7013]
- [ ] Move these 2 configuration options inside feature flags and update client code accordingly. https://github.com/opencrvs/opencrvs-countryconfig/blob/develop/src/api/application/application-config-default.ts#L51-L52

**Comment by Nil20** [comment]
PR: https://github.com/opencrvs/opencrvs-core/pull/7014

**Comment by Zangetsu101** [comment]
DATE_OF_BIRTH_UNKNOWN & INFORMANT_SIGNATURE_REQUIRED needs to be tested for this ticket

**Comment by SyedaAfrida** [comment]
This ticket is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/a134f709-d34d-4a00-81be-f8ce303d4efe
