### ISSUE TITLE
A staging server cannot both be backing up data and restoring

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#7015]
We noticed the restore (specically, the download.sh) process on staging had broken down after we enabled backup taking on the staging server.

Most of this issue is caused by Ansible playbooks sharing the same `external_backup_server_remote_directory` variable both for the backup target and for location from where to download the backup for periodic restore. Of course this cannot be the same value as otherwise the server restores its own backup. 

`backup_encryption_passphrase` variable has the same issue.

**Why do we even want one server to both restore and backup?**

This is pretty specific Farajaland requirement as we want to verify backup mechanism works also in hotfix versions we test on staging. We also do not test backups on QA.

**Comment by SyedaAfrida** [comment]
@rikukissa Backup is not working in staging environment

**Comment by rikukissa** [comment]
@SyedaAfrida I ran the restore procedure again on staging and I think it's ok now. Can you confirm? Let's try it again tomorrow

**Comment by SyedaAfrida** [comment]
This ticket is fixed
