### ISSUE TITLE
Dashboards cron jobs are not working

### ISSUE THREAD

**Issue by tahmidrahman-dsi** [opencrvs/opencrvs-core#7016]
**Describe the bug**
Cron jobs are throwing errors in the metrics service for both dashboard view refreshing and vs-export generation

**Screenshots**
![image](https://github.com/opencrvs/opencrvs-core/assets/42269993/adf431ee-28b1-43d8-94f9-698e0f334d2d)

**Comment by Zangetsu101** [comment]
The metabase view refresh cron probably got broken when the query was moved to countryconfig as it expects auth token but the cron has no way of providing that

**Comment by SyedaAfrida** [comment]
This bug is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/3dab865e-227b-426b-b9f6-098e69f60f22
