### ISSUE TITLE
Deployment using non-22 port doesn't work even when SSH_PORT is setup correctly

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#7018]
**Describe the bug**
If a country wants to use a non-default SSH port (e.g. 12345), provision works great but when it's time to deploy they encounter a roadblock. This is because there's a hardcoded SSH_PORT=22 definition in our deployment script [here](https://github.com/opencrvs/opencrvs-countryconfig/blob/develop/infrastructure/deployment/deploy.sh#L66).

## Tasks

- [ ] Ensure countries can use a port other than 22 and that it flows smoothly from Github environments all to way up to the SSH and rsync commands of deploy.sh

**Comment by jhirvioja** [comment]
Interested in doing this, but it would probably require introducing a new environment variable SSH_PORT. This needs to be updated to the documentation as well. How does one do a PR to the docs?

**Comment by jhirvioja** [comment]
> Hi @jhirvioja, thanks for your comment and would be happy to see a contribution from you! Where in the documentation did you find something related to this? I can handle updating them for you as I'm not 100% sure how or where a PR should be pointed to update it.
> 
> I'm also noticing we're not asking the port as part of our Github environment setup script, so maybe that's a good place to start from? https://github.com/opencrvs/opencrvs-countryconfig/blob/develop/infrastructure/environments/setup-environment.ts#L293-L326
> 
> Let me know if you have any further questions!

Probably [here at the very least](https://documentation.opencrvs.org/setup/3.-installation/3.3-set-up-a-server-hosted-environment/4.3.3-create-a-github-environment/4.3.3.1-environment-secrets-and-variables-explained#environment-secrets) and ofc in the documentation which is stepped there is a step-by-step for the cli, and if we add a step to setup-environmen.ts it should be reflected there as well.

Yeah - I identified these as steps:
- Remove line where SSH is hardcoded
- Add SSH_PORT to parameter reading
- Add ssh_port validation to cmd options / flags
- Add ssh_port to print usage and exit
- Add ability to change ssh port in env init script opencrvs-countryconfig/infrastructure/environments/setup-environment.ts
- (Documentation as described)

I will probably do a draft PR, and we can discuss there if it seems there are more known affected modules in the pipeline..?

**Comment by rikukissa** [comment]
Sounds good! I would look where we refer to SSH_HOST or SSH_ARGS and assume it should be roughly the same places.
I think country config is the only repository that these changes should affect. 
Let me know once you have something ready 👍
