### ISSUE TITLE
When declaration are being marked as duplicate & archived from the rejection modal, then sent incomplete/ declaration started action is added before archived action in history

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7024]
**Bug description:**
1) When declaration are being marked as duplicate & archived from the rejection modal, then sent incomplete action is added before archived action in history if the declaration was previously in in progress workqueue

2) When declaration are being marked as duplicate & archived from the rejection modal, then declaration started action is added before archived action in history if the declaration was previously in ready for review workqueue

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Download> Assign> Review any inprogress/ ready for review declaration
3. Click reject
4. Add comment> Mark as duplicate> Archive that record
5. Search that record with name/ tracking id
6. Click  Download> Assign
7. Observe history

**Actual result:**
 Sent incomplete/ declaration started action is added before archived action in history

**Expected result:**
Should only show archived action

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/248b64a3-6350-463e-b501-cbfd5d745644

**Environment:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by tiri39** [comment]
This bug is fixed.

https://github.com/opencrvs/opencrvs-core/assets/113257751/ba250cc6-01f3-4e6c-9c35-f3cb5959bb10

**Comment by tiri39** [comment]
This bug is fixed.

https://github.com/opencrvs/opencrvs-core/assets/113257751/ba250cc6-01f3-4e6c-9c35-f3cb5959bb10
