### ISSUE TITLE
Sometimes unassign action not appearing in record audit page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7035]
**Bug description:**
Sometimes unassign action not appearing in record audit page
 This bug occurs mostly when login in with the user first time and on assigning and unassign for the first time

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Download> Assign> goto record audit
3. observe actions in history
4. Unassign that record
5. Again assign that record 
6. Observe action in history

**Actual result:**
Sometimes unassign action not appearing in record audit page

**Expected result:**
Should show  unassign action

**Screen recording:**

![unassing bug](https://github.com/opencrvs/opencrvs-core/assets/94350336/2066e467-735a-412b-a069-1862672c7a79)

**Environment:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/7072

**Comment by SyedaAfrida** [comment]
This ticket is fixed

https://github.com/opencrvs/opencrvs-core/assets/94350336/c24a3819-cfa5-4a98-ae8e-af78c27a36e8
