### ISSUE TITLE
Resend email link not working from verification code page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7037]
**Bug description:**
Resend email link not working from verification code page

**Steps to reproduce:**
1. Go to login page
2. Enter username > Password> Continue
3. Click Resend email
4. Observe toast

**Actual result:**
1) Email is not being sent with verification code
2) Showing toast "Incorrect verification code. Please try again"

**Expected result:**
1) should send email
2) Should show toast "Invite sent"

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/61f51421-e9cb-4e5d-8715-7d420c62ba2f

**Environment:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/7047

**Comment by tiri39** [comment]
This bug is fixed.

https://github.com/opencrvs/opencrvs-core/assets/113257751/8cf7702f-8a26-4c5a-9442-f8b9eea2b37e
