### ISSUE TITLE
In update modal, multiple item names are showing wrong for marriage declaration

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7046]
**Bug description:**
In update modal, multiple item names are showing wrong for marriage declaration

Marriage-
Should be 
- Informant in place of Registration name
- Bride in place of Print and issue to bride
- Groom in place of Print and issue to Groom

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Update any marriage declaration
5. Submit
6. Download>assign> Go to record audit of that record
7.  Observe the updated action from the record audit page

**Actual result:**
Wrong item names

**Expected result:**
Should be 
- Informant in place of Registration name
- Bride in place of Print and issue to bride
- Groom in place of Print and issue to Groom

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/5a607901-ea8d-4bf3-9943-670c85c482c4

**Environment:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by tiri39** [comment]
- Informant in place of Registration name
- Bride in place of Print and issue to bride
- Groom in place of Print and issue to Groom

These are fixed. 

But in update modal for marriage declarations, if witness details are updated, then in item column its not showing specifically as '**Witness 1'** or **'Witness 2'**, just showing **witness for both witnesses**.

https://github.com/opencrvs/opencrvs-core/assets/113257751/50116bc6-222d-4890-a94e-c82772a28dee

**Comment by Nil20** [comment]
Latest Fix for country config: https://github.com/opencrvs/opencrvs-countryconfig/pull/185

**Comment by tiri39** [comment]
This ticket is fixed.

https://github.com/opencrvs/opencrvs-core/assets/113257751/5db844e2-f60d-4499-8b5d-ad1d6fa4535b

**Comment by tiri39** [comment]
This ticket is fixed.

https://github.com/opencrvs/opencrvs-core/assets/113257751/5db844e2-f60d-4499-8b5d-ad1d6fa4535b
