### ISSUE TITLE
Date and place of certification are showing wrong in certificate

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7060]
**Bug description:**
Date and place of certification are showing wrong in certificate

**Steps to reproduce:**
1. Login to RA/ Registrar
2. search for a record of another location
3. Print certificate of that record
4. Observe  date and place of certification

**Actual result:**
Date and place of certification are showing wrong in certificate
Date of certification is showing last assigned date
Place of certification is showing place of registered name

**Expected result:**
Should show current date in date of certification
should show user's office name in place of certification

**Screen recording:**
![date of cert](https://github.com/opencrvs/opencrvs-core/assets/94350336/1a4a842a-fb61-466d-8db9-07fac8dc2a46)

**Environment:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by Zangetsu101** [comment]
The updated certificates will need to be uploaded first before testing this

**Comment by SyedaAfrida** [comment]
This ticket is fixed


![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/a3fb1327-faf7-4002-b84d-f80f9139080f)
