### ISSUE TITLE
Correction cannot be made properly when try to correct from certificate preview page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7065]
**Bug description:**
Correction cannot be made properly when try to correct from certificate preview page

**Steps to reproduce:**
1. Login to RA/ Registrar
2. Go to ready to print
3. Go to certificate preview page
4. Click No, make correction
5. Make correction and submit
6. Observe the record in record audit page, view and history

**Actual result:**
- Record stays in assigned
- Record corrected action on appearing in history
- Correction do not appear when viewed

**Expected result:**
 Correction should appear when try to correct from certificate preview page, the same way it works for record audit page

**Screenshot/ Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/bb239f9c-98a5-480e-8bac-502e5243031f

![snt](https://github.com/opencrvs/opencrvs-core/assets/94350336/0cf0a326-ecae-4bde-a2c8-dc3e5c5e6c11)

**Environment:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/7093

**Comment by SyedaAfrida** [comment]
This ticket is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/64a5a8d2-1371-4a7e-916a-d9145a77b5c5
