### ISSUE TITLE
When a correction request is rejected, Reason for rejection is not showing in Correction rejected modal

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7075]
**Bug description:**
When a correction request is rejected, Reason for rejection is not showing in Correction rejected modal

**Steps to reproduce:**
1. Login as RA
2. Go to Ready to Print
3. Request an correction
4. Logout
5. Login as Registrar
6. Go to Ready for review'
7. Download> Assign> Review that record
8. Click reject> Provide reason> Reject correction
9. Got o ready to Print 
10. Download> Assign> Go to record audit page
11. Observe Correction reject modal

**Actual result:**

When a correction request is rejected, Reason for rejection is not showing in Correction rejected modal

**Expected result:**

Should show reason 

**Screenshot:**

![reject reason missing](https://github.com/opencrvs/opencrvs-core/assets/94350336/c5250fb7-03b2-4739-8f72-8e8287b961f4)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/7096

**Comment by SyedaAfrida** [comment]
This bug is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/dfb34fcc-b171-4ef5-a622-e1b1d1d6dd68
