### ISSUE TITLE
User stays rate limited even after the restriction time is over

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#7077]
The user also doesn't get any proper notification that they have been rate limited

Steps to reproduce are to be determined

**Comment by euanmillar** [comment]
@Zangetsu101 can you provide more info around how you discovered this and what the impact would be to leave this unresolved in 1.5.0.  I'm curious as to how a user could become rate limited with normal use of the app.

**Comment by Zangetsu101** [comment]
We have mostly encountered this on the team page where it has a generic toast that says "Sorry, we couldn't load the content for this page" which gets triggered when a user gets rate limited. And it still doesn't load even after the specified time has passed. Apparently if you log out and log in again, only then it works

See this thread for more info: https://opencrvsworkspace.slack.com/archives/C02P91N0E1W/p1717077997015809

**Comment by naftis** [comment]
Locally this happened for me once when the `/forms` endpoint wasn't properly responding, leading to the `getUser` (which is used to determine the default address of the user`) endpoint getting rate-limited. That should be a 1.6.0-specific issue (which shouldn't happen there either anymore) and not related to 1.5.0 though.

I'm unsure what are the steps to reproduce this at this point, will look into it if there's a specific case to investigate further.
