### ISSUE TITLE
Mark as duplicate button should be disabled when  reason is not provided

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7079]
**Bug description:**
Mark as duplicate button should be disabled when  reason is not provided

**Steps to reproduce:**
1. Login as RA/ Registrar
2. Go to Ready for review
3. Download> Assign> Review any duplicate record
4. Click Mark as duplicate
5. select tracking id
6. keep reason null> Observe  mark as duplicate button

**Actual result:**

mark as duplicate button is enabled and user is able to submit without reason 

**Expected result:**
mark as duplicate button should be disabled

**Screenshot/ Recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/53ea84e6-e782-4a96-9e26-6c94dd4c31f6

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by tiri39** [comment]
This bug is fixed.

https://github.com/opencrvs/opencrvs-core/assets/113257751/d7522b75-86dd-4df0-83a9-70878eaf27be
