### ISSUE TITLE
Zip/ postcode not showing in review page after submitting a declaration

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7080]
**Bug description:**
Zip/ postcode not showing in review page after submitting a declaration

**Steps to reproduce:**
1. Login as FA/RA/ Registrar
2. Declare any birth/ death/ marriage event
3. In any residential address select other
4. Enter all info including postcode/ zip
5. Submit the declaration
6. Now view/ review that declaration
7. Observe postcode/zip

**Actual result:**

Zip/ postcode not showing in review page after submitting a declaration

**Expected result:**
Zip/ postcode should show in review page after submitting a declaration

**Screenshot/ Recording:**
![zip missing](https://github.com/opencrvs/opencrvs-core/assets/94350336/876833c6-ce89-4499-bcad-42914a09957d)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by tiri39** [comment]
This bug is fixed.

![Image](https://github.com/opencrvs/opencrvs-core/assets/113257751/50a46dee-d76d-462d-88a9-e6df78e532f6)
