### ISSUE TITLE
Create test suit for Record Correction

### ISSUE THREAD

**Issue by jamil314** [opencrvs/opencrvs-core#7090]
- [x] Application 17 : Validate user can correct a record from Audit record page
- [x] Birth event correction 1 - 3
- [x] Birth event correction 4 - 6
- [x] Birth event correction 7 - 9
- [x] Death event correction 10 - 12
- [x] Death event correction 13 - 15
- [x] Death event correction 16 - 18

**Comment by SyedaAfrida** [comment]
@jamil314 https://docs.google.com/spreadsheets/d/1g0ReIDGw8lbHC6Am3O0A16S1y0jje8BZ/edit#gid=797586395

**Comment by SyedaAfrida** [comment]
fixed
