### ISSUE TITLE
VS Exports job not working 

### ISSUE THREAD

**Issue by tahmidrahman-dsi** [opencrvs/opencrvs-core#7091]
**Describe the bug**
Cron jobs for vs export generation are throwing errors in the metrics service

**Screenshots**
Kibana screenshot 

![image](https://github.com/opencrvs/opencrvs-core/assets/42269993/adf431ee-28b1-43d8-94f9-698e0f334d2d)

**Comment by tiri39** [comment]
This bug is fixed.

https://www.loom.com/share/a4d872fb75494e88b9950b0f09028668?sid=01054372-4450-4087-926b-e20cfeebc271

**Comment by tiri39** [comment]
This bug is fixed.

https://www.loom.com/share/a4d872fb75494e88b9950b0f09028668?sid=01054372-4450-4087-926b-e20cfeebc271
