### ISSUE TITLE
Block config routes to be publicly accessible

### ISSUE THREAD

**Issue by tahmidrahman-dsi** [opencrvs/opencrvs-core#7092]
### Description
Make all routes to handle internal service calls and select only endpoints which should be publicly available
...

### Dev tasks

- [ ] Update traefik config in [docker-compose.deploy.yml](https://github.com/opencrvs/opencrvs-countryconfig/blob/develop/infrastructure/docker-compose.deploy.yml)

**Comment by rikukissa** [comment]
@tahmidrahman-dsi this is closed in favour or https://github.com/opencrvs/opencrvs-core/issues/6279
