### ISSUE TITLE
In performance>Registration by status- Informant's relation and email address not showing in informant column

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7100]
**Bug description:**
In performance>Registration by status- Informant's relation and email address not showing in informant column

**Steps to reproduce:**
1. Login as RA/ Registrar/ National registrar
2. Click Performance
3. Click any link in registration by status
4. Observe informant column

**Actual result:**

In performance>Registration by status- Informant's relation and email address not showing in informant column,
Only phone number is showing

**Expected result:**
Should show relationship to child/ deceased, email address and phone number

**Screenshot/ Recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/52149acc-4f6e-495a-9fb4-e517c90f683d

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by Zangetsu101** [comment]
Same as #6157
