### ISSUE TITLE
Search query is not being saved in the Advanced Search results.

### ISSUE THREAD

**Issue by tiri39** [opencrvs/opencrvs-core#7110]
**Bug description:**
In the advanced search results for both birth and death, the search queries are not being saved by clicking Favorite button (star).

**Steps to reproduce:**

1. Login as FA/RA/ Registrar.
2. Select Advanced Search from the search bar and navigate to advanced search page.
3. In both tabs (birth and death) execute a search using some parameters.
4. In the search results page, click on the Favorite button (star).
6. In the modal, enter a name for the search query.
7. Click on 'Confirm'.

**Actual result:**
Shows toast - 'Sorry, something went wrong. Please try again.'
 
**Expected result:**
Should show toast- "Your advance search result has been bookmarked successfully". Also the query should be saved and shown in the sidebar.

**Screenshot/Recording:**
![ss3](https://github.com/opencrvs/opencrvs-core/assets/113257751/978519dd-13f2-434d-92a8-ffb6816dc31a)

**Tested on** - https://login.farajaland-qa.opencrvs.org/

**Version:**
V1.5.0

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/7117

**Comment by tiri39** [comment]
This bug is fixed.

https://github.com/opencrvs/opencrvs-core/assets/113257751/7cdba61f-7c6d-414a-a275-e728c01c8ad5
