### ISSUE TITLE
Error toast pops up when registrar tries to see Registration by status

### ISSUE THREAD

**Issue by Nil20** [opencrvs/opencrvs-core#7116]
Error toast pops up when registrar tries to see Registration by status

**To Reproduce**
Steps to reproduce the behaviour:

1. Login as a registrar 
2. Go to Performance
3. Under Registration by status, go to any status that has declarations
4. Inspect
5. See error

**Expected behaviour**
Shouldn't show error toast. Should show history of user involved declarations

**Actual behaviour**
Error toast pops up saying "Sorry, we couldn't load the content for this page"

**Screenshots**

![Image](https://github.com/opencrvs/opencrvs-core/assets/32668488/ffce49be-d757-4bb8-926d-1f859e97348a)

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/7118

**Comment by tiri39** [comment]
This bug is fixed.

https://github.com/user-attachments/assets/118fdb03-a68c-4bb4-a24c-14e49b2a6495
