### ISSUE TITLE
Performance: Min version of Performance Management so it is always right (or option to deprecate?)

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#7135]
Performance page that we have using React UI to UN standards contains elments which confuse countries that don't conform and they ask for improvements. Things like fees being configurable, no concept of late registration, no marriage event etc. 

Options:
1. We minimise the performance page to global most basic things so that is always right
2. We deprecate it - in place of data lake approach and use existing BI tools to create report like views
3. We support a highly flexible data views of performance using OpenCRVS UI custom components

**Comment by euanmillar** [comment]
@jpye-finch moved these requirements into https://github.com/opencrvs/opencrvs-core/issues/6261
