### ISSUE TITLE
In dashboard, record correction by type is not showing graph in widget

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7138]
**Bug description:**
In dashboard, record correction by type is not showing graph

**Steps to reproduce:**
1. Login as National system admin/ Performance manager/ National registrar
2. Click Dashboard
3. Observe  Record correction by type

**Actual result:**
In dashboard, record correction by type is not showing graph

**Expected result:**
 Should show graph

**Screenshot/ Recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/b820cf00-0f31-41f1-9fca-da163e8103d3

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by tahmidrahman-dsi** [comment]
fix in https://github.com/opencrvs/opencrvs-countryconfig/pull/139

**Comment by SyedaAfrida** [comment]
This ticket is fixed


![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/9117a00a-b4dd-4b64-83b4-8dcdeed2c8c8)
