### ISSUE TITLE
Unable to search correction requested records in advance search

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7139]
**Bug description:**
Unable to search correction requested records in advance search

**Steps to reproduce:**
1. Login as RA/ Registrar
2. Go to advance search
3. Select Registered from Status and any other parameter
4. Observe result

**Actual result:**
Unable to search correction requested records in advance search
Even unable to search with in review parameter

**Expected result:**
 Should be able to search when select registered status

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by naftis** [comment]
Is the quick fix to add 'correction requested' to the advanced search dropdown? @jpye-finch

**Comment by jpye-finch** [comment]
yes in this version as 'Correction Requested' is considered a status it should show in the dropdown. 

Note it is being considered that this won't be the case in the future. And another mechanism is required to find records pending corrections

**Comment by SyedaAfrida** [comment]
This ticket is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/0fc5287c-cfb2-44ca-84e2-abcb9124e69d
