### ISSUE TITLE
SMS notifications are not sent

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#7178]
**Describe the bug**

Currently, SMS notifications are not working. The defect is caused by SMS code still relying on copy file that do not exist anymore in the repository https://github.com/opencrvs/opencrvs-countryconfig/blob/develop/src/api/notification/sms-service.ts#L101-L118

Bug introduced in v1.4.1

Bug was introduced in this PR: https://github.com/opencrvs/opencrvs-farajaland/pull/843

**Comment by naftis** [comment]
Fix proposal in https://github.com/opencrvs/opencrvs-countryconfig/pull/164

**Comment by Zangetsu101** [comment]
@Zangetsu101 to test the logs related to this one

**Comment by Zangetsu101** [comment]
I looked at the flow and the bug was associated with the construction of the sms body which we can't test in an environment without actually enabling the sms notification.

**Comment by euanmillar** [comment]
Resolved
