### ISSUE TITLE
Heading Missing in Mobile View

### ISSUE THREAD

**Issue by tiri39** [opencrvs/opencrvs-core#7205]
**Bug description:**
In mobile view of 'Potential birth duplicate review'
-> the heading **'Is [Applicant name] (tracking id) a duplicate?'** is missing. 

Also in mobile view of Performance, the some page headings are missing.

**Steps to reproduce:**
1. Login as RA in mobile view.
2. Navigate to the record audit page of a potential duplicate record. 
3. Observe the heading.
4. Navigate to Performance.
5. Navigate to the following pages - 

- -> Registration by Status -> In Progress/ Ready for Review/ Sent for Updates/ Sent for Approval/ Ready to Print.
- -> (location - district office) -> Registrations -> Total -> click view
- -> (location - district office) -> Sources of registration -> Field Agents -> click view
- -> (location - Ibombo district, central province) -> Completeness rates -> Registered within 30 days/ within 1 year/ within 5 years -> view  
- -> (location - Ibombo district, central province) -> Registrations -> Total -> click view

6. Observe the headings.

**Actual result:**
Heading Missing in mobile view.

**Expected result:**
Heading should be visible in mobile view.

**Screenshot/ Recording:**
Heading in Web View -
![dup](https://github.com/opencrvs/opencrvs-core/assets/113257751/b0ea57b4-4f0b-4b70-b742-7677cec243e1)

Heading missing in Mobile View - 
![dup-heading missing](https://github.com/opencrvs/opencrvs-core/assets/113257751/f5999ce5-be1b-4251-8b4b-9634d2ac7682)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by eduffus** [comment]
I have downgraded the priority of this bug to low. Where web version works fine and functionality is unlikely to be used on mobile e.g. deduplication, then priority is "low".

**Comment by tiri39** [comment]
Partially fixed.

Bug still present in -  
## **-> Registration by Status -> In Progress/ Ready for Review/ Sent for Updates/ Sent for Approval/ Ready to Print.**




![Image](https://github.com/opencrvs/opencrvs-core/assets/113257751/ed9057c0-c141-4cd4-9d33-c080f432345d)

![Image](https://github.com/opencrvs/opencrvs-core/assets/113257751/e4617e25-91b6-485f-afc8-13f7af4c9e73)


## **-> (location - district office) -> Registrations -> Total -> click view**


![Image](https://github.com/opencrvs/opencrvs-core/assets/113257751/9a31f38b-b687-4bfa-af1a-1a4e0a3c9564)

![Image](https://github.com/opencrvs/opencrvs-core/assets/113257751/a11a32ee-349a-4225-8b81-ee348e5483bb)

## **-> (location - district office) -> Sources of registration -> Field Agents -> click view**


![Image](https://github.com/opencrvs/opencrvs-core/assets/113257751/7fc24749-79db-43d6-b0e4-cde2b5a8e3e3)

![Image](https://github.com/opencrvs/opencrvs-core/assets/113257751/d43ad437-35ff-4463-8c6b-4b8b39c30b4d)


## **-> (location - Ibombo district, central province) -> Completeness rates -> Registered within 30 days/ within 1 year/ within 5 years -> view**


![Image](https://github.com/opencrvs/opencrvs-core/assets/113257751/6926a821-e46e-44a5-9b00-acf83c3f10ac)

![Image](https://github.com/opencrvs/opencrvs-core/assets/113257751/08fb4870-7e31-4a12-81bf-1833b390db83)


## **-> (location - Ibombo district, central province) -> Registrations -> Total -> click view**


![Image](https://github.com/opencrvs/opencrvs-core/assets/113257751/c6b1507c-37ec-46e6-a00d-0046e045451c)

![Image](https://github.com/opencrvs/opencrvs-core/assets/113257751/645d68a5-1db5-4465-8945-898d62ff8610)

**Comment by tiri39** [comment]
This bug is fixed.

https://github.com/opencrvs/opencrvs-core/assets/113257751/7b97fb64-d497-4467-a8f4-148c69cb4c84
