### ISSUE TITLE
In Performance -> Completeness rates graph details page, table Sort is not working properly

### ISSUE THREAD

**Issue by tiri39** [opencrvs/opencrvs-core#7207]
**Bug description:**
In Performance -> Completeness rate, the table in graph details page is not being sorted properly.
-> Within 30 days (sort using - 'completeness rate' column not working)
-> Within 1 year (sort using - 'within 1 year' column not working)

**Steps to reproduce:**
1. Login as RA.
2. Navigate to Performance.
3. Select any location except office.
4. Click on 'view' of 'Registered within 30 days'.
5. In the graph details page, sort the table using the column 'completeness rate'.
6. Observe the sorted table.
7. Navigate to Performance again.
8.  Click on 'view' of 'Within 1 year'.
10. In the graph details page, sort the table using the column 'Within 1 year'.
11. Observe the sorted table.

 
**Actual result:**
The table is not sorted properly.

**Expected result:**
The table should be sorted properly both in ascending and descending order.

**Screenshot/Recording:**

https://github.com/opencrvs/opencrvs-core/assets/113257751/9ad99005-54af-4166-8534-2cee552498a7

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Version:**
V1.5.0

**Comment by tiri39** [comment]
Partially fixed. 

Sort based on 'completeness rate' works fine. **Works incorrectly** when sort is based on **'within 1 year / within 30 days / within 5 years'**



https://github.com/opencrvs/opencrvs-core/assets/113257751/495c6109-c3ad-46ad-ba3a-befb3529cfa1

**Comment by jamil314** [comment]
[New pr](https://github.com/opencrvs/opencrvs-core/pull/7248)
