### ISSUE TITLE
Run ElasticSearch reindex everytime the migrations run

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#7240]
1.6.0 is introducing a way to fully reindex ElasticSearch. Currently, the develop-branch handles reindexing via MongoDB's migrations. In other words, if the ES structure changes, a new MongoDB migration needs to be created to trigger the reindex.

The problem with this is that the same version might have multiple reindex-migrations when reindexing could be run only once. Also creating a reindex migration creates work that can be avoidable.

#### Improvement proposal

Run the ElasticSearch reindexing every time `run-migrations.sh` runs. The reindexing is fairly fast, and deployments are fairly scarce, so even if it sometimes runs without a distinctive need, it won't affect the deployments.

The risk is that when the database sizes grow, the reindexing can get slow. Per my testings, with ~1700 records it's ~6 seconds. That means 1 million records take 3529 seconds which is almost 1 hour. That is a long while but if done just a maximum of a few times a year, quite manageable. 

If that becomes a problem, the reindexing should be able to be sharded to run for example 10 threads in parallel, as the records and ElasticSearch documents are self-contained.

#### Dev tasks

- [x] Remove the migrations that reindex ElasticSearch
- [x] Add a reindexing call to `run-migrations.sh`

**Comment by Zangetsu101** [comment]
The QA need to select some records from the different workqueues and after deploy match them with previous data to make sure nothing went missing

**Comment by tiri39** [comment]
Found some issues - 

1. All records that were assigned (to any of the users) before the v1.6.0 deployment to QA, now has the initial OA. 

![Image](https://github.com/user-attachments/assets/83e334e9-8e0d-4a98-802b-ad0fb1ddf570)


2. RA can't review / update / unassign a record that is assigned to himself.

- can't unassign - 

![Image](https://github.com/user-attachments/assets/2264ff34-53b2-400e-a1b6-139483dfe33c)

- can't review - 

![Image](https://github.com/user-attachments/assets/e36fd3bb-017f-48ab-9976-a12a5e0f58e6)

- can't update -

![Image](https://github.com/user-attachments/assets/004cf38e-dba3-431f-a5d9-3885f9eaf7d5)

**Comment by tiri39** [comment]
Declaration (from **In Progress** workqueue) that are updated and then registered by Registrar, doesn't show the time of registration in the Ready to print work-queue. 


https://github.com/user-attachments/assets/5a48555c-cca5-40b3-a30c-e920a948d581

**Comment by makelicious** [comment]
Fixed the server issues related to running the script. It was never actually run. Will be fixed on next deployment

**Comment by tiri39** [comment]
This issue is not fixed yet - 

- If registrar updates any record (from in progress/ ready for review/ requires updates) before registering it, the time is not shown in the 'Registered' column in the Ready to Print workqueue.

<img width="697" alt="Screenshot 2024-08-06 124729" src="https://github.com/user-attachments/assets/2b7d5529-d332-477d-96e3-37eef4cd426b">

**Comment by tiri39** [comment]
"If registrar updates any record (from in progress/ ready for review/ requires updates) before registering it, the time is not shown in the 'Registered' column in the Ready to Print workqueue." - This bug is fixed.


https://github.com/user-attachments/assets/e8efdbf3-a9ec-4acd-9d66-ebdf4f45bfe3
