### ISSUE TITLE
Elasticsearch doesn't restore properly from backups

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#7259]
Everything else seems to work fine and backup processes pass successfully. Records from record search however cannot be found.

Can be reproduced:
- Staging (1.4.2)
- Custom environments (1.5.0)
- Custom environments (1.6.0)

### Analysis

Confirmed issue: nested elasticsearch directories in the backup restoration source

```
riku@farajaland-staging:~$ ls /data/backups/elasticsearch
elasticsearch
```

Once I changed it so that elasticsearch files are actually extracted directory to `/data/backups/elasticsearch`, everything started working again

**Comment by Zangetsu101** [comment]
Fixed in https://github.com/opencrvs/opencrvs-countryconfig/pull/170
