### ISSUE TITLE
Certificate preview fonts aren't loading in a deployed environment

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#7303]
![image](https://github.com/opencrvs/opencrvs-core/assets/1322608/883ce56c-b162-4c65-8c72-dc3435e82885)
Due to a content policy, the fonts are not loading when previewing a certificate.

Affects the preview SVG having a default serif font. In my machine, this happens in QA as well.
![image](https://github.com/opencrvs/opencrvs-core/assets/1322608/3a1bf9aa-f2e7-4616-b065-159189b11a94)

**Comment by SyedaAfrida** [comment]
Found console error in certificate preview page but no visual effects
![console error](https://github.com/opencrvs/opencrvs-core/assets/94350336/81ca9a72-f3a5-4753-a495-c5d4e8ae5e1b)

**Comment by SyedaAfrida** [comment]
This ticket is fixed


![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/b268d1d3-a68f-49d9-b9d5-2275d4b60da3)
