### ISSUE TITLE
Redis error in qa

### ISSUE THREAD

**Issue by jamil314** [opencrvs/opencrvs-core#7308]
**Describe the bug:**
In kibana log of `qa` environment, this error is throwing:

`Error: getaddrinfo ENOTFOUND redis://redis:6379`
`    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)`
`    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:128:17) {`
`  errno: -3008,`
`  code: 'ENOTFOUND',`
`  syscall: 'getaddrinfo',`
`  hostname: 'redis://redis:6379'`
`}`

The webhooks microservice is throwing the error continuously

**Comment by Zangetsu101** [comment]
@Zangetsu101 will be testing this one

**Comment by Zangetsu101** [comment]
Checked the logs in QA and webhooks has stopped complaining about redis
