### ISSUE TITLE
UI issue- In Performance> Registration by status table text are getting overlapped

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7313]
**Bug description:**
UI issue- In Performance> Registration by status table text are getting overlapped

**Steps to reproduce:**
1. Login as RA/Local registrar
2. Click Performance
3. Click any Registration by status link
4. Observe Informant and started column

**Actual result:**
When email address are slightly larger text are getting overlapped in informant and started column

**Expected result:**
 Should not overlap any text in in the table

**Screenshot/ Recording:**

![UI overlap in performance Registration by status page](https://github.com/opencrvs/opencrvs-core/assets/94350336/8f47af23-c7fc-436a-bec7-72c1af2a0a04)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by euanmillar** [comment]
We are deprecating this view so we can close this
