### ISSUE TITLE
Copy issue in Introduction page and certificate verified page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7324]
**Bug description:**
Copy issue in Introduction page and certificate verified page
**Steps to reproduce:**
1. Login as FA/RA/Local registrar
2. Start any declaration Birth/ death
3. Check introduction page
4. Again Scan any birth/ death QR code
5. Observe verbiage

**Actual result:**
Words are repeated

**Expected result:**
should not repeat. check screenshot

**Screenshot/ Recording:**

![intro](https://github.com/opencrvs/opencrvs-core/assets/94350336/3a1fb0e5-14ad-47ae-93ec-c281b8e20c1c)
![d-corup](https://github.com/opencrvs/opencrvs-core/assets/94350336/1fd791d6-d596-43a6-8d90-4b3b3b9d3b05)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

**Comment by tiri39** [comment]
This ticket is fixed.

![Image](https://github.com/opencrvs/opencrvs-core/assets/113257751/16d2aecc-2b8a-40bd-ac6f-c0f23b8d849a)


![Image](https://github.com/opencrvs/opencrvs-core/assets/113257751/cda8b977-f049-4d93-a138-37354ea8120c)
