### ISSUE TITLE
Sentry reports Redis got opened more than 10000 connections at a time

### ISSUE THREAD

**Issue by tahmidrahman-dsi** [opencrvs/opencrvs-core#7372]
From Sentry alert logs, it appears that Redis thrown error with max number of clients (by default which is [10000](https://redis.io/docs/latest/develop/reference/clients/#:~:text=Maximum%20Concurrent%20Connected%20Clients,The%20default%20is%2010%2C000%20clients.))  reached in Madagascar production environment 

https://opencrvs-foundation.sentry.io/issues/5583204907/?referrer=slack&notification_uuid=2ee83c5c-e6ce-4945-8014-2e1c570d8eb8&alert_rule_id=14932372&alert_type=issue

Potential reason: we might not be closing connections properly after we are done with redis db operations

**Comment by rikukissa** [comment]
I triaged this but there wasn't enough information unfortunately. Code looks fine. Propose we close this for now and reopen once it happens again.
