### ISSUE TITLE
Some parts of the PDF become black after printing certificate from Ready to Print workqueue

### ISSUE THREAD

**Issue by tiri39** [opencrvs/opencrvs-core#7385]
**Bug description:**
The certificate in the preview page looks fine, but most parts of it become black after it is printed.

**Steps to reproduce:**

1. Login as RA / registrar.
2. Navigate to the Ready to Print workqueue.
3. Assign any declaration.
4. Click Print -> Print in advance (or any other option from Certify Record page) -> Yes. print certificate -> Print

**Actual result:**
Most part of the certificate becomes black.

**Expected result:**
Certificate shouldn't be black.

**Screen recording:**

https://github.com/user-attachments/assets/0cbb45ec-5ae9-499d-b4b7-813ac2025648

**Tested on:** 
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
v1.6.0

**Comment by Zangetsu101** [comment]
https://github.com/opencrvs/opencrvs-countryconfig/pull/224

**Comment by tiri39** [comment]
The signatures of bride and groom become black in the PDF, looks fine in preview page.

- **Preview page -** 


![Image](https://github.com/user-attachments/assets/1b20652b-b268-447c-acc9-14951522dfba)


- **PDF -**


![Image](https://github.com/user-attachments/assets/01fef93c-e20e-4992-a66a-105fe5f2b515)

**Comment by jamil314** [comment]
https://github.com/opencrvs/opencrvs-countryconfig/pull/252

**Comment by SyedaAfrida** [comment]
This bug is fixed
https://github.com/user-attachments/assets/f37e7a77-c03f-4fd4-82d1-3ae28a371193
