### ISSUE TITLE
Create an Action menu

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#7390]
### Descriptions:
We don't have a consistent way to list all available actions that scales as more actions are add to OpenCRVS. 

This ticket is to:
- Create a reusable component called Action
- List all record actions based on the record scope and user scopes
- If the user is not assigned Then those actions that require the user to be assigned are disabled
- Shows who is assigned to the record
- Refactors Record Audit to use the Action component
- Desktop version is Medium
- Mobile version is Small

### Design

![Image](https://github.com/user-attachments/assets/d3e7fbb1-68f6-4cb9-a056-57c63ee43386)

Desktop:
![Image](https://github.com/user-attachments/assets/687c0064-c1a1-44c7-b788-d88e43369e5e)

Mobile:
![Image](https://github.com/user-attachments/assets/d8a132a5-d82e-4805-8a46-89268931b373)

**Variations based on record status:**
https://www.figma.com/design/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=19880-66203&t=dvwGBHOdODhytrIe-1

### ACs

GIVEN I am on the Record Audit view **unassigned** or it assigned to someone else
WHEN I click the Action menu
THEN show all the actions I have scopes
AND disable those i need to be assigned to action

GIVEN I am on the Record Audit view **assigned**
WHEN I click the Action menu
THEN show all the actions i have scopes 
AND have them all enabled

--

**Unassign another user** 
Currently this is done by clicking the profile. This moves it to the menu which feels more obvious:

GIVEN another user is assigned to a declaration 
WHEN the logged in user has the scope unassign-user 
THEN show the option Unassign
AND show the confirmation prompt to unassign the user

### Client front end action menu
- [ ] Use the dropdown button component build in https://github.com/opencrvs/opencrvs-core/issues/7390 and refactor record actions to use it

**Comment by naftis** [comment]
https://opencrvs.pages.dev/?path=/docs/controls-toggle-menu--docs
Toggle menu elements could be reused

Consider accessibility and keyboard navigation: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/

**Comment by jpye-finch** [comment]
@jamil314 

Design feedback:

- icon sizes should be medium
- Primary Button, SecondaryButton and tertiary button have been deprecated. Please use Button and add a variant to have an icon right - so we can use the chevron
- ResponsiveModel has been deprecated. Please use Dialog

Dialog has a bug atm with margin being added to the title... @naftis

**Comment by SyedaAfrida** [comment]
bugs found- #8049 , #8048
