### ISSUE TITLE
Multiple dividers in unexpected places in declaration forms

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7404]
**Bug description:**
Multiple dividers in unexpected places in declaration forms
- Birth event : mother & father's details page before usual place of residence
- Death event:  Spouse details page before usual place of residence
- Marriage event: after Place of marriage. Also change header of place of marriage

**Steps to reproduce:**
1. Login as FA/RA/Local registrar
2. Declare any event and observe

**Actual result:**
Multiple dividers in unexpected places in declaration forms
- Birth event : mother & father's details page before usual place of residence
- Death event:  Spouse details page before usual place of residence
- Marriage event: after Place of marriage. Also change header of place of marriage

**Expected result:**
Should remove dividers

**Screenshot/ Recording:**
![b2](https://github.com/user-attachments/assets/e384d976-f263-4369-98e3-b0580d4eba19)
![border](https://github.com/user-attachments/assets/3f7b1b88-e090-43a5-8925-43f6dff8bc9c)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.6.0

**Comment by Siyasanga** [comment]
Link to the PR https://github.com/opencrvs/opencrvs-farajaland/pull/1081

**Comment by jamil314** [comment]
[country config pr](https://github.com/opencrvs/opencrvs-countryconfig/pull/284)

**Comment by SyedaAfrida** [comment]
This bug is fixed

![Image](https://github.com/user-attachments/assets/fb39aa77-4091-47af-b1c9-0d68cbe927fc)
