### ISSUE TITLE
In Advanced Search, the 'Edit' link (in the 'Exact date unknown' section) is at the edge and not working

### ISSUE THREAD

**Issue by tiri39** [opencrvs/opencrvs-core#7417]
**Bug description:**
When any date range is chosen in the custom date field in advanced search, an edit button appears beside the selected date range. The edit button is at the edge and is not working properly.

**Steps to reproduce:**

1. Login as FA/RA/ registrar.
2. Navigate to advanced search.
3. Select any date range in the 'Exact date unknown' link.
4. Observe the edit link.

**Actual result:**
When the 'Edit' link is clicked, it just checks/unchecks the selected date range.

**Expected result:**
The calendar should be opened and user should be able to select date range when the 'Edit' link is clicked.

**Screen recording:**

https://github.com/user-attachments/assets/54c309a6-9074-45a0-aa05-30321086f329

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
v1.6.0

**Comment by Zangetsu101** [comment]
![Image](https://github.com/user-attachments/assets/aeab79fa-8826-4ce2-be35-962150840a73)

**Comment by SyedaAfrida** [comment]
**Bug:** Though this bug is fixed for web view, this is not properly fixed for mobile view. Cannot properly see edit option in mobile view

https://github.com/user-attachments/assets/b20e7ee0-88a3-4a50-bbe7-7d2b51c7f3c3

**Comment by SyedaAfrida** [comment]
This bug is fixed 

![Image](https://github.com/user-attachments/assets/72133266-2397-4bf5-bf78-4e175b3b43ae)
![Image](https://github.com/user-attachments/assets/8df32ad7-c7d3-4b8f-90d2-beb1f637ca1a)
