### ISSUE TITLE
Signatures (bride/ groom/ witness/ informant) are not being updated.

### ISSUE THREAD

**Issue by tiri39** [opencrvs/opencrvs-core#7462]
**Bug description:**
When an user tries to update the signature section:
In complete declarations, the updated signatures are not replacing the previous ones.
In incomplete declarations, where signature fields were left blank, the signatures are still blank after updating them.

**Steps to reproduce:**

For complete declarations - 
1. Login as FA.
2. Create a complete declaration and send it for review.
3. Login as RA.
4. Navigate to the 'ready for review' and download the previous declaration and observe it's review page.
5. Scroll down to the signature section.
6. Update the signature.
7. Click send or approval.
8. Login as registrar.
9. Navigate to the 'ready for review' and download the previous declaration and observe it's history.
10. Observe the review page of that declaration.

For incomplete declarations-
1. Login as FA.
2. Create an incomplete declaration (fill every required field except signature section) and send it for review.
3. Login as RA.
4. Navigate to the 'in progress' and download the previous declaration and observe it's review page.
5. Scroll down to the signature section.
6. Update the signature.
7. Click send or approval.
8. Login as registrar.
9. Navigate to the 'ready for review' and download the previous declaration and observe it's history.
10. Observe the review page of that declaration.

**Actual result:**
- The signature section shows the previous signatures for complete declarations and blank for incomplete declarations, not the updated one.
- The declaration history section doesn't have 'updated' action.

**Expected result:**

- Registrar should see the updated signatures in the review page. 
- If bride's/groom's signature is updated then Registrar should see the updated signature in the certificate preview page.
- The history section of that declaration should have an 'updated' action.

**Screen recording:**

For complete declaration -

https://github.com/user-attachments/assets/6320d600-1218-4be3-9316-315f7997a0fe

For incomplete declaration -

https://github.com/user-attachments/assets/51f1b536-4a49-4298-a6c3-89cb697314f8

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
v1.6.0

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/7579

**Comment by SyedaAfrida** [comment]
This ticket is not fixed for V1.5.1
![Image](https://github.com/user-attachments/assets/8f52d465-778f-4453-a90d-5b5a89dd62e2)

**Comment by SyedaAfrida** [comment]
This bug is fixed

https://github.com/user-attachments/assets/6a64ca79-fbc0-4a00-a7ad-31a5afa550a2

**Comment by SyedaAfrida** [comment]
This ticket is fixed

https://github.com/user-attachments/assets/f7ee26c0-df05-46ac-b22d-7a7f6e45d2cd

https://github.com/user-attachments/assets/9ab0d1b3-9b58-4e2c-a258-5dfaa620ca8d
