### ISSUE TITLE
Fix migration issues for countries migrating from 1.2

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#7464]
If countries updates its system from OpenCRVS 1.2 to the latest minor version, they will encounter two issues when running migrations:

- **Mongoose** creates empty collections before migrations are run, causing the migrations to fail when attempting to create the same collections. Core points are detailed [here](https://github.com/opencrvs/opencrvs-core/blob/develop/packages/migration/src/migrations/user-mgnt/20221229110512-modify-user-roleAndtype-fieldName.ts#L179) and [here](https://github.com/opencrvs/opencrvs-core/blob/develop/packages/migration/src/migrations/user-mgnt/20221229110512-modify-user-roleAndtype-fieldName.ts#L265). Both of these statements need to be wrapped in `if (!collectionExists) { /*  execute */ }`.

- Creating population estimates per day will fail [here](https://github.com/opencrvs/opencrvs-core/blob/e0d02579c4fc6751338e620da368d763afdeeee5/packages/migration/src/migrations/hearth/20230221105416-create-performance-views.ts#L766) if there are locations with identical names in the locations dataset. Use a more unique `_id` identifier instead of just `name` + `date`. Verify that Metabase queries are not directly referencing this `_id` field and that dashboards still work correctly after this change. This bug might also exist in the [Metabase data refresher](https://github.com/opencrvs/opencrvs-core/blob/c944f93ad666092e1e5231ec3d10dc532cd2902e/packages/metrics/src/features/performance/viewRefresher.ts#L46).
- `_type` is not supported anymore after ES 6. Let's drop it from all queries: [reference](https://github.com/opencrvs/opencrvs-core/blob/release-v1.5.1/packages/migration/src/utils/elasticsearch-helper.ts#L30). [reference 2](https://github.com/opencrvs/opencrvs-core/blob/release-v1.5.1/packages/migration/src/utils/elasticsearch-helper.ts#L98)

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/7480

**Comment by SyedaAfrida** [comment]
This ticket is fixed and tested in madagascar dev environment V1.6.0
