### ISSUE TITLE
Move manifest.json into country config

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#7466]
![Image](https://github.com/user-attachments/assets/b0d430d8-8aa2-40e8-9479-b456bad676c9)

It's not possible to change the name of the PWA because the manifest.json is in the client package as opposed to country config.  Is there any way that this can be configurable?

## Tech design
- [x] Create the following endpoint to country config package `GET /assets/:filename`. This endpoint should serve static files from a directory inside country config package. For instance `/static` or /src/static`. Copy both `manifest.json` and app icons into the directory. Note that OpenCRVS still should have at least a default manifest.json so build works.
- [x] To hide internal implementation details from the client, let's make the client query the same exact endpoints it uses today to fetch the files but add HTTP server logic to serve files internally from country config. 
Copy `infrastructure/nginx-default.conf` to `packages/client/nginx.conf` and change [this line](https://github.com/opencrvs/opencrvs-core/blob/release-v1.5.1/packages/client/Dockerfile#L42) accordingly. In the new nginx configuration, define the the following config before `location /`

```
    location /manifest.json {
        proxy_pass http://countryconfig:3040/static/manifest.json;
    }

    location /images/ {
        proxy_pass http://countryconfig:3040/static/images/;
    }
```

these blocks redirect client queries to the defined urls directly to country config.
- [x] For development time proxying, you need to modify Vite configuration. Use following code as reference

```ts
import { defineConfig } from 'vite';

export default defineConfig({
  server: {
    proxy: {
      '/manifest.json': {
        target: 'http://localhost:3040/static/',
        changeOrigin: true
      },
      '/images/': {
        target: 'http://localhost:3040/static/',
        changeOrigin: true
      }
    }
  }
});
```
- [x] Test locally that the proxy works properly by navigating to http://localhost:3000/manifest.json and http://localhost:3000/images/icons/icon-128x128.png
- [x] For Farajaland, change app name to `Farajaland CRS`
- [x] Deploy to dev, verify following urls work and return a value from country config
  - http://register.farajaland-dev.opencrvs.org/manifest.json
  - http://register.farajaland-dev.opencrvs.org/images/icons/icon-128x128.png

**Comment by rikukissa** [comment]
Related https://github.com/opencrvs/opencrvs-core/issues/7177

**Comment by naftis** [comment]
@tareq89 When building the client with `yarn build` we get this:
```
PWA v0.20.0
WARNING: "theme_color" is missing from the web manifest, your application will not be able to be installed
```

Could you check if you can fix this at the same time?

**Comment by rikukissa** [comment]
@tareq89 @naftis I also updated the task description as it's probably so that manifest.json also needs to be in core, regardless it also being in CC

>Copy both `manifest.json` and app icons into the directory. Note that OpenCRVS still should have at least a default manifest.json so build works

**Comment by tareq89** [comment]
> @tareq89 When building the client with `yarn build` we get this:
> 
> ```
> PWA v0.20.0
> WARNING: "theme_color" is missing from the web manifest, your application will not be able to be installed
> ```
> 
> Could you check if you can fix this at the same time?

When this error occurs? can you give me steps to reproduce this? looks like it happens when you try to install the app in the mobile, is it?

**Comment by naftis** [comment]
> > @tareq89 When building the client with `yarn build` we get this:
> > ```
> > PWA v0.20.0
> > WARNING: "theme_color" is missing from the web manifest, your application will not be able to be installed
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could you check if you can fix this at the same time?
> 
> When this error occurs? can you give me steps to reproduce this? looks like it happens when you try to install the app in the mobile, is it?

For me it happens when I run `yarn build` in client:
```
➜  client git:(ocrvs-7439) ✗ yarn build
yarn run v1.22.22
$ VITE_APP_VERSION=$VERSION NODE_OPTIONS=--max_old_space_size=8000 vite build
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
vite v5.3.1 building for production...
....
PWA v0.20.0
WARNING: "theme_color" is missing from the web manifest, your application will not be able to be installed
....
Done in 32.73s.
```

**Comment by Zangetsu101** [comment]
@tareq89 Could you please finish up cherry-picking the changes? For core both 1.6 & 1.5.1 are remaining. For countryconfig only 1.5.1 is left
