### ISSUE TITLE
Duplicate records created on the server at low connection speeds

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7477]
**Bug description:**
Multiple records sent to the outbox at low connection speeds may result in duplicates or multiple recordings.

**Steps to reproduce:**
1. Login as FA/RA/Local registrar
2. Declare any event in slow connectivity
3. Observe

>You can also reproduce this by looking up the exact HTTP request made when submitting a record and sending it twice

**Another technical way to reproduce**

1. Create a record, wait until it gets sent to the server (only way to know is by looking at the server logs really)
2. Quickly reload the page
3. Now the record is processed by the server but also in your inbox 

**Actual result:**
Sometimes, it shows that the record is actually submitted properly and appearing in sent of review workqueue. But still the record stays in the outbox. After couple of minutes or hour, the outbox record is again submitted, which causes to create duplicate of the original record

**Expected result:**
When a record is submitted and appearing in another workqueue, it should not appear in outbox.

**Screenshot/ Recording:**

![Screenshot 2024-07-22 at 15-34-24 VENEEM](https://github.com/user-attachments/assets/2547027a-6064-4263-a25d-3c99422c9c01)
![Screenshot 2024-07-22 at 15-36-10 VENEEM](https://github.com/user-attachments/assets/759d24d5-244f-4afe-89f6-2f07404e27e9)
![Capture d’écran de 2024-07-22 15-36-16](https://github.com/user-attachments/assets/78a2b93c-e11f-4fe6-892f-7e4e81498c78)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

## Tech tasks
- [ ] Research why the `draftId` sent as part of the `createBirthRegistration` payload isn't used by the server to not start additional processing. Fix the issue so Gateway returns a clear error indicating that the payload has already been processed. Client should then just treat it as it had been successfully sent. Notice that the code flow needs to not only verify if the record is in MongoDB. It needs to also let the request flow to search service which can then verify the record already existing in Elasticsearch. This is to ensure the client can retry sending the creation request even if the record was half-written the last time. https://github.com/opencrvs/opencrvs-core/issues/6208 is related.
- [ ] Research in what conditions client can send a new record as `markBirthAsRegistered`. Sometimes this incorrectly happens when submitting a brand new declaration as a registrar. How should client behave when it receives a "User has been unassigned" error so that we wont lose data (Still needs tech design) .

**Comment by Zangetsu101** [comment]
@rikukissa We had put this back to properly tech design before implementing but looks like a fix is needed for Madagascar/Somalia

**Comment by rikukissa** [comment]
@Zangetsu101 can you elaborate on what is the root cause of this? I can help with the design

**Comment by Zangetsu101** [comment]
Sure, the root cause would be that while elasticsearch is indexing a declaration, another one comes in, causing the duplicate check to fail

**Comment by Zangetsu101** [comment]
https://github.com/opencrvs/opencrvs-core/blob/4ee08fbab548b0c3f191406d57f7222d63ebd713/packages/workflow/src/records/handler/create.ts#L233-L241
Also there is a check for same declaration coming in twice which should have prevented this scenario but somehow it didn't :thinking:

**Comment by rikukissa** [comment]
I'm a bit confused as well. Is the bug that a user has two very similar (potentially duplicate) records in their outbox while they are offline and once they come online, both are sent time wise so close to each other that the first doesn't get registered as to ES before the second one performs its duplicate check?

**Comment by Zangetsu101** [comment]
> I'm a bit confused as well. Is the bug that a user has two very similar (potentially duplicate) records in their outbox while they are offline and once they come online, both are sent time wise so close to each other that the first doesn't get registered as to ES before the second one performs its duplicate check?

yes both these cases looked similar to me

**Comment by eduffus** [comment]
> I'm a bit confused as well. Is the bug that a user has two very similar (potentially duplicate) records in their outbox while they are offline and once they come online, both are sent time wise so close to each other that the first doesn't get registered as to ES before the second one performs its duplicate check?

No this is not the issue. The issue is that in low connectivity situations from one declaration 2 records are created on the server instead of one. It has nothing to do with the de-duplication functionality.
@SyedaAfrida has seen this and her analysis is: The record is actually submitted properly and appearing in sent for review workqueue. But still the record stays in the outbox. After some time the outbox record is again submitted, which causes to create a duplicate of the original record.
Logically it would seem due to the following:
- Record in Outbox should be removed when the record has been fully processed on the server side
- If processing does not fully complete on the server then the transaction should be rolled back
- In this case it would seem that the record is fully processed on the server but the record in the outbox remains and can be resubmitted (presumably due to intermittent connectivity)

**Comment by rikukissa** [comment]
Ok, thanks for the clarification. What most likely happens is
1. Client sends the records to the backend
2. While backend is processing the record, client's connection drops
3. Client interprets this incorrectly as a failed submission. Now we don't know if the record was stored or not.

You logic is correct, and its really the second point where we aren't fully meeting the requirement. 

This ticket is related and should be prioritised for tech design and implementation to fix the issue properly: https://github.com/opencrvs/opencrvs-core/issues/6208

**Comment by rikukissa** [comment]
Will need to be applied to 1.6.0 milestone as well.

**Comment by rikukissa** [comment]
Potentially related bug I found while trying to triage this:

### Record remain in outbox forever
<img width="1323" alt="image" src="https://github.com/user-attachments/assets/962695de-fbc3-4c86-ab6c-1636aca79d47">

1. Create a declaration with a very slow connection
2. Once the server receives the record, reload page on the client
3. You should now see the record both in the workqueue it was meant to go + in outbox

**Comment by SyedaAfrida** [comment]
This bug is fixed
https://github.com/user-attachments/assets/461ea43b-cd8a-47f0-a520-ed3795f87f12
