### ISSUE TITLE
When any user's role is updated, the updated role is not shown for that user's actions in the history section of a declaration's record audit page.

### ISSUE THREAD

**Issue by tiri39** [opencrvs/opencrvs-core#7495]
**Bug description:**
If any user's role is updated, the history section of a declaration shows the previous role instead of the updated role.

**Steps to reproduce:**

1. Login as National System Admin.
2. Edit any of the users (who can create declarations) role.
3. Login as that user and perform any action on any declaration.
4. Navigate to the record audit section of that declaration.
5. Observe the previously performed action in the history section.
6. Observe the user role of that action.

**Actual result:**
Shows the previous user role.

**Expected result:**
Should show the updated user role.

**Screenshot / Recording:**

https://github.com/user-attachments/assets/7cfb149c-82e2-4810-88a3-074697bd370a

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
v1.6.0

**Comment by SyedaAfrida** [comment]
This bug is fixed

https://www.loom.com/share/15f9a4a2995c4bc2bc98740cbf4865f6?sid=f783492e-c2b2-43da-b2c1-0f3727dd4a4a
