### ISSUE TITLE
Modify configuration to make informant signature mandatory in core

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7504]
### Description
Currently Informant signature is not mandatory in OpenCRVS core. To confirm some Somalia bug existing in core, need to change the configuration

### Design

![infSig](https://github.com/user-attachments/assets/b72fa617-561a-45ca-b8ef-21daa7418b01)

### Dev tasks

- [x] Make the signature required by updating form config in farajaland
- [x] deploy to qa with the new changes after getting it merged to release-v1.6.0

**Comment by tareq89** [comment]
There is a related change in the core: https://github.com/opencrvs/opencrvs-core/pull/7563

**Comment by tiri39** [comment]
Informant signature has been made mandatory.

![Image](https://github.com/user-attachments/assets/10f41caf-7fce-4259-9fb1-42a1d9fd0206)
