### ISSUE TITLE
When place of event is changed from Health institution to Residential address or vise versa, invalid information are shown, in correction request page

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7505]
**Bug description:**
When place of event is changed from Health institution to Residential address or vise versa, invalid information are shown, in correction request page

**Steps to reproduce:**
1. Login as RA
2. Correct any record by changing place of event is changed from Health institution to Residential address or vise versa
3. Logout
4. Login as Registrar
5. Click review in Ready for review page for that record
6. Observe original vs corrected table and scroll down in the record

**Actual result:**
In original vs corrected table is showing - in both columns
In the review section all the data in place of event is showing bank

**Expected result:**
In original vs corrected table should show health institution name as well as residential address name
Review section should not be blank

**Screenshot/ Recording:**

https://github.com/user-attachments/assets/2a6cbb2f-0069-44fa-8911-4690941344cd

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.6.0

**Comment by eduffus** [comment]
@SyedaAfrida if the record is still updated correctly but the summary view is wrong, this can be downgraded to medium.

**Comment by SyedaAfrida** [comment]
@eduffus Unfortunately the record also don't get updated properly

**Comment by Zangetsu101** [comment]
@tareq89 if you are unable to reproduce this please attach a recording of your finding and we can forward this to QA

**Comment by onnee04** [comment]
Couldn't reproduce that issue. Seems fine.

https://github.com/user-attachments/assets/c1f5dae0-ded9-4c07-bc56-cd663954dc92
