### ISSUE TITLE
Health facility name not found in dropdown if update/correction is made from health facility to residential address in another declaration

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7528]
**Bug description:**
Health facility name not found in dropdown if update/correction is made from health facility to residential address in another declaration

**Steps to reproduce:**
1. Login as RA/ Registrar
2. Update/Correct any record by changing place of event from Health institution to Residential address 
3. Make correction request/ correct record
4. Try make a declaration 
5. Observe the health facility name appearing in Place of birth / death
6. Refresh the page/logout and login again
7. Try make a declaration 
8. Observe the health facility name appearing in Place of birth / death

**Actual result:**
Health facility name not found in dropdown if correction is made from health facility to residential address in another declaration

**Expected result:**
should show all health facility names

**Screenshot/ Recording:**

![health facility](https://github.com/user-attachments/assets/d57e084b-af93-4478-bffc-3cf692bcb6c2)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.6.0

**Comment by onnee04** [comment]
Fixed

https://github.com/user-attachments/assets/93646883-bee2-448b-81ce-c87f3855a2df
