### ISSUE TITLE
For declaration where place of event/ residence is selected as Other than Farajaland, then Address line1,2 &3 does not update properly

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7531]
**Bug description:**
For declaration where place of event/ residence is selected as Other than Farajaland, then Address line1,2 &3 does not update properly

**Steps to reproduce:**
1. Login as RA/ Registrar
2. Try to update / correct any record
3. Change Place of event/ resident to Other
4. Fillup all fields including Address Line 1, 2,3
5. Submit
6. Again Review that record

**Actual result:**
Address line1,2 &3 does not update properly

**Expected result:**
Address line1,2 &3 should update properly

**Screenshot/ Recording:**

https://github.com/user-attachments/assets/a404b891-d2de-4a96-983a-8d9a6ce10eb2

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.6.0

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/pull/7555

**Comment by SyedaAfrida** [comment]
This bug is fixed

https://github.com/user-attachments/assets/4ac2388f-90bd-47c2-a9bf-5d6361915b83
