### ISSUE TITLE
Outbox issue for Registrar in record correction flow.

### ISSUE THREAD

**Issue by tiri39** [opencrvs/opencrvs-core#7583]
**Bug description:**
When registrar tries to correct a declaration (that wasn't corrected before), it get gets stuck at first. After clikcing 'retry', the declaration leaves outbox and a toast pops up saying - 'you are unassigned from [tracking id]'. If registrar tries to correct this record again, it gets stuck in the outbox again. This time, the record doesn't leave outbox when 'retry' is clicked.

**Steps to reproduce:**

1. Login as Registrar.
2. Create a declaration and register it.
3. Download that declaration from ready to print workqueue.
4. Click on 'correct record' from the record audit page.
5. Change the value of any field in the correction flow.
6. Navigate to the correction summary page and click on 'make correction'.
7. In the 'Correct record ?' modal, click on 'confirm'.
8. Observe the outbox.
9. Click on 'retry'
10. Observe the toast.
11. Navigate to ready to print and try to correct that record again.
12. Observe the outbox and click on 'retry'

**Actual result:**
At the first time while correcting, the record gets stuck in outbox, but leaves when 'retry' is clicked. At the second time in correction flow, the record is stuck in outbox and doesn't leave outbox even after clicking 'retry'

**Expected result:**
The record shouldn't get stuck in outbox. Should leave the outbox for both first and second time correction flow.

**Screenshot / Recording:**

https://github.com/user-attachments/assets/37ea0648-b290-432e-a72b-a75bdf733bb5

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
v1.6.0

**Comment by jamil314** [comment]
[#7600](https://github.com/opencrvs/opencrvs-core/pull/7600)

**Comment by onnee04** [comment]
this issue is fixed

https://github.com/user-attachments/assets/94c2da61-151f-40a6-9b72-b883a63f852a
