### ISSUE TITLE
Add the `Sync fork` -button to opencrvs-farajaland instead of opencrvs-countryconfig 

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#7596]
Having the Sync fork button in Farajaland would help us with syncing the base changes from country config to Farajaland. Do we need to ask GitHub customer service or can we do it ourselves?

**Comment by rikukissa** [comment]
Sent a support request
<img width="1012" alt="image" src="https://github.com/user-attachments/assets/d7d62e27-1fce-453d-87eb-bdeb18e8f7c3">

**Comment by naftis** [comment]
Thanks Riku and Github. Closing this as resolved.
