### ISSUE TITLE
A National/Local System Administrator was able to deactivate themselves from the system

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#7691]
Bug description:
A National/Local System Administrator was able to deactivate themselves from the system

Steps to reproduce:

As a National System Administrator or Local System Administrator

1. Navigate to Team and user list as the "National System Admin" or "Local System Administrator"
2. Search for yourself
3. Click the context menu next to yourself
4. Click on deactivate
5. Provide a reason  and confirm

Actual result:
Local/National System Administrator is deactivated straight away and removed from the system. Their session stops immediately

Expected result:
A Local/National System Administrator must not be able to deactivate themselves

Tested on:

1.6.0

**Comment by euanmillar** [comment]
PR: https://github.com/opencrvs/opencrvs-core/pull/7996

**Comment by Zangetsu101** [comment]
@jpye-finch maybe a couple of more items in the dropdown e.g. send username reminder, onboarding invite etc. don't make sense for the current user?

**Comment by onnee04** [comment]
@euanmillar mentioned issue is fixed. Now National/local system administrator can not be able to deactivate themselves.
But currently local system admin can deactivate national system admin/national registrar (if they are from same office). Also local system admin can not see role for national system admin/national registrar.

https://github.com/user-attachments/assets/8eee7507-0093-481d-9575-e1ccc1c5a748
