### ISSUE TITLE
Unable to change email address & phone number from settings as 2FA code not being sent to email

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7694]
**Bug description:**
Unable to change email address & phone number from settings as 2FA code not being sent to email

**Steps to reproduce:**
1. Login as any user
2. Go to settings
3. Click change in email/ phone number
4. Enter new email address/ phone number> Continue
5. Wait for verification code to receive through email

**Actual result:**
No verification code is sent to the email address

**Expected result:**
should send 2FA code through email

**Screenshot/ Recording:**

https://github.com/user-attachments/assets/b2d3a7f7-3fde-433b-a271-ac5a16dd4084

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.6.0

**Comment by onnee04** [comment]
Fixed 

https://github.com/user-attachments/assets/291ccaf3-a78b-4b41-82c2-b91888ec7c8c
