### ISSUE TITLE
Local system admin should not be able to create National System admin and National registrar

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7698]
**Bug description:**
Local system admin should not be able to create National System admin and National registrar

**Steps to reproduce:**
1. Login as local system admin
2. Go to Team
3. Click on Create new user
4. Observe the drop down options in roles

**Actual result:**
Local system admin has the option to create National System admin and National registrar

**Expected result:**
Local system admin should not be able to create National System admin and National registrar

**Screenshot/ Recording:**

https://github.com/user-attachments/assets/00ad3ed8-a767-4e9c-b55f-68a5b5911745

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.6.0

**Comment by euanmillar** [comment]
PR: https://github.com/opencrvs/opencrvs-core/pull/7996

**Comment by onnee04** [comment]
Fixed

https://github.com/user-attachments/assets/f69d8450-7636-454e-baea-29488be9ac75

**Comment by onnee04** [comment]
@euanmillar @Siyasanga 
But currently local system admin can deactivate national system admin/national registrar (if they are from same office). Also local system admin can not see role for national system admin/national registrar.

https://github.com/user-attachments/assets/b8a2f43c-7dfe-4849-bd7c-2f0c50d7e60f

**Comment by euanmillar** [comment]
@onnee04 @rikukissa @eduffus  we have discussed this in the IET team.  As the concept of a Local System Admin and a National System Admin is going to be deprecated in Custom Users & Scopes, we feel that the effort involved to fix this particular bug related to a Local System Admin being unable to read the role titles for a National Registrar, National System Admin  in 1.6.1 is not worth resolving.  It is our view that this is acceptable as a known issue: https://github.com/opencrvs/opencrvs-core/issues/7698#issuecomment-2520060015

**Comment by eduffus** [comment]
Setting to "Closed as not planned - won't fix" as above
