### ISSUE TITLE
When try to print a certificate registered in another location, Place of location is showing wrong

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7759]
**Bug description:**
When try to print a certificate registered in another location, Place of location is showing wrong

**Steps to reproduce:**
1. Login to any registrar of any location other than ibombo
2. Search for a registered declaration of ibombo
3. Click Print> Continue to certificate preview page
4. Observe Place of registration

**Actual result:**
Office name is correct but the location is wrong

**Expected result:**
 should show correct place of registration

**Screenshot/ Recording:**

![Image](https://github.com/user-attachments/assets/afb100cd-ad54-4ac3-92d6-a1d04f228476)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.6.0

**Comment by Zangetsu101** [comment]
It does say that it was registered by Kennedy Mweene, so the place of registration should be right in that case no?

**Comment by onnee04** [comment]
fixed
![Image](https://github.com/user-attachments/assets/1da236ef-5f6f-407b-bd86-75f5d9e69f07)

![Image](https://github.com/user-attachments/assets/9291b2d1-0a53-4dc4-804e-fea4d373491e)

![Image](https://github.com/user-attachments/assets/8cefd33e-c5db-4b09-bb65-cbb6ba87886f)
