### ISSUE TITLE
In marriage declarations, 'Phone number' and 'Email' field of Informant's details page not working properly when no option is chosen for 'Informant type' dropdown.

### ISSUE THREAD

**Issue by tiri39** [opencrvs/opencrvs-core#7771]
**Bug description:**
While creating marriage declarations, if 'Informant type' is not chosen, 'Phone number' and 'email' field of Informant's details page not taking inputs properly.

**Steps to reproduce:**
1. Login as FA/RA/reg.
2. Start creating a marriage declaration.
3. Don't select any option for 'Informant type' dropdown.
4. Enter any character/ paste anything in the 'phone number' or 'email' field of Informant's details page.
5. Observe.

**Actual result:**
When anything is entered / pasted at first, the form flashes and the input disappears. After that number/mail can be input normally.

**Expected result:**
The fields should take input properly.

**Screenshot/Recording:**

https://github.com/user-attachments/assets/30585ae2-9899-430a-b218-2ebcdbb7e97b

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Version:**
v1.6.0

**Comment by tareq89** [comment]
The main issue is that "When anything is entered/pasted at first, the form flashes and the input disappears." I have tried to recreate the problem in different ways, but I have not been able to.


Note that I checked it in Mac and Chrome, please confirm if the issue is Linux/windows or any browser specific.

**Comment by tiri39** [comment]
This bug doesn't seem to exist anymore.
Tested in Windows and Chrome (the same one that was used when the bug was found).

https://github.com/user-attachments/assets/7c3bc2ea-cca5-49ca-b902-ac275e8fffa8
