### ISSUE TITLE
Multiple fields showing wrong values when informant type is changed during correction record

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7781]
**Bug description:**
Multiple fields showing wrong values when informant type is changed during correction record
1. In birth correction, when informant type is changed from mother to anyone other than father eg. Brother/ sister
2. In birth correction, when informant type is changed from father to anyone other than mother eg. Brother/ sister
3. In death correction, when informant type is changed from spouse to anyone eg. Brother/ sister

**Steps to reproduce:**
1. Login to any registrar 
2. Go to Ready to Print> Correction record
3. Change informant type as mentioned above
4. Submit
5. Compare correct record modal and view

**Actual result:**
1) Multiple fields showing wrong values when informant type is changed during correction record
1. In birth correction, when informant type is changed from mother to anyone other than father eg. Brother/ sister
2. In birth correction, when informant type is changed from father to anyone other than mother eg. Brother/ sister
3. In death correction, when informant type is changed from spouse to anyone eg. Brother/ sister

2) In correction summary page when type id is changed then showing blank for orginal values

**Expected result:**
1) When informant type is changed, all the section values (informant, mother, father, spouse) should show properly
2) In correction summary Id type should not be blank for original coulmn, should show passport/ brn etc

**Screenshot/ Recording:**

https://github.com/user-attachments/assets/9b13e72a-2117-47d0-83b7-a9de3e2f69ff

_**Note:** This bug exists in V1.5.1. So need to cherry pick_

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.6.0, V1.5.1

**Comment by tiri39** [comment]
Not Fixed.

Birth - 
- when informant is changed (father/ mother -> any other option) : informant details are corrected properly, but the previous informant's (father / mother) is also changed and replaced with the informant details.

https://github.com/user-attachments/assets/2dd5892d-c4bd-40e2-8f11-0390ad43b2aa

Death -

- when informant is changed (spouse -> any option except 'someone else') : declration can't be corrected, gets stuck in outbox.

https://github.com/user-attachments/assets/47c392fd-f896-4d1a-ad38-53c51bb934f4

- when informant is changed (spouse -> 'someone else'), informantion are not corrected properly. 

https://github.com/user-attachments/assets/261b966b-4b3c-4546-8d9c-f5847ee3e6e2

**Comment by tiri39** [comment]
Fixed. 

- when informant is changed (father/ mother -> any other option) : informant details are corrected properly, but the previous informant's (father / mother) is also changed and replaced with the informant details. - FIXED.

https://github.com/user-attachments/assets/ad3de654-ae83-477a-a23f-77cc91c0c0fd

- when informant is changed (spouse -> any option except 'someone else') : declration can't be corrected, gets stuck in outbox. - FIXED.

https://github.com/user-attachments/assets/00e07101-645a-4158-9819-70e71d40ffb4

- when informant is changed (spouse -> 'someone else'), informantion are not corrected properly. - FIXED.

https://github.com/user-attachments/assets/d1f9006c-3559-4460-8c7d-b8f35cb2a891
