### ISSUE TITLE
Release "@opencrvs/toolkit" library as an npm package

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#7800]
### Description

We want to move away from the paradigm of countries needing to pull the code changes to get updates and instead allow them to use an "OpenCRVS" framework.

### Dev tasks

- [ ] Create a new package in core repo called `@opencrvs/toolkit`
- [ ] Create a index.ts file inside of it with just one function `export function noop() {}` 
- [ ] Use `yarn link` to link this to your local country config. Verify you can call the function from country config.
- [x] Add a new pipeline "Publish library to npm" to core repository. Use same triggers and version name resolution as [docker image push pipeline](https://github.com/opencrvs/opencrvs-core/blob/develop/.github/workflows/build-images-from-branch.yml) does

**Comment by naftis** [comment]
https://github.com/opencrvs/mosip/blob/main/.github/workflows/npm-publish.yml
I've done something similar for MOSIP repository lately that can be taken example of
