### ISSUE TITLE
'Custom time period' filter not working in mobile view.

### ISSUE THREAD

**Issue by tiri39** [opencrvs/opencrvs-core#7804]
**Bug description:**
In advance search and user audit page, custom date filter is not working; 'no results'/ 'no audits' or sometimes only a few results are shown.

**Steps to reproduce:**
1. Login as registrar.
2. Navigate to Teams tab.
3. Select any user and navigate to the user audit page.
4. Search by choosing a date range from custom date filter. (for ex.: June 2024 - October 2024).
5. Observe the search results in both web and mobile view.

For advance search - 
1. Login as registrar.
2. Navigate to advance search page.
3. Select any date from custom date filter (for ex.: June 2024 - October 2024) for 'date of registration' along with another parameter.
4. Observe the search results in both web and mobile view.

**Actual result:**
Search results are shown properly in web view but in mobile view, it shows - 'no results/ audits to display'

**Expected result:**
Should show results properly both in web and mobile view.

**Screenshot / Recording:**

https://github.com/user-attachments/assets/158d812a-aa15-47c3-a58f-d8ca73dd7f96

**Tested on:** 
https://login.farajaland-qa.opencrvs.org/

**Version:**
V1.5.0

**Comment by jamil314** [comment]
pr: https://github.com/opencrvs/opencrvs-core/pull/7810

Environment with the fix: https://fix-custom-time-period.opencrvs.dev

**Comment by tiri39** [comment]
Fixed.

https://github.com/user-attachments/assets/252f7151-0d40-419e-b498-81cc63dc658e
