### ISSUE TITLE
Un-handled documents Error in microservices

### ISSUE THREAD

**Issue by baarsamo** [opencrvs/opencrvs-core#7886]
**Describe the bug**
I am getting this un-handled error in Kibana in production like in the Documents microservices.

![Image](https://github.com/user-attachments/assets/208fe8c9-3af9-44d1-be10-571dfc988a5a)

this occurs in 1.5.1

**Comment by Zangetsu101** [comment]
Same as https://github.com/opencrvs/opencrvs-core/issues/7589

**Comment by euanmillar** [comment]
@rikukissa looks to me like this should be addressed as a bugfix in certified copies and then applied to a hotfix to suppress the error in 1.6.1.  Certified copies will not be available until 1.7.0. Some kind of script may need to be run to re-create all the certificate PDFs in Minio if the linked issue that @Zangetsu101 mentions is in fact the cause.

**Comment by euanmillar** [comment]
@rikukissa @Zangetsu101  This bug appears to be unique to Somalia's long/short form certificate code. It's likely the hack to show different templates using if/else code in the SVG causes it. The failure happens in workflow's "uploadCertificateAttachmentsToDocumentsStore" function.  I will investigate more but it can be removed from v1.6.1 as the solution will be country related.

**Comment by euanmillar** [comment]
Testing depends on: https://github.com/opencrvs/opencrvs-countryconfig/pull/322
