### ISSUE TITLE
In performance, Registration by status shows 0 when any province is selected.

### ISSUE THREAD

**Issue by onnee04** [opencrvs/opencrvs-core#7892]
**Bug description:**
In performance, Registration by status shows 0 when any province is selected.

**Steps to reproduce:**
1. Login to RA/ local Registrar/National register/ Local system admin/ National System Admin
2. Click Performance
3. Filter any province
4. Observe Registration by status

**Actual result:**
In performance, all value in registration by status shows 0.
**Expected result:**
Should show actual value in registration by status,

**Screenshot/record:**

https://github.com/user-attachments/assets/aa8efdbc-35bc-4a56-8a03-174ea8f0c316

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by jamil314** [comment]
[Live link](https://login.ocrvs-7892.opencrvs.dev)

**Comment by onnee04** [comment]
fixed

https://github.com/user-attachments/assets/ea5fa747-781c-42b8-97fa-f7470123b6e7

**Comment by SyedaAfrida** [comment]
This ticket is tested and fixed
