### ISSUE TITLE
Error When Renaming and Saving Existing Bookmark After Removal

### ISSUE THREAD

**Issue by onnee04** [opencrvs/opencrvs-core#7924]
Bug description:
Error When Renaming and Saving Existing Bookmark After Removal

Steps to reproduce:
1. Login as RA/ Registrar.
2. Click on any saved bookmark.
3. Click on the star.
4. Confirm remove.
5. Again click on the star.
6. Provide name of query.
7. Click on confirm.
8. Observe the toast message.

Actual result:
Can not save as bookmark. Says " Sorry, something went wrong. Please try again" . 

Expected result:
Searched result should be saved with provided bookmark name.

Screen recording:

https://github.com/user-attachments/assets/d1b12825-8eb4-4cd7-9e07-af39eb7756c5

Tested on:

https://register.farajaland-qa.opencrvs.org

**Comment by jamil314** [comment]
https://login.ocrvs-7924.opencrvs.dev/
#8089

**Comment by onnee04** [comment]
Fixed

https://github.com/user-attachments/assets/7ca9ebae-f8f3-49ca-87a9-730b9d63674d
