### ISSUE TITLE
Certified Copies : Incorrect Fee Added in Performance Page When Printing a Certificate a Second Time Using a New Template

### ISSUE THREAD

**Issue by tiri39** [opencrvs/opencrvs-core#8016]
**Bug description:**
If any certificate (that was printed before) is printed with a new template, the fee for previous template is added while printing the second time.
For example, a certificate was printed with 'birth certificate' template at the first time. Then if we try to print it again with another template (birth certificate certified copy) , incorrect fee ( fee for first template) is added to total fee.

**Steps to reproduce:**
1. Login as RA/ local registrar/ national registrar.
2. Navigate to 'Ready to Print' workqueue.
3. Print any declaration with any template.
4. Search that declaration and download it again.
5. Print the declaration with a different template this time.

**Actual result:**
Same certification fee is added for both templates.

**Expected result:**
Correct certification fee (according to the template) should be added each time.

**Recording:**
for birth: 

https://github.com/user-attachments/assets/4abd9487-e1ab-4808-beb6-fbac45426568

for death:

https://github.com/user-attachments/assets/e86a7a99-5858-4b31-829e-05bef1ebd0a8

**Tested on:**
https://ocrvs-7584.opencrvs.dev/

**Comment by tareq89** [comment]
There is a chance that this issue is linked to this issue.
https://github.com/opencrvs/opencrvs-core/issues/7793

**Comment by tiri39** [comment]
Fixed.

https://github.com/user-attachments/assets/b74612ff-743e-451a-a67e-94943ed86674
