### ISSUE TITLE
As a user, I want to search for a record using the UIN/VID of the child created on registration

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#8064]
## Description
- Allows the created UIN/VID to be searchable in OpenCRVS to retrieve the birth record

## ACs
GIVEN a birth was registered in OpenCRVS and a UIN created for the child
WHEN a user searches for the record
THEN the VID? UIN? can be used to search when the filet ID is selected

## Dev tasks

We currently use `BIRTH_CONFIGURABLE_IDENTIFIER` in @opencrvs/mosip repository and opencrvs-countryconfig-mosip certificate to show the NID.

- [x] Investigate, whether this identifier could be configured to be able to be search for. Consider that events v2 don't have a hard-coded set of NATIONAL_ID, MOSIP_VID, MOSIP_PSUT_TOKEN etc, we'll likely anyway need something configurable.
- [x] If it's very difficult for Events v1: consider if we should use the NATIONAL_ID identifier instead when doing `confirmRegistration` on @opencrvs/mosip repository

**Comment by naftis** [comment]
Decided to use the `NATIONAL_ID` identifier as it doesn't need core changes. The searching mechanism will anyway change for events v2, so changing the way identifiers are searched for V1 didn't seem like a good idea.

@rikukissa this has already been discussed, but flagging that in Events v2 searching with a hidden form field / JSON field must be possible.

**Comment by rikukissa** [comment]
Thanks, I'll make a note of that. It is aligned with the current design

**Comment by Erusha-Raju** [comment]
Note re scope of this ticket: It was decided to use the NATIONAL_ID identifier as it doesn't need core changes. The searching mechanism will anyway change for events v2, so changing the way identifiers are searched for V1 didn't seem like a good idea.
