### ISSUE TITLE
Certified Copies : Wrong error message shown when certificate type is not selected in printing flow

### ISSUE THREAD

**Issue by tiri39** [opencrvs/opencrvs-core#8118]
**Bug Description:**
In certificate printing flow, wrong error message is shown when certificate template is not selected.

**Steps to reproduce:**

1. Login as RA/local reg/ national reg.
2. Navigate to ready to print workqueue.
3. Download any record and click on 'Action' -> 'Print Certified Copy'.
4. In 'Certify record' page, DON'T select any template for certificate printing.
5. Select any option for collector.
6. Click 'Continue'.

**Actural Result:**
Shows error message : "Please select certificate type".
![Image](https://github.com/user-attachments/assets/cfd79993-68a5-4f77-8646-d7c5bd8a6689)

**Expected Result:**
According to design, should show error message : "Required for certification", below the template dropdown. 
![Image](https://github.com/user-attachments/assets/7fcd0a49-d3d1-4123-ac96-986fceeb46f6)

**Tested on:**
https://ocrvs-7584.opencrvs.dev/

**Version :** 
v1.7.0

**Comment by tareq89** [comment]
technically, based on the current design, validation error as shown here is not achievable.
![Image](https://github.com/user-attachments/assets/6430ee74-cfe2-49b7-8c42-41d2fb3ce44c)



any ideas @Zangetsu101 @rikukissa ?

**Comment by Zangetsu101** [comment]
We were able to make use of the pattern from the `RegisterForm`

**Comment by tiri39** [comment]
Fixed.

![Image](https://github.com/user-attachments/assets/b2a6ec88-1270-4ccd-bbb2-42365232b2d7)
![Image](https://github.com/user-attachments/assets/76f036b3-03cd-4103-9a63-12cc50033797)
![Image](https://github.com/user-attachments/assets/9d7e4fa0-d666-48d9-847c-3f25de7a9212)
