### ISSUE TITLE
As a system user completing a declaration I want to authenticate individuals and pre-populate the form (online) in order to ensure integrity of data across CR + ID

### ISSUE THREAD

**Issue by marcio-opencrvs** [opencrvs/opencrvs-core#8207]
- Reusable component that can be used throughout (any vital event) declaration (or other) form (when online only)
- If the individual is not enrolled in the ID system, the user can complete the form manually
- If individual is enrolled for ID, user enters their UIN/VID (e.g. from card, QR code scan)
- User clicks “authenticate” and eSignet interface appears, offering multiple authentication mechanisms:
    - OTP to be sent to the individual’s phone by SMS and then entered by system user
    - OTP to be sent to the individual by email and then entered by system user
    - Biometrics scan using face (using phone / tablet camera)
    - Biometrics scan using fingerprint (using plug and play L1 device)

- If authentication fails, user is notified and returned to OpenCRVS form to allow manual entry

- If authentication successful:
    - user is prompted with a set of biographic data that are available to pre-populate the form (this data set is configurable)
    - User “consents” to the data being used to pre-populate the form*
    - All form fields available for pre-population are filled (mapping of biographic data from MOSIP to OpenCRVS fields)
    - Presents “ID authenticated” to the user

- Pre-populated data is editable, in which case the authentication status is removed
- It should be possible to make fields / supporting documents conditional based on the authentication status. 
- Once form is submitted and being reviewed the authentication status is viewable. As above, edits to pre-populated data are possible, meaning the authentication status is removed

*Note: The method of consent capture is determined by the implementing country. It can take various forms, such as obtaining a signature on a form and an agent selecting on the resident's behalf, or the agent reading out the consent terms and receiving verbal approval.

**Comment by jpye-finch** [comment]
@marcio-opencrvs this Fgma issue was split into #7939 and #8062

**Comment by marcio-opencrvs** [comment]
@eduffus FYI, translating from your initial FigJam requirements.
This ticket has been split into two other tickets:
- https://github.com/opencrvs/opencrvs-core/issues/7939
- https://github.com/opencrvs/opencrvs-core/issues/8062.

Therefore, I'm closing this ticket to avoid duplicates.
