### ISSUE TITLE
Check console and remove any warnings or errors

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#991]
![image](https://user-images.githubusercontent.com/1206987/62459123-3e960d80-b787-11e9-9ab5-8fd88b32b561.png)

**Comment by Zangetsu101** [comment]
We weren't able to reproduce it

**Comment by SyedaAfrida** [comment]
The console error mentioned in this ticket is not appearing any more. But sometimes these following console error is found in the QA environment. This is inconsistent
![console](https://user-images.githubusercontent.com/94350336/179687298-44a4bca7-0a83-4097-abe3-f5211e523142.png)

**Comment by rikukissa** [comment]
That's great! If the errors are not appearing anymore, I think it's fine to close this ticket. We can open new ones if they resurface.

**Comment by naftis** [comment]
These were looked into in https://github.com/opencrvs/opencrvs-core/pull/5125
